### PR TITLE
Added icons for Kubernetes Node Metrics component

### PR DESCRIPTION
**Pull request by nwanduka**
**Notes for Reviewers**

There's no specific icon for the node metrics component as can be seen in the image below image

So I came up with a design for it. Thoughts?

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by MUzairS15 — COMMENTED** [review]
You might need to update the Integrations Spreadsheet to have this icon in use for `NodeMetrics` component.

**Comment by nwanduka** [comment]
> You might need to update the Integrations Spreadsheet to have this icon in use for `NodeMetrics` component.

Yes Uzair, Lee has mentioned this to me. I need some clarifications.
I've gone through the spreadsheet and in the Kubernetes section I don't find Node Metrics listed under the "component" column.
image

So when you say to update the spreadsheet, do you mean I should add this new component I've designed to the list, then in the "logo URL" column I'll paste the github link to the icon design, just like the others in the spreadsheet?

**Comment by leecalcote** [comment]
@nwanduka did we get you squared away on today's meeting?

**Comment by nwanduka** [comment]
> @nwanduka did we get you squared away on today's meeting?

Yes, you did @leecalcote. Thanks a lot. Found out I don't have edit access so I can't add an entry for the node metrics component. Maybe someone with edit access could add it. For subsequent designs, I'll select a component that is already listed in the spreadsheet then add the svg code as a comment and have a maintainer approve it.

**Comment by leecalcote** [comment]
Edit access is an undesirable liability - something that you really, really don't want.

**Comment by leecalcote** [comment]
Yes, a comment in the sheet works well. 👍  // @ritiksaxena124

**Comment by leecalcote** [comment]
> Edit access is an undesirable liability - something that you really, really don't want.

I don't want it either. _ugh_

**Comment by ritiksaxena124** [comment]
I have added the SVG in the spreadsheet 👍

**Comment by nwanduka** [comment]
Thank you @ritiksaxena124. So, this is ready to be merged?

**Pull request merged**
