### PR TITLE
FIXED: [mesheryctl] `mesheryctl system check` checks wrong platform

### LINKED ISSUE #8246: [mesheryctl] mesheryctl system check checks wrong platform
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior

In the following example, running `mesheryctl system check` to check the health of an active Meshery deployment results in Docker being checked when Meshery is deployed on Kubernetes as per the current config context
```
mesheryctl system check

Docker
--------------
Error: Meshery is not running locally, please ensure that the appropriate Docker context is selected for Meshery endpoint: https://playground.meshery.io/. To list all configured contexts use `docker context ls`: exit status 1
➜  meshery git:(master) mesheryctl system context view

Current Context: playground

endpoint: https://playground.meshery.io/
token: default
token-location: auth.json
platform: kubernetes
components:
- meshery-istio
- meshery-linkerd
- meshery-consul
- meshery-nsm
- meshery-kuma
- meshery-osm
- meshery-traefik-mesh
- meshery-nginx-sm
channel: stable
version: latest
provider: Meshery
```

#### Desired Behavior

`mesheryctl system check` should check the correct platform to determine the health of Meshery. 

#### Environment

- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- 📺 [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- ⌨️ [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- ⌨️ [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by zakisk**
**Notes for Reviewers**

This PR fixes #8246

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ✓] Yes, I signed my commits.
- [ ✓] Yes, I tested against bug statement.

### CODE REVIEW

**Review by leecalcote — APPROVED** [review]
LGTM

**Comment by leecalcote** [comment]
@zakisk, @Philip-21 a bit of help needed here - https://github.com/meshery/meshery/actions/runs/5657521386/job/15326944619?pr=8272#step:5:31

**Comment by Philip-21** [comment]
@leecalcote it seems to be a unit test error , i observed most of this error in pr's  after ci checks are taken place . The integration tests  always passed but the Unit tests fails.
It seems one has to check the `TestPatternList/Fetch_Filter_List`  to see if the response outputs are generated successfully
Its one of the unit test files written in the pattern package

**Comment by zakisk** [comment]
@leecalcote I checked [this error](https://github.com/meshery/meshery/actions/runs/5657521386/job/15326944619?pr=8272#step:5:31) as @Philip-21 suggested to check `TestPatternList/Fetch_Filter_List`, the error is [api response test data](https://github.com/meshery/meshery/blob/master/mesheryctl/internal/cli/root/filter/fixtures/list.filter.api.response.golden) contains WASM binary value (I guessed it) and when it is being unmarsheled in [MesheryFilter.FilterFile](https://github.com/meshery/meshery/blob/2936f0d8d4f4a584fb2c1921d62ba16970d42936/server/models/meshery_filter.go#L16) field it is causing `illegal base64 data at input byte 4` error.
at the moment [MesheryFilter.FilterFile](https://github.com/meshery/meshery/blob/2936f0d8d4f4a584fb2c1921d62ba16970d42936/server/models/meshery_filter.go#L16) field is of type `[]byte`. changing `[]byte` to [json.RawMessage](https://pkg.go.dev/encoding/json#RawMessage) type will solve the problem. I've tested it and the test had passed, if you both @leecalcote @Philip-21 agree on this we can move further.

**Comment by Philip-21** [comment]
Yh since the  [filter Payload](https://github.com/meshery/meshery/blob/2936f0d8d4f4a584fb2c1921d62ba16970d42936/server/handlers/meshery_filter_handler.go#L167) has been marshelled to json you can use `json.RawMessage` to convert it to raw json
The same will be implemented for [Pattern Payload](https://github.com/meshery/meshery/blob/2936f0d8d4f4a584fb2c1921d62ba16970d42936/server/handlers/meshery_pattern_handler.go#L214)

**Comment by leecalcote** [comment]
Thank you, gents. 👍

**Pull request merged**
