### PR TITLE
[mesheryctl] Fix for #1651: Allow users to pass in custom meshery server url instead of using the hardcoded localhost

### PR DESCRIPTION
**Pull request by anirudhjain75**

### CODE REVIEW

**Comment by anirudhjain75** [comment]
@leecalcote one of the two suggestion you had on improving the cmd

**Comment by anirudhjain75** [comment]
The Issue page is  #1651

**Review by leecalcote — COMMENTED** [review]
This is a good flag in concept. Ultimately, mesheryctl needs a global flag and/or a global configuration for the CLI.

We have a global configuration file option for `mesheryctlconfig` today, which is an ideal way to address this holistically.

This global configuration file is an incomplete implementation in that we need to define what the actual structure of this config file looks like.

Can we direct our efforts into this global view before implementing a flag for a specific command?

**Comment by leecalcote** [comment]
Reference on `mesheryctlconfig` - https://github.com/layer5io/meshery/issues/1083

**Pull request closed without merging**
