### PR TITLE
Changed file name from Filters to MesheryFilters

### LINKED ISSUE #3174: [UI] Change the file name of Filters to MesheryFilters
#### Current Behavior
We are having two files with the same name Filters and filters in the UI which may cause confusion. 

#### Desired Behavior
Change the file name of Filters to MesheryFilters so they can be distinguished easily.

#### Implementation
Task - To change the file name of Filters.js to MesheryFilters.js
- Inside the Filter.js,filter.js, navigator.js (the filter under the configuration)
- In the above files update the import MesheryFilters from "../../components/Filters"; accordingly.

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

### PR DESCRIPTION
**Pull request by ahcodes**
**Description**

This PR fixes #3174 which is, changing the file name of Filters to MesheryFilters in UI.

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Chadha93** [comment]
@ahcodes good work, Could you please sign your commit ( do follow the contribution.md ), then we are ready to go.

**Comment by ahcodes** [comment]
@Chadha93 I amended my commit. https://github.com/layer5io/meshery/pull/3195/commits/612d8e2155d5a5cee5f952f0540ac34217c9738b 

Let me know if anything else is needed from my end.

**Comment by Chadha93** [comment]
> @Chadha93 I amended my commit. [612d8e2](https://github.com/layer5io/meshery/commit/612d8e2155d5a5cee5f952f0540ac34217c9738b)
> 
> Let me know if anything else is needed from my end.

@ahcodes Great, please do edit the pr description (write about the change and checkmark I sign my commit )

**Comment by ahcodes** [comment]
> @ahcodes Great, please do edit the pr description (write about the change and checkmark I sign my commit ) in order to pass the DCO

Done.

**Review by Chadha93 — APPROVED** [review]

**Comment by leecalcote** [comment]
FYI - instructions specifically to this PR for commit amending - https://github.com/layer5io/meshery/pull/3195/checks?check_run_id=2813172291

**Comment by Chadha93** [comment]
> FYI - instructions specifically to this PR for commit amending - https://github.com/layer5io/meshery/pull/3195/checks?check_run_id=2813172291

@leecalcote Thanks, @ahcodes as mentioned please do amend your commit following the above.

**Review by Chadha93 — CHANGES_REQUESTED** [review]
Please do amend the `import `path inside the Filter, filter, Navigator accordingly of the new file name(otherwise all paths will break)  and amend the signoff accordingly.

**Comment by ahcodes** [comment]
@Chadha93 @leecalcote Sorry, guys, but I'm not sure if I am getting what I'm supposed to do here?

**Comment by Chadha93** [comment]
> @Chadha93 @leecalcote Sorry, guys, but I'm not sure if I am getting what I'm supposed to do here?

No problem @ahcodes it's good you asked, let me brief it.
Task - To change the file name of Filters.js to MesheryFilters.js
        - Inside the Filter.js,filter.js, navigator.js (the filter under the configuration) 
        - In the above files update the `import MesheryFilters from "../../components/Filters"`; accordingly.

**Comment by ahcodes** [comment]
> No problem @ahcodes it's good you asked, let me brief it.
> Task - To change the file name of Filters.js to MesheryFilters.js
> - Inside the Filter.js,filter.js, navigator.js (the filter under the configuration)
> - In the above files update the import MesheryFilters from "../../components/Filters"; accordingly.

@Chadha93 Thanks, I really appreciate your help! My branch is however, 44 commits behind layer5io:master, should I git pull the changes before pushing my amended commit and the new commits (with the quoted changes)?

**Comment by Chadha93** [comment]
> > No problem @ahcodes it's good you asked, let me brief it.
> > Task - To change the file name of Filters.js to MesheryFilters.js
> > 
> > * Inside the Filter.js,filter.js, navigator.js (the filter under the configuration)
> > * In the above files update the import MesheryFilters from "../../components/Filters"; accordingly.
> 
> @Chadha93 Thanks, I really appreciate your help! My branch is however, 44 commits behind layer5io:master, should I git pull the changes before pushing my amended commit and the new commits (with the quoted changes)?

Sure

**Comment by adithyaakrishna** [comment]
@ahcodes Can you please check the DCO thing? Because it's failing 😶

**Comment by adithyaakrishna** [comment]
@Chadha93 Does only one file need to be changed? Bc if there are any other files which has used the Filename while importing it will render `ModuleNotFound` error

**Comment by Chadha93** [comment]
> @Chadha93 Does only one file need to be changed? Bc if there are any other files which has used the Filename while importing it will render `ModuleNotFound` error

Yep, you are right @adithyaakrishna I have mentioned it already about changing the import accordingly in my previous comments.

**Comment by ahcodes** [comment]
> 
> 
> @ahcodes Can you please check the DCO thing? Because it's failing no_mouth

Yeah, sorry for the delay, it's just that I'm unable to checkout the PR to fix the DCO issue.
pr3195

It says "use arrow to move" and yet the command automatically exits before I can do it! I am still new to this whole DCO thing so would really appreciate some input as to what I'm supposed to do here.

**Comment by leecalcote** [comment]
@ahcodes executing these commands should take care of the issue - https://github.com/layer5io/meshery/pull/3195/checks?check_run_id=2851422683 

good of you to hang in there. You’re in good hands with @Chadha93 and @adithyaakrishna.

**Comment by ahcodes** [comment]
> 
> 
> @ahcodes executing these commands should take care of the issue - https://github.com/layer5io/meshery/pull/3195/checks?check_run_id=2851422683
> 
> good of you to hang in there. You’re in good hands with @Chadha93 and @adithyaakrishna.

I executed those commands (despite the problem I mentioned in https://github.com/layer5io/meshery/pull/3195#issuecomment-864427180) and now there's an error? 

image

**Comment by Chadha93** [comment]
> > @ahcodes executing these commands should take care of the issue - https://github.com/layer5io/meshery/pull/3195/checks?check_run_id=2851422683
> > good of you to hang in there. You’re in good hands with @Chadha93 and @adithyaakrishna.
> 
> I executed those commands (despite the problem I mentioned in [#3195 (comment)](https://github.com/layer5io/meshery/pull/3195#issuecomment-864427180)) and now there's an error? Apparently, it's because of the DCO and I am just lost here on what to do.
> 
> image

You should use your branch to push, don't use master to push. Just a random check, have you been able to build meshery locally ? Have you joined the slack channel I provided link earlier in the above comments ?

**Comment by leecalcote** [comment]
I’m manually overriding the dco requirement. Do join the community Slack work space, if you haven’t already. In the future, another solution is to redo you commit, considering the size of the change.

**Comment by adithyaakrishna** [comment]
@ahcodes You can update your branch from here itself, 
image
After this, checkout to master and run git pull origin master

**Comment by adithyaakrishna** [comment]
> > @Chadha93 @leecalcote Sorry, guys, but I'm not sure if I am getting what I'm supposed to do here?
> 
> No problem @ahcodes it's good you asked, let me brief it.
> Task - To change the file name of Filters.js to MesheryFilters.js
> - Inside the Filter.js,filter.js, navigator.js (the filter under the configuration)
> - In the above files update the `import MesheryFilters from "../../components/Filters"`; accordingly.

@ahcodes once you are done with that, update this and then your PR would be god to go 🎉

**Comment by leecalcote** [comment]
Following up... @ahcodes, ping when you have an update ready for review.

**Comment by ahcodes** [comment]
> > I executed those commands (despite the problem I mentioned in [#3195 (comment)](https://github.com/layer5io/meshery/pull/3195#issuecomment-864427180)) and now there's an error? Apparently, it's because of the DCO and I am just lost here on what to do.
> > image
> 
> You should use your branch to push, don't use master to push. Just a random check, have you been able to build meshery locally ? Have you joined the slack channel I provided link earlier in the above comments ?

Well, master was the branch I used to push from the beginning (if I'm not mistaken). 
And yes, I have a local folder to hold a copy of the Meshery repo locally. 
I also joined the Slack channel weeks ago.

**Comment by ahcodes** [comment]
> 
> 
> I’m manually overriding the dco requirement. Do join the community Slack work space, if you haven’t already. In the future, another solution is to redo you commit, considering the size of the change.

Thanks, I am already in the Slack workspace. And yeah, I would like to redo my commit and attempt this thing from the beginning if it's possible.

**Comment by leecalcote** [comment]
> > I’m manually overriding the dco requirement. Do join the community Slack work space, if you haven’t already. In the future, another solution is to redo you commit, considering the size of the change.
> 
> Thanks, I am already in the Slack workspace. And yeah, I would like to redo my commit and attempt this thing from the beginning if it's possible.

Sounds great. Yes, please move forward at-will.

**Comment by navendu-pottekkat** [comment]
@Chadha93 @ahcodes Should we close this PR?

**Comment by Chadha93** [comment]
@navendu-pottekkat Yes, I think. I will update this thing in the future if much is required. Thanks, @ahcodes you can find some more good first issues to continue.

**Comment by navendu-pottekkat** [comment]
@Chadha93 Okay, thank you. Closing this PR.

**Comment by ahcodes** [comment]
@Chad

> 
> 
> @navendu-pottekkat Yes, I think. I will update this thing in the future if much is required. Thanks, @ahcodes you can find some more good first issues to continue.

Yeah, no worries. I gotta learn a bit more before coming back!

**Pull request closed without merging**
