### PR TITLE
[README] Updated steps to access community drive

### LINKED ISSUE #2858: [README] Update README Community Section
#### Description
The Community section in the README says "Access the Community Drive". There is a new procedure of having this automated based on the individual filling in a [community member form](https://layer5.io/newcomer)
#### Expected Behavior
Update "Access Community Drive" to "To Access Community Drive, fill Community Member Form"

#### Screenshots/Logs
img
--

**Resources**
Refer to the [Contributing guide](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#contributing)

#### Environment:
- Meshery Version: 
- Kubernetes Version: 
- Host OS:
- Browser:

### PR DESCRIPTION
**Pull request by NeelParihar**
Signed-off-by: NeelParihar <neelparihar599@gmail.com>

**Description**
Updated the steps to access community drive from "Access Community Drive" to "To Access Community Drive, fill Community Member Form"

This PR fixes #2858

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by Ruth-ikegah — APPROVED** [review]
Thanks for sending a PR, I just noticed something, please @NeelParihar can you add 'the' to 'fill community member form' so it will be 'fill the community member form'. My apologies, I realize there was a mistake on the issue of not having 'the'.

This sounds grammatically correct!

**Review by Ruth-ikegah — CHANGES_REQUESTED** [review]
Thanks for sending a PR, I just noticed something, please @NeelParihar can you add 'the' to 'fill community member form' so it will be 'fill the community member form'. My apologies, I realize there was a mistake on the issue of not having 'the'.

This sounds grammatically correct!

**Comment by NeelParihar** [comment]
Hey @Ruth-ikegah, thank you for reviewing the pr and suggesting changes. I have updated it, please check it if they are done correctly

**Review by leecalcote — APPROVED** [review]
Good work, team!

**Pull request merged**
