### PR TITLE
add dark mode styles to table elements and head

### LINKED ISSUE #7049: [Docs]Dark mode issue in Error code page.
#### Current State

Screenshot from 2023-02-10 20-51-02

#### Desired State

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by rinkuhasija**
**Notes for Reviewers**

This PR fixes #7049 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit c1240a780c8259c2bab4bfbfa189e98f8874281d at: https://63f427ec589243699604704b--meshery-docs-preview.netlify.app

**Comment by leecalcote** [comment]
@avi88 take a look?

**Comment by leecalcote** [comment]
@tinniaru3005 have a look-see?

**Review by tinniaru3005 — COMMENTED** [review]
LGTM. But I cannot see the colour codes like yellow colour for an alert or red colour for a Fatal. Was it discussed to remove them? 👀

**Comment by l5io** [comment]
🚀 Preview for commit 2bc305db52633c1bc1714bd664abfb6869554177 at: https://63f4931737dfa13a5957f6a2--meshery-docs-preview.netlify.app

**Review by tinniaru3005 — APPROVED** [review]
LGTM! :)

**Review by Chadha93 — APPROVED** [review]
LGTM

**Comment by Chadha93** [comment]
Yay @rinkuhasija :balloon:

**Comment by Avi-88** [comment]
> @avi88 take a look?

Sorry for the delayed response , it didnt notify me of this mention. Good work @rinkuhasija 🙌 and congrats 🎉

**Pull request merged**
