### PR TITLE
fix table header background color on click

### LINKED ISSUE #7332: [Docs]Table headers are not visible when clicked in dark mode
#### Current State
When clicked in table headers (as we can see in the video) they are not visible under the dark mode in https://docs.meshery.io/project/compatibility-matrix#integration-tests

https://user-images.githubusercontent.com/90546692/224314171-2a6a32e3-4d38-4ca7-9c36-be31ac89bb2e.mp4

#### Desired State
The text should be visible in dark mode. Remove the white background when clicked

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by rinkuhasija**
**Notes for Reviewers**

This PR fixes #7332 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit e8fbbf1429b27e5449939a64bd7a4b03400589d8 at: https://640b392044ac810c7db66483--meshery-docs-preview.netlify.app

**Comment by rinkuhasija** [comment]
@Chadha93 Can you review it please whenever possible ?

**Review by hirentimbadiya — COMMENTED** [review]
I saw your changes and also opended preview site and it Looks Good to me although @Chadha93 , @leecalcote   you can re-review this PR.

**Comment by leecalcote** [comment]
Thank you for offering review, @hirentimbadiya. This helps. 

Looking good, @rinkuhasija.

**Pull request merged**
