### PR TITLE
docker extension empty state fixed 

### LINKED ISSUE #5658: [Docker Extension] Empty State needed for “Deploy a Service Mesh”
#### Current Behavior
When no Meshery Adapters are present, the “Deploy a Service Mesh” section is empty, leaving users potentially confused.

Screen Shot 2022-06-22 at 9 57 58 AM

#### Desired Behavior
Show an empty state message, providing information to the user.

#### Implementation
See https://github.com/meshery/meshery/tree/master/install/docker-extension

#### Mockups
Show an empty state message, like:

```
<h4>No Meshery Adapters Detected</h4>
<i>Connect one or more Meshery adapters to manage service meshes</i>
```

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by harkiratsm**
Signed-off-by: harkiratsm <multaniharry714@gmail.com>

**Description**

This PR fixes #5658 

**Notes for Reviewers**

image

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by warunicorn19 — COMMENTED** [review]
@harkiratsm did you get a chance to check this out locally on your docker-desktop?? I have a feeling even if one adapter fails to show up none of the adapters will show with this approach. // @sudo-NithishKarthik 

@leecalcote could you please provide better text here.

**Comment by warunicorn19** [comment]
head's up: merge conflict

**Comment by leecalcote** [comment]
Hey! Just because you said it first doesn't mean that I'm copying you.

**Comment by leecalcote** [comment]
> @harkiratsm did you get a chance to check this out locally on your docker-desktop?? I have a feeling even if one adapter fails to show up none of the adapters will show with this approach. // @sudo-NithishKarthik
> 
> @leecalcote could you please provide better text here.

Oh, right. In the Docker Extension deployment, it might be an all-or-nothing with respect to adapters running and the extension itself, in turn, running.

As long as the text included in the empty state message is responsive, it’ll work as currently phrased.

**Comment by harkiratsm** [comment]
@warunicorn19 @leecalcote Thanks ✨

**Comment by warunicorn19** [comment]
@leecalcote @sudo-NithishKarthik could one of you please check this PR out locally? For me, it's not working but that might be unrelated to this PR and just be something wrong with my system. 
Screenshot 2022-06-28 at 4 52 11 PM
I get this even after I have all adapters running.

**Comment by leecalcote** [comment]
@harkiratsm will you be on the Meshery Dev call this week?

**Comment by harkiratsm** [comment]
@leecalcote Sure 😄 .

**Review by warunicorn19 — APPROVED** [review]
LGTM🎉

**Review by leecalcote — APPROVED** [review]
Thanks for today's presentation, @harkiratsm 👏 Good stuff

**Pull request merged**
