### PR TITLE
Fix 11688 : Added tooltip for add buttons

### LINKED ISSUE #11688: [UI] Add tooltip to the upload/import button on playground meshery
### Current Behavior
Tooltip is missing  when hovering over upload/import button. 

### Desired Behavior
It should display tooltip when mouse is hovered over on it.

### Screenshots/Logs
https://playground.meshery.io/configuration/designs
image

### Environment

- Browser: Chrome
- Host OS: Mac
- Meshery Client Version: stable-v

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by helloworld-chhanda**
**Notes for Reviewers**

This PR fixes #11688
- Added tooltip for 2 buttons
Fixed: https://github.com/meshery/meshery/issues/11688

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
@amitamrutiya your review, would be great.

**Review by amitamrutiya — APPROVED** [review]

**Comment by amitamrutiya** [comment]
Hey @helloworld-chhanda, you did an excellent job—thanks for that! But next time, please wait for the issue to be assigned to you before making a PR.

**Comment by helloworld-chhanda** [comment]
> Hey @helloworld-chhanda, you did an excellent job—thanks for that! But next time, please wait for the issue to be assigned to you before making a PR.

Sure, I will wait. Thank you for your quick approval.

**Comment by Ashparshp** [comment]
@helloworld-chhanda. let's discuss this PR during the Meshery dev meeting call, if you would. Please add it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit?usp=drivesdk).

**Review by leecalcote — APPROVED** [review]

**Pull request merged**
