### PR TITLE
Fix: main layout & footer links

### LINKED ISSUE #10705: [Docs] Responsiveness issues
### Current State
https://docs.meshery.io/ currently in moblie view : 

     

it needs to be made responsive in smaller screen.

There were changes made to css recently, refer: https://github.com/meshery/meshery/commit/f660ca3c2e16795f4ec2fa977b8cfd2ef03a6da1

### Desired State

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by abhishekmmgn**
**Notes for Reviewers**

This PR fixes #10705

- padding in small-width devices
- ghost links in footer

Before:
image
image

After:
image

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit d32a36ed387678a3d71c5e821accc844cde19336 at: https://66169dff10665742217f327e--meshery-docs-preview.netlify.app

**Comment by abhishekmmgn** [comment]
@vishalvivekm have a look at the PR.

**Comment by leecalcote** [comment]
Resyncing with master

**Comment by l5io** [comment]
🚀 Preview for commit ca53d707676aa2bc0a4eb6df93103fcb82371abf at: https://6616f3d1743fc944780d8b06--meshery-docs-preview.netlify.app

**Comment by leecalcote** [comment]
This overlap is not ideal.
Screenshot 2024-04-10 at 10 43 41 PM

**Comment by leecalcote** [comment]
What is the difference / improvement in moving from small-hide class to the other class?

**Comment by abhishekmmgn** [comment]
We are using <span> to get a tooltip-like effect when hovering over the social links icons.
This has not been achieved perfectly in the desktop and it was hidden in the small-width devices. On the desktop, it resulted in unwanted links. The small-hide class is being used to hide those spans on small-width devices.
I changed the logic to: if hover over icons, then show the tooltip.

https://github.com/meshery/meshery/assets/107319349/6886eb00-0fe5-4a0c-8297-abe307ab6e7f

**Comment by leecalcote** [comment]
@abhishekmmgn oh, I see now, regarding the social icons and tooltips. Thank you very much for this explanation.

**Comment by l5io** [comment]
🚀 Preview for commit 6725d7aa31a1d4017d98e85a4333e2914790e3dd at: https://66176f778e4b1f3a26c7f7d5--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit d5d1262db422f949e7dc0fdd3e123693275421c7 at: https://66177397eca2303aac25881a--meshery-docs-preview.netlify.app

**Pull request closed without merging**
