### PR TITLE
[UI] Custom design for widget - updown

### LINKED ISSUE #6006: [UI] Design for replica set field in RJSF
#### Current Behavior

Currently the replica set field in RJSF, is not good looking by UI perspective.

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by harkiratsm**
Signed-off-by: harkiratsm <multaniharry714@gmail.com>

**Description**

This PR fixes #6006

**Notes for Reviewers**

[Screencast from 14-08-22 10:54:28 AM IST.webm](https://user-images.githubusercontent.com/71957674/184523908-73428951-cfbb-469c-8ea3-140c5dfc36ae.webm)

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Review by Chadha93 — COMMENTED** [review]
@harkiratsm This is great you have made the fastest iteration/progress here in the RJSF area :1st_place_medal:

**Comment by Chadha93** [comment]
@harkiratsm Could you please change the up-down widget UI according to the slider mockup provided in this issue description? 
https://github.com/meshery/meshery/issues/4937

**Comment by harkiratsm** [comment]
@leecalcote any suggestions

**Review by warunicorn19 — COMMENTED** [review]
I think the widget can get a little smaller, current size looks a little too big for the form. And for what @Chadha93 said, I think that slider was made for "percent" and "percentage" fields, replicas are of type "integer" I don't think there's a need for the slider here.

**Review by leecalcote — CHANGES_REQUESTED** [review]
Let's simply reduce the size of the values allowed in the existing component and see about having the replicas field in a split column in the form (given that it will be small enough to fit on one side).

**Comment by leecalcote** [comment]
@harkiratsm right. Let’s proceed with the statement in my last comment.

**Pull request closed without merging**
