### PR TITLE
Reduced code duplication in handling API calls

### PR DESCRIPTION
**Pull request by MUzairS15**
**Description**
Reduced code duplication in handling failed API calls

**Notes for Reviewers**
Dependent PR for #4956 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by MUzairS15** [comment]
@leecalcote , @Abhishek-kumar09 , @sudo-NithishKarthik 
Pls review

**Review by bariqhibat — COMMENTED** [review]
I don't think this is a better approach, but it's good that we centralize the error handling. Instead, it'd be good if we centralize the API calls and handle error there

**Review by Abhishek-kumar09 — COMMENTED** [review]
This is not looking good, considering the fact that there has been increased number of functional arguments and hence less readable code. HOF can be a choice, you can also use a custom hook comprised of the `useReducer` and `useContext` hooks. 

I think we can hold off this for some time. I will be providing you more information soon.

**Comment by MUzairS15** [comment]
Okay, then for #4956, to check for server response should I add check logic in every error handler or wait for https://github.com/meshery/meshery/pull/4979#pullrequestreview-860952725.

@bariqhibat @Abhishek-kumar09

**Comment by Abhishek-kumar09** [comment]
> Okay, then for #4956, to check for server response should I add check logic in every error handler or wait for #4979 (review).

Add it at one or two places per say it will act as a place for the experimentation of the behaviour. we can takeover from there after that.

**Comment by MUzairS15** [comment]
Ok, have already added for performance page, will do the requested changes.
 let's keep it for the Performance page only, will work?

**Comment by leecalcote** [comment]
heads-up: @sudo-NithishKarthik is out sick for a couple days.

**Comment by leecalcote** [comment]
@MUzairS15 a couple of merge conflicts have arisen.

**Comment by MUzairS15** [comment]
> @MUzairS15 a couple of merge conflicts have arisen.

Yes, will fix those, but since a different approach is considered and as told in 
> I think we can hold off this for some time. I will be providing you more information soon.

Will update this branch when finally refactoring starts.

**Comment by sudo-NithishKarthik** [comment]
Let us not spend too much in here now. We have all this set up properly in our [ui-refactor branch](https://github.com/meshery/meshery/tree/meshery-ui-restructuring/ui). All the API calls for each feature are put in [helpers.js](https://github.com/meshery/meshery/blob/meshery-ui-restructuring/ui/features/mesheryEnvironment/helpers.js).  
It is not worth our time to try and make the current code better (which is going to be a huge task) as we are just going to switch to the new ui later.

**Comment by sudo-NithishKarthik** [comment]
It is really good that you have taken this initiative @MUzairS15 , but to ensure that your efforts don't go waste, let's not think about improving it further. Once add the changes that are necessary for #4956 to get through. I would encourage you to look into the ui-refactoring branch and explore ways to improve it.

**Pull request closed without merging**
