### PR TITLE
[UI] RJSF textfield enhancement

### LINKED ISSUE #4812: [UI] Consolidate text input form field labels into placeholders
#### Current Behavior
Screen Shot 2021-12-22 at 1 24 39 PM

#### Desired Behavior
Screen Shot 2021-12-22 at 1 24 58 PM

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by Chadha93**
Signed-off-by: Gaurav Chadha <gauravchadha1676@gmail.com>

**Description**
Consolidates text input form field labels into placeholders

This PR fixes #4812 

**Notes for Reviewers**

https://user-images.githubusercontent.com/65453826/147206953-c2e89166-3173-4a1e-88c8-703f7c6a12b1.mp4

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Thank you, @Chadha93. There's a bit of weirdness with some of the fields that have predefined placeholders...

**Comment by Chadha93** [comment]
> Thank you, @Chadha93. There's a bit of weirdness with some of the fields that have predefined placeholders...

In Tooltip or in configurator?

**Comment by leecalcote** [comment]
In the Tooltip.

**Comment by Chadha93** [comment]
> In the Tooltip.

Screenshot from 2021-12-23 19-44-49
which one specifically?

**Comment by leecalcote** [comment]
Replicas is a great example.

**Comment by Chadha93** [comment]
> Replicas is a great example.

Umm, 😅 they all are using the same component, I'm not getting the difference here.

**Comment by leecalcote** [comment]
Tsk, tsk. See the "0" in the Replicas field and how it is lost?

**Comment by Chadha93** [comment]
> Tsk, tsk. See the "0" in the Replicas field and how it is lost?

Gotcha :+1: I check just now, it is the predefined value that we are storing there, either we can keep it or remove it, by removing the placeholder will be visible on the spot and works well.

**Pull request merged**
