### PR TITLE
Update Id Using Helm Charts

### PR DESCRIPTION
**Pull request by Vi1234sh12**
Signed-off-by: Vishal Dhanure vishald41234@gmail.com

**Description**
Update Id : Using Helm Charts 

This PR fixes #
[[Docs] Link broken for helm on kubernetes setup page #2839](https://github.com/layer5io/meshery/issues/2839)

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by Nikhil-Ladha** [comment]
Please fix the signoff issue, and update the description to use only the issue number like `PR fixes #2839`

**Review by leecalcote — COMMENTED** [review]
@Vi1234sh12 thanks for tying to improve the documentation. Neither of these two things are CLI commands:

- `helm-charts`
- `Kubernetes manifests`

Backticks (<pre> tags) are used to denote a cli command or portions of a script potentially.

`helm` - - is a cli
`kubectl` - - is a cli

Let's close this particular PR, but please keep your docs improvements coming. 👍

**Comment by leecalcote** [comment]
@Vi1234sh12 heads-up: on your next PR, have a look at the commit signing instructions listed here - https://github.com/layer5io/meshery/pull/2841#issuecomment-832871079

**Comment by Vi1234sh12** [comment]
> @Vi1234sh12 heads-up: on your next PR, have a look at the commit signing instructions listed here - https://github.com/layer5io/meshery/pull/2841#issuecomment-832871079

Yeah , Sure  I'm follow instructions

**Comment by Nikhil-Ladha** [comment]
Ohh, @leecalcote ig there is some miss communication, the issue was with the link in the site not properly navigating to the appropriate section. Though, the change in the name was supposed to be opposite as highlighted in the issue. So, I think at least the link needs to be fixed.

**Pull request closed without merging**
