### PR TITLE
[server]fix missing services attribute for empty design

### PR DESCRIPTION
**Pull request by MUzairS15**
**Notes for Reviewers**
The `Services` struct had `omitempty` tag because of which if the design was empty, it was not being streamed inside the response.

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by MUzairS15** [comment]
// @aabidsofi19 @leecalcote

**Review by leecalcote — COMMENTED** [review]
Removal of this also leaves the system vulnerable to a nil primary key...

**Comment by MUzairS15** [comment]
The services key as you said should be ever present, and this PR ensures this happens.
Comparing  it with primary constraint not null, if design is empty, it is not that `services` will be null but an empty object.

skipping/removing the key for empty design makes it difficult to understand whether design is actually empty or have got corrupted.

**Comment by leecalcote** [comment]
> The services key as you said should be ever present, and this PR ensures this happens. Comparing it with primary constraint not null, if design is empty, it is not that `services` will be null but an empty object.

Aha! Ok, that’s very good.

**Pull request merged**
