### PR TITLE
fixing recent mesheryctl system start panic 

### PR DESCRIPTION
**Pull request by Revolyssup**
**Description**

This PR fixes panic due to recent PR

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Revolyssup** [comment]
@navendu-pottekkat  merging this should fix the issue.

**Review by navendu-pottekkat — APPROVED** [review]
Looks good!

Thank you for fixing this quickly!

// @metonymic-smokey FYI

**Comment by leecalcote** [comment]
All, thank you for addressing this quickly. Please raise up the visibility of this sort of issue as it will require an immediate release of Meshery. Otherwise all Meshery users are dead in the water.

**Comment by navendu-pottekkat** [comment]
> All, thank you for addressing this quickly. Please raise up the visibility of this sort of issue as it will require an immediate release of Meshery. Otherwise all Meshery users are dead in the water.

😐  I thought we hadn't made a release since we merged the other PR. I thought this was only an issue with the master branch.

Will be careful with this.

**Pull request merged**
