### PR TITLE
Service Mesh Provisioning for DDE

### PR DESCRIPTION
**Pull request by warunicorn19**
Signed-off-by: Aditya Chatterjee <speak2adi@gmail.com>

**Description**
DOES NOT WORK, DO NOT MERGE
This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Conflict...

**Comment by leecalcote** [comment]
@sudo-NithishKarthik will you add a helping hand here?

**Comment by leecalcote** [comment]
Syncing with `master`

**Comment by l5io** [comment]
🚀 Preview for commit 580e2a3bac7072e08cbc5a45732b403dff0aaea9 at: https://62585e8be9fd3f1c6829d7cd--meshery-docs-preview.netlify.app

**Comment by leecalcote** [comment]
@warunicorn19 or @sudo-NithishKarthik will you update the makefile to include `make ui` to install, build and export the UI?

**Comment by l5io** [comment]
🚀 Preview for commit 8d4ddd20bdb4a051d9404097fa7f04936b3b06b8 at: https://625f35bfea07d100c32d6a40--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 705e54de60fab07eef8118f7d3c73d265493241e at: https://625f3c5b35fa930063ef0170--meshery-docs-preview.netlify.app

**Comment by warunicorn19** [comment]
Yup I'll do it @leecalcote

**Comment by l5io** [comment]
🚀 Preview for commit 5133c5154eb67f08dff3fa410b730f630f016b66 at: https://625ff435aa557a0de4d62dea--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 80ce20fc9f9aee2d2e9f22f3c7ffd3bd21fc58c5 at: https://625ffcefead7be1383a8a7af--meshery-docs-preview.netlify.app

**Pull request merged**
