### PR TITLE
adjusting all unit tests  for mesheryctl to increase coverage

### LINKED ISSUE #7805: [CI] Improve the CI and make sure it is useful for PR review
#### Current Behavior

As I discussed with @leecalcote. Many of our test cases are out of maintenance and these cases will cause the CI `golangci-lint` and `integrate-test` always failed. It is hard for helping the maintainer to merge the code.

And we have a low code coverage [codecov](https://codecov.io/gh/meshery/meshery)
 
#### Desired Behavior

we should fix these issues, and increase the code coverage to 40%(It is the first step).

#### Implementation

- [x] #7761
- [x] #7804
- [x] #3988
- [ ] #7821 

#### Acceptance Tests

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by Philip-21**
**Notes for Reviewers**

This PR fixes #7805 and #8429

Fixing multiple error failed tests in unit test [workflow](https://github.com/meshery/meshery/actions/runs/5802089714/job/15727771173)
Adjusting unit tests across various packages  making sure we get the TEST PASSED 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by Philip-21** [comment]
I made some changes for expectedResponse to tally with the actualResponse 
The changes had to be made in the load() that loads the expected response golden files ,  
With the changes made, the expected response is able to adjust the `/r/n`  to   `/n  ` to generate right indents to tally with the actualResponse. 
Extra space or indent needs to be left for the ` /n`  to occupy in the golden files

**Comment by Philip-21** [comment]
delete-test

Snapshots shows one of the changes i made here

**Comment by Philip-21** [comment]
I will be making changes to other packages where necessary

**Comment by suhail34** [comment]
Amazing

**Review by leecalcote — APPROVED** [review]

**Comment by leecalcote** [comment]
@suhail34 @Philip-21 please have a look - https://github.com/meshery/meshery/actions/runs/5896476458/job/15994396672?pr=8501

**Comment by Philip-21** [comment]
> @suhail34 @Philip-21 please have a look - https://github.com/meshery/meshery/actions/runs/5896476458/job/15994396672?pr=8501

I think the error codes, there seem to be duplicate error codes, details and name, there may have been some duplicacy from one of the pr's merged . That should be whats causing the workflow error. 
I wonder where these changes were made cause i cant find them i the utils package

**Comment by Philip-21** [comment]
@suhail34 the ListTest in the filter package  passes locally but fails in workflow [run](https://github.com/meshery/meshery/actions/runs/5900241347/job/16004150623?pr=8501#step:5:254), I am thinking of removing it totally. Or maybe a configuration in the workflow can be done to make it pass

**Comment by Philip-21** [comment]
@leecalcote  from the changes i have made, I've been able to tackle the unit test [failures](https://github.com/meshery/meshery/actions/runs/5802089714/job/15727771173#step:5:12), the integration test which had this [error](https://github.com/meshery/meshery/actions/runs/5929851326/job/16078392023?pr=8501#step:6:16) has been adjusted,  the code coverage has increased up to some point but  `19%` isn't effective. 
More tests will be created  in another pr  as this pr focuses on making tests pass.

**Comment by Philip-21** [comment]
Screenshot 2023-08-22 183025
@suhail34 , @leecalcote 
Commit [7bb0d8b](https://github.com/meshery/meshery/pull/8501/commits/7bb0d8ba4e59f08c291b16d8c817e005fd7e7c32#diff-4b1ab3e3d407fa299f2b80c9bf0140d6ad7cb2f9dae509e5b72d17ec12414a34) implemented some changes in the list.go for args to be detected and used to perform list actions

**Comment by Philip-21** [comment]
@leecalcote, @suhail34   from the changes i have made, I've been able to tackle the unit test [failures](https://github.com/meshery/meshery/actions/runs/5802089714/job/15727771173#step:5:12), the integration test which had this [error](https://github.com/meshery/meshery/actions/runs/5929851326/job/16078392023?pr=8501#step:6:16) has been adjusted,  the code coverage has increased up to some point but  `19.8%` isn't effective, still i am glad that more lines of code have been covered in various packages. I am still trying to figure out why integration tests keeps failing 
More tests will be created  in another pr  as this pr focuses on making tests pass to increase coverage

**Comment by vishalvivekm** [comment]
@Philip-21 Let's discuss this on Meshery Dev call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#) if you would. :)

**Comment by leecalcote** [comment]
@suhail34 good to go?

**Comment by suhail34** [comment]
yes we can merge this one for know for others issues i will communicate with @Philip-21

**Comment by Philip-21** [comment]
@suhail34 there's a new workflow [unitest](https://github.com/meshery/meshery/actions/runs/5963685713/job/16177398737?pr=8501) error, I just discovered it after i finished fixing some git conflicts, 
` Get "http://localhost:9081/api/filter?page_size=10000": no responder found`  I have tried multiple url's but i still get the same message. The filter delete url is always `api/filter/id`.

I'm still figuring it out but a suggestion from you can help speed up things

**Comment by suhail34** [comment]
I think it might be because Meshery running on different port it was issue I faced before I have created a pr for that it might get fix by that

**Comment by Philip-21** [comment]
> @suhail34 there's a new workflow [unittest](https://github.com/meshery/meshery/actions/runs/5963685713/job/16177398737?pr=8501) error, I just discovered it after i finished fixing some git conflicts, 
` Get "http://localhost:9081/api/filter?page_size=10000": no responder found`  I have tried multiple url's but i still get the same message. The filter delete url is always `api/filter/id`.
> I think it might be because Meshery running on different port it was issue I faced before I have created a pr for that it might get fix by that

**Comment by Philip-21** [comment]
Hello @leecalcote, could you please consider merging this pull request? I'd like to write additional unit tests that depend on the changes I've made here.

**Review by suhail34 — APPROVED** [review]
CodeCov is now 19.40% on your branch LGTM

**Comment by suhail34** [comment]
updating the branch

**Review by suhail34 — CHANGES_REQUESTED** [review]
Why are there changes made to go.mod and go.sum

**Review by suhail34 — APPROVED** [review]
LGTM

**Comment by Aisuko** [comment]
Thanks for your guys' contribution. I am happy to see you guys' working hard on this. However, I saw the Intergration Tests still failed, and it is hard to fix by one PR. https://github.com/meshery/meshery/actions/runs/5998728420/job/16267548545. So, I reopen this issue in order to fix the failed unit test case.

**Pull request merged**
