### PR TITLE
Fix eslint error for "TemplateLiteral" and fix package-lock.json for billboard.js

### LINKED ISSUE #1920: [UI] Issue at running eslint validation on master
**Description**
There is an issue on `master` that you can not run the UI by executing `make run-ui-dev`:

```
$ make run-ui-dev
cd ui; npm run dev; cd ..

> ui@1.0.0 dev /home/rodolfo/git/ramrodo-forks/meshery/ui
> eslint . && nodemon ui_dev_server.js


Oops! Something went wrong! :(

ESLint: 7.6.0

TypeError: Cannot read property 'range' of null
Occurred while linting /home/rodolfo/git/ramrodo-forks/meshery/ui/components/CustomToolbarSelect.js:1
    at OffsetStorage.setDesiredOffset (/home/rodolfo/git/ramrodo-forks/meshery/ui/node_modules/eslint/lib/rules/indent.js:341:45)
    at /home/rodolfo/git/ramrodo-forks/meshery/ui/node_modules/eslint/lib/rules/indent.js:1395:29
    at Array.forEach (<anonymous>)
    at Object.TemplateLiteral [as listener] (/home/rodolfo/git/ramrodo-forks/meshery/ui/node_modules/eslint/lib/rules/indent.js:1387:34)
    at /home/rodolfo/git/ramrodo-forks/meshery/ui/node_modules/eslint/lib/rules/indent.js:1633:55
    at Array.forEach (<anonymous>)
    at Program:exit (/home/rodolfo/git/ramrodo-forks/meshery/ui/node_modules/eslint/lib/rules/indent.js:1633:26)
    at /home/rodolfo/git/ramrodo-forks/meshery/ui/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/home/rodolfo/git/ramrodo-forks/meshery/ui/node_modules/eslint/lib/linter/safe-emitter.js:45:38)

```

The error seems to be with eslint validation. You can see the same error if you run eslint:

```bash
$ cd ui
$ npx eslint .
```

**Expected Behavior**
The UI should run without problems

**Environment:**
- Host OS: linux
- Meshery Version:  master
- Kubernetes Version: N/A
- Browser: N/A

---
[Optional] **To Reproduce**
```bash
$ cd ui
$ npx eslint .
```

[Optional] **Additional Context**
If you add this to the eslint config, that specific issue is ignored:

```json
ignoredNodes: ['TemplateLiteral']
```

### PR DESCRIPTION
**Pull request by ramrodo**
**Description**

This change:
- Adds `ignoredNodes` for `TemplateLiteral` to avoid errors with eslint
- Updates `package-lock.json` for `billboard.js`

This PR fixes #1920

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by ramrodo** [comment]
@Nikhil-Ladha @Sudhish2101 this will fix both errors: `eslint` validation and `package.json`

**Comment by Nikhil-Ladha** [comment]
I already had a PR open for this #1919 , but no issues we can go ahead with this one. I will close mine.

**Comment by Nikhil-Ladha** [comment]
I was not sure about adding the lock file, that's the reason I didn't updated it. But, I think it's necessary. Let's merge this.

**Review by Nikhil-Ladha — APPROVED** [review]
Thanks for the fix @ramrodo

**Comment by Sudhish2101** [comment]
Thanks for the fix @ramrodo.

**Pull request merged**
