### PR TITLE
[UI] Improved UI in Performance Profile test results 

### LINKED ISSUE #3798: [UI] Improve The Graph UI in Performance Profiles Page
#### Current Behavior
The performance graphs that are being shown right now in meshery ui are looking cluttered with information which makes it difficult for the users to consume the data. 

Screenshot 2021-08-06 at 10 41 45 AM

#### Desired Behavior
Make the performace graph modal less cluttered so that the users can easily consume the information.

#### Implementation
The way the graph is presented cannot be improved, but the presentation of this data shown in the image below can be improved. 

Screenshot 2021-08-06 at 10 45 51 AM

### Acceptance Criteria
1. Extract the latency calculations and on either the left hand or right hand side of the histogram, vertically stack the P50, P90, P95, P99 results. // @Meghana-12 

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by meghanacosmos**
Signed-off-by: Meghana-12 <meghana.cosmos@gmail.com>

**Description**
Improved the UI 
Screenshot 2021-08-31 at 1 30 24 AM
Screenshot 2021-09-01 at 9 32 59 PM
This PR fixes #3798 

**Notes for Reviewers**
This is a quick fix. 
I need a valid URL and details that I can use to test this properly.  

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by warunicorn19** [comment]
Too much white space on the right, don't you think?

**Comment by Meghana-12** [comment]
> Too much white space on the right, don't you think?

Actually, I'm using Material UI `GridList` to create 3 columns. Since I'm just mapping title array contents here (dunno how long they can get). Couldn't think of anything else. 

And I'm unable to `wrap` the content somehow, trying to fix that and to make the word before colon bold.

**Comment by leecalcote** [comment]
Demo in tomorrow's Meshery Dev call?

**Comment by leecalcote** [comment]
Demo in tomorrow's Meshery Dev call?

**Comment by Meghana-12** [comment]
I need a valid URL and details that I can use to test this properly.

**Comment by Meghana-12** [comment]
And UI integration checks at failing, what causes that ?

**Comment by warunicorn19** [comment]
@Meghana-12 what are you talking about the endpoint URL? you could just use https://google.com

**Comment by Meghana-12** [comment]
Does `res.Labels` always have only 2 entries? Title of the test and URL ?
https://github.com/meshery/meshery/blob/master/ui/lib/chartjs-formatter.js#L60

**Comment by Meghana-12** [comment]
And is it okay if I remove the commented code in these two files and refactor a bit?

**Comment by Meghana-12** [comment]
Tried to add the percentiles to the right of the chart. But when view on slightly smaller screens it's leading to a lot of white space.
Screenshot 2021-09-01 at 9 26 27 PM

So I'm just displaying the percentiles in a row
Screenshot 2021-09-01 at 9 32 59 PM

**Comment by Meghana-12** [comment]
I wish I could work on this further but my schedule's packed due to exams and assignments ;( 

Will be back in a week!

**Review by leecalcote — APPROVED** [review]

**Comment by leecalcote** [comment]
Thank you, @Meghana-12. Sounds good.

**Pull request merged**
