### PR TITLE
Green drop shadow is removed on the K8s context switcher in both dark and light modes.

### LINKED ISSUE #8696: [UI] Position K8s Context Switcher Drawer under the page title bar
### Current Behavior
Notice how the K8s context switcher drawer is on top of the green drop shadow from the page's title bar? Well, it is not supposed to be. 

### Desired Behavior
The K8s context switcher drawer should be at a layer lower such that the green drop shadow applies to this pulldown slider as well.

### Implementation
z-index...

### Acceptance Tests
1. The page bar's green drop shadow is visible on the K8s context switcher pulldown in both dark and light modes.

### Screenshot
Screenshot 2023-09-08 at 5 25 08 PM

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by ShailikaS**
**Notes for Reviewers**

This PR fixes #8696

Here's the image.
Screenshot 2023-09-15 at 4 43 32 PM

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit b1f8cdb4ff6ace33ae032fc69e16d90501598161 at: https://6504487aa24bc415c12083a1--meshery-docs-preview.netlify.app

**Review by Mohith234 — COMMENTED** [review]
Hey @ShailikaS, The issue isn't with the `dot` in the K8s context switcher drawer

The requirement is to have the drawer itself backward (z index) in order to get the page's title bar shadow ( which is in green ) on top of the K8s context switcher drawer

**Comment by saurabh100ni** [comment]
Let's discuss it on the websites call.
Please add this as an agenda item in the meeting minutes, if you would :)
https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima

**Comment by saurabh100ni** [comment]
Let's discuss this on the Meshery dev call tomorrow,
Please add this as your agenda item in Docs: https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit

**Comment by sudhanshutech** [comment]
This issue is fixed in my pr #8939 . This change is not needed

**Pull request closed without merging**
