### PR TITLE
fix(ci): update `docker-compose.yaml` path

### LINKED ISSUE #6106: [CI] `mesheryctl` unit test failing as `docker-compose.yaml` path is incorrect
#### Current Behavior

Unit test for `github.com/layer5io/meshery/mesheryctl/internal/cli/root/system` fails due to incorrect URL to download `docker-compose.yaml`. Thus, GitHub Actions job _Golang Unit and Integration Tests / Unit tests (pull_request)_ fails for every `mesheryctl` related change

image

#### Desired Behavior

Unit test for `github.com/layer5io/meshery/mesheryctl/internal/cli/root/system` passes

#### Implementation

Update path to `docker-compose.yaml` at [platform.go#332](https://github.com/meshery/meshery/blob/master/mesheryctl/pkg/utils/platform.go#L332) and [platform.go#352](https://github.com/meshery/meshery/blob/master/mesheryctl/pkg/utils/platform.go#L352)

"docker-compose.yaml" to "docs/docker-compose.yaml"

#### Acceptance Tests

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by whois-pk**
**Description**
- Corrected `docker-compose.yaml` path from `/docs` to `/install/docker/`
- Made subsequent changes in `[platform.go](https://github.com/meshery/meshery/blob/master/mesheryctl/pkg/utils/platform.go)`

This PR fixes #6106 

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by pk-218** [comment]
@leecalcote I couldn't find any breaking changes other than `platform.go`

**Comment by l5io** [comment]
🚀 Preview for commit f6444c4b0f00b465fc334507c4196c59251ff792 at: https://630a7b820a0b953dbb267dad--meshery-docs-preview.netlify.app

**Comment by leecalcote** [comment]
@pk-218 ok, thanks for looking. Stated another way, this issue only affects `mesheryctl system reset`, correct?

**Comment by pk-218** [comment]
@leecalcote Yes

Once changes are merged, the unit test for `mesheryctl system reset` and the integration test for `mesheryctl system` should pass.

**Review by leecalcote — APPROVED** [review]
Good one update. Full steam ahead here. 🚂

**Comment by leecalcote** [comment]
Wow. Ok, @pk-218. Two PRs landing within 5 minutes of each other...


...now, you're just showing off. 😉

**Pull request merged**
