### PR TITLE
[Server] Feat: Move to v1beta1

### PR DESCRIPTION
**Pull request by MUzairS15**
**Notes for Reviewers**

This PR fixes #

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
How's that design migration function coming along? 😄

**Comment by leecalcote** [comment]
@MUzairS15 components have this listed as their`"schemaVersion": "core.meshery.io/v1beta1",`. Unless all `core.meshery.io` is versioned together, I don't believe that the current value is appropriate, but that `"schemaVersion": "component.core.meshery.io/v1beta1",` is what is needed. What do you think?

**Comment by leecalcote** [comment]
I resolved the merge conflicts.

**Comment by l5io** [comment]
🚀 Preview for commit fbf5704777c07fc6c76746bf50abad6d98deec53 at: https://66388e36d79e9e963751f407--meshery-docs-preview.netlify.app

**Pull request merged**
