### PR TITLE
added "language: en" to the frontmatter of all Docs pages that are in English

### LINKED ISSUE #7283: [Docs] Add "language: en" to the frontmatter of all Docs pages that are in English
#### Current State
A Spanish translation of Meshery's docs exists. In order to facilitate a separation between viewing the dark speak in different languages, it would be good to have all pages containing a `language` frontmatter setting. Currently, not all of the English pages have this setting.

Example of a page missing this setting - https://github.com/meshery/meshery/blob/master/docs/pages/reference/rest-api-reference.md?plain=1

Example of a page having this setting - https://github.com/meshery/meshery/blob/master/docs/pages/reference/troubleshooting/installation.md?plain=1

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by hirentimbadiya**
**Notes for Reviewers**

This PR fixes #7283 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 596bcf4b07a87aa56862320bc9906a4c7261c2c3 at: https://64069044098e2c0ee94d5c45--meshery-docs-preview.netlify.app

**Comment by hirentimbadiya** [comment]
@b0id can you please kindly review my PR.

**Comment by b0id** [comment]
If you want a formal review you will have to request one from me on Github.  I see no problems with the changes otherwise, however, that is from the scope of my understanding about the project others may have feedback, I am unaware of.

**Review by leecalcote — CHANGES_REQUESTED** [review]
@hirentimbadiya, thanks for this PR. Make sure that you have not made changes to v0.4 or v0.5. Those versions are snapshotted and frozen in time.

Screenshot 2023-03-07 at 5 42 16 PM

**Comment by hirentimbadiya** [comment]
> @hirentimbadiya, thanks for this PR. Make sure that you have not made changes to v0.4 or v0.5. Those versions are snapshotted and frozen in time.
> 
> Screenshot 2023-03-07 at 5 42 16 PM

I will do that.

**Comment by l5io** [comment]
🚀 Preview for commit 871ae78116f7d0be4f05ca9b33144b1ebfc8e1c4 at: https://640870282d7df71f41856ea8--meshery-docs-preview.netlify.app

**Comment by Chadha93** [comment]
@hirentimbadiya  Let's discuss this on the Meshery Dev call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#) if you would. :)

**Comment by l5io** [comment]
🚀 Preview for commit d241a71376603f1b6f5ac04419cd27ae284f58b0 at: https://64087560ac196d27556235c8--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit bee9df5b1e198258303b33badc8f46714e4236b5 at: https://6408770766f09a2755e81a6c--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit a94745d3826bda4340adf9a10f7e49a54ae24db7 at: https://640878ad2d7df725d7856e99--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 419ba338d1c6ab1223aa187caab5eb99ab76cc69 at: https://64087a7dac196d2bd162391f--meshery-docs-preview.netlify.app

**Comment by hirentimbadiya** [comment]
hello @leecalcote can you please review PR now , I made changes and made sure the language: en is not in v0.4 & v0.5 files

**Comment by l5io** [comment]
🚀 Preview for commit 5b5c4ee4287ed062ddb4b6aeb99cab9940d0019c at: https://6408c2a40e2b226a92219616--meshery-docs-preview.netlify.app

**Comment by leecalcote** [comment]
@hirentimbadiya please resync your fork/clone, such that this PR only includes your commits, not the commits of others.

**Review by leecalcote — CHANGES_REQUESTED** [review]
@hirentimbadiya please resync your fork/clone, such that this PR only includes your commits, not the commits of others.

**Comment by l5io** [comment]
🚀 Preview for commit 789c172cefb5c89c3aeec3658b930be779c7b3f9 at: https://64093055344a1740de544eca--meshery-docs-preview.netlify.app

**Comment by hirentimbadiya** [comment]
@leecalcote , can I close this PR  and submit a fresh PR with the relevant changes.

**Pull request closed without merging**
