### PR TITLE
[UI] MeshModel Summary in Meshery Settings

### PR DESCRIPTION
**Pull request by theBeginner86**
**Notes for Reviewers**

This PR updates the Meshery Settings page to show the registered MeshModel (eg: Components, Relationships, etc).

This PR fixes #

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
I'm testing now. Where might I see this draft UI?

**Comment by leecalcote** [comment]
> I'm testing now. Where might I see this draft UI?

Oh. There are no UI changes, yet. ✔️

**Comment by theBeginner86** [comment]
> I'm testing now. Where might I see this draft UI?

It's not ready yet. 😅
So far I've just set up some basic GraphQL schema stuff.

Though It would be visible in the Meshery Dashboard (somewhere close to workloads).

**Comment by theBeginner86** [comment]
This PR is ready for review:


https://user-images.githubusercontent.com/73700530/213236215-c3fb1a1a-0d7d-4a48-b701-43015509f38f.mov

**Review by Revolyssup — DISMISSED** [review]

**Comment by theBeginner86** [comment]
Moved to the settings page. // @leecalcote 

Screenshot 2023-01-25 at 6 52 33 PM

**Review by leecalcote — APPROVED** [review]

**Pull request merged**
