### PR TITLE
update meshery architecture diagrams

### LINKED ISSUE #1615: [Docs] Update Meshery Architecture diagrams
**Description**

Swap out the outdated Meshery architecture pictures in the [Architecture](https://meshery.layer5.io/docs/architecture) page in the Meshery docs.
The images can be sourced from the [Architecture folder](https://drive.google.com/drive/folders/1_aKPepn31LfXrWkdAdiZWgjdFVigTo1M?usp=sharing) in the Layer5 community drive.

The images have been named according to the headings in the documentation - Meshery architecture diagram, client and provider. They should be updated under their respective headings.

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

### PR DESCRIPTION
**Pull request by lolyparty**
Signed-off-by: lolyparty <ololadeolayiwola01@gmail.com>

**Description**

This PR fixes #1615 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — CHANGES_REQUESTED** [review]
Hi @lolyparty, could we keep these as SVGs? Vector graphics work very well in this situation for scaling out the images cleanly. The Slides can be downloaded as SVGs.

**Comment by lolyparty** [comment]
Can you please explain how to download them as svg?  Because the files in the drive are all PNG

**Comment by leecalcote** [comment]
For posterity - Untitled

**Review by leecalcote — APPROVED** [review]
Thank you, @lolyparty

**Pull request merged**
