### PR TITLE
[Docs] Changed calculation logic on the compatibility matrix

### PR DESCRIPTION
**Pull request by asubedy**
Signed-off-by: asubedy <frexpe@pm.me>

**Notes for Reviewers**
1. Cilium is not giving desired result

This PR fixes #

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 1ba3995596a60b8e706893d75e03661a8d1a0941 at: https://63a996cd3be54901499a7fc2--meshery-docs-preview.netlify.app

**Review by leecalcote — COMMENTED** [review]
@alphaX86 a good opportunity to familiarize with Jekyll even more.

**Comment by leecalcote** [comment]
@asubedy outside of Cilium, are you also changing the logic to only consider the latest stable release test results?

**Comment by asubedy** [comment]
> @asubedy outside of Cilium, are you also changing the logic to only consider the latest stable release test results?

Yes @leecalcote the matrix looks for the latest stable release for a particular kubernetes version and shows its status and if it does not find any stable version it shows the status of the latest edge release. If there is any stable release done then again instead of edge it will show the status of stable version.

**Comment by leecalcote** [comment]
this is looking much better, @Revolyssup -- https://63a996cd3be54901499a7fc2--meshery-docs-preview.netlify.app/installation/platforms

**Review by leecalcote — APPROVED** [review]

**Pull request merged**
