### PR TITLE
[Server] [Bug] Fix Cilium deployments not showing in UI.

### PR DESCRIPTION
**Pull request by MUzairS15**
Signed-off-by: MUzairS15 <muzair.shaikh810@gmail.com>

**Description**

This PR fixes Cilium mesh deployments not showing up in Meshery UI.

Screenshot 2022-05-01 at 1 06 17 PM

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by MUzairS15** [comment]
All resources from kube-system namespace are being showed. And I think resources which don't have name are   k8s resources not related to cilium.

This is not ideal. I will look into it.

**Comment by leecalcote** [comment]
@MUzairS15 makes sense. Good plan.

**Comment by leecalcote** [comment]
@Revolyssup having the list of core vs non-core Kubernetes components is useful here. // @Abhishek-kumar09

**Comment by MUzairS15** [comment]
@Revolyssup any suggestions??
One way I could think of is filtering before showing in UI. But this approach is not full proof.

**Review by Abhishek-kumar09 — APPROVED** [review]

**Comment by leecalcote** [comment]
Gents, this must be more intelligently addressed. Please solicit input from @jtaleric, @xmulligan, and @lizrice on what attributes of a Kubernetes object uniquely identify it as a Cilium component, e.g. `image: cilium/cilium`.

**Comment by Revolyssup** [comment]
> Gents, this must be more intelligently addressed. Please solicit input from @jtaleric, @xmulligan, and @lizrice on what attributes of a Kubernetes object uniquely identify it as a Cilium component, e.g. `image: cilium/cilium`.
> 
> We're in need of identifying a Cilium "fingerprint" - ideally, a single (or composite set of) attribute(s) that uniquely identify each component of a Cilium deployment. This fingerprint is to be documented in the Meshery Adapter for Cilium Service Mesh and supplied to MeshSync upon adapter registration with Meshery Server.

This fingerprint can be extracted by organization name from image of the pod, which is CIlium. I will push the commit on this PR

**Comment by Revolyssup** [comment]
@leecalcote  Further filtering removes other k8s pods from discovery.
this

Although the changes I made in this PR will eventually go into each and every adapter and the adapter will direct the filters for mesh discovery

**Pull request merged**
