### PR TITLE
Update README.md for better readability

### LINKED ISSUE #6777: [Docs] Small images in Meshery Readme.
#### Current State
The images in the readme of Meshery are very small that a user/viewer has to click on them to view what it is. Some open on GitHub while some redirects to meshery doc website and the GIF one directly gets downloaded. Some alignment issues are also there leading to an inconsistent reading experience.

#### Desired State
All images should be of equal size and big enough so that it serves their purpose directly. Paragraph and image alignment should be consistent throughout the doc.

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by chinu-anand**
Signed-off-by: Chinu Anand <chinuanand81@gmail.com>

**Notes for Reviewers**

This PR fixes #6777 

All the table alignment and image size issues are solved in this.

The only problem left is with the Meshery community section's paragraph where there are 3 components: the community icon, a paragraph and a slack icon, the property "display: flex" is working fine in other markdown editors but in GitHub, it's not rendering it correctly and overriding internally with "display: inline", I think its the issue with GitHub as 5 other markdown editors can't be wrong.

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Right: GitHub Markdown strips many HTML and CSS tags, intentionally not supporting them.

**Review by eeshaanSA — COMMENTED** [review]
Looks good for the most part. we need to address the broken links here as well, the contributing guide, and the project overview presentation links.

**Review by kayceeDev — APPROVED** [review]
I commend you use of English and understanding of markdown syntax. Looks good to me

**Comment by chinu-anand** [comment]
Yeah sure @eeshaanSA , I mainly focused on improving the readability issue in the doc.

**Comment by leecalcote** [comment]
> I commend you use of English and understanding of markdown syntax. Looks good to me

This is no small thing either. We all could use a composition 101 refresher.

**Comment by leecalcote** [comment]
@UtkarshMishra12 @Chadha93  we have a broken link to the Meshery Project Overview deck that one of our community members deleted.

**Pull request merged**
