### PR TITLE
Revert "Revert "Open API Docs #4""

### PR DESCRIPTION
**Pull request by dhruv0000**
**Description**

Added login/logout fixes to #3342.

**Notes for Reviewers**

***Need to make a new release of Meshery Cloud before merging this***

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by utkarsh-pro — APPROVED** [review]
LGTM

**Comment by kumarabd** [comment]
@utkarsh-pro @dhruv0000 End to end test failing. Anything we can do about it?

**Comment by piyushsingariya** [comment]
Thanks a lot @dhruv0000 , for fixing it up  :muscle:

**Comment by dhruv0000** [comment]
@kumarabd test passing.

**Review by kumarabd — APPROVED** [review]

**Comment by leecalcote** [comment]
Meshery Cloud v0.1.15 released to Staging.

**Comment by dhruv0000** [comment]
@leecalcote  We should probable create a new release, or people using stable branch won't be able to login.

**Pull request merged**
