### PR TITLE
Change ruby version and Adapter Documentation

### PR DESCRIPTION
**Pull request by Boombag0607**
**Notes for Reviewers**

Fixes ruby version for arm64 systems. Highlights `make docker` in adapter doc.

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
@Boombag0607 thanks for this. Please investigate the [failed documentation build](https://github.com/meshery/meshery/actions/runs/5365444610/jobs/9734266901?pr=7933) and be sure to [sign-off on your commits](https://github.com/meshery/meshery/pull/7933/checks?check_run_id=14525149537).

**Comment by l5io** [comment]
🚀 Preview for commit 8d64b77fca09e75c156e3fe4bb9619abe31ec0ea at: https://649759bf7290f11d4ce7aa58--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit b40cfc9286d8091d768ff90642e827cd4da0b77a at: https://64975a9be3d5791b24f94b80--meshery-docs-preview.netlify.app

**Review by leecalcote — APPROVED** [review]
Good stuff here, @Boombag0607 👍

**Pull request merged**
