### PR TITLE
Fix SQL injection in /api/system/meshsync/resources

### PR DESCRIPTION
**Pull request by gyohuangxin**
**Notes for Reviewers**

This PR fixes #

As mentioned in GitHub Security Lab (GHSL) Vulnerability Report, this PR is to fix a SQL injection in /api/system/meshsync/resources. 
Similar vulnerabilities has been fixed in https://github.com/meshery/meshery/pull/9372  using `SanitizeOrderInput` function, which you can uses as a reference.

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by gyohuangxin** [comment]
"Golang Unit and Integration Tests" job failed because of unchanged files, it's not related to my PR, I can raise another PR to fix them.

"MeshKit Error Codes Utility Runner" job's error message is `Error: Input required and not supplied: token`, which I have no idea about. @MUzairS15 Do you know that?

**Comment by MUzairS15** [comment]
> "Golang Unit and Integration Tests" job failed because of unchanged files, it's not related to my PR, I can raise another PR to fix them.
> 
> "MeshKit Error Codes Utility Runner" job's error message is `Error: Input required and not supplied: token`, which I have no idea about. @MUzairS15 Do you know that?

`Error: Input required and not supplied: token` The workflow runs fine on `master` [branch](https://github.com/meshery/meshery/actions/runs/7678549308) , I think for PRs the GH Token is not being used, we can skip them (right now the conditional included to skip is not working correctly). I will look on this workflow.

Thanks for volunteering on 
> "Golang Unit and Integration Tests" job failed because of unchanged files, it's not related to my PR, I can raise another PR to fix them.".

Do you have one already?

**Comment by gyohuangxin** [comment]
> Thanks for volunteering on

> "Golang Unit and Integration Tests" job failed because of unchanged files, it's not related to my PR, I can raise another PR to fix them.".

> Do you have one already?

@MUzairS15  Not yet, but I can create one today.

**Review by leecalcote — APPROVED** [review]
The change in this PR looks great.

**Review by MUzairS15 — APPROVED** [review]

**Pull request merged**
