### PR TITLE
Redesign mesheryctl commands on docs site

### LINKED ISSUE #2529: [Docs] redesign mesheryctl Command Reference
**Current State:**

[mesheryctl Command Reference](https://docs.meshery.io/reference/mesheryctl) is a central document which shows all the available `mesheryctl` commands and their usage.

**Desired State:**

However, the current page is not intuitive to the user and also misses documentation for some of the new commands added in `mesheryctl`.

The goal of the new design should be the following-

1. **Improved mesheryctl Command Reference page** that the users can refer to.
2. **Links added to each of the commands** which will point to the individual doc of each command.(individual docs are not added currently)

See [user stories in the design spec](https://docs.google.com/document/d/1Iw88bZEL_fWeajxHh0BgmhuXGKl455P4CF-vm1yCkU8/edit#heading=h.nj62kbe4pwcb) for more info.

The following principles should be followed while designing and maintaining the document-

* **Intuitive**
The document should be intuitive to the user. They should be able to easily understand the layout of the commands and should be able to easily check the subcommands and flags for each of the commands.

* **Ease of access**
Each of the commands will have a separate documentation page and link to that page should be added to the corresponding command in the table.

**Implementation:**

* Improve the [mesheryctl Command Reference](https://docs.meshery.io/reference/mesheryctl) page with inspiration from the [mesheryctl Command Reference and Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit?usp=sharing) doc.

The table should have the following columns-

1. command/arguments- The base command/argument
2. flag- Flags available for the given command
3. function- The function of the given command
4. usage- Example usage of the given command

* Add links in each entry in the table corresponding to a command which points to individual docs of the respective command (individual docs are not added currently). 

---
**Contributor Resources:**
- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
- [mesheryctl Command Reference](https://docs.meshery.io/reference/mesheryctl)
- [mesheryctl Command Reference and Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit?usp=sharing)
- [design spec- mesheryctl Command Reference](https://docs.google.com/document/d/1Iw88bZEL_fWeajxHh0BgmhuXGKl455P4CF-vm1yCkU8/edit#)

### PR DESCRIPTION
**Pull request by alphaX86**
**Description**

This PR fixes #2529 

**Notes for Reviewers**
I've added almost all commands given in the [mesheryctl Command Reference and Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit?usp=sharing) but still it may cause an unordered feel, so please do review and tell any suggestions/problem faced in pre-review stage so that I can change ASAP accordingly

**[Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by alphaX86** [comment]
@navendu-pottekkat the doc is ready but what I felt is that some ordering is disturbed in the reference page. Could you check and tell any suggestions to avoid it?

**Comment by navendu-pottekkat** [comment]
@alphaX86 Nice. Let me review it...

**Review by navendu-pottekkat — COMMENTED** [review]
We ideally want the table to look like the [mesheryctl- Command Reference and Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0) spreadsheet-

Screenshot from 2021-03-12 22-41-30

But it is not possible to create multi-row cells/merged rows in pure markdown so we will need to use HTML tables.

You can check out [this issue](https://stackoverflow.com/questions/46621765/can-i-merge-table-rows-in-markdown/46648510) to get an idea on how to implement this.

**Comment by alphaX86** [comment]
> We ideally want the table to look like the [mesheryctl- Command Reference and Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0) spreadsheet-
> 
> Screenshot from 2021-03-12 22-41-30
> 
> But it is not possible to create multi-row cells/merged rows in pure markdown so we will need to use HTML tables.
> 
> You can check out [this issue](https://stackoverflow.com/questions/46621765/can-i-merge-table-rows-in-markdown/46648510) to get an idea on how to implement this.

Got it! Will use HTML tables to sort this out then

**Comment by navendu-pottekkat** [comment]
@alphaX86 Although it requires some grunt work, it should be easy to maintain in the long run. Thank you for taking this up! 🚀

**Comment by leecalcote** [comment]
@alphaX86 FYI here's a related PR - #2548

**Comment by alphaX86** [comment]
Hmm, interesting! I was working to make the tables as HTML mode as the `rowspan` doesn't work on markdown. For that, I have to rework all YAML files. Need to check that PR out for idea though....

**Comment by navendu-pottekkat** [comment]
> Hmm, interesting! I was working to make the tables as HTML mode as the `rowspan` doesn't work on markdown. For that, I have to rework all YAML files. Need to check that PR out for idea though....

That PR may not help you out as it is just the template for the individual docs for the commands. But the links in the table that you are creating will point to docs created using this template.

**Comment by alphaX86** [comment]
Oh okay, I understand

**Comment by alphaX86** [comment]
So far, I didn't implement YAML for now to check how it prints. After review on this, I'll re-implement YAML to desired state

**Comment by alphaX86** [comment]
@navendu-pottekkat it's ready. Review it. And tell what colors I could add for it to make it look better

**Review by navendu-pottekkat — COMMENTED** [review]
The page looks amazing! All it needs is some proper color coding.

The `docs/pages/reference/mesheryctl-commands.md` file looks maintainable to me. It would not take much effort to add and remove commands.

This means that we do not need the other `yaml` files right? Could you clean those up too when you make the PR?

**Comment by alphaX86** [comment]
> The page looks amazing! All it needs is some proper color coding.
> 
> The `docs/pages/reference/mesheryctl-commands.md` file looks maintainable to me. It would not take much effort to add and remove commands.
> 
> This means that we do not need the other `yaml` files right? Could you clean those up too when you make the PR?

Copy that I'll remove those? So do you want me to remove all of those under `_data`?

**Comment by leecalcote** [comment]
We just got done moving these commands into datafiles so that we can programmatically publish individual command pages.

What's driving the need to reverse this?￼

**Comment by alphaX86** [comment]
> We just got done moving these commands into datafiles so that we can programmatically publish individual command pages.
> 
> What's driving the need to reverse this?￼

Well, should I keep as it is then?

**Comment by leecalcote** [comment]
Good question. I'm still trying to understand the need for the change. ￼ if you can describe that here, that be great. Or we can grab @navendu-pottekkat and jump on a call. To walk through it. If is to style the page, perhaps, there's an approach not yet considered. 

A single, monolithic page is harder to maintain particularly as we go to publish independent pages for each command.

**Comment by navendu-pottekkat** [comment]
@alphaX86 We might need to switch back to using the data stored in the YAML files. As @leecalcote pointed out, using the datafiles would make it easy to maintain since we are also adding the pages for this individual commands.

@Nikhil-Ladha would be able to help you out with it as it should be possible to use the datafiles in HTML.

Maintainability is a key factor when we design these documents as it will undergo a lot of continuous improvements.

If this does not work, we might need to look into some other approaches so that we do not compromise maintainability.

**Comment by alphaX86** [comment]
@navendu-pottekkat I agree, why not use the data files on individual docs instead of main doc page. Coz we need to include the links to those docs too. In such case, how we'll know that this command links to that individual doc if we use data files?? I'm really started to think on this

**Comment by alphaX86** [comment]
@navendu-pottekkat @leecalcote @Nikhil-Ladha the doc is ready for view. Review it and tell what further changes are needed, well for some YAML files it has be worked for linking purposes, but I'll do it after the review and opinion

**Review by navendu-pottekkat — COMMENTED** [review]
Are we not using the multi row cells for such cases?

Screenshot from 2021-03-22 12-38-53

**Comment by alphaX86** [comment]
Still in progress! But I shared because I found a way to group YAML files, if you need such, I may need to group them again

**Comment by navendu-pottekkat** [comment]
Okay got it. We need to have multi row cells right? For clarity.

Please group them and keep using the YAML files.

**Comment by alphaX86** [comment]
It's done! Finally the color part is needed!! 🥳

**Review by navendu-pottekkat — COMMENTED** [review]
@alphaX86 Looking good! 

Is there a way we can order the items in the table? ex `system start` could be shown at first instead of the bottom and the commands could be ordered as in the Command Tracker spreadsheet.

Could you check if it would be feasible?

Other than that, everything looks good. And adding proper color formatting would make this even better.

**Comment by alphaX86** [comment]
The tricky part is ordering, coz IDK in what logic order it prints. But the grouped ones can be put first as you said

**Comment by Nikhil-Ladha** [comment]
> The tricky part is ordering, coz IDK in what logic order it prints. But the grouped ones can be put first as you said

It prints in the order it gets the data, you can sort or filter the data as well.
Checkout this https://shopify.github.io/liquid/basics/introduction/

**Comment by alphaX86** [comment]
What color shades can be given 🤔 It must be shades of gray but hmm......

**Comment by alphaX86** [comment]
Seems we need to discuss this afterwards

**Comment by leecalcote** [comment]
@alphaX86 brand resources - https://layer5.io/brand and [brand guide here](https://docs.google.com/presentation/d/1Ofy15e2bAIz4IYC8X70omnlpX9vI0QZpkRijYbxGAd4/edit)

**Review by navendu-pottekkat — COMMENTED** [review]
Changes looks good!

This seems to be _meshed_ up-

Screenshot from 2021-03-22 23-41-03

**Comment by alphaX86** [comment]
> Changes looks good!
> 
> This seems to be _meshed_ up-
> 
> Screenshot from 2021-03-22 23-41-03

Ah, that's rowspan issue, I may didn't remove a tag, okay need to look on it

**Review by navendu-pottekkat — CHANGES_REQUESTED** [review]
In the global commands and flags, version is a command, not a flag.

Screenshot from 2021-03-23 14-28-46

The order of the commands are not as per the [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)

The [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0) is the central source of truth for all of the mesheryctl commands. 

What I mean to say here is that add every command and flag as it is from the spreadsheet to the page. And remove any outdated the command/flag that is still on the doc.

**Comment by alphaX86** [comment]
Remove outdated commands and use command tracker as the main one........ Alright I moved version as subcommand but left due to some factors, alright trying that again

**Comment by alphaX86** [comment]
The order it prints is in Alphabetical order but the command tracker sheet is somewhat a bit random. I managed to mimicked some

**Comment by alphaX86** [comment]
Colors are removed as it felt overkill for us

**Comment by alphaX86** [comment]
Let's see how this goes.... 😆

**Review by navendu-pottekkat — APPROVED** [review]
@alphaX86 Great work! Thank you.

We can merge this.

**Comment by leecalcote** [comment]
Oof. Wow. Way to be, @alphaX86. This is decent-sized lift. I love it.

**Comment by leecalcote** [comment]
Heads-up: as you go to work on the next PR to layer in hyperlinks for each command, you will likely find that the datafiles need to be converted to a Jekyll Collection (collection of .md files), so that individual pages can be automatically generated.

**Comment by leecalcote** [comment]
Please move forward quickly on exposing individual command pages, because users will be without usage references until this happens.

**Pull request merged**
