### PR TITLE
Update mode toggle icons

### LINKED ISSUE #7208: [Docs]Dark mode icon in docs in dark mode
#### Current State
In dark mode, the icon is the same as in light mode (the sun icon)
image

#### Desired State
The icon in dark mode should be the dark mode icon as in other websites
image

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by vishalvivekm**
**Notes for Reviewers**

This PR fixes #7208

- sets dark mode in docs by default issue  #7190 
- merges moniker and codes meshery/meshery.io#1020
-  updates the mode toggle icons:

in light mode 
Screenshot_20230228_005348

in dark mode 
Screenshot_20230228_005336

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.
Signed-off-by: Vivek Vishal <110674407+vishalvivekm@users.noreply.github.com>

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit fcae4465a7b6e78b89d17e99c61adccef25ed2d1 at: https://63fd07e9355c2f0e1c134df1--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 2a7580f4ddbbde15b2d771bc799f159a199ad5c0 at: https://63fd1ed617cdd41e329281ee--meshery-docs-preview.netlify.app

**Comment by vishalvivekm** [comment]
things got messed up with DCO and rebasing. Closing this PR. will submit a new one

**Comment by vishalvivekm** [comment]
> Cool

Hey Thanks @leecalcote . I'd again created a new PR right after closing this one. 
Sudhanshu says he's a PR open for review so maybe once that gets merged then I can push my changes for icons, specifically.

**Pull request closed without merging**
