### PR TITLE
[API]Fix Incorrect API Endpoint for Istio Mesh Adapter Undeployment

### LINKED ISSUE #8799: [API] Wrong API endpoint is called while undeploying mesh adapters
### Current Behavior

when undeploying a mesh adapter from meshery UI (in this case istio mesh adapter),
adapter undeploy button

## Wrong API endpoint is called
api

`api/system/graphql/query` should have been called instead with body
```
{
  "query": "mutation AdapterStatusMutation($input: AdapterStatusInput) { adapterStatus: changeAdapterStatus(input: $input) }",
  "variables": {
    "input": {
      "targetStatus": "DISABLED",
      "targetPort": "10000",
      "adapter": "meshery-istio"
    }
  }
}

```

`api/system/adapter/manage?adapter=meshery-istio%3A10000` doesn't undeploy adapters.
### Desired Behavior

Call aforesaid Graphql API to undeploy adapters

### Environment

- Browser: Chrome Safari Firefox
- Host OS:Linux
- Meshery Server Version: stable-v0.6.139 
- Meshery Client Version: stable-v0.6.139 
- Platform: Docker

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by Shiva953**
**Notes for Reviewers**

This PR fixes #8799 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by zakisk** [comment]
@Shiva953 have you tested it by deploying and deploying adapters and seeing that is it listed in `docker ps` command in your machine?

**Review by MUzairS15 — CHANGES_REQUESTED** [review]
Can you use react-relay for making GraphQL mutations?
Refer this as an example, https://github.com/meshery/meshery/blob/4db47c8aa4eb66892f91efb0128403164e97580e/ui/components/graphql/mutations/OperatorStatusMutation.js

**Comment by Shiva953** [comment]
@MUzairS15 did it, would like a review on the same

**Review by Yashsharma1911 — COMMENTED** [review]
Build is failing @Shiva953

**Comment by saurabh100ni** [comment]
Let's discuss this on the Meshery dev call tomorrow,
Please add this as your agenda item in Docs: https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit

**Comment by leecalcote** [comment]
merge conflict, @Shiva953

**Comment by Shiva953** [comment]
Closing this one, would create a new PR for it

**Pull request closed without merging**
