### PR TITLE
Migrated CustomToolbarSelect Component from MUIv4 to MUIv5 and Sistent

### LINKED ISSUE #12219: [UI] Migrate Custom Toolbar Select Component to use MUI v5 Styling and Sistent Component
### Current Behavior
This [CustomToolbarSelect](https://github.com/meshery/meshery/blob/5e7e59a2de62d45f3ba9aa8e89a832dc4f09a059/ui/components/CustomToolbarSelect.js#L30) Component uses MUI v4's styling. This needs to be updated for improved performance and consistency.

### Desired Behavior
- [ ]  use [Sistent](https://github.com/layer5io/sistent) components for  MUI v4 to MUI v5 migration

Sistent is our design system that uses MUI v5, you can also refer to this [doc](https://docs.meshery.io/project/contributing/contributing-ui-sistent) to understand how to use Sistent.

### Acceptance Tests
The component must be updated without introducing any breaking changes in functionality or theming across all instances where it is used.

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by Divyansh200102**
**Notes for Reviewers**

- This PR fixes #12219

- For ui changes: Please add a screenshot showcasing the UI before/after changes. 
- Before(Light Mode)
image

- Before(Dark Mode)
image

- After(Light Mode)
image

- After(Dark Mode)
image

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by vishalvivekm** [comment]
@Divyansh200102 Thank you for your contributions! Let's discuss this during the Meshery Development call today at 9:00 AM CT | 7:30 PM IST. Adding it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit?pli=1#) || [meeting link](https://meet.layer5.io/meshery).

**Comment by Divyansh200102** [comment]
@vishalvivekm hi for some personal reason i wont be able to attend the meeting . Can i get the reviews from the maintainers directly here?

**Comment by leecalcote** [comment]
> @vishalvivekm because i am travelling at the moment i am not sure if i can do it today i tried joing but it just kept disconnecting. Can do the review in the next upcoming meeting?

yes

**Comment by leecalcote** [comment]
@nebula-aac there's a second PR from @Divyansh200102 up for review - https://github.com/meshery/meshery/pull/12559

**Comment by Divyansh200102** [comment]
> @nebula-aac there's a second PR from @Divyansh200102 up for review - https://github.com/meshery/meshery/pull/12559

@leecalcote apologies but I won't be able to  join the meeting and present a demo of the components tomorrow as there are connectivity issues where I currently am. I will be back by next week and then I will present the demo of both the migrated components if necessary.For now I will attach the screenshots of the migrated component for reference.

**Comment by Divyansh200102** [comment]
@nebula-aac i have resolved the conflicts please see if it's good to merge

**Comment by Divyansh200102** [comment]
@vishalvivekm the changes are approved in this pr can you please merge it.

**Comment by Divyansh200102** [comment]
@leecalcote this pr is approved can you please merge it?

**Pull request merged**
