### PR TITLE
updated Consul version to 1.8 and removed sentence SMI adapter for ku…

### PR DESCRIPTION
**Pull request by Rex739**
Signed-off-by: user <ojemehprogress@gmail.com>

**Description**
Update Consul Version to 1.8
This PR fixes #1526
- Updated Consul version from 1.5 to 1.8

- Removed "The SMI adapter for Kuma can also be installed using Meshery" sentence from [https://meshery.layer5.io/docs/service-meshes/adapters/consul](url)

**Notes for Reviewers**
This is my very first open source contribution. its a start of a new dawn. 
i'll get use to the process soon enough.

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by PluckyPrecious — CHANGES_REQUESTED** [review]
Looks good @Rex739 🥳  just a little touch and we are good to go

- The Subject /PR Title should be a short description of changes made beginning with a capital letter and written in the imperative eg. `Update` instead of Updated or Updates. `Update Consul Version to 1.8` works fine, others can go to the body.
- This PR fixes #issue-number 
- Signed commits box should be ticked by adding a small letter [x] in the box and clear white spacing, use preview to see changes made.

Thank you for contributing to open-source and choosing Layer5, we will be glad to have you join our [Slack Community](http://slack.layer5.io)  to help you get involved.

**Review by leecalcote — APPROVED** [review]
Looking good, @Rex739! Here's a short article, which explains the logic behind the "fixes ##" - https://github.blog/2013-01-22-closing-issues-via-commit-messages/

**Review by mgfeller — APPROVED** [review]
Looks good, @Rex739! Thank you for your contribution!

**Comment by leecalcote** [comment]
Ka-pow! 💥 Thank you, @Rex739.

**Comment by PluckyPrecious** [comment]
This PR fixes #1504

**Pull request merged**
