### PR TITLE
[feat] : smooth notification modal appearance

### LINKED ISSUE #7546: [UI] : Notification modal appearance is laggy
#### Current Behavior
Notification modal appearance animation seems little laggy.

https://user-images.githubusercontent.com/76901313/231986117-b0ce8803-a6cf-4d90-a54d-7e586093a691.mov

#### Desired Behavior
It could be smooth.

#### Implementation
A simple css animation.

#### Acceptance Tests
N/A

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by vedant-jain03**
**Notes for Reviewers**

This PR fixes #7546 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by vedant-jain03** [comment]
cc @leecalcote @Chadha93

**Comment by vedant-jain03** [comment]
cc @leecalcote @Chadha93

**Comment by adithyaakrishna** [comment]
@vedant-jain03 Tests are failing and also can you please update your branch?

**Comment by vedant-jain03** [comment]
> @vedant-jain03 Tests are failing and also can you please update your branch?

Will look into it but I think those 2 jobs are failing for others PRs as well @adithyaakrishna

**Review by adithyaakrishna — APPROVED** [review]
LGTM

**Comment by adithyaakrishna** [comment]
@vedant-jain03 Will merge it post the CI process being completed :)

**Review by leecalcote — APPROVED** [review]
Oh, excellent. This is a nice addition, @vedant-jain03 👏

**Comment by leecalcote** [comment]
Thank you for reviewing, @adithyaakrishna

**Pull request merged**
