### PR TITLE
Test: Increase Test Coverage of Doc File

### PR DESCRIPTION
**Pull request by amitamrutiya**
**Notes for Reviewers**

I don't think it's necessary to create an issue for this PR, so I directly made the PR.

- In this PR, I increased the test coverage of the doc file from 63.6% to 83.5%. I believe this will significantly improve unit testing.

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by sudhanshutech** [comment]
@amitamrutiya for such please do create issues

**Comment by amitamrutiya** [comment]
> @amitamrutiya for such changes please do create issues

Next time I will keep that in mind. Sorry for the inconvenience.

**Review by Jougan-0 — APPROVED** [review]

**Comment by Jougan-0** [comment]
@singh1203 if you check and then merge it.

**Review by singh1203 — APPROVED** [review]
LGTM.

**Pull request merged**
