### PR TITLE
Fixed toc.yml URL entries

### PR DESCRIPTION
**Pull request by vedant-kakde**
Signed-off-by: Vedant Kakde <69970950+vedant-kakde@users.noreply.github.com>

**Description**
Fixed toc.yml entries and now pages are routed correctly.

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 1d80e89135f927cea87b4d8bac8cb39e7a92a5a8 at: https://616b263965ff93ae1efee973--meshery-docs-preview.netlify.app

**Comment by alphaX86** [comment]
I don't think this is no way related to issue #3011 the objective is to recreate the page so that newcomers can easily know how and what to do in order to contribute from obtaining info from docs/README file

**Comment by vedant-kakde** [comment]
Hey @alphaX86  , you are right this PR is bit unrelated to the main issue but these URLs need to be fixed and I'm not sure whether I need to recreate that contributing-docs page  or not because in that page more details are covered than the docs readme file. Will you please tell me what more changes are required in this PR ?

**Comment by vedant-kakde** [comment]
@alphaX86 Please merge this one. I'll add those changes in other PR. Thanks.

**Pull request merged**
