### PR TITLE
fix merging of icons with sidebar in codeblock

### LINKED ISSUE #7229: [Docs]Position of icons in codeblock of docs
#### Current State
Currently when opening the side bar the icons of codeblock are above the side bar like [page](https://docs.meshery.io/installation/quick-start) and also scrolling as we move down.

https://user-images.githubusercontent.com/90546692/222105208-f2fb818d-b71b-4a52-9e7b-0a8dc7a749b3.mp4

image

#### Desired State
The icons should be below the sidebar

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by rinkuhasija**
**Notes for Reviewers**

This PR fixes #7229 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit e6adc90e48474c3d8ac44d7682b6bd73d2b3b6e7 at: https://6402757e29b76130f5377700--meshery-docs-preview.netlify.app

**Review by sudhanshutech — APPROVED** [review]
Good work @rinkuhasija

**Comment by vishalvivekm** [comment]
Hey, nice work there @rinkuhasija . The icons no longer show up on sidebar in small screens. 

However, there's some improvement in @chinu-anand 's PR #7264 which also takes care of better visual aspects of the code snippets on the page. 
@leecalcote for you to take a look!

[Screenshot_20230304-125359.jpg](https://user-images.githubusercontent.com/110674407/222882234-a04213bb-e099-4caf-a782-f0c346708b8e.jpg)

**Comment by leecalcote** [comment]
@rinkuhasija @vishalvivekm how would you like to proceed with this PR given the merging of https://github.com/meshery/meshery/pull/7264?

**Comment by vishalvivekm** [comment]
> @rinkuhasija @vishalvivekm how would you like to proceed with this PR given the merging of #7264?

How about closing this pr for now ( as #7264's gonna be merged) and get opportunities for @rinkuhasija to work on other issues?

**Comment by rinkuhasija** [comment]
@vishalvivekm @leecalcote 
I am closing this PR.

**Pull request closed without merging**
