### PR TITLE
Release table text alignment fix

### LINKED ISSUE #7158: [UI] - Version table misaligned cells
#### Current Behavior
In this version table, each cell is misaligned [page](https://docs.meshery.io/project/releases)

#### Desired Behavior
Each cell should be center aligned
#### Screenshots/Logs
image

#### Environment

- Browser: Chrome
- Host OS: Windows

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by gurpreet-legend**
**Notes for Reviewers**

Have fixed the text alignment of table elements in `/project/releases/` page.

This PR fixes #7158 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 00006835209e64314056cb10938188b35df6ac12 at: https://640269549e10cf282bcb88cb--meshery-docs-preview.netlify.app

**Comment by gurpreet-legend** [comment]
@Nikhil-Ladha , @eeshaanSA bug fixed, ready to merge :)

**Review by leecalcote — APPROVED** [review]
Lgtm

**Comment by leecalcote** [comment]
Thank you

**Pull request merged**
