### PR TITLE
Fixed URL Issue

### LINKED ISSUE #4681: [Docs] Page not linked
#### Current State
the highlights red part in the below image is not a link on this [page](https://docs.meshery.io/extensibility/adapters). 

#### Desired State
It should be a link to https://docs.meshery.io/project/contributing.

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by sahilsuman933**
**Description**
Fixed URL Issue

This PR fixes #4681

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 829922579a7abdce54a299ff3447b72aedd50758 at: https://61a2c49ec6e229f5e6d6225b--meshery-docs-preview.netlify.app

**Comment by sahilsuman933** [comment]
@shubham-tyagi Can you please check this PR and approve this.

**Comment by shubham-tyagi** [comment]
great stuff @sahilsuman933, but there is a DCO issue while automatic merging. On a side note you don't have to merge your branch in your master branch it's safe to keep your master branch away from your local commits. Just submit a PR through the branch you made changes in. See this for reference https://docs.meshery.io/project/contributing/contributing-gitflow.

**Review by shubham-tyagi — COMMENTED** [review]
Nice work.

**Comment by shubham-tyagi** [comment]
@warunicorn19 can you tell us exactly why there is a DCO issue here?

**Comment by warunicorn19** [comment]
@shubham-tyagi, it's because of the missing sign-off, @sahilsuman933 are you sure you have a sign-off configured? Like eother switch it on from vscode or add it to your .gitconfig

**Comment by sahilsuman933** [comment]
Maybe because I edited the doc directly from the GitHub.

**Comment by warunicorn19** [comment]
Oh yeah it's because of that. Please follow the link that @shubham-tyagi shared.

**Comment by sahilsuman933** [comment]
@warunicorn19 yeah because I tried to fix this issue using the github directly and I didn't got any way to insert signoff in github

**Pull request closed without merging**
