### PR TITLE
[RJSF] Migration v3-v5, Validation Error Fixes 

### PR DESCRIPTION
**Pull request by Abhishek-kumar09**
**Description**
- v3-v5
- Fix Validation errors and don't show errors for required fields of their parent as optional fields.

TODOS:
- Migration from v3 to v5 is a big change
- The templates, objectfield and arrayfield needs to be updated

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Abhishek-kumar09** [comment]
@harkiratsm

**Comment by leecalcote** [comment]
@harkiratsm, what feedback does our resident RJSF Ninja have?

**Comment by harkiratsm** [comment]
Actually I am still in a state where I am thinking about are patches required, I am testing some stuff at my end with ajv6. By the time I can work on adding the changes we required, and make the migration stuff faster by the end of this week.

Rest All good.

// @leecalcote

**Comment by leecalcote** [comment]
@harkiratsm more detail needed here.

**Comment by leecalcote** [comment]
Demo today, please.

**Comment by leecalcote** [comment]
I don't think the test failure is related to this PR.

**Review by leecalcote — DISMISSED** [review]

**Comment by Abhishek-kumar09** [comment]
final changes awaiting

**Pull request merged**
