### PR TITLE
Remove meshery-perf references

### LINKED ISSUE #10367: [mesheryctl] command for importing design
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

### Desired Behavior

Mesheryctl need command for the import of designs in bulk (as either a directory in URL or as a local file directory).
Command for import design to the meshery server. 
Create neccessary flags like --file .
Add documenation.

### Mockups

---

### Contributor Resources

- ⌨️ [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](http://discuss.meshery.io) and [Layer5 Community Slack](https://slack.meshery.io)

### LINKED ISSUE #10637: [CI] Meshery Helm Charts: References to "meshery-perf" need to change to "meshery-nighthawk"
### Current Behavior
In the Meshery Helm charts, there are invalid references to "meshery-perf" - https://github.com/meshery/meshery/tree/master/install/kubernetes/helm

### Desired Behavior

All references to "meshery-perf" need to change to "meshery-nighthawk"

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
- Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)
- 🧪 [Meshery Test Plan Spreadsheet](https://docs.google.com/spreadsheets/d/13Ir4gfaKoAX9r8qYjAFFl_U9ntke4X5ndREY1T7bnVs/edit#gid=0)

### PR DESCRIPTION
**Pull request by lekaf974**
**Notes for Reviewers**

This PR fixes #10637

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 030d2ad8029bfd85b3f4e07c4bac78a02e54d8cf at: https://66077500bd20168d7f78b40e--meshery-docs-preview.netlify.app

**Comment by vishalvivekm** [comment]
Thank you @lekaf974 
Let's discuss this on websites call. Add this as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#), if you would :)

**Comment by l5io** [comment]
🚀 Preview for commit e4e25260437590829324500497f8297a90c24611 at: https://6609db9cc09bc50fde98bfa4--meshery-docs-preview.netlify.app

**Comment by lekaf974** [comment]
@vishalvivekm I added a suggestion in the doc but I will not b there due to public holiday.

**Comment by l5io** [comment]
🚀 Preview for commit 31799780fdb5a1e3490b1e88dbdbe43938acb0b9 at: https://660ace8de4397f783f6815a9--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 791a6ce8d40769b2b564a6eb6ae6ca6d67e6001d at: https://660b1e55806ae6210ef98792--meshery-docs-preview.netlify.app

**Comment by leecalcote** [comment]
@lekaf974, you have another opportunity to present this in today's Meshery dev meeting...

**Pull request merged**
