### PR TITLE
[Docs] Update "How to Get Your Token" Section for Clarity on Local an…

### PR DESCRIPTION
**Pull request by aryannargotra**
…d Remote Providers

This update clarifies the process of obtaining the authentication token in Meshery by distinguishing between Local and Remote Providers. The "How to Get Your Token" section has been revised to provide specific instructions for each provider type in both the Meshery UI and Meshery CLI. 

Changes include:
- Detailed login instructions for Local and Remote Providers.
- Clear steps for retrieving the token from the Meshery UI.
- Enhanced guidance for using the Meshery CLI to obtain the token.

This addresses issue #12184.

**Notes for Reviewers**

This PR fixes #

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
@ianrwhitney might be interested in this.

**Comment by l5io** [comment]
🚀 Preview for commit ee7b669a6e28a15d7e537731120fe7e349881497 at: https://6706c6ed91cf1c2591e91d3d--meshery-docs-preview.netlify.app

**Review by ianrwhitney — COMMENTED** [review]
LGTM. @leecalcote thanks for pointing this out. 🚀

**Comment by leecalcote** [comment]
Awesome. 🙌 

@aryannargotra, thanks much for jumping and taking care of this. We have the "all clear" from @ianrwhitney. 🚀

**Comment by leecalcote** [comment]
Oh, I just noticed a couple items. I'll make a couple suggestions.

**Comment by aryannargotra** [comment]
> Oh, I just noticed a couple items. I'll make a couple suggestions.

Sure! Please go ahead.

**Comment by l5io** [comment]
🚀 Preview for commit a490ea10cd368b0da0163fef383d5cfc8187053b at: https://670941df2063a6a220ad1677--meshery-docs-preview.netlify.app

**Comment by vishalvivekm** [comment]
@aryannargotra 
Thank you for your contributions! Let's discuss this during the Meshery Development call today at 9:00 AM CT | 7:30 PM IST. Adding it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit?pli=1#) || [meeting link](https://meet.layer5.io/meshery).

**Comment by l5io** [comment]
🚀 Preview for commit bb3743ff0144800d4b68c50f5a32a04df93b532f at: https://670f9a69e21712480f2773c8--meshery-docs-preview.netlify.app

**Pull request closed without merging**
