### PR TITLE
Added RKE2 Installation Guide #11729

### PR DESCRIPTION
**Pull request by subho30666**
**Notes for Reviewers**

This PR fixes #
1)Added RKE2 Installation Guide (rancher.md)
2)Added RKE2 svg
3)Updated toc.yml
rke2

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 2b8e664acf038d2d3138454b55db3071cbd86288 at: https://66c9277fd921d34a3a7a806d--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 6f1ee545c58b99f6468bc2d514220fb2af6f6146 at: https://66c93b279d77675833ca96dc--meshery-docs-preview.netlify.app

**Review by leecalcote — COMMENTED** [review]
@subho30666 thanks.

Is there any unique prerequisite or installation step specific to RKE2? I don't know that I see one in here. If that is the case, we can forego having this page.

// @nunix

**Comment by subho30666** [comment]
> @subho30666 thanks.
> 
> Is there any unique prerequisite or installation step specific to RKE2? I don't know that I see one in here. If that is the case, we can forego having this page.
> 
> // @nunix

All steps are the same;,just we have to set the RKE2 context.

**Comment by leecalcote** [comment]
@subho30666, I certainly appreciate your effort here. Did you install Meshery on RKE2? Using what method?

**Comment by subho30666** [comment]
> @subho30666, I certainly appreciate your effort here. Did you install Meshery on RKE2? Using what method?

This are the exact steps i followed.
1)curl -L https://meshery.io/install | PLATFORM=kubernetes bash -
2)kubectl config use-context default
3)mesheryctl system config set --context default
4)mesheryctl system start
here default was my rke2 context

**Comment by subho30666** [comment]
@leecalcote  Could you please let me know if I need to revise, add, or remove anything in my contribution to get the PR merged? I used the curl method to install Meshery on RKE2, following the style of the MiniKube installation guide.

**Comment by Ashparshp** [comment]
@subho30666, let's discuss this PR during the Meshery dev meeting call, if you would. Please add it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit?usp=drivesdk).

**Comment by subho30666** [comment]
@Ashparshp  okay i will add this

**Pull request closed without merging**
