### PR TITLE
removing test files to view ci performance

### LINKED ISSUE #8429: [CI] Low CodeCov report analysis for mesheryctl
#### Current Behavior
From  Codecov CI reports,   the coverage doesn't seem to increase its still at the same percentage rate , I was looking at the code coverage for the filter and pattern package , it seems the codecov metrics don't seem to read the unit tests.
From this issue i raised [here](https://github.com/meshery/meshery/issues/8241) few weeks back, the filter package still has the same [report](https://app.codecov.io/gh/meshery/meshery/tree/master/mesheryctl%2Finternal%2Fcli%2Froot%2Ffilter) upon we had new  unit test that were created and adjusted. 
The config.go doesn't have any [coverage](https://app.codecov.io/gh/meshery/meshery/tree/master/mesheryctl%2Finternal%2Fcli%2Froot) at all and multiple unit tests were created and passed .

Here is the total codecov report for the` root package` is still at `15%`  from the report [here](https://app.codecov.io/gh/meshery/meshery/tree/master/mesheryctl%2Finternal%2Fcli%2Froot)
The report for the `pkg` is still at 0%  [here](https://app.codecov.io/gh/meshery/meshery/tree/master/mesheryctl%2Fpkg%2Futils).

The total codecov report for mesheryctl is still at `15%`

#### Desired Behavior
Make necessary implementations for  Mesheryctl to hit the` 80%` codecov margin.

#### Implementation
Writing effective unit tests and making sure they all pass to increase coverage. 
Like the image below
delete-test

here is a [guide](https://discuss.layer5.io/t/how-to-write-unit-integration-tests-for-mesheryctl/285) to writing tests

#### Acceptance Tests

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
- Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)
- 🧪 [Meshery Test Plan Spreadsheet](https://docs.google.com/spreadsheets/d/13Ir4gfaKoAX9r8qYjAFFl_U9ntke4X5ndREY1T7bnVs/edit#gid=0)

### PR DESCRIPTION
**Pull request by Philip-21**
**Notes for Reviewers**

This PR fixes #8429 
NOTE, this not a pr fix , it is just a random check to view performance of codecov 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Got it. 👍

**Comment by Philip-21** [comment]
> ## [Codecov](https://app.codecov.io/gh/meshery/meshery/pull/8441?src=pr&el=h1&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=meshery) Report
> Patch coverage has no change and project coverage change: **`+0.90%`** 🎉
> 
> > Comparison is base [(`a9b53a0`)](https://app.codecov.io/gh/meshery/meshery/commit/a9b53a0ecbcf3b80dcd1ccb6204453ab40037b3f?el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=meshery) 5.20% compared to head [(`504c66e`)](https://app.codecov.io/gh/meshery/meshery/pull/8441?src=pr&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=meshery) 6.11%.
> > Report is 109 commits behind head on master.
> 
> > ❗ Current head [504c66e](https://github.com/meshery/meshery/commit/504c66e58b0375c2236868aa6c6c86b31e647c2c) differs from pull request most recent head [f23b5a4](https://github.com/meshery/meshery/commit/f23b5a4c15afcd429651032538d1f3cb2ce0cfd6). Consider uploading reports for the commit [f23b5a4](https://github.com/meshery/meshery/commit/f23b5a4c15afcd429651032538d1f3cb2ce0cfd6) to get more accurate results
> 
> Additional details and impacted files
> [☔ View full report in Codecov by Sentry](https://app.codecov.io/gh/meshery/meshery/pull/8441?src=pr&el=continue&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=meshery). 📢 Have feedback on the report? [Share it here](https://about.codecov.io/codecov-pr-comment-feedback/?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=meshery).

Resend Bot for latest commit

**Comment by l5io** [comment]
🚀 Preview for commit f824e85c97a5f0c15d0dc5c7f67e5909bdd778d8 at: https://64d6074b0a5e86489e8feb9d--meshery-docs-preview.netlify.app

**Comment by Philip-21** [comment]
test2-gen

From the above image all the unit tests have been removed from the whole mesheryctl package , codecov doesn't read any coverage at all since the unit tests aren't present . CodeCoverage for mesheryctl is `0%`

**Comment by l5io** [comment]
🚀 Preview for commit 968a75938a95e14f4bf417c463f426b403875daf at: https://64d7d52daee1732ad48eff72--meshery-docs-preview.netlify.app

**Comment by vishalvivekm** [comment]
@Philip-21 Let's discuss this on Meshery Dev call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#) if you would. :)

**Pull request closed without merging**
