### PR TITLE
[WIP] Updating operator docs

### PR DESCRIPTION
**Pull request by metonymic-smokey**
**Description**
This PR adds documentation on updating/upgrading operators in the docs.

This PR fixes # 148 from meshery-operator

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by metonymic-smokey** [comment]
Reviewers,
1. I think this snippet from `update.go` is extraneous:  
https://github.com/meshery/meshery/blob/80616857c36f2177b5551086f5f1ac9eb6ee1f71/mesheryctl/internal/cli/root/system/update.go#L184-L187
I think it should be removed?  

2. In `update.go`, in a docker deployment, operator manifests are not updated like in the case of a k8s deployment. I think both docker and k8s should have identical behaviour in updating operators?

Let me know what you think, I can make the changes in this PR itself.

**Comment by l5io** [comment]
🚀 Preview for commit 8e17a9f47ba67da485e6e9337825d633f3ebb806 at: https://610ec6ae185b20547d91c2b5--meshery-docs-preview.netlify.app

**Comment by leecalcote** [comment]
> Reviewers,
> 
> I think this snippet from `update.go` is extraneous:  
> 
> https://github.com/meshery/meshery/blob/80616857c36f2177b5551086f5f1ac9eb6ee1f71/mesheryctl/internal/cli/root/system/update.go#L184-L187
> 
> I think it should be removed?  
> 
> 
> 
> Let me know what you think, I can make the changes in this PR itself.  
> 
> 

Gosh, it sure seems that way to me (extraneous).

**Comment by metonymic-smokey** [comment]
> Gosh, it sure seems that way to me (extraneous).

The things that go unnoticed in reviews xD

**Comment by l5io** [comment]
🚀 Preview for commit 1b91aab5da4ff42ca06e666605235824c0940cd9 at: https://610ecb6829cc9170baba7599--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 42cb48812892b213b24b261a488dc7f50be408a9 at: https://610fe9de842ddb38195fc568--meshery-docs-preview.netlify.app

**Comment by metonymic-smokey** [comment]
@leecalcote pls let me know if there is any way I can improve the operator upgrade parts.
Thanks!

**Comment by l5io** [comment]
🚀 Preview for commit 642d004237b079054ee316c3f117e19133d0da2c at: https://6110f4ed2175631ea36a050c--meshery-docs-preview.netlify.app

**Review by leecalcote — APPROVED** [review]
LGTM

**Pull request merged**
