### PR TITLE
[DOCS] Swagger REST API update for Applications

### PR DESCRIPTION
**Pull request by Chadha93**
Signed-off-by: Gaurav Chadha <gauravchadha1676@gmail.com>
**Description**
 

- [x] Swagger REST API update for Applications 
- [x] Tested OK on swagger servers.

**Notes for Reviewers**
Please do watch the video.

https://user-images.githubusercontent.com/65453826/187045085-b125b0a3-3914-4ddb-a6ba-ef47010bad19.mp4

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 7ce444aa83c76bf5d160ddb3e27015e93601f4a8 at: https://630a70b04e7d9630d8f3504b--meshery-docs-preview.netlify.app

**Comment by leecalcote** [comment]
Does the "Try out!" button work, @Chadha93?

**Comment by Chadha93** [comment]
> Does the "Try out!" button work, @Chadha93?

Yes

**Comment by Chadha93** [comment]
Ahh, not showing APIs in the build preview. :eyes: :crying_cat_face:

**Comment by Chadha93** [comment]
@piyushsingariya ^^

**Comment by l5io** [comment]
🚀 Preview for commit cd3f9d5e53c8545df2c22a569e1fb40a756af976 at: https://630a7e3b6d86c23cf09688d2--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit b56f1dc765d9b76eecec48e2e8f128d090357329 at: https://630a7fc97ca5613e29983f22--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 05deb045c64ab373582cefdccda5649b307489a1 at: https://630a8142a0b05a42f87bbc1d--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 419e5f6a7dcf852cb715aac8710091086b5419cc at: https://630a88b8319afc45c6609d16--meshery-docs-preview.netlify.app

**Comment by Chadha93** [comment]
@piyushsingariya the docs are building fine locally and swagger too, but still not built on preview, We don't need to push swagger.yaml right? Referred this https://docs.google.com/document/d/1YnpJs6D_arzuE5ieqMyuJs3A3UYSVp9YZYhbc966sWg/edit

image

**Comment by piyushsingariya** [comment]
The workflow run on the merge, @Chadha93 you can change it to run on every commit push and pull-requests.

**Comment by Chadha93** [comment]
> The workflow run on the merge, @Chadha93 you can change it to run on every commit push and pull-requests.

@piyushsingariya It's already set on pull_requests and synchronize(every commit push) https://github.com/meshery/meshery/blob/master/.github/workflows/build-and-preview-site.yml

**Comment by leecalcote** [comment]
Does the build preview workflow include the swagger build, too?

**Comment by leecalcote** [comment]
If this PR is merged, will your changes be overwritten, @Chadha93? If not, and the only issue is that you're not getting a deployment preview with these changes, then that issue can be filed separately for someone in the CI workgroup to pick up.

**Comment by Chadha93** [comment]
> If this PR is merged, will your changes be overwritten, @Chadha93? If not, and the only issue is that you're not getting a deployment preview with these changes, then that issue can be filed separately for someone in the CI workgroup to pick up.

It should not, we may merge and see if that works or not.

**Pull request merged**
