### PR TITLE
initial commit for versioning

### PR DESCRIPTION
**Pull request by warunicorn19**
Signed-off-by: Aditya Chaterjee <speak2adi@gmail.com>

**Description**
Trying out versioning of docs. Versioning for only v0.1 has been done till now, making PR to keep track of progress
This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 862bcfb30d5f54badea6ab406e17f7fafb386422 at: https://617d1aa918edaa625bf0de96--meshery-docs-preview.netlify.app

**Comment by warunicorn19** [comment]
Preview for commit: https://617d1aa918edaa625bf0de96--meshery-docs-preview.netlify.app/v0.1/ 

Further things to do: 
- [ ] change internal links according to versions
- [ ] Fix TOC to redirect to specific version.
- [ ] Footer issues

**Comment by alphaX86** [comment]
@warunicorn19 great work going on here. I saw your PR and impressive work! But I feel the idea of keeping version folders and showing them.... won't be a huge overload? Why not use tags in docs? Like if we mention one, then the version tag should be fetched from all docs and if match is found, print them. Else, keep it hidden.

Did you think of this perspective? I guess some work will be indeed involved but reduces overload

**Comment by warunicorn19** [comment]
@alphaX86 yup using tags did occur to me as well, but I'm not sure if we can pass multiple versions in a tag, like we might want a particular file to be present in multiple versions, i don't think that is something we would be able to do with tags. 

Can we put in multiple fields in one tag?

**Comment by warunicorn19** [comment]
But, yes we'll really have to take a look the repo size constraints. Though, as of now, I've put in everything in all versions, so I'll be deleting a lot of stuff as well, let's see what happens.

**Comment by warunicorn19** [comment]
uh-oh i deleted this fork 🥲

**Comment by warunicorn19** [comment]
i deleted this fork and clone, opening a new PR.

**Comment by alphaX86** [comment]
😅 ok...

**Pull request closed without merging**
