### PR TITLE
Discuss tag branch

### PR DESCRIPTION
**Pull request by kayceeDev**
**Notes for Reviewers**

This PR fixes #6773 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit a7ebe491ec515291778e952d97a279e1e8b7947e at: https://63a976310a3d6b7aa0c26f03--meshery-docs-preview.netlify.app

**Comment by leecalcote** [comment]
merge conflict

**Comment by l5io** [comment]
🚀 Preview for commit 7e2cd504e3629ae7ce9425271233706b906d3b63 at: https://63ade967be17be244b5d0999--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 595d5bc8bc9306171f7acc3026609e3a37e67bb5 at: https://63adeb3e227e0b22f4fcccba--meshery-docs-preview.netlify.app

**Review by leecalcote — COMMENTED** [review]
Looking good aesthetically. Visiting this page (https://63adeb3e227e0b22f4fcccba--meshery-docs-preview.netlify.app/reference), I suppose we'll want to limit the number of rows shown to 10 bullet points.

**Comment by leecalcote** [comment]
@kayceeDev something that you'll do or no?

**Comment by kayceeDev** [comment]
> @kayceeDev something that you'll do or no?

Like you suggested in the last meeting, it is great to make this API calls directly and then limit the result to 10. That I will also look into. For the current implementation I can just reduce the number of posts in the JSON to 10. Unavoidably, more fixes are definitely required.

**Comment by leecalcote** [comment]
> > @kayceeDev something that you'll do or no?
> 
> Like you suggested in the last meeting, it is great to make this API calls directly and then limit the result to 10. That I will also look into. For the current implementation I can just reduce the number of posts in the JSON to 10. Unavoidably, more fixes are definitely required.

No, the Jekyll query/loop can simply be limited to 10, @kayceeDev.

**Comment by leecalcote** [comment]
@asubedy will you implement a LIMIT here? It can be done in the same or a separate PR.

**Comment by kayceeDev** [comment]
> > > @kayceeDev something that you'll do or no?
> > 
> > 
> > Like you suggested in the last meeting, it is great to make this API calls directly and then limit the result to 10. That I will also look into. For the current implementation I can just reduce the number of posts in the JSON to 10. Unavoidably, more fixes are definitely required.
> 
> No, the Jekyll query/loop can simply be limited to 10, @kayceeDev.

Done.

**Comment by l5io** [comment]
🚀 Preview for commit 09d0d12a94b7a35e1ec0dd7639ba58198fd0f7bd at: https://63b25d16b904780b763e6d79--meshery-docs-preview.netlify.app

**Comment by asubedy** [comment]
@kayceeDev, can you add [this](https://github.com/meshery/meshery.io/blob/bef677f6d2684fabe1c3e1746ae36449068cbc83/_includes/related-discussion.html#L24) section so that the correct author of the post is shown

**Review by asubedy — CHANGES_REQUESTED** [review]
@kayceeDev can you add [this](https://github.com/meshery/meshery.io/blob/bef677f6d2684fabe1c3e1746ae36449068cbc83/_includes/related-discussion.html#L24) section so that correct author are shown for the post

**Comment by l5io** [comment]
🚀 Preview for commit bb70a89effcb428fc42252540a560ec8b455d722 at: https://63b5818f84a58275869fe378--meshery-docs-preview.netlify.app

**Review by leecalcote — APPROVED** [review]
Good work. Nice collaboration. 🥇

**Pull request merged**
