### PR TITLE
[UPDATED] config for default context

### LINKED ISSUE #7794: [mesheryctl] Default config update required
#### Current Behavior
Currently the default context for mesheryctl has all the components.
```
Current Context: local

endpoint: http://localhost:9081/
token: Default
token-location: auth.json
platform: kubernetes
components:
- meshery-app-mesh
- meshery-istio
- meshery-linkerd
- meshery-consul
- meshery-nsm
- meshery-kuma
- meshery-osm
- meshery-traefik-mesh
- meshery-nginx-sm
- meshery-cilium
channel: stable
version: latest
```

#### Desired Behavior

```
Current Context: local

endpoint: http://localhost:9081/
token: Default
token-location: auth.json
platform: kubernetes
components:
channel: stable
version: latest
```

#### Implementation
The deploying & undeploying of adapters by a meshery server has been added by [this PR](https://github.com/meshery/meshery/pull/7378). User can deploy/undeploy any adapters using that feature.

#### Contributor Resources

- ⌨️ [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by zakisk**
**Notes for Reviewers**

This PR fixes #7794

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
What testing have you done with this change?

**Comment by suhail34** [comment]
This is the compose file from where we extract info about services(adaptars)  images based on the component entries in config.yaml and start the meshery server. And this compose file are downloaded from latest release tag

**Comment by vishalvivekm** [comment]
@zakisk Let's discuss this on Meshery Dev call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#) if you would. :)

**Comment by abdullah1308** [comment]
@suhail34 Yes you are right. You're not supposed to make changes to this file. This compose file is used to fetch information about the containers for meshery adapters. 

The approach taken to deploy adapters is as follows -

1. Mesh config (~/.meshery/config) is read in
2. The compose file is downloaded
3. The containers for the components that are mentioned in the mesh config are deployed. 

This can be seen here -

https://github.com/meshery/meshery/blob/a085ea761d72d07613fa942ef8629731e0e19095/mesheryctl/internal/cli/root/system/start.go#L186-L274

**Comment by zakisk** [comment]
@abdullah1308 @suhail34 I've tested it, it works fine, [docker-compose.yaml](https://docs.divio.com/en/latest/reference/docker-docker-compose/#services-defined-in-docker-compose-yml) serves the purpose of deploying containers in docker and then `config.yaml` file in `.meshery` folder is created upon information which containers are deployed, that's the reason I think it must be edited.

**Pull request closed without merging**
