### PR TITLE
Refactor YAML structure to a single file (for mesheryctl reference)

### LINKED ISSUE #3977: [Docs] (child) Rework YAML structure for `mesheryctl` reference in docs
#### Current State
The mesheryctl reference fetches data from YAML files and because of this many files are created which makes it hard and clumsy to maintain. 

#### Desired State
The YAML files must be restructured completely and remove unnecessary files if found. 

(Inspired from Lee's suggestion) 

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by alphaX86**
**Description**

This PR fixes #3977 

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 0c90e7b441da7a4b80d60460d48a9aff940b46fb at: https://612663d3cc84f8f0d4b887dc--meshery-docs-preview.netlify.app

**Comment by afzal442** [comment]
hey @alphaX86, thanks for the PR, could do you also update this work once these PRs #3889 #3841 get merged? otherwise, we can have conflict issues.

What do you think?

**Comment by warunicorn19** [comment]
@afzal442 i think its best to hold all other mesheryctl docs PRs until this is merged, this I feel is a priority. after this is done, we can pull this and make the changes accordingly, it'll be much easier

**Comment by l5io** [comment]
🚀 Preview for commit 1f9b3dce618938fd968024e03a9cee8afe9b944a at: https://6129eb284a8cabd299cc873d--meshery-docs-preview.netlify.app

**Comment by alphaX86** [comment]
@leecalcote @adithyaakrishna mapping of new data is almost done. Only remaining part is to map data to the reference table

**Comment by l5io** [comment]
🚀 Preview for commit a94dfe5640fa81b1754e2c4b50d0238d0634a037 at: https://612a08c4f26662e6537b44d8--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 6052190898c9417c462eb044ff65ca31326369b6 at: https://612f13062b6c1d6606b59881--meshery-docs-preview.netlify.app

**Comment by alphaX86** [comment]
@leecalcote the mapping for subcommand pages is done, but I find it difficult when trying to access the variables on loop and fetch those data. So should I hardcode them like `{% assign var = site.data.mesheryctlcommands.cmds.global %}` (this one works but problem is we need to declare every time in order to fetch a command/subcommand)

Or you need variables like `{% assign var = site.data.mesheryctlcommands.cmds[page.commands][0] %}` like that (this one didn't work and I need to figure out why)

**Comment by alphaX86** [comment]
Oh I didn't delete that multiple YAML files because of this, if we can find a solution then we can safely delete those YAML files and keep it as one

**Comment by l5io** [comment]
🚀 Preview for commit e8e9693866be16f0964abf383c1bac771ca57c5f at: https://61321f4f1bfb012919dca071--meshery-docs-preview.netlify.app

**Comment by alphaX86** [comment]
> @leecalcote the mapping for command and subcommand pages is done, but I find it difficult when trying to access the variables on loop and fetch those data on reference table. So should I hardcode them like `{% assign var = site.data.mesheryctlcommands.cmds.global %}` (this one works but problem is we need to declare every time in order to fetch a command/subcommand)

Since no reply is made, I hardcoded them to reference variables. It worked and it's up and running

**Comment by l5io** [comment]
🚀 Preview for commit 003c06eb8faaa5469abb95fd155276bde36c56d7 at: https://61322b05f37407389ffd2e2e--meshery-docs-preview.netlify.app

**Comment by alphaX86** [comment]
Just curious... when the review will get over? Coz some PRs are made to hold for long time because of me :')

**Review by leecalcote — APPROVED** [review]
@alphaX86, you’ve done it! This has to feel good. 😄 Nice work.

**Pull request merged**
