### PR TITLE
[mesheryctl] platform: kubernetes support for `system stop` command

### LINKED ISSUE #2311: [mesheryctl] [child] make `system stop` platform aware(`platform: kubernetes`)
See Epic #2307 for context and further description of this issue.

**Current Behavior**

`mesheryctl system stop` by default stops all Meshery server and Adapters' containers and does not consider for Kubernetes platform.

**Desired Behavior**

`mesheryctl system stop` considers current platform and for `platform: kubernetes` it should delete all deployments made by Meshery. (Should be done using [Kubernetes Go client](https://github.com/kubernetes/client-go)- by importing [MeshKit](https://github.com/layer5io/meshkit))

_Do not use system-level calls to a bash script like_ `$ kubectl delete -f` .

### PR DESCRIPTION
**Pull request by pottekkat**
Signed-off-by: navendu-pottekkat <navendupottekkat@gmail.com>

**Description**

This PR fixes #2311

mesheryctl now checks for the `platform` of the `current-context` and if the platform is kubernetes, it will delete all deployments made by Meshery. The user can also use the `--context` flag to switch contexts.

The logic of the case when the platform is docker is unchanged.

Screenshot from 2021-03-02 19-14-20

As shown above the pods are terminated when the platform is kubernetes.

This is done using the manifest files present in the `.meshery/manifests` folder and the adapters specified in the `config.yaml` file. 

**Notes for Reviewers**

- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
What a great write-up.

**Comment by leecalcote** [comment]
A couple lint items to look into...

**Comment by navendu-pottekkat** [comment]
@leecalcote Fixed lint errors. I always forget to lint check locally and only realise it until I see the red cross mark on the PR.

**Comment by leecalcote** [comment]
Quick check - do we warn the user and ask for confirmation in order to delete the Meshery deployment?

**Comment by navendu-pottekkat** [comment]
> Quick check - do we warn the user and ask for confirmation in order to delete the Meshery deployment?

Nope. I also thought about it since we will be deleting the deployments in kubernetes as opposed to just stopping the containers in docker. But since we are not asking this for docker, I did not add it here.

**Comment by leecalcote** [comment]
@navendu-pottekkat, given the behavior differences, it's good to consider either changing the command name to `delete` or prompting the user for confirmation - https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit?disco=AAAALLkU8Ck

**Comment by navendu-pottekkat** [comment]
@leecalcote I think it would be best if we add a user prompt since stop makes more sense in the case of docker.

**Comment by navendu-pottekkat** [comment]
@leecalcote I have added the user prompt similar to what we have for the reset command. Please check and suggest if there are any changes needed to the PR

**Review by leecalcote — APPROVED** [review]
Looking good.

**Pull request merged**
