### PR TITLE
Workflow for deleting current context

### LINKED ISSUE #2959: [mesheryctl] `system context delete` does not handle deleting the `current-context`
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior

`mesheryctl system context delete <current-context name>` will delete the `current-context` leaving the `current-context` empty.

This will result in other commands failing.

#### Desired Behavior

Instead, `mesheryctl` could automatically set another context as the `current-context` or let the user decide which context to set from an interactive list.

This should also prevent the user from deleting the context if that is the only remaining context.

Please discuss the specifics on how this should be implemented below.

---

#### Contributor Resources

- [mesheryctl Contributing Guide](https://github.com/layer5io/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by metonymic-smokey**
**Description**
This PR currently asks the user whether they wish to delete the current context. If the user confirms, the user can then select the next current context from an interactive list using arrow keys.  

This PR fixes #2959 

**[Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by metonymic-smokey** [comment]
@navendu-pottekkat @leecalcote currently this allows an interactive selection of context based on arrow keys, when the user is deleting current context.    
Could you please give me an idea on what is the expected workflow when done using flags/commandline arguments?  

Thanks!

**Comment by metonymic-smokey** [comment]
@navendu-pottekkat could you tell me which lines to remove to resolve this conflict in `go.sum` ? 

Thanks!

**Comment by navendu-pottekkat** [comment]
@metonymic-smokey yep the resolve looks good

**Review by leecalcote — DISMISSED** [review]
Really neat, @metonymic-smokey 👍

**Pull request merged**
