### PR TITLE
Addd SMI Conformance as a feature to Istio Adapter

### LINKED ISSUE #1474: [Docs] List SMI Conformance as a feature of Kuma adapter
**Current State:**
The documentation for the [Meshery adapter for Kuma](https://meshery.layer5.io/docs/service-meshes/adapters/kuma) is missing a list and description of all of the operations that it supports. 

**Desired State:**
Another supported feature of the adapter for Kuma is SMI Conformance - https://meshery.layer5.io/docs/functionality/smi-conformance. This needs to be highlighted as  functionality in each of the adapter docs.

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

### PR DESCRIPTION
**Pull request by ghost**
**Added SMI Conformance Capability as a feature of the Istio Adapter **

This PR fixes #1474

**Notes for Reviewers**

The SMI conformance capability docs that I have been using was coined from a google document. For the istio adapter, there are 5 main features listed. I added the SMI conformance capability as the 6th one and gave a little more detail. I think that a small summary is all that is necessary. Then a read more link can direct readers to the SMI Conformance capability main file so that the adapters do not get cluttered. If my summary is not the best, I am willing to make changes.

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X ] Yes, I signed my commits.

### CODE REVIEW

**Comment by KarenEfereyan** [comment]
I forgot to sign the last commit. Now im having to go through some unnecessary stress.

**Comment by PluckyPrecious** [comment]
Hello @KarenEfereyan the mastery is in the stress 😄 , just run these commands to sign [DCO](https://github.com/layer5io/meshery/pull/1493/checks?check_run_id=1045681297) also do well to edit these 👇🏽 

The  subject should be -  `Add SMI Conformance as feature to Istio Adapter`
Signed commits should be a small letter `x` in the box and clear the white spacing. and viola! 😉

**Comment by KarenEfereyan** [comment]
> Hello @KarenEfereyan the mastery is in the stress 😄 , just run these commands to sign [DCO](https://github.com/layer5io/meshery/pull/1493/checks?check_run_id=1045681297) also do well to edit these 👇🏽 
> 
> The  subject should be -  `Add SMI Conformance as feature to Istio Adapter`
> Signed commits should be a small letter `x` in the box and clear the white spacing. and viola! 😉 

The mastery is the koko o
 I will fix it

**Comment by leecalcote** [comment]
@KarenEfereyan would you like to have another go at this one?

**Comment by KarenEfereyan** [comment]
> @KarenEfereyan would you like to have another go at this one?

With all pleasure

**Comment by KarenEfereyan** [comment]
> @KarenEfereyan would you like to have another go at this one?

@leecalcote I have fixed it. I have cut down the SMI conformance capability. Can you please review?

**Comment by KarenEfereyan** [comment]
I signed my commits this time but I am still getting errors. I am using this [link](https://github.com/layer5io/meshery/pull/1493/checks?check_run_id=1100370602) but I am still not getting it. Crying face... @PluckyPrecious

**Comment by PluckyPrecious** [comment]
Hi Karen no worries 😉 run git `rebase HEAD~6 --signoff`  Next run

`git push --force-with-lease origin AddSMIToIstio`

**Comment by KarenEfereyan** [comment]
> Hi @KarenEfereyan  no worries 😉 run git `rebase HEAD~6 --signoff`  Next run
> 
> `git push --force-with-lease origin AddSMIToIstio`, the issue is the force push isn’t reflecting. Alternatively you could remove other conflicting files. Beep me on slack let get it done.

Will do right now..im so annoyed😂😂😂

**Comment by KarenEfereyan** [comment]
> Hi @KarenEfereyan no worries 😉 run git `rebase HEAD~6 --signoff` Next run
> 
> `git push --force-with-lease origin AddSMIToIstio`, the issue is the force push isn’t reflecting. Alternatively you could remove other conflicting files. Beep me on slack let get it done.

It was absolutely my fault

**Comment by KarenEfereyan** [comment]
@lee this PR references [this](https://github.com/layer5io/meshery/issues/1474). But it seems to have been closed. Can this PR be closed then too? To avoid confusion

**Pull request closed without merging**
