### PR TITLE
fix: Use `COPY` instead of `ADD` for files and folders

### PR DESCRIPTION
**Pull request by iamrajiv**
## Description

Although `ADD` and `COPY` are functionally similar, generally speaking, `COPY` is preferred. That’s because it’s more transparent than `ADD`. `COPY` only supports the basic copying of local files into the container, while `ADD` has some features (like local-only tar extraction and remote URL support) that are not immediately obvious.

### CODE REVIEW

**Comment by iamrajiv** [comment]
@bariqhibat Please check this PR the last PR was close automatically when I did force push.

**Review by bariqhibat — APPROVED** [review]
Looks good to me!

**Comment by iamrajiv** [comment]
@leecalcote

**Comment by leecalcote** [comment]
I'm still looking for a compelling reason to switch. Any change to the project is a risk. Without any stated benefit other than this is a best practice and provides additional transparency.... we haven't hit the threshold for risk vs reward here.

Instead, I would love to see PRs that are dropping the image size of Meshery Server. _That_ is very much needed.

**Comment by leecalcote** [comment]
The addition of swagger / api docs just added another ~200MB, I think.

**Pull request closed without merging**
