### PR TITLE
Docs- Add token fetching information to API Refs.

### PR DESCRIPTION
**Pull request by b0id**
**Notes for Reviewers**

I added the images, for clarity, but will remove if only text is needed, another solution is a simple link.  

There is a broken link for Meshery UI, I did not repair, I can append this PR or submit separate issue. I opted for the later.

This PR fixes # 6994 #6993 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit aeeaa1014f33049262c269df29a7c14b53df88fd at: https://63e5ae5384a8c733ab51be68--meshery-docs-preview.netlify.app

**Review by leecalcote — APPROVED** [review]
This is well-done, @b0id. I'm having a difficult time finding anything that needs changed. 

Nice work.

**Comment by Chadha93** [comment]
@b0id  Let's discuss this on the Meshery Dev call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#) if you would. :)

**Review by leecalcote — APPROVED** [review]
@vishalvivekm are your recent changes aligned with this update or do you need to incorporate this new reference?

**Comment by b0id** [comment]
Will update @leecalcote

**Comment by l5io** [comment]
🚀 Preview for commit ee4920a346f72790ae51814afaea319a7d73fcd9 at: https://63ec6cc949679b6042e001f1--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit c9a506b4876878792690510d9decd503e845e5bd at: https://63ec6f8bfd3bd868379ccb49--meshery-docs-preview.netlify.app

**Review by leecalcote — APPROVED** [review]
¡Excellenté!

**Comment by vishalvivekm** [comment]
> @vishalvivekm are your recent changes aligned with this update or do you need to incorporate this new reference?

Yes, they did.
 As @b0id said above to update the same broken link in both the API Refs Guides ([GraphQL](https://docs.meshery.io/reference/graphql-apis) and [REST API](https://docs.meshery.io/reference/rest-apis) ), I'm gonna go create a new issue and then tackle it myself there for you to review it and then merge if it'd look good enough :) 
@leecalcote

**Comment by vishalvivekm** [comment]
> > @vishalvivekm are your recent changes aligned with this update or do you need to incorporate this new reference?
> 
> Yes, they did. As @b0id said above to update the same broken link in both the API Refs Guides ([GraphQL](https://docs.meshery.io/reference/graphql-apis) and [REST API](https://docs.meshery.io/reference/rest-apis) ), I'm gonna go create a new issue and then tackle it myself there for you to review it and then merge if it'd look good enough :) @leecalcote

Done in PR #7116
@leecalcote

**Pull request merged**
