### PR TITLE
Registry log dynamic

### PR DESCRIPTION
**Pull request by Jougan-0**
**Notes for Reviewers**

This PR fixes #10567 

Handles all the registration using my local repo [meshkit](https://github.com/meshery/meshkit/pull/499) needs to merge it first .
Event offset issue fix [Pr](https://github.com/meshery/meshery/pull/11064) needs to be merged to for this pr to work perfectly.

- [x] - Replaced instance of owner Id with the system ID that is instance Id .
- [x] - Logs are written every time the RegistryEntity function is called.
- [x] - For different registration if you want just need to call the HandlerError function with that host will work with all the registrants .
- [x] - Use A file under ./meshery/logs that is created at the start when server runs and then it is written by the variable whenever the RegistryAttempts is updated.
- [x] - Changed the Name of function and endpoint to be more generic and that makes better sense.
- [x] Kubernetes Event Updated.
- [x] Handles Multiple Registrants.
- [x]  Logs format update.
- [x]  Docs dry run built done .
image
image

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**

- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Jougan-0** [comment]
- [ ] Kubernetes Event Updated.
- [ ] Handles Multiple Registrants.
- [ ] Logs format update.
- [ ] Docs dry run built done .

**Comment by leecalcote** [comment]
@Jougan-0 is there anything left here or are we merge-ready?

**Comment by Jougan-0** [comment]
> @Jougan-0 is there anything left here or are we merge-ready?
> 
>  

For kubernetes if I remember correctly the event was not sent properly. Double checking and conforming.

**Comment by Jougan-0** [comment]
The meshkit needs to be merged first and then the go mod needs update.

**Comment by leecalcote** [comment]
> The meshkit needs to be merged first and then the go mod needs update.

Got it. Ok, good to go - https://github.com/meshery/meshkit/releases/tag/v0.7.33

**Comment by leecalcote** [comment]
```
Error: server/helpers/common_registry_logs.go:68:20: undefined: meshmodel.ErrEmptySchema
```

**Comment by Jougan-0** [comment]
> ```
> Error: server/helpers/common_registry_logs.go:68:20: undefined: meshmodel.ErrEmptySchema
> ```

Fixing Those it's the meshkit.

**Comment by Jougan-0** [comment]
> ```
> Error: server/helpers/common_registry_logs.go:68:20: undefined: meshmodel.ErrEmptySchema
> ```

Fixed.

**Comment by Jougan-0** [comment]
@leecalcote This one good to go as well, if we update the meshkit release this needs to merge or release will break.

**Pull request merged**
