### PR TITLE
[UI] Added avatar in design card

### PR DESCRIPTION
**Pull request by Yashsharma1911**
**Notes for Reviewers**

This PR fixes #

Screenshot 2023-11-15 at 8 19 50 PM

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Can we find a spot on the back of the card for this Owner avatar?

**Comment by leecalcote** [comment]
> Can we find a spot on the back of the card for this Owner avatar?

@Yashsharma1911, please move to the backside of the card.

**Comment by Yashsharma1911** [comment]
How does this look?

Screenshot 2023-11-25 at 11 30 43 AM

**Comment by Yashsharma1911** [comment]
Moving forward here, I moved the avatar to back

**Pull request merged**
