### PR TITLE
Navigation links fixed

### PR DESCRIPTION
**Pull request by iArchitSharma**
**Notes for Reviewers**

Server events link fixed in naviagtion
Filter sub-section under Logical removed as it does not exist

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 586506685f1d43c58e52bd9defcb94517bd142b1 at: https://656a415078668a35e47fd306--meshery-docs-preview.netlify.app

**Comment by leecalcote** [comment]
The down arrow indicates that the item has children.

**Comment by l5io** [comment]
🚀 Preview for commit e93cd76b6c3333991da3d6b8da02a4a2ccbf6b59 at: https://656ae3451bfe421a6501acba--meshery-docs-preview.netlify.app

**Review by leecalcote — APPROVED** [review]
Lgtm

**Pull request merged**
