### PR TITLE
fix: add a flag to save operations Notifications

### PR DESCRIPTION
**Pull request by harkiratsm**
Signed-off-by: harkiratsm <multaniharry714@gmail.com>

**Notes for Reviewers**

This PR fixes #

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by harkiratsm** [comment]
@Revolyssup Context - https://app.clickup.com/t/2me48ef?comment=1429336115

**Comment by leecalcote** [comment]
What does this look like in terms of a general model that all events adhere to?

**Comment by harkiratsm** [comment]
Even though the save is false by default still, we were seeing the snackbar that pattern has been saved during the cyto conversion, the function ```formatPatternOutput``` is being used for the save true as well as false also. so I added an additional check.

**Comment by harkiratsm** [comment]
It's more of an extra check to stop the save notifications from appearing on each call.

**Comment by Chadha93** [comment]
@harkiratsm  Let's discuss this on the Meshery Dev call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#) if you would. :)

**Comment by harkiratsm** [comment]
Closing as it would be fixed by @Revolyssup PR.

**Pull request closed without merging**
