### PR TITLE
Update URL viladate, compatible with RFC that is not URL standard

### PR DESCRIPTION
**Pull request by m9rco**
**Description**

The following validation should not be fail,

This PR fixes #

**Notes for Reviewers**

image

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by m9rco** [comment]
image

**Comment by gyohuangxin** [comment]
@m9rco Great! Thank you for your first PR. It makes sense to me, but I've no idea about why checks failed. I think above golang checks is not related to this PR 
cc @leecalcote

**Review by gyohuangxin — APPROVED** [review]

**Comment by leecalcote** [comment]
Good stuff, @m9rco 💪

**Comment by leecalcote** [comment]
@gyohuangxin, right on. These golang lint issues are a separate concern. 


@alphaX86, almost completed their fixes?

**Comment by alphaX86** [comment]
@leecalcote lint issues are fixed, we just need to rerun the workflow now

**Comment by warunicorn19** [comment]
@alphaX86 I re-run the jobs, the golangci-lint still seems to fail.

**Review by warunicorn19 — APPROVED** [review]
Looking good, Thanks @m9rco

**Comment by leecalcote** [comment]
@alphaX86 haha! 😆

**Comment by leecalcote** [comment]
@m9rco Yay! 🎈 Congratulations. 😄

**Pull request merged**
