### PR TITLE
“Add Load Generators Description ”

### LINKED ISSUE #1407: [Docs] Add descriptions of load generators in Meshery Performance Management page
**Current State:**
The [Performance Management page](https://meshery.layer5.io/docs/functionality/performance-management) does not have a description of the three supported load generators:

- fortio
- wrk2
- Nighthawk

**Desired State:**
This page should describe the fact that Meshery supports these load generators and have a short description of what each load generator is. See the [service mesh landscape](https://layer5.io/landscape) for some of these details and [performance management design documents](https://drive.google.com/drive/u/0/folders/1lzL9SwcsEaYY8hT1I4nC5M91o2awgr9G).

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

### PR DESCRIPTION
**Pull request by Annysah**
Signed-off-by: Annysah <anisatakinbani13@gmail.com>

**Description**

This PR fixes #1407

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by PluckyPrecious** [comment]
Cool @Annysah 😊, the PR title should perfectly describe work done `Add Load Generators Description ` isn’t bad, what do you think?

**Comment by Annysah** [comment]
Thanks Precious, I will make the changes asap.

**Review by leecalcote — APPROVED** [review]
Well done, @Annysah. This looks great. 👍

**Comment by leecalcote** [comment]
Whoo-hoo! 🎈 Thank you for digesting and presenting Meshery's functionality in this area, @Annysah.

**Comment by Annysah** [comment]
Thank you so much @leecalcote, I'm so excited.

**Pull request merged**
