### PR TITLE
[fix/ci]: cypress binary unavailable

### PR DESCRIPTION
**Pull request by Abhishek-kumar09**
Signed-off-by: Abhishek-kumar09 <abhimait1909@gmail.com>

**Description**
A test PR to fix github ci problem with cypress tests.
This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by MarioArriaga92** [comment]
Looking at this right now @leecalcote @Abhishek-kumar09, what's the actual issue this is fixing?

**Comment by Abhishek-kumar09** [comment]
Issue: 
`Cypress is installed but binary is not available`

**Comment by MarioArriaga92** [comment]
Ohh, this one @Abhishek-kumar09, right?
Screen Shot 2021-12-23 at 13 06 04
https://github.com/meshery/meshery/runs/4619150486?check_suite_focus=true

**Comment by MarioArriaga92** [comment]
@Abhishek-kumar09 if one pays close attention to the output, cypress version is stated to be '9.0.0' but expected binary location is for '8.1.0'

**Comment by Abhishek-kumar09** [comment]
yep,
Looks like it is fixed. Cleaning up the garbage.
image

**Comment by MarioArriaga92** [comment]
@Abhishek-kumar09 I just don't get why we need to run 'npx cypress install', this should be done by 'npm i' internally in prior steps

**Comment by Abhishek-kumar09** [comment]
That was caching error. Adding one more step to install cypress and cache the location.
Adding more steps doesn't add build minutes since  if cypress is already installed and cached, then the installing and unzipping operations won't be performed, if not installed then the binaries will be installed and cached.

**Comment by MarioArriaga92** [comment]
Especially because we are not doing a production build, so devDependencies should be installed as any npm hooks should run as well
Screen Shot 2021-12-23 at 13 14 20

**Comment by MarioArriaga92** [comment]
@Abhishek-kumar09 sounds good let me know when code clean up is done and I'll take a look, thanks!

**Comment by MarioArriaga92** [comment]
It' just seems weird this started happening for no apparent reason, it'd be interesting to find if there's any underlying root cause.

**Comment by Abhishek-kumar09** [comment]
Yeah, it was caching error at it's root.
We were caching node modules but not cypress binary path. 
Adding `/runner/.cache/Cypress` helped.
Then latest cypress was installed which is `9.2.0` and the code is executed with `8.x.x`.
I don't know why it downloaded latest binaries of cypress, although it is provided that it has to install `8.x.x` cypress version in package.json.

**Pull request merged**
