### PR TITLE
Extensions/refactor/styling

### PR DESCRIPTION
**Pull request by humblenginr**
**Description**
RJSF styling changes for Meshery Extensions
It includes some general RJSF styling changes and toolbar style changes to enable dynamic background color.

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — APPROVED** [review]

**Comment by dhruv0000** [comment]
@sudo-NithishKarthik Can you look into the failing integration tests by this PR? Its causing other open PR to not pass the checks.

**Comment by sudo-NithishKarthik** [comment]
Its a linting issue @dhruv0000

**Comment by dhruv0000** [comment]
Cool. Added fix in #4191

**Comment by sudo-NithishKarthik** [comment]
Thank you @dhruv0000 😄

**Pull request merged**
