### PR TITLE
CI: Modified to create changelog file for release

### LINKED ISSUE #510: [CI] Automate the updating of Releases docs page as part of CI release process.
**Current Behavior**
[Release](https://meshery.layer5.io/docs/releases) documentation gets out of date as the docs page is not always automatically updated when a new release is made.

**Desired Behavior**
1. Release notes (text from the description of the release) as entered by a maintainer into a given release (made on the web UI of github.com) are taken and used to populate a new row in the table on the Releases page of the Meshery documentation.
1. The following standard text snippet is automatically added to the description of the release on github.com so that the maintainer doesn't have to manually add it:
```
---
See the [quick start guide](https://layer5.io/meshery/#getting-started) to get started with the latest release. and the [releases](https://meshery.layer5.io/docs/installation/releases) documentation for release notes and the build and release strategy.
```
1. The standard text snippet above should not be included and repeated in each row of the Releases table in the Meshery docs.
1. Include a workflow to notify the [#announcements channel](https://layer5io.slack.com/archives/CSF3PSZT9) in Slack each time a new release is made.

**Implementation:**
Requirement 1. and 3. might be best done in GitHub Actions.
  Ideally, a new workflow or augmentation of the existing GitHub Actions workflow can provide a solution here (e.g. copying of the text contained in the description of [a given release](https://github.com/layer5io/meshery/releases/tag/v0.3.2)). 

Requirement 2. might be best done in goreleaser.

**Related Issues:**
#509

### PR DESCRIPTION
**Pull request by SudhanAruna**
Signed-off-by: Arunagirinadan Sudharshan <sudhan.aruna.97@gmail.com>

**Description**

This PR fixes #510

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by SudhanAruna** [comment]
Please let me know your feedback on these changes.

**Comment by leecalcote** [comment]
@SudhanAruna thank you. This is a step in the right direction. Ideally, the Releases page will automatically reflect change logs from each release. Given the current direction of this workflow, a way that we can achieve the goal of having the Releases page automatically updated is to:

1. Create a Jekyll datafile to track release notes (or create a new Jekyll collection in which each a file is created for each release made).
1. Modify the [Releases page](https://github.com/layer5io/meshery/blob/master/docs/pages/getting-started/project/releases.md) to use this new Jekyll datafile / collection.

**Comment by Sudhan97** [comment]
Okay, I'll make the changes.

**Comment by leecalcote** [comment]
Thank you, @SudhanAruna. Let @chandrashritii  or me know if you stumble on any aspect of the Jekyll work and either one of us will help.

**Comment by leecalcote** [comment]
@SudhanAruna any progress here? Anything I can help with?

**Comment by SudhanAruna** [comment]
@leecalcote Please let me your feed back on this approach.

**Review by leecalcote — APPROVED** [review]
@SudhanAruna 💥 Nice!

**Comment by leecalcote** [comment]
@SudhanAruna, well done! One small item to deal with here: the descending order of releases by version number is being itemized slightly out of order with the string “v0.4.9” coming before “v0.4.25", because the “9” is greater than “2", as opposed to “25” being greater than “9".

**Pull request merged**
