### PR TITLE
trasitioned from patterns to designs

### PR DESCRIPTION
**Pull request by warunicorn19**
Signed-off-by: Aditya Chatterjee <speak2adi@gmail.com>

**Description**
Changed Patterns to Designs
This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
@MarioArriaga92 "pages"module can't be found. Is this related to today's new ui integration tests?

**Comment by leecalcote** [comment]
The changes here don't affect any `cy` attributes, it seems.

**Review by leecalcote — APPROVED** [review]

**Comment by MarioArriaga92** [comment]
@leecalcote @warunicorn19 it seems that next.js build is failing:
```
info  - Using external babel configuration from /home/runner/work/meshery/meshery/ui/.babelrc
error - ./pages/_document.js:4:0
Module not found: Can't resolve 'styled-jsx/server'
```

**Comment by MarioArriaga92** [comment]
That's output in line 129-ish of test run

**Comment by MarioArriaga92** [comment]
Same issue happened in a workflow run 2 days ago, result [here](https://github.com/meshery/meshery/runs/5282312007?check_suite_focus=true)

**Comment by MarioArriaga92** [comment]
@leecalcote @warunicorn19 looks like it's something that "randomly" happens when version of npm is different on GitHub Actions Runner. Can someone please re-run the workflow a couple of times to confirm this?

**Comment by warunicorn19** [comment]
Re-running

**Comment by MarioArriaga92** [comment]
2nd best guess is that a change un package-lock.json is introduced in a way that doesn't run the workflow and this is fixed when a contributor PR with changes to that file which do not contain that difference.

When issue happens, I see first lines of failing job in integration/end-to-end test run logs as this:
```
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
```

**Comment by MarioArriaga92** [comment]
@warunicorn19 looks like it's still failing, can you push version of upackage-lock.json you have please? For both UI and provider folders

**Review by leecalcote — APPROVED** [review]

**Comment by leecalcote** [comment]
@MarioArriaga92, this is most helpful. I'll dig into the node version...

**Comment by warunicorn19** [comment]
@MarioArriaga92 this makes sense, i think currently we're only compatible with node v16, that's the checks fail when node version is anything else.

**Comment by warunicorn19** [comment]
I've been waiting for the e2e test to finish for the last 30 minutes🥲. anyway, I don't think it's gonna fail. @leecalcote I think we can update the Node version in the secrets or I have hard-coded the node version in the workflow, so tests should be failing anymore. CC @MarioArriaga92

**Comment by warunicorn19** [comment]
Ahhh all greens 🥲😍

**Comment by leecalcote** [comment]
@warunicorn19 sounds good. Please do update this org secret.

**Comment by MarioArriaga92** [comment]
Glad ci issue got solved @warunicorn19 @leecalcote 🤖

**Pull request merged**
