### PR TITLE
renamed performance management related API endpoints

### LINKED ISSUE #779: [Meshery] Restructure performance management related API endpoints
**Current Behavior**
The collection of performance related API endpoints is here - https://github.com/layer5io/meshery/blob/master/router/server.go#L34-L38. These can be grouped behind a common path.

**Desired Behavior**
These need to be renamed and placed behind a common `/perf` path. 

**Acceptance Criteria**
The performance endpoints should be like so:

```
/api/perf/load-test
/api/perf/load-test-smps
/api/perf/load-test-prefs
/api/perf/results
/api/perf/result
```

### PR DESCRIPTION
**Pull request by ashiscs**
fixes #779 
Signed-off-by: ashiscs <ashissingh640@gmail.com>

### CODE REVIEW

**Comment by ashiscs** [comment]
Ok sir @leecalcote

**Comment by kushthedude** [comment]
@ashiscs Any update over here?

**Comment by ashiscs** [comment]
> @ashiscs Any update over here?

It is left to be done..

**Comment by leecalcote** [comment]
@ashiscs don’t forget that VS Code (and other IDEs) will help track down all the references to these names. What do you anticipate the ETA on this one is? There’s no rush here at the moment.

**Comment by leecalcote** [comment]
@ashiscs what would you like to do with this PR?

**Pull request closed without merging**
