### PR TITLE
[mesheryctl] Promote environment subcommand from experimental(#12947)

### LINKED ISSUE #12947: [mesheryctl] Promote environment command from experimental
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

We need to promote environment subcommand

### Current Behavior

Command is available under experimental status

```bash
mesheryctl exp environment
```
### Desired Behavior

Should move as regular subcommand

```bash
mesheryctl environment
```

### Implementation

1. move subcommand under root
2. Update related documentation 

### Acceptance Tests

- command is available at root subcomands level
- documentation is updated

### Mockups

---

### Contributor Resources

- ⌨️ [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by TusharMohapatra07**
**Notes for Reviewers**

The PR is WIP

- This PR fixes #12947 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by TusharMohapatra07** [comment]
@leecalcote Hey, as a part of hacktoberfest, i had contributed to an org for cli written in go. This issue would be a greate start for me to explore this repository. So, i'll be working on the issue.

**Comment by vishalvivekm** [comment]
@TusharMohapatra07 
Thank you for your contributions! Let's discuss this today, during Meshery Development call at 9:00 AM CT | 8:30 PM IST. Adding it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit?pli=1&tab=t.0#) || [meeting link.](https://meet.layer5.io/meshery)

**Comment by winkletinkle** [comment]
@TusharMohapatra07, the Golang build check is failing. 👀

**Comment by TusharMohapatra07** [comment]
@winkletinkle Hey, i build the binary on my local system and everything is working fine.

image
image

**Comment by lekaf974** [comment]
@TusharMohapatra07 closing this PR I was already working on it also it requires documentation update. 

Please don't wok on an issue already assigned to someone else to avoid duplicate work

**Comment by TusharMohapatra07** [comment]
@lekaf974 sorry for my overlook, i didn't notice you had self assigned the issue. My bad!

**Comment by lekaf974** [comment]
> @lekaf974 sorry for my overlook, i didn't notice you had self assigned the issue. My bad!

No problem, your help is welcomed and your changes were good, just we both worked on the same issue. 
You could review my opened PR and give feedback.

**Pull request closed without merging**
