### PR TITLE
[Lifecycle] Enhance error message for failed installations

### PR DESCRIPTION
**Pull request by theBeginner86**
**Description**

This PR:
- updates meshes/meshops.proto and meshes/meshops.pb.go so that new fields could be received from the adapter which fails in applying a given operation.
- updates UI to show more fields in the notification center for error messages. 

This PR is related to https://github.com/meshery/meshery-istio/issues/376

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by warunicorn19** [comment]
@theBeginner86 let's see a demo of how this works on the dev call today.

**Review by Revolyssup — COMMENTED** [review]
@theBeginner86  After this we will also need to update this change in the adapter library.

**Comment by theBeginner86** [comment]
> @theBeginner86 After this we will also need to update this change in the adapter library.

@Revolyssup 
Yeah, I did make that change. Please check this PR: https://github.com/meshery/meshery-istio/pull/387 (it includes the complete info)

**Comment by Revolyssup** [comment]
> 

I think even that PR will need changes in adapter library first.

**Comment by Revolyssup** [comment]
> @Revolyssup Would you mind elaborating a bit about what changes are you referring to? sweat_smile
> 
> > ICYMI, I did update some stuff in this PR as well: [meshery/meshery-adapter-library#81](https://github.com/meshery/meshery-adapter-library/pull/81)

Here I meant that the go code generated from proto files has to be there in adapter library as well

**Comment by theBeginner86** [comment]
> > @Revolyssup Would you mind elaborating a bit about what changes are you referring to? sweat_smile
> > > ICYMI, I did update some stuff in this PR as well: [meshery/meshery-adapter-library#81](https://github.com/meshery/meshery-adapter-library/pull/81)
> 
> Here I meant that the go code generated from proto files has to be there in adapter library as well

I did add that generated meshops.pb.go file. 
To reduce confusion I have just requested your review on my PR at meshery-adapter-library 😊

**Pull request closed without merging**
