### PR TITLE
[Docs] Release Notes for Meshery v0.5.1

### PR DESCRIPTION
**Pull request by l5io**
An auto-generated pull request to document release notes for Meshery v0.5.1

### CODE REVIEW

**Comment by leecalcote** [comment]
Haha! @ramrodo :)

**Review by Aisuko — DISMISSED** [review]
approve

**Comment by Aisuko** [comment]
Can we use this as a template for the release of other adapters?

**Comment by ramrodo** [comment]
@leecalcote I'll close this PR as this not reflect the changes of Meshery v0.5.1. The next release should create the right PR for that.

**Comment by leecalcote** [comment]
Thank you, sir.

**Pull request closed without merging**
