### PR TITLE
[Server] Add support to fetch connection by id.

### PR DESCRIPTION
**Pull request by MUzairS15**
**Notes for Reviewers**

This PR fixes #

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by lekaf974** [comment]
@MUzairS15 something wrong with meshkit error test related to `mesheryctl` does your branch up-to-date ? or perhaps not related

**Review by leecalcote — APPROVED** [review]
Syncing with HEAD...

**Comment by lekaf974** [comment]
@leecalcote seeing you trying to fix the issue by syncing to master but the test meshery error code is failing since this last week https://github.com/meshery/meshery/actions/workflows/error-codes-updater.yaml?page=2 after a PR merge

**Comment by lekaf974** [comment]
#10818 should fix `Meshery Error Codes Utility Runner`

**Comment by leecalcote** [comment]
Oh, I see. This is good. 👍 Let’s give it another sync…

**Review by lekaf974 — APPROVED** [review]
LGTM

**Pull request merged**
