### PR TITLE
Add links, captions as annotation tags in `mesheryctl` files

### PR DESCRIPTION
**Pull request by alphaX86**
**Notes for Reviewers**

This PR fixes #

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit f26543b4e8af39b1b71b12eb19f107b91b811ad6 at: https://63fb9269c0c82513d5af4165--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit e9bf3aaa6a5b1c5e11b570c336715906f7257de1 at: https://63fb9676c0c82516d2af416a--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 8ba107e54d98613ea3564d7dec98c657cc4adaa8 at: https://63fcbff3419ea51aeff09aeb--meshery-docs-preview.netlify.app

**Review by leecalcote — APPROVED** [review]
Very nice, @alphaX86

**Pull request merged**
