### PR TITLE
Add mesheryctl smoke test workflow

### PR DESCRIPTION
**Pull request by pottekkat**
Signed-off-by: Navendu Pottekkat <navendupottekkat@gmail.com>

**Description**

Adds a workflow that runs on every PR and push to master to run a smoke test with mesheryctl.

- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — COMMENTED** [review]
Push test results to /docs/_compatibility. Use "passing", "partial", and "failing" as test statuses. Define a name for each test. Follow the existing markdown format.

**Comment by piyushsingariya** [comment]
> How is the build of mesheryctl here any more of a test than the existing workflows that build and unit test mesheryctl?

+1

**Comment by leecalcote** [comment]
Answering my own question a bit.... I understand that this is likely a starting point for running any number of functional tests like `mesheryctl mesh deploy`.

**Comment by leecalcote** [comment]
@navendu-pottekkat will you articulate how this will be built upon? In its current form, it's redundant.

**Comment by navendu-pottekkat** [comment]
Smoke tests will be a subset of E2E tests. If the smoke tests fail, we skip E2E tests and if it passes we continue on with the E2E tests.

All tests are built upon each other as it is proposed in the [Master Test Strategy](https://docs.google.com/document/d/14vbwnKafqxrr-cJOmLWEvvj75MFrxFKiUdfPwZRhg64/edit#heading=h.nxppificfb4m).

**Pull request closed without merging**
