### PR TITLE
UI: Fix Adapter selection changes on page refresh

### LINKED ISSUE #871: [Meshery] Adapter selection changes on page refresh
**Description**
When a user has navigated to `/management?adapter=<adapter-name>:<port>` and the page is refreshed, often the displayed adapter will change, despite the user not having changed their selection. Example:

Untitled

This issue is likely due to out of order messages received through the go channel used by go routines to query all the adapters for their metadata. Assuming this is the case, this article might be of value - https://medium.com/@fonseka.live/how-to-maintain-the-order-of-go-routines-117a5be86c4f

**Expected Behavior**
Users should see the same adapter (e.g. Linkerd) when refreshing this page. e.g. `http://localhost:9081/management?adapter=meshery-linkerd:10001`

### PR DESCRIPTION
**Pull request by nveenjain**
#### Description

This PR is a work-around for #871     

#### Notes to reviewers:
This is vanilla JS implementation, this should be kept at lower priority if react-router code can be updated to pass on the query object. 

#### Checklist

- [x] [DCO](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin) signed.
- [x] Title of the PR starts with area name, e.g. `meshery:`, `mesheryctl:`, `ui:`.

Signed-off-by: Naveen Jain <nveenjain@gmail.com>

### CODE REVIEW

**Comment by leecalcote** [comment]
@shalinibhawsingka this is a great PR for you to review.

**Comment by nveenjain** [comment]
Actually fix will automatically close the issue... linked with the PR... That's why i mentioned fix in the description. 

It's also in the PR template :sweat_smile:

**Comment by kushthedude** [comment]
> Actually fix will automatically close the issue... linked with the PR... That's why i mentioned fix in the description.
> 
> It's also in the PR template

That was my point , as you mentioned it is temporary fix or more of a workaround. Therefore we should let the issue remain open to let know that this needs to be addressed and we have used a workaround so that UX dont gets poor.
I hope you are getting my point.

**Comment by leecalcote** [comment]
Marking as a work-around to flag the issue for a native fix later.

**Comment by leecalcote** [comment]
Thanks, @nveenjain!

**Pull request merged**
