### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Ruhi-Khan**
**Notes for Reviewers**

This PR fixes #

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
@Ruhi-Khan thanks! This PR seems to be missing your commit(s).

**Comment by Yashsharma1911** [comment]
@Ruhi-Khan thankyou, please make sure PR contains issue link and changes you made, refer to contributing guide if you are facing any issue

**Review by Ruhi-Khan — COMMENTED** [review]
meshery:master I have made some basic changes like I have updated docs and there were some error so I recreated the PR.

**Comment by Yashsharma1911** [comment]
> meshery:master I have made some basic changes like I have updated docs and there were some error so I recreated the PR.

@Ruhi-Khan we are still unable to see the changes you made, please look on GitHub official docs to get help on making sure changes made in locally are reflected on pull request

**Comment by vishalvivekm** [comment]
@Ruhi-Khan ??

**Comment by Ruhi-Khan** [comment]
I have updates the docs and I m learning how to do contribute more.. how to
share connect the link how to add and etc..

**Comment by leecalcote** [comment]
Whee!

**Pull request merged**
