### PR TITLE
fixed the export modal

### PR DESCRIPTION
**Pull request by captain-Akshay**
**Notes for Reviewers**

This PR fixes #

[Screencast from 2024-02-18 18-14-45.webm](https://github.com/meshery/meshery/assets/59491379/28aadbd2-c7f2-4981-a666-28a4d0852e70)

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by ritiksaxena124** [comment]
Too much padding at the bottom part

**Comment by captain-Akshay** [comment]
[Screencast from 2024-02-19 00-54-07.webm](https://github.com/meshery/meshery/assets/59491379/a37b8c8c-7833-44d9-bc28-ed8ca9784f9e)

**Comment by captain-Akshay** [comment]
// @ritiksaxena124

**Comment by ritiksaxena124** [comment]
When you click on the embed button and the modal expands to show code the left and right padding is too much, decrease it to 1/2 or increase the padding on left and right side when the embed is not clicked. 

Right now it's uneven increase in the padding when that embed button is clicked and modal expands

**Comment by captain-Akshay** [comment]
[Screencast from 2024-02-19 11-41-36.webm](https://github.com/meshery/meshery/assets/59491379/a5d2dc2b-5a74-4417-9827-340c0c20e3a4)
@ritiksaxena124

**Comment by captain-Akshay** [comment]
[Screencast from 2024-02-19 11-41-36.webm](https://github.com/meshery/meshery/assets/59491379/689d366c-2ea7-4d35-b0e3-32a26214cd08)

**Comment by ritiksaxena124** [comment]
Much better 👍

**Review by ritiksaxena124 — APPROVED** [review]

**Review by leecalcote — APPROVED** [review]

**Pull request merged**
