### PR TITLE
fix: Dashboard card missing title and background

### PR DESCRIPTION
**Pull request by MeenuyD**
fixes the Dashboard card missing title and background of resources
#9195 
#9240

### CODE REVIEW

**Review by kumarankit999 — COMMENTED** [review]
Looking Good

**Comment by coder12git** [comment]
looks good to me!

**Review by coder12git — APPROVED** [review]

**Review by leecalcote — APPROVED** [review]

**Comment by leecalcote** [comment]
Thanks!

**Comment by MeenuyD** [comment]
Your welcome

**Pull request merged**
