### PR TITLE
[Docs] Resolves the missing bullet points(Issue #12903)

### LINKED ISSUE #12903: [Docs] Fix Missing Bullet Points in Release Documentation.
### Current State
There is a persisting issue with across Release docs regarding missing bullet points which impacts the readability and presentation.
bl2

### Desired State
A consistent view with regards to formatting.

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by FilledEther20**
**Notes for Reviewers**

- This PR fixes #12903 
- Before 
bl2

- After
bl1

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit e164688a616a6508c0637186f1ae381c3c00871b at: https://6761ad5a1ba23e3fa5f63443--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 57397006ee24994abae2ecc4cd43d87ec0e08cad at: https://67655a813e8f076a3777d85f--meshery-docs-preview.netlify.app

**Comment by sudhanshutech** [comment]
@FilledEther20 
Thank you for your contribution!
Let's discuss this during the website call on Monday(today) at 6:30 PM IST (7:00 AM CT).

Please add it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit?tab=t.0).

**Comment by sudhanshutech** [comment]
@FilledEther20 take care of this in the root workflow and close this pr.

**Comment by SAHU-01** [comment]
@FilledEther20 do you have an update on this?

**Pull request closed without merging**
