### PR TITLE
Fix for unwanted snackbar in perf preferences tab

### PR DESCRIPTION
**Pull request by Nikhil-Ladha**
Signed-off-by: Nikhil-Ladha <nikhilladha1999@gmail.com>

- Added the null condition before showing the snackbar.

- Also, added the default values of the fields for the preferences page.

### CODE REVIEW

**Comment by Nikhil-Ladha** [comment]
> We discussed to populate the defaults from the perf page. It would be odd to have values populated at the perf page with preference being empty.

I have added that, and also mentioned it in the PR description.

**Comment by kushthedude** [comment]
> > We discussed to populate the defaults from the perf page. It would be odd to have values populated at the perf page with preference being empty.
> 
> I have added that, and also mentioned it in the PR description.

I dont see where are they added?

**Comment by kushthedude** [comment]
> > We discussed to populate the defaults from the perf page. It would be odd to have values populated at the perf page with preference being empty.
> 
> I have added that, and also mentioned it in the PR description.

Is the generator getting updated?

**Comment by Nikhil-Ladha** [comment]
> > > We discussed to populate the defaults from the perf page. It would be odd to have values populated at the perf page with preference being empty.
> > 
> > 
> > I have added that, and also mentioned it in the PR description.
> 
> Is the generator getting updated?

Yes, it is.

**Comment by kushthedude** [comment]
> > > > We discussed to populate the defaults from the perf page. It would be odd to have values populated at the perf page with preference being empty.
> > > 
> > > 
> > > I have added that, and also mentioned it in the PR description.
> > 
> > 
> > Is the generator getting updated?
> 
> Yes, it is.

Can you recheck it, gen is not populated to fortio by default as it doesn't fetch the value from store.

**Comment by Nikhil-Ladha** [comment]
I am updating the MesheryResultsDialogue.js file with the indentation to fix the failing of UI test.

**Comment by Nikhil-Ladha** [comment]
> > > > > We discussed to populate the defaults from the perf page. It would be odd to have values populated at the perf page with preference being empty.
> > > > 
> > > > 
> > > > I have added that, and also mentioned it in the PR description.
> > > 
> > > 
> > > Is the generator getting updated?
> > 
> > 
> > Yes, it is.
> 
> Can you recheck it, gen is not populated to fortio by default as it doesn't fetch the value from store.

Yes, the load-generators are not getting populated but only the QPS, Concurrent Rqsts, and the Duration fields are.

**Comment by kushthedude** [comment]
> Yes, the load-generators are not getting populated but only the QPS, Concurrent Rqsts, and the Duration fields are.

We would this to also be set to its default value -> fortio

**Comment by Nikhil-Ladha** [comment]
> > Yes, the load-generators are not getting populated but only the QPS, Concurrent Rqsts, and the Duration fields are.
> 
> We would this to also be set to its default value -> fortio

Ohh, okay will add that.

**Pull request merged**
