### PR TITLE
Adding websocket port to list of ports - fix for #6200

### LINKED ISSUE #6200: [Docs] Add websocket port to list of ports in meshery documentation
#### Current State
Websocket port needs to be added to the meshery architecture [network ports table](https://docs.meshery.io/concepts/architecture#network-ports)

#### Desired State

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by vishnus17**
Signed-off-by: Vishnu S <58102524+vishnus17@users.noreply.github.com>

**Description**

This PR fixes #6200

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 05516cfe49d9a396ec74abbe92e7e772ad309811 at: https://631cdff0b9acb87eff5ae412--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 1d443867e1b33f7c3b9f714e17bb792761dbe65f at: https://631ce223f19e9b0278e049ae--meshery-docs-preview.netlify.app

**Comment by hershd23** [comment]
https://631ce223f19e9b0278e049ae--meshery-docs-preview.netlify.app/concepts/architecture

Scroll to the bottom of the page. The meshery-perf row which is the bottom-most row is shorter than the rows preceding it. We'll need to fix that before merging

**Comment by l5io** [comment]
🚀 Preview for commit 6df5bae3560bfbfabc7ffde5aa03330fa48fba9a at: https://631e5357d1b60478129d7dc5--meshery-docs-preview.netlify.app

**Comment by vishnus17** [comment]
Hi @hershd23. I've made that change.

**Comment by l5io** [comment]
🚀 Preview for commit f2a4430b4898e7e3cd69e2e72ee1787da3a79c0e at: https://631e5848780f1a7e52cb2f89--meshery-docs-preview.netlify.app

**Comment by vishnus17** [comment]
My bad. First time contributing so I tried to read everything I can but committing to my forked branch automatically pulled the changes here as well which caused the sign off issue. I understand that each commit should be signed off for successful CI run. Is it okay if I close this PR and open a new one. Please let me know.
Thanks. Always learning! 😅

**Comment by l5io** [comment]
🚀 Preview for commit a987553a918ec81bc322b9cffeb46728cf2d595e at: https://631e5b1b734bf17c5e3a8f05--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 87f773dfffc31a9f4dfde719876511417920796f at: https://631e5d649907ec7a8881bba7--meshery-docs-preview.netlify.app

**Comment by vishnus17** [comment]
Had to understand why CI tests were failing and fix it. Finally it looks good now. 
Always learning! This is my first contribution here.

**Review by hershd23 — DISMISSED** [review]
Given it looks perfect, I'll approve your changes.

LGTM

Any idea as to why removing the line break between those two lines did the trick?

**Comment by hershd23** [comment]
Oops looks like I don't have write access to master for this repo.

@leecalcote @CyrineG @Revolyssup take a look and merge if the changes seem fine

**Review by CyrineG — APPROVED** [review]
LGTM!

**Comment by vishnus17** [comment]
> Given it looks perfect, I'll approve your changes.
> 
> LGTM
> 
> Any idea as to why removing the line break between those two lines did the trick?

I don't know the exact reason why that fix was working but this is what I found out during the fix:
  As we're using a custom formatting method here for the entries with images, adding line breaker was considering the entries without custom formatting as an empty entry which messed up the alignment. When you try putting a '|' after the line breaker in the same line, it'll show the empty row without any entry and then Meshery Perf in a new row below it. 
  

I've just figured out the actual fix for the issue. It was a missing "-" in the  {% endfor -%}.

I'll push this change so that the actual fix can be merged before final review.

**Comment by l5io** [comment]
🚀 Preview for commit 07f2cc3262ca3175feecaabbd5aba79a895b30e5 at: https://631f192ef19e9b1453e048f8--meshery-docs-preview.netlify.app

**Comment by vishnus17** [comment]
Hi @CyrineG @hershd23 . 
Sorry that you have to do the commit review again but this one seems to be more logical as I found out that the issue was actually a syntax error.
Thank you.

**Comment by hershd23** [comment]
You have absolutely nothing to be sorry about. Infact had we pushed in that hacky fix it would have caused problems in the future. 

Great work, digging in to the issue.

**Review by hershd23 — APPROVED** [review]

**Review by CyrineG — APPROVED** [review]

**Comment by vishnus17** [comment]
Hi @leecalcote. Can you approve the changes as other PRs are being committed into the repo which would need me to update the branch again and possibly require another review? I'm not sure though.
Thanks.

**Comment by l5io** [comment]
🚀 Preview for commit ada8324fd0472fc7fd2f7d4d81ad1b1b8ca59e33 at: https://6320c449da84ae01aa0eba15--meshery-docs-preview.netlify.app

**Review by warunicorn19 — APPROVED** [review]
LGTM! Thanks @vishnus17

**Pull request merged**
