### PR TITLE
[Docs] Updated description of Hipster store sample app

### LINKED ISSUE #3830: [Docs] Update description of Hipster store sample app
#### Current State
The Hipster sample application's description in Meshery Docs is out of date: https://docs.meshery.io/guides/sample-apps#hipster.

#### Desired State
This sample application, https://github.com/GoogleCloudPlatform/microservices-demo, has been renamed to Online Boutique

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by afzal442**
Signed-off-by: afzal <afzal442@gmail.com>

**Description**
Modifies hipster shop to the online boutique

This PR fixes #3830 

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit f59750cc2b3edfc5b2bb7465148b8a438056ce87 at: https://61138b977175e8985c73effd--meshery-docs-preview.netlify.app

**Review by warunicorn19 — APPROVED** [review]
LGTM, Thanks @afzal442

**Comment by afzal442** [comment]
Thanks, @warunicorn19 as always.

https://61138b977175e8985c73effd--meshery-docs-preview.netlify.app/guides/sample-apps#online-boutique

**Review by leecalcote — APPROVED** [review]
looking good, @afzal442 👍

**Pull request merged**
