### PR TITLE
[Performance] splitting Nighthawk out of Meshery's container

### LINKED ISSUE #4075: [Enhancement] Split Nighthawk out of meshery docker image
#### Current Behavior
Nighthawk's load generation services are currently present in meshery's docker image. This is not good because:
* This limits us from exposing many advanced Nighthawk features.
* Bloats the Meshery image and makes it too heavy.
* Slightly affects the performance of both the tools.

#### Desired Behavior
Nighthawk should run as a separate container outside of Meshery's container. It should either be in the Kubernetes cluster or a docker container depending upon if Meshery is connected to a cluster or not.
This should be done by using `GetNighthawk` as a golang wrapper around Nighthawk's interface.

An outcome of this would also be opening up the scope of supporting distributed load generation with horizontally scaled Nighthawk deployments. :muscle:

### PR DESCRIPTION
**Pull request by DelusionalOptimist**
Signed-off-by: Rudraksh Pareek <rudrakshpareek3601@gmail.com>

**Description**

This PR fixes #4075

**Notes for Reviewers**
- [x] Deploy in k8s
- [ ] Deploy in docker containers
- [ ] Transform results natively

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Task linked: [CU-94zvye Split Nighthawk out of meshery docker image](https://app.clickup.com/t/94zvye)

**Comment by gyohuangxin** [comment]
@DelusionalOptimist It totally looks good for me, can you provide more information about how it runs?

**Comment by leecalcote** [comment]
@DelusionalOptimist is on break from the project for another few weeks or so. He might respond, however, we should assume that he won't while he's on break and we should proceed in his absence.

**Comment by gyohuangxin** [comment]
> @DelusionalOptimist is on break from the project for another few weeks or so. He might respond, however, we should assume that he won't while he's on break and we should proceed in his absence.

@leecalcote Thanks, got it. I try to run this code in my host to verify it works, but I have few knowledge about how to build Meshery code. Can you provide some docs? 

@navendu-pottekkat FYI

**Comment by gyohuangxin** [comment]
@navendu-pottekkat I'll try it, thanks.

**Comment by leecalcote** [comment]
Link to design spec - https://docs.google.com/document/d/1Qy_BpHXibTvL9daLTc5L4fjmr1F051ya0UYeghNUq_I/edit#

**Comment by leecalcote** [comment]
@DelusionalOptimist, I probably missed the note... are we migrating this issue to the `meshery-perf` repo or handling this effort under a different issue?

**Comment by DelusionalOptimist** [comment]
@leecalcote The code in this PR was to help Meshery server interact with the Nighthawk gRPC service directly. AFAIK that won't be happening.. so I think it becomes unnecessary to keep this in Meshery.
Yes, the proper place where this functionality should be meshery-perf... I suppose, right @gyohuangxin?
Relevant slack thread: https://layer5io.slack.com/archives/CFGG6U10E/p1642937943024200

**Comment by gyohuangxin** [comment]
@DelusionalOptimist Yes, I think so. I paused this PR due to our new design of `meshery-perf` component.

**Pull request closed without merging**
