### PR TITLE
Filter "order by" parameter to fix sql inject vuln

### PR DESCRIPTION
**Pull request by phant0ms**
## and export SanitizeOrderInput function

**Notes for Reviewers**

This PR fixes #
fix a sql inject in route `api/system/database`,  in `GetSystemDatabase` function, filter order by parameter with a exiting function `models.SanitizeOrderInput`.

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Thank you for creating a fix for this security vulnerability, @phant0ms 👍

**Comment by leecalcote** [comment]
You'll want to follow the instructions on this page in order to ensure that your git commits are signed - https://github.com/meshery/meshery/pull/9372/checks?check_run_id=18731162779

**Review by MUzairS15 — APPROVED** [review]
Thanks for the fix @phant0ms .
Will you make sure to sign your commits so that we can get this merged.

**Comment by phant0ms** [comment]
Sorry for the late reply. i have signed the commit @MUzairS15  @leecalcote

**Pull request merged**
