### PR TITLE
[extension] Add support to search users

### PR DESCRIPTION
**Pull request by theBeginner86**
**Notes for Reviewers**

This PR adds support to search users. Would be helpful for users lookup components.

New API added: `/api/identity/users`
Updated docs ✔️

Screenshot 2023-05-14 at 4 53 19 AM

This PR fixes #

Also, updated existing hardcoding of a remote provider API `/api/identity/profile/<ID>` to instead use capability to determine the API.

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 00cce687b7330876626a330e1ad211f0e02ada2d at: https://6460311ef630b3256bc38731--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit c3593249f02a4d52c6ea0dacc28bfb593783a4d9 at: https://6460371e15bb46255eb5fc12--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit b4422035b9ebc24cb9f26cf936240a4cd2031962 at: https://646039b25d79022d3098b1a3--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit ee860223228582e062d4e0d59460c13ed6cbf50f at: https://64603b1300a4712dd517e148--meshery-docs-preview.netlify.app

**Comment by leecalcote** [comment]
@yash37158 @Chadha93

**Pull request merged**
