### PR TITLE
mesheryctl: mesheryctl version not aligned

### PR DESCRIPTION
**Pull request by subhamkrai**
adding additional tab to aligned the mesheryctl
version command.

Signed-off-by: subhamkrai <subhamkumarrai03@gmail.com>

**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by subhamkrai** [comment]
for now, used tweak needs discussion on this.

**Comment by subhamkrai** [comment]
@anirudhjain75  any suggestions?

**Comment by anirudhjain75** [comment]
Yea I did share formatting tools / tips for you to have a look on. What's your progess with that ?

**Comment by subhamkrai** [comment]
> Yea I did share formatting tools / tips for you to have a look on. What's your progess with that ?

yes, I saw that but I'm not sure that how that will resolve in this case as for both client and server version we have same logging method but we are getting different formats in  `GITSHA`.

**Comment by leecalcote** [comment]
@subhamkrai one item that needs to be addressed is the missing "v" in the release tag in the Client Version line. Will you have this "v" added back?

**Comment by leecalcote** [comment]
> @subhamkrai one item that needs to be addressed is the missing "v" in the release tag in the Client Version line. Will you have this "v" added back?

@anirudhjain75 will you create a new issue to track this request?

**Comment by anirudhjain75** [comment]
> > Yea I did share formatting tools / tips for you to have a look on. What's your progess with that ?
> 
> yes, I saw that but I'm not sure that how that will resolve in this case as for both client and server version we have same logging method but we are getting different formats in  `GITSHA`. 

You'll have make it in such a way to print both server version and client version at once using formatting method

**Comment by anirudhjain75** [comment]
> @subhamkrai one item that needs to be addressed is the missing "v" in the release tag in the Client Version line. Will you have this "v" added back?

I don't understand what you mean by it

**Comment by leecalcote** [comment]
@anirudhjain75 no sweat. If you will run `mesheryctl version`, you’ll see.

**Comment by leecalcote** [comment]
@anirudhjain75 here you go:

```
➜  meshery git:(myMeshMap) mesheryctl version
Client Version: 0.4.3 	  GitSHA: 51fa5e6626f024aa3bd914efd0d0c34fa136021a
Server Version: v0.4.3 	  GitSHA: 51fa5e6
```

See the missing "v" in the Client Version line?

**Comment by anirudhjain75** [comment]
Okay Yea... This can be added after the formatter task is done

**Comment by anirudhjain75** [comment]
@subhamkrai let me know if you're still on this :)

**Comment by leecalcote** [comment]
@anirudhjain75 will you breakout the addition of "v" in the Client Version into a separate issue/PR, so that it can be uncoupled and move forward?

**Comment by anirudhjain75** [comment]
Yea it would make a beginner issue.

**Comment by leecalcote** [comment]
Marking issue as stale, assuming @subhamkrai won't be able to finish off this PR.

**Comment by leecalcote** [comment]
Stale bot removed the label. @subhamkrai quick question - do you foresee finishing this off or is it best to close this PR and unassign the issue for the time being?

**Comment by subhamkrai** [comment]
> Stale bot removed the label. @subhamkrai quick question - do you foresee finishing this off or is it best to close this PR and unassign the issue for the time being?

okay, lets close this PR or if @anirudhjain75  wants to takeover fell free to do.

**Comment by anirudhjain75** [comment]
I have some other work to be done. Hopefully someone else comes up and picks this... I dont see an open issue for this 🤔. I'm reopening this for other contributors to pick up from here.

**Comment by leecalcote** [comment]
@vijcheru this PR is inactive. You might want to have a look around this issue to see if a fix is possible.

**Pull request closed without merging**
