### PR TITLE
Updated empty state of confirmation modal | CU-2kcvd3c

### PR DESCRIPTION
**Pull request by asubedy**
Signed-off-by: asubedy <frexpe@pm.me>

**Description**
image

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
Task linked: [CU-2kcvd3c Validation Modal: Enhance empty state](https://app.clickup.com/t/2kcvd3c)

**Comment by leecalcote** [comment]
Nice, @asubedy 👍

**Review by leecalcote — APPROVED** [review]

**Comment by leecalcote** [comment]
The bottom of the Meshery Operator body is cutoff, though...

**Review by leecalcote — CHANGES_REQUESTED** [review]
Please ensure Meshery Operator logo fits in-full.

**Comment by asubedy** [comment]
image

**Review by leecalcote — APPROVED** [review]

**Comment by leecalcote** [comment]
Is this logo in utf8 format?

**Comment by asubedy** [comment]
I copied the svg from sigma file. Not so sure about utf8 😓

**Pull request merged**
