### PR TITLE
Fix meshery-operator helm chart

### PR DESCRIPTION
**Pull request by panyuenlau**
Signed-off-by: Darren_Lau <panyuenlau@gmail.com>

**Description**

This PR fixes  https://github.com/meshery/meshery/issues/4185

**Notes for Reviewers**
The updated CRDs are copied from this PR: https://github.com/meshery/meshery-operator/pull/203

Results after the fix:
```
helm install test install/kubernetes/helm/meshery -n meshery --kubeconfig=$KUBECONFIG
NAME: test
LAST DEPLOYED: Wed Sep 15 15:07:05 2021
NAMESPACE: meshery
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
1. Get the application URL by running these commands:
     NOTE: It may take a few minutes for the LoadBalancer IP to be available.
           You can watch the status of by running 'kubectl get --namespace meshery svc -w test-meshery'
  export SERVICE_IP=$(kubectl get svc --namespace meshery test-meshery --template "{{ range (index .status.loadBalancer.ingress 0) }}{{.}}{{ end }}")
  echo http://$SERVICE_IP:9081/provider
2. All the Notes.txt of Meshery, Mesheryistio and Mesherylinkerd need to add the content here. This can be achieved by sub PR.

kubectl get pods -n meshery --kubeconfig=$KUBECONFIG
NAME                                    READY   STATUS    RESTARTS   AGE
meshery-677df7b644-kjg68                1/1     Running   0          76s
meshery-consul-5769bf7c9c-vqk6j         1/1     Running   0          77s
meshery-cpx-679cb4c5bb-5z8vc            1/1     Running   0          77s
meshery-istio-55bc6b4679-bhh84          1/1     Running   0          77s
meshery-kuma-64476f65fb-vzf98           1/1     Running   0          76s
meshery-linkerd-bb74b8dd9-bs6s9         1/1     Running   0          76s
meshery-nsm-846c648c97-xx8vw            1/1     Running   0          76s
meshery-operator-8899b86cf-cjsb4        1/1     Running   0          76s
meshery-osm-97995cd6f-pjfdd             1/1     Running   0          76s
meshery-traefik-mesh-65bc8888bc-nk5mn   1/1     Running   0          76s
```

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by panyuenlau** [comment]
https://github.com/meshery/meshery/pull/4194 will fix the UI integration test failure

**Review by DelusionalOptimist — COMMENTED** [review]
Thanks @panyuenlau. Meshery server, adapters and operator are getting installed now.
However, broker and meshsync don't. Is this expected @leecalcote @utkarsh-pro ?

**Comment by panyuenlau** [comment]
> Thanks @panyuenlau. Meshery server, adapters and operator are getting installed now.
> However, broker and meshsync don't. Is this expected @leecalcote @utkarsh-pro ?

Hmmm yea... the `meshery-operator` is not reconciling the `broker` and `meshsync` at all... 

And it seems like the `crds.yaml` was copied from https://github.com/meshery/meshery-operator/tree/master/config/crd/bases after using `controller-gen` (or the `make manifests` command) in the `meshery-operator` repo? 

If this is the case, should we also provide a `v1` package in the `meshery-oeprator/api` folder and then use `controller-gen` to auto-generate the new CRDs and finally copy them over here?

**Comment by panyuenlau** [comment]
> Thanks @panyuenlau. Meshery server, adapters and operator are getting installed now.
> However, broker and meshsync don't. Is this expected @leecalcote @utkarsh-pro ?

Hey @DelusionalOptimist, I updated this PR to use the auto-generated CRD manifests in the meshery-operator PR (https://github.com/meshery/meshery-operator/pull/203).

But somehow the `meshery-operator` is still not reconciling the broker and meshshync for some reason, logs:
```
time="2021-09-16T17:10:02Z" level=info msg="metrics server is starting to listen" app=meshery-operator
time="2021-09-16T17:10:02Z" level=info msg=reconcilerGroupmeshery.layer5.ioreconcilerKindMeshSync app=meshery-operator
time="2021-09-16T17:10:02Z" level=info msg=controllermeshsync app=meshery-operator
time="2021-09-16T17:10:02Z" level=info msg=reconcilerGroupmeshery.layer5.ioreconcilerKindBroker app=meshery-operator
time="2021-09-16T17:10:02Z" level=info msg=controllerbroker app=meshery-operator
time="2021-09-16T17:10:02Z" level=info msg="starting manager" app=meshery-operator
time="2021-09-16T17:10:02Z" level=info msg="starting metrics server" app=meshery-operator
time="2021-09-16T17:10:02Z" level=info msg="Starting EventSource" app=meshery-operator
time="2021-09-16T17:10:02Z" level=info msg="Starting EventSource" app=meshery-operator
time="2021-09-16T17:10:02Z" level=info msg="Starting Controller" app=meshery-operator
time="2021-09-16T17:10:02Z" level=info msg="Starting workers" app=meshery-operator
time="2021-09-16T17:10:02Z" level=info msg="Starting Controller" app=meshery-operator
time="2021-09-16T17:10:02Z" level=info msg="Starting workers" app=meshery-operator
```

**Review by leecalcote — APPROVED** [review]
Excellent. Thank you, @panyuenlau 👍

**Comment by panyuenlau** [comment]
I will update the PR later today so that the helm chart installation is consistent with `mesheryctl`

**Comment by leecalcote** [comment]
Haha! There it is, @panyuenlau! 🎈 😎

**Pull request merged**
