### PR TITLE
Broken URL FIX

### LINKED ISSUE #4681: [Docs] Page not linked
#### Current State
the highlights red part in the below image is not a link on this [page](https://docs.meshery.io/extensibility/adapters). 

#### Desired State
It should be a link to https://docs.meshery.io/project/contributing.

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by sahilsuman933**
Signed-off-by: Sahil Suman <sahilsuman933@gmail.com>

**Description**
Broken URL fix

This PR fixes #4681

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 455c8d4edef46f48821cf059013c938fe7aa0621 at: https://61a3c6a3bd4389a9e8c88ddb--meshery-docs-preview.netlify.app

**Comment by sahilsuman933** [comment]
@warunicorn19 Bhaiya can you please review this pull request

**Review by warunicorn19 — APPROVED** [review]
LGTM! Thank you @sahilsuman933 for seeing this to the end 😄.

**Comment by leecalcote** [comment]
Whoo-hoo, @sahilsuman933! 🎈

**Pull request merged**
