### PR TITLE
This PR fixes #7265 

### LINKED ISSUE #7265: [UI]-Hyperlink under dark mode not visible
#### Current Behavior
The Hyperlink is not properly visible under dark mode.
raw

#### Desired Behavior
Color should be changed to make it visible
update

I have sucessfully made the changes @leecalcote just need your permission to PR can you please assign me.

#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by parmishh**
**Notes for Reviewers**

This PR fixes #7265 

https://github.com/meshery/meshery/issues/7265
 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by parmishh** [comment]
@Chadha93 continuing our discussion from ##7265 #7266 I have made the changes and eslint error has been solved.



update

update2

**Comment by parmishh** [comment]
@Chadha93 can you please review it. All checks have passed.

**Comment by parmishh** [comment]
@Chadha93 is this issue for which I made a PR and passed all checks yesterday not considered anymore?

**Comment by parmishh** [comment]
@Chadha93 can you please review it. All checks have passed.

**Review by Chadha93 — APPROVED** [review]

**Comment by Chadha93** [comment]
Yay @parmishh :balloon:

**Pull request merged**
