### PR TITLE
[Docs] Restructure proposal

### PR DESCRIPTION
**Pull request by leecalcote**
Signed-off-by: Lee Calcote <lee.calcote@layer5.io>

**Notes for Reviewers**

This PR fixes #9883

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 2dba2a00f527b70930bd74c22e12adf6a0a18b50 at: https://659c793c0e2397340b173751--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit f4024760ed00044758866d68edd157b963c848fe at: https://659c95f15cac66489493e2e9--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit f842f7617356278977167884119d862ac4961757 at: https://659eea103163af16f1f92547--meshery-docs-preview.netlify.app

**Review by sudhanshutech — COMMENTED** [review]
Is this also the series in which topic will be restructured

**Comment by leecalcote** [comment]
> Is this also the series in which topic will be restructured? Just A FAQ section at end separate could be nice(just suggestion) . All docs site consist of separate section for that.
> 
> LGTM🚀

Yes, this is just a proposal as to how the content (sections, pages, material) of the docs will be structured. Yes, you're suggestion that a Conclusion or perhaps, a "Suggested Reading" be implicitly included on each page through their layout, based on `type` and `category` - - something that @vishalvivekm is to be working with for the dynamic table of content.s

**Pull request merged**
