### PR TITLE
Create tests for `mesheryctl exp relationships` command

### LINKED ISSUE #12136: Create Unit and Integration Tests for `mesheryctl exp relationships` Command
### Description
We need to develop comprehensive unit and integration tests for the `mesheryctl exp relationships` command. This command is responsible for listing, viewing, and searching MeshModel relationships, as well as generating relationship documents.

The goal is to ensure the correctness of the core functionalities, error handling, and interaction with the Meshery server.

### Current Behavior
Currently, there are no automated tests covering the `mesheryctl exp relationships` command, which includes:
[] Listing relationships (`mesheryctl exp relationships list`)
- Viewing details of a specific relationship (`mesheryctl exp relationships view`)
- Searching for relationships (`mesheryctl exp relationships search`)
- Handling interaction with the Meshery server and command prerequisites (e.g., server running, version validation).

### Desired Behavior
Tests should cover the following aspects:

1. **Unit Tests**:
   - **Model Prompt Selection**: Verify that the `selectRelationshipPrompt` function correctly displays and returns a relationship when multiple options are available.
   - **Argument Validation**: Ensure that missing or invalid arguments (e.g., invalid model names) trigger the appropriate error messages.
   - **Subcommand Handling**: Verify that invalid subcommands trigger the appropriate error messages.
   
2 **Integration Tests**:
   - **Server Interaction**: Mock the Meshery server and verify that the command correctly interacts with it, including:
     - Validating that the server is running.
     - Handling failed connections or invalid credentials.
     - Properly fetching and displaying relationships data.
   - **Data Retrieval and Display**: Ensure that relationships data is correctly retrieved, parsed, and displayed in both JSON and YAML formats.
   
4. **Error Handling**:
   - Handle cases where the Meshery server is unavailable.
   - Handle invalid or missing credentials.
   - Handle improper arguments or subcommands.

### Checklist:
- [ ] Listing relationships (`mesheryctl exp relationships list`)
- [ ] Viewing details of a specific relationship (`mesheryctl exp relationships view`)
- [ ] Searching for relationships (`mesheryctl exp relationships search`)
- [ ] Handling interaction with the Meshery server and command prerequisites (e.g., server running, version validation).

### Implementation
- Use mock APIs to simulate interaction with the Meshery server and return test data for relationships.
- Use existing testing frameworks and patterns for `mesheryctl`.
- Follow Meshery's contribution guidelines for writing tests.

### Resources
- The file to be tested: `mesheryctl/internal/cli/root/exp/relationships.go`
- [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)

### Contributor Resources

- ⌨️ [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by yaten2302**
**Notes for Reviewers**

- This PR fixes #12136 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

This PR creates tests for - `mesheryctl exp relationships` command, responsible for viewing, listing and searching MeshModel relationships.

### CODE REVIEW

**Comment by yash37158** [comment]
Hey @yaten2302, thanks for your PR! Could you please sign your commit?

**Comment by yaten2302** [comment]
Hey @yash37158 , ig my first commit is not signed, but since the changes have been pushed, could you please guide that how can I sign the changes now? <br>
image

Also, I've a doubt, I asked it over here, could you please guide regarding [this](https://layer5io.slack.com/archives/C0130BQ4L3T/p1731261518501859?thread_ts=1730815858.990569&cid=C0130BQ4L3T) also?

**Comment by vishalvivekm** [comment]
@yaten2302 
Let's discuss this during the Meshery Development call today at 9:00 AM CT | 8:30 PM IST. Adding it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit?pli=1#) || [meeting link](https://meet.layer5.io/meshery).

**Comment by yaten2302** [comment]
@vishalvivekm , may we add this as an agenda item for today's call?

**Comment by vishalvivekm** [comment]
Most definitely, yes

**Review by lekaf974 — APPROVED** [review]
LGTM

**Comment by lekaf974** [comment]
@alphaX86 can you have a 2nd review ?

**Comment by alphaX86** [comment]
Hi @yaten2302 thanks for your PR. Has this been tested on your side without any failures?

**Comment by alphaX86** [comment]
And please mark this PR as "ready" if everything is fine from your side. PR is in draft stage FYI

**Comment by yaten2302** [comment]
@alphaX86 , yes the tests are passing, I've checked.
Also, yes, this is a draft PR, I wanted to confirm that if these changes, looks good, then may I go on and write tests for other commands as well. The tests present rn are only for the `mesheryctl exp relationship list` cmnd, not for `view` or some others... So, as mentioned in the issue, may work on it furthur?

**Comment by yaten2302** [comment]
@vishalvivekm  , may I add this in today's agenda item?

**Review by lekaf974 — CHANGES_REQUESTED** [review]
Fix DCO issue

**Comment by yaten2302** [comment]
@lekaf974 @alphaX86 , actually, there are some issues while fixing the DCO. I'm closing this one and creating a new PR for the same, with the exact same changes.
Apologies for inconvenience.

**Pull request closed without merging**
