### PR TITLE
refactor: move from io/ioutil to io and os packages

### PR DESCRIPTION
**Pull request by Juneezee**
**Description**

The `io/ioutil` package has been deprecated in Go 1.16 (See https://golang.org/doc/go1.16#ioutil). This PR replaces the existing `io/ioutil` functions with their new definitions in `io` and `os` packages.

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
This is great, @Juneezee. Thanks for taking on this effort.

**Review by bariqhibat — APPROVED** [review]
Thanks for the PR and the release notes! Looks great and the CI passes fine too

**Review by leecalcote — APPROVED** [review]
Very helpful. Thank you, @Juneezee 👏

**Comment by leecalcote** [comment]
Yay, @Juneezee! 🎈

**Pull request merged**
