### PR TITLE
refractor: add enum for file operations among patterns, filters and apps

### PR DESCRIPTION
**Pull request by Abhishek-kumar09**
Signed-off-by: Abhishek-kumar09 <abhimait1909@gmail.com>

**Description**
Simulate enums for common file operations among filters, patterns and applications

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Did we land on centralizing first?

**Review by sudo-NithishKarthik — DISMISSED** [review]
This looks good. Although, we would ideally want to centralize this approach. But, lets merge this one first and then discuss about it, as this is the area that would be most affected without enums.

**Review by sudo-NithishKarthik — APPROVED** [review]
Looks good

**Review by bariqhibat — APPROVED** [review]
Yeah, let's do what @sudo-NithishKarthik said, looks good!

**Pull request merged**
