### PR TITLE
[UI] Color of Metrics Tab when selected fixed

### LINKED ISSUE #7290: [UI] Color of Metrics Tab when selected
#### Current Behavior

At /settings#metrics,
In dark mode, selected Grafana or Prometheus tabs have #607d8b color. As per the color scheme, It should be #00B39F.

https://user-images.githubusercontent.com/103871275/223193722-b9c38203-5037-4e5a-af3b-74e5fe1e382c.mp4

#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by soham4abc**
**Notes for Reviewers**

This PR fixes #7290 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

Dark Mode: 
image

Light Mode:
image

Please do have a look @leecalcote @hs05june

### CODE REVIEW

**Review by Yashsharma1911 — COMMENTED** [review]
Thanks for solving this LGTM 👏, can you remove extra formatting changes because those formatting changes are not required

**Comment by soham4abc** [comment]
> Thanks for solving this LGTM clap, can you remove extra formatting changes because those formatting changes are not required

I tried doing that but, It's resulting in eslint errors!

**Comment by soham4abc** [comment]
> Thanks for solving this LGTM clap, can you remove extra formatting changes because those formatting changes are not required

Done as per request. Please do have a look!

**Review by Yashsharma1911 — APPROVED** [review]
nice work 👏

**Comment by soham4abc** [comment]
@leecalcote please do have a look and let me know if it requires any changes or not! :-)

**Comment by leecalcote** [comment]
If @Yashsharma1911 approves... then so do I. 

Thanks, @soham4abc 👍

**Pull request merged**
