### PR TITLE
[Docs] Nighthawk setup steps 

### PR DESCRIPTION
**Pull request by Chadha93**
Signed-off-by: Gaurav Chadha <gauravchadha1676@gmail.com>

**Description**
Added the nighthawk setup procedure to run a performance test using load generator as Nighthawk

**Notes for Reviewers**
All commands verified and tested

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
@DelusionalOptimist these deployment steps seem complete, but how will Meshery know to use this externally deployed load generator?

**Comment by Chadha93** [comment]
> I think [this](https://61646010a841fead278bf32b--meshery-docs-preview.netlify.app/guides/performance-management) might be a better place to include this documentation seeing that the "Functionality" page describes the overall functionality of that particular feature and the "Guide" pages describe how to actually use that.

Thanks for pointing it out, @navendu-pottekkat I have shifted the information to the desired page and added a link to it under Nighthawk.

**Comment by navendu-pottekkat** [comment]
Okay. Thank you for clarifying @Chadha93

**Comment by DelusionalOptimist** [comment]
All, sorry for creating such confusion.
These docs are about how to get and use nighthawk in a development environment, with the current deployment method. So I think, these fit good in the contributing guide.

Basically, right now, if you're running meshery server locally, it expects the binaries to be present in `cmd` directory so that it can run the service and connect to it.
Though, this is temporary and would be changed later such that the server doesn't have any direct interaction with those, I thought it would be worth mentioning this for other contributors, for the meantime :sweat_smile:.

**Comment by Chadha93** [comment]
ohk, I have added the docs and link to it using the *  symbol so maybe it will give the developer easiness for using this for time being

**Pull request closed without merging**
