### PR TITLE
[mesheryctl] added update prompt

### LINKED ISSUE #2460: [mesheryctl] prompt user when new mesheryctl update is available
#### Current Behavior

no prompt

#### Desired Behavior

A prompt similar to
Screen Shot 2021-02-26 at 9 28 37 AM

The update check should fail silently if GitHub is not reachable

### PR DESCRIPTION
**Pull request by aneeshnema**
**Description**

This PR fixes #2460 
Screenshot 2021-03-05 110324

**[Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
💥

**Review by navendu-pottekkat — COMMENTED** [review]
@aneeshnema Looks good. Maybe we can also suggest by logging how the user can update rather than only showing that the update is available...

**Comment by navendu-pottekkat** [comment]
@aneeshnema I mean that we can maybe point to [this doc](https://docs.meshery.io/guides/upgrade#upgrading-meshery-cli) and say something like-

`Check https://docs.meshery.io/guides/upgrade#upgrading-meshery-cli for instructions on how to update mesheryctl`

**Comment by aneeshnema** [comment]
@navendu-pottekkat updated 
Screenshot 2021-03-05 123249

**Review by navendu-pottekkat — APPROVED** [review]

**Comment by navendu-pottekkat** [comment]
Nice! 🚀

**Comment by leecalcote** [comment]
Very cool, @aneeshnema

**Pull request merged**
