### PR TITLE
[Broadcast] Readjust fields for latest Meshkit broadcaster

### LINKED ISSUE #4250: Upgrade to MeshKit v0.2.27 Broadcast message type failure
#### Current Behavior
Upgrading to MeshKit v0.2.27 produces this error on build:

```
➜  meshery git:(master) ✗ make run-fast
cd cmd; go mod tidy; \
        BUILD="v0.5.58" \
        PROVIDER_BASE_URLS="https://meshery.layer5.io" \
        PORT=9081 \
        DEBUG=true \
        ADAPTER_URLS="mesherylocal.layer5.io:10000 mesherylocal.layer5.io:10001 mesherylocal.layer5.io:10002 mesherylocal.layer5.io:10003 mesherylocal.layer5.io:10004 mesherylocal.layer5.io:10006 mesherylocal.layer5.io:10007 mesherylocal.layer5.io:10008 mesherylocal.layer5.io:10009 meshery-nginx-sm:10010" \
        go run main.go;
# github.com/layer5io/meshery/internal/graphql/model
../internal/graphql/model/helpers.go:83:5: cannot use broadcast.OperatorSyncChannel (type broadcast.BroadcastSource) as type string in field value
../internal/graphql/model/helpers.go:84:5: unknown field 'Message' in struct literal of type broadcast.BroadcastMessage
make: *** [run-fast] Error 2
```

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by bariqhibat**
**Description**

This PR fixes #4250

**Notes for Reviewers**

Adjust fields for operator sync broadcaster

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
@bariqhibat heads-up: link check failures.

**Comment by Revolyssup** [comment]
@leecalcote  @bariqhibat  Is this PR ready to go?
I need the fix to get rid of error in order to make PR for k8s component generation.

**Comment by bariqhibat** [comment]
> @leecalcote  @bariqhibat  Is this PR ready to go?
> I need the fix to get rid of error in order to make PR for k8s component generation.

This is ready, but I don't precisely know why one check is failing.

**Review by utkarsh-pro — APPROVED** [review]
LGTM

**Pull request merged**
