### PR TITLE
Upgrade gqlgen

### PR DESCRIPTION
**Pull request by acald-creator**
**Notes for Reviewers**

This PR upgrade `gqlgen`, and it's actually important now to upgrade as I ran into an error generating the resolvers and others.

This will need to match in meshmap once the go.mod sync completes.

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Bad build...

**Comment by leecalcote** [comment]
...I meant to say that GitHub failed us with a bad build.

**Comment by acald-creator** [comment]
I thought `golangci-lint` has a timeout arg set, but apparently not.

**Comment by leecalcote** [comment]
> I thought `golangci-lint` has a timeout arg set, but apparently not.

Oh, is that what is going on?

**Comment by acald-creator** [comment]
> > I thought `golangci-lint` has a timeout arg set, but apparently not.
> 
> Oh, is that what is going on?

Actually the timeout arg is set at 3m, so we will need to set it a bit higher then, 5m should work. Ill update this PR

**Review by leecalcote — APPROVED** [review]
Yay!

**Pull request merged**
