### PR TITLE
[Extensions] Enhance Meshery Docker Extension UI

### LINKED ISSUE #9299: [Extensions] Enhance Meshery Docker Extension UI
### Current Behavior

Currently, there is an empty state for Adapters widget that was earlier used to provision specific service meshes. But recently Adapters were removed from the default deployment of Meshery so Meshery Docker Extension users are currently experiencing bad UX.

Screenshot 2023-11-02 at 10 34 12 PM

### Desired Behavior

Remove that widget from the main UI and make it more simple and elegant.

### Mockups

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Meshery Build and Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 UI Design For Meshery Extensions [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 📚 [Meshery Extensibility Providers](https://docs.meshery.io/extensibility/providers)
- ⌨️ [Meshery API Docs](https://docs.meshery.io/extensibility/api)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by senali-d**
**Notes for Reviewers**

This PR fixes #9299 

Screenshot 2023-11-16 at 9 19 47 PM

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by aabidsofi19** [comment]
@senali-d it would be great if we start using sistent here . 
we should be importing the icons from there now ..

**Comment by leecalcote** [comment]
This is looking good, @senali-d 😃

**Review by leecalcote — CHANGES_REQUESTED** [review]
Here's an item to resolve:

https://github.com/meshery/meshery/actions/runs/6894047287/job/18754991284?pr=9377#step:4:1951

```
#35 [ui 3/3] RUN cd ui; npm install --omit=dev; npm run build && npm run export; mv out /; mv public /
#35 196.3 Failed to compile.
#35 196.3 
#35 196.3 ./pages/_document.js
#35 196.3 Module not found: Can't resolve 'styled-jsx/server' in '/ui/pages'
#35 196.3 
#35 196.3 
#35 196.3 > Build failed because of webpack errors
```

**Comment by leecalcote** [comment]
Checking in ... ok, I see that that build failure is still present. Moving to next PR...

**Comment by senali-d** [comment]
Build error was related meshery ui. Fixed it here..

**Review by theBeginner86 — APPROVED** [review]

**Pull request merged**
