### PR TITLE
index in spanish page had some words still in englosh

### PR DESCRIPTION
**Pull request by alonsolopezr**
Signed-off-by: JOSE ALONSO LOPEZ ROMO <alonso.lopez.r@gmail.com>

**Description**
Some words in the index docs page, in the spanish section, were still in english.
This PR fixes #

**Notes for Reviewers**
Validate this pr please @jesuslerma, @ramrodo

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit b875d6439ffbce2edf41effc254ba930354478c6 at: https://615b98441f5f4a37e73d57ed--meshery-docs-preview.netlify.app

**Review by ramrodo — APPROVED** [review]
Great! :)

**Review by jesus-lerma — APPROVED** [review]
LGTM!

**Comment by alonsolopezr** [comment]
Excellent.. thanks.. I think the people in the workshop really liked it, and hopefully they start contributing this week 🙌🏼

**Comment by leecalcote** [comment]
Very cool. 😎

**Pull request merged**
