### PR TITLE
[Docs] - Refactored Old Docs with Emoji

### LINKED ISSUE #3456: [Docs] - Update and Refactor Old Releases in Meshery Docs to Have Emojis
#### Current State
The latest [release docs](https://docs.meshery.io/project/releases/) of Meshery, https://docs.meshery.io/project/releases/v0.5.30 have emojis in them while the older ones do not. Eg.: https://docs.meshery.io/project/releases/v0.5.1 

#### Desired State
All the releases should have emojis in them

#### Screenshots:

**With Emojis,** 

image

**Without Emojis,**

image

---

#### Contributor Resources

- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/meshery/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
- [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by adithyaakrishna**
Signed-off-by: Adithya Krishna <aadithya794@gmail.com>

**Description**

This PR fixes #3456 

**Notes for Reviewers**

This PR also updates the release-drafter.yml to have an emoji for General,

image

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit c526ae0d6ddbda96658fddcc8cec4f5d3a8b6874 at: https://60eb0291a46931ad4527b6c1--meshery-docs-preview.netlify.app

**Comment by alphaX86** [comment]
IG it's better to rebase only on master rather than fork branches... 👀

**Review by alphaX86 — APPROVED** [review]
LGTM bro 👍 🎉

**Comment by alphaX86** [comment]
But we need to decide if it's good to rebase every time, that's why I deleted a PR of mine 🤣

**Comment by adithyaakrishna** [comment]
Waait, you used to fork branches everytime? 👀 

I have only one local copy of meshery, I just run

```
- git checkout master
- git fetch upstream
- git rebase upstream/master
- git push origin master
- git checkout -b <new_branch_name>
```

Make the Changes, then `git add -A`, `git commit`, `git push origin <new_branch_name>`

**Comment by alphaX86** [comment]
Forks are great way to avoid changes on repos... Anyway either way are good actually but I won't fork my branches LOL similar to yours but I rebase only on master not on my working branch

**Review by leecalcote — APPROVED** [review]
Much better. Thank you, @adithyaakrishna

**Comment by leecalcote** [comment]
@adithyaakrishna be aware the that Release Drafter template for release notes could use this same formatting so that future release notes follow this improved formatting. Here's a link to the template - https://github.com/meshery/meshery/blob/master/.github/release-drafter.yml

**Pull request merged**
