### PR TITLE
Support multi-zone use of capability registry assets

### LINKED ISSUE #6814: [MeshModel] Server: Support multi-zone use of capability registry assets
#### Current Behavior
Currently, integrated systems that Meshery allows users to configure have their individual system (e.g. Kubernetes) components (e.g. Pod) registered into Meshery’s Database (into the Capabilities Registry tables) upon boot. Part of this registration process includes a depositing of component-specific icons (as light and dark mode SVGs) onto Meshery’s filesystem here - https://github.com/layer5io/meshery/tree/master/server/meshmodel/components.
This path isn’t accessible by Meshery UI as a client of the Nextjs “web server” under its exposed path, /ui/public/static here - https://github.com/layer5io/meshery/tree/master/ui/public/static - where other images are made available.

#### Desired Behavior
Rather than replicating the SVG files (or splitting them out from their respective component packages), ideally, we can configure Nextjs to also expose the images under the /server/meshmodel/components folders.

#### Implementation
Use Nextjs's [multi-zones](https://nextjs.org/docs/advanced-features/multi-zones) capability to expose capability registry assets.

#### Acceptance Tests
1. `/server/meshmodel` directory contents are accessible over http under `<meshery-server-host>`/static/meshmodel`

#### Mockups

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by aryabyte21**
Signed-off-by: AryaArunB <arya2001bhosale@gmail.com>

**Notes for Reviewers**

This PR fixes #6814
please  see if this fixes this issue, thanks!

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by acald-creator** [comment]
@aryabyte21 Thank you for your PR!

Can you provide the steps you took to ensure that the MeshModels are being served correctly?

I just received the error attempting to run the dev server that is also a proxy server as well.

```bash
make ui
cd ui; npm run dev ; cd ..;

> meshery-ui@1.0.0 dev
> eslint . --fix && NODE_OPTIONS='--openssl-legacy-provider' node ui_dev_server.js

node:internal/modules/cjs/loader:1042
  throw err;
  ^

Error: Cannot find module 'next/zone'
Require stack:
- /home/phxvlabs-io/go/src/github.com/experiments/meshery/ui/ui_dev_server.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1039:15)
    at Module._load (node:internal/modules/cjs/loader:885:27)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/home/phxvlabs-io/go/src/github.com/experiments/meshery/ui/ui_dev_server.js:5:18)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:82:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/phxvlabs-io/go/src/github.com/experiments/meshery/ui/ui_dev_server.js'
  ]
}
```

**Review by Abhishek-kumar09 — CHANGES_REQUESTED** [review]
It is modifying the ui_dev_server.js, the file is only responsible for accessing the dev server for localhost:3000. It shouldn't work for 9081, where our prod ui is hosted. Do we require change in next.js config?

**Comment by acald-creator** [comment]
I have an upcoming change for next.config.js to see if I can get MeshModel components to show up through Next.js itself, but it's buggy. I'm still testing it and hope to have a PR today.

**Comment by Chadha93** [comment]
@aryabyte21  Let's discuss the update of this PR on the Meshery Dev call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#) if you would. :)

**Comment by leecalcote** [comment]
@aryabyte21, thanks for engaging with us!

**Comment by leecalcote** [comment]
@aryabyte21, thanks much for this effort. I _think_ that the project has successfully circumnavigated this particular need for now. Let's close out this PR and re-open should the need arise again. Thanks again for contributing. Let's get you onto a new issue. 👍

**Pull request closed without merging**
