### PR TITLE
Add lint pre-commit check with husky

### LINKED ISSUE #3702: [UI] Add eslint pre-commit hook
#### Current Behavior
The only way to identify lint errors in meshery-ui is to run `npm run dev` or eslint manually.

#### Desired Behavior
Eslint pre-commit hook should be added so that lint checks happen before a commit has been made. 

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

### PR DESCRIPTION
**Pull request by humblenginr**
This PR fixes #3702 

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Do we anticipate these rules conflicting with contributor's existing linters? Do we expect that their IDE automatically picks up these rules or is it likely that many contributors will be surprised when they to go `git commit` and find they are out of compliance? Is there a set of .vscode settings or plugin that we might suggest?

**Comment by sudo-NithishKarthik** [comment]
When the contributor runs `git commit`, a pre-commit hook that we defined will run `eslint` using the set of rules that we provided. When a contributor has a different formatter(in the form of plugins) set up in his IDE, then, it might conflict. So, it is advisable to *disable plugins other than eslint for formatting and linting* if they have any. Having said that, after adding this pre-commit hook, even if the contributor had other plugins activated and that made changes to the codebase according to it's rules, at the time of committing, `eslint` will lint according to the rules that we provided and will not allow the commit unless it follows the rules that we provided.

**Comment by sudo-NithishKarthik** [comment]
The user need not configure anything in order for this hook to work, provided the contributor had run `npm install`

**Comment by leecalcote** [comment]
This is great, Nithish. Your remarks here would be great to have here
https://docs.meshery.io/project/contributing-ui as well.

**Comment by leecalcote** [comment]
@sudo-NithishKarthik is the pre-commit hook included in this PR? What conventions are we enforcing with respect to single vs double quotes?

**Comment by sudo-NithishKarthik** [comment]
`Husky` is the tool that we use for setting up pre-commit hook. It had already been setup with this project (Husky version 7), but the hooks were not configured because in versions 4+, we will have to do them on our own. So, i have degraded husky from v7 to v4 so that it automatically configures the hook.

**Comment by sudo-NithishKarthik** [comment]
I am tracking the extension of eslint rules in a different issue #3701

**Comment by sudo-NithishKarthik** [comment]
Yes, it is a temporary downgrade for auto configuration

**Comment by sudo-NithishKarthik** [comment]
> This is great, Nithish. Your remarks here would be great to have here
https://docs.meshery.io/project/contributing-ui as well.

Yes @leecalcote , once we add more rules and push this pr, we will add it to the docs

**Review by leecalcote — DISMISSED** [review]

**Comment by sudo-NithishKarthik** [comment]
@leecalcote , i have found another way of doing this without downgrading

**Comment by leecalcote** [comment]
😅

**Review by leecalcote — APPROVED** [review]

**Pull request merged**
