### PR TITLE
Feat: Implement new missing permissions page

### PR DESCRIPTION
**Pull request by dragon-slayer875**
**Notes for Reviewers**

This PR fixes updates the design of the missing permissions page.

image

image

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by dragon-slayer875** [comment]
After discussion with @Yashsharma1911, it was decided to put the request roles feature on hold for now as it will need some help from him, which he will provide as soon as he gets time from his exams.

Apart from that this new layout is ready to be used.

**Comment by leecalcote** [comment]
> After discussion with @Yashsharma1911, it was decided to put the request roles feature on hold for now as it will need some help from him, which he will provide as soon as he gets time from his exams.
> 
> Apart from that this new layout is ready to be used.

Thank you for this status update.

**Comment by dragon-slayer875** [comment]
> @dragon-slayer875, you're refactoring to simply include the org switcher, right? If you can't achieve this tomorrow, then simply update the verbiage to be more friendly. This task has been outstanding for ... well, entirely too long.

Lee I think there's some miscommunication going on between us. 
This page is functional right now. 
This PR can be reviewed and following the review can be merged.

**Comment by leecalcote** [comment]
@dragon-slayer875 perhaps, the stale screenshots and stale PR description are throwing us off.

**Comment by leecalcote** [comment]
Provide a refreshed state of what is delivered here, please.

**Pull request merged**
