### PR TITLE
Changed the ui dev server port to 4000

### LINKED ISSUE #3947: [UI] Change dev server port
#### Current Behavior
Currently, Meshery UI dev server listens on `localhost:3000`. When a contributor wants to setup Grafana, which also listens on `localhost:3000`, he will get an error saying that the port is busy.

#### Desired Behavior
We need to change the Meshery UI dev server port to something else, like `:3081` or something, so that, it doesn't clash with anything else.

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by sayantan1413**
Signed-off-by: sayantan1413 <sayantanbose2001@gmail.com>

**Description**

The Ui dev server port is changed to 4000. The workflow is that 
1. Checks if anything is running on port 4000
2. If it is then it will go in a loop and will increase by 1
3. this process will continue untill the next vacant port is found
4. and ithen it will get ready at that port.

This PR fixes #3947 

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
What change are we intending for the provider-ui?

**Comment by leecalcote** [comment]
4001 sounds good or ideally a port number adjacent to the provider-ui's port number. The process to check for open port, then increment when it isn't free is greata.

**Comment by leecalcote** [comment]
If we set the ui to start at 4001 by default (assuming no conflict), will you update the provider-ui to have similar port detection logic and start at maybe 4002 (since it is current set to start at 4001)?

**Comment by sayantan1413** [comment]
Yeah @leecalcote sure I will shift the same logic to provider Ui too.✔️

**Comment by warunicorn19** [comment]
Currently the provider UI starts at 3001

**Review by leecalcote — APPROVED** [review]
LGTM

**Comment by leecalcote** [comment]
@sayantan1413 will you verify that none of the Contributing docs need to be updated? Either on docs.meshery.io

**Comment by sayantan1413** [comment]
@leecalcote forwarding this PR to the meshery-ui-restructing branch

**Comment by leecalcote** [comment]
@sayantan1413 gotcha. Ok, sounds great. I think this is a positive change and will be helpful. 👍

**Comment by leecalcote** [comment]
@warunicorn19 @adithyaakrishna, what do you think of these proposed changes?

**Comment by warunicorn19** [comment]
@leecalcote I think these changes look good, there's no conflict with any other ports that we use throughout our projects, and even if there is, the port changes by +1, so this is good👍

**Pull request closed without merging**
