### PR TITLE
[Extension] RJSF - remove description and add tooltip to fields

### PR DESCRIPTION
**Pull request by bariqhibat**
Signed-off-by: Bariq <bariqhibat@gmail.com>

**Description**

**Notes for Reviewers**
Meshery Extension:
1. Remove description fields in the field input
2. Add help tooltip for description

image

image

Final implementation
image

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by sudo-NithishKarthik** [comment]
Can we reduce the icon size @bariqhibat  ?

**Review by leecalcote — APPROVED** [review]

**Comment by leecalcote** [comment]
@bariqhibat @sudo-NithishKarthik conflict - https://github.com/meshery/meshery/pull/4171/conflicts

**Comment by bariqhibat** [comment]
Due to unforeseen issues, I reverted back to the old design but hide the description for aesthetics. 
The issues are:
- Custom fields input component isn't able to update the states of the form from inside the component easily. Hence, there might need a refactoring on how to manage RJSF form states

**Comment by bariqhibat** [comment]
Latest commit

image

**Comment by leecalcote** [comment]
What a clean UI this makes.

**Review by leecalcote — APPROVED** [review]

**Pull request merged**
