### PR TITLE
Postgre-component-version/signoff

### PR DESCRIPTION
**Pull request by Ayush9026**
**Notes for Reviewers**

This PR fixes Icon for Meshmodel Postgres Component - Postgres Version  https://github.com/meshery/meshery/issues/8756

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by saurabh100ni** [comment]
Let's discuss this Item in tomorrow's website call, 
please add it as your agenda if you would: 
https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit

**Comment by saurabh100ni** [comment]
Let's discuss this on the Meshery dev call tomorrow,
Please add this as your agenda item in Docs: https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit

**Review by MUzairS15 — COMMENTED** [review]
@Ayush9026 This isn't complete, will you be continuing on this?
(Read the step mentioned in issue description).

**Comment by leecalcote** [comment]
Filename has redundant extensions.

**Pull request closed without merging**
