### PR TITLE
Adding Operator Settings in Environments Tab

### LINKED ISSUE #2214: Operator view in the configuration and main page
#### Desired Behavior
A new section needed to be created for the operator flow. Below are the screenshots for the design.

#### Mockups
System Dashboard
Settings

### PR DESCRIPTION
**Pull request by dhruv0000**
**Description**

This PR fixes #2214

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
@dhruv0000 what remains to complete here?

**Comment by dhruv0000** [comment]
The API endpoint updates the data only when the component is loaded or changed. Need a better solution like SSEs to be implemented which I suggested before, or else the user would have to click the chip to update the data.

**Comment by dhruv0000** [comment]
Mabey we can merge this PR and I can work on implementing SSEs next.

**Comment by dhruv0000** [comment]
The PR is good to go @leecalcote.

**Comment by leecalcote** [comment]
Good to go! 🎉

**Pull request merged**
