### PR TITLE
resolved label cutoff issue

### LINKED ISSUE #9862: [Enhancement] Label being cutoff in dashboard
### Current Behavior
On a smaller screen, the label of the tab menu in the dashboard is cut off
image

### Desired Behavior
Label should not be cut-off in smaller screens

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by Aniket-76**
flexbasis set to "unset" from class MuiTab-fullWidth

**Notes for Reviewers**

This PR fixes #9862

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — COMMENTED** [review]
@Aniket-76, thanks. Is this introducing a new issue of label overlapping?

**Comment by Aniket-76** [comment]
> @Aniket-76, thanks. Is this introducing a new issue of label overlapping?

I didn't see anything like that on my side, at least from what I noticed.

**Comment by saurabh100ni** [comment]
Hi @Aniket-76  ,
Thanks for your PR! I encourage you to share this in the Meshery Development Meeting today at 8:30 PM IST. Share your screen, and walk us through it. It's cool to take and share feedback. Check the [Doc](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit) here to include this PR.

You're welcome at the meeting

Check to [community calendar](https://layer5.io/community/calendar) for more details of meetings at Layers.

**Review by sudhanshutech — APPROVED** [review]

**Comment by sudhanshutech** [comment]
lgtm, there is no issue of cutoff

**Pull request merged**
