### PR TITLE
[ui] Update grammar in operator removal message

### LINKED ISSUE #3182: [UI] Grammar in Operator removal message
#### Description
A verbiage change is needed in the following message:

Screen Shot 2021-06-09 at 12 43 21 PM

#### Expected Behavior
Ideal verbiage:

Title: Remove Meshery Operator from this cluster?
Description: Meshery is now disconnected from your Kubernetes cluster. Do you want to remove the Meshery Operator from your cluster as well? 

#### Location
Find this message when removing the Kubernetes cluster connection on the Settings page (http://localhost:9081/settings)

---

**Contributor Resources:**
- (Contributing Docs](https://docs.meshery.io/project/contributing)

### PR DESCRIPTION
**Pull request by josephmidura**
Signed-off-by: Joseph Midura <josephmidura632@gmail.com>

**Description**

This PR fixes #3182

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by josephmidura** [comment]
Screen Shot 2021-06-10 at 5 10 31 PM

**Review by leecalcote — APPROVED** [review]
Looks great, @josephmidura 👍 

@ramrodo, the Netlify failed build checks are examples of an errant failure. Ideally, we're not invoking a netlify builds when no /docs/* are changed as those builds are unnecessary. And in this case, their failed build checks are preventing the PR from being merged.

**Comment by ramrodo** [comment]
> Looks great, @josephmidura +1
> 
> @ramrodo, the Netlify failed build checks are examples of an errant failure. Ideally, we're not invoking a netlify builds when no /docs/* are changed as those builds are unnecessary. And in this case, their failed build checks are preventing the PR from being merged.

It seems there is another bug from Netlify builds. I'll check that this weekend to have all the tests green again.

**Comment by leecalcote** [comment]
Re-running Netlify checks...

**Review by leecalcote — APPROVED** [review]
Wonderful. Thank you, @josephmidura 💪

**Pull request merged**
