### PR TITLE
Aabidsofi/k8s switcher

### LINKED ISSUE #8623: [UI] Infinite Loading on Pinging K8s Context
### Current Behavior

Currently, when I user clicks on k8s context in the context selector then user observe an infinite loading.

https://github.com/meshery/meshery/assets/73700530/bb051b34-a804-4b6c-846d-1fbc82d01b88

### Desired Behavior

Ensure this infinite loading is not observed and users should be able to ping it as they used to do.

### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by aabidsofi19**
**Notes for Reviewers**

This PR fixes #8623

https://github.com/meshery/meshery/assets/65964225/49e44028-5372-4d0b-9a01-56f350445701

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by Ghat0tkach** [comment]
@aabidsofi19  Let's discuss this on Meshery Dev call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#) if you would. :)

**Comment by aabidsofi19** [comment]
yup calling `this.props`  was one issue , but i have fixed the error details , added notification details , and there was a undefined function in errorHandler

**Comment by theBeginner86** [comment]
resolved conflicts 👍

**Review by theBeginner86 — APPROVED** [review]
LGTM

**Pull request merged**
