### PR TITLE
migrate theming to user prefs

### PR DESCRIPTION
**Pull request by aabidsofi19**
**Notes for Reviewers**

This PR fixes #

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by aabidsofi19** [comment]
@MUzairS15  i am setting theme as a toplevel preference , but he api is returning 500 . might be we need backend updates

**Comment by MUzairS15** [comment]
Can you paste the pref object that you are sending?

**Comment by aabidsofi19** [comment]
> Can you paste the pref object that you are sending?

@MUzairS15  request :
image
response:
image

**Review by leecalcote — APPROVED** [review]
Looks good!

**Comment by leecalcote** [comment]
@aabidsofi19, we do have these three eslint errors:

```
/home/runner/work/meshery/meshery/ui/components/Header.js
  1:28  error  'useLayoutEffect' is defined but never used  no-unused-vars

/home/runner/work/meshery/meshery/ui/components/UserPreferences/index.js
  47:28  error  'useThemePreference' is defined but never used  no-unused-vars

/home/runner/work/meshery/meshery/ui/pages/_app.js
  41:8  error  'theme' is defined but never used  no-unused-vars
```

**Comment by MUzairS15** [comment]
> @MUzairS15 i am setting theme as a toplevel preference , but he api is returning 500 . might be we need backend updates

Yes, I see theme is being stored at top level, (updated_at, test preferences...).

BTW, any reason for not storing in the remoteProviderPreferences?

**Comment by aabidsofi19** [comment]
> > @MUzairS15 i am setting theme as a toplevel preference , but he api is returning 500 . might be we need backend updates
> 
> Yes, I see theme is being stored at top level, (updated_at, test preferences...).
> 
> BTW, any reason for not storing in the remoteProviderPreferences?

yeah because i am making it for whole meshery ui , so thought it shouldnt be specific to remoteProvider .

**Comment by MUzairS15** [comment]
Yeah, but the user record and prefs are stored in remote provider, so I
think better to place them inside provider prefs.

**Pull request merged**
