### PR TITLE
Removed extra single quotes from make commands

### PR DESCRIPTION
**Pull request by VaibhavMalik4187**
* Running "make mesheryctl-linux-amd64" used to fail because of presence of double quotes in the LDFLAGS variable in the Makefile.
* Removed the double quotes fixes the error.

Fixes: https://github.com/meshery/meshery/issues/8378

**Notes for Reviewers**

This PR fixes #

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by VaibhavMalik4187** [comment]
@leecalcote can you please review this PR? Thanks!

**Review by suhail34 — CHANGES_REQUESTED** [review]
This broke the normal make command 
https://github.com/meshery/meshery/blob/f7593356b8cf5bbfa3e811dc6e8e852465bd0224/mesheryctl/Makefile#L9-L11
Please mind adding quotes to this both too

**Comment by VaibhavMalik4187** [comment]
> This broke the normal make command
> 
> https://github.com/meshery/meshery/blob/f7593356b8cf5bbfa3e811dc6e8e852465bd0224/mesheryctl/Makefile#L9-L11
> 
> Please mind adding quotes to this both too

Thanks for reporting the regression @suhail34. To fix the regression, I kept the LDFLAGS variable wrapped in double quotes and removed the extra single quotes from the `make mesheryctl-*` commands. Hopefully, that'll be okay.

**Review by suhail34 — APPROVED** [review]
LGTM now

**Comment by VaibhavMalik4187** [comment]
@leecalcote is this PR good to go?

**Comment by leecalcote** [comment]
Good to go. 🚀

**Pull request merged**
