### PR TITLE
[Docs] SMI Guide

### PR DESCRIPTION
**Pull request by chandrashritii**
**Description**

Update the Meshery-SMI guide

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
@chandrashritii the pr/draft label is currently affixed. There is a conflict to resolve.

**Comment by chandrashritii** [comment]
Not sure why the DCO check is failing. The commits have been signed off

**Review by NupurThakur27 — COMMENTED** [review]
@chandrashritii DCO failed on some of your commits

**Review by leecalcote — CHANGES_REQUESTED** [review]
A number of inaccuracies here. Will need a rewrite.

**Comment by leecalcote** [comment]
@chandrashritii let's chat, if assistance is needed.

**Pull request closed without merging**
