### PR TITLE
[Docs] Implementing opengraph protocol 

### LINKED ISSUE #5960: [Docs] Ensure OpenGraph image for all Meshery Docs pages
#### Current State
Meshery Docs doesn't have an [opengraph image](https://ogp.me/) defined across each of its pages.

#### Desired State
Modifying an existing `include` and `layout`, ensure that every page defines https://github.com/meshery/meshery/blob/master/docs/assets/img/meshery.png as the image.

https://cards-dev.twitter.com/validator can be used to help verify implementation.

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by kamalbuilds**
Signed-off-by: Kamal Nayan <95926324+legendarykamal@users.noreply.github.com>

**Description**

This PR fixes #5960 

An effort to  Ensure OpenGraph image for all Meshery Docs pages.

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit eac2e3e101d9eec236cf60d912ba95da947eceb3 at: https://6311fc501f8fa60058f1f9b7--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 07934348b3f35ae6b1be0e9c4d2267e9d7acc2cd at: https://6311fe3091afdf063944e34f--meshery-docs-preview.netlify.app

**Comment by legendarykamal** [comment]
@leecalcote just confirming, am I on the right path ?

**Comment by l5io** [comment]
🚀 Preview for commit 84aafab5bcfa11124a4e19885db245e88ca7872b at: https://63121f0f484a6c234026066b--meshery-docs-preview.netlify.app

**Comment by legendarykamal** [comment]
Update -> I have reverted doc/v0.4/search.html changes as after going much through docs, I found that It will auto be overwritten. .

**Comment by l5io** [comment]
🚀 Preview for commit 9774feffd569a04e3905ca8c1bd4ee8b91d59d67 at: https://63122459484a6c28aa2603c5--meshery-docs-preview.netlify.app

**Comment by leecalcote** [comment]
Is this PR still draft?

**Comment by legendarykamal** [comment]
> Is this PR still draft?

no, adding the metatags in _includes  file shall ensure that we have Opengraph protocol on all the pages .

**Comment by leecalcote** [comment]
Removing `pr/draft` label...

**Review by leecalcote — APPROVED** [review]
lgtm

**Pull request merged**
