### PR TITLE
Add API Service Icon

### LINKED ISSUE #8732: [MeshModel] [UX]: Icon for Kubernetes Component - API Service
### Current Behavior
Meshery is a powerful platform that contains over [200 integrations](https://layer5.io/cloud-native-management/meshery/integrations) for managing cloud-native applications. MeshMap is an extension of Meshery that visually represents these integrations and components. Currently, most of the icons used in MeshMap have the default shape of a circle. However, to improve visual clarity and consistency, we need to design custom icons for MeshMap components.

### Desired Behavior
A new Icon for  **API Service** needs to be created. This issue calls for a volunteer to draft a new Icon.

### Instructions for Components
While the default shape for new components is a circle, each component should be considered for its best-fit shape.
1. Review and familiarize with the available set of predefined relationship types. Refer to the Cytoscape [node types](https://js.cytoscape.org/demos/node-types/) for a list of possible shapes. 
1. Propose a specific shape, best-suited to visually represent the Component. Example - Deployment as a pentagon, DaemonSet as a skull icon etc.
3. Create two versions of the icon one is white and another one is colored
4.  Make a PR after adding the icon inside the [new-icon folder](https://github.com/meshery/meshery/tree/master/ui/assets/new-icons) present in the meshery repository
5. Provide the icon in SVG format
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- [MeshModel Repository](https://github.com/meshery/meshery/tree/master/server/meshmodel)
- 🖥 [MeshModel Overview](https://docs.google.com/presentation/d/1SQMfyu5shjpGKlYONdVzOtd7UYTgLWBcgUvHMLCZ2tY/edit#slide=id.g226f5de5180_19_259)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by ShatilKhan**
**Notes for Reviewers**

This PR fixes #8732

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.
 
Description:
Initial PR, Please give feedback on the current Icon. I haven't made the white version yet. If this design is okay & approved I will add in the white version.

### CODE REVIEW

**Comment by ShatilKhan** [comment]
I just noticed I made some mistakes in the design, I'm working on fixing it. Will update soon.

**Comment by leecalcote** [comment]
There is a plug-to-plug design that exist for this component already, right, @ShatilKhan? 

We'll want to focus on the components that still have their generic model logo (in this case, the Kubernetes logo).

**Comment by leecalcote** [comment]
@ritiksaxena124 will you confirm that the referring issue wasn't opened by mistake or that there wasn't accidental conflict? Should @ShatilKhan pick up a different component's icon to work on?

**Comment by leecalcote** [comment]
@ShatilKhan as you work through icons, know that we desire to avoid lettering in the icons.

**Comment by ritiksaxena124** [comment]
Oh yes, we have a plug-to-plug icon for API service. @ShatilKhan you can take up another icon issue. btw you are doing great and on the right path 🙌

**Comment by ShatilKhan** [comment]
Thanks @ritiksaxena124, that means a lot. Trying to contribute a little bit everyday😃
I'll take on another icon issue.

**Comment by ritiksaxena124** [comment]
When you do will you check on the [playground](https://playground.meshery.io/extension/meshmap) as well if the icon has been added already or not?

**Comment by saurabh100ni** [comment]
Let's discuss this on the Meshery dev call tomorrow,
Please add this as your agenda item in Docs: https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit

**Pull request closed without merging**
