### PR TITLE
Fixed [UI] table in meshery docs

### PR DESCRIPTION
**Pull request by yash37158**
The table for "Meshery Adapter For Cilium" is not displayed correctly. You can see it in the docs [here](https://docs.meshery.io/reference/error-codes#meshery-adapter-for-cilium).

Fixed the table for meshery adapter for cilium #7141 
**Notes for Reviewers**

This PR fixes #

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 4303ce40e0bd8a8fd93db938bc3053c04bfb8a70 at: https://64a520702b046c6b9100b8eb--meshery-docs-preview.netlify.app

**Comment by yash37158** [comment]
@leecalcote @Chadha93 Need a review on this

**Comment by l5io** [comment]
🚀 Preview for commit f71a1317b58a7939763d5cc08235efbfb894a919 at: https://64a651034e58923988f46b30--meshery-docs-preview.netlify.app

**Comment by sudhanshutech** [comment]
@yash37158 Let's discuss this on Websites Meeting call on Monday. Please add this as an agenda item in the [meeting mintes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.69qskjv558bk) if you would

**Comment by yash37158** [comment]
@Chadha93 @leecalcote @sudhanshutech are we good to merge this ?

**Comment by l5io** [comment]
🚀 Preview for commit 1bb2c758ea1048de9c894cf1f1e8cb1590fdc752 at: https://64ad636c222b2b0acf6b06e4--meshery-docs-preview.netlify.app

**Comment by leecalcote** [comment]
@yash37158 in a separate PR, can you make the links in the table clickable as intrapage anchors?

**Comment by yash37158** [comment]
As I can check, the intra-page anchor for meshery-cilium is not working.

**Comment by Chadha93** [comment]
@yash37158  Let's discuss this on the Meshery Dev call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#) if you would. :)

**Comment by yash37158** [comment]
sure @Chadha93

**Comment by leecalcote** [comment]
@yash37158 ok, can you fix that particular link?

**Comment by yash37158** [comment]
Sure @leecalcote i'll fix that

**Pull request merged**
