### PR TITLE
[Docs] Universally append

### LINKED ISSUE #3078: [Docs] Universally append " | Meshery" to the end of page titles
#### Current State

Some individual pages have "| Meshery" added to their `<title>`s.

#### Desired State

While this text **should** be appended, no individual page should have this appended as a one-off. This text should be globally appended from within the head.html file - https://github.com/layer5io/meshery/blob/ed11d7c831823b6aa005764bb79a33822655bcd0/docs/_includes/head.html#L21

#### Acceptance Criteria

1. No page has this text individually specified (all existing references should be removed).
2. All pages should have this text visibly appended in their title (when viewed by a user).

---

#### Contributor Resources

- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
- [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by Patil2099**
Fixes #3078

### CODE REVIEW

**Comment by leecalcote** [comment]
Thanks, @Patil2099. Please execute these instructions to amend a sign-off on your commit(s) - https://github.com/layer5io/meshery/pull/3081/checks?check_run_id=2712278238

**Comment by adithyaakrishna** [comment]
@Patil2099 Please do execute the instructions mentioned in the above comment, once done will review it 💯

Also, Great work 🎉
I should have thought about this, PR #3000 Added titles to the pages and this could have been implemented in one file instead of altering 20 👀🤦‍♂️

**Comment by leecalcote** [comment]
Looks great, @Patil2099 👍

just to soon as you amend your commit with your sign-off, we will be good to go.

**Comment by Patil2099** [comment]
I think it is ready for review now @adithyaakrishna  @leecalcote.

**Comment by leecalcote** [comment]
Yay, @Patil2099! 🎈

**Pull request merged**
