### PR TITLE
[Server] fix #6357: race condition in k8s component registration

### LINKED ISSUE #6357: [Server] Race condition in K8s component registration
In the following code, the reference to range value `ctx` at line 86 generates a race condition because it is a reference in the body of a gorutine.

https://github.com/meshery/meshery/blob/f2b1ef8c7b987175f6e3af8e1d1cee2d0a9f3163/server/models/k8s_components_registration.go#L50-L96

([here](https://go.dev/play/p/pmmyHsSwkL2) a simplified version of the bug)

Bug found by [revive](https://github.com/mgechev/revive)

### PR DESCRIPTION
**Pull request by chavacava**
Signed-off-by: chavacava <salvadorcavadini+github@gmail.com>

This PR fixes #6357

**Notes for Reviewers**
This PR fix the race condition by passing the range value as argument of the concurrent function.
The PR also includes some code reorganization to make it more GO idiomatic.

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
@acald-creator, will you kindly give this a look today?

**Comment by leecalcote** [comment]
> Sure, tentatively, it looks good to me. I did see race conditions in other places, but don't remember where, so I will be checking.

thank you, @acald-creator 👍 


@sudo-NithishKarthik please give this a once-over.

**Comment by leecalcote** [comment]
@Revolyssup what feedback do you have?

**Review by Revolyssup — APPROVED** [review]

**Comment by Revolyssup** [comment]
LGTM

**Pull request closed without merging**
