### PR TITLE
Add mode toggle icons

### LINKED ISSUE #7208: [Docs]Dark mode icon in docs in dark mode
#### Current State
In dark mode, the icon is the same as in light mode (the sun icon)
image

#### Desired State
The icon in dark mode should be the dark mode icon as in other websites
image

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by vishalvivekm**
**Notes for Reviewers**

This PR fixes #7208

- sets dark mode in docs by default issue  #7190 
- merges moniker and codes meshery/meshery.io#1020
-  updates the mode toggle icons (currently there's same icon ☀ for both modes):

in light mode 
Screenshot_20230228_005348

in dark mode 
Screenshot_20230228_005336

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.
Signed-off-by: Vivek Vishal <110674407+vishalvivekm@users.noreply.github.com>

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 5e76cb078bf16c4d2990f805d696caecd78fc398 at: https://63fd3a1610709d13aa583990--meshery-docs-preview.netlify.app

**Review by chinu-anand — CHANGES_REQUESTED** [review]
Please remove changes other than those pertinent to the issue you are actually working on.

**Comment by vishalvivekm** [comment]
> Please remove changes other than those pertinent to the issue you are actually working on.

Yes, even previous commits get associated with my this PR even when i'd created a new branch locally for this specifically and pushed the commit on that. Also my last PR got messed up ( context: "rebase")  so it  ended up strange. 
I"ll figure out how to remove those and update the PR. @chinu-anand

**Comment by chinu-anand** [comment]
Have you tried `git reset --hard` ? This will probably solve the issue, but use with caution always. Try different things.

**Comment by l5io** [comment]
🚀 Preview for commit 72872668d5985644924373e8a14beaf151fce2c0 at: https://63fdf61618d51002609fd2af--meshery-docs-preview.netlify.app

**Comment by vishalvivekm** [comment]
> Have you tried `git reset --hard` ? This will probably solve the issue, but use with caution always. Try different things.

I'll be back with a update soon! Thanks.

**Pull request closed without merging**
