### PR TITLE
[Dashboard] Fix DB mutex from concurrent read/write and refactoring gql subs

### LINKED ISSUE #4440: [Server] DB is locked due to multiple read/write at the same time
#### Current Behavior

Due to concurrent read/write at the same time, db is locked, making no read and write is happening.
[Reference issue](https://github.com/mattn/go-sqlite3/issues/632) from Golang SQLite3 repo.

#### Expected Behavior

Read and write should be committed perfectly without any issues, if there's any read/write running on the DB (and made the db locked), the next read/write will need to be wait for this read/write to finish and then execute their functionalities.

#### Environment

- **Host OS:** Linux (Windows WSL)
- **Platform:** Kubernetes
- **Meshery Server Version:** edge-latest
- **Meshery Client Version:** edge-latest

#### To Reproduce
1. Setup Meshery Server with its brokers, NATS, and operators
2. Setup a service mesh and make sure it is detected by Meshery
3. Go to Dashboard
4. See error "db is locked"

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by bariqhibat**
**Description**

This PR fixes #4440

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — DISMISSED** [review]

**Review by utkarsh-pro — DISMISSED** [review]
LGTM

**Comment by bariqhibat** [comment]
Good to merge? @leecalcote @utkarsh-pro

**Comment by bariqhibat** [comment]
Small changes: fix tables not being found from sqlite3 db

**Comment by bariqhibat** [comment]
Met with an error with this PR, checking
image

**Comment by leecalcote** [comment]
@bariqhibat, a small conflict has popped up.

@utkarsh-pro will you queue this into your review backlog?

**Comment by leecalcote** [comment]
Resolved conflict.

**Review by utkarsh-pro — APPROVED** [review]
LGTM

**Pull request merged**
