### PR TITLE
Solved issue #3434, fixed isMesheryRunning function by making it ping…

### LINKED ISSUE #3434: [mesheryctl] Fix `IsMesheryRunning()` for locally running meshery
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior

Currently many commands fail to execute because the function fails to detect if meshery is running locally or not.

#### Desired Behavior

It should detect, ofcourse!
Send a GET request to http://localhost:9081/api/version ? If the response is 200 then it is running and reachable or else it is not. and that means Meshery is might be running local

---

#### Contributor Resources

- [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by Revolyssup**
… to the meshery server to check if meshery is running

Signed-off-by: Ashish Tiwari <ashishjaitiwari15112000@gmail.com>

**Description**

This PR fixes #3434 

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 1432ac51526e172865386f066e16f47235c6513c at: https://60ec0260a46931c85b27b578--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 3b4240d18dd5648721e395ca660b9c822c2e3f2e at: https://60ec03695a8535b8af8e0a4c--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit ea63ad1270a6e9e42999f4f4585e270fac2bff39 at: https://60ec041b6f32a877248c0948--meshery-docs-preview.netlify.app

**Comment by piyushsingariya** [comment]
@Revolyssup The issue was supposed to fix the function not rework it completely. The issue is about adding an additional check to `IsMesheryRunning` that is sending the request and all.
Discussing things save a lot of your precious time.

**Comment by leecalcote** [comment]
@Revolyssup thanks for this! Much appreciated.

@piyushsingariya will you confirm if this change is still needed?

**Comment by piyushsingariya** [comment]
@leecalcote This change is being resolved through #3495

**Pull request closed without merging**
