### PR TITLE
Fixing the test failure

### LINKED ISSUE #9825: [Mesheryctl] Lint check failures
Thanks, @Althaf66. See the [failed check annotations](https://github.com/meshery/meshery/actions/runs/7384544622/job/20087775484?pr=9811)? Fixing these would be a great next step for you.

_Originally posted by @leecalcote in https://github.com/meshery/meshery/issues/9811#issuecomment-1874336014_

### PR DESCRIPTION
**Pull request by Althaf66**
**Notes for Reviewers**

This PR fixes #9825 
Fixing the unit test cases.

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — COMMENTED** [review]
Please list the component your working on in the subject line of the PR.

**Comment by vishalvivekm** [comment]
@Althaf66  Let's discuss this on the Meshery Dev call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#) if you would. :)

**Comment by Althaf66** [comment]
One test case is still failing 😥
https://github.com/meshery/meshery/actions/runs/8174993665/job/22351158235?pr=10484

**Comment by leecalcote** [comment]
Almost there, @Althaf66

**Pull request merged**
