### PR TITLE
Move all components to sistent single package

### LINKED ISSUE #9598: Tables: Include 100 row maximum
<@U04PQB6E85V> a low priority item to verify: the Sistent datatables ship with a default pagination supporting up to 100. In some places where datatables are used, it’s only up to 25 records max currently.

[Slack Message](https://layer5io.slack.com/archives/C023QGMSH8D/p1701813031294079)

### PR DESCRIPTION
**Pull request by sudhanshutech**
**Notes for Reviewers**

This PR fixes #9598 

1. Move all components to sistent single package i.e @layer5/sistent
2. All tables will have standard pagination props , so we don't need to include it

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Thanks for including your #2 note. 👍

**Review by leecalcote — APPROVED** [review]
Both light and dark mode are good to go?

**Comment by leecalcote** [comment]
@sudhanshutech the dashboard still isn't responsive.

**Comment by sudhanshutech** [comment]
> Both light and dark mode are good to go?

yes its good

**Comment by sudhanshutech** [comment]
> @sudhanshutech the dashboard still isn't responsive.

ok, i will take a look

**Pull request merged**
