### PR TITLE
Add the Database page in spanish

### LINKED ISSUE #4351: [Docs] Create/Update the Database page in spanish, that goes in the CONCEPT section in the spanish docs site
#### Current State
The spanish docs site doesn't have the Database page translation to spanish 
English page to translate: https://docs.meshery.io/concepts/architecture/database
#### Desired State
The spanish docs site has the Database page translated to spanish in the CONCEPT section 
---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by chal-gro**
Signed-off-by: Christian Alexis Castro Guerrero <christian.alexis.gro@gmail.com>

**Description**

This PR fixes #4351

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 232f37d31c65ceeddce5878cd2dcbc9f963e995a at: https://6161f3f83311c3b2eb340300--meshery-docs-preview.netlify.app

**Comment by chal-gro** [comment]
I made the changes, just that I left Library as a "Biblioteca" and not as a "Librería"

**Comment by l5io** [comment]
🚀 Preview for commit 40f23ebb0f6e032edefd3eefbcce5ca2f8e28837 at: https://616229f1b2b760fb753aae95--meshery-docs-preview.netlify.app

**Comment by ramrodo** [comment]
> I made the changes, just that I left Library as a "Biblioteca" and not as a "Librería"

Sounds good.- Thanks. 👍🏼

**Pull request merged**
