### PR TITLE
Fix overflow on Meshery Docs error page

### LINKED ISSUE #7063: [Docs] Error code title overflow
#### Current Behavior

The title "Error code" overflows from the table on page https://docs.meshery.io/reference/error-codes

#### Expected Behavior

No overflow.

#### Screenshots/Logs

image

#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Google Chrome
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by chinu-anand**
Signed-off-by: Chinu Anand <chinuanand81@gmail.com>

**Notes for Reviewers**

This PR fixes #7063 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit ea83748f7cebbc7aae97f9ee9c2f37b7e1b965e2 at: https://63e9c374cc473a1577202bec--meshery-docs-preview.netlify.app

**Comment by deepakdinesh1123** [comment]
@chinu-anand Could you please add images indicating what the problem was and how your changes fixed it?

**Comment by chinu-anand** [comment]
> @chinu-anand Could you please add images indicating what the problem was and how your changes fixed it?

The images are attached with issue #7063 and I applied the correct CSS to fix that.

**Comment by chinu-anand** [comment]
@Chadha93 Correct me if I am wrong but I think topics related to meshery docs are only discussed on Websites Call on Mondays.

**Comment by leecalcote** [comment]
> @Chadha93 Correct me if I am wrong but I think topics related to meshery docs are only discussed on Websites Call on Mondays.

Not a hard rule, but you're right that this is generally the flow. It varies a bit on size / complexity of changes and on size of weekly agenda.

Changes that @alphaX86 made at one point were the discussion of a number of Meshery Dev meetings. 😁

**Review by leecalcote — APPROVED** [review]

**Pull request merged**
