### PR TITLE
Add share option

### PR DESCRIPTION
**Pull request by MUzairS15**
Signed-off-by: MUzairS15 <muzair.shaikh810@gmail.com>

**Description**

This PR fixes #
1. Adds option to share milestones on Twitter, LinkedIn and Facebook.

**Notes for Reviewers**
1. On Facebook and LinkedIn we cannot add composed post, they have restricted API.
2. Had to do string manipulation/ parsing, as we are not sending details appropriately, everything is stuffed inside `details` attribute (Need to be tackled separately, with OperationCenter Spec)
3. For some events, where we can't distinguish, the entire Message is composed as part of post.
**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
@MUzairS15 placement and coloring 😬 

Screen Shot 2022-08-30 at 2 04 03 PM


@warunicorn19 the other menus... on your to-do list.

**Comment by warunicorn19** [comment]
I'm doing them right now.

**Comment by leecalcote** [comment]
@MUzairS15 The tweet is looking great. Way to put this custom message together. Really neat.

Screen Shot 2022-08-30 at 2 05 34 PM

**Comment by MUzairS15** [comment]
> @MUzairS15 placement and coloring 😬 (this is Safari)
> 
> Screen Shot 2022-08-30 at 2 04 03 PM
> 
> @warunicorn19 the other menus... on your to-do list.

I will see in Figma, how it is supposed to be or @warunicorn19 can you please look into styling🙏

**Comment by warunicorn19** [comment]
Ahh, I was just about to say. How do we want the tabs to be? I'm literally blank as to how to style them 😅.

**Comment by leecalcote** [comment]
@warunicorn19 A slight color offset (like the color used on the background paper of the pages) for the entire background will do.

**Comment by legendarykamal** [comment]
@leecalcote probably something like this ->  #ded7d7 

image

**Comment by leecalcote** [comment]
The color of the page background is #eaeff1

Screen Shot 2022-09-01 at 8 38 37 PM

**Comment by Chadha93** [comment]
@MUzairS15 Conflicts resolved and tested OK 
image

**Comment by warunicorn19** [comment]
I think we can go ahead and merge this now. 
Screenshot 2022-09-11 at 1 48 35 AM

**Comment by Chadha93** [comment]
@leecalcote Good to merge with this one?

**Comment by leecalcote** [comment]
Thanks for asking @Chadha93. I had not seen the last couple updates. Yes, that screenshots look good 👍

**Review by leecalcote — APPROVED** [review]

**Review by Chadha93 — APPROVED** [review]
LGTM

**Pull request merged**
