### PR TITLE
Fix recursive API calls when multiple page changes immediately in configurations

### LINKED ISSUE #7976: [UI] Handle API requests efficiently
#### Current Behavior

The issue pertains to all pages that utilize cards and tables, such as "`filters`," "`applications`," "`designs`," and "`profiles`." When we navigate to another page quickly through pagination, there is a bug that occurs due to the timing of the response from the previous page.

Currently, when we swiftly move to the next page before the response from the previous page arrives, it leads to an undesired behavior. The bug arises because the system is not able to handle this rapid navigation properly, resulting in incorrect or unexpected results.

https://github.com/meshery/meshery/assets/90546692/5e8eae2b-b163-4d22-8015-48954f2356ff

#### Desired Behavior

It should handle requests efficiently.

#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by HarshDobariya79**
**Notes for Reviewers**

This PR fixes #7976 

**Changes**
- Fix the bug which was causing **recursive** API calls and crashing the page.

**Demo**

[API-recursion-fix-demo.webm](https://github.com/meshery/meshery/assets/29772969/4f52189c-d033-47c8-9b6a-6c216e226255)

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by HarshDobariya79** [comment]
> Looks good, thanks @HarshDobariya79. Please fix the lint issues.

The linting

> Looks good, thanks @HarshDobariya79. Please fix the lint issues.

The linting issues were introduced in #8013, but thanks for pointing it out I've fixed it.

**Comment by Chadha93** [comment]
@HarshDobariya79  Let's discuss this on the Meshery Dev call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#) if you would. :)

**Review by sudhanshutech — APPROVED** [review]

**Comment by sudhanshutech** [comment]
@Abhishek-kumar09

**Review by leecalcote — APPROVED** [review]

**Comment by leecalcote** [comment]
Thanks for getting this taken care of, @HarshDobariya79

**Pull request merged**
