### PR TITLE
[CI] Update and add tests, glob expressions for backend files in CodeCov

### LINKED ISSUE #5239: [CI] Update Codecov CI to evaluate coverage for Meshery Server
#### Current Behavior
Currently CodeCov tool evaluates coverage only for mesheryctl and some internal files. Not all files are made to evaluate

#### Desired Behavior
Update CI to evaluate the coverage for Meshery Server and other components

#### Acceptance Tests
None (Only path needs some updates)

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by alphaX86**
Signed-off-by: Aadhitya A <aadhitya864@gmail.com>

**Description**

This PR fixes #5239 

**Notes for Reviewers**
Needs some tests to see if it works...

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by Abhijay007 — DISMISSED** [review]
LGTM !!

**Comment by alphaX86** [comment]
Is there any way to reflect changes on CodeCov within branch itself? 🤔 coz I don't think it's showing in the report generated now...

**Comment by piyushsingariya** [comment]
I see atleast one written test is required to show these folders in codecov. Cool, I get it. I think it's your queue to start adding tests to these folders.

Write one test in each of these folders(where you can) for the simplest function written in these folders(if you don't find any small functions in any of these that's okay). So that they start to show-up in codecov UI.
image

**Comment by alphaX86** [comment]
> I see atleast one written test is required to show these folders in codecov. Cool, I get it. I think it's your queue to start adding tests to these folders.
> 
> Write one test in each of these folders(where you can) for the simplest function written in these folders(if you don't find any small functions in any of these that's okay). So that they start to show-up in codecov UI.

OK boss 👍
image

**Comment by alphaX86** [comment]
Sample test worked! Proceeding to add tests in folders now

**Comment by MarioArriaga92** [comment]
Not that familiar with codecov and golang unit tests but there's a failure in golang unit tests right now:
`golangci-lint run --out-format=github-actions] in [] ...
  level=error msg="Running error: context loading failed: no go files to analyze"`

**Review by MarioArriaga92 — CHANGES_REQUESTED** [review]
Let's fix golang lint failure as simple tests are being added

**Comment by alphaX86** [comment]
The golang lint failure is often seen actually. It's also one of my tasks to resolve this issue. I'll fix it though 👍

**Comment by alphaX86** [comment]
@piyushsingariya it's almost ready, could you check if it's OK? Some tests are made dummy to activate the coverage

**Review by leecalcote — APPROVED** [review]
The golanglint-ci issue is a separate concern.

**Comment by alphaX86** [comment]
Understood, it'll be solved in a separate PR 👍

**Pull request merged**
