### PR TITLE
[CI/mesheryctl] Add unit tests for mesheryctl

### PR DESCRIPTION
**Pull request by alphaX86**
Signed-off-by: Aadhitya A <aadhitya864@gmail.com>

**Description**
This PR adds some unit tests to mesheryctl files

This PR fixes #

**Notes for Reviewers**
WIP...

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
@gr455, will you have a look over this PR?

**Comment by gr455** [comment]
> @gr455, will you have a look over this PR?



> @gr455, will you have a look over this PR?

Sure

**Review by leecalcote — APPROVED** [review]
LGTM

**Comment by leecalcote** [comment]
Still `pr/draft'?

**Comment by alphaX86** [comment]
I didn't add more tests yet, that's why pr/draft

--
Regards,
Aadhitya A

**Comment by leecalcote** [comment]
Oh, ok. 👌

**Comment by piyushsingariya** [comment]
Wait. Don't merge it. Will merge it after having a one-on-one with @alphaX86

**Comment by alphaX86** [comment]
This pr is not ready to merge, still I need to add tests for some files

**Comment by alphaX86** [comment]
Branch lost in Ubuntu OS. Will open a new one soon, replicating this!

**Pull request closed without merging**
