### PR TITLE
Replace hardcoded URL with Endpoints from context

### PR DESCRIPTION
**Pull request by anirudhjain75**
Signed-off-by: Anirudh Jain <anirudh.jain@outlook.com>

### CODE REVIEW

**Comment by leecalcote** [comment]
While you're updating the cfg package, @anirudhjain75, perhaps, change it's name to "config"...

**Comment by anirudhjain75** [comment]
Sure @leecalcote

**Comment by anirudhjain75** [comment]
Hey @leecalcote , Version command is now context aware

**Review by leecalcote — DISMISSED** [review]
LGTM

**Comment by leecalcote** [comment]
A couple conflicts to knock out...

**Review by leecalcote — APPROVED** [review]

**Pull request merged**
