### PR TITLE
[Refactor] Updated backend

### PR DESCRIPTION
**Pull request by YashKamboj**
Signed-off-by: YashKamboj <yashkamboj29@gmail.com>

**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by YashKamboj** [comment]
@leecalcote @Chadha93  We can merge this !!

**Comment by Abhishek-kumar09** [comment]
@YashKamboj Would you mind adding a PR description telling specifically what are the backend changes here, 2312 file without context is hard to digest 😄

**Comment by YashKamboj** [comment]
@Abhishek-kumar09 i just copy pasted backend folders from the master branch 😅😅

**Review by Abhishek-kumar09 — APPROVED** [review]
Okay, CITY

**Pull request merged**
