### PR TITLE
[CI]Update Workflow to latest versions #11607

### LINKED ISSUE #11607: [CI]Update Workflow to latest versions
### Changes

Update actions/checkout to v4
Update actions/setup-go to v5
and few more..

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
- Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)
- 🧪 [Meshery Test Plan Spreadsheet](https://docs.google.com/spreadsheets/d/13Ir4gfaKoAX9r8qYjAFFl_U9ntke4X5ndREY1T7bnVs/edit#gid=0)

### PR DESCRIPTION
**Pull request by ayushsawant464**
**Notes for Reviewers**

This PR fixes #11607 
[CI]Update Workflow to latest versions

### CODE REVIEW

**Review by singh1203 — COMMENTED** [review]
In my opinion, shouldn't we come in batches? 
@Jougan-0

**Comment by leecalcote** [comment]
A challenge of reviewing this change is the fact that most of the core build checks aren't triggered to fire (or didn't fire) and so it's not clear if we're all green or not.

**Comment by Ashparshp** [comment]
@ayushsawant464 let's discuss this PR during the Meshery dev meeting call, if you would. Please add it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit?usp=drivesdk).

**Comment by ayushsawant464** [comment]
ok

**Comment by jerensl** [comment]
Let's use https://app.stepsecurity.io for this one, using versioning like @v4 is not security best practice, it's better to use the sha1 commit hash as versioning for GitHub action.

step security bot will handle this automatically

**Comment by ayushsawant464** [comment]
ok will create a new pull request with said changes.

**Comment by ayushsawant464** [comment]
@jerensl created a new pr -https://github.com/meshery/meshery/pull/11690 !!

**Pull request closed without merging**
