### PR TITLE
Adds Pattern Enhancement 

### LINKED ISSUE #3307: [UI] Patterns: Action Enhancements
#### Current Behavior
Users need the ability to deploy patterns from the Patterns table.

#### Desired Behavior
Users should see a Deploy button in each row of the table.

#### Implementation

In the table:
1. Add "Deploy" button (use Play icon or Lighting Bolt icon) to invoke the Pattern "deploy" endpoint.
1. Change "..." elipse icon to Pencil icon
1. Update name of column from "Details" to "Actions"

In the patternfile modal:
1. Change icon for Update Patterns action to a Save (disk) icon

#### Acceptance Tests

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

### PR DESCRIPTION
**Pull request by Chadha93**
**Description**
Added the suggested action Enhancements. 

This PR fixes #3307 

**Notes for Reviewers**
Deploy Endpoint is not invoked yet.

**[Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Chadha93** [comment]
@leecalcote Why this pr is showing changes of another filter pr, I have made this pr from a New branch?

**Review by leecalcote — CHANGES_REQUESTED** [review]
@Chadha93 will you investigate these?

Screen Shot 2021-07-01 at 10 04 10 AM

**Comment by Chadha93** [comment]
I will create a new pr for this, this branch is having conflicts (taking changes from another branch)

**Comment by leecalcote** [comment]
Sounds good.

**Pull request closed without merging**
