### PR TITLE
Remove the word "Successfully" if it is unnecessary 

### PR DESCRIPTION
**Pull request by weilirs**
**Notes for Reviewers**
At the Wednesday Development Meeting, Lee asked me to remove the word "Successfully" from all files if it is unnecessary. This PR is for that purpose.
- This PR fixes #

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by weilirs** [comment]
I removed some of them and I would like to hear some feedback before I going too deep

**Review by leecalcote — CHANGES_REQUESTED** [review]
Thanks. Let's restrict this removal of "successfully" to only Meshery events, error code messages, notifications sent to the user and exclude updates to contributing.md, docs, Meshery Designs and so forth.

**Comment by l5io** [comment]
🚀 Preview for commit d048f3710209317f2f923c2a07082eae761a671b at: https://675e3101efc0aed005e8cffc--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 046b6ed2e2f113764c0a9c7ccee40796e6590c29 at: https://675e34cfd13a7ed34b043a96--meshery-docs-preview.netlify.app

**Comment by weilirs** [comment]
open a new one with sign-off

**Pull request closed without merging**
