### PR TITLE
implemented eslint checks 

### LINKED ISSUE #5953: [UI/Eslint] Enable important eslint checks
#### Current Behavior

The eslint is a great complement with JS to catch the errors in front during parse time. But some important checks being on `off` state introduces bugs in the code and failures that can be otherwise rectified in advance. Such checks are jsx keys and "no-dupe-keys". 

#### Desired Behavior
```
 "react/jsx-key" : "off",
 "no-dupe-keys" : "off",
```

WARN on "react/jsx-key"
Error on "no-dupe-keys"

#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by kamalbuilds**
Signed-off-by: Kamal <geniusamansingh@gmail.com>

This PR fixes #5953

**Description**
Enabled important eslint checks

WARN on "react/jsx-key"
Error on "no-dupe-keys"

**Notes for Reviewers**
The previous PR got auto closed so reopening from the new fork.

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by adithyaakrishna** [comment]
@legendarykamal The tests are failing, also could you please remove this one line from, https://github.com/meshery/meshery/pull/5997/files#file-provider-ui-components-providercomponent-js-L124?

CC @MarioArriaga92 Would love to know your opinion on the above change :)

**Comment by legendarykamal** [comment]
Yes I know @adithyaakrishna 
Pls refer https://github.com/meshery/meshery/pull/5974

**Review by Abhishek-kumar09 — APPROVED** [review]
LGTM

**Comment by Abhishek-kumar09** [comment]
> @legendarykamal The tests are failing, also could you please remove this one line from, https://github.com/meshery/meshery/pull/5997/files#file-provider-ui-components-providercomponent-js-L124?
CC @MarioArriaga92 Would love to know your opinion on the above change :)

@legendarykamal would you create a new PR making the change?

**Pull request merged**
