### PR TITLE
fix: broken link in adapters 

### LINKED ISSUE #4144: [Docs]Broken Link
#### Current State
The `check our progress` link on the adapters page is broken. [example](https://docs.meshery.io/service-meshes/adapters/tanzu-sm#lifecycle-management)
#### Desired State
Fix the broken link.
---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by Shatakshi0805**
Signed-off-by: Shatakshi <shatakshi.gupta85@gmail.com>

**Description**

This PR fixes #4144

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Shatakshi0805** [comment]
Don't know how Gemfile got deleted. fixing it now.

**Comment by l5io** [comment]
🚀 Preview for commit b6aa879058c401c94ebdedd7fab246329c220393 at: https://613eda717161e97ff4fbfaeb--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 6b209d5bfb0a186233da4355dc21222bf98545ea at: https://613edb38fe74625d67eb94ed--meshery-docs-preview.netlify.app

**Comment by Shatakshi0805** [comment]
@warunicorn19 should I squash the commits?

**Comment by warunicorn19** [comment]
3 commits seem fine, no need to squash 😄.

**Review by warunicorn19 — APPROVED** [review]
LGTM 🎉, Thanks @Shatakshi0805

**Review by leecalcote — APPROVED** [review]
Looks great. 👍

**Comment by leecalcote** [comment]
yay, @Shatakshi0805! 🎈

**Pull request merged**
