### PR TITLE
espanol button link fixed and extra code deleted  w/signoff

### LINKED ISSUE #4652: [Docs] "Espanol" link on the docs home page not working.
#### Current State
after clicking on **"Espanol"** which is on the top right corner, we cant go to the Spanish language page of our docs.
 

#### Desired State
We should be able to go on the Spanish language page after clicking on it.

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by varunsaral**
Signed-off-by: varun saral <varunsaral47@gmail.com>

**Description**
The navbar espanol documentation link seem broken 
This PR fixes #4652 
The navbar espanol link and removed extra code
**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ . ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 69bee75bbe589ad3832008fdd3f3c9c3ae4f4e5e at: https://619a8e7f89c930589cfa660e--meshery-docs-preview.netlify.app

**Review by warunicorn19 — APPROVED** [review]
Looking good🎉, Thank you @varunsaral for this. Just one thing could you please link the issue to the PR (just put the PR no. where it's written `This PR fixes #<no.>`) then we'd be good to merge

**Comment by varunsaral** [comment]
> Looking good🎉, Thank you @varunsaral for this. Just one thing could you please link the issue to the PR (just put the PR no. where it's written `This PR fixes #<no.>`) then we'd be good to merge

Sorry and thank you @warunicorn19 for this silly mistake , I tried every step carefully but it just slipped through my eyes .

**Comment by warunicorn19** [comment]
@varunsaral it's no problem at all.😄

**Pull request merged**
