### PR TITLE
Minor changes on NPM packages

### PR DESCRIPTION
**Pull request by acald-creator**
Upgraded 
* `react-select`
* `react-countdown-clock`
* `isomorphic-unfetch`

Installed `MUI v5` and `graphql-ws` as placeholder.
* Material V4 has stopped received updates as of September 2021
* `subscription-transport-ws` has deprecated and moved to `graphql-ws`
* Installed these as a placeholder
* GraphQL may require a design review on the setup. There are some `websocket` dependencies issues.

Signed-off-by: Antonette Caldwell <pullmana8@gmail.com>

**Notes for Reviewers**

This PR fixes #

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
@Harshit-Dandriyal will you test and confirm functionality given the description that @acald-creator has included?

**Comment by leecalcote** [comment]
Using the Local Provider and visiting /user/preferences, an overly large performance icon is displayed.

Screenshot 2023-01-15 at 5 37 05 PM

**Comment by Abhishek-kumar09** [comment]
> Using the Local Provider and visiting /user/preferences, an overly large performance icon is displayed.
> 
> Screenshot 2023-01-15 at 5 37 05 PM

https://github.com/meshery/meshery/pull/6690 solves this

**Review by Abhishek-kumar09 — APPROVED** [review]
Given this is "Minor" change and complete migration is to be carried out afterwards, I approve this PR.

**Pull request merged**
