### PR TITLE
Actions Enhancement for Meshery Patterns

### LINKED ISSUE #3307: [UI] Patterns: Action Enhancements
#### Current Behavior
Users need the ability to deploy patterns from the Patterns table.

#### Desired Behavior
Users should see a Deploy button in each row of the table.

#### Implementation

In the table:
1. Add "Deploy" button (use Play icon or Lighting Bolt icon) to invoke the Pattern "deploy" endpoint.
1. Change "..." elipse icon to Pencil icon
1. Update name of column from "Details" to "Actions"

In the patternfile modal:
1. Change icon for Update Patterns action to a Save (disk) icon

#### Acceptance Tests

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

### PR DESCRIPTION
**Pull request by Chadha93**
Signed-off-by: Chadha93 <gauravchadha1676@gmail.com>

**Description**
Adds suggested enhancement for Meshery Patterns

This PR fixes #3307 

**Notes for Reviewers**
Endpoints to trigger the deploy button are not yet triggered.
image

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Chadha93** [comment]
@leecalcote here's a clean coded PR : )

**Comment by utkarsh-pro** [comment]
@Chadha93 `/api/experimental/pattern/deploy` `POST` request to this endpoint should work.

**Comment by leecalcote** [comment]
Thank you, @Chadha93. Holding on merging until the deploy button is activated.

**Comment by Chadha93** [comment]
@leecalcote @utkarsh-pro  The deploy endpoints are working fine now.  This pr can be merged :)) Thanks @sudo-NithishKarthik for working along.
Screenshot 2021-07-05 110747

**Review by utkarsh-pro — APPROVED** [review]
LGTM

**Comment by leecalcote** [comment]
Good work! 😄

**Pull request merged**
