### PR TITLE
Sign-off-by : Karen Efereyan kimsyefe@gmail.com ADD smi conformance c…

### PR DESCRIPTION
**Pull request by ghost**
…apability section in docs

**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by PluckyPrecious** [comment]
Hi @KarenEfereyan can you please fill the PR form appropriately and sign DCO? Click on the DCO error details for steps to get it sorted. 👍🏽

**Comment by KarenEfereyan** [comment]
Where are the DCO error details

**Comment by PluckyPrecious** [comment]
https://github.com/layer5io/meshery/pull/1399/checks?check_run_id=988861048

**Comment by KarenEfereyan** [comment]
Omg i used the wrong email.. Im really sorry

**Comment by KarenEfereyan** [comment]
Omg i used the wrong email.. I put in the email i use most frequently but not the one for github..im.sorry i will ammend that.

**Comment by PluckyPrecious** [comment]
It's fine 😄

**Comment by KarenEfereyan** [comment]
After service we get back to it. I want to be done with today.

**Comment by KarenEfereyan** [comment]
@PluckyPrecious I have pushed my branch's commit. Can you please look into it. What more do I need to do?

**Comment by PluckyPrecious** [comment]
> Hi @KarenEfereyan you didn’t push any commit as the folder is empty, could you please fill the PR form appropriately and sign DCO? Click on the DCO error details for steps to get it sorted. 👍🏽

@Karen all these haven’t been done including the commit.🙂

**Comment by KarenEfereyan** [comment]
https://github.com/layer5io/meshery/pull/1399

Here is my latest PR. I have made all the necessary changes. My file is now reflecting, I get a message saying I am able to merge and I await your corrections. Thanks for all your help @PluckyPrecious and @NupurThakur27

**Comment by KarenEfereyan** [comment]
Seems DCO is stilll not working. What do I need to do

**Comment by PluckyPrecious** [comment]
> https://github.com/layer5io/meshery/pull/1399/checks?check_run_id=988861048

Please follow this instruction to fix it.

**Comment by KarenEfereyan** [comment]
Im trying😪😪😪😪

**Comment by KarenEfereyan** [comment]
SMI
@NupurThakur27 has been so helpful but DCO is still not checked. And thedevkaren@gmail.com is the email associated with my github account. And I believe that is the one I am to use.

**Comment by Ruth-ikegah** [comment]
@KarenEfereyan you can send a message, let's see what's going on

**Pull request closed without merging**
