### PR TITLE
[Docs] Add 'Contributing to Meshery Policies' Guide #11324

### LINKED ISSUE #11324: [Docs] "Contributing to Meshery Policies"
### Current State

Meshery integrates OPA and Rego in a couple different ways, one of which is as an evaluation engine for Meshery Relationships.

### Desired State

Akin to other contributing guides, a set of instructions as to how to contribute to Meshery Policies is needed.

### Draft of the section on "Testing Rego Policies for Relationships"

> 1. **Code:** Make changes to Rego files in their respective Meshery model folder.
> 1. **Build:** Build Meshery Server, which loads all available policies.
> 1. **Test:** 
> 1.1. Verify that policy loaded successfully by opening Meshery UI and visiting `Settings`—>`Registry`
> 1.1. Alternatively, verify by reviewing registration logs found under `~/.meshery/logs/*.log`
> --- Optionally ---
> 1. **Verify Visually:** by opening the MeshMap extension.
> 1.1. Drag and drop the implicated components onto the canvas. 
> 1.1. Click on each component and visit the “Relationships” tab menu. Verify presence of “Available Relationship”.
> 1.1. Attempt to visually form the relationship by clicking and dragging either the component or edges between components.
> 1.1. If a component is to be mutated by relationship formation, attest specific changes.

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by Vaibhav701161**
**Fixes #11324**

This PR adds a comprehensive guide on contributing to Meshery policies, addressing the need for clear instructions on modifying, creating, and testing Rego policies within the Meshery codebase.

### Changes Included:
- Created a new file, `CONTRIBUTING-POLICIES.md`, with detailed instructions on:
  - Understanding Meshery policies and their purpose.
  - Locating and modifying existing Rego policy files.
  - Creating new Rego policy files following Meshery’s conventions.
  - Testing Rego policies using Meshery’s UI and MeshMap extension.
  - Best practices for writing and maintaining policies.

- Updated the main `CONTRIBUTING.md` file to reference the new guide, ensuring discoverability for contributors interested in policy management.

### Additional Information:
- The new guide provides a step-by-step approach to policy contributions, ensuring contributors understand the impact of their changes on existing systems and workflows.

- [x] I have signed my commits.

Reviewers, please verify the changes to ensure the content aligns with the desired state.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit bcdbc3ef512f9d6e6deb51a0eb7809912602f7e9 at: https://66e45d6dc63a382353804f81--meshery-docs-preview.netlify.app

**Review by Ashparshp — COMMENTED** [review]
@Vaibhav701161, empty file?

**Comment by Vaibhav701161** [comment]
@Ashparshp let me see how empty file got pushed!
will update you soon!

**Comment by vishalvivekm** [comment]
@Vaibhav701161 Will you please push your changes, if so we can cover this item on Meshery's development call today.
Meeting minutes: https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit?pli=1#

**Review by MUzairS15 — COMMENTED** [review]
@Vaibhav701161 Is this by mistake? Please close it.

**Comment by Vaibhav701161** [comment]
@vishalvivekm Apologies for missing the meeting and not pushing the updates. I had an unexpected personal situation that required my immediate attention, and I couldn’t make it in time. I’ll make sure to catch up on everything and have the updates pushed as soon as possible

**Pull request closed without merging**
