### PR TITLE
Fixed Typo

### PR DESCRIPTION
**Pull request by UtkarshMishra12**
**Description**
Signed-off-by: UtkarshMishra12 [nasautkarsh@gmail.com](mailto:nasautkarsh@gmail.com)

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**

- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — DISMISSED** [review]
LGTM

**Comment by l5io** [comment]
🚀 Preview for commit 99def192a2071b7c788d15279d54ca073c7fb610 at: https://6334b5d3aeff0f0292a865b8--meshery-docs-preview.netlify.app

**Comment by leecalcote** [comment]
@UtkarshMishra12 will you take a moment sign-off on your commit? Instructions here - https://github.com/meshery/meshery/pull/6281/checks?check_run_id=8605207054 and in the PR description.

**Comment by l5io** [comment]
🚀 Preview for commit 574abd8e381ac0d3e09a4de8db5dbebf1841bed0 at: https://6334bb57ca6bf406c7f60dee--meshery-docs-preview.netlify.app

**Comment by leecalcote** [comment]
Thanks, @UtkarshMishra12. Yay! 🎈

**Pull request merged**
