### PR TITLE
[Docs] reverting lockfile update

### PR DESCRIPTION
**Pull request by thisiskaransgit**
**Notes for Reviewers**

This PR reverts the unwanted changes pushed in the PR #8235

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 03898bcc41888344c9bbbe625f17a316e36ade35 at: https://64b96016e32ba809ad5c5273--meshery-docs-preview.netlify.app

**Comment by Chadha93** [comment]
Thanks @thisiskaransgit. Tests running...

**Comment by Chadha93** [comment]
> Thanks @thisiskaransgit. Tests running...

Oops failing....

**Comment by thisiskaransgit** [comment]
@Chadha93, debugging the issue...

**Review by leecalcote — APPROVED** [review]

**Pull request merged**
