### PR TITLE
RJSF Validation

### PR DESCRIPTION
**Pull request by harkiratsm**
Signed-off-by: harkiratsm <multaniharry714@gmail.com>

**Description**

This PR fixes #

**Notes for Reviewers**

[rename.webm](https://user-images.githubusercontent.com/71957674/187063441-05b8bc2d-a71b-47f9-9173-4896ad1afa9a.webm)

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
Task linked: [CU-2rc1paf RJSF Validation](https://app.clickup.com/t/2rc1paf)

**Review by YashKamboj — APPROVED** [review]
LGTM!! Good work

**Review by leecalcote — CHANGES_REQUESTED** [review]
Why are you showing the user a field three times as wide as the input size allows?

**Comment by harkiratsm** [comment]
@leecalcote the size of the input field is fixed in this [pr](https://github.com/meshery/meshery/pull/6101)

**Comment by leecalcote** [comment]
> @leecalcote the size of the input field is fixed in this [pr](https://github.com/meshery/meshery/pull/6101)

Oh, I see. Ok, that's good. ✔️

**Review by leecalcote — APPROVED** [review]

**Pull request merged**
