### PR TITLE
Upgrade Meshkit and Operator

### PR DESCRIPTION
**Pull request by Revolyssup**
Signed-off-by: Ashish Tiwari <ashishjaitiwari15112000@gmail.com>

**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Merge conflict.

**Comment by leecalcote** [comment]
Add `MeshSync` label, please.

**Comment by leecalcote** [comment]
Is this PR still needed?

**Comment by Revolyssup** [comment]
@leecalcote  the subsequent change in meshmap has been merged. Lets merge this one as well.

**Comment by Revolyssup** [comment]
@leecalcote  This most probably(90%) will solve the incluster operator installation/uninstallation bug caused by helm

**Pull request merged**
