### PR TITLE
Update BillboardJS from v1 to v2

### PR DESCRIPTION
**Pull request by dhruv0000**
**Description**

This PR upgrades billboardJS 

**Note for Reviewer**
1. Tested for `perf test results`
2. Tested for `Grafana Charts`

**[Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Are perf tests using chartjs?

**Comment by dhruv0000** [comment]
no. We are using `billboardJS` v2

**Comment by dhruv0000** [comment]
Tested for Grafana Charts and Perf Tests. We are good to merge @leecalcote .
perf_charts
grafana

**Comment by leecalcote** [comment]
This is a very pleasant surprise. 😄

**Review by leecalcote — APPROVED** [review]
Thank you, @dhruv0000 💪

**Review by leecalcote — APPROVED** [review]

**Pull request merged**
