### PR TITLE
Added MAINTAINERS.md

### PR DESCRIPTION
**Pull request by ankushbhardwaj408**
**Notes for Reviewers**

This PR fixes #

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit b36049ef9a4c511bbe64273c2438822014d20860 at: https://65544a2f814fb256787a4e92--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 577733c905ac5afe9373f227bbf73a41a3ad75c7 at: https://65544b6b1b99515167a13168--meshery-docs-preview.netlify.app

**Review by leecalcote — CHANGES_REQUESTED** [review]
Please make these changes in the root-level maintainers file

**Comment by ankushbhardwaj408** [comment]
> Please make these changes in the root-level maintainers file

Done.

**Comment by vishalvivekm** [comment]
@ankushbhardwaj408 Let's discuss this on Meshery Dev call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#) if you would. :)

**Review by leecalcote — APPROVED** [review]

**Pull request merged**
