### PR TITLE
[UI] JSS: Dependency update

### PR DESCRIPTION
**Pull request by leecalcote**
Signed-off-by: leecalcote <leecalcote@gmail.com>

**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Review by Abhishek-kumar09 — COMMENTED** [review]
the package locks are not human maintained and they don't change someone else's npm builds, and they are prone to modification on npm install.

**Comment by leecalcote** [comment]
> the package locks are not human maintained and they don't change someone else's npm builds, and they are prone to modification on npm install, which is a part of make run

@Abhishek-kumar09, will you rephrase? I'm not sure that I understand the point that you're making. Are you saying that only dependabot should be updating dependencies? Meshery UI is not using the latest JSS, and so this PR is to upgrade to the latest as part of the routine of keeping pace with dependencies. Humans can do this, too, and before Dependabot was acquired by GitHub a couple years ago, humans had to do this manually.

**Comment by Abhishek-kumar09** [comment]
Yeah, the `package-lock` are not modified by us. They are modified automatically based on the package.json file.

**Comment by Abhishek-kumar09** [comment]
This change is good, if we wan't to enforce the latest JSS, but it's not a guarantee.

**Review by Abhishek-kumar09 — APPROVED** [review]

**Pull request merged**
