### PR TITLE
Corrected Spelling Mistakes

### PR DESCRIPTION
**Pull request by ENUMERA8OR**
Corrected Spelling Mistakes across multiple documents.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 74af0a00d77e6274dca803a05cd3f49f633c80e7 at: https://668f7c38bb40daedad730fc8--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 260a2b6e20521e7bf2233effb5e9d850867ab93e at: https://668f82d0cf6263feeedc1b20--meshery-docs-preview.netlify.app

**Review by Yashsharma1911 — APPROVED** [review]
Thanks for making sure spellings are correct

**Review by Yashsharma1911 — COMMENTED** [review]
Although v0.4 doc is old doc, @vishalvivekm do we want to merge this PR

**Comment by leecalcote** [comment]
> Although v0.4 doc is old doc, @vishalvivekm do we want to merge this PR

In general, we don't want to make changes to the snapshotted, older versions. A spelling correction is acceptable, though, and benign in terms of other potential breakages.

**Review by leecalcote — APPROVED** [review]

**Pull request merged**
