### PR TITLE
Bug/ayush khandelwal 007/3306

### LINKED ISSUE #3306: [UI] Performance Profiles: Updates to Cards
#### Current Behavior
Performance Profile cards have an intriguing user experience, but also has a few areas of need of improvement.

#### Implementation
1. Change Delete action behavior: present user a confirmation modal before deleting the performance profile
1. Add all profile details to the back of the card: service mesh type, QPS and Concurrent requests and custom headers, if present.
1. Move Delete and Edit buttons to back of the card.
1. Remove the "Details" button from the front of the card.
1. Move "view test results" to the front. Rename to "View Results". 
1. Activate card on hover. Provide another indication to the user that they can click on the card.
    1. Option: tilt card ever so slightly
    1. Option: lightly tint the background of the card

#### Acceptance Tests

- [x] 1. Perf profiles require user confirmation prior to being deleted.
- [ ] 2. Users can see all details of a performance profile in a read-only fashion on the back of the profile card, including custom headers if present.
- [ ] 3. Users can invoke administrative operations from the back of the card, not the front.
- [ ] 4. Users can click "View Results" to expand the card, showing test result details in tabular form.
- [ ] 5. User is provided indication that cards are clickable both by changing the pointer to "hand" and one other _subtle_ visual indicator.

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

### PR DESCRIPTION
**Pull request by Ayush-Khandelwal-007**
**Description**

This PR fixes #3306 

**Notes for Reviewers**
Still there are 2 points where I need views form others:
1. Is hover effect looking okay or should it be changed.(I tried the slightly rotated card effect but it don't looks good)
2. On having a longer card in a row, the other card still remains of the same size. Should we have it like that or stretch according to the neighbouring card size?
(Any other ideas and thoughts are welcomed.)

https://user-images.githubusercontent.com/59086855/124360232-49dd6680-dc46-11eb-8763-5d32ed9216bc.mov

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by sudo-NithishKarthik** [comment]
Ya, the hover effect looks fine for now. For the longer card issue, we can increase the z-index of the card when it is opened(elongated).

**Comment by Ayush-Khandelwal-007** [comment]
Problem with long card is not about the height rather the placement of the content.
Presently all the content will stick at the top, and if its spread all over the card, it leaves too much blank space.

**Comment by sudo-NithishKarthik** [comment]
i see 🤔 
What i was thinking was, if we make that card pop out(like a modal) when its clicked, then, the rest of the cards placement won't  be disturbed. And for the placement of content inside the card, it shouldn't matter since now the card will be popped out right.
What do you think ?

**Comment by Ayush-Khandelwal-007** [comment]
@leecalcote whats your review on this?

**Comment by leecalcote** [comment]
Dear sir: 

Thank you for this screen recording. I can't quite be sure, but it looks like there's a tinge of a color being used here that does not belong in our palette. Kindly navigate to your operating system's color picker, highlight the entire range of purple colors, then press the DELETE key. 

Sincerely,
Police Officer Hue

**Comment by Nikhil-Ladha** [comment]
I second @sudo-NithishKarthik 's suggestion. Using a modal here will benefit us.
Also, when we click the `edit` button on the card that opens up a Modal too, right?

**Comment by leecalcote** [comment]
> I second @sudo-NithishKarthik 's suggestion. Using a modal here will benefit us.
> Also, when we click the `edit` button on the card that opens up a Modal too, right?

There is a recording on one of the recent Meshery dev meetings that explains the requested changes in detail. 

It’s not clear the the on hover action is suitable. It’s too much movement. This might need to be removed for now, so the the rest can move forward.

**Comment by Ayush-Khandelwal-007** [comment]
Ohkay. ill remove the on hover effect.

**Comment by Ayush-Khandelwal-007** [comment]
> Dear sir:
> 
> Thank you for this screen recording. I can't quite be sure, but it looks like there's a tinge of a color being used here that does not belong in our palette. Kindly navigate to your operating system's color picker, highlight the entire range of purple colors, then press the DELETE key.
> 
> Sincerely,
> Police Officer Hue

😶I didn't changed anything in the delete or edit button icons. Still ill look into it and change the colour.

**Pull request closed without merging**
