### PR TITLE
Add missing resources (broker && meshsync CRs, kube-rbac container) in helm charts

### LINKED ISSUE #4202: Broker and Meshsync pods, along with kube-rbac-proxy container are missing while installing with helm chart
#### Current Behavior

The `Broker` and `Meshsync` pods are missing after meshery is deployed using the [helm chart](https://github.com/meshery/meshery/tree/master/install/kubernetes/helm/meshery)

The `kube-rbac-proxy` container is also missing in the `meshery-operator` pod compared to the installation result that `mesheryctl` gives 
#### Expected Behavior

We should provide a way to manually create CR instances for `Broker` and `Meshsync` after the CRDs are installed

We should also add the `kube-rbac-proxy` container to the `meshery-operator` pod so that the meshery installation process with helm chart is consistent with `mesheryctl`

#### Screenshots/Logs

With helm chart installation:
```
helm install test install/kubernetes/helm/meshery -n meshery --kubeconfig=$KUBECONFIG
NAME: test
LAST DEPLOYED: Wed Sep 15 15:07:05 2021
NAMESPACE: meshery
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
1. Get the application URL by running these commands:
     NOTE: It may take a few minutes for the LoadBalancer IP to be available.
           You can watch the status of by running 'kubectl get --namespace meshery svc -w test-meshery'
  export SERVICE_IP=$(kubectl get svc --namespace meshery test-meshery --template "{{ range (index .status.loadBalancer.ingress 0) }}{{.}}{{ end }}")
  echo http://$SERVICE_IP:9081/provider
2. All the Notes.txt of Meshery, Mesheryistio and Mesherylinkerd need to add the content here. This can be achieved by sub PR.

kubectl get pods -n meshery --kubeconfig=$KUBECONFIG
NAME                                    READY   STATUS    RESTARTS   AGE
meshery-677df7b644-kjg68                1/1     Running   0          76s
meshery-consul-5769bf7c9c-vqk6j         1/1     Running   0          77s
meshery-cpx-679cb4c5bb-5z8vc            1/1     Running   0          77s
meshery-istio-55bc6b4679-bhh84          1/1     Running   0          77s
meshery-kuma-64476f65fb-vzf98           1/1     Running   0          76s
meshery-linkerd-bb74b8dd9-bs6s9         1/1     Running   0          76s
meshery-nsm-846c648c97-xx8vw            1/1     Running   0          76s
meshery-operator-8899b86cf-cjsb4        1/1     Running   0          76s
meshery-osm-97995cd6f-pjfdd             1/1     Running   0          76s
meshery-traefik-mesh-65bc8888bc-nk5mn   1/1     Running   0          76s

kubectl get brokers.meshery.layer5.io -n meshery
No resources found in meshery namespace.

kubectl get meshsyncs.meshery.layer5.io -n meshery
No resources found in meshery namespace.
```

With `mesheryctl` installation:
```
kubectl get pods -n meshery
NAME                                    READY   STATUS    RESTARTS   AGE
meshery-58f5449cc-tjrmq                 1/1     Running   0          68s
meshery-broker-0                        2/2     Running   0          27s
meshery-consul-6cb6f89f66-wbjk2         1/1     Running   0          62s
meshery-cpx-8497c64cfc-2gh7v            1/1     Running   0          57s
meshery-istio-db9b99584-mhnrz           1/1     Running   0          66s
meshery-kuma-9b5ddbb77-dmnmz            1/1     Running   0          59s
meshery-linkerd-94c765956-swpjn         1/1     Running   0          64s
meshery-meshsync-5bcbc874f8-rzgsg       1/1     Running   2          25s
meshery-nginx-sm-5546bc9b5d-2qcxp       1/1     Running   0          52s
meshery-nsm-c7fd64dc4-nqdrd             1/1     Running   0          61s
meshery-operator-bddf9fd66-8sr68        2/2     Running   0          34s
meshery-osm-5ffd986b64-z674l            1/1     Running   0          56s
meshery-traefik-mesh-5d6695b5fd-zs5rl   1/1     Running   0          54s

kubectl get brokers.meshery.layer5.io -n meshery
NAME             AGE
meshery-broker   8m11s

kubectl get meshsyncs.meshery.layer5.io -n meshery
NAME               AGE
meshery-meshsync   8m46s
```
#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:**  Kubernetes
- **Meshery Server Version:** stable-v
- **K8s version** any
- **Helm version** any

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by panyuenlau**
Signed-off-by: Darren Lau panyuenlau@gmail.com

**Description**

This PR fixes #4202 

**Notes for Reviewers**
First install meshery-oeprator along with all the adapters and the CRDs for Broker and Meshsync:
```
helm install meshery install/kubernetes/helm/meshery -n meshery
NAME: meshery
LAST DEPLOYED: Sun Sep 19 13:53:04 2021
NAMESPACE: meshery
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
1. Get the application URL by running these commands:
     NOTE: It may take a few minutes for the LoadBalancer IP to be available.
           You can watch the status of by running 'kubectl get --namespace meshery svc -w meshery'
  export SERVICE_IP=$(kubectl get svc --namespace meshery meshery --template "{{ range (index .status.loadBalancer.ingress 0) }}{{.}}{{ end }}")
  echo http://$SERVICE_IP:9081/provider
2. All the Notes.txt of Meshery, Mesheryistio and Mesherylinkerd need to add the content here. This can be achieved by sub PR.
```

Then install the CR instances for Broker and Meshsync:
```
helm install broker install/kubernetes/helm/meshery-cr/meshery-broker/ -n meshery
NAME: broker
LAST DEPLOYED: Sun Sep 19 21:25:52 2021
NAMESPACE: meshery
STATUS: deployed
REVISION: 1
TEST SUITE: None

helm install meshsync install/kubernetes/helm/meshery-cr/meshery-meshsync/ -n meshery 
NAME: meshsync
LAST DEPLOYED: Sun Sep 19 21:26:08 2021
NAMESPACE: meshery
STATUS: deployed
REVISION: 1
TEST SUITE: None
```

**Results**
The resources that are deployed using the helm charts match with the `mesheryctl`:
```
kubectl get pods -n meshery
NAME                                    READY   STATUS    RESTARTS   AGE
meshery-5cc4489f77-kvkzf                1/1     Running   0          7h38m
meshery-broker-0                        2/2     Running   0          6m34s
meshery-consul-77d459ccf6-g8lkg         1/1     Running   0          7h38m
meshery-cpx-6b54ff5ffc-46bfj            1/1     Running   0          7h38m
meshery-istio-6c56dd44fb-6hz9q          1/1     Running   0          7h38m
meshery-kuma-7f4dbc98cc-2dnf5           1/1     Running   0          7h38m
meshery-linkerd-5456b548cd-v8xsd        1/1     Running   0          7h38m
meshery-meshsync-86d4959b54-fc2qb       1/1     Running   2          6m22s
meshery-nsm-5bfd567998-7l4lc            1/1     Running   0          7h38m
meshery-operator-7486c6bddc-dcjcb       2/2     Running   0          7h38m
meshery-osm-55d95c7b8b-jfdrg            1/1     Running   0          7h38m
meshery-traefik-mesh-64bb9c58b6-65wd7   1/1     Running   0          7h38m
```
After the Broker and Meshsync pods are created, the meshery-oeprator is able to reconcile them:

> _Note_:
> It seems the `mesheryctl` uses the yamls in [meshery-operator/config](https://github.com/meshery/meshery-operator/tree/master/config) and [meshery/install/deployment_yamls](https://github.com/meshery/meshery/tree/master/install/deployment_yamls/k8s) to do the installation (source code reference: https://github.com/meshery/meshery/blob/master/mesheryctl/pkg/utils/helpers.go#L87-L104), this is probably not the best practice because it would cause inconsistencies and confusions because. 
>
> It'd be better to refactor the `mesheryctl` implementation to use the helm charts to do the installation so that using the `mesheryctl` is just an automated way of using `helm` charts to do the installations.

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Sync'ing branch with `master` in order to upgrade go integration test build workflow to 1.16.

@panyuenlau will you consider executing [these commands](https://github.com/meshery/meshery/pull/4211/checks?check_run_id=3667307106) in order to amend a sign-off to your commit(s)? To configure your commits to always carry a sign-off, there are a couple of suggested approaches [here](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin).

**Comment by l5io** [comment]
🚀 Preview for commit 4fc7a0997657aaee0066f010bf859d5b6890f524 at: https://614a927b2cc739129c198e97--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 25591f22e016929b6ea872fdb10d6cd68293374a at: https://614a972c159f73129c1053e4--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 4fc7a0997657aaee0066f010bf859d5b6890f524 at: https://614a97b941f2e6130914f884--meshery-docs-preview.netlify.app

**Comment by panyuenlau** [comment]
Messed up the commits history while merging the master branch, opened a new PR: https://github.com/meshery/meshery/pull/4227

**Pull request closed without merging**
