### PR TITLE
modify controlplane query

### PR DESCRIPTION
**Pull request by vineethvanga18**
**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
@vineethvanga18 thanks for iterating on this. There are a couple of build checks failures to look into.

**Comment by vineethvanga18** [comment]
@leecalcote  https://github.com/layer5io/meshery/pull/2492 should be merged first.

**Comment by kumarabd** [comment]
@vineethvanga18  can you PR to #2492 instead of master?

**Comment by vineethvanga18** [comment]
I think I don't have permission

**Pull request closed without merging**
