### PR TITLE
[Docs] Updated contributing for UI and Docs

### LINKED ISSUE #5129: [Docs] Extra and confusing step in the contributing
#### Current State
The docs mention an extra and confusing step about contributing to Meshery's UI.
Fo reference : see the [last step](https://docs.meshery.io/project/contributing/contributing-ui)  and I feel like the instruction to use `zshrc` instead of `bashrc` should be given before the very step that uses this. 
for reference [here](https://docs.meshery.io/project/contributing/contributing-docs)

#### Desired State
All of the steps mentioned prior to that cover everything one needs to run Meshery and contribute to it.

---

#### [Contributor Guides](https://docs.meshery.io/project/contributing) and Resources
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by shubhangi013**
**Description**

This PR fixes #5129 

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit a47ba205f43790ef9913932a7b8aa9ce0168f49e at: https://6219fbd4b3f50f94dd0e2b6d--meshery-docs-preview.netlify.app

**Review by leecalcote — CHANGES_REQUESTED** [review]
Thanks, @shubhangi013. Please see the DCO requirement in the Welcome note above.

Instructions to append your sign-off in this specific PR - https://github.com/meshery/meshery/pull/5130/checks?check_run_id=5343772907

**Comment by shubhangi013** [comment]
@leecalcote Done!

**Comment by l5io** [comment]
🚀 Preview for commit bfb3fd552546ac3ea27d75e8eb650ced0c8354c0 at: https://621acb70760a2bdd24b57591--meshery-docs-preview.netlify.app

**Review by warunicorn19 — APPROVED** [review]
LGTM, Thank you @shubhangi013

**Pull request merged**
