### PR TITLE
docs is set to dark mode by default

### LINKED ISSUE #7190: [Docs] Set dark mode as the default Meshery Docs theme
#### Current State
Currently, light mode is the default.

#### Desired State
Dark mode, baby. Dark mode.

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by sudhanshutech**
**Notes for Reviewers**

This PR fixes #7190 
Meshery docs theme is set to dark mode by default.

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit ecd16cea1a5573b9f2fcd2a5229324b21346da4f at: https://63fb5f634154ee754603d24b--meshery-docs-preview.netlify.app

**Comment by Yashsharma1911** [comment]
Hey @sudhanshutech nice work I have checked and getting this flickering on reload maybe because of adding `dark-mode` class to the body dynamically by js can you directly insert `dark-mode` class in body tag rather using js

https://user-images.githubusercontent.com/71271069/221682814-46517c8d-8bdf-46e6-b04a-c06bd2235ec2.mov

**Comment by sudhanshutech** [comment]
> Hey @sudhanshutech nice work I have checked and getting this flickering on reload maybe because of adding `dark-mode` class to the body dynamically by js can you directly insert `dark-mode` class in body tag rather using js

Sure I am on it

**Comment by sudhanshutech** [comment]
@Yashsharma1911 I have made necessary changes please have a look

**Comment by l5io** [comment]
🚀 Preview for commit e783509462821bc79005c5edf4e2fa5488c38aa4 at: https://63fd9e20ccddc85675789313--meshery-docs-preview.netlify.app

**Comment by vishalvivekm** [comment]
> @Yashsharma1911 I have made necessary changes please have a look

Hey @sudhanshutech here's a little feedback. When set in light mode, if you reload or go to any other pages, it abruptly switches to dark mode on its own:

https://user-images.githubusercontent.com/110674407/221822307-e10bef95-af02-45a5-be31-1a1b5ae96ad2.mp4

**Comment by Chadha93** [comment]
@sudhanshutech Let's discuss this on the Meshery Dev call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#) if you would. :)

**Comment by sudhanshutech** [comment]
> @sudhanshutech Let's discuss this on the Meshery Dev call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#) if you would. :)

Hey @Chadha93 , unfortunately I couldn't take today's meet so can i discuss this in next meet becuase I want discuss on my own in the meet.

**Comment by leecalcote** [comment]
@sudhanshutech this couldn't possibly be the ideal approach. Please go back to the drawing board on this. In the meantime, let's free up this issue assignment.

**Pull request closed without merging**
