### PR TITLE
Captain/publishmodal

### PR DESCRIPTION
**Pull request by captain-Akshay**
**Notes for Reviewers**

This PR fixes #

Screenshot 2024-06-24 at 4 34 00 AM

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by captain-Akshay** [comment]
@Yash Sharma I do need help with making the RJSF required for publish action and not for save action

**Comment by Yashsharma1911** [comment]
> @Yashsharma1911  I do need help with making the RJSF required for publish action and not for save action
> 

In info modal we delete the required property from schema before passing it to RJSF, when user clicks on publish pass schema with required property and use RJSF validate, you can find implementation of how to validate in Helm Wizard in Meshery UI

**Comment by Yashsharma1911** [comment]
> > @Yashsharma1911  I do need help with making the RJSF required for publish action and not for save action
> 
> In info modal we delete the required property from schema before passing it to RJSF, when user clicks on publish pass schema with required property and use RJSF validate, you can find implementation of how to validate in Helm Wizard in Meshery UI

@captain-Akshay lemme know when you will push the new changes

**Comment by leecalcote** [comment]
merge conflicts.

**Comment by leecalcote** [comment]
Merge conflicts still.

**Comment by leecalcote** [comment]
Is selective validation not possible? Should we close this PR?

**Comment by leecalcote** [comment]
Screenshot?

**Pull request merged**
