### PR TITLE
detailed description for login and logout

### PR DESCRIPTION
**Pull request by warunicorn19**
Signed-off-by: Aditya Chaterjee <speak2adi@gmail.com>

**Description**
added better description for login and logout commands ( contd. from #3973 )
This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 7d390b06f655f33176cc8a71a675629534299ca5 at: https://614b1bb0709e4cb73f0bb8a2--meshery-docs-preview.netlify.app

**Review by alphaX86 — DISMISSED** [review]
LGTM let's see for others...

**Comment by alphaX86** [comment]
@warunicorn19 don't rebase this PR ASAP, coz I made an error in your change for that login, logout during merge conflict in my PR. Wait until I give a go

**Comment by warunicorn19** [comment]
Alrighty @alphaX86.

**Comment by alphaX86** [comment]
> @warunicorn19 don't rebase this PR ASAP, coz I made an error in your change for that login, logout in the ref table during merge conflict in my PR. Wait until I give a go

The issue is fixed. Thanks for your patience @warunicorn19 👍

**Review by leecalcote — DISMISSED** [review]

**Pull request merged**
