### PR TITLE
[Feat] Add validation endpoint

### PR DESCRIPTION
**Pull request by humblenginr**
**Description**

This PR creates a new endpoint api/meshmodel/validate. This PR is a part of meshmodel transition. It will be used to validate all types of meshmodel data. This is backed by CUE. This PR is associated with this https://github.com/meshery/meshkit/pull/196. One of the main reasons for exposing this functionality via meshery server(as opposed to just keeping it as a meshkit library function) is that it has use-cases in the frontend(fsm validation, design validation etc.).

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 99a20d91d75df2b229fcbd91ba0a875f75ac3fb7 at: https://62e15ad43cdbe5364d5fae27--meshery-docs-preview.netlify.app

**Comment by sudo-NithishKarthik** [comment]
Hmm.. It is working locally.. Re-running the jobs.

**Comment by leecalcote** [comment]
Unit tests failing.

**Comment by leecalcote** [comment]
An extra commit or two picked up by accident.

**Comment by sudo-NithishKarthik** [comment]
merging this as all the tests are passing

**Pull request merged**
