### PR TITLE
#1476

### PR DESCRIPTION
**Pull request by 7daytheory**
**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by 7daytheory** [comment]
I hope this does the job. Otherwise I might have to change some of the base structure since changing margins/sizes of content inside the table effects both img and text

**Comment by 7daytheory** [comment]
> Thank you, @7daytheory! Will you kindly consider incorporating the following feedback?
> 
> We do desire for visitors to have a sense of these platforms being categorized (e.g. Docker, Kubernetes, Mac...). Ideally, platforms listed under each category will be indented using whitespace (`&nbsp;`) or tabs (`&#9;`) (as opposed to hyphens). #1476 describes this a bit.

I added tabs and added a sign off but it doesn't seem to be taking. will try again

**Comment by leecalcote** [comment]
😄 @7daytheory

**Comment by PluckyPrecious** [comment]
This PR fixes #1436

**Pull request merged**
