### PR TITLE
Image Links Added

### LINKED ISSUE #4280: [Docs] Broken Image Links
#### Current State
Images are broken on this page - https://docs.meshery.io/functionality/performance-management

Screen Shot 2021-09-30 at 9 32 48 AM

#### Desired State
Images should be displayed.

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by Rishi22-Coding**
Signed-off-by: Saptarshi Patra <saptarshi.patra.22@gmail.com>

**Description**
Broken Images Links Fixed

This PR fixes #4280 

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 879b8343912eb043d7c9d6df65999dba3fd09e04 at: https://6156acbf34999c8d15a4422b--meshery-docs-preview.netlify.app

**Comment by Rishi22-Coding** [comment]
@warunicorn19 any thoughts??

**Comment by warunicorn19** [comment]
@Rishi22-Coding sorry for the inconvenience but @navendu-pottekkat fixed this in his PR as it was done by mistake. But, something to keep in the mind for next time, the syntax for the <a> tag was correct, you were not supposed to add a normal link there 😅.

**Comment by Rishi22-Coding** [comment]
> @Rishi22-Coding sorry for the inconvenience but @navendu-pottekkat fixed this in his PR as it was done by mistake. But, something to keep in the mind for next time, the syntax for the `` tag was correct, you were not supposed to add a normal link there 😅.
Okay I will keep that in mind next time😅.

**Pull request closed without merging**
