### PR TITLE
expose remote provider capabilities

### LINKED ISSUE #10510: [UI] Expose Remote Provider Capabilities in Settings page
### Current Behavior
As an extensible platform, Meshery has many different extension points. The Remote Provider extension point is one of those.

### Desired Behavior
Expose this API’s information in the existing “Remote Provider” tab of the Settings page - http://localhost:9081/api/provider/capabilities

### Mockups

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by Aseem22**
**Notes for Reviewers**

This PR fixes #10510

Preview:

Preferences-Meshery

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Thanks, @Aseem22!

**Comment by leecalcote** [comment]
Thanks, @Aseem22.

This is the right information. The layout is not so great, though, and fairly difficult to digest (in addition to it being ugly). What can you do to improve this?

**Comment by leecalcote** [comment]
> Thanks, @Aseem22.
> 
> This is the right information. The layout is not so great, though, and fairly difficult to digest (in addition to it being ugly). What can you do to improve this?

@Aseem22 thoughts? @Rexford74 @nwanduka help, please.

**Comment by nwanduka** [comment]
> > Thanks, @Aseem22.
> > This is the right information. The layout is not so great, though, and fairly difficult to digest (in addition to it being ugly). What can you do to improve this?
> 
> @Aseem22 thoughts? @Rexford74 @nwanduka help, please.

I was looking at this today. I don't have Meshery installed locally so I can't view the link in the associated issue description for more context about what is needed. I tried installing the Meshery extension in Docker but I keep getting errors. I'll keep at it. I'm sure I'll make some headway, otherwise, I'd definitely reach out for assistance so this PR doesn't linger for more than it already has.

**Comment by Aseem22** [comment]
> > > Thanks, @Aseem22.
> > > This is the right information. The layout is not so great, though, and fairly difficult to digest (in addition to it being ugly). What can you do to improve this?
> > 
> > 
> > @Aseem22 thoughts? @Rexford74 @nwanduka help, please.
> 
> I was looking at this today. I don't have Meshery installed locally so I can't view the link in the associated issue description for more context about what is needed. I tried installing the Meshery extension in Docker but I keep getting errors. I'll keep at it. I'm sure I'll make some headway, otherwise, I'd definitely reach out for assistance so this PR doesn't linger for more than it already has.

how can I help you here @nwanduka?

**Comment by leecalcote** [comment]
@Aseem22, you can use a tabbed menu component to organize these multiple lists of capabilities.

**Comment by sudhanshutech** [comment]
@Rexford74 @nwanduka any luck here

**Comment by leecalcote** [comment]
@Aseem22 we have a merge conflict here.

Have you proceeded with any further updates given the latest mockup from @Rexford74?

**Comment by Aseem22** [comment]
@leecalcote @Rexford74 all the updates have been made. 


https://github.com/meshery/meshery/assets/89309144/23d13ba1-fb08-4f8b-ba20-b138924ab905

**Comment by Rexford74** [comment]
> @leecalcote @Rexford74 all the updates have been made.
> 
>  aca7135f-ee78-4790-a3be-3b5d849dcc7f.mp4

Hey @Aseem22. Thanks for submitting this PR. I don't know if it's just me, but I can't seem to watch the video. Any help?

**Pull request merged**
