### PR TITLE
Fix: Overlapping of Link icon

### LINKED ISSUE #5917: [UI] Overlapping of icons on search result page
#### Current Behavior
On hovering over the bullet point of the list of results shown in search results [page](https://docs.meshery.io/search/) one extra attachment icon is coming and it's overlapping with the bullet points. 

#### Desired Behavior
Either the attachment icon can be removed and just showing the underline border below the heading of the list item would look sleek, or we can add some spacing between the attachment icon and bullet points so that they don't overlap. 

#### Screenshots/Logs
Mashery_1

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by janvi01**
Signed-off-by: janvi01 <janvibajo1@gmail.com>

**Description**

This PR fixes #5917 

**Notes for Reviewers**

I couldn't apply `margin-left` to anchorlink, I wonder what was the reason, so adjusted the link icon below the bullet icon.

Screenshot 2022-10-19 at 12 56 26 PM

Current implementation -

Screenshot 2022-10-19 at 12 59 14 PM

Also, the link icon points the heading to the top of the page, maybe it should point to the actual link.

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 3a150732dad8a9a9aee9840ab0ead1771cc0dc72 at: https://634fa9d831538368fef9511b--meshery-docs-preview.netlify.app

**Review by Abhishek-kumar09 — APPROVED** [review]

**Comment by leecalcote** [comment]
Thanks, @janvi01. Here's a recording of the behavior as seen in Safari.


https://user-images.githubusercontent.com/7570704/197621810-4d1d53b1-e715-4401-bd64-c9a10c8ce237.mov

**Comment by l5io** [comment]
🚀 Preview for commit be4798a239c0570e03fba72ad6667fcf07545d45 at: https://6357bfad3bbf744631c7fd46--meshery-docs-preview.netlify.app

**Review by leecalcote — CHANGES_REQUESTED** [review]
This change negatively impacts the placement of the anchor on other documentation pages.

**Comment by janvi01** [comment]
> This change negatively impacts the placement of the anchor on other documentation pages.

What should be the viable solution then? maybe placing it on the right side?

**Comment by leecalcote** [comment]
> > This change negatively impacts the placement of the anchor on other documentation pages.
> 
> What should be the viable solution then? maybe placing it on the right side? @leecalcote

@janvi01, yes, that will work.

**Comment by Chadha93** [comment]
@janvi01 Let's discuss this on the Meshery Dev call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#)

**Pull request closed without merging**
