### PR TITLE
Update logs to be right

### PR DESCRIPTION
**Pull request by Jougan-0**
**Notes for Reviewers**

This PR fixes #
Merge this [Schemas](https://github.com/meshery/schemas/pull/151) PR and update go mod before merging this PR.
Do a new Meshkit release as well.

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Schemas updated in #11772

**Comment by leecalcote** [comment]
```
$ make server
...
...
INFO[2024-08-23T23:12:04-05:00] For registrant artifacthub successfully imported 2116 models 11709 components 108 relationships  app=meshery
INFO[2024-08-23T23:12:04-05:00] For registrant github successfully imported 158 models 2446 components  app=meshery
INFO[2024-08-23T23:12:04-05:00] For registrant meshery successfully imported 5 models 593 components  app=meshery
```

**Comment by leecalcote** [comment]
Build checks failing.

**Comment by Jougan-0** [comment]
> Build checks failing.

It is due to that that unmarshall that I discussed. I'll fix it and the other linting I am taking a look and fixing it.

**Comment by Jougan-0** [comment]
> ```
> $ make server
> ...
> ...
> INFO[2024-08-23T23:12:04-05:00] For registrant artifacthub successfully imported 2116 models 11709 components 108 relationships  app=meshery
> INFO[2024-08-23T23:12:04-05:00] For registrant github successfully imported 158 models 2446 components  app=meshery
> INFO[2024-08-23T23:12:04-05:00] For registrant meshery successfully imported 5 models 593 components  app=meshery
> ```
> 
> One of these counts seems to be off, @Jougan-0

I think I am not following here could you please specify which one out of three. If you are talking w.r.t. the 1st one and relationships they are supposed to 108 and before they were 104 and now I think it is fixed.

**Review by leecalcote — APPROVED** [review]
Yay!

**Pull request merged**
