### PR TITLE
[DOCS] Change Database diagram to new one and rename database SVG file

### LINKED ISSUE #2421: [Docs] Update database architectural diagram
**Current State:**
The diagram on this page - https://docs.meshery.io/concepts/architecture/database is outdated.

**Desired State:**
The representative slide in [Meshery Architecture deck](https://docs.google.com/presentation/d/1SQMfyu5shjpGKlYONdVzOtd7UYTgLWBcgUvHMLCZ2tY/edit#slide=id.gbba492491e_0_5) (slide 7) should be exported to SVG and used replace the existing slide.

---
**Contributor Resources**
- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

### PR DESCRIPTION
**Pull request by alphaX86**
Signed-off-by: Aadhitya A <aadhitya864@gmail.com>

**Description**

This PR fixes #2421 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by alphaX86** [comment]
@leecalcote it's done. But it may need a test to see if it works. I done it and it LGTM

**Review by leecalcote — DISMISSED** [review]
Nice job on creating an individual page for the database component. The docs are in need of having a page created for each individual component.

**Comment by leecalcote** [comment]
@alphaX86 have a look at the updates made. Good to review and digest.

**Comment by alphaX86** [comment]
@leecalcote is this a desirable change? 
The architecture page is correct one

**Comment by alphaX86** [comment]
@leecalcote is this page a desirable one?
The arch page looks good with new image
image

But the database page, shows a different one
image

**Comment by alphaX86** [comment]
Should I leave as it is, then?

**Comment by leecalcote** [comment]
@alphaX86, oops. You're right. Use of the image on the dedicated database page was accidental. that older diagram should be deleted and replaced. 👍

**Comment by alphaX86** [comment]
Alright, so am I allowed to rename that image? Coz it works only if I do so, else it shows the old one only 😶

**Comment by alphaX86** [comment]
Whoa wait a sec. Ah!!! @leecalcote I misunderstood one moment, sorry for the inconvenience caused but it's redirected to original site one. So I guess it'll work as expected and no changes are required. I'll double check it though.....

**Comment by alphaX86** [comment]
Screenshot_2021-02-21-19-19-27-002_com android chrome

From the above image, I guess the desired change is achieved. I mistook the original site one. Anyway, issue solved! 👍

**Comment by leecalcote** [comment]
Oh, good deal.👌

**Pull request merged**
