### PR TITLE
fix: style for overview class

### PR DESCRIPTION
**Pull request by Udit-takkar**
Signed-off-by: Udit Takkar <udit.07814802719@cse.mait.ac.in>

This PR fixes https://github.com/meshery/meshery.io/issues/924

centered this button and width is not 100% as mentioned here https://github.com/meshery/meshery.io/issues/924#issuecomment-1336122105

Screenshot 2022-12-26 at 4 16 46 PM

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 7405430607f58c59e304e3a840c828b8c3dfb1c7 at: https://63a97d2cd922a87f55fb2f9f--meshery-docs-preview.netlify.app

**Review by leecalcote — APPROVED** [review]
LGTM

**Comment by l5io** [comment]
🚀 Preview for commit a959e87839cc300f37548514640dd52c93a23a57 at: https://63a9d43dceb41a358000d3c7--meshery-docs-preview.netlify.app

**Review by UtkarshMishra12 — APPROVED** [review]
LGTM Thanks @Udit-takkar 🚀🥇

**Review by leecalcote — APPROVED** [review]
lgtm

**Pull request merged**
