### PR TITLE
Pattern/Application Configuration form separated out

### LINKED ISSUE #4137: [ UI-Patterns ] Extract Patterns component to it's own file
#### Current Behavior
Pattern function in is in MesheryPatterns.js . This issue is based on action item 1 in the epic. [#4110]. 

#### Desired Behavior
Have own file for Patterns Component.

#### Implementation
Extract out the patterns component into it's own file.
https://github.com/meshery/meshery/blob/d11e84b348b48fdfe80823549692640553ab0d85/ui/components/MesheryPatterns.js#L645-L650

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by Zain-Muiz**
Signed-off-by: Zain-Muiz <zainu10863@gmail.com>

**Description**
Configuration form separated out and reused across Patterns and Applications.

This PR fixes #4137

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by navendu-pottekkat** [comment]
@Zain-Muiz Could you check these merge conflicts?

**Comment by sudo-NithishKarthik** [comment]
I don't think @Zain-Muiz  is available. @Abhishek-kumar09 , can you see to it that this pr gets merged ?

**Comment by leecalcote** [comment]
@Abhishek-kumar09 is this PR still valid?

**Comment by Abhishek-kumar09** [comment]
Hi @Zain-Muiz, Thanks a lot for opening a PR. Your efforts count. I am closing this PR. Since we had some major changes in the  codebase. By the way, Please let me know if you want to assist anywhere on some other components.

**Pull request closed without merging**
