### PR TITLE
Added serverside SSE for operator

### PR DESCRIPTION
**Pull request by dhruv0000**
Signed-off-by: dhruv0000 <patel.4@iitj.ac.in>

**Description**
Implementing SSE for meshery Operator
This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Nice

**Comment by dhruv0000** [comment]
This might be scrubbed. Had a talk with @abhishekkumkar in afternoon. Taking the direction of having a graphql subscription, which can later be extended in other places.

**Comment by leecalcote** [comment]
Ok, sounds good.

**Comment by kumarabd** [comment]
> This might be scrubbed. Had a talk with @abhishekkumkar in afternoon. Taking the direction of having a graphql subscription, which can later be extended in other places.

You tagged the wrong guy @dhruv0000 :P

**Pull request closed without merging**
