### PR TITLE
fixed the chevron problem

### LINKED ISSUE #3769: [UI] button to expand the menu is not visible when the menu is minimised
#### Current Behavior

The button to expand the menu is not visible when the menu is minimised as shown below.

The users have to scroll to find the button to expand the menu.

Screenshot 2021-08-04 at 6 18 40 PM

Screenshot 2021-08-04 at 6 18 45 PM

#### Desired Behavior

The button to expand should be visible and users should be able to click it without having to scroll.

#### Environment

- Browser: Chrome
- Host OS: Mac
- Meshery Server Version: edge
- Meshery Client Version: edge
- Platform: Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by warunicorn19**
Signed-off-by: Aditya Chaterjee <speak2adi@gmail.com>

**Description**
This fixes the Chevron issue, but just for chrome

https://user-images.githubusercontent.com/53532328/128404977-7485e974-ae0b-4ff5-aac9-4f36dde7e478.mov

Small overlap issue persists for safari

https://user-images.githubusercontent.com/53532328/128405058-065bdc6c-ae6f-4c94-84da-b63edf308099.mov

This PR fixes #3769 

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by Abhishek-kumar09 — COMMENTED** [review]
It still shows the backgroung behind the chevron, so for smaller screen we may see something like this (The overallaping effect ).

A better approach could be to block that view entirely?

 image

**Comment by warunicorn19** [comment]
@Abhishek-kumar09 we could try that, I'll take a look tomorrow.

**Comment by Abhishek-kumar09** [comment]
Sure, Btw the latest drawer has some changes. Don't forget to pull the latest changes :smiley:

**Comment by warunicorn19** [comment]
Yes, I have that in mind😅.

**Comment by warunicorn19** [comment]
@Abhishek-kumar09 could you tell me how you got this? Can't seem to recreate this.

**Comment by Abhishek-kumar09** [comment]
> @Abhishek-kumar09 could you tell me how you got this? Can't seem to recreate this.

Just decrease the height of the browser window and expand the icons of help button. and try to scroll then.

**Comment by warunicorn19** [comment]
@Abhishek-kumar09 since ive made the chevron sticky, that problem doesnt happen anymore, like you can just scroll down.

Uploading Screen Recording 2021-08-06 at 6.39.09 PM.mov…

**Comment by warunicorn19** [comment]
@leecalcote could we merge this? I think the issue is fixed but every time i open the development server, i get to see different a different behaviour from the chevron.

**Comment by leecalcote** [comment]
@warunicorn19 sounds good. Let's see...

**Pull request merged**
