### PR TITLE
fix[UI]: Make Meshery logo stick to the top in Navigator

### LINKED ISSUE #3131: [UI] Logo area should be frozen in place
#### Description
The Meshery Logo should not disappear when users scroll through the menu.

#### Screenshots/Logs
Untitled

#### Environment:
- Meshery Version: v0.5.17
- Browser: Safari

### PR DESCRIPTION
**Pull request by humblenginr**
Made position sticky and gave top 0 so that the List item component
remains at the top. And gave z index 5 to make it look like its in the
top and covers whatever is under it

Resolves Issue #3131

Signed-off-by: suod-NithishKarthik <nithishkarthik01@gmail.com>

**Description**

This PR fixes #3131 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x ] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Thank you for tackling this issue, @sudo-NithishKarthik 👍

**Review by Ayush-Khandelwal-007 — CHANGES_REQUESTED** [review]
It is done neatly but can you please remove the styles form the class that are not required, like font size and all.

**Comment by sudo-NithishKarthik** [comment]
Ya, sure 👍🏽

**Review by Ayush-Khandelwal-007 — APPROVED** [review]
Good to go now 👍🏻 .

**Review by leecalcote — APPROVED** [review]
Thank you, @sudo-NithishKarthik 👍

**Pull request merged**
