### PR TITLE
Adds a New Line for the finalMSG

### LINKED ISSUE #3255: [mesheryctl]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior
A grammatical error exists in the output from the `mesheryctl system stop` command when Meshery is deployed in K8s cluster.

#### Desired Behavior
This output should read:

```
➜  ~ mesheryctl system stop
Meshery deployments will be deleted from your cluster. Are you sure you want to continue [y/n]? y
Stopping Meshery...
Pods terminated.
Meshery is stopped.
```

#### Screenshots/Logs
```
➜  ~ mesheryctl system stop
Meshery deployments will be deleted from your cluster. Are you sure you want to continue [y/n]? y
Stopping Meshery...
Pods terminatedeshery pods
Meshery is stopped.
```

#### Environment

- Host OS: Mac
- Meshery Client Version: stable-v0.5.25
- Platform: Kubernetes

---

#### Contributor Resources

- [mesheryctl Contributing Guide](https://github.com/layer5io/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by DantrazTrev**
Signed-off-by: Ayush PS <ayushpratap16@gmail.com>

**Description**

This PR  fixes #3255

**Notes for Reviewers**
Adds a new line to the `finalMSG` in the `spinner` in `mesheryctl` . This is close to the desired behaviour,

The issue for the overlapping text tracks down to the [Spinner](https://github.com/briandowns/spinne) library used [issue](https://github.com/briandowns/spinner/issues/58#issue-351399814).

This is a makeshift fix for this issue.Till the issue in the library is fixed

**[Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Thank you, @DantrazTrev. Is this still a draft or is it ready for review?

**Comment by DantrazTrev** [comment]
Hei @leecalcote this is still a draft . I apologize  for the delay I'm having a few system issues so I couldn't test the rest of it .

**Comment by DantrazTrev** [comment]
> Thank you, @DantrazTrev. Is this still a draft or is it ready for review?

Hei @leecalcote it's done now , The issue tracks down to the Spinner library https://github.com/briandowns/spinner/issues/58#issue-351399814 for some terminals. I've added a new line to make things looks good for now

**Comment by navendu-pottekkat** [comment]
Thank you @DantrazTrev This seems like the viable workaround for now.

**Review by navendu-pottekkat — DISMISSED** [review]
Looks Good, although we still see the spinner which is an issue but as this is a workaround, it is better than what we have now.

Screenshot_20210624_175611

If the second message(finalMSG) is longer than the first message(Suffix), we would not have this issue right? That is also a viable fix for this.

```
⣽ Terminating Meshery pods
Terminated pods in the meshery namespace
```

@leecalcote @anirudhjain75 @hexxdump Thoughts?

**Comment by DantrazTrev** [comment]
@navendu-pottekkat Maybe we could Add longer finalMSG . Just an empty string to cover up the message. That'll still be a hack and might solve the inteneted case?

**Comment by navendu-pottekkat** [comment]
Yes that could be. It should not effect anything else I guess.

**Comment by DantrazTrev** [comment]
> Yes that could be. It should not effect anything else I guess.

Yup it does . I'm adding it now
Screenshot from 2021-06-24 18-50-20

**Review by hexxdump — COMMENTED** [review]
@DantrazTrev , What happens when the s.Suffix is reset before s.Stop() at line no: 195?

**Comment by DantrazTrev** [comment]
Hei @hexxdump . Not really sure how that would play out in every environment🤔,  But my initial guess was from a sandbox logging out in every line . I can give it a try , but I don't think that would be a good use case if `CreateDefaultSpinner` was used anywhere else.

**Comment by hexxdump** [comment]
> Hei @hexxdump . Not really sure how that would play out in every environment🤔, But my initial guess of trying that was from a sandbox logging out in every line . I can give it a try again , but I don't think that would be a good use case if `CreateDefaultSpinner` was used anywhere else.

@DantrazTrev, resetting s.Suffix is applicable only for this instance of spinner. It will not impact any other spinner(which can have a different Suffix and FinalMSG). We can test it out on other OS/env, if this works in the way we expect it to work.

**Comment by DantrazTrev** [comment]
> > Hei @hexxdump . Not really sure how that would play out in every environmentthinking, But my initial guess of trying that was from a sandbox logging out in every line . I can give it a try again , but I don't think that would be a good use case if `CreateDefaultSpinner` was used anywhere else.
> 
> @DantrazTrev, resetting s.Suffix is applicable only for this instance of spinner. It will not impact any other spinner(which can have a different Suffix and FinalMSG). We can test it out on other OS/env, if this works in the way we expect it to work.

@hexxdump that works the same. So I should switch to that now ig?

**Comment by hexxdump** [comment]
> > > Hei @hexxdump . Not really sure how that would play out in every environmentthinking, But my initial guess of trying that was from a sandbox logging out in every line . I can give it a try again , but I don't think that would be a good use case if `CreateDefaultSpinner` was used anywhere else.
> > 
> > 
> > @DantrazTrev, resetting s.Suffix is applicable only for this instance of spinner. It will not impact any other spinner(which can have a different Suffix and FinalMSG). We can test it out on other OS/env, if this works in the way we expect it to work.
> 
> @hexxdump that works the same. So I should switch to that now ig?

It sounds like a better plan to me, rather than padding the FinalMsg.

@navendu-pottekkat, what do you think?

**Comment by navendu-pottekkat** [comment]
@hexxdump @DantrazTrev So basically the UX would be the same, instead of padding, we go with a better workaround. Sounds good to me.

**Comment by DantrazTrev** [comment]
> @hexxdump @DantrazTrev So basically the UX would be the same, instead of padding, we go with a better workaround. Sounds good to me.

Done @navendu-pottekkat

**Review by hexxdump — APPROVED** [review]
LGTM. Thanks @DantrazTrev !

**Comment by navendu-pottekkat** [comment]
@DantrazTrev @hexxdump I'm still getting the same-

Screenshot_20210624_231354

**Comment by DantrazTrev** [comment]
> @DantrazTrev @hexxdump I'm still getting the same-
> 
> Screenshot_20210624_231354

Looked fine on here. Let me just recheck.

**Comment by DantrazTrev** [comment]
> @DantrazTrev @hexxdump I'm still getting the same-
> 
> Screenshot_20210624_231354

Sorry @navendu-pottekkat , I think we might need to revert to the old padding hack

**Comment by navendu-pottekkat** [comment]
Ahhh, cool. @hexxdump were you able to get the workaround you mentioned? Was it working for you?

**Comment by sayantan1413** [comment]
Hey @navendu-pottekkat and @DantrazTrev I added the line s.Suffix = "" before line 195 but the error still persist for me. But if it is working on other machine then it is absolutely fine.

**Comment by DantrazTrev** [comment]
Hei @navendu-pottekkat I'm reverting it back to the padding I think the s.Suffix part only works for the sandbox environments.

**Comment by DantrazTrev** [comment]
> Hei @navendu-pottekkat I'm reverting it back to the padding I think the s.Suffix part only works for the sandbox environments. And we're looking for the option that covers most cases

**Comment by navendu-pottekkat** [comment]
@DantrazTrev Are the changes ready for review?

**Comment by hexxdump** [comment]
> Ahhh, cool. @hexxdump were you able to get the workaround you mentioned? Was it working for you?

Does not work on macOS. Better to go with the padding fix.

**Review by hexxdump — APPROVED** [review]

**Review by navendu-pottekkat — APPROVED** [review]

**Comment by navendu-pottekkat** [comment]
Thank you @DantrazTrev

**Pull request merged**
