### PR TITLE
[Docs] Network port clarification

### LINKED ISSUE #4831: [Docs] Identify and reduce which Meshery Broker ports are used
#### Current State
4222/tcp, 6222/tcp, 8222/tcp, 7777/tcp, 7422/tcp, 7522/tcp are listed as the ports used by Meshery Broker - https://docs.meshery.io/concepts/architecture#network-ports. Are all of these needed?

#### Desired State
Identify the ports that are actually used. Reduce number of ports used. Update docs.

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by leecalcote**
Signed-off-by: leecalcote <leecalcote@gmail.com>

**Description**

This PR fixes #4831

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 59d868c43aebc6a36e360ce2c5615c749a681c50 at: https://61ce2d450b79200e07850170--meshery-docs-preview.netlify.app

**Comment by warunicorn19** [comment]
@leecalcote could you please revert the changes to the package-lock.json files

**Comment by l5io** [comment]
🚀 Preview for commit aebf34c52691b9ed3da465d51570cd04cd4de946 at: https://61ce2ed79a1bec244441daf9--meshery-docs-preview.netlify.app

**Review by warunicorn19 — APPROVED** [review]
LGTM, I think you missed out on `octarine` though

**Review by bariqhibat — APPROVED** [review]
Looks good!

**Comment by l5io** [comment]
🚀 Preview for commit 965423482708e0f1f22d93318488799196e56a7b at: https://61cf4f08eb07cb6b25095d7f--meshery-docs-preview.netlify.app

**Pull request merged**
