### PR TITLE
[MeshSync] Expose MeshSync Discovered Resources

### PR DESCRIPTION
**Pull request by theBeginner86**
**Notes for Reviewers**

This PR adds API (/system/meshsync/resources) to fetch MeshSync Discovered Resources.

Screenshot 2023-10-18 at 6 52 25 PM

This PR fixes #

Earlier, it was part of this [PR](https://github.com/meshery/meshery/pull/9127) but then I moved it out considering the urgency of GO pkg update.

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 93fbc610585cfef6c0f352f9d90f309d449a2804 at: https://652feaaccb96e702c3703faf--meshery-docs-preview.netlify.app

**Comment by theBeginner86** [comment]
Updated Meshery API [Spreadsheet](https://docs.google.com/spreadsheets/d/1ABJCbfQRi0uN_YoP2kmHZ-lTI4S4QuvRk1_unomKNRE/edit?skip_itp2_check=true&pli=1#gid=1241442399)

**Comment by l5io** [comment]
🚀 Preview for commit 91c0d85a89d96147ee6ff71212e31f00bfb7d062 at: https://652ff78b69983b0996e5807f--meshery-docs-preview.netlify.app

**Comment by theBeginner86** [comment]
@Yashsharma1911  @senali-d looks good?

**Pull request merged**
