### PR TITLE
Model include added in integrations layout

### PR DESCRIPTION
**Pull request by iArchitSharma**
**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 32f49c121e976c7064fdc97c5cf29d1c6fe0ca8a at: https://6627bb52374b210093328bee--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit a76e60e3024cd76a6cc5ebc9a6ee38198ace4eea at: https://662f7ea58ab10800a7e652bc--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit d9088b625c92e42ba3e2ffd2100b7f9086882575 at: https://66364d4d2788c4059d1f410c--meshery-docs-preview.netlify.app

**Review by leecalcote — APPROVED** [review]
Thank you!

**Pull request merged**
