### PR TITLE
[UI] Fix UI crash due to invalid hook call

### PR DESCRIPTION
**Pull request by Abhishek-kumar09**
Signed-off-by: Abhishek-kumar09 <abhimait1909@gmail.com>

Fixes: https://layer5io.slack.com/archives/CFGG6U10E/p1645404841404479

**Description**
Fix problems of hook call inside function.
The hooks follow principles of being called only from the react functional components. 
This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by warunicorn19 — COMMENTED** [review]
Getting this now, @Abhishek-kumar09 this is an issue with the schema right? 
Screenshot 2022-02-21 at 9 02 33 AM

**Comment by Abhishek-kumar09** [comment]
Yeah, So read though this: 
image

We were right kinda wrong. 
We were expecting all the fields to have `type` property in the schema (necessary to take a lot of decisions), but reading through point 1, it is clear that if any of the two field is present in `x-kubernetes-int-or-string` or `x-kubernetes-preserve-unknown-fields` the schema will not have a `type` property, that was the exception we were missing from the start. 

Thus, the schema is **not** invalid.

**Comment by warunicorn19** [comment]
Got you, Thank you @Abhishek-kumar09

**Review by warunicorn19 — APPROVED** [review]
LGTM! Merge at will

**Pull request merged**
