### PR TITLE
modify cypress tests after multi-ctx PR

### PR DESCRIPTION
**Pull request by Abhishek-kumar09**
Signed-off-by: Abhishek-kumar09 <abhimait1909@gmail.com>

**Description**
1. Modify tests for passing ui
2. The chips were removed thus the corresponding tests for clicks are also commented out.

The UI had changed the following way.
Previous | Now
--- | ----
image | image

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
The first of two tests passed. ✅

**Comment by leecalcote** [comment]
Two of two passed. ✅

**Comment by leecalcote** [comment]
Fixes https://github.com/meshery/meshery/issues/5068

**Review by leecalcote — APPROVED** [review]
LGTM

**Review by warunicorn19 — APPROVED** [review]

**Comment by MarioArriaga92** [comment]
Taking a look

**Review by MarioArriaga92 — APPROVED** [review]
LGTM 🔥

**Comment by warunicorn19** [comment]
Thank you for the review @MarioArriaga92

**Pull request merged**
