### PR TITLE
fixed table header and updated overview link

### LINKED ISSUE #7591: [Docs] Replace contents of Meshery Overview
#### Current State
Currently the pages https://docs.meshery.io/getting-started/overview and https://docs.meshery.io/project are redundant. The 'project' page however is more comprehensive and contains additional links. 

#### Desired State

1. Change `Meshery Overview` at https://docs.meshery.io to link to https://docs.meshery.io/project

Screenshot 2023-04-22 at 2 12 46 AM

2. Fix the table headers at  https://docs.meshery.io/project

Currently they look like the following -

image
 
Instead they should look like the ones at https://docs.meshery.io/getting-started/overview

image

3. Make sure that all content at https://docs.meshery.io/getting-started/overview is contained in https://docs.meshery.io/project

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by rijusougata13**
**Notes for Reviewers**

This PR fixes #7591 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 9291512855a61f5b881ce8a0c94cbb8d02dcd750 at: https://644543a534418c387300b7d5--meshery-docs-preview.netlify.app

**Review by thisiskaransgit — APPROVED** [review]
Looks good to merge, thank you for this fix :tada:

**Comment by thisiskaransgit** [comment]
With this, we can remove getting-started/overview.md from the directory & `cd .. ` news.md

**Comment by rijusougata13** [comment]
I can't find a slot to update? In which date I should add this note?

**Comment by vishalvivekm** [comment]
> I can't find a slot to update? In which date I should add this note?

@rijusougata13 here:  [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#)

**Comment by rijusougata13** [comment]
updated @vishalvivekm

**Review by leecalcote — APPROVED** [review]
Thanks much, @rijusougata13

**Pull request merged**
