### PR TITLE
Fix the meshmodel docs as suggested by reviewers.

### PR DESCRIPTION
**Pull request by parth721**
**Notes for Reviewers**

This PR fixes #

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 48d2127ac442a8f3dc5d18ebc03bcee9f14315f2 at: https://64fb4587ecfe8316e8586b8d--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 48d2127ac442a8f3dc5d18ebc03bcee9f14315f2 at: https://64fb6059d0af9f3e726bc482--meshery-docs-preview.netlify.app

**Comment by alphaX86** [comment]
@parth721 is this same as PR #8656?? 👀

**Comment by alphaX86** [comment]
I see same changes there as well

**Comment by parth721** [comment]
Oh sorry I will close it now... My mistake

**Pull request closed without merging**
