### PR TITLE
[UI] - Added count to tabs for meshmodel browser

### PR DESCRIPTION
**Pull request by smartdev09**
**Notes for Reviewers**

This PR fixes #

Added count to meshmodel browser tabs. 

coubnt

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — DISMISSED** [review]
Looking good!

**Comment by leecalcote** [comment]
@UsmanDev09 I wonder if you can assist with these failing eslint checks. // @Abhishek-kumar09

**Comment by leecalcote** [comment]
Actually, I think @theBeginner86 took care of these.

**Comment by theBeginner86** [comment]
btw looks like this PR introduced more lint errors 😅 // @UsmanDev09 

Please don't forget to fix lint errors before pushing.

Screenshot 2023-07-05 at 2 17 58 AM

**Comment by theBeginner86** [comment]
But I have added the fix for eslint... 👍

**Review by theBeginner86 — APPROVED** [review]

**Pull request merged**
