### PR TITLE
Update Artifacts sub-section in documentation

### PR DESCRIPTION
**Pull request by ValGrace**
Re-worded the sentencing the artifacts subsection for readability.

**Notes for Reviewers**

This PR fixes #

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit d54871df652cfe551aecf6eeae6506b67e2e68b9 at: https://651acafa17e8451c4cd71e73--meshery-docs-preview.netlify.app

**Comment by saurabh100ni** [comment]
Let's discuss this on the Meshery dev call tomorrow,
Please add this as your agenda item in Docs: https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit

**Review by leecalcote — APPROVED** [review]
Yay, @ValGrace! 💯 

Most excellent.

**Comment by leecalcote** [comment]
Thank you for this, @ValGrace 👏

**Pull request merged**
