### PR TITLE
Upgrade github.com/layer5io/nighthawk-go to v0.5.0

### PR DESCRIPTION
**Pull request by gyohuangxin**
Signed-off-by: Huang Xin <xin1.huang@intel.com>

**Description**

This PR fixes layer5io/getnighthawk#237

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by DelusionalOptimist — CHANGES_REQUESTED** [review]
@gyohuangxin please remove this line:
https://github.com/meshery/meshery/blob/900984bae4a5ffe2a14d84991dc724d42320bd95/helpers/load_test_interface.go#L312
This line is trying to set `h2` in test config but since it is deprecated and not present in the new [command line options](https://github.com/layer5io/getnighthawk/blob/ee35f6bea5fadef194d028b98e03bfdb570a14fa/pkg/proto/options.pb.go#L882) struct, it fails during compilation.

Please change this line:
https://github.com/meshery/meshery/blob/900984bae4a5ffe2a14d84991dc724d42320bd95/helpers/load_test_interface.go#L411
to
```
d, err := nighthawk_client.Transform(res1)
```

**Comment by gyohuangxin** [comment]
@DelusionalOptimist Thanks for your comments, I'll try it.

**Comment by gyohuangxin** [comment]
@DelusionalOptimist UT tests passed after the change as you said, pls review again. Thanks

**Comment by leecalcote** [comment]
I'm seeing lots of  ✅ here. :)

**Review by leecalcote — APPROVED** [review]
LGTM

**Pull request merged**
