### PR TITLE
[UI] Filters delete files(single select)

### LINKED ISSUE #3826: [Filters] Unable to delete a filter persisted in Remote Provider
#### Description
Deleting filters stored in Remote Providers doesn't have the desired affect.

#### Expected Behavior
Filter record should be tombstoned by Remote Provider and no longer displayed in the UI.

#### Screenshots/Logs

Screen Shot 2021-08-09 at 9 27 58 AM

#### Environment

- Host OS: Mac 
- Meshery Server Version: stable-v0.5.42
- Meshery Client Version: stable-v0.5.42
- Platform: Docker 

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by Chadha93**
Signed-off-by: Gaurav Chadha <gauravchadha1676@gmail.com>

**Description**
Configuring the Bulk delete

This PR fixes #3826 

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Chadha93** [comment]
@utkarsh-pro I'm able to trigger/access the bulk delete, but facing an issue to pass/set the delete function according to have the bulk delete functionality trigerred. 
Screenshot from 2021-08-15 00-00-56

**Comment by Chadha93** [comment]
@navendu-pottekkat Since the bulk delete provided by the muidatable is accessed now, but not triggering the delete operation successfully, maybe it would work without making any changes to the delete handler in the backend.

**Comment by navendu-pottekkat** [comment]
@Chadha93 I am not quite sure. The backend only expects a single ID and proceeds to delete the pattern/filter/application with that ID.

**Comment by utkarsh-pro** [comment]
@Chadha93 does the implementation Performance Profile Table helps? https://github.com/meshery/meshery/blob/master/ui/components/MesheryPerformance/PerformanceProfileTable.js

**Comment by Chadha93** [comment]
> @Chadha93 does the implementation Performance Profile Table helps? https://github.com/meshery/meshery/blob/master/ui/components/MesheryPerformance/PerformanceProfileTable.js

@utkarsh-pro Thanks, you pointed exactly what I need, PerformaceProfileTable uses the same approach, which means it will work with UI changes only. so no changes are required in the backend. :100:

**Comment by Chadha93** [comment]
@utkarsh-pro 
Now it is deleting the filters from selection but, when selecting more than one its deletes the first one could you please tell why it's not doing for multiple, The API endpoints used are also working fine.
https://user-images.githubusercontent.com/65453826/129598017-80735bd5-a78f-41e1-880b-df2bad1c5092.mp4

**Review by leecalcote — APPROVED** [review]
Single delete action. ✔️

**Pull request merged**
