### PR TITLE
[RJSF/Extension] Fix Name and Namespace Fileds

### PR DESCRIPTION
**Pull request by Abhishek-kumar09**
Signed-off-by: Abhishek-kumar09 <abhimait1909@gmail.com>

**Description**
The Fix for name and namespace being odly aligned and pulled to end.
image

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
@Abhishek-kumar09 is it possible to eliminate much of the vertical whitespace between the title bar and the Name and Namespace fields?

Taking this one step further, is is possible to put both of these fields into a contain with light shadow like this?

Group 1042


See https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=4021%3A21993 for CSS

**Review by leecalcote — COMMENTED** [review]
@sudo-NithishKarthik will this apply universally? Across both "templates"?

**Comment by l5io** [comment]
Task linked: [CU-1y8j5k3 [Designer] Move the `Name` and `Namespace` fields to the top in the RJSF form](https://app.clickup.com/t/1y8j5k3)

**Comment by leecalcote** [comment]
CU-1y8j5k3

**Comment by Abhishek-kumar09** [comment]
> @sudo-NithishKarthik will this apply universally? Across both "templates"?

Yes, @leecalcote

**Pull request merged**
