### PR TITLE
aligned icon in footer

### LINKED ISSUE #7269: [UI] improve the positon and spacing of icons in the UI
#### Current Behavior

While most of the icons are placed perfectly fine in the UI, there are some which are aligned in the wrong way, or have wrong amount of spacing.

#### Desired Behavior

The icons should be aligned properly and also have proper spacing to ensure the UI looks clean and polished.
For example:
Current: 
i2

Possible Improvement:
i3

#### Implementation

1. Identifying the icons which are wrong( already few examples are here, like the "heart" shape of the footer)
2. Applying styles that make the icons properly spaced and aligned.

#### Mockups

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by soham4abc**
**Notes for Reviewers**

This PR fixes #7269

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

Footer Icon aligned as per requirement:

image

### CODE REVIEW

**Review by leecalcote — CHANGES_REQUESTED** [review]
Please use dynamic positioning (e.g. justify-items: center), not static (explicit px or rem).

**Comment by soham4abc** [comment]
> Please use dynamic positioning (e.g. justify-items: center), not static (explicit px or rem).

Done as per request! 
Please do have a look!!

**Comment by sidtohan** [comment]
Oh so it seems like we have both made a PR for this same issue @soham4abc. Its fine though, but I think its best if we integrate our changes.

**Comment by leecalcote** [comment]
Merge conflict...

**Comment by soham4abc** [comment]
> Merge conflict...

Fixed

**Review by harkiratsm — APPROVED** [review]

**Review by Chadha93 — APPROVED** [review]

**Pull request merged**
