### PR TITLE
Added Cilium Service Mesh to table of contents (menu)

### LINKED ISSUE #5472: [Docs] Add Cilium Service Mesh to table of contents (menu)
#### Current State
The current table of contents does not have Cilium Service Mesh listed.
Screen Shot 2022-05-03 at 5 43 38 PM

#### Desired State
Add an entry for Cilium Service Mesh pointing to `/service-meshes/adapters/cilium`

(https://docs.meshery.io/service-meshes/adapters/cilium)

---

#### [Contributor Guides](https://docs.meshery.io/project/contributing) and Resources
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by Rohith-Raju**
Signed-off-by: Rohith Raju <rohithraju488@gmail.com>

**Description**
[Docs]
Added a menu item in **Service Meshes toc**

This PR fixes #5472

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 744d35d46c82163a8f52ddbbe9f885cc38334162 at: https://6277745b3b8ea01d636de8aa--meshery-docs-preview.netlify.app

**Review by karnatisrinivas — COMMENTED** [review]
LGTM, Nice work rohith 👍

**Review by Akshit42-hue — APPROVED** [review]
LGTM! Great work @Rohith-Raju :)

**Comment by l5io** [comment]
🚀 Preview for commit 92f329d648cb65dfd4bbfa60492c7e488a9024ca at: https://6278fdd79f1815222582ee5f--meshery-docs-preview.netlify.app

**Review by Chadha93 — COMMENTED** [review]
@Rohith-Raju Good work here, just a minor: we should use cilium highlighted images here for representation, currently it's highlighted on linkerd 
image

**Comment by leecalcote** [comment]
@Rohith-Raju, looks good. While you're in here, will you also fix the misspelling of "Ciluim" on the adapter page?

**Comment by Rohith-Raju** [comment]
@leecalcote Could you provide me with a link pointing to where the mistake occurred?

**Comment by leecalcote** [comment]
Search the page for the misspelling, @Rohith-Raju

**Comment by Rohith-Raju** [comment]
As @Chadha93 pointed me to change the screenshots, Well I'm not able to access the Cilium adapter.

image
image
image
image

I have exams starting tomorrow and can't find time to debug them. If this issue is of utmost priority, please send me the screenshots and since it's just a matter of changing the images, I'll do it 😄

**Comment by leecalcote** [comment]
The misspelling is right on the page that you've created a table of contents entry for - https://docs.meshery.io/service-meshes/adapters/cilium. I'll take care of it.

**Pull request merged**
