### PR TITLE
Add Details/Summary for General Contribution Flow

### LINKED ISSUE #7455: [Docs] Add Details/Summary for General Contribution Flow
#### Current State
Some Meshery Docs pages have more information displayed upon page load than is immediately necessary. 

https://docs.meshery.io/project/contributing is an example. Both the https://docs.meshery.io/project/contributing#general-contribution-flow and the https://docs.meshery.io/project/contributing#meshery-contribution-flow sections could be collapsed by default.

#### Desired State
Use `<details>` and `<summary>` to provide the reader with a show/hide toggle. Only the summary should be shown on page load.

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by ankur0904**
**Notes for Reviewers**

This PR fixes #7455 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit cd66b6ab00c917868a517ed44898971c40dae2a6 at: https://6486dd2a3cc836050a8503cc--meshery-docs-preview.netlify.app

**Comment by vishalvivekm** [comment]
@ankur0904 
??
Screenshot from 2023-06-12 16-04-48

**Comment by l5io** [comment]
🚀 Preview for commit 07303ff95d8fe8f8aebfb31bcd8f13cf61e65281 at: https://64874e31b3de6000776a53a4--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 465c295b57c4dd084209e07b49210b619a73a258 at: https://648e930278649d7925a5bc62--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 54ea0c1c01f0d9f87b90626a14d2d2e410eda8fa at: https://648e94cab952097b8f052cec--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit c76977ff780eb407de929b5ae90ea6baf2611301 at: https://648e98fa38df297d14152149--meshery-docs-preview.netlify.app

**Comment by thisiskaransgit** [comment]
@ankur0904, What's your progress?

**Comment by ankur0904** [comment]
@thisiskaransgit I tried but unable to fix the issue :(

**Comment by leecalcote** [comment]
@ankur0904, To add your Signed-off-by line to every commit in this branch:

Ensure you have a local copy of your branch by [checking out the pull request locally via command line](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/checking-out-pull-requests-locally).
In your local branch, run: `git rebase HEAD~5 --signoff`
Force push your changes to overwrite the branch: `git push --force-with-lease origin docs/ankur0904/#7455`

**Review by leecalcote — CHANGES_REQUESTED** [review]
@ankur0904, To add your Signed-off-by line to every commit in this branch:

Ensure you have a local copy of your branch by [checking out the pull request locally via command line](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/checking-out-pull-requests-locally).
In your local branch, run: `git rebase HEAD~5 --signoff`
Force push your changes to overwrite the branch: `git push --force-with-lease origin docs/ankur0904/#7455`

**Comment by l5io** [comment]
🚀 Preview for commit b3b8f6789687121b60ab0debb93b2e4140415496 at: https://64a07fa313d46c6037548401--meshery-docs-preview.netlify.app

**Review by leecalcote — APPROVED** [review]

**Comment by leecalcote** [comment]
@ankur0904 you're right. It doesn't. Thank you for pointing this out.

**Comment by ankur0904** [comment]
@leecalcote @thisiskaransgit  Thank you so much.

**Pull request merged**
