### PR TITLE
docs in dark mode by default and added icons

### LINKED ISSUE #7190: [Docs] Set dark mode as the default Meshery Docs theme
#### Current State
Currently, light mode is the default.

#### Desired State
Dark mode, baby. Dark mode.

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by vishalvivekm**
**Notes for Reviewers**

This PR fixes #7190 #7208 
- sets dark mode as default Meshery docs theme
- updates the mode toggle icons (currently there's same icon ☀ for both modes):

Screenshot_20230228_005336
Screenshot_20230228_005348

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
Signed-off-by: Vivek Vishal <110674407+vishalvivekm@users.noreply.github.com>
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 0bf4cb03df46dd470b905f309deb323c1babcaf3 at: https://63ff9ff0990de2004eacad4a--meshery-docs-preview.netlify.app

**Comment by leecalcote** [comment]
@sudhanshutech what do you think?

**Comment by sudhanshutech** [comment]
> @sudhanshutech what do you think?

@leecalcote  there is a flickering of dark mode when page reloads in light theme, @vishalvivekm the root cause is because the javascript is reloading after the page reloads. So here is a reference you can take @vishalvivekm https://dev.to/ayc0/light-dark-mode-avoid-flickering-on-reload-1567

**Comment by sudhanshutech** [comment]
Let me know if you need help @vishalvivekm

**Comment by l5io** [comment]
🚀 Preview for commit c04e04368c7228569a2194eebf3f42ae8ff3085c at: https://6400740a9890866a17e26ff1--meshery-docs-preview.netlify.app

**Comment by vishalvivekm** [comment]
> Let me know if you need help @vishalvivekm

Hey, Thank you very much @sudhanshutech for the feedback! Please do checkout the new preview! The Flickering is gone ☺ 

I consider this to be the first and last change required in this PR @leecalcote @GaganpreetKaurKalsi

**Comment by sudhanshutech** [comment]
Nice work @vishalvivekm 👍

**Comment by leecalcote** [comment]
Thank you, gents.

**Pull request merged**
