### PR TITLE
Update version.go

### LINKED ISSUE #1664: [mesheryctl] Update error message in `mesheryctl version` failure to connect to server
**Description**
The error message shown when Meshery server is unavailable could be better phrased.

```
➜  .meshery mesheryctl version
Client Version: 0.4.12 	  GitSHA: 6f7a527f3fa5e713c52686f3387c3ae1b54de1f2
Server Version:  	  GitSHA: 6f7a527

failed to check for latest version of Meshery
```

**Expected Behavior**
Error message should be:

"Meshery server unreachable. Please confirm that Meshery is running and available. "

### PR DESCRIPTION
**Pull request by tripathyprateek**
**Description**

This PR fixes #1664 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Review by kushthedude — CHANGES_REQUESTED** [review]
Wrong place to change, please see the issue again!
Here is the code which needs the fix 
```go
		_, err = handlers.CheckLatestVersion(version.GetBuild())
		if err != nil {
			logrus.Warn("\nfailed to check for latest version of Meshery")
		}
```

**Comment by kushthedude** [comment]
Also, please sign-off your commits.

**Comment by leecalcote** [comment]
Here are the instructions to sign-off on this PR's commits: https://github.com/layer5io/meshery/pull/1769/checks?check_run_id=1319237799

**Comment by leecalcote** [comment]
@kushthedude this is the incorrect area to place the logic given a code change that was merged 2 hours prior to this PR, correct?

Keep up the good work, @tripathyprateek. We moved the cheese on you, while you were busying fixing the issue.

**Comment by tripathyprateek** [comment]
is this a problem with lint? I had only changed the message but it shows 93 lines are changed?

**Comment by kushthedude** [comment]
> is this a problem with lint? I had only changed the message but it shows 93 lines are changed?

IMO it is a problem with your local IDE/editor, as well as will you please look into the conflicts as well.

**Comment by leecalcote** [comment]
@tripathyprateek, I think you're close to a solution here. The inclusion of the 58 commits above is likely a snafu in managing forks, branches, and so on. You might given the branch on this PR another attempt or simply close this PR, sync your fork and clone, then submit a new PR... either way will work. 👍

**Comment by tripathyprateek** [comment]
Yes I will just close this PR and sync it again, and open a new PR

**Pull request closed without merging**
