### PR TITLE
add functionality to dynamically update the URL 

### LINKED ISSUE #8889: [Documentation] Link hyperlinks to URL querystrings and get the specific section location (#anchor) in your clipboard
### Current Behavior

When you click on a hyperlink that is linked to an anchor, such as a heading, the anchor isn't included in the URL querystring. Consequently, when you attempt to share a specific section of a page by clicking the anchor, then copying the URL from your browser's address bar, the clipboard doesn't capture the specific section location represented by the anchor (#anchor).

https://docs.meshery.io/reference/error-codes

### Expected Behavior

The expected outcome for the error code reference page is to have each error code readily hyperlinked and accessible from different locations, including the Notification Center within the Meshery UI.
### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by goldfishdolphin**
… an anchor link

**Notes for Reviewers**
I have added a javascript function to dynamically update the URL when a user clicks on an anchor link.
This PR fixes #8889 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit a55c059d67028e3ebfa1c6616ad1a45fd64fd683 at: https://650fdca7cb64f62c03b9fbb2--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 8a73eef4b6ce1274c8f9172d4d6b3d3ccee07b89 at: https://650fe0e451dc692fbbf8b4ca--meshery-docs-preview.netlify.app

**Review by aabidsofi19 — APPROVED** [review]
lgtm

**Review by Chadha93 — APPROVED** [review]
Thank you @goldfishdolphin

**Pull request merged**
