### PR TITLE
 applycmd for Mesh command

### LINKED ISSUE #8292: [mesheryctl] Apply Sub Command for Mesh Command
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior
No `apply` sub-command created for Mesh Command

#### Desired Behavior
  Create `apply` sub-command in mesheryctl's [mesh Command](https://github.com/meshery/meshery/tree/master/mesheryctl/internal/cli/root/mesh)

#### Mockups

---

#### Contributor Resources

- ⌨️ [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by Philip-21**
**Notes for Reviewers**

This PR fixes #8292

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by Philip-21** [comment]
@alphaX86, @theBeginner86, @abdullah1308    please i will need your review and help on this i've been figuring out how to try and implement the tls serviceMesh operation in the `sendOperationRequest()`

**Comment by vishalvivekm** [comment]
@Philip-21 Let's discuss this on Meshery Dev call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#) if you would. :)

**Review by leecalcote — CHANGES_REQUESTED** [review]
Hi @Philip-21, please have a look at the golangci-lint issues found.

**Comment by Philip-21** [comment]
> Hi @Philip-21, please have a look at the golangci-lint issues found.

Yh I saw it , I haven't set up the applycmd to be used in the `mesh.go` I'm still trying to implement service mesh operations like tls configurations before I declare it as a mesh command . The pr is still under work .

**Pull request closed without merging**
