### PR TITLE
[Docs] Add contributing instructions for end-to-end testing using Cypress

### LINKED ISSUE #5211: [Docs] Meshery UI: Add contributing instructions for end-to-end testing using Cypress
#### Current State
The [contributing page for Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui) doesn't currently mention Cypress and end-to-end tests.

#### Desired State
https://docs.meshery.io/project/contributing/contributing-ui should include specifics of considerations that contributors should make while contributing to Meshery UI.

The labeler commenter for PRs matching `component/ui` can also be updated to include a hyperlink to this section of the docs.

Context:
https://layer5io.slack.com/archives/C011VPREG2Z/p1647265714076679

---

#### [Contributor Guides](https://docs.meshery.io/project/contributing) and Resources
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by MarioArriaga92**
**Description**
Added contributing instructions providing useful info of how cypress folder files are organized, purpose and how to get started. **(see notes for reviewers and gif below)**

This PR fixes #5211

**Notes for Reviewers**
**The labeler commenter for PRs matching component/ui change so it includes a hyperlink to this section of the docs is included**

CleanShot 2022-05-21 at 22 03 37

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 927ec1f5a4343210026adceb6c7380d4b758488b at: https://6289a953618f47070d11dd5d--meshery-docs-preview.netlify.app

**Comment by leecalcote** [comment]
Most excellent, @MarioArriaga92.

**Comment by leecalcote** [comment]
Tossed in a few updates for your consideration.

**Review by leecalcote — DISMISSED** [review]

**Comment by l5io** [comment]
🚀 Preview for commit cfefa0a7c190a83ab288d3666f3cfcc53faacc49 at: https://628fcd4ac9cbfe0e291cd63c--meshery-docs-preview.netlify.app

**Comment by MarioArriaga92** [comment]
LGTM @leecalcote, only pending thing is the update the labeler commenter for PRs to include hyperlink - let me give it a try

**Comment by l5io** [comment]
🚀 Preview for commit be4de44514522e5d5068fd90656ad084cb351dc3 at: https://628fdaab4f80711a942d2c7c--meshery-docs-preview.netlify.app

**Review by Abhishek-kumar09 — APPROVED** [review]
LGTM

**Pull request merged**
