### PR TITLE
[UI] Formatted json data into design card

### LINKED ISSUE #12220: [UI] Make the json data foramtted into design card
### Current Behavior
When we click on the design card on the design page there is raw json data.

### Desired Behavior
Converted into formatted JSON data.

### Screenshots/Logs
image

### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by kingdarabahmad**
**Notes for Reviewers**

This PR fixes #12220

ScreenShot1: Not FullScreen
Screenshot 2024-10-16 at 5 27 09 PM

ScreenShot2: FullScreen Mode
Screenshot 2024-10-16 at 5 27 20 PM

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by amitamrutiya** [comment]
don't formate yaml data that we show. Some pattern file have the json data and some have a yaml one so make yaml one formatted.
image

**Comment by vishalvivekm** [comment]
@kingdarabahmad 
Thank you for your contributions! Let's discuss this during the Meshery Development call today at 9:00 AM CT | 7:30 PM IST. Adding it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit?pli=1#) || [meeting link](https://meet.layer5.io/meshery).

**Comment by leecalcote** [comment]
@amitamrutiya, do we have a ✅ from you here or are there additional changes / feedback needed?

**Review by amitamrutiya — CHANGES_REQUESTED** [review]

**Review by amitamrutiya — APPROVED** [review]

**Comment by amitamrutiya** [comment]
Thanks @kingdarabahmad for fix this issue.

**Pull request merged**
