### PR TITLE
Fix user pref tabs UI

### LINKED ISSUE #3936: [UI] User Prefs: Only display remote provider tab when user signs into a remote provider.
#### Current Behavior

This screenshot is of a user using the Local Provider (None). They should not see the Remote Provider tab.
Screen Shot 2021-08-18 at 7 30 22 PM

The labels on the tabs should be responsive and should not be cut off.

Screen Shot 2021-08-18 at 7 34 53 PM

#### Desired Behavior
In `/user/preferences`, the Remote Provider tab should only be shown when the user is connected to a Remote Provider.

#### Environment

- Browser: Safari
- Host OS: Mac
- Meshery Server Version: stable-v0.5.48

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by ghost**
**Description**
- Show remote provider only when remote provider is used otherwise hide it.
- Fix tab and their labels to be responsive.

This PR fixes #3936

### CODE REVIEW

**Comment by sudo-NithishKarthik** [comment]
https://user-images.githubusercontent.com/75248557/130205945-a79b0e46-b416-4a0f-8bb3-7eb43dd57a2d.mov

I still see the `Remote Provider` tab 🤔 , @yagarwal1307

**Review by sudo-NithishKarthik — COMMENTED** [review]
When using the `None` provider, `Performance` tab does not have any content in it.

Screenshot 2021-08-20 at 2 26 51 PM

**Comment by sudo-NithishKarthik** [comment]
@leecalcote , should we actually show the `performance` tab in case of local provider, considering the fact that we would be persisting it in the remote provider in the future ?

**Review by warunicorn19 — CHANGES_REQUESTED** [review]
Screenshot 2021-08-20 at 2 58 04 PM

While @sudo-NithishKarthik points out the important stuff, i'll nitpick a little, is there a reason why theres this line? if its insignificant please remove it.😃

**Comment by yagarwal1307** [comment]
@sudo-NithishKarthik Ahhhhh, stupid mistake! Nice catch btw! Fixing it just 2 minutes.

@warunicorn19 I don't know about the line, this was already there, must be the border. Looked cool to me so I just left it there :P. For now I am setting the width of enclosing container 100% that would fix it!

**Comment by warunicorn19** [comment]
For some reason there is a little lag when remote provider is clicked, the lag was longer when i opened it the first time.


https://user-images.githubusercontent.com/53532328/130230999-982accd3-f5a6-431c-9838-7c8535419301.mov

**Comment by yagarwal1307** [comment]
@warunicorn19 I don't know in my case remote provider tab is empty! Also I am pretty sure it is not because of the changes I made or is it? (If you think it is please tell me the potential reason, I dont think its because of me)

But I think I can guess the reason!

According to me it is happening because of the nature of how react works.
If you go check ExtensionSandbox component you will find that everytime this tab is rendered useEffect is called and useEffect is called once the code has already been rendered. So what might be happening is that before data is fetched since you have nothing in data nothing is shown. But once useEffect is called, you get data and it gets re rendered. Hence the case!

**Review by warunicorn19 — APPROVED** [review]
No no, even i dont think its because of the changes you've done😅. i was just wondering. i guess what you said makes sense and that's probably the cause. Thanks!

All looks good to me🎉, thanks for this @yagarwal1307 .
@sudo-NithishKarthik would you like to add anything else?

**Comment by yagarwal1307** [comment]
@warunicorn19 the issue was the same as I was referring to. In the extensionSandbox.js when no data is available we are rendering null. I replaced that null with 'hello' and you can see the result. Please check the video below.
https://user-images.githubusercontent.com/49173018/130235508-7c46f114-51f7-4113-904d-3c09d64c9f15.mp4

Also I have observed this same thing in a lot of places in the code base and we should use some placeholders in all those places. It will improve the ui significantly.

**Comment by yagarwal1307** [comment]
Also one more thing making the request for same data again and again does not make any sense in the first place in this case. For this I think we should rather use redux or something and just fetch the data once!

**Comment by warunicorn19** [comment]
@yagarwal1307 good catch. Something to think about. If you'd like you can add it to the agenda of our community meeting and we can discuss this at length there.

**Comment by yagarwal1307** [comment]
sure @warunicorn19 I will do that.

**Comment by sudo-NithishKarthik** [comment]
@yagarwal1307 , Thank you for fixing it.

> For some reason there is a little lag when remote provider is clicked, the lag was longer when i opened it the first time.

Yes, @yagarwal1307 is right, the reason for the delay in the content to appear is because of the fact that `null` is being rendered until the data is received from the network request which fetches provider capabilities and also partly because of the fact that it is an extension point of Meshery, which loads the component each time you go to the tab. We should definitely use a progress bar or something instead. Can any of you guys open an issue for it ? @yagarwal1307  or @warunicorn19 .

> Also one more thing making the request for same data again and again does not make any sense in the first place in this case. For this I think we should rather use redux or something and just fetch the data once!

There is an open proposal for this which addresses this issue among the others, we will be switching to Redux based architecture real soon 🚀 .

**Comment by warunicorn19** [comment]
@yagarwal1307 please go ahead and create the issue😃.

**Comment by yagarwal1307** [comment]
cool! Doing that

**Review by sudo-NithishKarthik — APPROVED** [review]

**Comment by sudo-NithishKarthik** [comment]
Thank you @yagarwal1307 , for you valuable contributions 🎉

**Pull request merged**
