### PR TITLE
[Lifecycle] Installation: Move away from git.io

### LINKED ISSUE #5430: [Docs] git.io deprecation
#### Current State
Meshery uses `git.io` shortened URLs in its docs. `git.io` service has been deprecated and the redirections are supposed to stop working from 29th April.

More info: https://github.blog/changelog/2022-04-25-git-io-deprecation/

#### Desired State
Replace `git.io` based links.

---

#### [Contributor Guides](https://docs.meshery.io/project/contributing) and Resources
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by leecalcote**
Signed-off-by: leecalcote <leecalcote@gmail.com>

**Description**

This PR fixes #5430

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit b9ac6ad85b93b03139625143af941fa824001c93 at: https://62686f93d7009d0524038169--meshery-docs-preview.netlify.app

**Review by utkarsh-pro — APPROVED** [review]
LGTM

**Comment by leecalcote** [comment]
Thank you, gents.

**Comment by l5io** [comment]
🚀 Preview for commit 1ba260b322006db4461f94dfbcb5aace72b360fc at: https://626971c6ffe86606466134c6--meshery-docs-preview.netlify.app

**Pull request merged**
