### PR TITLE
[UI] Provider UI bug fix

### LINKED ISSUE #5966: [Provider UI] Vertical scrollbar should be hidden.
#### Current Behavior
Recently, the vertical scrollbar shows in the Provider UI. The body/div background seems to be no longer full bleed.

#### Desired Behavior
The off-white background should cover the entire page. The scrollbar should not be visible.

#### Screenshots/Logs
Screen Shot 2022-08-04 at 5 12 02 PM

#### Environment

- Browser: Chrome and Safari

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by Chadha93**
Signed-off-by: Gaurav Chadha <gauravchadha1676@gmail.com>

**Description**
Removes unwanted scrollbar/margin from the provider UI.

This PR fixes #5966 

**Notes for Reviewers**

Provider-fix
Postmortem Report: It was due to user-style agents being exposed internally may be due to some dependency issues.
**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Chadha93** [comment]
@legendarykamal you might want to review this since you were working on this I guess.

**Comment by Chadha93** [comment]
@leecalcote. This one is also KO (Knocked out).

**Review by leecalcote — APPROVED** [review]
Thank you!

**Comment by legendarykamal** [comment]
Ah @Chadha93 man you are great 👍
I have messed couple of hours on this finding out 🔍 and trying different things to achieve the result 🧐. Good good.

**Pull request merged**
