### PR TITLE
Edited repository overview link

### LINKED ISSUE #6653: [Docs] Replace Google Doc link with link to web page
#### Current State
The Layer5 repository overview doc (https://docs.google.com/document/d/1brtiJhdzal_O6NBZU_JQXiBff2InNtmgL_G1JgAiZtk/edit#) is linked to in various places (readmes, docs, and so on).

#### Desired State
1. Replace the Gdoc link with this web page link - https://layer5.io/community/handbook/repository-overview.
2. Remove "Layer5" in the link description, changing it to "Layer5 Repository Overview".

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by BabyElias**
Signed-off-by: Anoushka Jha <95405559+BabyElias@users.noreply.github.com>

**Notes for Reviewers**

This PR fixes #6653 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 455e9ecfc5a2e6c777a04b11c1df10671641d158 at: https://6393116c3e70ef2110ad75a5--meshery-docs-preview.netlify.app

**Comment by leecalcote** [comment]
Thanks. In what other locations did you find the link?

**Comment by BabyElias** [comment]
> Thanks. In what other locations did you find the link?

image
Generated [PR #6663](https://github.com/meshery/meshery/pull/6663) for the same

**Comment by leecalcote** [comment]
Understood. Thank you. Although, I'm wondering where else you might have discovered this link. Surely, this isn't the only one, is it?

**Comment by BabyElias** [comment]
> Understood. Thank you. Although, I'm wondering where else you might have discovered this link. Surely, this isn't the only one, is it?

Went through readmes of all given repos, and pages on the meshery.io site. Overall, these were the only two places where I found the link being used. Should I go through the website again?

**Comment by l5io** [comment]
🚀 Preview for commit 4dc3828c8840cf12c5e99ded4b10e07d17a9c02a at: https://639402f425a7ad465cb64e32--meshery-docs-preview.netlify.app

**Pull request merged**
