### PR TITLE
fix: ui-integration tests are unable to start

### PR DESCRIPTION
**Pull request by Abhishek-kumar09**
Signed-off-by: Abhishek kr <abhimait1909@gmail.com>

**Notes for Reviewers**

This PR fixes #

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Abhishek-kumar09** [comment]
re-running

**Comment by Abhishek-kumar09** [comment]
https://github.com/meshery/meshery/blob/b8fabef0d658c95fd14ed9666df7d13ce91bf47b/ui/README.md#L13 😕

**Comment by MarioArriaga92** [comment]
> https://github.com/meshery/meshery/blob/b8fabef0d658c95fd14ed9666df7d13ce91bf47b/ui/README.md#L13
> 
> 😕

This might've been applicable when current LTS version of node came with npm v6 by default, we're going to have to check if it still holds true.

**Comment by MarioArriaga92** [comment]
There's still a problem with UI end-to-end tests failing on setting none provider (500 error with "Unexpected issue." in response body to `GET http://localhost:3000/api/provider?provider=None` request through cypress) but this PR LGTM as it fixed several other problems.

**Review by MarioArriaga92 — APPROVED** [review]
There's still a problem with UI end-to-end tests failing on setting none provider (500 error with "Unexpected issue." in response body to GET http://localhost:3000/api/provider?provider=None request through cypress) but this PR LGTM as it fixed several other problems.
CleanShot 2022-11-28 at 15 25 27@2x

**Comment by leecalcote** [comment]
@Revolyssup is this related to changes the security of Meshery APIs?

**Comment by Revolyssup** [comment]
> @Revolyssup is this related to changes the security of Meshery APIs? --> #6440

No. 500 is not related to that change. That change only results in 401, if there's an issue.

**Pull request merged**
