### PR TITLE
[UI] Migration of  Error Boundary to functional component from Class based component

### LINKED ISSUE #12118: [UI] Migrate Error Boundary to Functional Component and Use MUI v5 supported Sistent component
### Current Behavior

This [ErrorBoundary](https://github.com/meshery/meshery/blob/268c1667a6ab6a8bbdcbd960df20023d8ecbfb3a/ui/components/ErrorBoundary.js#L9) Component is a `class-based` component and it uses MUI v4's `Box` component. These need to be updated for improved performance and consistency.

### Desired Behavior

- [ ] migrate class-based component to a functional component
- [ ]  add a Sistent Button component needs to be used

### Acceptance Tests
 The component must be updated without introducing any breaking changes in functionality or theming across all instances where it is used.

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by THEBOSS0369**
This PR fixes #12118

**Notes for Reviewers**

Hello !

In this PR, I have migrated the `Error Boundary` Component to `function Component` from `Class Based` Component. Updated error handling logic to use React hooks.

Note: This PR does not migrate the button as it has already been done by someone.

Thanks !

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by vishalvivekm** [comment]
@THEBOSS0369 
Thank you for your contributions! Let's discuss this during the Meshery Development call today at 9:00 AM CT | 7:30 PM IST. Adding it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit?pli=1#) || [meeting link](https://meet.layer5.io/meshery).

**Comment by sudhanshutech** [comment]
@THEBOSS0369 the eslint check is failing

**Review by sudhanshutech — CHANGES_REQUESTED** [review]
We don't need to use the existing error boundary @THEBOSS0369 we can directly use the error boundary component direct from sistent. // @SAHU-01

**Comment by THEBOSS0369** [comment]
The next changes is done on this PR #12439

**Pull request closed without merging**
