### PR TITLE
READ-ME Updated with 4.1 release notes 

### PR DESCRIPTION
**Pull request by accordingtoherr**
Updated the Read.ME to include notes from 4.1 release. Please note, I wanted to also get the 4.2 one done but the link provided in that issue was only for 4.1. 

- I only updated lines 64-66 with the release name, link to the notes/contributors (mirroring others), and a bullet point listing the main change

- Emily

### CODE REVIEW

**Comment by leecalcote** [comment]
Excellent! Thank you, @accordingtoherr. 👍

**Comment by leecalcote** [comment]
Fixes https://github.com/layer5io/meshery/issues/1593

**Review by PluckyPrecious — CHANGES_REQUESTED** [review]
Hey @accordingtoherr well-done😊, I think it will look good if you follow the steps used in writing other releases notes.
* Release date should be this - 8 August 2020
* The bullet point should be under 
```
**What's new ?**
- Documentation
   + CONTRIBUTING.md typo and error fixes

```
  No need adding the contributor or PR number.

* Also, check this out https://github.com/layer5io/meshery/pull/1595/checks?check_run_id=1140659936 to help amend your DCO sign-off. 👌🏽

**Review by Ruth-ikegah — CHANGES_REQUESTED** [review]
Hi, @accordingtoherr Nice work on taking this. As @PluckyPrecious has mentioned on this, please effect these changes. In case you have any issues, you can send a message on slack

**Comment by accordingtoherr** [comment]
@PluckyPrecious just fixed it! =]

**Review by leecalcote — APPROVED** [review]
Looking good, @accordingtoherr. 👍

**Comment by kushthedude** [comment]
Great work @accordingtoherr 🎉

**Pull request merged**
