### PR TITLE
Pattern Configurator: Fix issues with PAtternConfigurator

### PR DESCRIPTION
**Pull request by Abhishek-kumar09**
**Description**
Fix problems and add the pathway to the pattern configurator

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — CHANGES_REQUESTED** [review]
@Abhishek-kumar09 there's a merge conflict to address.

**Comment by Abhishek-kumar09** [comment]
@leecalcote 
Working on the items from the last meeting.
fixed minors
- prettified string
- breadcrumbs for navigation
- some other functionality fixes

- meshmap Styles are not 100% same as this. WIll  be working on same. But this PR up to this change looks fine. Will be completely doing it in future.


image

**Comment by leecalcote** [comment]
@utkarsh-pro  will you comment on the traits concern?

**Comment by leecalcote** [comment]
@Abhishek-kumar09 is this ui build failure specific to your PR? https://github.com/meshery/meshery/runs/4296106694?check_suite_focus=true#step:5:106

**Comment by utkarsh-pro** [comment]
@Abhishek-kumar09, yes traits are still very much relevant and their relevance should increase in the future.

**Pull request merged**
