### PR TITLE
add: Relationship between csi-driver and other k8s resources

### PR DESCRIPTION
**Pull request by RipulHandoo**
**Notes for Reviewers**

This PR fixes #
1. Relationship between CSI  driver and other k8s resources.

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by RipulHandoo** [comment]
@MUzairS15 @leecalcote This PR is ready to merge and It's working as expected.

Uploading CSI DRIVER.mp4…

**Comment by leecalcote** [comment]
Thank you for this video capture. A merge conflict popped up.

**Comment by leecalcote** [comment]
@RipulHandoo @MUzairS15, I wonder at what point we should be splitting these relationship definitions into separate files...

**Comment by RipulHandoo** [comment]
> Thank you for this video capture. A merge conflict popped up.

@leecalcote Merge conflicts will come every time as these changes are happening in a single file.

**Comment by leecalcote** [comment]
This is in part the logic behind my question.

**Comment by leecalcote** [comment]
You can avoid this by editing a different section of the file, not perpetually the end of the file.

More to my point, though, is us defining a contributor convention in which we articulate a guideline of one `from` per relationship definition - just as a convention, not a hard rule.

**Comment by MUzairS15** [comment]
Updated mutatedRef from `csi.driver.name` to `csi.driver`

**Review by MUzairS15 — APPROVED** [review]
Thanks

**Pull request merged**
