### PR TITLE
[Docs] Release Notes for Meshery v0.5.37

### PR DESCRIPTION
**Pull request by l5io**
An auto-generated pull request to document release notes for Meshery v0.5.37

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 46186308d323aea4470191c5a3f953272c53a094 at: https://60eb0495a46931adaf27b616--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit d86b254f415e15d1bfe6bce5f713a05b59303537 at: https://60eb92b13d6d3f3fd456ffd1--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 2d87072fd340fa7a2556875273d2461577f3e2e8 at: https://60eb93fda4693149e02860ac--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit d3e2d6fa11fd696008567646abe3dcc8d15f5ec0 at: https://60eb988eaf97d67e347461f2--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 8a502d59216b2fdf852e1744374ca5ce9631e785 at: https://60ec168add0de6cfe05879e5--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 8b0bc6d85d09ad8d390aa228ae36fc450c93b340 at: https://60ec5c94af97d6632074664c--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 5ae7c2921ff584ce9f11039c3a5b68829ca77d93 at: https://60ec8ecca469316b1127b6f0--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit cbd4532ec5023f0ded452d0c1e19180aa4f0d0f1 at: https://60ed8d35e43dfb39b5125640--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 9e184e421cb290ac03b387ea7391925ad5f991ad at: https://60edbbff3c963515460f0e19--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit ac3dcfe388c592f422d0fa37f791f54749b853b0 at: https://60edd8a92724e93536dd815e--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 55f7e7e5e59bec300694206ed2892b83541056c5 at: https://60ede8f62724e94a9bdd8177--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 85c0e9ecad55447b397808e072fbd0c209a26f70 at: https://60edea3bfeb2084b75989427--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit dfe5653aae812c117f8ffbedd3d0ebd5db1ff5e1 at: https://60edeb39dca7824be1830767--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 38e4dde375fa3ba8c39ce2ef635e52530ba47232 at: https://60edefd8b58d9d4f1e9247d5--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 92a5a09cee05c6da7c94c16cd968b0abf1e1d904 at: https://60edf8313c963562840f0d08--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit fe2352528b0be63c926c6e0dd757f00194f6c664 at: https://60edf8ef3c963564a21023d4--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 74be9ca827997da5059cf42231e18944da81007f at: https://60ee6a6f46370bdd5ce79209--meshery-docs-preview.netlify.app

**Review by kumarabd — APPROVED** [review]

**Pull request merged**
