### PR TITLE
feat: relationship between CSI drive and other k8s components

### PR DESCRIPTION
**Pull request by RipulHandoo**
**Notes for Reviewers**
1. RelationShip between k8s CSI Driver and other resources.

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by saurabh100ni** [comment]
Hi @RipulHandoo 
Thanks for your PR! I encourage you to share this in the Meshery Development Meeting tomorrow at 8:30 PM IST. Share your screen, and walk us through it. It's cool to take and share feedback. Check the [Doc](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit) here to include this PR.

You're welcome at the meeting

Check to [community calendar](https://layer5.io/community/calendar) for more details of meetings at Layers.

**Review by MUzairS15 — COMMENTED** [review]
Pod to CSIDriver with 2 binding comps in between.
@RipulHandoo Define this visual representation in detail.
Right now we only support one binding in between, but if it's valid and makes sense we can update the support.

**Review by MUzairS15 — COMMENTED** [review]
@RipulHandoo thanks, Will you drop in a video where you again create existing (network/mount/permission) relationships so that we are covered fully?

You may also want to showcase the working of new relationships defined in this PR.

**Comment by RipulHandoo** [comment]
@MUzairS15 In the video, I've added all the relationships for which I raised a PR. However, I manually added the values for now.
https://github.com/meshery/meshery/assets/107461226/42d2800b-d652-43cc-8656-57db0d843e23

**Comment by l5io** [comment]
🚀 Preview for commit 60c858f0d778d11197770a659814d318c3025010 at: https://65c688b051894309b25e5870--meshery-docs-preview.netlify.app

**Review by MUzairS15 — COMMENTED** [review]
@RipulHandoo This PR and https://github.com/meshery/meshery/pull/10262/files.
We only need one, right?
I think this is accidental.

**Comment by RipulHandoo** [comment]
> @RipulHandoo This PR and https://github.com/meshery/meshery/pull/10262/files. We only need one, right? I think this is accidental.

Yes, this pr got corrupted.

**Pull request closed without merging**
