### PR TITLE
[Meshery-Extension] setup single source of truth for svgs

### PR DESCRIPTION
**Pull request by Abhishek-kumar09**
Signed-off-by: Abhishek kr <abhimait1909@gmail.com>

**Description**
- Adds up the component svgs to be used by meshery as well as meshery-extension under a static file host.
This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Abhishek-kumar09** [comment]
Depends on https://github.com/meshery/meshery/pull/5885

**Review by leecalcote — CHANGES_REQUESTED** [review]
Things like the `cluster-role.svg` will need two versions: one without the shape (circle, which should be a rounded rectangle) and one with the shape.

**Comment by Abhishek-kumar09** [comment]
> Things like the `cluster-role.svg` will need two versions: one without the shape (circle, which should be a rounded rectangle) and one with the shape.

Hmmm, Okay. This PR don't has the cluster role changes. I think @Harshit-Dandriyal is tracking that in his seperate branch. So the svgs can be added and chosen.

**Comment by Abhishek-kumar09** [comment]
For now merging this PR, since it has some crucial changes wrt visualiser fixes.

**Pull request merged**
