### PR TITLE
[meetings] Created NewComers meeting attendence folder

### LINKED ISSUE #12011: [Docs] Create Newcomer's meeting attendance folder for the week of 09/30/2024
### Current Behavior
As a project, we track attendance to the weekly Newcomers meeting under the [_meetings directory](https://github.com/meshery/meshery/tree/master/docs/_meetings). It’s important that each newcomer both feel at ease in the community, and also, comfortable with the process of contributing (in this particular case, using git). 

### Desired Behavior
Each meeting attendee creates attendance record (a file with their name in the filename or their name in the content of the file) in the _meeting directory. The format of this file doesn't matter. What's important is that the attendee get into the groove of git-based contribution.

### Implementation
1. Create a new directory under the [_meetings directory](https://github.com/meshery/meshery/tree/master/docs/_meetings), entitled "week-of-<mm/dd/yyyy>", replacing mm/dd/yyyy the date for the start of the week. This new, empty directory will serve as the landing spot for attendance records.

### Acceptance Tests
1. A new directory is present and is NOT listed as dd/mm/yyyy, but as mm/dd/yyyy.

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by kingdarabahmad**
**Notes for Reviewers**

This PR fixes #12011

- Created a new directory `week-of-10-14-2024` under the `_meetings` directory for weekly Newcomers meeting attendance.
- The directory follows the required format (mm/dd/yyyy) for the start of the week.

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — CHANGES_REQUESTED** [review]
Thanks. Revert your changes to the Gemfiles, please.

**Comment by l5io** [comment]
🚀 Preview for commit a16a79897ac5b62e2ae77e44a702dd8cea7282cc at: https://670e075368d03ef80be9dbfe--meshery-docs-preview.netlify.app

**Comment by kingdarabahmad** [comment]
@leecalcote i have successfully pushed the requested changed to the PR

**Review by leecalcote — CHANGES_REQUESTED** [review]
Not quite. Your Gemfile.lock change is still included.

**Comment by l5io** [comment]
🚀 Preview for commit e460fbde22efc7a134cc5cbeee93b458c8fefdc5 at: https://670e50c6acc9ac391d6530e0--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit dc77c6a9e028e9a6829556d6e87eb41bc0790285 at: https://670e53c076e3ddb1b323dac5--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 5bd2e4e65fcda7e1c3f6d8f94f2c5e8816e73bcd at: https://670e59cde3e68cbd95d00dfd--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 319ef1dd9e9385ae33a642d16f1e03866f05ad65 at: https://670e60ad1fbea4719ebc121b--meshery-docs-preview.netlify.app

**Pull request merged**
