### PR TITLE
[Draft] ARM support for Meshery

### PR DESCRIPTION
**Pull request by lolverae**
**Notes for Reviewers**

This PR fixes https://github.com/meshery/meshery/issues/6308

Keep in mind 2 things:
- The LuaJIT version compatible with ARM is still a beta, however this shouldn't conflict with the original amd64 image (at least experimental ARM support for Meshery images would be possible)
- I raised a PR to the glibc image from frolvlad but until my changes are merged I provisionally used my own forked image https://hub.docker.com/r/lolverae/alpine-glibc, here you can find the Dockerfile used: https://github.com/lolverae/docker-alpine-glibc 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Chadha93** [comment]
@lolverae  Let's discuss this on the Meshery Dev call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#) if you would. :)

**Comment by leecalcote** [comment]
👀

**Comment by Chadha93** [comment]
@lolverae Thank you for showing up on the last call. Let's discuss the progress and get this merge. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#) if you would. :)

**Comment by acald-creator** [comment]
@lolverae Can you provide an update on this? This would be great to be merged into Meshery, as I have a Mac with m1 chip, and it would be great to continue developing on my Mac.

**Comment by lolverae** [comment]
Hey, @acald-creator 
Currently, I'm working on compiling glibc manually on an ARM VM, which I'll be using in the final base image for the server.
I've encountered a few challenges along the way, but I'm continuing to work through them and hope to have a successful build soon. Thanks for your patience and support as I work on this.

**Pull request closed without merging**
