### PR TITLE
[Lifecycle] Helm: Update container image repo with the correct location

### LINKED ISSUE #2962: Replace the image repo with the right address
https://github.com/layer5io/meshery/blob/a17afc78f1c3abc81f760bac67f953dc95ca5cb0/install/kubernetes/helm/meshery/values.yaml#L9

### PR DESCRIPTION
**Pull request by nakul-shahdadpuri**
**Description**

This PR fixes #2962

**Notes for Reviewers**
Replaced the image repo with the right address as directed in the comments. :)

**[Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
@nakul-shahdadpuri will you execute these commands in order to sign-off on your commit? https://github.com/layer5io/meshery/pull/2973/checks?check_run_id=2609990531

Thanks!

**Review by leecalcote — APPROVED** [review]
LGTM

**Comment by samirparhi-dev** [comment]
On it .

**Comment by samirparhi-dev** [comment]
The correction is reflecting now. Fine for me .

```samirparhi@Samirs-Mac Downloads % k describe pod meshery-67d7ddbc8-w72r9  -n meshery
Name:         meshery-67d7ddbc8-w72r9
Namespace:    meshery
Priority:     0
Node:         aks-k8sstaging-29265774-vmss000001/10.240.0.5
Start Time:   Wed, 19 May 2021 11:21:58 +0530
Labels:       app.kubernetes.io/instance=meshery
              app.kubernetes.io/name=meshery
              pod-template-hash=67d7ddbc8
Annotations:  <none>
Status:       Running
IP:           10.244.5.41
IPs:
  IP:           10.244.5.41
Controlled By:  ReplicaSet/meshery-67d7ddbc8
Containers:
  meshery:
    Container ID:   docker://5cbba99eea2f01265ff70f5445f72b3684468bd5d57a393d5306fe055e200b7c```
    Image:          layer5/meshery:stable-latest
    Image ID:       docker-pullable://layer5/meshery@sha256:5314eea136c1b41f058be22235e17e8bf2bc797246309607383824e989a65183
    Port:           8080/TCP
    Host Port:      0/TCP
    State:          Running
      Started:      Wed, 19 May 2021 11:23:09 +0530
    Ready:          True
    Restart Count:  0
```

**Review by samirparhi-dev — APPROVED** [review]
LGTM

**Review by leecalcote — APPROVED** [review]
Thank you, gents. 👍

**Comment by leecalcote** [comment]
yay, @nakul-shahdadpuri! 🎈

**Pull request merged**
