### PR TITLE
[Docs] Updated FAQ for design invisibility issues in catalog

### PR DESCRIPTION
**Pull request by saurabh100ni**
**Notes for Reviewers**
Updated [FAQ section](https://docs.meshery.io/project/faq) in Meshery Docs addressing Image invisibility issues due to low bandwidth.

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit c87bba047c5f82b893a417e0cce094d2e775727e at: https://6586e55538826a8c51269a34--meshery-docs-preview.netlify.app

**Review by goldfishdolphin — APPROVED** [review]
Looking Good 👍🏽

**Review by leecalcote — COMMENTED** [review]
Thanks. This is not a location that anyone browsing the catalog will look to.

**Comment by leecalcote** [comment]
@vishalvivekm

**Comment by l5io** [comment]
🚀 Preview for commit 3acdeb0346a4e24d1a83aebc7450c44ab6ef05f0 at: https://65955144f3e4e6995f7cbf45--meshery-docs-preview.netlify.app

**Review by leecalcote — CHANGES_REQUESTED** [review]
https://github.com/meshery/meshery/pull/9704#pullrequestreview-1797670317

**Comment by l5io** [comment]
🚀 Preview for commit c23958ae6cd45af63e11f9ae6c82324204062e04 at: https://65a57a50a2c4041d52234543--meshery-docs-preview.netlify.app

**Comment by MUzairS15** [comment]
@saurabh100ni @vishalvivekm @iArchitSharma

**Review by leecalcote — APPROVED** [review]

**Pull request merged**
