### PR TITLE
Allow getting entities by ids

### PR DESCRIPTION
**Pull request by Yashsharma1911**
**Notes for Reviewers**

This PR fixes #

This PR update entities API to have `id` params, which allows to fetch entity like models, components and relationship by id

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by Yashsharma1911** [comment]
This PR depends on new release of meshkit

**Comment by Yashsharma1911** [comment]
// @amitamrutiya

**Comment by amitamrutiya** [comment]
@Yashsharma1911 for these two I still have to pass the modal name because the modal name is a variable, not an argument that we are passing.

`GetAllMeshmodelRelationships`
`GetMeshmodelComponentByModel`

**Comment by Yashsharma1911** [comment]
> @Yashsharma1911 for these two I still have to pass the modal name because the modal name is a variable, not an argument that we are passing.
> 
> `GetAllMeshmodelRelationships` `GetMeshmodelComponentByModel`

Ohh I see I missed those once I guess, you can simply make changes to those functions similar to this PR

**Pull request merged**
