### PR TITLE
fix: ci issues in ui

### PR DESCRIPTION
**Pull request by kushthedude**

### CODE REVIEW

**Comment by kushthedude** [comment]
@leecalcote @ramrodo, This PR fixes whatever issues you had with caching in the past. The test failure is due to the error in the tests which may have been missed out since our CI for UI was inactive for couple of days.

**Review by leecalcote — APPROVED** [review]
I was just looking over the failed build issues in @ramrodo's e2e PR.

Thanks for this, @kushthedude

**Comment by leecalcote** [comment]
I wonder where gonum went. https://github.com/layer5io/meshery/pull/2192/checks?check_run_id=1634429603#step:3:1596

**Comment by kushthedude** [comment]
> I wonder where gonum went. https://github.com/layer5io/meshery/pull/2192/checks?check_run_id=1634429603#step:3:1596

Gonum package is giving 500 for a while, must be a flake. Should be fixed on its own by tomorrow, I hope.

**Comment by leecalcote** [comment]
Ok, yes, hopefully. Like you say, it's causing failures in other builds, too.

**Pull request merged**
