### PR TITLE
mesheryctl: mesheryctl set kubeconfig

### LINKED ISSUE #112: Verify Meshery compatibility with GKE
Install Meshery locally. Point to GKE cluster. Update documentation based on experience.

Tasks:

1. Install Meshery locally. (using Meshery cli which runs all the services on `Docker` using `docker-compose`)
2. Open Meshery UI.
3. Configure Meshery to use kubeconfig for GKE deployment. [using the kubeconfig file mostly found in your $HOME/.kube/config (OR) by getting the config from `kubectl config view --raw > config` command]
3. Deploy each supported service mesh & a sample app in that environment using Meshery.
4. Performance test each supported service mesh in the environment using Meshery.
5. Update documentation with changes needed.

### LINKED ISSUE #146: Generate cluster access for public clouds(GKE/EKS) via mesheryctl
**Is your feature request related to a problem? Please describe.**
It would be nice via mesheryctl generate cluster access for public clouds:
```
https://github.com/layer5io/meshery/issues/102
```
**Describe the solution you'd like**
Need to translate this shell script to be part of mesheryctl:
```
https://github.com/layer5io/meshery/issues/102#issuecomment-491261460
```

**Describe alternatives you've considered**
Depending on use case, we can consider to use existing service account.

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by kanishkarj**
**Description**

Currently, this PR configures meshery with the kubeconfig based on the options provided by the user. 

This PR fixes #146 

#####  How to test?
* from meshery, download the token() by clicking the "Get Token" item in the dropdown.
* for testing GKE, configure your `kubectl` to point to the cluster.
* check if it's working by running `kubectl get all`,
* build mesheryctl and run :
```shell
./mesheryctl system config gke --token "PATH TO TOKEN"
```

#### Checklist

- [] [Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin).
- [] PR title includes `[<name of area>]:<description>`
- [x] minikube
- [x] GKE
- [x] EKS
- [ ] any more?

### CODE REVIEW

**Comment by kanishkarj** [comment]
@leecalcote could you give it a run?

**Comment by leecalcote** [comment]
@kanishkarj we can toss AKS onto the list (if you have this access).

**Comment by kanishkarj** [comment]
I'll fix the merge conflicts too.
I don't have an account in AKS though. Also, can we use the script to auth into the Kubernetes service of any cloud provider?

**Comment by kanishkarj** [comment]
Another feature you might want to check is when there are multiple contexts Mesheryctl lists them, and the user can choose which one to register with.

**Comment by leecalcote** [comment]
@nitishvu and @chandresh-pancholi what do you think?

**Comment by chandresh-pancholi** [comment]
I will take a look.

**Comment by nitishvu** [comment]
@kanishkarj  and @leecalcote 

looks good.
we can use all functions in `ScriptGKE()` for EKS.
Next time we can add these(create_service_account, get_secret_name_from_service_account)  to common lib so that we can use it for other managed k8's.

Also this file `mesheryctl/kubeconfig.yaml` has working k8 details do we need this?

@kanishkarj  you can find EKS related steps here `https://meshery.layer5.io/docs/installation/eks`
maybe in next PR if you don't have access to EKS I can test.

**Comment by kanishkarj** [comment]
@nitishvu Could you `./mesheryctl system config gke --token "PATH TO TOKEN"` on EKS directly then? if all the functions will work, then maybe the whole thing might work on it?

**Comment by nitishvu** [comment]
@kanishkarj 
I think it will work, I have some questions.
will ping you in slack

**Comment by leecalcote** [comment]
Kicking the build jobs...

**Comment by kanishkarj** [comment]
I'll fix these rightaway

**Comment by leecalcote** [comment]
> @kanishkarj we can toss AKS onto the list (if you have this access).
> 
> @kanishkarj you may want to have a look here - https://github.com/layer5io/meshery/pull/1084/conflicts

@scotty-c! If you have time to hop in, your eyes on this and perspective, will be most warmly welcomed.

**Comment by nitishvu** [comment]
Hi @kanishkarj 

code if working find for **EKS** and able to create service account.
its failing in `get_secret_name_from_service_account` because of `jq` command which is not present in my mac.
can you please try to use an existing command  like `awk` or use GO to parse the JSON

**Please find the below log.**

```
-n Creating target directory to hold files in /tmp/meshery/...
done-e 
Creating a service account in default namespace: sa-meshery-pbumrkrq
serviceaccount/sa-meshery-pbumrkrq created
clusterrolebinding.rbac.authorization.k8s.io/sa-meshery-pbumrkrq created
-e 
Getting secret of service account sa-meshery-pbumrkrq on default
sh: line 24: jq: command not found
Error generating config:exit status 127
```

**Comment by kanishkarj** [comment]
That makes sense, I shall shift the script to use `awk` maybe.

**Comment by kanishkarj** [comment]
@nitishvu Could you try it once after install `jq`? I shall work on other alternatives till then.

**Comment by leecalcote** [comment]
+1 for jq

**Comment by kanishkarj** [comment]
Imitating jq with awk is pretty hard. Jq is built for JSON parsing. Maybe when we implement the script in golang we can fix it.

**Comment by nitishvu** [comment]
yes executed with jq please find the below log.

```
$ ./mesheryctl system config gke --token ~/Downloads/auth.json 
-n Creating target directory to hold files in /tmp/meshery/...
done-e 
Creating a service account in default namespace: sa-meshery-lklmdgir
serviceaccount/sa-meshery-lklmdgir created
clusterrolebinding.rbac.authorization.k8s.io/sa-meshery-lklmdgir created
-e 
Getting secret of service account sa-meshery-lklmdgir on default
Secret name: sa-meshery-lklmdgir-token-rshpf
-e -n 
Extracting ca.crt from secret...
done-e -n 
Getting user token from secret...
done-e 
Setting current context to: aws
Cluster name: kubernetes
Endpoint: XXXXX
-e 
Preparing k8s-sa-meshery-lklmdgir-default-conf
-n Setting a cluster entry in kubeconfig...
Cluster "kubernetes" set.
-n Setting token credentials entry in kubeconfig...
User "sa-meshery-lklmdgir-default-kubernetes" set.
-n Setting a context entry in kubeconfig...
Context "sa-meshery-lklmdgir-default-kubernetes" created.
-n Setting the current-context in the kubeconfig file...
Switched to context "sa-meshery-lklmdgir-default-kubernetes".
-e 
All done! Test with:
KUBECONFIG=/tmp/meshery//kubeconfig.yaml kubectl get pods
you should not have any permissions by default - you have just created the authentication part
You will need to create RBAC permissions
NAME                              READY   STATUS      RESTARTS   AGE
details-v1-c5b5f496d-q9tv9        1/1     Running     0          17d
pi-5lkb7                          0/1     Completed   0          56d
pi-9p5sx                          0/1     Completed   0          56d
productpage-v1-7d6cfb7dfd-sz6vq   0/1     Pending     0          17d
ratings-v1-f745cf57b-h8brm        1/1     Running     0          17d
reviews-v1-85c474d9b8-zsdtk       0/1     Pending     0          17d
reviews-v2-ccffdd984-c7sjd        0/1     Pending     0          17d
reviews-v3-98dc67b68-5879h        0/1     Pending     0          17d
Error getting contexts : json: cannot unmarshal bool into Go value of type string
```

**Comment by kanishkarj** [comment]
Could you try it now @nitishvu ?

**Comment by nitishvu** [comment]
@kanishkarj    getContexts is failing

```
$ ./mesheryctl system config gke --token ~/Downloads/auth.json 
-n Creating target directory to hold files in /tmp/meshery/...
done-e 
Creating a service account in default namespace: sa-meshery-eoofxdav
serviceaccount/sa-meshery-eoofxdav created
clusterrolebinding.rbac.authorization.k8s.io/sa-meshery-eoofxdav created
-e 
Getting secret of service account sa-meshery-eoofxdav on default
Secret name: sa-meshery-eoofxdav-token-hsqj6
-e -n 
Extracting ca.crt from secret...
done-e -n 
Getting user token from secret...
done-e 
Setting current context to: aws
Cluster name: kubernetes
Endpoint: XXX
-e 
Preparing k8s-sa-meshery-eoofxdav-default-conf
-n Setting a cluster entry in kubeconfig...
Cluster "kubernetes" set.
-n Setting token credentials entry in kubeconfig...
User "sa-meshery-eoofxdav-default-kubernetes" set.
-n Setting a context entry in kubeconfig...
Context "sa-meshery-eoofxdav-default-kubernetes" created.
-n Setting the current-context in the kubeconfig file...
Switched to context "sa-meshery-eoofxdav-default-kubernetes".
-e 
All done! Test with:
KUBECONFIG=/tmp/meshery//kubeconfig.yaml kubectl get pods
you should not have any permissions by default - you have just created the authentication part
You will need to create RBAC permissions
Error getting contexts : json: cannot unmarshal bool into Go value of type string


```

**Comment by kanishkarj** [comment]
@nitishvu , Fixed the bug in JSON unmarshalling. Should work now!

**Comment by nitishvu** [comment]
@kanishkarj  working fine with new change.

```
$ ./mesheryctl system config gke --token ~/Downloads/auth.json 
-n Creating target directory to hold files in /tmp/meshery/...
done-e 
Creating a service account in default namespace: sa-meshery-htfyddiu
serviceaccount/sa-meshery-htfyddiu created
clusterrolebinding.rbac.authorization.k8s.io/sa-meshery-htfyddiu created
-e 
Getting secret of service account sa-meshery-htfyddiu on default
Secret name: sa-meshery-htfyddiu-token-gjwc8
-e -n 
Extracting ca.crt from secret...
done-e -n 
Getting user token from secret...
done-e 
Setting current context to: aws
Cluster name: kubernetes
Endpoint: XXXX
-e 
Preparing k8s-sa-meshery-htfyddiu-default-conf
-n Setting a cluster entry in kubeconfig...
Cluster "kubernetes" set.
-n Setting token credentials entry in kubeconfig...
User "sa-meshery-htfyddiu-default-kubernetes" set.
-n Setting a context entry in kubeconfig...
Context "sa-meshery-htfyddiu-default-kubernetes" created.
-n Setting the current-context in the kubeconfig file...
Switched to context "sa-meshery-htfyddiu-default-kubernetes".
-e 
All done! Test with:
KUBECONFIG=/tmp/meshery//kubeconfig.yaml kubectl get pods
you should not have any permissions by default - you have just created the authentication part
You will need to create RBAC permissions
NAME                              READY   STATUS      RESTARTS   AGE
details-v1-c5b5f496d-q9tv9        1/1     Running     0          18d
pi-5lkb7                          0/1     Completed   0          57d
pi-9p5sx                          0/1     Completed   0          57d
productpage-v1-7d6cfb7dfd-sz6vq   0/1     Pending     0          18d
ratings-v1-f745cf57b-h8brm        1/1     Running     0          18d
reviews-v1-85c474d9b8-zsdtk       0/1     Pending     0          18d
reviews-v2-ccffdd984-c7sjd        0/1     Pending     0          18d
reviews-v3-98dc67b68-5879h        0/1     Pending     0          18d
List of available contexts : 
(1) sa-meshery-eoofxdav-default-kubernetes 
(2) sa-meshery-htfyddiu-default-kubernetes 
(3) sa-meshery-msiedyax-default-kubernetes 
Enter choice: 3   
{"configuredServer":"XXXXXX","contextName":"sa-meshery-msiedyax-default-kubernetes","clusterConfigured":true,"server_version":"v1.14.9-eks-502bfb","nodes":[{"internal_ip":"XXXXX","hostname":"XXXXX","allocatable_cpu":"2","allocatable_memory":"7762960Ki","capacity_cpu":"2","capacity_memory":"7865360Ki","os_image":"Amazon Linux 2","operating_system":"linux","kubelet_version":"v1.14.7-eks-1861c5","kubeproxy_version":"v1.14.7-eks-1861c5","container_runtime_version":"docker://18.6.1","architecture":"amd64"}]}
```

**Comment by leecalcote** [comment]
Syncing with master; re-running build.

**Comment by kanishkarj** [comment]
@leecalcote considering that the same script can be used for GKE / EKS / AKS(most probably) should we rename the argument in mesheryctl from gke to something else?

**Comment by leecalcote** [comment]
@kanishkarj assuming that the script is the same across these three now and will likely stay that way in the future, yes, that's a good call. We actually need to given this command structure a little bit of a think in context of all the commands that might come. The "Meshery CLI" design doc is the right place to get a bird's eye view on this.

// @thakursaurabh1998

**Comment by kanishkarj** [comment]
@leecalcote How should we go ahead with this?

**Comment by leecalcote** [comment]
Thank you for testing this @nitishvu! 

@kanishkarj Currently, placing this functionality as a `system` subcommand is the best option we have. Should we ever create a `platform` command, we might relocate at that point.

**Comment by kanishkarj** [comment]
> Thank you for testing this @nitishvu! 
> 
> @kanishkarj Currently, placing this functionality as a `system` subcommand is the best option we have. Should we ever create a `platform` command, we might relocate at that point.

Sounds good to me!

**Pull request merged**
