### PR TITLE
Show menu in subcommands under `mesheryctl system`

### PR DESCRIPTION
**Pull request by nebula-aac**
Removed args in certain subcommands under `system`.

Show help menu instead.

**Notes for Reviewers**
Open issue: https://github.com/meshery/meshery/issues/8400

This PR removes args in certain subcommands under 'system'. This makes the user experience a little bit jarring because when you go to navigate to certain subcommand, you expect the help menu to show up. On some of the subcommand, it didn't make sense to have args because there's already a help menu in place with other subcommands for that one.

A couple of the files that were added to the commit which I did not know until after the fact. These are just formatting issues.

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
@nebula-aac are we holding onto this under commands outside of `system` have been updated or were those already reviewed?

**Comment by nebula-aac** [comment]
@leecalcote any of the other commands didn't seem like it needs a help menu, so far i only saw `system` had some subcommand that would be better with a menu option. i can double check

**Comment by leecalcote** [comment]
Menus… like that of `mesheryctl system login` as an example, right?

Clarification: we will still have MeshKit-style error codes with probable cause and suggested remediation, right?

**Comment by nebula-aac** [comment]
@leecalcote 

Yes, whenever you run a command, some of the subcommand returns an error because we were requiring another command attached, but we wouldn't know unless we do `meshery system context`.

It will return this 

```bash
./mesheryctl system context
Error: please specify a flag or subcommand. Use 'mesheryctl system context --help' to display user guide.

See https://docs.meshery.io/reference/mesheryctl/system/context for usage details
```

When I was navigating through some of the commands, I felt it was an extra step to ask for the user to provider another flag, and then ask them use `--help` to get the commands needed for it, when you can just run it as normal and see the help menu.

And ask for `meshkit`, yes, the only reason the fields wouldn't be showing would be if you didn't add anything to. In `errors` packages from `meshkit`, we don't have a requirement to look for those fields to be filled, nor do we have a check for if a field has been nil or not.

I can make it so but it may cause some initial start for everyone to get used unless we documented in the official readme about how to setup a custom error message.

**Comment by leecalcote** [comment]
Ok, so not a selectable menu, then, unlike the login command that has a menu.

**Review by suhail34 — COMMENTED** [review]
Same problem with other subcommand too will you be doing it in this pr itself

**Comment by nebula-aac** [comment]
I can check.

**Comment by Philip-21** [comment]
> @leecalcote
> 
> Yes, whenever you run a command, some of the subcommand returns an error because we were requiring another command attached, but we wouldn't know unless we do `meshery system context`.
> 
> It will return this
> 
> ```shell
> ./mesheryctl system context
> Error: please specify a flag or subcommand. Use 'mesheryctl system context --help' to display user guide.
> 
> See https://docs.meshery.io/reference/mesheryctl/system/context for usage details
> ```
> 
> When I was navigating through some of the commands, I felt it was an extra step to ask for the user to provider another flag, and then ask them use `--help` to get the commands needed for it, when you can just run it as normal and see the help menu.
> 
> And ask for `meshkit`, yes, the only reason the fields wouldn't be showing would be if you didn't add anything to. In `errors` packages from `meshkit`, we don't have a requirement to look for those fields to be filled, nor do we have a check for if a field has been nil or not.
> 
> I can make it so but it may cause some initial start for everyone to get used unless we documented in the official readme about how to setup a custom error message.

@nebula-aac its best if the fields are filled because it gives the user an idea on how to proceed with a solution when an error occurs , our focus should just be making each error message for each field brief and concise

**Review by Philip-21 — COMMENTED** [review]
@nebula-aac for the meshkit error package,  its best if the fields are filled because it gives the user an idea on how to proceed with a solution when an error occurs , our focus should just be making each error message in each field brief and concise.

**Comment by nebula-aac** [comment]
@Philip-21 I agree but I'm not doing it on this PR though

That will be a separate PR once I test out the changes I can make in `meshkit`.

This PR is just to remove some of the required args in some of the subcommands.

**Comment by Philip-21** [comment]
If you want to make changes in Meshkit please create an issue first, so we all can understand what you want to implement

**Comment by leecalcote** [comment]
This has a dependency on https://github.com/meshery/meshkit/pull/340, is that right?

**Pull request merged**
