### PR TITLE
added upgradation command for mesheryctl using brew in docs

### PR DESCRIPTION
**Pull request by ashiscs**
Signed-off-by: ashiscs <ashissingh640@gmail.com>

### CODE REVIEW

**Comment by ashiscs** [comment]
@leecalcote sir done!

**Comment by ashiscs** [comment]
@leecalcote sir, now it will work!!

**Comment by leecalcote** [comment]
@ashiscs have a look again. The footer.html file is still included in this PR.

**Comment by ashiscs** [comment]
@leecalcote sir, now is it okay??

**Pull request closed without merging**
