### PR TITLE
Fix context search in modal

### PR DESCRIPTION
**Pull request by MUzairS15**
Signed-off-by: MUzairS15 <muzair.shaikh810@gmail.com>

**Description**
The bug was due to regression introduce in this pr https://github.com/meshery/meshery/pull/5952/commits/5f3804e1bb801110236110af916b567b396be751

https://user-images.githubusercontent.com/79860504/197325818-42ffb8ba-098e-4393-b095-c3ba42e69e88.mov

This PR fixes search functionality in modal not working correctly.

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Review by theBeginner86 — APPROVED** [review]
Works well! 
Thank you @MUzairS15 for quick fix

**Comment by theBeginner86** [comment]
Merging this one as it solves an urgent issue regarding the search in the deployment modal. // @leecalcote

**Comment by leecalcote** [comment]
@theBeginner86 thank you. A Meshery release might be appropriate.

**Comment by theBeginner86** [comment]
> @theBeginner86 thank you. A Meshery release might be appropriate.

gotcha. Making a release....

**Pull request merged**
