### PR TITLE
chore: sort the technology list in alphabetical order

### LINKED ISSUE #8642: [UI] Designs: Technology selection - Alphabetical sorting and support for multiple selections
### Current Behavior
1. When publishing a design or adding metadata to a design, the long list of technology choices only allows the user to choose one technology at-a-time before the selector closes.

2. The list of technologies is not presented in alphabetical order.

### Screenshots

Screenshot 2023-09-01 at 4 52 04 PM

 

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by Yana-Gupta**
**Notes for Reviewers**

This PR fixes #8642

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Yashsharma1911** [comment]
Good @Yana-Gupta 👏 though I have some suggestions

1) Instead of mapping in schema directly we are already mapping here so I think we don't require to loop again on schema
https://github.com/meshery/meshery/blob/f18bb842de48daccbc221528ebc7d82c7e82230f/ui/components/MesheryPatterns.js#L524

2) The changes that you made MesheryPatterns also need to be made in `MesheryFilters` page and `PublishModal` to reflect changes in all publish modal

**Comment by Yana-Gupta** [comment]
> Good @Yana-Gupta 👏 though I have some suggestions
> 
> 1. Instead of mapping in schema directly we are already mapping here so I think we don't require to loop again on schema
>    https://github.com/meshery/meshery/blob/f18bb842de48daccbc221528ebc7d82c7e82230f/ui/components/MesheryPatterns.js#L524
> 2. The changes that you made in MesheryPatterns also need to be made in `MesheryFilters` page and `PublishModal` to reflect changes in all publish modal

Ohh okay @Yashsharma1911 and should I make the changes in `MesheryFilters` and `PublishModal` page in this pull request only.

**Comment by Yashsharma1911** [comment]
Yes you should push changes in this PR

**Comment by Yana-Gupta** [comment]
@Yashsharma1911 I am unable to find publish model page in ui.. will you provide some help.

**Comment by Yashsharma1911** [comment]
> @Yashsharma1911 I am unable to find publish model page in ui.. will you provide some help.

here it is https://github.com/meshery/meshery/blob/master/ui/components/Modals/PublishModal.js

**Comment by Yana-Gupta** [comment]
> > @Yashsharma1911 I am unable to find publish model page in ui.. will you provide some help.
> 
> here it is https://github.com/meshery/meshery/blob/master/ui/components/Modals/PublishModal.js

Thanks

**Comment by Yana-Gupta** [comment]
> hey @Yana-Gupta
> 
> Let's discuss this on Meshery Dev call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#) if you would. :)

Hi @Ghat0tkach currently I'm little busy so won't be able to attend the meeting.

**Comment by Yashsharma1911** [comment]
> > hey @Yana-Gupta
> > Let's discuss this on Meshery Dev call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#) if you would. :)
> 
> Hi @Ghat0tkach currently I'm little busy so won't be able to attend the meeting.

@Yana-Gupta please ping when it's done

**Comment by Yana-Gupta** [comment]
> > > hey @Yana-Gupta
> > > Let's discuss this on Meshery Dev call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#) if you would. :)
> > 
> > 
> > Hi @Ghat0tkach currently I'm little busy so won't be able to attend the meeting.
> 
> @Yana-Gupta please ping when it's done

Yes @Yashsharma1911 It's done

Filter's page:
image

Design's page:
[Screencast from 14-09-23 11:05:01 AM IST.webm](https://github.com/meshery/meshery/assets/103108630/24bdd664-37c0-4e03-bc27-9ee55a097a1c)

**Review by Yashsharma1911 — APPROVED** [review]
Thankyou @Yana-Gupta LGTM 👏

**Pull request merged**
