### PR TITLE
fixed typos and grammar for documentation

### LINKED ISSUE #736: typos and incorrect grammar for documentation
**Description**
Various typos in files and grammar error in documentation

**Expected Behavior**
Errors as typos and incorrect usage of grammar 
**Screenshots**

image

### PR DESCRIPTION
**Pull request by shivaylamba**
Signed-off-by: shivaylamba shivaylamba@gmail.com

#### Description

This PR fixes #736     

#### Checklist

- [] [DCO](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin) signed.
- [] Title of the PR starts with area name, e.g. `meshery:`, `mesheryctl:`, `ui:`.

### CODE REVIEW

**Comment by shivaylamba** [comment]
Please review @leecalcote

**Comment by leecalcote** [comment]
@shivaylamba you'll want to execute [these instructions](https://github.com/layer5io/meshery/pull/737/checks?check_run_id=505806694) on your local branch.

Here's a bit of background and a git alias / IDE configuration that will automatically sign your commits -https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin

**Comment by shivaylamba** [comment]
I have signed the DCO @leecalcote

**Comment by leecalcote** [comment]
Good, good, good. 👍

**Pull request merged**
