### PR TITLE
Add job to perform a Meshery rollout for CNCF playground on release

### PR DESCRIPTION
**Pull request by Revolyssup**
**Notes for Reviewers**

This PR adds another job which performs a Meshery rollout for CNCF playground on release

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — CHANGES_REQUESTED** [review]
My request was and is to have this as a separate flow. Please see line 83.

**Comment by Revolyssup** [comment]
> My request was and is to have this as a separate flow. Please see line 83.

Done

**Review by leecalcote — APPROVED** [review]

**Comment by leecalcote** [comment]
Thank you, @Revolyssup 🥇

**Comment by leecalcote** [comment]
I see your `playground` tag, too, Mr. Tiwari. 👏

**Pull request merged**
