### PR TITLE
Updated meshery docs

### LINKED ISSUE #3691: [Docs] Updating the docs about recent updates on refactoring mesheryctl commands
#### Current State
The meshery docs needs to be updated about the recent updates on refactoring of the mesheryctl commands

---

#### Contributor Resources

- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/meshery/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
- [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by debjani1413**
**Description**
The meshery docs has been updated about the recent updates on refactoring of the mesheryctl commands

This PR fixes #3691 

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 7c88e44d4f8347862e22eaf25fe27cc73a20640c at: https://6104529579da0a23bec48de4--meshery-docs-preview.netlify.app

**Comment by navendu-pottekkat** [comment]
This is great! Thank you for being diligent here @debjani1413. There is a missing commit sign-off. Could you check that?

**Comment by l5io** [comment]
🚀 Preview for commit 567f6f0a014ee94266cde3bcbfb4c6782740da57 at: https://6104535276c5be21aa03b4f1--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit fb094081f2e2f93be9644bf62b84a1a8e55ac75f at: https://610453e0ed4e0b1c376f1e84--meshery-docs-preview.netlify.app

**Comment by debjani1413** [comment]
> This is great! Thank you for being diligent here @debjani1413. There is a missing commit sign-off. Could you check that?

@navendu-pottekkat, I recently migrated to wsl2 on windows and its taking a different or rather a non-compliant mail-id to signoff and hence it's failing, I'm trying my best to solve it :)

**Comment by l5io** [comment]
🚀 Preview for commit a9080b791ca2e8be9086ad311bb990498c39c93a at: https://6104555bee22eb28bc3e012c--meshery-docs-preview.netlify.app

**Pull request closed without merging**
