### PR TITLE
add configuration env.SAAS_BASE_URL to values.yaml

### LINKED ISSUE #2277: [Helm] Meshery chart deployment from GitHub repo failing with unset env var
#### Description
When deploying Meshery via helm using these instructions:

```
git clone https://github.com/layer5io/meshery.git\; cd meshery
kubectl create namespace meshery
helm install meshery --namespace meshery install/kubernetes/helm/meshery
```
Meshery server crashes with the error below.

#### Screenshots/Logs
```
kubectl logs --namespace meshery -l "app.kubernetes.io/name=meshery,app.kubernetes.io/instance=meshery"
time="2021-01-20T21:10:14Z" level=info msg="Using '/home/appuser/.meshery/config' to store user data"
time="2021-01-20T21:10:14Z" level=info msg="Using '/home/appuser/.kube' as the folder to look for kubeconfig file"
time="2021-01-20T21:10:14Z" level=info msg="Log level: info"
time="2021-01-20T21:10:14Z" level=fatal msg="SAAS_BASE_URL environment variable not set."
```

#### Environment:
- Meshery Version: v0.4.27
- Kubernetes Version: 1.19.x

### PR DESCRIPTION
**Pull request by zjyingchang**
Signed-off-by: zjyingchang <zjyingchang@163.com>

**Description**

This PR fixes #2277 

**Notes for Reviewers**

 add configuration env.SAAS_BASE_URL: https://meshery.layer5.io to values.yaml

**[Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Awesome. 😄

**Review by Aisuko — CHANGES_REQUESTED** [review]
Thanks for your contribution. We need to bump the chart version to 2.1.2 https://github.com/layer5io/meshery/blob/6c1066a109a80fc0ba182a7f2a93cfe8377344da/install/kubernetes/helm/meshery/Chart.yaml#L33

**Comment by zjyingchang** [comment]
> Awesome. 😄
This is my first time to commit pr. I‘m learning how to be a contributor

**Review by Aisuko — APPROVED** [review]
LGTM

**Comment by Aisuko** [comment]
@zjyingchang Thanks for your contribution.

**Comment by leecalcote** [comment]
Whoo-hoo! 🎈 Nice work, @zjyingchang. 💯

**Comment by leecalcote** [comment]
> > Awesome. 😄
> 
> This is my first time to commit pr. I‘m learning how to be a contributor

This makes that fact that your commits were signed off from the start even more impressive. Most of the rest of us neglect to have sign-off configured in our `git` setup. 😂

**Pull request merged**
