### PR TITLE
[Resolves issue #5542 — Correct Bot message with right image

### LINKED ISSUE #5542: [Bot] Fix welcome bot image
#### Expected Behavior

It should show up as it used to be.
Screenshot 2022-05-26 at 1 33 46 PM

#### Screenshots/Logs

Currently it looks like:
Screenshot 2022-05-26 at 1 26 41 PM

#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by Santosh1176**
This PR resolves [#5542](https://github.com/meshery/meshery/issues/5542#issue-1249241908) by correcting the bot message to display the right image.

Signed-off-by: Santosh - <dtshbl@gmail.com>

**Description**

This PR fixes #5542 

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Thanks, @Santosh1176

**Comment by Santosh1176** [comment]
My pleasure @leecalcote

**Comment by leecalcote** [comment]
😄 @Santosh1176.

will you take a quick moment to execute these command in order to sign-off on your commit? - https://github.com/meshery/meshery/pull/5544/checks?check_run_id=6608403649

**Comment by Santosh1176** [comment]
> 😄 @Santosh1176.
> 
> will you take a quick moment to execute these command in order to sign-off on your commit? - https://github.com/meshery/meshery/pull/5544/checks?check_run_id=6608403649

I had signed-off the commit using *commit -s -m “commit message*. Not sure, why I am getting this message. However, I’ll follow the instructions in the link to rectify it.

**Review by Akshit42-hue — COMMENTED** [review]
Hey @Santosh1176, You can refer this article in order to sign-off your commit https://docs.pi-hole.net/guides/github/how-to-signoff/

**Comment by leecalcote** [comment]
> 😄 @Santosh1176.
> 
> will you take a quick moment to execute these command in order to sign-off on your commit? - https://github.com/meshery/meshery/pull/5544/checks?check_run_id=6608403649

@Santosh1176 these are the commands that you need to run - https://github.com/meshery/meshery/pull/5544/checks?check_run_id=6622200675

**Comment by Santosh1176** [comment]
> > smile @Santosh1176.
> > will you take a quick moment to execute these command in order to sign-off on your commit? - https://github.com/meshery/meshery/pull/5544/checks?check_run_id=6608403649
> 
> @Santosh1176 these are the commands that you need to run - https://github.com/meshery/meshery/pull/5544/checks?check_run_id=6622200675

Done as advised and thanks for helping out.

**Pull request merged**
