### PR TITLE
Add release_channel to the version api response and remove radio buttons from the UI

### LINKED ISSUE #2194: [UI] "stable-" hardcoded into Release dashboard panel
**Description**
When users are subscribed to the "edge" channel, "stable-" is errantly inserted.

**Expected Behavior**
"stable-" should not be hardcoded.

**Screenshots**
Screen Shot 2021-01-01 at 4 17 03 PM

**Environment:**
- Meshery Version: v0.4.27

### LINKED ISSUE #2195: [UI] Report "Channel Subscription" in Release dashboard panel
#### Current Behavior
Meshery shows users details of the Meshery release channel and version they are running. The disabled radio button group for release channels implies that users will be able to switch channel subscriptions.

#### Desired Behavior
Users should be shown the name of their current channel subscription, not offered to switch channels.

#### Implementation
1. Remove radio button for Channel subscription switching.
1. Add `$HOME/.meshery/meshery.yaml` to `docker-compose.yaml`
1. Retrieve currently subscribed channel from `config.yaml` for `current-context`.
1. Rename "Channel" section title to "Channel Subscription". Show currently subscribed channel. 

#### Acceptance Tests
1. No radio buttons. 
1. Just name of currently subscribed channel.

### PR DESCRIPTION
**Pull request by tangledbytes**
Signed-off-by: Utkarsh Srivastava <srivastavautkarsh8097@gmail.com>

**Description**
This PR fixes #2195 and fixes #2194 

**Notes for Reviewers**

**Relevant Screenshots**

Screenshot_20210104_035727

Screenshot_20210104_035643

Screenshot_20210104_034911

Screenshot_20210104_034058

**[Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
@utkarsh-pro regarding this method:

"The release channel is determined by matching the current commit sha with the commit sha of the stable release, if they match then the meshery server is considered to be of "stable" release while if they don't then release channel is considered of "edge" release."

The release channel can be determined by presence of "stable-" or "edge-" in the version number (tag), yeah?

**Comment by leecalcote** [comment]
@utkarsh-pro support for "channel" in Mesheryconfig file is coming - https://github.com/layer5io/meshery/issues/2164. Even with this support, though, release channel is still best determined by "stable" or "edge" from the tag from the ldflags using the information the `/api/server/version` endpoint uses.

**Comment by leecalcote** [comment]
@SudhanAruna, about how far away are you from having https://github.com/layer5io/meshery/issues/2164 ready?

**Comment by utkarsh-pro** [comment]
> @utkarsh-pro regarding this method:
> 
> "The release channel is determined by matching the current commit sha with the commit sha of the stable release, if they match then the meshery server is considered to be of "stable" release while if they don't then release channel is considered of "edge" release."
> 
> The release channel can be determined by presence of "stable-" or "edge-" in the version number (tag), yeah?

@leecalcote, the version response doesn't have the channel, is it coming with some PR?
```js
{
    build: "v0.4.27",
    latest: "v0.4.27",
    outdated: false,
    commitsha: "c8008aa3fd6c25561f577990aa5a4c094c939fdc",
    release_channel: "edge"
}
```

**Comment by leecalcote** [comment]
@utkarsh-pro oh, wow. I didn't realize that we're not including stable/edge in the tag provided through ldflags. Let's add this information in the ldflags as the source of truth for Meshery server to know whether it is running stable or edge.

**Comment by leecalcote** [comment]
Awesome.

**Pull request merged**
