### PR TITLE
Made settings consistent with the UI

### PR DESCRIPTION
**Pull request by partik03**
**Notes for Reviewers**

This PR fixes #
#6443

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.
 Before 
198065993-7fd1d00a-6b9e-4673-852c-352486f2dbc8

After

Screenshot from 2022-12-12 20-22-37

### CODE REVIEW

**Review by Chadha93 — COMMENTED** [review]
LGTM, Good work @partik03. Do present this on Meshery dev call, link of [minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#), for a feedback. Let's merge then.

**Comment by partik03** [comment]
> LGTM, Good work @partik03. Do present this on Meshery dev call, link of [minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#), for a feedback. Let's merge then.

Thank you.I don't have the write access to mention my topic in the document.

**Comment by Chadha93** [comment]
> > LGTM, Good work @partik03. Do present this on Meshery dev call, link of [minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#), for a feedback. Let's merge then.
> 
> Thank you.I don't have the write access to mention my topic in the document.

You can make suggestions as comment.

**Comment by partik03** [comment]
@Chadha93 is this pr going to merge or should I make some changes to it??

**Comment by Chadha93** [comment]
Yes, as discussed on the Meshery dev call, let's go with your changes if you want you can work on the feedback regarding UX of this.

**Review by Chadha93 — APPROVED** [review]
LGTM

**Pull request merged**
