### PR TITLE
fix : [UI] "Add Cluster" button to be always available

### LINKED ISSUE #12379: [UI] "Add Cluster" button to be always available
### Current Behavior
Users who have one or more Kubernetes clusters connected sometimes wish to add another cluster under Meshery's management.  They can do so on the Connections page or that _could_ do so under the Kubernetes context switcher in the upper right corner.

Users that have existing Kubernetes cluster connections are not shown the convenient option of the "Add Cluster" button that they will see when there are not clusters connected. 

### Desired Behavior
As a matter of convenience, it would be nice if the "Add Cluster" button was ever-present.

### Acceptance Tests
Whether a user has zero or more Kubernetes cluster connections, the Add Cluster button will be available.

### Mockups

Screenshot 2024-10-15 at 5 12 37 PM

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by Divyansh200102**
**Notes for Reviewers**

- This PR fixes #12379

-Before 
Screenshot 2024-11-10 090947

-After
Screenshot 2024-11-10 090921

-Video

https://github.com/user-attachments/assets/412d220b-2fd2-4aa3-88cf-fb97849065f6

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by vishalvivekm** [comment]
@Divyansh200102 Let's discuss this during the Meshery Development call today at 9:00 AM CT | 8:30 PM IST. Adding it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit?pli=1#) || [meeting link](https://meet.layer5.io/meshery).

**Review by sudhanshutech — CHANGES_REQUESTED** [review]
@Divyansh200102 can you show how it looks when there are no k8s clusters?

**Comment by Divyansh200102** [comment]
> @Divyansh200102 can you show how it looks when there are no k8s clusters?

@sudhanshutech this is how it looks like when no clusters are connected
image
this button basically directs to the connections page where an add cluster button is present as you may know.

**Comment by Divyansh200102** [comment]
> @Divyansh200102 can you show how it looks when there are no k8s clusters?

apologies for the late reply @sudhanshutech please see the video below is this the desired change we want? When there are no clusters connected (or a cluster whose name is not present) we have the connect cluster button which directs to the connection page but when there are clusters connected we have an add cluster button . is that what we want? if yes i have made the changes accordingly.

https://github.com/user-attachments/assets/ede7e5b4-3b05-4e55-8e9e-4596521c14a4

**Comment by leecalcote** [comment]
Ready for final review, right, @Divyansh200102?

@sudhanshutech @amitamrutiya

**Comment by Divyansh200102** [comment]
> Ready for final review, right, @Divyansh200102?
> 
> @sudhanshutech @amitamrutiya

I'll test  the changes one final time.

**Pull request closed without merging**
