### PR TITLE
fixed the iframe

### LINKED ISSUE #1549: [Docs] Embedded YouTube video is broken
**Current State:**
On [this page](https://meshery.layer5.io/docs/service-meshes/adapters/nsm/nsm#2-vpp-icmp-application), the embedded YouTube video is broken.

Screen Shot 2020-09-07 at 3 56 54 PM

**Desired State:**
The Youtube video should be playable from the documentation page itself.

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

### PR DESCRIPTION
**Pull request by jomefavourite**
**Description**

This PR fixes #1549 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Hi @jomefavourite, will you execute these instructions to ensure that your commit signed-off? https://github.com/layer5io/meshery/pull/1550/checks?check_run_id=1083470238

**Comment by jomefavourite** [comment]
I don't know why it isn't working. I hope i didn't break anything

**Review by leecalcote — APPROVED** [review]
Looks great. Thanks, @jomefavourite! 👍

**Comment by leecalcote** [comment]
@jomefavourite will you update this PR's description to include the issue number that it fixes? GitHub will auto close the issue when the PR is merged saving us some time and potentially stale issue(s).

**Comment by jomefavourite** [comment]
All changes has been approved except one. I don't know what else is wrong.
Screenshot (167)

**Review by leecalcote — APPROVED** [review]
Thank you, @jomefavourite 😄

**Pull request merged**
