### PR TITLE
[README] add: Community Forum

### PR DESCRIPTION
**Pull request by aminoxix**
_Signed-off-by: amino19  <anshumaankrprasad76@gmail.com>_

**Description**
Added a single line, for Discussion forum of Community.

This PR fix #`enhancement`

**Notes for Reviewers**
@leecalcote : Point added ✔️ 

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — CHANGES_REQUESTED** [review]
Please only change the single line necessary to add reference to Discuss.

**Comment by leecalcote** [comment]
Signal when only the lines changed show in the diff.

**Comment by amino19** [comment]
@leecalcote : I tried to change `single line`, but it declares `whole file`, Actually I am working on one PR ie, CI, but at the same time I use different branch as well, idk Sir, how this happens! :confused: 
But it's done!

**Review by Nikhil-Ladha — APPROVED** [review]

**Comment by Nikhil-Ladha** [comment]
> @leecalcote : I tried to change `single line`, but it declares `whole file`, Actually I am working on one PR ie, CI, but at the same time I use different branch as well, idk Sir, how this happens! 
> But it's done!

Are you using prettier or so? If that's the case, that might be causing the issue.
Try making a change in a different editor and check the `git diff`.

**Comment by amino19** [comment]
@Nikhil-Ladha : Ah yes, Thanks Sir, I think this suggestion would be at gold! :slightly_smiling_face: 
Done with changes!

**Review by Nikhil-Ladha — APPROVED** [review]

**Pull request merged**
