### PR TITLE
Fixed broken link

### PR DESCRIPTION
**Pull request by arunkarthicknm**
Signed-off-by: arunkarthick <arunkarthicknm@gmail.com>

**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by arunkarthicknm** [comment]
Done :) @l5io

**Comment by arunkarthicknm** [comment]
Hello @l5io , I checked the preview and it works fine now. Will you merge this PR please? 😀

**Comment by arunkarthicknm** [comment]
Can anyone merge this PR please :)

**Review by leecalcote — APPROVED** [review]
Thanks for this, @arunkarthicknm 👍 

This one went under the radar for a bit.

**Pull request merged**
