### PR TITLE
Categorization of Permissions

### PR DESCRIPTION
**Pull request by iArchitSharma**
**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 3160a5a1c95ca5859d5fdbadb44b5fbbfc7fcd33 at: https://6654525ceb7d056ad45fbb15--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit e7afce3708ceed55a1692a8df4fb03a793a4c111 at: https://6656073c1994c558d455c60a--meshery-docs-preview.netlify.app

**Review by dragon-slayer875 — CHANGES_REQUESTED** [review]
Can you please make it so that the lengths of all table rows are equal?
image

**Comment by l5io** [comment]
🚀 Preview for commit 4372046be5d2144445c44c1e5243e6e91fd5b699 at: https://66570ecbd0dc999bc691b790--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 8d2d73b96769c76ce1d4549869c37228138db89c at: https://6657105aad96e09f21c0cb17--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 506d22a73ad4e24a65533eb5bfe12d5891fe1a5f at: https://665726cf99c6bd0d83dfb838--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit c6a3273e97029cacbebf859a6730735c0e98e81d at: https://66574b731d978634fc63bb31--meshery-docs-preview.netlify.app

**Review by leecalcote — CHANGES_REQUESTED** [review]
Still missing Key ID and CASL moniker?

**Comment by dragon-slayer875** [comment]
> Still missing Key ID and CASL moniker?

@leecalcote Archit is working on it separately from this. 
Monikers and UUIDs will be added in a new PR.

**Comment by leecalcote** [comment]
ok

**Review by leecalcote — APPROVED** [review]

**Pull request merged**
