### PR TITLE
 Add Loading Spinner Component 

### PR DESCRIPTION
**Pull request by 14Richa**
**Description**

https://user-images.githubusercontent.com/41283476/147383851-ddd86d05-174f-4cc0-b22b-e5d3e2c9edfa.mp4

This PR adds loading spinner component 

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by bariqhibat — APPROVED** [review]
Looks good!

**Comment by leecalcote** [comment]
I agree with @bariqhibat. 🙂 

There is a small merge conflict to resolve, @14Richa.

**Comment by 14Richa** [comment]
> I agree with @bariqhibat. slightly_smiling_face
> 
> There is a small merge conflict to resolve, @14Richa.

Resolved.

**Review by sudo-NithishKarthik — APPROVED** [review]
Looking good @14Richa 🎉 .

**Comment by leecalcote** [comment]
Whoo-hoo! 🥳

**Comment by bariqhibat** [comment]
Hi @sudo-NithishKarthik, I somehow can't find this component in the master branch. Is this PR reverted by any chance?

**Comment by sudo-NithishKarthik** [comment]
It's in `meshery-ui-restructuring` branch @bariqhibat

**Comment by bariqhibat** [comment]
> It's in `meshery-ui-restructuring` branch @bariqhibat

Ah got it, thanks for the comment

**Pull request merged**
