### PR TITLE
Enhancing Meshery docs website.

### PR DESCRIPTION
**Pull request by Krishna2323**
Signed-off-by: Krishna Gupta <belivethatkg@gmail.com>

**Notes for Reviewers**
Enhancing Meshery docs website.

This PR fixes #

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Conflict...

**Comment by leecalcote** [comment]
@Krishna2323 version v0.4 and v0.5 of the site should be left as-is. Only the top-level folder should change.

**Comment by leecalcote** [comment]
Close this PR?

**Comment by Krishna2323** [comment]
New PR created.

**Pull request closed without merging**
