### PR TITLE
[mesheryctl] Moved update flag to utils/constants

### PR DESCRIPTION
**Pull request by Revolyssup**
Signed-off-by: Ashish Tiwari <ashishjaitiwari15112000@gmail.com>

**Description**
Currently update flag is randomly defined in check_test in system package. Moving this to a utils/constants for a more ubiquitous use.

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Revolyssup** [comment]
@piyushsingariya  unit tests are failing because somehow in workflow ,its looking for tests files in github.com/layer5io/
Can you see why is it happening?

**Comment by piyushsingariya** [comment]
this constant should be placed under the root/constants package. utils/constants contains repository level constants.

FYI:- many constants that are supposed to be only used my mesheryctl are in process to be shifted under root/constants package.

**Comment by Revolyssup** [comment]
> this constant should be placed under the root/constants package. utils/constants contains repository level constants.
> 
> FYI:- many constants that are supposed to be only used in mesheryctl are in process to be shifted from utils package to root/constants package.

Cool, will make the changes

**Review by navendu-pottekkat — COMMENTED** [review]
With this PR only the update flag is moved to the constants file. What about the other constants/ flags? Should we be moving them to constants?

**Pull request closed without merging**
