### PR TITLE
modified provider urls

### LINKED ISSUE #10009: [Docs] Broken link in reference/rest-apis page in documentation
### Current State
Link: https://docs.meshery.io/reference/rest-apis
Currently, the summary of the Authentication has a broken link (shown in the picture below)

Docs  broken link providers

### Desired State
It should point towards the [link](https://docs.meshery.io/extensibility/providers)

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by JyothiSwaroopReddy07**
**Notes for Reviewers**

This PR fixes #10009

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit d407393942116208ec104ae064d233fce113b283 at: https://65ab2877bfe9a7407c25c2b1--meshery-docs-preview.netlify.app

**Review by ASK-03 — APPROVED** [review]
Hey @JyothiSwaroopReddy07! This LGTM. Thanks for your contribution.

**Comment by l5io** [comment]
🚀 Preview for commit 3794216ab31a701a49e5dcea0c185190dfa986ea at: https://65aba23e0c77518537244891--meshery-docs-preview.netlify.app

**Comment by sudhanshutech** [comment]
"Thank you, @JyothiSwaroopReddy07, for the pull request! I appreciate your initiative. In the future, could you please make sure to ask and get assigned the issue before raising a pull request? This helps us ensure proper coordination.

**Comment by saurabh100ni** [comment]
Hi @JyothiSwaroopReddy07 ,
Thanks for your PR! I encourage you to share this in the Website Meeting tomorrow at 6:30 PM IST. Share your screen, and walk us through it. It's cool to take and share feedback. Check the [Doc](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit) here to include this PR.

You're welcome at the meeting

Check to [community calendar](https://layer5.io/community/calendar) for more details of meetings at Layers.

**Comment by JyothiSwaroopReddy07** [comment]
> Hi @JyothiSwaroopReddy07 , Thanks for your PR! I encourage you to share this in the Website Meeting tomorrow at 6:30 PM IST. Share your screen, and walk us through it. It's cool to take and share feedback. Check the [Doc](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit) here to include this PR.
> 
> You're welcome at the meeting
> 
> Check to [community calendar](https://layer5.io/community/calendar) for more details of meetings at Layers.

will make demo of it

**Comment by saurabh100ni** [comment]
you don't have to prepare a presentation or demo for this, Just come and Join the meet and share your work by simply presenting your screen so others can share their feedback and you can also do the same for them.

**Review by leecalcote — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
