### PR TITLE
Add the Architecture page in spanish

### LINKED ISSUE #4349: [Docs] Create/Update the Architecture page in spanish, that goes in the CONCEPT section in the spanish docs site
#### Current State
The spanish docs site doesn't have the Architecture page translation to spanish 
English page to translate: https://docs.meshery.io/concepts/architecture
#### Desired State
The spanish docs site has the  Architecture page translated to spanish in the CONCEPT section 
---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by chal-gro**
**Description**

This PR fixes #4349

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 354e6d68443fa8bcb7bf7c3376daf47612db7adc at: https://6161f0573311c3aa9f3403df--meshery-docs-preview.netlify.app

**Comment by ramrodo** [comment]
@jesuslerma @alonsolopezr Could you review this PR giving a second look/approval, please?

**Comment by ramrodo** [comment]
Also @chal-gro, the **Arquitectura** link/concept is appearing on the English page/site. We should create (if it is needed) the **Concepts** section as it is in the original content:

image

And the new section should be in the Spanish Index:

image

**Comment by l5io** [comment]
🚀 Preview for commit ec75d6ffdac2af1bcc6a09d6c2d1741ad61fe10d at: https://61622df4c3dcde195907e1c8--meshery-docs-preview.netlify.app

**Comment by alonsolopezr** [comment]
EXCELENT.. but, just a word lacks the ó (propósito), just fix this one please
Captura de Pantalla 2021-10-09 a la(s) 17 07 16

**Pull request merged**
