### PR TITLE
Add earliest supported service mesh version to each adapter

### LINKED ISSUE #4486: [Docs] Add earliest supported service mesh version to each adapter
#### Current State
Using details from the Meshery Adapter [spreadsheet tracker](https://docs.google.com/spreadsheets/d/1rGGpSXC68iDJzNRU-qZIRQsZUwkt1qLFg7JCs4pfvbU/edit#gid=0), update the language used in the table here (https://docs.meshery.io/service-meshes) to be "earliest version" and list the earliest supported service mesh version.

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by Shreyas220**
**Description**
added the earliest version column 

This PR fixes #4486

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Yes, @Shreyas220 :check

**Comment by l5io** [comment]
🚀 Preview for commit 699a2a7049a50ef2d7f4eb92979ff0966b2606a0 at: https://617d884797042d516cc0b2d2--meshery-docs-preview.netlify.app

**Comment by Shreyas220** [comment]
@leecalcote 
https://617d884797042d516cc0b2d2--meshery-docs-preview.netlify.app/concepts/architecture/adapters
https://617d884797042d516cc0b2d2--meshery-docs-preview.netlify.app/service-meshes

**Comment by leecalcote** [comment]
@Shreyas220 versions are missing. Please fill-in.
Screen Shot 2021-11-02 at 12 10 47 PM

**Comment by Shreyas220** [comment]
@leecalcote we don't have components for the missing  
what should I put in those place

**Comment by warunicorn19** [comment]
i guess for those we could just keep the versions that it has right now. Do we not have components for traefik mesh though?🤔

**Comment by leecalcote** [comment]
+1 to what @warunicorn19 said.

**Comment by leecalcote** [comment]
@warunicorn19 you might take of this on @Shreyas220's behalf.

**Comment by warunicorn19** [comment]
Sure I'll create a new PR.

**Comment by l5io** [comment]
🚀 Preview for commit 30c524cb6e2dd5772e983737d7d562fe4a89f096 at: https://618570de8720d8091b1174b1--meshery-docs-preview.netlify.app

**Comment by warunicorn19** [comment]
@leecalcote made the changes, anything else that is required to be added?

**Comment by leecalcote** [comment]
💪

**Review by leecalcote — APPROVED** [review]

**Pull request merged**
