### PR TITLE
CI: Added a spell check for go files

### PR DESCRIPTION
**Pull request by nveenjain**
Refers #827, the spell test for Javascript based files needs to be done.
Did the initial setup for spell check.

Signed-off-by: Naveen Jain <nveenjain@gmail.com>

#### Notes to reviewers:
This is not a complete fix, there needs to be a PR opened for JS based files. And then we can create a pre commit hook
#### Checklist

- [x] [DCO](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin) signed.
- [x] Title of the PR starts with area name, e.g. `meshery:`, `mesheryctl:`, `ui:`.

### CODE REVIEW

**Comment by leecalcote** [comment]
I wonder if spell check makes sense in context of ensuring that this job is only executed when files are changed within the /docs and /ui directories (and exclude the running of this job for changes in all other directories). I'm not sure. 

It is worth noting that we've injected a number of new steps in our CI workflow recently, and in advance of breaking out components in to separate repos (e.g. /docs), would do well to consider if we can invoke CI jobs based on file changes in specific directories.

**Comment by leecalcote** [comment]
After discussion in the Meshery Development Meeting today, we'll go forth with evaluation of this check in `meshery-tmp`. 👍

**Comment by leecalcote** [comment]
@nveenjain irrespective of whether the spell checker is incorporated, there are many misspellings that you're corrected in this PR, which is great. For now, would you like to submit an alternative PR with just the spelling corrections?

**Comment by nveenjain** [comment]
Sure @leecalcote, I'll open another PR and one pr in the meshery-tmp repo

**Comment by kushthedude** [comment]
I think we are good to close this.

**Pull request closed without merging**
