### PR TITLE
Removed the margin from all SVG.

### PR DESCRIPTION
**Pull request by Harshit-Dandriyal**
Signed-off-by: Harshit Dandriyal <56961488+Harshit-Dandriyal@users.noreply.github.com>

**Description**
Removed the margin from all SVG.
This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Testing...

**Comment by leecalcote** [comment]
Are these being used elsewhere in Meshery UI currently?

**Comment by leecalcote** [comment]
Screen Shot 2022-10-10 at 5 32 55 PM

**Comment by Harshit-Dandriyal** [comment]
> Are these being used elsewhere in Meshery UI currently?

Nope.

**Comment by Abhishek-kumar09** [comment]
@Harshit-Dandriyal Did I say the logos should be 20*20?

**Pull request merged**
