### PR TITLE
[Docker] remove default adapters for docker

### PR DESCRIPTION
**Pull request by Azanul**
**Notes for Reviewers**

This PR updates docker deployment (including docker extension) of Meshery to exclude all adaptors initially.

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
@Azanul build a copy of the extension and run it. Given the UI's functionality, does it make sense to merge this?

**Comment by Azanul** [comment]
> @Azanul build a copy of the extension and run it. Given the UI's functionality, does it make sense to merge this?

Users can access Meshery UI through docker extension UI. Since users can (un)deploy from Meshery UI, merging this won't cause a feature loss and it'll reduce the footprint.

**Comment by MarioArriaga92** [comment]
@Azanul I've merged base master branch through Github UI to confirm [this issue](https://github.com/meshery/meshery/issues/7740) I've logged is still occurring or not🤞

**Comment by Azanul** [comment]
@leecalcote parking this till @senali-d gets done with her task in the extension.

**Pull request closed without merging**
