### PR TITLE
Navigator Active Tab Enhancement

### LINKED ISSUE #5715: [UI] Navigator Active Tab Enhancement
#### Current Behavior
Currently, The active tab is not highlighted/representing that it is active/opened. 
Not-Active

#### Desired Behavior
Let's have it highlighted to represent that the particular tab is active/opened. 
Active

#### Implementation
Highlight it with the hover color on the active tab. 
More suggestions are welcomed for better UX. 

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by manikmmalhotra**
Signed-off-by: manikmmalhotra <manikmalhotra2113@gmail.com>

**Description**
 highlighted tab to represent that the particular tab is active/opened.
This PR fixes #5715 

**Notes for Reviewers**
Always open for suggestions and improvements. Please point me out if anything should be added/corrected.

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Review by Chadha93 — COMMENTED** [review]
@manikmmalhotra  Please always provide screenshots or videos whenever a UI change is made. It would help the reviewers a lot.

**Comment by manikmmalhotra** [comment]
@Chadha93 sure here are the changes
Screenshot from 2022-07-18 21-37-13
Screenshot from 2022-07-18 21-36-54

**Comment by leecalcote** [comment]
A set of before / after comparison screenshots would be great.

**Comment by leecalcote** [comment]
> @leecalcote i've editted the last comment with before and after screenshot

Thank you much. I see them now. @meshery/meshery-ui-maintainers what do you think? Is "after" better or worse than "before"? // @Nikhil-Ladha

**Comment by manikmmalhotra** [comment]
@leecalcote just a suggestion if we highlight the background but don't change the color of text from white to blue , that may look better for eg:
Screenshot from 2022-07-18 23-47-47

**Comment by Abhishek-kumar09** [comment]
contrast may be brought to better. But I think the providing the background is good, but then need to be consistent with other menu items too.

**Comment by leecalcote** [comment]
This is a tough one, @manikmmalhotra 😰

**Pull request closed without merging**
