### PR TITLE
[Feat] Add validation endpoint

### PR DESCRIPTION
**Pull request by humblenginr**
**Description**

This PR creates a new endpoint `api/meshmodel/validate`. This PR is a part of `meshmodel` transition. It will be used to validate all types of `meshmodel` data. This is backed by CUE. This PR is associated with this [meshkit pr](https://github.com/meshery/meshkit/pull/196). One of the main reasons for exposing this functionality via meshery server(as opposed to just keeping it as a meshkit library function) is that it has use-cases in the frontend(fsm validation, design validation etc.).

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
@sudo-NithishKarthik does this fix any validation modal bugs?

**Comment by sudo-NithishKarthik** [comment]
Yes, @leecalcote . I will replace the current approach with which we do validation with this new only and those will fix this.

**Review by leecalcote — CHANGES_REQUESTED** [review]
Failed lint checks.

**Comment by leecalcote** [comment]
New MeshKit version available.

**Pull request closed without merging**
