### PR TITLE
moved-/.regal to policies/wasm/policies/.regal

### LINKED ISSUE #12139: Relocate .regal to `/policies` directory.
**Current Situation***

`meshery/meshery`'s root directory contains a `.regal` folder.

***Desired Situation**

The `.regal` folder is relocated to  `/policies` folder.

**Acceptance Criteria**

1. Regal linter continues to work.

---
[Slack Message](https://layer5io.slack.com/archives/CDM0ACDM5/p1727363051300079?thread_ts=1727363051.300079&cid=CDM0ACDM5)

### PR DESCRIPTION
**Pull request by moiz2405**
**Notes for Reviewers**
Moved  .regal/  to  policies/wasm/policies/.regal 
This PR fixes #12139

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x ] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — COMMENTED** [review]
Thank you, @moiz2405.

Please confirm that the build check using Regal is runs and behaves as expected. // @ctcarrier

**Comment by vishalvivekm** [comment]
@moiz2405 
Thank you for your contributions! Let's discuss this during the Meshery Development call today at 7:30 PM IST (9:00 AM CT). Adding it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit?pli=1#) || [meeting link](https://meet.layer5.io/meshery).

**Comment by moiz2405** [comment]
> @moiz2405 Thank you for your contributions! Let's discuss this during the Meshery Development call today at 7:30 PM IST (9:00 AM CT). Adding it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit?pli=1#) || [meeting link](https://meet.layer5.io/meshery).

Hi @vishalvivekm, I'm looking forward to the meeting and hoping to get some insights on proper workflow and recommended practices.

**Comment by leecalcote** [comment]
@moiz2405 are you no longer working on this? Please indicate if the related issue should be reassigned.

**Pull request closed without merging**
