### PR TITLE
Fix for the results page

### LINKED ISSUE #1004: [UI] Performance test results with MeshSync information failing to display
**Description**
Performance test results that include environment information from MeshSync do not display in the /results page.

**Expected Behavior**
The modal window should show the perf test results and environment information gathered by MeshSync (Kubernetes and node information).

**Screenshots**

1. The first results shown here are from a test run when Meshery **is not** connected to Kubernetes (does not run MeshSync). 
1. The second results shown here (in error) are from a test run when Meshery **is** connected to Kubernetes (does run MeshSync).

Untitled

### PR DESCRIPTION
**Pull request by Nikhil-Ladha**
Signed-off-by: Nikhil-Ladha <nikhilladha1999@gmail.com>

**Description**

This PR fixes #1004 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by kushthedude** [comment]
Can we create an issue for this as to see why was this happening in the first place?

**Comment by Nikhil-Ladha** [comment]
There is an issue mentioned above, and I think we know already why was the issue coming up.

**Comment by kushthedude** [comment]
> There is an issue mentioned above, and I think we know already why was the issue coming up.

I don't guess we know it yet, or else this would not happen in some occasional cases.

**Comment by Nikhil-Ladha** [comment]
I said that yesterday, why was it happening. As, when we have a mesh configured at that time when we were fetching the results at that time for the "Service Mesh" part of the Results dialog, we were passing a key-value pair to the function which was rendered to the page directly. But, actually, the value was an array of objects as a result the error was occurring. So, instead of passing the value to the dialogue, we are only passing the key to it for the time being.

**Pull request merged**
