### PR TITLE
[UI] New Notification Design implementation

### LINKED ISSUE #3187: New Notification Design implementation.
#### Current Behavior
The present notification snack bars and alerts in notification drawer don't match the sigma designs as well as the present light theme.

In below image you could see the notification in the red box and you could open up the notification drawer form the icon in the top right marked with yellow.

Screenshot 2021-05-28 at 1 41 57 PM

#### Desired Behavior
The notification snack bars and alerts in notification drawer should have the design as made in the figma.

#### Implementation
Look for the designs from the sigma 
[Figma Link](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=2328%3A7) 

From the below link you could find how to apply styling to the snackers easily.
- https://material-ui.com/api/snackbar/
- https://material-ui.com/customization/components/#overriding-styles-with-classes 

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

### PR DESCRIPTION
**Pull request by jeantiston**
Signed-off-by: jeantiston <jean.tiston.work@gmail.com>

**Description**

Changed snackbar colors and notifications drawer design based on the Figma design.
This PR fixes #3187

**Notes for Reviewers**

This change is **NOT YET FINISHED** I'm still not sure what action is needed for the check and x buttons in the drawer? (see screenshot below) so let me know.
I just wanted to put this out there so people can already review it and see if I missed anything else.

Screen Shot 2021-06-13 at 10 50 59 PM

Snackbar colors have been changed.
Screen Shot 2021-06-12 at 12 26 17 AM copy
Screen Shot 2021-06-12 at 12 26 26 AM copy
Screen Shot 2021-06-11 at 10 35 43 PM

**[Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
@jeantiston, looking great. Some feedback and a couple of asks:

https://user-images.githubusercontent.com/7570704/121965897-5e0f0180-cd33-11eb-9b96-5fde635d2c68.mov

**Comment by leecalcote** [comment]
@jeantiston, will you have a look at the onhover style of the new buttons? We'll want for them to essentially be the inversion of the onhover style used for colorized buttons.

Screen Shot 2021-06-14 at 5 09 20 PM

**Review by Ayush-Khandelwal-007 — CHANGES_REQUESTED** [review]
Excellent work! Just one small change. The notifications which are collapsed still show up arrow , can it be made down arrow for the collapsed one.?

**Comment by jeantiston** [comment]
@leecalcote @Ayush-Khandelwal-007 Thanks for reviewing! I'll make the changes tomorrow and update this pr. I just have another question. The current notification drawer has buttons to filter only the errors notifs and button to filter all notifs. Since we don't have that on the new design should I remove the code for notification filtering?

**Comment by leecalcote** [comment]
@jeantiston sounds great. Clarification: are you referring to the bell icon as a notification severity filter? This notification drawer would benefit from such a severity filter, but I don't believe it has one today. A filter would be nice to have...

**Comment by leecalcote** [comment]
Oh! I see the filter that you're referring to now. I took my blinders off. :/

Screen Shot 2021-06-15 at 12 12 29 PM

Yes, additional filters for the other severity levels would be great. I wonder how well they fit. I'll try to fidget in the design. While I do, please don't let that stop you taking a crack it either the design or implementation yourself. 👍

**Comment by jeantiston** [comment]
I have fixed the hover colors, removed the redundant X button, and fixed the collapsed arrow orientation

https://user-images.githubusercontent.com/52349175/122440288-fd035a00-cfce-11eb-9f28-b24b5824524c.mov

@leecalcote it seems that right now the filters are only able to distinguish event type like error or warning since the event object does not have the severity yet?
`
{event_type: 2, summary: "Error while installing Istio service mesh", details: "Error with istio operation: Error running istioctl…tcp 127.0.0.1:49519: connect: connection refused\n", operation_id: "18f689ad-7136-4f7c-abbb-e441228107e2"}
`

I was thinking about how we can fit in filters for types or severity maybe clickable chips? Although there seems to be 5 levels of severity and at least 4 types so I'm not really sure if it's a good idea. Just throwing it out there.
Screen Shot 2021-06-18 at 12 46 04 AM

**Comment by mgfeller** [comment]
@jeantiston Adding the link to the doc "Messaging System and Notification Center Design": https://docs.google.com/document/d/1_zpEWBcC6ngOLen_E_nc-octiUdBbpmdwwIX6qzo70M/edit#

Curious where the existing format (as mentioned above) and the event type comes from / is specified?

**Comment by jeantiston** [comment]
Hi @mgfeller. I console logged the parsed data from eventStream
https://github.com/layer5io/meshery/blob/master/ui/components/MesheryNotification.js#L212

and I think it is handled in the backend here
https://github.com/layer5io/meshery/blob/5b510d982dff5aff3870d6389745f7a2fdad1a13/handlers/events_streamer.go#L22

But I'm not entirely familiar with Go or the codebase to pinpoint where that format is defined exactly.

**Comment by mgfeller** [comment]
Hi @jeantiston, thanks  for that pointer! The format is defined here: https://github.com/layer5io/meshery/blob/fa55b66f9ed5d5745206fd2e2c6a2d3fd4d1937c/meshes/meshops.proto#L76

I think it will take a while until this is changed to the format I mentioned earlier, or maybe the new format is exposed on another endpoint, like `/api/cloud_events`. But I'm not aware of any plans regarding this. 

// @leecalcote 
// @kumarabd

**Comment by jeantiston** [comment]
Hi @mgfeller. Thanks for showing me where the format is!

In that case, maybe we can move forward with the design changes that is already implemented in this pr (snackbar and notification drawer changes) and revisit the formatting of the actual notification once event format is changed to the new one or once another endpoint can be used?

**Comment by mgfeller** [comment]
@jeantiston yes I think that makes sense :+1:

**Comment by Ayush-Khandelwal-007** [comment]
The work looks neat and implemented in a good way.
Just a quick question from @leecalcote , why is it that we have close drawer button removed? Shouldn't we be having one clear all button and one close button, right now both are triggered in just button as in figma design.👀

**Comment by jeantiston** [comment]
Hi @Ayush-Khandelwal-007. I thought the button on the lower left is the back/close drawer button? 

Screen Shot 2021-06-23 at 12 06 19 PM

**Comment by leecalcote** [comment]
@jeantiston let's keep your momentum up and get your PR over the hump here. Recognizing that there might be a follow PR based on further feedback, let's merge as-is and give your changes a twirl.

I see now that my statement here is basically a regurgitation of what you and @mgfeller both said.... wow... two weeks ago. Yikes.

**Comment by leecalcote** [comment]
haha! Awesome, @jeantiston! 🎈

**Comment by jeantiston** [comment]
Hooray! 🎉 Thank you!

**Pull request merged**
