### PR TITLE
[Docs] Copy-to-clipboard fix

### LINKED ISSUE #2007: [Docs] Copy-to-clipboard copies $ along with the code snippet
**Current State:**
The [clipboardjs](https://clipboardjs.com) feature incorporated doesn't work as expected, it copies the whole code segment including the `$`. This defeats the purpose of issue #1269, who's goal was to aid the user in not copying the `$` by accident.

**Desired State:**
Improve the reader experience for Meshery CLI commands, by only copying the code snippet, excluding the `$`.

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

### PR DESCRIPTION
**Pull request by chebro**
**Description**

This PR fixes #2007 

**[Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by chandrashritii** [comment]
Great job with the CSS @chebro Can you fix this as well? They commands under *Enable VM* and *Set WSL2 as the default version* should also have the copy button. Adding a code tag should fix it

Screenshot_2020-12-02 Windows

**Comment by chandrashritii** [comment]
The same is happening for the [mesheryctl](https://meshery.layer5.io/docs/guides/mesheryctl) guide, [meshery metrics](https://meshery.layer5.io/docs/guides/meshery-metrics) and a few other guides. The code tag isn't being picked up by the plugin. That's probably because the markdown code tags (```) need to be replaced with the new copy blocks for each of the code snippets

Also, this change was done in #1946. It needs to be reverted

Screenshot_2020-12-02 Upgrade mesheryctl and Meshery

**Comment by chebro** [comment]
> That's probably because the markdown code tags (```) need to be replaced with the new copy blocks

You're right, I didn't want to add the copy blocks in the wrong place so I left many unattended, should've left a comment, my bad. Will try to add the copy blocks where it makes sense to me for now, and someone can hopefully pick it up from there.

**Comment by chebro** [comment]
@chandrashritii I have update many mardown (```) code blocks to the new clipboardjs ones. I haven't touched the spanish docs though. Maybe someone can pick that up?

**Comment by chandrashritii** [comment]
Thank you for this update @chebro Really good work here. Let me look through the docs and pick up any code snippets that you have missed and the spanish docs

**Comment by leecalcote** [comment]
Good work, @chebro. 😄

**Review by leecalcote — APPROVED** [review]
I tossed in a couple of tweaks to tie-off, @chebro's good work.

**Pull request merged**
