### PR TITLE
[README.md] bold styling not applied to text

### LINKED ISSUE #9053: [README.md] bold styling not applied to text
#### Current State
Currently all points under section: "Join the Meshery community!" have the first word or two italicized and bold styling added. However the third point "_Fill-in_ a [community member form](https://layer5.io/newcomers) to gain access to community resources.", has its first word "Fill-in" italicized, but does not have the bold styling applied. 

### Screenshots
imageedit_3_9131638095

#### Desired State
To maintain consistency, add bold styling to the text "Fill-in"

i.e "_**Fill-in**_  a [community member form](https://layer5.io/newcomers) to gain access to community resources."

---

#### [Contributor Guides](https://docs.meshery.io/project/contributing) and Resources
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.meshery.io)

### PR DESCRIPTION
**Pull request by xiangpingjiang**
**Notes for Reviewers**

This PR fixes #9053

### CODE REVIEW

**Review by sandramsc — COMMENTED** [review]
Great effort. looks good! 

One item before merging, please address this [lint error ](https://github.com/meshery/meshery/actions/runs/6448770104/job/17506397552?pr=9054).

**Comment by leecalcote** [comment]
Thank you, @xiangpingjiang 👍

**Comment by sudhanshutech** [comment]
@xiangpingjiang the lint erro is fixed, will you just update your branch with latest changes so we can merge this pr

**Comment by xiangpingjiang** [comment]
> @xiangpingjiang the lint error is fixed, will you just update your branch with latest changes so we can merge this pr

I will do it soon

**Comment by Ckbhatia** [comment]
> > @xiangpingjiang the lint error is fixed, will you just update your branch with latest changes so we can merge this pr
> 
> I will do it soon

Just take a pull from the upstream master and merge with your local branch and push

**Review by sandramsc — APPROVED** [review]
LGTM!

**Review by Ckbhatia — APPROVED** [review]

**Review by Yashsharma1911 — APPROVED** [review]
Thankyou guys, LGTM

**Comment by Yashsharma1911** [comment]
Yay 🎈

**Pull request merged**
