### PR TITLE
Updated slack and discuss link

### LINKED ISSUE #7588: Update Discussion Forum link and Slack link
#### Current Behavior
Update Discussion Forum link and Slack link

#### Expected Behavior
On the Meshery Docs website, Dicuss link (https://discuss.layer5.io/) can be replaced with http://discuss.meshery.io/ (and the same for Slack at https://slack.meshery.io/). 
Note : Please note that the lack of “s” in http://discuss.meshery.io/ is intentional and the “s” is not to be added.

#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by DarrenDsouza7273**
**Notes for Reviewers**
 Updated slack and discuss link in the latest version and in v0.4 and v0.5 of Meshery docs
This PR fixes #7588

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by DarrenDsouza7273** [comment]
@leecalcote @Chadha93 @Savio629

**Comment by DarrenDsouza7273** [comment]
In the Meshery docs the twitter links are still redirecting to layer5 twitter handle instead of Meshery twitter handle should I update those in this pr?

**Comment by l5io** [comment]
🚀 Preview for commit 2742f2d538f4a3cbb64637e69b1a31aa9262122e at: https://644655b91b1a5000af13e2b6--meshery-docs-preview.netlify.app

**Review by leecalcote — APPROVED** [review]
Looks great, @DarrenDsouza7273. Thank you for taking care with respect to http vs https.

**Pull request merged**
