### PR TITLE
[CI] fix build UI workflow

### PR DESCRIPTION
**Pull request by Shiva953**
**Notes for Reviewers**

This PR addresses #9566

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
> Hey @Shiva953 Let's discuss this on Meshery Development Meeting today at 8:30 PM IST / 9 AM Central time. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#).

@Shiva953 did you discuss the merits of this on last week's Meshery CI meeting?

**Comment by leecalcote** [comment]
> > Hey @Shiva953 Let's discuss this on Meshery Development Meeting today at 8:30 PM IST / 9 AM Central time. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#).
> 
> @Shiva953 did you discuss the merits of this on last week's Meshery CI meeting?

@Shiva953 did you discuss the merits of this on last week's Meshery CI meeting?

**Review by MUzairS15 — CHANGES_REQUESTED** [review]
Instead you can use the expressions in GH actions for each of the steps in that job
```
if: {{ failure() }}
run: exit 1
```

**Comment by leecalcote** [comment]
@Shiva953 still with us?

**Comment by leecalcote** [comment]
@Shiva953 have you abandoned this effort?

**Pull request closed without merging**
