### PR TITLE
[DOCS] Add dropdown arrows in docs Sidebar Menu. #3946

### LINKED ISSUE #3946: [Docs] Add dropdown arrows in docs Sidebar Menu
#### Current State
I think it'd be better to add dropdown arrows for Sidebar in https://docs.meshery.io/ too, like the one discussed for [ this issue](https://github.com/meshery/meshery/issues/3940). It's not clear which Menu items have submenus and which ones do not. 
Screenshot 2021-08-21 at 1 50 41 PM
Here, the Menu item Contributing has sub-menu items, but the rest don't. But all look the same. 

#### Desired State

Have a clear distinction between the Menu items which have submenus and which don't. A dropdown arrow like the one below would make it clear. 

Screenshot 2021-08-20 at 3 27 22 PM
---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by 14Richa**
Signed-off-by: 14Richa <onlinericha19@gmail.com>

**Description**
Screenshot from 2021-12-10 11-29-37

This PR fixes #3946

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 1823c77cf804e23e69b947e9a80de58efb59f089 at: https://61b30ca21a2fcccb737b6e05--meshery-docs-preview.netlify.app

**Comment by warunicorn19** [comment]
This is not exactly the approach we were going for here. Basically, it is supposed to be a chevron in front or after the item which has "child" items, and on click, it would point downwards. Also, it would have to be dynamic, in the sense, that when any item in the sidebar is listed as a title and has a child element, the dropdown would be there. Take a look at the `sidebar.html`, which might help you understand the issue a bit more clearly😃.

**Comment by navendu-pottekkat** [comment]
@14Richa Could you check the comment made by @warunicorn19 above ^^

**Comment by leecalcote** [comment]
@14Richa reflecting on the comments above, does the enhancement request make sense?

**Comment by 14Richa** [comment]
@leecalcote 
AFAIK Jekyll doesn't support dynamic dropdowns, particularly in sidebars. Plus, it is a low priority since it's a UI issue in docs, my hack to just put a downward arrow is sufficient to tell users to click the link. Of course, it's not nice but serves the purpose.
I checked some other sites which were made on jekyll, but couldn't find any with similar dropdown. We have a similar dropdown in meshery dashboard - but that's handled via React components. So it's easy to make on there. Jekyll is a pain.

**Comment by leecalcote** [comment]
@14Richa all fair points. I agree. 

While not always obvious (there's a lot to wrangle between hundreds of contributors), we strive for our projects to delight. In this case, a visual indicator of the fact that a given menu item contains a collection of additional menu items affords for discovery of docs that might otherwise go unbeknownst to the reader.

No need to rely on Jekyll as a framework to take a small step forward in this goal. An arrow/indicator can be simply toggled on click of a menu item containing a sub-menu. No work item is too small for me to spend time on, no user delight too unimportant, and no job too dirty for my hands. Let me know if I can assist.

**Comment by 14Richa** [comment]
Sure, so what do you suggest - Do you think the current hack is good enough?

**Comment by leecalcote** [comment]
@14Richa, yes, it pretty much is good enough. An accordion-style menu using bootstrap or something similar with all menus collapsed initially might make the docs more digestible.

**Comment by 14Richa** [comment]
> @14Richa, yes, it pretty much is good enough. An accordion-style menu using bootstrap or something similar with all menus collapsed initially might make the docs more digestible.

Agree, but that'd require moving away from jekyll to bootstrap (if I understand correctly). IMO that's a bigger task than what this ticket is about. I feel we can merge this and come back to this later once the core platform UI restructuring is complete.

**Comment by leecalcote** [comment]
No, no, bootstrap would be in addition to Jekyll. Bootstrap is probably already be used in some parts of the docs.

**Review by leecalcote — APPROVED** [review]
The addition of ↆs is a step forward. 👍

**Pull request merged**
