### PR TITLE
fix: remove direct link to the source code

### LINKED ISSUE #10133: [Docs] The link is broken in https://docs.meshery.io/concepts/logical/models
### Current State

The link of [components examples](https://github.com/meshery/meshery/blob/20bbdb696a2587886b72138a3caa31723dd67197/docs/pages/concepts/logical/models.md?plain=1#L50) in https://docs.meshery.io/concepts/logical/models is broken (404).

### Desired State

We should find and link another model which have components definition.

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by RipulHandoo**
**Notes for Reviewers**

This PR fixes #10133 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 23f3c1a4fbb60d0ad0fed464f3f9fd1c91430868 at: https://65bbf913a0482f256df964ea--meshery-docs-preview.netlify.app

**Review by leecalcote — CHANGES_REQUESTED** [review]
Are you trying to hyperlink back to the same in-page anchor (section heading)? If so, you're missing `#`.

Or are you trying to link to the logical page that covers each one of these?  I think that is what you were trying to do based on our conversation and this is what you need:

```
[Relationships]({{site.baseurl}}/concepts/logical/relationships)
```

**Comment by leecalcote** [comment]
@ASK-03, @RipulHandoo doesn't feel well physically and would probably encourage your assistance. Think you can tie this off in a new PR?

**Comment by ASK-03** [comment]
> @ASK-03, @RipulHandoo doesn't feel well physically and would probably encourage your assistance. Think you can tie this off in a new PR?

Sorry to hear that! Wishing @RipulHandoo a speedy recovery! I'm here to help however I can. I'll create a PR shortly.

Thanks @leecalcote for assigning me this PR!

**Comment by RipulHandoo** [comment]
Thanks, @ASK-03, but I've updated the PR.

**Comment by RipulHandoo** [comment]
PTAL @leecalcote .

**Comment by l5io** [comment]
🚀 Preview for commit 238d60cb67b5e9aa12a3d087dcce5a30e9250d53 at: https://65bbfe9dc325a8290d4f3f60--meshery-docs-preview.netlify.app

**Comment by ASK-03** [comment]
> Thanks, @ASK-03, but I've updated the PR.

Hey @RipulHandoo! I admire your strong work ethic. Hope you get well soon! 😊

**Comment by ASK-03** [comment]
@leecalcote @RipulHandoo , I've noticed that the links seem redundant. Initially, one directed to the source code and the other to the document page, but now both lead to the document page. I suggest keeping just one link, preferably at the end of the passage.

**Comment by RipulHandoo** [comment]
> @leecalcote @RipulHandoo , I've noticed that the links seem redundant. Initially, one directed to the source code and the other to the document page, but now both lead to the document page. I suggest keeping just one link, preferably at the end of the passage.

@ASK-03 right. Now the links are at the start of the passage. Thanks.

**Comment by l5io** [comment]
🚀 Preview for commit f021453195552ae5f9af10c7acf8bf72cc331c18 at: https://65bc070aa379370497dbb47a--meshery-docs-preview.netlify.app

**Review by leecalcote — APPROVED** [review]
LGTM

**Pull request merged**
