### PR TITLE
[Docs]: Added create new file feature

### LINKED ISSUE #7252: [Docs] New Link: "Create a new child page"
#### Current State
Meshery Docs is missing a hyperlink that allows contributors to conveniently create a new docs page based on their current location in the docs.

#### Desired State

Ideally, a new link "Create new page" is available on each docs page like in the screenshot.

Screenshot 2023-03-01 at 10 30 47 PM

Use the following hyperlink format to create a dynamic link that will create a new docs file:

```
https://github.com/meshery/meshery/docs/<path to current file>?filename=change-me.md&value=---%0Atitle%3A+%22Long+Page+Title%22%0AlinkTitle%3A+%22Short+Nav+Title%22%0Aweight%3A+100%0Adescription%3A+%3E-%0A+++++Page+description+for+heading+and+indexes.%0A---%0A%0A%23%23+Heading%0A%0AEdit+this+template+to+create+your+new+page.%0A%0A%2A+Give+it+a+good+name%2C+ending+in+%60.md%60+-+e.g.+%60getting-started.md%60%0A%2A+Edit+the+%22front+matter%22+section+at+the+top+of+the+page+%28weight+controls+how+its+ordered+amongst+other+pages+in+the+same+directory%3B+lowest+number+first%29.%0A%2A+Add+a+good+commit+message+at+the+bottom+of+the+page+%28%3C80+characters%3B+use+the+extended+description+field+for+more+detail%29.%0A%2A+Create+a+new+branch+so+you+can+preview+your+new+file+and+request+a+review+via+Pull+Request.%0A
```

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by soham4abc**
**Notes for Reviewers**

This PR fixes #7252 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.
 
Added a dynamic hyperlink that allows users to create new `.md` file with the provided template.

What is looks like:
image

The page it is opening:
image

@leecalcote would you please have a look?

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 2ba7ea671cbea3f7daac578bc00d5b51501c4d62 at: https://6400cbe36c5ec800b28392a2--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit c9069ea9a055c0e0ed14747dc01c1b4d6de4956a at: https://6400cde87ae95b005897106d--meshery-docs-preview.netlify.app

**Comment by vishalvivekm** [comment]
Though it looks good to me, there's some issue with the preview while creating a new page! will you look into it @soham4abc

**Comment by soham4abc** [comment]
> Though it looks good to me, there's some issue with the preview while creating a new page! will you look into it @soham4abc

It would be very helpful if you provide information about the issue you are facing while previewing the file.

Thanks for going through my code!

**Review by leecalcote — CHANGES_REQUESTED** [review]
Cool. That was fast. 🙂 This link works in my test in Safari.

Will you please:

1) ensure that the line height is consistent between these links? Currently, this new link hugs the "Edit this page" link above it too tightly.
2) Lowercase "New Page", like so: "Create new page"

**Comment by soham4abc** [comment]
@leecalcote I have made the requested changes. Would you please have a look?

**Comment by l5io** [comment]
🚀 Preview for commit e888119732fb6ffa6419ff5d40b0ca8f8c284f5c at: https://64016c4438e261759e33b2ca--meshery-docs-preview.netlify.app

**Review by leecalcote — APPROVED** [review]
Looks great to me. 

Final thoughts, @vishalvivekm?

**Comment by vishalvivekm** [comment]
> Looks great to me.
> 
> Final thoughts, @vishalvivekm?

Yes, we can go ahead with it! @leecalcote 
Thanks @soham4abc 🚀

**Pull request merged**
