### PR TITLE
feat: Initiation of Cypress UI Testing for Meshery-UI

### PR DESCRIPTION
**Pull request by kushthedude**
Refers #987

Tests are being added for Meshery 🎉 
--

### CODE REVIEW

**Comment by kushthedude** [comment]
FYI, All of this failed tests are due to `istio-client-go` which is deprecated, See here https://github.com/layer5io/meshery/issues/989

**Comment by kushthedude** [comment]
Sorry for the confusion here, 3000 was occupied by my local grafana instance which I was not knowing. So I will be restoring the port numbers.

**Comment by leecalcote** [comment]
This PR is on-hold until a dev vs prod distinction is able to be made.

**Comment by kushthedude** [comment]
> This PR is on-hold until a dev vs prod distinction is able to be made.

This will be done by tonight, including the dockerfile changes & documentation changes :+1:.

**Comment by kushthedude** [comment]
@leecalcote It is done, now Cypress will not be bundled with our release artefacts. Also, the size of our docker image will be reduced by 50+ MB as there were 5+ dependencies which were not used in the production environment and rather were only getting used as devDependencies like ES-Lint & Babel/traverse.

**Pull request merged**
