### PR TITLE
meshery: Fixed the issue of reload on using current anchors for tabs

### LINKED ISSUE #1150: [UI] Enable sub-links for settings sub-tabs
**Description**

Right now the URL of the subtabs in settings are distinguished by `/settings#name_of_tab` which is cause of many bugs right now.

**Expected Behavior**

Have a anchor sub-URL for each tab like `settings/name_of_tab`.

### PR DESCRIPTION
**Pull request by Nikhil-Ladha**
Signed-off-by: Nikhil-Ladha <nikhilladha1999@gmail.com>

**Description**

This PR fixes #1150 also added few tweaks to UI such as addition of snackbars to keep consistency and have a good UX.  

**Notes to reviewers**

#### Checklist

- [x] [Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin).
- [x] PR title includes `[<name of area>]:<description>`

### CODE REVIEW

**Comment by leecalcote** [comment]
@Nikhil-Ladha will you confirm that the "Configure Prometheus" button the Dashboard now navigates the user all the way to the Prometheus sub-tab?

**Comment by Nikhil-Ladha** [comment]
No @leecalcote , I haven't incorporated that part yet into this change. I had a few thoughts regarding that, so kept it for a different PR. As the user preferences was a bit messed up so I thought, it's better to at least complete that part and submit.

**Comment by leecalcote** [comment]
@Nikhil-Ladha thank you for doing this PR. Feedback:

1) Let's not include a snackbar message about fetching user preferences. That should just happen w/o needing to tell the user that it happened.
2) Will you check on the population of the preference values into these fields? Text is colliding.

Untitled

**Comment by leecalcote** [comment]
Weird. Regarding 2) above, on subsequent test, I don't see text colliding.

Untitled

**Comment by Nikhil-Ladha** [comment]
> @Nikhil-Ladha thank you for doing this PR. Feedback:
> 
> 1. Let's not include a snackbar message about fetching user preferences. That should just happen w/o needing to tell the user that it happened.
> 2. Will you check on the population of the preference values into these fields? Text is colliding.
> 
> Untitled

Cool, will remove that snackbar then.

**Comment by Nikhil-Ladha** [comment]
> Weird. Regarding 2) above, on subsequent test, I don't see text colliding.
> 
> Untitled

A glitch in the matrix, I suppose 😬

**Comment by Nikhil-Ladha** [comment]
Now it's fixed, @leecalcote . We are good to go.

**Pull request merged**
