### PR TITLE
[UI] Add Connection Stats Chart

### PR DESCRIPTION
**Pull request by aabidsofi19**
**Notes for Reviewers**

- Adds Connection Stats Chart
- Makes legend svgs square 
- Adds a  column name valid check 

image

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by gopivaibhav** [comment]
Sure @leecalcote 🚀

**Review by gopivaibhav — APPROVED** [review]
Thank you @aabidsofi19 Everything looks good to me but is there a chance of mentioning deleted connections as 0 instead of not mentioning the parameter with which we are comparing?
I am new to reviewing PRs. So, this took me long to review this.

image

**Comment by aabidsofi19** [comment]
> Thank you @aabidsofi19 Everything looks good to me but is there a chance of mentioning deleted connections as 0 instead of not mentioning the parameter with which we are comparing? I am new to reviewing PRs. So, this took me long to review this.
> 
> image



> Thank you @aabidsofi19 Everything looks good to me but is there a chance of mentioning deleted connections as 0 instead of not mentioning the parameter with which we are comparing? I am new to reviewing PRs. So, this took me long to review this.
> 
> image

we can , but it will add more breaking points as  we have 5-6 different states  . as i in future we add a new state  , or rename or remove some we dont need to change anything here .

**Comment by leecalcote** [comment]
Is the empty state considered for here?

**Comment by leecalcote** [comment]
👍 
Screenshot 2023-08-10 at 5 40 57 PM

**Comment by leecalcote** [comment]
Empty State:
Screenshot 2023-08-10 at 5 44 54 PM


We could use an improvement on the empty state message, which could report "No connections available." and present this button:
Screenshot 2023-08-10 at 5 46 44 PM


You can test the empty state easily by using the Local (None) Provider

**Pull request merged**
