### PR TITLE
Add "Application" to MeshModel components

### PR DESCRIPTION
**Pull request by Revolyssup**
Signed-off-by: Ashish Tiwari <ashishjaitiwari15112000@gmail.com>

**Notes for Reviewers**

This PR fixes #

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — CHANGES_REQUESTED** [review]
Please add this schema to the MeshModels design spec.

**Comment by Revolyssup** [comment]
> Please add this schema to the MeshModels design spec.

Done

**Comment by leecalcote** [comment]
> > Please add this schema to the MeshModels design spec.
> 
> Done

@sudo-NithishKarthik a proposal has been made.

**Comment by Revolyssup** [comment]
@leecalcote Merging this as first iteration as it is required for MeshModel backend integration. This can be changed later.

**Pull request merged**
