### PR TITLE
[FIXED] mesheryctl error code conflicts solved

### PR DESCRIPTION
**Pull request by zakisk**
**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by vishalvivekm** [comment]
@zakisk Let's discuss this on Meshery Dev call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#) if you would. :)

**Review by leecalcote — COMMENTED** [review]
Is this missing ErrInvalidAPICallCode?

**Comment by zakisk** [comment]
@leecalcote it was redundant, and wasn't documented as well.

**Review by leecalcote — APPROVED** [review]
Oh, I see.

**Pull request merged**
