### PR TITLE
[Docs] Release Notes for Meshery v0.5.18

### PR DESCRIPTION
**Pull request by l5io**
An auto-generated pull request to document release notes for Meshery v0.5.18

### CODE REVIEW

**Comment by leecalcote** [comment]
Interesting, it looks like the we're accidentally grabbing the next release's notes as opposed to the current release's notes. Could be a simple change in sequencing that is needed.

**Comment by ramrodo** [comment]
> Interesting, it looks like the we're accidentally grabbing the next release's notes as opposed to the current release's notes. Could be a simple change in sequencing that is needed.

Right, I'll dig more into it. We need to take the current tag number that is already created

**Comment by leecalcote** [comment]
I think we're good to close out this PR. Is that right, @ramrodo?

**Comment by ramrodo** [comment]
Yeah, we can close this PR.

**Comment by leecalcote** [comment]
Good deal.

**Pull request closed without merging**
