### PR TITLE
Rectify misspelling in #7057 in contributing-cli doc

### LINKED ISSUE #7057: [Docs] Rectify Misspelling
#### Current State
In the User Experience ( GUI vs CLI) section in the [docs - contributing to mesheryctl page](https://docs.meshery.io/project/contributing/contributing-cli#user-experience-gui-vs-cli), `mesheryctl` is misspelled as `mesherctl`.

#### Desired State
It should be `mesheryctl`.

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by vishalvivekm**
**Notes for Reviewers**

This PR fixes #7057 
My first PR and it rectifies the misspelling in the User Experience ( GUI vs CLI) section in the [docs - contributing to mesheryctl page](https://docs.meshery.io/project/contributing/contributing-cli#user-experience-gui-vs-cli)

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.
Signed-off-by: Vivek Vishal <110674407+vishalvivekm@users.noreply.github.com>

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit cb09ce57ee7153da528c52b84db7fa2aca510336 at: https://63e8b452ccbb6b61dcb1a304--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit e8afb81973bb2d61e1bd83426b8376bb4d929e6b at: https://63e8beeb10adff6410180e84--meshery-docs-preview.netlify.app

**Comment by vishalvivekm** [comment]
Hi @leecalcote , 
I am a cs undergrad, a beginner in open source, excited to be part of a collaborative community where I can learn learn from others and make useful contributions with their help.
I have very good understanding of Java, C++, C, JavaScript, bash, HTML/CSS,SQL and know basics of Golang in learning phase.
I'd like to work on this project under the LFX mentorship's spring term ( Mar-May), and am excited that I'll get to learn from you and the community about Meshery and different technologies used in it.
Currently exploring and learning more about layer5 and Meshery.

**Review by leecalcote — APPROVED** [review]
Looking good, @vishalvivekm. It's nice to meet you!

**Pull request merged**
