### PR TITLE
Made changes in FAQ.md

### PR DESCRIPTION
**Pull request by Zubiii333**
**Notes for Reviewers**
Added a few questions FAQs. Will be adding more 
This PR fixes #

The issue stated here https://github.com/meshery/meshery/issues/8910#event-10544943524

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 352ab69b66640e5a304c4da634f2638acd1c6d09 at: https://651cf4e8e1aa4c0540edb0e5--meshery-docs-preview.netlify.app

**Comment by vishalvivekm** [comment]
@Zubiii333 Let's discuss this on Meshery Dev call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#) if you would. :)

**Comment by leecalcote** [comment]
@Zubiii333 are you going to take care of this? https://github.com/meshery/meshery/pull/9013#issuecomment-1746305401

**Comment by Zubiii333** [comment]
@leecalcote Yes sir! I'll take care of this.

**Comment by saurabh100ni** [comment]
Thanks for raising the PR, let's Discuss this in the Meshery Development Call today,
Please add this as an agenda in the Doc  : [Doc](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit)

**Comment by leecalcote** [comment]
> @leecalcote Yes sir! I'll take care of this.

@Zubiii333 are you going to take care of this? https://github.com/meshery/meshery/pull/9013#issuecomment-1746305401

**Comment by Zubiii333** [comment]
@leecalcote I genuinely apologize for the delay. Got caught up with my academics. I'll add a few QnAs as soon as I get home.

**Comment by Zubiii333** [comment]
@saurabh100ni Hi, could you please review my last PR?

**Comment by l5io** [comment]
🚀 Preview for commit 300c503cc6b787c7a8c867d431fe6b73c12f3995 at: https://652c04be412cb3057a49ee0e--meshery-docs-preview.netlify.app

**Comment by leecalcote** [comment]
> @saurabh100ni Hi, could you please review my last commit in this PR?

@Zubiii333 you're still missing sign-offs on your commits.

**Comment by leecalcote** [comment]
@Zubiii333 follow these instructions - https://github.com/meshery/meshery/pull/9013/checks?check_run_id=17717076701

**Comment by leecalcote** [comment]
@Zubiii333  a final follow up here...

**Comment by leecalcote** [comment]
@Zubiii333 and another attempt to close this out…

**Comment by Zubiii333** [comment]
PR closed. Thank you

**Pull request closed without merging**
