### PR TITLE
[ FEAT ] : Migrate Class Component to functional Component

### LINKED ISSUE #11503: [UI]: Migrate Extension Page from Class to Functional Component
### Current Behavior

Currently, the Extension Page is implemented as a class component, which can be more complex and harder to manage state and lifecycle methods compared to functional components.

### Desired Behavior

The Extension Page should be migrated from a class component to a functional component. This will simplify the codebase, make it more readable, and leverage modern React features like hooks for state and lifecycle management.

### Implementation

- Refactor the existing class component to a functional component.
- Use React hooks (e.g., useState, useEffect) to manage state and lifecycle methods.
- Ensure all functionalities of the class component are retained in the functional component.
- Update any related tests and documentation to reflect the changes.

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by senthil-athiban**
**Notes for Reviewers**

This PR fixes #11503, and #11493 

- [x] Migrated the Extension page from class to functional component without affecting react lifecycle
- [x] Migrated connection page from class to function component
- [x] Migrated RTK query for `api/provider/capabilities` 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by vishalvivekm** [comment]
@senthil-athiban 
Let's discuss this on the Meshery dev meeting starting 7:30 PM IST today. Adding it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit?usp=drivesdk)

**Comment by sudhanshutech** [comment]
@senthil-athiban is this good to go?

**Comment by senthil-athiban** [comment]
@sudhanshutech, added RTK migration as well, and we're good to go.

**Comment by Ashparshp** [comment]
@senthil-athiban, did we discuss this in the meeting?

**Pull request closed without merging**
