### PR TITLE
Fixed height consistency in design cards

### LINKED ISSUE #8470: [UI] Make the card heights consisitent
### Current Behavior

Presently, there exists an inconsistency in the heights of the cards within the configuration. To rectify this,  ensure that these cards dynamically adjust their heights based on the tallest component present, thus achieving uniformity in their appearance.

### Screenshots/Logs

image

### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by EraKin575**
**Notes for Reviewers**

This PR fixes #8470 

**Before**
image

**After**
fixed height consistency
image

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by aabidsofi19** [comment]
@EraKin575  can you address  the above comments , so we will be good to merge this .

**Comment by EraKin575** [comment]
@aabidsofi19 do you refer to the failed PR tests?

**Comment by aabidsofi19** [comment]
No the comments i put in review

**Comment by EraKin575** [comment]
@aabidsofi19 i am sorry i dont see any review comments on the pr

**Comment by aabidsofi19** [comment]
image

**Review by aabidsofi19 — APPROVED** [review]

**Comment by EraKin575** [comment]
@aabidsofi19  will you take a look?

**Comment by aabidsofi19** [comment]
Let's merge this

**Comment by EraKin575** [comment]
@aabidsofi19 please inform me if there is anything left to do while this PR gets merged

**Pull request merged**
