### PR TITLE
[Docs] Format <details> with HTML tag not markdown - Update contributing-models.md

### PR DESCRIPTION
**Pull request by hamza-mohd**
**Notes for Reviewers**

This PR fixes a display issue on this page - https://docs.meshery.io/project/contributing/contributing-models#contribute-to-meshmodel-relationships

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 32b5f03768a871c5218e4eca6c27e3a56a9b0bf0 at: https://65ce6c71d7ea8b2f13149279--meshery-docs-preview.netlify.app

**Review by leecalcote — APPROVED** [review]
lgtm

**Comment by l5io** [comment]
🚀 Preview for commit 79ced4cd02458ced08898e31ae506b8509a62743 at: https://65ce70e35da8fe34013b8a13--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 61921cd2c4ac2b8508b314a31bc2fd47367def8b at: https://65ce72f3a30c9b30e7a98bbf--meshery-docs-preview.netlify.app

**Comment by vishalvivekm** [comment]
@leecalcote 
image

**Review by vishalvivekm — APPROVED** [review]
LGTM

**Review by leecalcote — APPROVED** [review]
Aha! Whitespace!

**Pull request merged**
