### PR TITLE
[Docs] fixes #1748 SVG of Meshery Architecture Diagram

### LINKED ISSUE #1748: [Docs] Revert Meshery Architecture diagram to SVG
**Current State:**
The first arch diagram on [this page](https://meshery.layer5.io/docs/architecture) uses a png not an svg like the others. 
The docs should be using vector-based images where possible, not rasterized images. The image is of poor quality and has an errant, floating OSM icon on it.

**Desired State:**
1. Download this diagram as an SVG from the [Meshery Architecture deck](https://docs.google.com/presentation/d/1SQMfyu5shjpGKlYONdVzOtd7UYTgLWBcgUvHMLCZ2tY/edit#slide=id.ga01cadb669_0_0).
1. Delete .png image and replace with SVG.

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

### PR DESCRIPTION
**Pull request by DanRowe**
Signed-off-by: Daniel Rowe <daniel@drowe.dev>

**Description**
Replaced Meshery Architecture diagram PNG with SVG.

This PR fixes #1748 

**Notes for Reviewers**
This is my first pull request so let me know if everything looks all right!

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — APPROVED** [review]
Whoa. Quick work, @DanRowe1. Thank you! 👍

**Comment by leecalcote** [comment]
Beautiful. Complete with commit sign-off and with reference to the fixed issue.  🤔 I'm having a hard time finding something to complain about, @DanRowe1. I'm not sure that I like this.

Hey! Look at that! I did find something to complain about. 😄 Thanks, @DanRowe1.

**Comment by DanRowe1** [comment]
Happy to help! @leecalcote

**Comment by leecalcote** [comment]
There's plenty more bad jokes to be had where those come from, @DanRowe1. You're most welcome to join the Layer5 community - http://slack.layer5.io. It's a welcoming place.

**Pull request merged**
