### PR TITLE
lang dropdown selector, toc for each lang, all files included for all…

### LINKED ISSUE #1789: [Docs] Internationalization and localization of Meshery Docs (i18n compatible)
**Current State:**
Meshery documentation is being translated to other languages than English. 

**Desired State:**
Incorporate the https://github.com/kurtsson/jekyll-multiple-languages-plugin plugin into Meshery's documentation system.

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

### PR DESCRIPTION
**Pull request by alonsolopezr**
… languages, front matter edited for each lang. Translated pages added for es and tr languages

Signed-off-by: JOSE ALONSO LOPEZ ROMO <alonso.lopez.r@gmail.com>

**Description**
modification of docs/folder and reorganization of these, to accomplish:
* Multilang dropdown
* sidebar in lang selected
* links of each language in index, translated
* front matter and permalinks adjusted
* data nav and tocs added for each lang
* several translated pages added for es/ and tr/
* The rest of the pages en base english site, added for es/ and tr/ as well (templates)

In the need of another lang... few things will be needed to modify: adding _data/translations lang.yml; add the language to _data/languages to be displayed in the dropdown; add the _data/tocs/toc_lang.yml for the sidebar to display correctly. And all the pages with their front matter considering the vars: lang, language, categories (the same value on three). And the permalink with the language added to, like: permalink: es/page/page 

This PR fixes #1789 
[Docs] Internationalization and localization of Meshery Docs (i18n compatible) #1789

**Notes for Reviewers**
Please @jesuslerma, @chandrashritii, validate this. Tell me if the folder structure is ok. I think there are too way files that got pushed. From the vendor/ I assumed.

**[Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by chandrashritii** [comment]
This looks really great @alonsolopezr. Amazing work here 🎈  As we discussed, it might need some cleaning up before it can be merged -
- A few of the links are still breaking 
- The liquid tags should be modified to pull up only translated pages when you switch to a certain language
- As you mentioned, a few invalid changes and extra files have been added to the commit in addition to the modified files. We should do a customary check to make sure its not breaking any other site components
- The exact workflow for adding translations should be written down for future contributors who wish to translate the Meshery documentation.

**Comment by alonsolopezr** [comment]
Thanks @chandrashritii for the comments... you think including the var "list: exclude" will do the trick on this on the permalinks?? or do we need anything else??
And yes... the pull must be done very clean, to ensure only docs are impacted.
And I would really like to contribute in whatever I may in the guide for the translates contrib...
Thanks again @chandrashritii and have a great week...
I will continue working on this till is done

**Comment by alonsolopezr** [comment]
Hello again @chandrashritii and @jesuslerma, I did a clean 'docs' edit again. 
*Resolved all the broken links (I identify some of the actual English site... but those to be resolved in another PR) 
*I translated the whole site to Spanish (there where 3 or 4 section to be translated)
* Changed toc logic
* Changed listing logic in the section's index.md

I tested and everything is rendered... please check this out, and tell me about it.

Thanks in advance

**Comment by alonsolopezr** [comment]
Hi @chandrashritii, @jesuslerma, there where 2 conflicts about 2 md files. I already fix them here.
Please, check this.... any validation or feedback would be appreciated 👍🏼
Thanks in advance

**Comment by alonsolopezr** [comment]
I think I resolved the last git conflicts right... I took the actual content of the two md pages, and the make file to correct this... please check this also @chandrashritii and @jesuslerma 

Thanks in advance

**Comment by chandrashritii** [comment]
Hey @alonsolopezr I'm sorry for the late reply. The toc and rendering works. I went through the entire site again as well. A couple of points to consider before we go for a final review - 
1. All the pages should have *translated headers* present on the index page for each language. If the page isn't available in the chosen language, a template 404 page should be offered with links to the page in English and any other available languages rather than simply redirecting to the English translation.
2. The drop down menu should  by default show English as the chosen language rather than *lang*
3. Can the permalinks be translated as well?
4. The headers of the header bar and the right index bar should be translated as well.

These aren't big changes but will definitely need a bit of discussion. The permalinks part might especially take a bit of a manual effort. As we discussed before, I'll help you with that. Let's discuss and get it done this week. Great job here! ⭐

**Comment by alonsolopezr** [comment]
Thanks for the review @chandrashritii... 

All the pages should have translated headers present on the index page for each language. 
-> I think they are now... if I understood this characteristic... 
-> The English index, has the pages titles in English. The Spanish index page, has the titles display in Spanish and so on.
-> is this the correct idea? or is there an index page that doesn't work list this?

If the page isn't available in the chosen language, a template 404 page should be offered with links to the page in English and any other available languages rather than simply redirecting to the English translation.
-> ok, cool, let me try on this... 
-> this sould be displayed by a script on the 404 logic, right? could be??

The drop down menu should by default show English as the chosen language rather than lang
-> Yes, the is easy... The thing is after the page with the selected language is loaded, the  "value" reestablish always to this first one, in this case, would be English... I started to try to fix one by a get parameter in the link, or something like that, ... but I left it as is, in the effort to finish it first.
-> let's explore on the possible solutions please

Can the permalinks be translated as well?
-> yes, well I think it would be no problem... but, I thought of the permalink as the "common" bond between languages, I mean, of course the filename and where the filename is good to identify every original file and the translations of it... but also with the permalink, it is easier to find errors, and track which file is correspondent to which translation.
-> also for the files that have graphics or assets that are 'named' similar
-> but, anyway, yeah, it could be done, because we have all the font matter section of each file modified as well

The headers of the header bar and the right index bar should be translated as well.
-> yes, I forgot about these on the header jejejej... yes, I will proceed as the same with the toc
-> the right index bar is rendered by the docs/_includex/navigation.html right?


Thanks, and I push these changes tomorrow, or tonight... 
Have a great Saturday

**Comment by alonsolopezr** [comment]
Hello again, dear @chandrashritii  and @jesuslerma, please review this...

So I fixed the lang dropdown, it now only shows the lang selected, and it stay selected until it is changed.
Also I translated the nav links
Also Translated the right sidebar...

Only thing left would be the permalink, and the 404 stuff....

Also, I'm seen right here, in the PR checks, that my branch is out-of-date... And I did make sure of fetch/merge etc in my local....So I guess, it would be better to copy this /docs folder, ditch my local repo, clone again master and paste the docs in the "new" repo again?? heheheh, please, tell me what you think.

Have a nice weekend

**Comment by shubhank-saxena** [comment]
Hello @alonsolopezr . Thank you for this great work! 
Some feedback regarding the preview I saw -
1. The landing of the 404 page resets the language. So we need to prevent that.
2. Selection of language on any other page except for homepage redirects back to the homepage. Not sure if this is needed, but can we keep the translation and yet show the page in focus?
3. Permalink is still there (as mentioned by @chandrashritii )
4. Not associated with this PR, but can we fix the auto-scroll of the sidebar every time we select a submenu? The navbar resets itself and it's kinda confusing to navigate around.

**Comment by alonsolopezr** [comment]
Thanks @shubhank-saxena por the review... I really appreciate it. 
1. I haven't been able to start working about 404.. but I will start with this.
2. Yes I also noticed this as an issue. I think that preserve the actual permalink or something like that, and then when the lang change is triggered, we can concatenate this to the href,,,, or something like that. I don't know if Jekyll does have a property like the "actual", "back" url, that would be definitely he solution.
3. I really need for you all to consider this, and if permalink have to be translated, let's go with that. But, as I mention before, I really think the permalink is more useful if it is "unique", and only the "lang" part of it is changed. Example: https://docs.meshery.io/installation/platforms/docker would be for "en"... https://docs.meshery.io/es/installation/platforms/docker would be for Spanish and https://docs.meshery.io/tr/installation/platforms/docker would be for Turkish and so on... so it is always the same, it is easy to track and update, etc.
4. YES! I also consider this somehow "confusing" sometimes jejejej because it "moves" the whole toc. I think this could be achieved from css... but let's explore on this.

THANKS AGAIN... have a great midweek

**Comment by leecalcote** [comment]
@alonsolopezr regarding #2, one option is to use a variation of something like this:

```
<script>
                  function changeLang() {
                    var langSelector = document.getElementById("langSelection");
                    var lang = langSelector.options[langSelector.selectedIndex].value;
                    window.location=lang+"{{page.url}}";
                }
                </script>
                <select onchange="changeLang(this.value)"
```

**Comment by alonsolopezr** [comment]
Yes, that is a good choice... sorry for answering so late... I was kind of lost between msgs! Thanks Lee!!

**Comment by leecalcote** [comment]
Let's give this one final, last push... ping me @alonsolopezr, if a collaborative review is helpful.

**Comment by alonsolopezr** [comment]
Yes, I'm a mess with my time right now.... but I'm taking this weekend full on this, and the other messages/notifications issue too... for which I'm still not sure were to render it ?

**Comment by alonsolopezr** [comment]
So, let me get this on track this couple of days and then ping you up for a review.... thanks @leecalcote 🎉

**Comment by leecalcote** [comment]
You’re right. We need a small design spec for the Latest Happenings/Current Events notification feed. 

The original idea is that this feed will load in Internet-connected Meshery UIs, such that along with the resources links, there would be one for Latest News (or something similar).

**Comment by alonsolopezr** [comment]
Hi again... So I'm trying to retake full on this PR. I fixed the Point Number 2 by @shubhank-saxena on the page "reset" to the main index page of the docs, when the language was changed and selected.
So please @shubhank-saxena , @chandrashritii , @jesuslerma, @leecalcote .. maybe someone can check this one.
I'm also going to update the files that had been changing in content.
And besides this, I think the only thing left would be the 404 stuff, AND FIX SOME BROCKEN LINKS...
https://deploy-preview-2411--meshery-docs.netlify.app/
So, please check this out. And have a great weekend. THANKS

**Comment by alonsolopezr** [comment]
Hi... So, for the 404 translate... I'm not getting it down... and that's because the 'exception' triggered by the static sites, goes down to it's main english 404.md, and that's it. It may be "changed" by the dropdown lang selector when in the actual 404... 
Captura de Pantalla 2021-04-04 a la(s) 16 48 02

but the langs just resets when a 404 and I haven't managed to translate acording to the lang previously selected by user.
(reference to it...https://github.com/kurtsson/jekyll-multiple-languages-plugin/issues/156)

But anyways, I translated the respective 404.mds.
So I think the only thing left is including langs vars in front matter of updated files, and try to nail the broken links down. And that's it...
So please, anyone check this... THANKS IN ADVANCE

**Comment by alonsolopezr** [comment]
> You’re right. We need a small design spec for the Latest Happenings/Current Events notification feed. The original idea is that this feed will load in Internet-connected Meshery UIs, such that along with the resources links, there would be one for Latest News (or something similar). screenshot - https://user-images.githubusercontent.com/7570704/113436912-3e5e7300-93ab-11eb-82f9-73b9c6073a9b.png

So, This would have to be consumed by an API of something!?!? I'm on the right track here? Because, the "dominion" of the docs is it's "context" folder.. so I've been looking into these Jekyll API stuff, and there are actually some things done with it... so, It could be a possibility... BUT FIRST... It this the actual IDEA to be done??

Thanks in advance

**Pull request closed without merging**
