### PR TITLE
Environment Page MUI v5 update

### PR DESCRIPTION
**Pull request by SAHU-01**
**Notes for Reviewers**

This PR fixes part of https://github.com/meshery/meshery/issues/11493 , based on [this](https://docs.google.com/spreadsheets/d/1RlUcr-iLtCFCsV1VZvWD0jBijPJAx-Rk-1GLLsL9sSI/edit?usp=sharing) sheet , the environments page and its related components have been migrated to use sistent components and necessary mui v5 changes have been applied to these pages.

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
@SAHU-01 a couple of prettier lint checks to address - https://github.com/meshery/meshery/actions/runs/10923412294/job/30319963878?pr=12061#step:3:38

**Review by sudhanshutech — CHANGES_REQUESTED** [review]
@SAHU-01 use the sistent specific tokens.

**Comment by SAHU-01** [comment]
> @SAHU-01 use the sistent specific tokens.

Sure @sudhanshutech, i'll update these  before the weekend ends, Thanks!

**Comment by sudhanshutech** [comment]
merge conflicts...

**Pull request closed without merging**
