### PR TITLE
Update reference table in docs

### LINKED ISSUE #10503: [mesheryctl] `registry` docs published under `exp` when command has been promoted already
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

### Current Behavior
Docs for `mesheryctl registry` are published at https://docs.meshery.io/reference/mesheryctl#experimental-features

### Desired Behavior

Should point to https://docs.meshery.io/reference/mesheryctl/system/registry

### Environment

- Host OS: Mac 
- Meshery Client Version: stable-v0.7.26

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- 📺 [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- ⌨️ [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- ⌨️ [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by alphaX86**
**Notes for Reviewers**

This PR fixes #10503 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 71d092fa158a4865f0a9e277bb432833d042278f at: https://65e899c176bd4a18ce8c149e--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit bd8071a614d5eb344534959c52c0f6cfcbb6ddbd at: https://65e89d23bd34661d63535177--meshery-docs-preview.netlify.app

**Review by leecalcote — CHANGES_REQUESTED** [review]
Thank you, @alphaX86. Will you update the mesheryctl GitHub issue templates to include a checklist that has a link to this task? https://docs.meshery.io/project/contributing/contributing-cli#adding-newremoving-existing-commands-in-the-reference-index

**Comment by leecalcote** [comment]
@Althaf66 @RipulHandoo @vishalvivekm @hexxdump @aboobakersiddiqr63 @MUzairS15  @meshery/mesheryctl-contributors @meshery/mesheryctl-maintainers please be aware of this manual step - https://docs.meshery.io/project/contributing/contributing-cli#adding-newremoving-existing-commands-in-the-reference-index

**Comment by alphaX86** [comment]
> Thank you, @alphaX86. Will you update the mesheryctl GitHub issue templates to include a checklist that has a link to this task? https://docs.meshery.io/project/contributing/contributing-cli#adding-newremoving-existing-commands-in-the-reference-index

Sure Lee, will update it. I'm thinking whether to automate the index itself to avoid this manual issue. Either via a script or with a help of library.

**Pull request merged**
