### PR TITLE
Fix: Added Responsive Style for Dashboard charts. Signed-off-by Danan…

### LINKED ISSUE #9610: [UI] Dashboards not mobile friendly
### Current Behavior
The dashboards are not responsive / Mobile friendly. 

### Desired Behavior
All pages, including the dashboards should be more friendly 

### Screenshots/Logs

image
### Environment

- Browser:  Safari
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v0.7.0

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by Dananjay996**
…jay996 w/signoff

**Notes for Reviewers**

This PR partially fix #9610 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Thanks, @Dananjay996. Are there any adjustments needed for the other dashboard pages?

**Comment by Dananjay996** [comment]
Hey @leecalcote , I went through the other dashboards when I was fixing this initially and I did not find any non-responsive ones. I will check it through once again and will let you know. Also let me know if there are some non-responsive ones left. Thank you!

**Comment by leecalcote** [comment]
Workloads --> Deployments, for example is responsive?

**Comment by abhijeetgauravm** [comment]
Hey @Dananjay996  Let's discuss this on Meshery Development Meeting today at 8:30 PM IST / 9 AM Central time. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#).

**Comment by Dananjay996** [comment]
Okay sure, @abhijeetgauravm

**Review by theBeginner86 — APPROVED** [review]

**Comment by theBeginner86** [comment]
thank you @Dananjay996!

**Comment by theBeginner86** [comment]
We would need to separately address the tables. @Dananjay996 
Example:

Screenshot 2023-12-13 at 11 42 20 PM

**Pull request merged**
