### PR TITLE
Consolidate mesheryctl app into pattern

### LINKED ISSUE #10275: [mesheryctl] Support for consolidate mesheryctl app into mesheryctl pattern
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

### Current Behavior

There is commands like **mesheryctl app** and **mesheryctl pattern**. We didn't need two seperate command, so we consolidate **mesheryctl app** into **mesheryctl pattern**.

### Desired Behavior

We need to consolidate **mesheryctl app** into **mesheryctl pattern**.

### Acceptance Tests

- [ ] Consolidate app into pattern
- [ ] Update documentation

---

### Contributor Resources

- ⌨️ [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](http://discuss.meshery.io) and [Layer5 Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by Althaf66**
**Notes for Reviewers**

This PR fixes #10275 

Support for consolidating mesheryctl app into pattern.

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — COMMENTED** [review]
@Althaf66 please look into the failing lint checks. Will you also itemize each of the subcommands that you've moved over from `app` to `pattern`?

**Comment by saurabh100ni** [comment]
Hi @Althaf66 ,
Thanks for your PR! I encourage you to share this in the Meshery Development Meeting today at 8:30 PM IST. Share your screen, and walk us through it. It's cool to take and share feedback. Check the [Doc](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit) here to include this PR.

You're welcome at the meeting

Check to [community calendar](https://layer5.io/community/calendar) for more details of meetings at Layers.

**Comment by leecalcote** [comment]
Pending an answer to my question...

**Comment by Althaf66** [comment]
mesheryctl app has 5 commands. import, list, view, offboard, onboard. Due to repeatition with pattern commands, list is changed to listapp and view is changes to viewapp.

**Comment by leecalcote** [comment]
> mesheryctl app has 5 commands. import, list, view, offboard, onboard. Due to repeatition with pattern commands, list is changed to listapp and view is changes to viewapp.

Nooooo. That won't work. You're missing the point.

**Review by MUzairS15 — CHANGES_REQUESTED** [review]
@Althaf66 Navigate to the UI and under the configuration tab check we have only `Designs` and `Filters`.
Applications are no longer a construct, so `listapp` and' viewapp'.... are not required.

The ask here is to make both clients the same (UI and mesheryctl).
The Patterns API is the only thing that you need to call to list, view, onboard, and offboard (all these operations are being done in the existing pattern command).

So, delete all the app commands. 
Add a new flag source type to filter on source type (K8sManifest, Helmcharts,Designs)...
refer to the UI to get more details. Whatever UI supports exactly same needs to be added to the mesheyrctl pattern command.

**Comment by leecalcote** [comment]
@Althaf66 have you account for the feedback, yet?

**Comment by Althaf66** [comment]
Yes, I completed the issue as per @MUzairS15 said. Could you please review it.

**Comment by RipulHandoo** [comment]
Due to lack of response to reviews from the maintainer over an extended period, we're closing this PR. While it addressed the issue, timely review is crucial. We appreciate your contribution and encourage ongoing engagement.

**Pull request closed without merging**
