### PR TITLE
[UI]: Remove unused code in Filter.js

### PR DESCRIPTION
**Pull request by senthil-athiban**
**Notes for Reviewers**

This PR fixes #

- [x] Remove the endpoints and functions of deploy, and undeploy
- [x] Remove userPref query: As I notice there is no state used from useState for user pref data.

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by dottharun** [comment]
@sudhanshutech, do we need to use schema from sistent here?

**Comment by sudhanshutech** [comment]
Yes @dottharun , @senthil-athiban don't change the schema part since it will be used from sistent and there is already a pr which i will merge today.

@dottharun yo didn't removed the deploy and undeploy functionality since its not been used?

**Comment by sudhanshutech** [comment]
@dottharun please ensure @senthil-athiban is doing rtk migration at those places where its left.
@senthil-athiban see the rtk migration tracker  spreadsheet in the issue or search codebase with datafetch and change that to rtk . I thing deploy and undeploy is not being used in filter so it can removed completely and schema will sistent.

**Comment by dottharun** [comment]
@sudhanshutech I think mine was merged before I could make the change. We need to remove those.

**Comment by senthil-athiban** [comment]
@sudhanshutech @dottharun Do I need to remove schema, deploy and undeploy ?

**Comment by dottharun** [comment]
> @sudhanshutech @dottharun Do I need to remove schema, deploy and undeploy ?

For schema: Revert the changes in this PR.
For deploy and undeploy: Make changes and remove the endpoints and functions from master.
For userPref query: Investigate if it's used anywhere, as I notice there is no state used from useState. Remove if not used anywhere.

**Comment by senthil-athiban** [comment]
Thanks @dottharun

**Comment by senthil-athiban** [comment]
> @dottharun please ensure @senthil-athiban is doing rtk migration at those places where its left. @senthil-athiban see the rtk migration tracker spreadsheet in the issue or search codebase with datafetch and change that to rtk . I thing deploy and undeploy is not being used in filter so it can removed completely and schema will sistent.

@sudhanshutech some of the components are not listed in the spreadsheet which needs to be migrated to RTK such as Header, and so on.

**Comment by senthil-athiban** [comment]
@sudhanshutech @dottharun seems to be like deploy and undeploy are used in [confirmation modal](https://github.com/meshery/meshery/blob/master/ui/components/Filters.js#L1383), can we remove the confirmation modal ?, it doesn't used anywhere, correct me if am wrong.

**Comment by dottharun** [comment]
> @sudhanshutech @dottharun seems to be like deploy and undeploy are used in [confirmation modal](https://github.com/meshery/meshery/blob/master/ui/components/Filters.js#L1383), Can we remove the confirmation modal? It isn't used anywhere, correct me if I'm wrong.

Yes, Remove if not used anywhere.

**Comment by Ashparshp** [comment]
@senthil-athiban let's discuss this PR during the Meshery dev meeting call, if you would. Please add it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit?usp=drivesdk).

**Review by sudhanshutech — APPROVED** [review]

**Comment by sudhanshutech** [comment]
@senthil-athiban everything works fine right all other functionalities ?

**Comment by senthil-athiban** [comment]
@sudhanshutech, seems to be everything is fine.

https://github.com/user-attachments/assets/86059325-248d-454a-9956-e27057c2af24

**Review by sudhanshutech — APPROVED** [review]

**Pull request merged**
