### PR TITLE
Improve meshery pattern list error message

### PR DESCRIPTION
**Pull request by Ebi27**
**Notes for Reviewers**

Made a correction to the error message by changing the 'MESHERY' to be displayed to 'Meshery'. Added the function to the test file to ensure it is displaying the correct error message. 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 143b17e18ac27c53d59ccb196110d0cb52bfa1c0 at: https://63c346f16b470a6b2c739d5b--meshery-docs-preview.netlify.app

**Review by ayushthe1 — CHANGES_REQUESTED** [review]
I dropped my suggestions in the slack.

**Comment by leecalcote** [comment]
Please use a descriptive PR title, @Ebi27.

**Comment by leecalcote** [comment]
Follow the instructions in the contributing.md (or in the contributing sections of docs.meshery.io) to ensure that your dev env is configured to automatically add your signoff on your commits.

**Comment by l5io** [comment]
🚀 Preview for commit 862c03a5b99b27eb050d920b27f712092014d1da at: https://63c4b0400b341354c2f291e2--meshery-docs-preview.netlify.app

**Comment by Ebi27** [comment]
Just leaving this here. My problem right now is mainly in resolving the conflicts as my clone was done 3 months ago, alot has happened during that period. I have tried everything on the internet and I figured I need to go back to the root, so I'll be taking another git course and then retrying afterwards. Thank you for your kind understanding.

**Comment by ayushthe1** [comment]
@Ebi27 ,you don't need to take course . Just follow these steps and your problem will be surely solved :
  
* Delete your forked version of repository on github and also delete it from your local system. 
* Again fork the repository on github (this   way you will get the latest version of Meshery)
* Clone that repo onto your local system. 
* make the desired changes and then commit using `git commit -s -m "msg"`,-s for the sign-off.
* push the changes to origin. 

This I think would be the easiest path for you to take. I understand that your repo is cluttered with too many changes and is also not updated, so start fresh from the latest version of repo and from a new clean branch.

**Comment by Ebi27** [comment]
Oh, thank you @ayushthe1. That's exactly the issue I'm facing. I'll follow your suggested steps now. Thanks alot! Really appreciate your help.

**Comment by Ebi27** [comment]
Hey @ayushthe1 I thought to update you. I did as you advised which worked and then I saw you already made the "MESHERY" to "Meshery" correction I was trying to make. Thanks again, for your kind help. Really appreciate it.

**Pull request closed without merging**
