### PR TITLE
Add alphabetical sorting to the Adapter Operation lists

### LINKED ISSUE #1670: [UI] Sort Adapter Operations Alaphbetically
**Current Behavior**
Each Meshery Adapter's operations are read from the respective adapter in real-time when a user navigates to a particular service mesh page. There is no guaranteed ordering of the list of supported operations that the adapter will respond with. So, users will see a different order of menu items (sported operations) each time that they load the page. See screenshots:

First load of the Istio page:
Screen Shot 2020-10-11 at 11 25 35 AM

Second load of the Istio page:
Screen Shot 2020-10-11 at 11 25 28 AM

**Desired Behavior**
Supported operations should be shown in the same order each time a user loads the page. Operations should be alphabetically sorted by name of the operation in the UI.

### PR DESCRIPTION
**Pull request by tangledbytes**
Signed-off-by: Utkarsh Srivastava <srivastavautkarsh8097@gmail.com>

**Description**
This PR adds alphabetical sorting to Meshery Adapter operations list. 

This PR fixes #1670 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — APPROVED** [review]
Thank you, @utkarsh-pro

**Comment by leecalcote** [comment]
@utkarsh-pro we have a similar issue with the alphabetical listing of adapter operations that are dynamically loaded each time the `/management` page for each adapter is loaded. The operation names are retrieved from the respective adapter with each load of the page and not received is the same order each time, but in a different order each time. 

Do you mind looking into this? A new issue will need to be created.

**Comment by leecalcote** [comment]
Ha! I thought I was looking at a PR on the alphabetical listing of the names of service meshes In the `performance` page (another issue recently raised for adding new entries to that list). Could you take a quick look over there and confirm that those names are being alphabetically list (except for the name of a discovered service mesh, which is present above the fold/line)?

**Comment by utkarsh-pro** [comment]
> Ha! I thought I was looking at a PR on the alphabetical listing of the names of service meshes In the `performance` page (another issue recently raised for adding new entries to that list). Could you take a quick look over there and confirm that those names are being alphabetically list (except for the name of a discovered service mesh, which is present above the fold/line)?

Are we talking about this page?
meshery_performance_ui

Here the list of service meshes is not sorted. I can create another PR for this.

**Pull request merged**
