### PR TITLE
[Relationships] Dapr: Add dapr relationships

### PR DESCRIPTION
**Pull request by innocentrda**
**Notes for Reviewers**

This PR fixes #

This PR defines relationships between [Configuration](https://docs.dapr.io/reference/resource-specs/configuration-schema/), [Subscription](https://docs.dapr.io/reference/resource-specs/subscription-schema/), [Resiliency](https://docs.dapr.io/reference/resource-specs/resiliency-schema/) and [Component](https://docs.dapr.io/reference/resource-specs/component-schema/) dapr resources. 

It is suggested to make this relationship Sibling since Configuration, Subscription,  Resiliency and Component dapr resources are at the same hierarchical level. Similarly to a Service and a Pod, where a Service reference a Pod to allow pod networking, Resiliency features can intercept Component to enable some control to Component failures. With the components target defined in Resiliency resource, you can apply retry, timeout and circuitBreaker policies to Component operations.

Screenshot from 2024-05-28 11-07-35

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by yaron2** [comment]
Hi, Dapr maintainer here. Siblings would be the correct way to represent Dapr components.

**Comment by innocentrda** [comment]
> Hi, Dapr maintainer here. Siblings would be the correct way to represent Dapr components.

**Review by leecalcote — CHANGES_REQUESTED** [review]
@innocentrda, please go back to the drawing board on this proposal.

**Comment by innocentrda** [comment]
> @innocentrda, please go back to the drawing board on this proposal.

@leecalcote Do you have another idea of what type this relationship could be?

**Comment by leecalcote** [comment]
@yaron2, @salaboy, here's a revision on the proposed visual relationship. 

Screenshot 2024-06-21 at 4 34 49 PM

**Comment by leecalcote** [comment]
#### Propose Dapr Component Visualization #2: Pluggable Function

A second, deeper level of visualization is that of having the Dapr Component's pluggable function (e.g. logger, secret store, pub/sub, etc.) captured as a configuration artifact of the Dapr Component. Please see the following short screen recording as an example. Replace "wasm-plugin" with "dapr-component" and its configuration artifact (its variant) as the  "HTTP Filter". The "HTTP Filter" would be the Dapr Component's pluggable function (e.g. logger).


https://github.com/meshery/meshery/assets/7570704/455f01f2-ac97-415c-85e4-36fea731a397

**Comment by yaron2** [comment]
@leecalcote @innocentrda would you be interested in presenting this work on one of our Dapr community calls?

**Comment by leecalcote** [comment]
@yaron2, most certainly, yes. Name the date/time and we'll be there.

**Comment by yaron2** [comment]
> @yaron2, most certainly, yes. Name the date/time and we'll be there.

Great! The next one is on July 10th, if you can make it just leave a comment there with a brief description of what you'll show and one of our community managers will be in touch: https://github.com/dapr/community/issues/489

**Comment by yaron2** [comment]
@leecalcote will you be coming to the community call tomorrow on July 10th?

**Comment by leecalcote** [comment]
Thanks for messaging, @yaron2.  I missed your earlier note. Yes, tomorrow at 9am PST. We’ll be there. 👍 I’m adding an agenda item comment now…

**Comment by yaron2** [comment]
> Thanks for messaging, @yaron2. I missed your earlier note. Yes, tomorrow at 9am PST. We’ll be there. 👍 I’m adding an agenda item comment now…

We are skipping tomorrow's call as we didn't get the agenda sorted in time. Feel free to sign up for the July 24th call

**Pull request merged**
