### PR TITLE
[UI]Added EventListner in SliderButton

### PR DESCRIPTION
**Pull request by Harshit-Dandriyal**
Signed-off-by: Harshit-Dandriyal <dandriyalh9318@gmail.com>

**Description**
Before this PR, We have to click exact on our arrow icon(faAngleLeft) which can disturb UI experience. 

https://user-images.githubusercontent.com/56961488/160255899-fb26a443-3fd9-48fa-b3a0-b433ed4e0b30.mp4

--------
After this PR, I created EventListener in SlideButton, So, it can use it in same way by clicking whole button.

https://user-images.githubusercontent.com/56961488/160255854-7fa0cf79-e66c-47a7-ba32-a77183f2107d.mp4

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
@YashKamboj will you review?

**Comment by YashKamboj** [comment]
Yeah!! @leecalcote

**Review by YashKamboj — CHANGES_REQUESTED** [review]
@Harshit-Dandriyal Instead of adding a EventListner , if you move the `onClick` in the `div` it will work just fine and it would be easier to implement.

**Comment by Harshit-Dandriyal** [comment]
@YashKamboj Yes, you are Right, I am updating my PR

**Comment by Harshit-Dandriyal** [comment]
@YashKamboj Thank you :)

**Review by YashKamboj — APPROVED** [review]
LGTM!!, Nice Work @Harshit-Dandriyal

**Review by Chadha93 — APPROVED** [review]
@Harshit-Dandriyal good update :1st_place_medal:

**Review by warunicorn19 — APPROVED** [review]
LGTM! Thanks @Harshit-Dandriyal

**Pull request merged**
