### PR TITLE
solved the issue of unresponsiveness of header

### PR DESCRIPTION
**Pull request by AdityaRaimec22**
**Notes for Reviewers**

This PR fixes #

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit d49fa521c1f8225b8107d16f4ce6a336bc61b992 at: https://64c9db6ff095665df0e47d65--meshery-docs-preview.netlify.app

**Comment by vishalvivekm** [comment]
@AdityaRaimec22 Let's discuss this on Meshery Dev call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#) if you would. :)

**Review by leecalcote — COMMENTED** [review]
Thanks. What issue does this fix?

**Comment by AdityaRaimec22** [comment]
@leecalcote #8072 it solves

**Comment by l5io** [comment]
🚀 Preview for commit 024ad96ebd9ee2e145badbe2366a5674e225d250 at: https://64cfb3f24077e059948fe405--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 75181e7cc1e0e2d9cad6c52072d9388c96684d91 at: https://64d06d42a3461a2e0f47eb18--meshery-docs-preview.netlify.app

**Comment by leecalcote** [comment]
Thanks, @AdityaRaimec22 🎈

**Pull request merged**
