### PR TITLE
[Docs] Release Notes for Meshery v0.5.25

### PR DESCRIPTION
**Pull request by l5io**
An auto-generated pull request to document release notes for Meshery v0.5.25

### CODE REVIEW

**Comment by leecalcote** [comment]
@ramrodo, you're working to shift away from a a system of having an ongoing pre-release PR that captures release notes as we go, and to the prior system of capturing the entirety of the release notes at time of release, right?

**Comment by ramrodo** [comment]
> you're working to shift away from a a system of having an ongoing pre-release PR that captures release notes as we go, and to the prior system of capturing the entirety of the release notes at time of release, right?

Yes @leecalcote. Right that. Now we're having a PR that is updated every merge to master. Let's see how this works.

**Comment by leecalcote** [comment]
Ok, ideally, though, we would use the prior approach of a one-time snapshot of the release notes on trigger of a release.

**Comment by ramrodo** [comment]
> Ok, ideally, though, we would use the prior approach of a one-time snapshot of the release notes on trigger of a release.

I tried to have the previous approach but I couldn't to have it working :(

**Comment by leecalcote** [comment]
@ramrodo the release note PRs are being lost between releases, it seems.

**Comment by ramrodo** [comment]
> @ramrodo the release note PRs are being lost between releases, it seems.

@leecalcote Oh, it seems u.u. I think before creating a new release we should mark this PR as **Ready for review** and merge it. Then, create the new release, in order to not lose the current notes.

**Comment by ramrodo** [comment]
Or maybe, we can manage different branch names based on the release number for allowing different PRs to be opened.

**Comment by leecalcote** [comment]
> > @ramrodo the release note PRs are being lost between releases, it seems.
> 
> @leecalcote Oh, it seems u.u. I think before creating a new release we should mark this PR as **Ready for review** and merge it. Then, create the new release, in order to not lose the current notes.

Makes sense. ✔️ Making a mental note of these manual steps.

This gives us stronger motivation to circle back on figuring out how to reenable the prior flow of capturing the release notes during release time and publishing.

**Comment by leecalcote** [comment]
@ramrodo I made release and immediately went to merge this PR. In that time, though, the workflow had already run to create a new set of docs for the next release v0.5.25.

**Comment by ramrodo** [comment]
> > @ramrodo the release note PRs are being lost between releases, it seems.
> 
> @leecalcote Oh, it seems u.u. I think before creating a new release we should mark this PR as **Ready for review** and merge it. Then, create the new release, in order to not lose the current notes.


@leecalcote Yep. Maybe this comment above was misunderstood: https://github.com/layer5io/meshery/pull/3067#issuecomment-858137432

But first, we need to merge this PR (before creating the release). So, to be clear, the process should be:

0. We want to create a new release
1. We go to the Release notes PR, convert it into a PR (from a draft)
2. Approve it and merge it
3. Then, publish a release

I know that knowing and doing this process correctly is hard and should be automated but I have not been able to do it as it was before :C

**Pull request merged**
