### PR TITLE
Fix server build error coming on boot

### LINKED ISSUE #10255: [Server] Build error with incorrect UUID length 37
### Current Behavior
Building Meshery Server produces this error:

```
ERRO[2024-02-08T15:04:37-06:00] uuid: incorrect UUID length 37 in string "10a03036-53a0-40b3-9f69-6daab852e434 "  app=meshery code=11043 probable-cause="Invalid object format" severity=2 short-description="Unmarshal unknown error: " suggested-remediation="Make sure to input a valid JSON object"
```

### Expected Behavior
The error message is generic, doesn't point to which subsystem had the error, nor does it suggest how this error might be remediated. The error message should include this information.

### Screenshots/Logs
```
cd server; cd cmd; go mod tidy; \
	BUILD="v0.7.17" \
	PROVIDER_BASE_URLS="https://meshery.layer5.io" \
	PORT=9081 \
	DEBUG=true \
	ADAPTER_URLS="localhost:10000 localhost:10001 localhost:10012" \
	APP_PATH="./apps.json" \
	KEYS_PATH="../../permissions/keys.csv" \
	go run main.go error.go;
INFO[2024-02-08T15:04:34-06:00] Local Provider capabilities are: Not Set      app=meshery
INFO[2024-02-08T15:04:34-06:00] Meshery Server release channel is: Not Set    app=meshery
INFO[2024-02-08T15:04:34-06:00] Meshery Database is at: /Users/lee/.meshery/config  app=meshery
INFO[2024-02-08T15:04:34-06:00] Using kubeconfig at: /Users/lee/.kube         app=meshery
INFO[0000] Log level: debug
INFO[2024-02-08T15:04:34-06:00] extracting Patterns from /Users/lee/.meshery/content/patterns  app=meshery
INFO[2024-02-08T15:04:34-06:00] seeding sample Patterns                       app=meshery
DEBU[2024-02-08T15:04:34-06:00] seeding Pattern: IstioFilterPattern.yaml      app=meshery
DEBU[2024-02-08T15:04:34-06:00] seeding Pattern: IstioSPIRE.yaml              app=meshery
DEBU[2024-02-08T15:04:34-06:00] seeding Pattern: bookInfo.yaml                app=meshery
DEBU[2024-02-08T15:04:34-06:00] seeding Pattern: bookInfoPattern.yaml         app=meshery
DEBU[2024-02-08T15:04:34-06:00] seeding Pattern: bookInfoPatternForCatalog.yaml  app=meshery
DEBU[2024-02-08T15:04:34-06:00] seeding Pattern: bookstore.yaml               app=meshery
DEBU[2024-02-08T15:04:34-06:00] seeding Pattern: emojivoto.yaml               app=meshery
DEBU[2024-02-08T15:04:34-06:00] seeding Pattern: installLinkerd.yaml          app=meshery
DEBU[2024-02-08T15:04:34-06:00] seeding Pattern: istioInstallationForCatalog.yaml  app=meshery
DEBU[2024-02-08T15:04:34-06:00] seeding Pattern: istioinstall.yaml            app=meshery
DEBU[2024-02-08T15:04:34-06:00] seeding Pattern: minimalistiobookinfo.yaml    app=meshery
INFO[2024-02-08T15:04:34-06:00] extracting Filters from /Users/lee/.meshery/content/filters/binaries  app=meshery
INFO[2024-02-08T15:04:34-06:00] seeding sample Filters                        app=meshery
DEBU[2024-02-08T15:04:34-06:00] seeding Filter: http_auth_bg.wasm             app=meshery
DEBU[2024-02-08T15:04:34-06:00] seeding Filter: jwt_filter_bg.wasm            app=meshery
DEBU[2024-02-08T15:04:34-06:00] seeding Filter: metrics_collector_bg.wasm     app=meshery
DEBU[2024-02-08T15:04:34-06:00] seeding Filter: singleton_http_call_bg.wasm   app=meshery
DEBU[2024-02-08T15:04:34-06:00] seeding Filter: singleton_queue_bg.wasm       app=meshery
DEBU[2024-02-08T15:04:34-06:00] seeding Filter: tcp_metrics_bg.wasm           app=meshery
DEBU[2024-02-08T15:04:34-06:00] seeding Filter: tcp_packet_parse_bg.wasm      app=meshery
INFO[2024-02-08T15:04:35-06:00] Meshery Server listening on: 9081             app=meshery
ERRO[2024-02-08T15:04:37-06:00] uuid: incorrect UUID length 37 in string "10a03036-53a0-40b3-9f69-6daab852e434 "  app=meshery code=11043 probable-cause="Invalid object format" severity=2 short-description="Unmarshal unknown error: " suggested-remediation="Make sure to input a valid JSON object"
INFO[2024-02-08T15:04:37-06:00] extracting Applications from /Users/lee/.meshery/content/applications  app=meshery
INFO[2024-02-08T15:04:37-06:00] seeding sample Applications                   app=meshery
DEBU[2024-02-08T15:04:37-06:00] seeding Application: bookinfo                 app=meshery
DEBU[2024-02-08T15:04:37-06:00] seeding Application: emojivoto                app=meshery
DEBU[2024-02-08T15:04:37-06:00] seeding Application: httpbin                  app=meshery
DEBU[2024-02-08T15:04:37-06:00] seeding Application: imagehub                 app=meshery
```

### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by Yashsharma1911**
**Notes for Reviewers**

This PR fixes #10255 
Fix server build error coming on boot because of extra space in key id

This error was coming because of having extra space in key id, I updated both spreadsheets to make sure if next time this spreadsheet gets updates because of workflow we don't reproduce the error

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by Yashsharma1911** [comment]
@MUzairS15 I'm thinking of moving this spreadsheet to server directory

**Comment by MUzairS15** [comment]
👍

**Review by MUzairS15 — COMMENTED** [review]
@Yashsharma1911 Was the spreadsheet updated?
Or is this extra space is added while dumping the CSV?

**Review by MUzairS15 — COMMENTED** [review]
Because you are changing the location, you also need to update the
1. Path in the server/the variable that controls it.
2. Workflow that generates keys and dumps the csv.
3. Dockerfile.

**Comment by Yashsharma1911** [comment]
> @Yashsharma1911 Was the spreadsheet updated? Or is this extra space is added while dumping the CSV?

@MUzairS15 This issue comes when we dump spreadsheet, I updated both places when we dump again we will not this error

**Comment by Yashsharma1911** [comment]
> Because you are changing the location, you also need to update the
> 
> 1. Path in the server/the variable that controls it.
> 2. Workflow that generates keys and dumps the csv.
> 3. Dockerfile.

Thankyou for sharing yes I was just updating these

**Review by leecalcote — DISMISSED** [review]

**Comment by Yashsharma1911** [comment]
Docker build failing, I wonder this is not because of this PR changes

**Comment by leecalcote** [comment]
> Docker build failing, I wonder this is not because of this PR changes

@Yashsharma1911 good question. No, it's failing because of:

```
#36 206.5 Module not found: Can't resolve '@xstate/inspect' in '/ui/pages'
```

I think that @aabidsofi19 has fixed this issue. Let's rebase and find out.

**Comment by Yashsharma1911** [comment]
> > Docker build failing, I wonder this is not because of this PR changes
> 
> @Yashsharma1911 good question. No, it's failing because of:
> 
> ```
> #36 206.5 Module not found: Can't resolve '@xstate/inspect' in '/ui/pages'
> ```
> 
> I think that @aabidsofi19 has fixed this issue. Let's rebase and find out.

Thankyou Lee for checking, docker build is successful, I'm moving forward here

**Pull request merged**
