### PR TITLE
Backfill missing release tags

### LINKED ISSUE #1303: [Docs] Backfill all the releases on the releases page
**Current Behavior**

There missing release tags in the https://meshery.layer5.io/docs/project/releases

**Desired Behavior**

Add all the release tags of Meshery till v0.0.1 in the https://meshery.layer5.io/docs/project/releases 

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

### PR DESCRIPTION
**Pull request by PluckyPrecious**
**Description**

This PR fixes #1303 

**Notes for Reviewers**
Added release tags from v0.0.1 - v0.1.6 to the release page

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by PluckyPrecious** [comment]
> Hey @PluckyPrecious , can you please take a moment and sign DCO?

@kushthedude fixed, thanks.

**Comment by PluckyPrecious** [comment]
> Great work @PluckyPrecious 🥳 🥳 !!

Thank you! 🥳

**Comment by leecalcote** [comment]
Yay, @PluckyPrecious! 🎈

**Comment by PluckyPrecious** [comment]
Thanks @leecalcote 😃

**Pull request merged**
