### PR TITLE
[mesheryctl] #1708 `version` command add indicator to user

### LINKED ISSUE #1708: [mesheryctl] `version` command should provide an "operation in-progress" indicator to user
**Current Behavior**
`meshery version` takes some time to execute the check against the GitHub API for the latest release of software. This check can take a few seconds, leaving the user to wonder what is going on.

```
mesheryctl version
Client Version: 0.4.13 	  GitSHA: aa6dbc84ba47d81d087ae7c7f5693a0d8cce9cc2
Server Version: v0.4.13 	  GitSHA: aa6dbc8

v0.4.13 is not the latest Meshery release. Upgrade to v0.4.14. Run `mesheryctl system upgrade`
```

**Desired Behavior**
Users should be shown an indicator that a check is being performed.

**Implementation**
Show user the info message: ```Checking for latest version of Meshery....```

### PR DESCRIPTION
**Pull request by cardinalion**
Signed-off-by: Cardinalion <ywang10@wesleyan.edu>

**Description**

This PR fixes #1708 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — CHANGES_REQUESTED** [review]
Thank you, @cardinalion. The portion of this command that takes a long time is the function just below the comment 
```
// Inform user of the latest release version
```
Could you move this log statement to just before that on ~line 120?

**Comment by cardinalion** [comment]
Aha, I see what you mean

**Review by leecalcote — APPROVED** [review]
Looks good! Thank you, @cardinalion. 💯

**Comment by leecalcote** [comment]
There's more where this came from @cardinalion. 😉 

I encourage you to join the Layer5 community at http://slack.layer5.io. It's warm and welcoming. It would be nice to have you engage in any of the ongoing projects - https://layer5.io/projects.

**Pull request merged**
