### PR TITLE
Add user facing clean APIs for querying capability registry

### PR DESCRIPTION
**Pull request by Revolyssup**
Signed-off-by: Ashish Tiwari <ashishjaitiwari15112000@gmail.com>

**Description**

This PR adds clean APIs for user friendly queries on capability registry.
Just like kubernetes has a hierarchy of GroupVersionKind. Here a Heirarchy of TypeVersionName is used.
The type can be: core,kubernetes, istio,linkerd,etc

`/api/components/types` => Returns types // ["kubernetes",“istio”,”core”,”linkerd”...]
`/api/components/{type}`=> Returns all components for that type
`/api/components/{type}/versions` => Returns array of available versions for that type
`/api/components/{type}/{version}` => Returns all components of given version for that type
`/api/components/{type}/{version}/{componentName}` => Returns all components of given name of given version

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by Revolyssup** [comment]
Some comments and swagger docs to be added here.

**Review by gr455 — DISMISSED** [review]

**Comment by Revolyssup** [comment]
@leecalcote  Updated it with spreadsheet. Good to go from my side.

**Review by sudo-NithishKarthik — APPROVED** [review]
LGTM

**Review by leecalcote — CHANGES_REQUESTED** [review]
API docs not updated.

**Pull request merged**
