### PR TITLE
Translation install index

### PR DESCRIPTION
**Pull request by alonsolopezr**
**Description**

This PR fixes #

**Notes for Reviewers**
@jesuslerma Tagged for reviewing... thanks again

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Aisuko** [comment]
@alonsolopezr Thanks for contributing, please signoff first `https://github.com/layer5io/meshery/pull/1723/checks?check_run_id=1290124550`

**Comment by alonsolopezr** [comment]
@Aisuko I think I signed off correctly this las commit... (I had a diff name between local and my github account). Thanks

**Comment by Aisuko** [comment]
> @Aisuko I think I signed off correctly this las commit... (I had a diff name between local and my github account). Thanks

Happy to the contributing. I saw the DCO checker may did not passed

**Comment by jesuslerma** [comment]
closed by #1724

**Pull request closed without merging**
