### PR TITLE
v0.4.22 release added

### PR DESCRIPTION
**Pull request by ezioishan**
Signed-off-by: Ishan Sourav <ishansourav7@gmail.com>

**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — CHANGES_REQUESTED** [review]
Please include all releases in between v0.4.4 and v0.4.22. This will be about 18 entries.

**Comment by ezioishan** [comment]
So should i take back this pull request and make a request only after committing all 18 entries?

**Comment by leecalcote** [comment]
You can add new commits to this branch and those commits will reflect in this PR.

**Comment by ezioishan** [comment]
I am not able to find any information regarding releases between v0.4.4 and v.4.22. Also my last commit was a mistake as i added v0.4.21 and v0.4.20

**Comment by leecalcote** [comment]
@ezioishan here you are - https://github.com/layer5io/meshery/releases - information about the prior releases.

**Pull request closed without merging**
