### PR TITLE
fixed filter list logging the endpoint

### LINKED ISSUE #11315: [mesheryctl] `filter list` logs endpoint remove it.
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

### Current Behavior

When we run `mesheryctl filter list` a log line stating the endpoint that is hit remove it.
### Screenshots/Logs

``` 
 ./mesheryctl filter list
http://localhost:9081/api/filter?pagesize=25&page=0
```
### Environment

- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- 📺 [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- ⌨️ [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- ⌨️ [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by Aviral0702**
**Notes for Reviewers**

This PR fixes #11315

The logging of endpoint when filter list command is executed has been removed now.

Previous Behavior:
image

Current Behavior:
image

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by Jougan-0 — APPROVED** [review]

**Comment by Jougan-0** [comment]
Test failing

**Comment by Aviral0702** [comment]
> Test failing

Yes ! the test is failing because the actual response doesn't matches to the expected response which is in the testdata file which is list.filter.output.golden. As it is advised not to update those files so I haven't updated them.

**Comment by Ashparshp** [comment]
@Aviral0702 Let's discuss this issue during the Meshery dev meeting call. Please add it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit?usp=drivesdk).

**Comment by Aviral0702** [comment]
> @Aviral0702 Let's discuss this issue during the Meshery dev meeting call. Please add it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit?usp=drivesdk).

Ok @Ashparshp I will add it.

**Review by singh1203 — APPROVED** [review]
LGTM!

**Comment by Jougan-0** [comment]
> > Test failing
> 
> Yes ! the test is failing because the actual response doesn't matches to the expected response which is in the testdata file which is list.filter.output.golden. As it is advised not to update those files so I haven't updated them.

Either replace it or remove it tests shouldn't be failing.

**Comment by Aviral0702** [comment]
> > > Test failing
> > 
> > 
> > Yes ! the test is failing because the actual response doesn't matches to the expected response which is in the testdata file which is list.filter.output.golden. As it is advised not to update those files so I haven't updated them.
> 
> Either replace it or remove it tests shouldn't be failing.

Okay

**Review by leecalcote — APPROVED** [review]

**Review by Yashsharma1911 — APPROVED** [review]

**Review by Jougan-0 — APPROVED** [review]

**Pull request merged**
