### PR TITLE
Header overlay on sidebar fixed #9877

### LINKED ISSUE #9877: [UI]: Prevent overflow of dashboard tables on small screens
### Current Behavior

On playground dashboard in workload and configuration tabs, UI become inconsistent with a sliding bar

### Desired Behavior

It should match with UI of other tabs and not overflow on sliding or should be handled accordingly

### Screenshots/Logs

configuration
workload

### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by Paras-245**
**Notes for Reviewers**

This PR fixes #9877

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ y] Yes, I signed my commits.

### CODE REVIEW

**Comment by sudhanshutech** [comment]
@Paras-245 what screen width you were having this issue, i am not experiencing this

**Comment by Paras-245** [comment]
> @Paras-245 what screen width you were having this issue, i am not experiencing this




@sudhanshutech In workload and configuration tab it was giving horizontal scroll bar only on full screen and after sliding dashboard just fly.

After fix

**Comment by leecalcote** [comment]
@Paras-245 no, the nav sidebar is not supposed to overlap the rest of the page.

**Review by leecalcote — CHANGES_REQUESTED** [review]
@Paras-245 no, the nav sidebar is not supposed to overlap the rest of the page.

**Comment by leecalcote** [comment]
Thanks, but no thanks, @Paras-245

**Pull request closed without merging**
