### PR TITLE
mesheryctl: Fix system start --reset to reset the meshconfig before s…

### LINKED ISSUE #2957: [mesheryctl] `system start --reset` does not reset the meshconfig before starting Meshery
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior

`mesheryctl system start --reset` does not reset the meshconfig file for Kubernetes and resets the meshconfig after starting Meshery in Docker(which will fail if the user had modified the meshconfig).

#### Desired Behavior

`mesheryctl system start --reset` should first reset the meshconfig file and then restart Meshery for both the platforms.

---

#### Contributor Resources

- [mesheryctl Contributing Guide](https://github.com/layer5io/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by amitech**
Signed-off-by: Amit Kumar <amitsharma928@gmail.com>

**Description**

This PR fixes #2957 

Tested for both Kubernetes (minukube) and Docker.

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by hexxdump — APPROVED** [review]
This sounds like a good approach, i.e., reset the config first and then go ahead with the start operation with the modified config values.

**Review by navendu-pottekkat — APPROVED** [review]
LGTM. Thank you @amitech

**Comment by leecalcote** [comment]
yay, @amitech! 🎈

**Comment by amitech** [comment]
Thanks all for reviewing. Happy to see first PR approved. 😇

**Comment by leecalcote** [comment]
Same here. 😄

**Pull request merged**
