### PR TITLE
Updating Meshery Broker and MeshSync [Docs]

### PR DESCRIPTION
**Pull request by pranav767**
Meshery Broker and MeshSync Hyperlink were redirecting to the Spanish version , this was not the intended way .

Signed-off-by: Pranav Patil <itsmepranav888@gmail.com>

**Notes for Reviewers**
This was discussed in one of the website meeting that the Url for Meshsync and Meshery Broker were redirecting to the spanish version which was not the intended way so fixed both of them 

This PR fixes #

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 53c7add88c0f25c13d8e64bf78ef58a2a5a98b9f at: https://63c76a33fd85241215f01f2e--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 4c7ce0ddfda9a5756aaa44c781672b62081b32a5 at: https://63c7eb9218c1fe2441197f70--meshery-docs-preview.netlify.app

**Review by UtkarshMishra12 — APPROVED** [review]
LGTM 🥇 Thanks @sassukeuchiha 🚀

**Comment by sassukeuchiha** [comment]
Thank you for the fast response @UtkarshMishra12 😁

**Pull request merged**
