### PR TITLE
Fix for issue#6357 (Race condition in go routine)

### LINKED ISSUE #6357: [Server] Race condition in K8s component registration
In the following code, the reference to range value `ctx` at line 86 generates a race condition because it is a reference in the body of a gorutine.

https://github.com/meshery/meshery/blob/f2b1ef8c7b987175f6e3af8e1d1cee2d0a9f3163/server/models/k8s_components_registration.go#L50-L96

([here](https://go.dev/play/p/pmmyHsSwkL2) a simplified version of the bug)

Bug found by [revive](https://github.com/mgechev/revive)

### PR DESCRIPTION
**Pull request by PratikforCoding**
Signed-off-by: PratikforCoding <kotalpratik@gmail.com>

**Description**

This PR fixes #6357 

**Notes for Reviewers**
Tried to resolve the race condition in goroutine

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by PratikforCoding** [comment]
@leecalcote can you review this or assign someone please?

**Comment by leecalcote** [comment]
Rename this PR title please

**Comment by PratikforCoding** [comment]
Done that.

**Comment by Chadha93** [comment]
@PratikforCoding Let's discuss this on the Meshery Dev call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#)

**Comment by leecalcote** [comment]
A merge conflict has come up, @PratikforCoding, perhaps, you can resolve, while @gr455 does a review.

**Comment by leecalcote** [comment]
> A merge conflict has come up, @PratikforCoding, perhaps, you can resolve, while @gr455 does a review.

**Comment by leecalcote** [comment]
@paularah, you might like to offer review here.

**Comment by PratikforCoding** [comment]
can someone help with the failed tests? I wanna learn about them.

**Pull request closed without merging**
