### PR TITLE
[Helm] Update MeshSync chart

### PR DESCRIPTION
**Pull request by MUzairS15**
**Notes for Reviewers**

This PR fixes #

The MeshSync controller was failing to publish updates to the MeshryServer because of the invalid MeshSync CR.
With recent enhancements in the MeshSync controller, the resources to watch are tracked inside the CR itself. SInce Meshery Server uses the helm chart to provision Operators/Controllers old/outdated CR was getting deployed failing to receive updates.

This PR updates, `MeshSync CRD, CR and values.yaml`

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by MUzairS15** [comment]
// @leecalcote @KiptoonKipkurui

**Review by leecalcote — APPROVED** [review]
Thank you, @MUzairS15.

@KiptoonKipkurui, here is what I meant when inquiring about updating Meshery to deploy the latest Operator/MeshSync.

**Review by leecalcote — COMMENTED** [review]
@MUzairS15 is this config what is running in Playground now?

**Comment by KiptoonKipkurui** [comment]
my bad, i didnt know this far, but thanks for the pointer, I will explore more

**Comment by MUzairS15** [comment]
> @MUzairS15 is this config what is running in Playground now?

Nope.

**Comment by MUzairS15** [comment]
Hence there was an issue happening as mentioned in the PR description.

**Comment by leecalcote** [comment]
> Hence there was an issue happening as mentioned in the PR description.

@MUzairS15 I'm wondering how the Playground is working, then, without this config.

**Comment by leecalcote** [comment]
> my bad, i didnt know this far, but thanks for the pointer, I will explore more

No sweat. Also: I specifically said `go.mod`, so my suggestion was a bit too pointed.

**Comment by MUzairS15** [comment]
Because we sync the informer store at start, the data received from the store is what only available in the server.
The later updates in the cluster ate blocked.

**Comment by MUzairS15** [comment]
The MeshSync skipped the publishing and  failed forward.

**Comment by MUzairS15** [comment]
Hence we didn’t saw MeshSync failing @leecalcote

**Pull request merged**
