### PR TITLE
Kuma dark mode logo resolve

### LINKED ISSUE #7981: [Docs]Dark mode logo issue for Meshery Adapter of Kuma
#### Current State
logo of Meshery Adapter for Kuma not visiable in dark mode at https://docs.meshery.io/
logo of meshery adapter for kuma not visiable in dark mode at /service-meshes/adapters/kuma/

#### Desired State
logo should be visiable

image
image

image
image

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by lanzkrish**
**Notes for Reviewers**

This PR fixes #7981 

Screenshot 2023-08-19 at 5 37 57 AM
Screenshot 2023-08-19 at 5 37 45 AM

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 1a539be2deab01e018bb09db42ebefa31f7041be at: https://64e008ebb6215b028b6dfbb2--meshery-docs-preview.netlify.app

**Comment by leecalcote** [comment]
Will you offer a reference that shows the same approach has been taken for light/dark mode compatibility elsewhere?

**Comment by lanzkrish** [comment]
> Will you offer a reference that shows the same approach has been taken for light/dark mode compatibility elsewhere?

https://meshery.io/community/

here I have also worked on this previously

**Comment by l5io** [comment]
🚀 Preview for commit 0269a648097e4927439e818af6f0a4459033021f at: https://64e0cc1cc3249756bc2ba9e2--meshery-docs-preview.netlify.app

**Comment by leecalcote** [comment]
I'm asking for another reference within Meshery Docs.

**Comment by lanzkrish** [comment]
> I'm asking for another reference within Meshery Docs.

No there aren't any other situations for light/dark mode compatibility issues except for this Kuma logo

**Comment by l5io** [comment]
🚀 Preview for commit e87122090458ee5c4fe5dda826df2f9e756062a2 at: https://64e160b811201117802797a7--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 7adcb753cd3426abce68052f25a16842f8b88391 at: https://64e1651cb6215b1b896dfb67--meshery-docs-preview.netlify.app

**Comment by vishalvivekm** [comment]
@lanzkrish Let's discuss it on the websites call on Monday. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima).

**Comment by leecalcote** [comment]
@lanzkrish will you be back to fix the DCO issue?

**Comment by lanzkrish** [comment]
Yes yes I'll fix the issue

**Comment by l5io** [comment]
🚀 Preview for commit 6fa3b524e1ac75d4121b0d17aaf7216f935de326 at: https://64e44951db1bf4262b35c518--meshery-docs-preview.netlify.app

**Comment by lanzkrish** [comment]
I have created a new PR #8596  for this issue

**Pull request closed without merging**
