### PR TITLE
[Playground] Fix CORS issue during logout | CU-85zrgczty

### PR DESCRIPTION
**Pull request by theBeginner86**
**Notes for Reviewers**

This PR fixes #

https://user-images.githubusercontent.com/73700530/208216126-6fe3cc3a-30e0-4a28-bbe7-207cc4b68578.mp4

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
Task linked: [CU-85zrgczty [Playground] CORS issue during logout](https://app.clickup.com/t/85zrgczty)

**Comment by theBeginner86** [comment]
> Task linked: [CU-85zrgczty [Playground] CORS issue during logout](https://app.clickup.com/t/85zrgczty)

Added explanation here ^^

**Comment by leecalcote** [comment]
@MUzairS15 an item for your eyes...

**Review by MUzairS15 — APPROVED** [review]
LGTM

**Pull request merged**
