### PR TITLE
fix: go sum conflicts due to dependabot

### PR DESCRIPTION
**Pull request by kushthedude**
Signed-off-by: Kush Trivedi <kushthedude@gmail.com>

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Is this needed? I’m confused as to why this needs fixed all the time. Should this just wait until the next feature/bugfix PR?

**Comment by kushthedude** [comment]
> Is this needed? I’m confused as to why this needs fixed all the time. Should this just wait until the next feature/bugfix PR?

Dependabot PR already has an issue opened for this, and this is why I made the frequency of updates from one week to one month so that we can merge all PRs and then make a successive PR to fix all conflicts.

**Comment by kushthedude** [comment]
> Is this needed? I’m confused as to why this needs to be fixed all the time. Should this just wait until the next feature/bugfix PR?

Got it let's handle this in another bugfix PR!

**Pull request closed without merging**
