### PR TITLE
lastest enhance after meshkit release

### PR DESCRIPTION
**Pull request by Freedisch**
**Notes for Reviewers**

This PR fixes Meskit was released, I updated the latest changes to the endpoints enhancement
this is a continuation of #8257 #8224

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Freedisch** [comment]
@MUzairS15, the new Meshkit release didn't include the func for Pascal cases, so I still kept that func here

**Comment by leecalcote** [comment]
@Freedisch be more specific about which MeshKit version you're relying on, if you would. 

If you’re relying on v0.6.52, which is what is in this PR, then these errors are produced when Meshery is built:
```
# github.com/layer5io/meshery/server/handlers
../handlers/component_handler.go:219:7: mod.HostID undefined (type "github.com/layer5io/meshkit/models/meshmodel/core/v        github.com/docker/libcompose => github.com/docker/libcompose v0.4.1-0.20190808084053-143e0f3f1ab9
1alpha1".Model has no field or method HostID)
../handlers/component_handler.go:220:7: mod.HostName undefined (type "github.com/layer5io/meshkit/models/meshmodel/core/v1alpha1".Model has no field or method HostName)
../handlers/component_handler.go:221:7: mod.DisplayHostName undefined (type "github.com/layer5io/meshkit/models/meshmodel/core/v1alpha1".Model has no field or method DisplayHostName)
../handlers/component_handler.go:1156:9: comp.HostID undefined (type "github.com/layer5io/meshkit/models/meshmodel/core/v1alpha1".ComponentDefinition has no field or method HostID)
../handlers/component_handler.go:1157:9: comp.HostName undefined (type "github.com/layer5io/meshkit/models/meshmodel/core/v1alpha1".ComponentDefinition has no field or method HostName)
../handlers/component_handler.go:1158:9: comp.DisplayHostName undefined (type "github.com/layer5io/meshkit/models/meshmodel/core/v1alpha1".ComponentDefinition has no field or method DisplayHostName)
../handlers/relationship_handlers.go:165:8: rel.HostID undefined (type "github.com/layer5io/meshkit/models/meshmodel/core/v1alpha1".RelationshipDefinition has no field or method HostID)
../handlers/relationship_handlers.go:166:8: rel.HostName undefined (type "github.com/layer5io/meshkit/models/meshmodel/core/v1alpha1".RelationshipDefinition has no field or method HostName)
../handlers/relationship_handlers.go:167:8: rel.DisplayHostName undefined (type "github.com/layer5io/meshkit/models/meshmodel/core/v1alpha1".RelationshipDefinition has no field or method DisplayHostName)
make: *** [server] Error 1
```

**Comment by Freedisch** [comment]
> @Freedisch be more specific about which MeshKit version you're relying on, if you would.
> 
> If you’re relying on v0.6.52, which is what is in this PR, then these errors are produced when Meshery is built:
> 
> ```
> # github.com/layer5io/meshery/server/handlers
> ../handlers/component_handler.go:219:7: mod.HostID undefined (type "github.com/layer5io/meshkit/models/meshmodel/core/v        github.com/docker/libcompose => github.com/docker/libcompose v0.4.1-0.20190808084053-143e0f3f1ab9
> 1alpha1".Model has no field or method HostID)
> ../handlers/component_handler.go:220:7: mod.HostName undefined (type "github.com/layer5io/meshkit/models/meshmodel/core/v1alpha1".Model has no field or method HostName)
> ../handlers/component_handler.go:221:7: mod.DisplayHostName undefined (type "github.com/layer5io/meshkit/models/meshmodel/core/v1alpha1".Model has no field or method DisplayHostName)
> ../handlers/component_handler.go:1156:9: comp.HostID undefined (type "github.com/layer5io/meshkit/models/meshmodel/core/v1alpha1".ComponentDefinition has no field or method HostID)
> ../handlers/component_handler.go:1157:9: comp.HostName undefined (type "github.com/layer5io/meshkit/models/meshmodel/core/v1alpha1".ComponentDefinition has no field or method HostName)
> ../handlers/component_handler.go:1158:9: comp.DisplayHostName undefined (type "github.com/layer5io/meshkit/models/meshmodel/core/v1alpha1".ComponentDefinition has no field or method DisplayHostName)
> ../handlers/relationship_handlers.go:165:8: rel.HostID undefined (type "github.com/layer5io/meshkit/models/meshmodel/core/v1alpha1".RelationshipDefinition has no field or method HostID)
> ../handlers/relationship_handlers.go:166:8: rel.HostName undefined (type "github.com/layer5io/meshkit/models/meshmodel/core/v1alpha1".RelationshipDefinition has no field or method HostName)
> ../handlers/relationship_handlers.go:167:8: rel.DisplayHostName undefined (type "github.com/layer5io/meshkit/models/meshmodel/core/v1alpha1".RelationshipDefinition has no field or method DisplayHostName)
> make: *** [server] Error 1
> ```

No, I'm relying on the 0.6.54

**Comment by leecalcote** [comment]
@abdullah1308 will you put your 👀s on this?

**Review by leecalcote — APPROVED** [review]
@theBeginner86 fyi, regarding k8s connection table merge.

**Pull request merged**
