### PR TITLE
Add support for importing helm chart via URL on application page

### PR DESCRIPTION
**Pull request by Revolyssup**
Signed-off-by: Ashish Tiwari <ashishjaitiwari15112000@gmail.com>

**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Abhishek-kumar09** [comment]
@Revolyssup Should it be a file picker?? Or directory Pricker?? Or just path to location as text

**Comment by Revolyssup** [comment]
> @Revolyssup Should it be a file picker?? Or directory Pricker?? Or just path to location as text

Let the user browse and chose a directory. Take that directory path and put it in a string. Send that string in `path`

**Comment by leecalcote** [comment]
The UX should be the same as any other type of App import.

**Comment by leecalcote** [comment]
There should be a new column in the Application table used to indicate source application type (e.g. helm, compose, ...)

**Comment by leecalcote** [comment]
@Revolyssup please mention the issue that this is being created for (the one with @mchurichi on copy).

**Comment by leecalcote** [comment]
Failing tests..

**Comment by leecalcote** [comment]
The biggest issue with supporting filepaths-based imports is that in nearly all cases a user's deployment of Meshery will be in a containerized deployment. Containerized Meshery Server will nearly always not have access to the same filesystem or that portion of the filesystem.

UI should disallow any URI ending in anything but `.tgz` or `.yaml` or `.yml`.

**Comment by Revolyssup** [comment]
@leecalcote  Should we move forward with it so that latest Application `source-content` PR can work on top of it?

**Comment by leecalcote** [comment]
@Revolyssup Does the UI disallow any URI ending in anything but .tgz or .yaml or .yml?

Does support for local file imports only support a single file (ideally), and not attempt a directory import?

**Comment by Revolyssup** [comment]
> @Revolyssup Does the UI disallow any URI ending in anything but .tgz or .yaml or .yml?
> 
> Does support for local file imports only support a single file (ideally), and not attempt a directory import?

No su

> @Revolyssup Does the UI disallow any URI ending in anything but .tgz or .yaml or .yml?
> 
> Does support for local file imports only support a single file (ideally), and not attempt a directory import?

Question 1- No it won't disallow from backend side.
Question 2- We decided on not to support local helm chart imports due to possible issues in container so I will remove that small logic and then we can merge.

**Review by leecalcote — APPROVED** [review]

**Pull request merged**
