### PR TITLE
fixed the dropdown icon bug across modals

### PR DESCRIPTION
**Pull request by captain-Akshay**
**Notes for Reviewers**

This PR fixes #

 This fixes all the drop down menu in all the modal we have in meshery & meshmap. It is responisve and fix the drop down icon which was not clickable.

https://github.com/meshery/meshery/assets/59491379/05b5583a-8969-4bda-99a0-54805540b05a

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by Yashsharma1911 — APPROVED** [review]
Thankyou LGTM

**Comment by Yashsharma1911** [comment]
Just to confirm, we don't open dropdown on clicking "?" right?

**Comment by ritiksaxena124** [comment]
> Just to confirm, we don't open dropdown on clicking "?" right?

Right @Yashsharma1911

**Review by ritiksaxena124 — APPROVED** [review]
Looks good to me 🚀

**Pull request merged**
