### PR TITLE
[UI] "Undeploy" checkmark color has changed

### LINKED ISSUE #5783: [UI] Different color for the "undeploy" checkmarks on the Applications page
#### Current Behavior

Currently, it has the same blue/green color as other elements in the UI.
#### Desired Behavior

 Since it is a delete action, it would be good if this was using the same red color as used by the undeploy button is using in the grid-based view on the applications page.
#### Mockups

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by subhradwip01**
Signed-off-by: subhradwip01 <subhradwip01@gmail.com>

**Description**
Color of the "undeploy" checkmarks on the Applications page has chnaged
This PR fixes #5783

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by Chadha93 — CHANGES_REQUESTED** [review]
@subhradwip01 Would you also add this color update to other configurations(Filters/Designs)?

**Comment by Chadha93** [comment]
@Abhishek-kumar09 The UI cypress tests are failing again.

**Comment by Abhishek-kumar09** [comment]
The fails are introduced here: https://github.com/meshery/meshery/pull/5761 and https://github.com/meshery/meshery/pull/5716. Reminds us why we e2e tests are important to pass before merging.

**Comment by Abhishek-kumar09** [comment]
https://github.com/meshery/meshery/pull/5794

**Comment by subhradwip01** [comment]
> @subhradwip01 Would you mind sharing a screenshot?
Ya sure

**Comment by subhradwip01** [comment]
Output
https://user-images.githubusercontent.com/88609894/178657860-4b61bb79-5da2-4c4f-a9b9-e22b8c59664e.mp4

**Review by Chadha93 — APPROVED** [review]
LGTM, all E2E checks passed.

**Pull request merged**
