### PR TITLE
[WIP] Add documentation for `system check`

### LINKED ISSUE #4197: [Docs] Add docs for `mesheryctl system check` command
#### Current State
`mesheryctl system check` is a command use to run system health checks for both pre and post deployment scenarios.

#### Desired State
1. Add documentation for this command in the [Command Reference](https://docs.meshery.io/reference/mesheryctl) page and add individual page for this command.
2. Create a [guide](https://docs.meshery.io/guides) which walks through how a user can verify their environment readiness covering most common use-cases.
---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by alphaX86**
Signed-off-by: Aadhitya A <aadhitya864@gmail.com>

**Description**

This PR fixes #4197 

**Notes for Reviewers**
Guide is WIP

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit c4f7ea1f875ee5a989f4ecac2eaa31e82715965b at: https://616bce3a7f9d4f9fb0def4a8--meshery-docs-preview.netlify.app

**Comment by piyushsingariya** [comment]
@alphaX86 We also need to add a lists of reasons/solutions of failure of each and every check.
e.g.
- Adapter check failed
  - Adapter not deployed
  - Meshery can't reach kubernetes(Solution: Upload kubeconfig from Meshery UI)

Just an example but with better formatting and grammar. 🤓

**Comment by alphaX86** [comment]
I'm familiar with preflight that's why I entered some Q. Alrighty I'll add them 🤓👍

**Comment by navendu-pottekkat** [comment]
Really great work @alphaX86 . FAQ is quite good. We might need to iterate over this once more. 

Is this still a WIP? I don't think you are missing anything other than us looking over it again and refining this.

**Comment by alphaX86** [comment]
> Hi @alphaX86 , great work!. Gave some minor suggestions that you may look into when you find time.

Thanks @Mr-DG-Wick :) I'll add them when I'm free

**Comment by alphaX86** [comment]
That rebase I thought this will resolve DCO check...... 👎 I'll open up a new PR with changes needed. Closing this PR

**Comment by alphaX86** [comment]
@piyushsingariya @leecalcote and others, a new PR is made. Refer #4462

**Pull request closed without merging**
