### PR TITLE
Table display issue resolved

### LINKED ISSUE #7141: [UI] The table in docs is not displayed correctly
#### Current Behavior
The table for "Meshery Adapter For Cilium" is not displayed correctly. You can see it in the docs [here](https://docs.meshery.io/reference/error-codes#meshery-adapter-for-cilium).
 

#### Desired Behavior
Either the table should be displayed or the HTML tags could be removed
#### Screenshots/Logs
image

image

#### Environment

- Browser: Chrome Brave Firefox
- Host OS: Windows 11
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by jayeshuk**
Worked on the Issue #7141 so that the table displays in the right format.

**Notes for Reviewers**

This PR fixes #7141 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 26f3caa02bdb6dd2401eaaefed551b393f9a4742 at: https://64a5a5554c54e509f4cdb7f3--meshery-docs-preview.netlify.app

**Review by hirentimbadiya — COMMENTED** [review]
@jayeshuk , Please refrain from creating a pull request until the issue has been assigned to you.

**Comment by jayeshuk** [comment]
@hirentimbadiya Sure. Is this been worked on already ?

**Comment by vaibhav135** [comment]
@jayeshuk I still can't see the table in the preview?

image

**Comment by Chadha93** [comment]
@jayeshuk  Let's discuss this on the Meshery Dev call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#) if you would. :)

**Review by leecalcote — APPROVED** [review]
Thanks!

**Pull request merged**
