### PR TITLE
add light mode support for summary view

### PR DESCRIPTION
**Pull request by vishalvivekm**
**Notes for Reviewers**

https://github.com/meshery/meshery/pull/7374#pullrequestreview-1358272421  // @leecalcote 

- makes details/summary visible in light mode 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Thanks, @vishalvivekm. I'm hopeful that instead of one style, we can incorporate two different font colors: one for light mode and one for dark mode.

**Comment by l5io** [comment]
🚀 Preview for commit 35f2592354140ed22d916ce71852b1e689710979 at: https://64216688adf9c108e76d43ac--meshery-docs-preview.netlify.app

**Comment by vishalvivekm** [comment]
> Thanks, @vishalvivekm. I'm hopeful that instead of one style, we can incorporate two different font colors: one for light mode and one for dark mode.

Yep, done. // @leecalcote 

Light mode:
Screenshot 2023-03-27 145317
and
Screenshot 2023-03-27 145348

Dark Mode:
Screenshot 2023-03-27 145329

Screenshot 2023-03-27 145418

**Comment by goldfishdolphin** [comment]
I think it may look better without number .

**Comment by goldfishdolphin** [comment]
If numbers are required, they may look better outside the summary tag .

**Comment by vishalvivekm** [comment]
Screenshot 2023-03-28 093647
@goldfishdolphin good to go?

**Review by goldfishdolphin — APPROVED** [review]
Looking good 👍

**Comment by l5io** [comment]
🚀 Preview for commit 6dbc31175565cec7fe5b02f93bf81c0cb249c9e9 at: https://64229203b2c76f21b58a27ba--meshery-docs-preview.netlify.app

**Review by goldfishdolphin — APPROVED** [review]
Amazing work @vishalvivekm 👍🏽

**Review by goldfishdolphin — APPROVED** [review]
@vishalvivekm, @leecalcote 
🌟🚀

**Review by asubedy — CHANGES_REQUESTED** [review]
I guess information has been jumbled up, 
image
1. Two times mention of Meshery CLI command
2. picture in wrong place accordion


Other few changes required.
image

1. Start the bullet points from next line
2.  The font color inside the Codeblock displaying `http:\\{meshery-server}:9081/provider` is very light
3.  And it will be better to show the link in this manner `http....` rather than giving it a full codeblock


Please fix these changes.

**Comment by vishalvivekm** [comment]
https://user-images.githubusercontent.com/110674407/228785209-49fce83d-eb8d-47eb-a00a-5920bffc9bf8.mp4

<br/>
@asubedy looks good?

**Review by leecalcote — APPROVED** [review]
Good use of vars. 👍

**Comment by vishalvivekm** [comment]
> @vishalvivekm let's open new PR to address the issue I mentioned. The video you shared looks good.

Got it @asubedy . 
Now that this PR is merged, if i may ask, how the font -color and codeblock in the docs page now is different than the commit preview? see the difference below:

The  final commit preview:
Screenshot from 2023-03-31 14-54-31

The docs page now:
Screenshot from 2023-03-31 14-53-55

**Comment by asubedy** [comment]
@vishalvivekm wow I actually don't have an answer for this 🤔. Needs more investigating

**Comment by vishalvivekm** [comment]
> @vishalvivekm wow I actually don't have an answer for this 🤔. Needs more investigating

Thank you @asubedy. would it still be a good idea to come up with a new PR addressing the issues that you mentioned, and that would make the details/summary look just like the video above?

**Comment by asubedy** [comment]
Yes yes, A PR is required because the content now is all jumbled we need to fix that.

**Comment by vishalvivekm** [comment]
> Yes yes, A PR is required because the content now is all jumbled we need to fix that.

Roger!

**Pull request merged**
