### PR TITLE
[chore] Fix MeshModel models reterival

### LINKED ISSUE #8929: Refactor Models Retrieval Handling to Reduce Latency and Improve Code Organization
### Current Behavior
At present, within our codebase, we are managing the acquisition of models through a single central handler defined in [component_handler.go](https://github.com/meshery/meshery/blob/master/server/handlers/component_handler.go#L38). Specifically, this handler encompasses the retrieval of mesh models and necessitates a loop through all components in order to obtain the identity model names. Regrettably, this approach has led to excessive utilization of the component handler across various use cases, which, in turn, has given rise to latency-related issues.

### Desired Behavior
Each meshmodel database table should have its dedicated handler, residing in a separate file. This segregation will not only improve code organization but also help mitigate latency problems

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by theBeginner86**
**Notes for Reviewers**

This PR removes the unwanted loop to find the host metadata for given meshmodel.
This work is pushed to SQL handler in MeshKit. 
Related: https://github.com/meshery/meshkit/pull/375

Performance Improvements:

Before (**20sec** to fetch **298** models):
Screenshot 2023-09-28 at 11 22 43 AM

After (**70ms** to fetch **298** models):
Screenshot 2023-09-28 at 12 18 58 PM

This PR fixes #8929

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Review by Yashsharma1911 — APPROVED** [review]
It will require meshkit release?

**Comment by theBeginner86** [comment]
> It will require meshkit release?

yes

**Comment by leecalcote** [comment]
For a moment, I got my seconds and milliseconds mixed up

**Review by leecalcote — DISMISSED** [review]
Lgtm.

 Pending MeshKit merge.

**Review by leecalcote — APPROVED** [review]

**Comment by leecalcote** [comment]
@Jougan-0 heads-up. The update here should eliminate much redundancy and significantly speed up the API as it pertains to https://github.com/meshery/meshery/pull/8949

**Comment by Jougan-0** [comment]
@leecalcote okay sir got it

**Comment by Jougan-0** [comment]
@leecalcote i am using the old code for meshmodel and other getting the summary just storing the values in maps for me it shows 
image

**Pull request merged**
