### PR TITLE
update to pkg/browser to open URLs

### LINKED ISSUE #3664: [mesheryctl] Opening URL on browser throws an error if xdg-open is not present on Linux platform
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior

mesheryctl throws an error when and shows that unable to start when `xdg-open` is not available.

```
Opening Meshery in your browser. If Meshery does not open, please point your browser to http://localhost:31409 to access Meshery.

Error: failed to start Meshery 

See https://docs.meshery.io/reference/mesheryctl/system for usage details

: failed to exec command

See https://docs.meshery.io/reference/mesheryctl/system for usage details

: exec: "xdg-open": executable file not found in $PATH

Usage:

  mesheryctl system start [flags]

 Flags: [...]
```

#### Desired Behavior

1. This should not be shown as an error and in the absence of xdg-open, mesheryctl should show a warning.
2. Move to https://github.com/pkg/browser for opening URL on browser.

---

#### Contributor Resources

- [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by pottekkat**
Signed-off-by: Navendu Pottekkat <navendupottekkat@gmail.com>

**Description**

This PR fixes #3664 

Updated to [pkg/browser](https://github.com/pkg/browser) to open URLs in mesheryctl.

**Notes for Reviewers**

Please test out this PR on multiple OSes by running `mesheryctl system start` and checking if Meshery is being opened in the browser.

- [x] MacOS/M1
- [x] MacOS/Intel
- [x] Linux
- [ ] Windows

- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by hexxdump — APPROVED** [review]
Looks good!

**Review by piyushsingariya — APPROVED** [review]
Linux works! to be specific manjaro Arch linux.

**Comment by navendu-pottekkat** [comment]
@piyushsingariya any idea why the test fails?

**Comment by leecalcote** [comment]
LGTM. My test on MacOS/Intel was successful.

**Review by leecalcote — APPROVED** [review]

**Comment by navendu-pottekkat** [comment]
@leecalcote The workflow should not have failed, I am checking to see if we can fix it. It says it is because of the missing `xdg-open`.

@piyushsingariya were you able to draw any better insight?

**Review by piyushsingariya — DISMISSED** [review]

**Review by piyushsingariya — APPROVED** [review]

**Pull request merged**
