### PR TITLE
[Docs] Integrationn Test Results: visual enhancement

### PR DESCRIPTION
**Pull request by leecalcote**
Signed-off-by: leecalcote <leecalcote@gmail.com>

**Notes for Reviewers**

@asubedy, there is much unnecessary redundancy in the way the integration tests results are organized into three groups in the main page (this can be consolidted from three repetitive groups of logic into one) and into individual component pages (these can be consolidated into a single page).

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 4f6d30bbf7aa49426f43503bc7c15a3f14d4ffc4 at: https://621c173398b212c23b2bf6d3--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 75c126baf24876280abc713750d77bbf6b86cdaa at: https://621c1ab22c2abf906dbd3163--meshery-docs-preview.netlify.app

**Comment by asubedy** [comment]
Since the test results are not clickable I don't think we should use hover effect on them.

**Review by alphaX86 — APPROVED** [review]
Looks appealing 😍 

+1 to @asubedy's comment, the list hover effect on test results can be removed. Other than that, LGTM on my side :)

**Comment by leecalcote** [comment]
Good call. Part of the issue here is that the page has styling defined for `tr` hover state that is not using Bootstrap's classes. If we can extend or argument those styles this might be more manageable - https://getbootstrap.com/docs/5.1/content/tables/. Is this something that either @alphaX86 or @asubedy can look into in another PR?

**Comment by leecalcote** [comment]
Adding a new style like:

```css
  td.no-hover:hover, tr.no-hover:hover {
    background-color: none !important;
    cursor:default !important;
  }
```

and this class to each of the trs and tds doesn't have the desired affect.

**Comment by leecalcote** [comment]
@alphaX86 is this something that you can tie-off?

**Comment by alphaX86** [comment]
I'll give a look on it @leecalcote 👍

**Comment by leecalcote** [comment]
Thank you, sir.

**Pull request merged**
