### PR TITLE
[content] Migrate Apps -> Designs

### PR DESCRIPTION
**Pull request by theBeginner86**
**Notes for Reviewers**

Depends on https://github.com/meshery/meshkit/pull/402

I have not removed any backend code as mesheryctl still refers the applications APIs.

This PR fixes #

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 050b5f0a5a906e8f16b67a4ecbbdca78e96f8516 at: https://653e308b7cf24059ead62039--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 4fb78969a5e1d1ab88167f516f4d6a46c5cb3bbf at: https://653f4e17bf18b3220fe62b7b--meshery-docs-preview.netlify.app

**Comment by aabidsofi19** [comment]
@theBeginner86  can i work of  this pr , should i expect any major  changes ?

**Comment by l5io** [comment]
🚀 Preview for commit 4db07c4ad26082ab731e55950ba160f4082f7e2a at: https://653f726c2f372444fc657d05--meshery-docs-preview.netlify.app

**Comment by theBeginner86** [comment]
> @theBeginner86 can i work of this pr , should i expect any major changes ?

Yes, feel free to use. This PR is ready from my end. 

There are several changes. You need to built the corresponding Remote Provider and MeshKit PRs. (I have linked each of them).

**Comment by l5io** [comment]
🚀 Preview for commit 2a7f0839219a84655cae69a50368afb100ae15d3 at: https://65413cb817152340f4d9bae8--meshery-docs-preview.netlify.app

**Review by aabidsofi19 — DISMISSED** [review]
Awesome :heart:

**Comment by l5io** [comment]
🚀 Preview for commit bd3add56118e077bed7ef2e88c4aca1da41480e2 at: https://6541660ad8571202edc04517--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit f7419987b82668701b8b97b5f0a01b0e30ae073c at: https://65416c4f387de50731a9d042--meshery-docs-preview.netlify.app

**Pull request merged**
