### PR TITLE
fix: Improve the error message in server-version

### LINKED ISSUE #1206: [mesheryctl] Improve `version` error message when server is unreachable
**Description**
When the Meshery server API is unreachable, the following error is shown to the user when executing `meshery version`:

```
➜  ~ mesheryctl version
Client Version: 0.3.18 	  GitSHA: 26173973db79fe92523754d8301d1421186b9cc3
Server Version: Unavailable 	  GitSHA: Unavailable

Could not communicate with Meshery at http://localhost:9081/api
Ensure that Meshery is available. See (https://docs.meshery.io)
```

**Expected Behavior**
A couple minor wording updates will improve this error message:

- [ ] Provide actual /api/server/version endpoint in message.
- [ ] Change from "Ensure that Meshery is available." to
     ```  
     Ensure that Meshery is available. 
     See Meshery Documentation (https://docs.meshery.io) for help.
     ```

### PR DESCRIPTION
**Pull request by rshivam08**
Signed-off-by: Shivam Rathore <shivamrathore307@gmail.com>

**Description**
This PR will improve the version error message which is shown to the user when executing meshery version.

**Notes to reviewers**

#### Checklist

- [] [Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin).
- [] PR title includes `[<name of area>]:<description>`

### CODE REVIEW

**Comment by Aisuko** [comment]
@rshivam08 Thanks

**Comment by Aisuko** [comment]
@leecalcote  The dependency error not reference to this PR 

```
go: github.com/aspenmesh/istio-client-go@v0.0.0-20191010215625-4de6e89009c4 requires
5
	istio.io/api@v0.0.0-20190820204432-483f2547d882 requires
6
	istio.io/gogo-genproto@v0.0.0-20190731221249-06e20ada0df2: unrecognized import path "istio.io/gogo-genproto": https fetch: Get "https://istio.io/gogo-genproto?go-get=1": unexpected EOF
7
##[error]Process completed with exit code 1.
```

**Comment by leecalcote** [comment]
> @leecalcote The dependency error not reference to this PR
> 
> https://github.com/layer5io/meshery/pull/1234/checks?check_run_id=842913743
> 
> ```
> go: github.com/aspenmesh/istio-client-go@v0.0.0-20191010215625-4de6e89009c4 requires
> 5
> 	istio.io/api@v0.0.0-20190820204432-483f2547d882 requires
> 6
> 	istio.io/gogo-genproto@v0.0.0-20190731221249-06e20ada0df2: unrecognized import path "istio.io/gogo-genproto": https fetch: Get "https://istio.io/gogo-genproto?go-get=1": unexpected EOF
> 7
> ##[error]Process completed with exit code 1.
> ```

@nveenjain could you have a look at this?

**Comment by rshivam08** [comment]
> Hey @rshivam08 , great work here! Just a quick note, please give a more descriptive PR name next time

@kushthedude Thanks a lot! I will surely take it into consideration.

**Pull request merged**
