### PR TITLE
#304 - Collapsible Side Navigation

### PR DESCRIPTION
**Pull request by mcastre**
- Add new collapse menu icon (ui/static/img/sidebar-collapse-toggle-icon.svg)
- Use React's setState to set `isDrawerCollapsed` (boolean) to trigger certain CSS classes to style the collapsed and expanded sidebar nav.
- Hide collapse button for mobile screens only (No need to collapse the sidebar on mobile screens since its already hidden away using a hamburger icon)

### CODE REVIEW

**Comment by mcastre** [comment]
Not sure why the docker build is failing. Re-running checks

**Comment by girishranganathan** [comment]
Hey @mcastre, thx for the PR.
The docker builds are failing bcoz a dependent GitHub Action repo (docker) seems to have been deleted.

**Comment by mcastre** [comment]
Is that based on my code?

**Comment by girishranganathan** [comment]
> Is that based on my code?

No, it is not. The issue is elsewhere.

**Comment by girishranganathan** [comment]
@mcastre can you please sync your branch with master? This will get the build fixed.

**Comment by leecalcote** [comment]
@mcastre thanks for this PR! Here are short instructions on how to sync your branch with master - https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#keep-local-branch-up-to-head-on-master

**Comment by mcastre** [comment]
@girishranganathan PR is now passing checks

**Comment by leecalcote** [comment]
Excited about this, @mcastre. I'd love to have you demo this in our community call on Friday. - https://layer5.io/meshery/#community

**Comment by leecalcote** [comment]
Looking good, @mcastre! Have a quick look in [this recording](https://youtu.be/0f6Qe2aS5F0). Are you able to hide the horizontal scrollbar to remove it as an artifact during transition?

**Comment by mcastre** [comment]
@leecalcote Yea, let me take a look at that. It might be because the width change is happening a tad faster than the transition. Hopefully a simple CSS fix will do the trick.

Im open to demo on Friday! Are you guys using Hangouts Meet for video conferencing as well, or just phone conference?

**Comment by leecalcote** [comment]
@mcastre yes, Hangouts. Details here - https://layer5.io/meshery/#community

**Pull request merged**
