### PR TITLE
“move codecov from root to .github”

### LINKED ISSUE #3337: [CI] Move codecov.yml into .github directory
**Description**
As a project, we are in need of minimizing the number of files in the root directory of Meshery.

The [codecov.yml](https://github.com/meshery/meshery/blob/master/codecov.yml) file is in need of being relocated.

---

According to this:
https://docs.codecov.com/docs/codecov-yaml#can-i-name-the-file-codecovyml

> Can I name the file .codecov.yml?
> Yes. However, the file must still be located in the root, dev/, or .github/ directories

So, it is possible to move it into `.github/` directory.

_Originally posted by @ramrodo in https://github.com/meshery/meshery/discussions/3210#discussioncomment-874626_

### PR DESCRIPTION
**Pull request by suhaniii**
Signed-off-by: Suhani Agarwal <suhaniagarwal@Suhanis-MacBook-Air.local>

**Description**

This PR fixes #3337 

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by adithyaakrishna — DISMISSED** [review]
LGTM 🎉 
It has been moved correctly 💯

**Comment by adithyaakrishna** [comment]
Also @suhaniii If you don't mind, please do update your signoff parameters. The email has a error I guess.

- git config --global user.email "<yourmailid@mailprovider.com>"

**Comment by alphaX86** [comment]
> * git config --global user.email "[yourmailid@mailprovider.com](mailto:yourmailid@mailprovider.com)"
Seems she masked her email with Mac's address... @suhaniii better make your email public as the DCO needs a valid email, else it won't pass that check during work flow run

**Comment by adithyaakrishna** [comment]
I don't think it would stop the DCO from passing, as the DCO considers whatever you put inside " " during config as a string 👀

**Comment by alphaX86** [comment]
Hmm well you may be right... Let's see when it runs 👍

**Comment by suhaniii** [comment]
> > * git config --global user.email "[yourmailid@mailprovider.com](mailto:yourmailid@mailprovider.com)"
> 
> Seems she masked her email with Mac's address... @suhaniii better make your email public as the DCO needs a valid email, else it won't pass that check during work flow run

Updated config for next one

**Comment by leecalcote** [comment]
Thanks, @suhaniii! 

@ramrodo, do you know if any configuration will need updated in CodeCov?

**Comment by suhaniii** [comment]
> Thanks, @suhaniii!
> 
> @ramrodo, do you know if any configuration will need updated in CodeCov?

@ramrodo  Are we good to go ?

**Comment by ramrodo** [comment]
> @ramrodo, do you know if any configuration will need updated in CodeCov?

I don't think so. That should be enough.

**Comment by l5io** [comment]
🚀 Preview for commit 856d78b79dbe93a5fbd33db111563cb865a29bb1 at: https://60e327622ad04e7679e5e8ba--meshery-docs-preview.netlify.app

**Comment by ramrodo** [comment]
> @ramrodo Are we good to go ?

If all the tests are green, we are ok to go.

I want to let you all know some **best practices** at creating PRs: the title/purpose of this PR was moving the `codecov.yml` file to `.github` folder but there were modified other 16 lines. This is hard to review or even if we want to revert one single change, we would revert everything, not only the single file we wanted.
Please, next time try to submit PR separately and touch only the files needed.

**Comment by leecalcote** [comment]
> > @ramrodo Are we good to go ?
> 
> If all the tests are green, we are ok to go.
> 
> I want to let you all know some **best practices** at creating PRs: the title/purpose of this PR was moving the `codecov.yml` file to `.github` folder but there were modified other 16 lines. This is hard to review or even if we want to revert one single change, we would revert everything, not only the single file we wanted.
> Please, next time try to submit PR separately and touch only the files needed.

@suhaniii this PR accidentally includes other commits not directly related to this PR. To avoid this, you'll want to ensure that your fork and local clone of the `meshery` repo is synced with the upstream master.

**Pull request merged**
