### PR TITLE
[Docs] Initialize Extension's user facing documentation | CU-85zrzt5fg

### PR DESCRIPTION
**Pull request by Chadha93**
**Notes for Reviewers**
Initialize Extension's user facing documentation for Extensions and Extensions Snapshot.

This PR fixes #CU-85zrzt5fg

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 1fa231ccff03647d93a191a803ffc19023379880 at: https://64808554d340e115e9bde73a--meshery-docs-preview.netlify.app

**Comment by Chadha93** [comment]
How to use MeshMap and different features specific documentation and video recording will be added. Such as How to import, publish, deploy, undeploy, use ctx menu, configure via RJSF, use the terminal, log streaming, and many more...

**Review by leecalcote — CHANGES_REQUESTED** [review]
This is an extension. Publish under extensions.

**Comment by l5io** [comment]
🚀 Preview for commit 2ce934936853109330f08d61ae5d64dfd3c1917b at: https://6489c3730d4c4b297d6ec64d--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 4c1b2261996f9c98c1643f514aa274b916bde103 at: https://648c35842d51ee00c159589a--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 2e5f16916214f35c4c3507e574534b2009a0d0a6 at: https://648c3a747897085785307934--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit d65e9f7a8dd6c6b2c55496c0eba0f3fe01cb2b54 at: https://648c4ce54afc0304ae30f48a--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 1af21851e9d6591325bb04fc715889eca4566dec at: https://648c4ed8c9851705519b2e59--meshery-docs-preview.netlify.app

**Comment by adithyaakrishna** [comment]
@Chadha93 I am curious why we are running the screenshot action for changes in the docs 🤔

**Comment by l5io** [comment]
🚀 Preview for commit 043f521673efede79824f1448f2036f3bd00a3e4 at: https://648c6577fca9191f542e86aa--meshery-docs-preview.netlify.app

**Comment by Chadha93** [comment]
> @Chadha93 I am curious why we are running the screenshot action for changes in the docs thinking

@adithyaakrishna Yes, It's executed on every PR for now. We’re looking to get exposure and it's ([snapshot](https://github.com/layer5labs/meshmap-snapshot)) use. We are working on having a  different mechanism for this, so, unless we only trigger when a change to a Helm Chart is made.

**Comment by l5io** [comment]
Task linked: [CU-85zrzt5fg [Docs] MeshMap User Documentation with Tutorials](https://app.clickup.com/t/85zrzt5fg)

**Comment by l5io** [comment]
🚀 Preview for commit 09bd49ed2b8085be0079ee49dc9745ab0e799ecb at: https://648ca3ab751d1f0415e33313--meshery-docs-preview.netlify.app

**Review by Abhishek-kumar09 — COMMENTED** [review]
looks good

**Pull request merged**
