### PR TITLE
Convert MesheryAdapterPlayComponent from class-based component to functional component

### LINKED ISSUE #8812: [UI] Convert `MesheryAdapterPlayComponent` from class-based component to functional component
### Current Behavior
`MesheryAdapterPlayComponent` is a class-based component.

### Desired Behavior
`MesheryAdapterPlayComponent` should be a functional component.

### Implementation
Convert all the Class-based components to new updated functional components. It is important here to convert a class-based component to a functional component you may need to convert some functions as well. Check if the function is used in other components or not.

Also, make sure to use the hooks while converting them. For example, you need to covert withNotify with useNotification, useRouter hook. Please check if a hook for functional components is available and use that.

Here is a quick blog that will help you get started with : [Link](https://www.digitalocean.com/community/tutorials/five-ways-to-convert-react-class-components-to-functional-components-with-react-hooks)

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by toth2000**
**Notes for Reviewers**

This PR fixes #8812

# Potential Breaking Changes
## Need proper testing
I  have converted the class component `MesheryAdapterPlayComponent` to a functional component. I did some testing and fixed the issue that I encountered. But I am not very familiar with the usage of that component so proper testing is required to try out the full usage of the component. 

During the conversion to a functional component, I noticed a lot of functions and variables where defined but not used in the class component. Due to EsLint rules, I have removed some of the unused methods and commented other. A list is mentioned below.

## Unused Functions in Class Component
- handleChange (deleted)
- handleModalOpen (commented)
- handleSMIClick (commented)
- handleDeployModalOpen (commented)
- handleDeployModalClose (commented)
- activeContextChangeCallback (commented)
- generateSMIResult (commented)

### Note: Due to Eslint rule I had to comment these unused functions as a result of which I had to comment on several other functions/variables as well (as they were only used in those functions).

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Rajdip019** [comment]
Looks good @toth2000 . Love that you created a new hook for the functional component. Just make sure that was not used in other places.

Also, there is a lot of commented code. Make sure to clean them up or write why it is commented.

**Comment by Rajdip019** [comment]
Also, make sure to remove the withNotify and withRouter instead use react hooks that are already built and there in the codebase.

**Comment by toth2000** [comment]
> Looks good @toth2000 . Love that you created a new hook for the functional component. Just make sure that was not used in other places.

I have checked the methods are not called anywhere else.

> 
> Also, there is a lot of commented code. Make sure to clean them up or write why it is commented.

I have mentioned in the PR description a list of unused methods in the class component. I am not sure if I should remove these or not. So, I have commented.

**Comment by Rajdip019** [comment]
> > Looks good @toth2000 . Love that you created a new hook for the functional component. Just make sure that was not used in other places.
> 
> I have checked the methods are not called anywhere else.
> 
> > Also, there is a lot of commented code. Make sure to clean them up or write why it is commented.
> 
> I have mentioned in the PR description a list of unused methods in the class component. I am not sure if I should remove these or not. So, I have commented.

Yes, remove them. Do the small changes with `withNotify` and `withRouter` . Then please upload a video with the working state of the component.

**Comment by Rajdip019** [comment]
> > withNotify
> 
> `withNotify` is a custom hook what should I replace it with? and `withRouter` to be replaced with `useRouter` ?

You can replace `withNotify` with useNotification. You can see it's use in other functional components. 

And yeah you are right about the `withRouter`

**Comment by toth2000** [comment]
@Rajdip019 I have removed the commented code and replaced the `withNotify` and `withRouter` hooks with `useNotification` and `useHistory` hooks

**Comment by toth2000** [comment]
Here is a video of the component working:

https://github.com/meshery/meshery/assets/65480420/41e0458a-4205-48a8-9643-3db7ee03523b

**Comment by Rajdip019** [comment]
LGTM.

**Comment by saurabh100ni** [comment]
Let's discuss this on the Meshery dev call tomorrow,
Please add this as your agenda item in Docs: https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit

**Pull request closed without merging**
