### PR TITLE
Capitalize button text in Meshery UI modals

### LINKED ISSUE #9846: [Enhancement] Capitalize button text in Meshery UI modals
### Current Behavior
In some modals in Meshery, the button text is not capitalized and some modals have button text capitalized.

image

image

### Desired Behavior
Capitalize the button text in all the modals

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by Aayush2111**
**Notes for Reviewers**

This PR fixes #9846 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by saurabh100ni** [comment]
Hi @Aayush2111   ,
Thanks for your PR! I encourage you to share this in the Meshery Development Meeting tomorrow at 8:30 PM IST. Share your screen, and walk us through it. It's cool to take and share feedback. Check the [Doc](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit) here to include this PR.

You're welcome at the meeting

Check to [community calendar](https://layer5.io/community/calendar) for more details of meetings at Layers.

**Comment by sudhanshutech** [comment]
@Aayush2111 merge conflicts...

**Review by leecalcote — CHANGES_REQUESTED** [review]
Fix merge conflicts, please.

**Comment by leecalcote** [comment]
@ritiksaxena124 look good?

**Comment by ritiksaxena124** [comment]
Looks good to me 👍. I wonder if instead of hardcoding the button text we can just add the CSS property to the button component so that it automatically converts the text to uppercase @Aayush2111.

**Comment by sudhanshutech** [comment]
> Looks good to me 👍. I wonder if instead of hardcoding the button text we can just add the CSS property to the button component so that it automatically converts the text to uppercase @Aayush2111.

Make sense. @Aayush2111 any progress? This modals uses genric modal, you need to add style to that modal, a one line change.

**Comment by Aayush2111** [comment]
> > Looks good to me 👍. I wonder if instead of hardcoding the button text we can just add the CSS property to the button component so that it automatically converts the text to uppercase @Aayush2111.
> 
> Make sense. @Aayush2111 any progress? This modals uses genric modal, you need to add style to that modal, a one line change.

Sure, actually, the other buttons were also hardcoded, so I followed the same structure. Do you want me to remove the hardcoding and add CSS properties to them as well?
Screenshot (12)
Screenshot (13)

**Comment by Aayush2111** [comment]
@sudhanshutech @ritiksaxena124 
Suggesting something like this?

**Comment by leecalcote** [comment]
Calling on @sudhanshutech and @senali-d for their 👀 on.

**Pull request closed without merging**
