### PR TITLE
Replace the repetitive logic with handler pagination

### LINKED ISSUE #10825: Replace the repetitive logic for extracting `page, pagesize, search, offset` from API handlers to use  `getPaginationParams ` in `utils.go`.
Replace the repetitive logic for extracting `page, pagesize, search, offset` from API handlers to use  `getPaginationParams ` in `utils.go`.

_Originally posted by @MUzairS15 in https://github.com/meshery/meshery/pull/10824#discussion_r1585605275_

### PR DESCRIPTION
**Pull request by singh1203**
**Notes for Reviewers**

This PR fixes #10825

Replaces the repetitive logic for extracting page, page size, search, and offset from API handlers and uses getPaginationParams in utils.go

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Deepak0320Singhal** [comment]
@singh1203 Let's discuss this in Meshery Dev meeting on Wednesday. Adding this as an agenda item....
Meeting minutes: https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit?pli=1#
Meeting link: https://meet.layer5.io/meshery

**Comment by Jougan-0** [comment]
@singh1203 lint failing. :thinking:

**Review by leecalcote — CHANGES_REQUESTED** [review]
Two failing build checks.

**Review by leecalcote — APPROVED** [review]
@humblenginr, please be aware of this change.

**Pull request merged**
