### PR TITLE
Consolidate and remove duplicate ErrorBoundary.js

### LINKED ISSUE #9002: [UI] Consolidate or remove duplicate `ErrorBoundary.js`
There are two `ErrorBoundary.js` files.

- `/ui/components/General/ErrorBoundary.js`
- `/ui/components/ErrorBoundary.js`

Need to decide where to keep one of the file in, and remove the other file.

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by coder12git**
**Notes for Reviewers**

This PR fixes #9002

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by coder12git** [comment]
cc @nebula-aac

**Comment by aabidsofi19** [comment]
@coder12git  ,  we have now defined the error boundary component inside the `sistent` library .  we should be directly using it from there

**Comment by coder12git** [comment]
> @coder12git , we have now defined the error boundary component inside the `sistent` library . we should be directly using it from there

Okay @aabidsofi19

**Comment by saurabh100ni** [comment]
Let's discuss this on the Meshery dev call tomorrow at 7:30 pm IST / 9:00 am CT,
Please add this as your agenda item in Docs: https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit

**Comment by leecalcote** [comment]
@coder12git what would you like to do with the PR in the meantime?

**Comment by coder12git** [comment]
> @coder12git what would you like to do with the PR in the meantime?

@leecalcote nothing because we already have a `error boundary` component inside the `sistent` library , so i don't think there is any use of this PR.

**Pull request closed without merging**
