### PR TITLE
Try pinning Node v18.12.1 and use openssl legacy flags to fix open-ssl webpack nodejs error cy integration tests run thrown after Meshery UI is started in dev mode

### LINKED ISSUE #6864: [CI] ui-integration tests are unable to start (Error: error:0308010C:digital envelope routines::unsupported, ERR_OSSL_EVP_UNSUPPORTED)
#### Current Behavior
There's a recurrent issue during running meshery cypress integration tests ('ci-test-integration' npm script called by [our buld-ui-and-server.yml ci workflow](https://github.com/meshery/meshery/blob/master/.github/workflows/build-ui-and-server.yml#L119)) in which we get the following error (see [here](https://github.com/meshery/meshery/actions/runs/3835743870/jobs/6529301044) for example):
```
> meshery-ui@1.0.0 dev16
> eslint . --fix && node ui_dev_server.js

info  - Using webpack 4. Reason: custom webpack configuration in next.config.js https://nextjs.org/docs/messages/webpack5
node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports.__webpack_modules__.15660.module.exports (/home/runner/work/meshery/meshery/ui/node_modules/next/dist/compiled/webpack/bundle4.js:111680:62)
    at NormalModule._initBuildHash (/home/runner/work/meshery/meshery/ui/node_modules/next/dist/compiled/webpack/bundle4.js:85092:16)
    at handleParseError (/home/runner/work/meshery/meshery/ui/node_modules/next/dist/compiled/webpack/bundle4.js:85146:10)
    at /home/runner/work/meshery/meshery/ui/node_modules/next/dist/compiled/webpack/bundle4.js:851[78](https://github.com/meshery/meshery/actions/runs/3835743870/jobs/6529301044#step:5:79):5
    at /home/runner/work/meshery/meshery/ui/node_modules/next/dist/compiled/webpack/bundle4.js:[85](https://github.com/meshery/meshery/actions/runs/3835743870/jobs/6529301044#step:5:86)033:12
    at /home/runner/work/meshery/meshery/ui/node_modules/next/dist/compiled/webpack/bundle4.js:51096:3
    at iterateNormalLoaders (/home/runner/work/meshery/meshery/ui/node_modules/next/dist/compiled/webpack/bundle4.js:50937:10)
    at Array.<anonymous> (/home/runner/work/meshery/meshery/ui/node_modules/next/dist/compiled/webpack/bundle4.js:50928:4) {
  opensslErrorStack: [ 'error:030000[86](https://github.com/meshery/meshery/actions/runs/3835743870/jobs/6529301044#step:5:87):digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v***.12.1
Error: server closed unexpectedly
    at ChildProcess.onClose (/home/runner/work/meshery/meshery/ui/node_modules/start-server-and-test/src/index.js:75:14)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:10[91](https://github.com/meshery/meshery/actions/runs/3835743870/jobs/6529301044#step:5:92):16)
    at ChildProcess._handle.onexit (node:internal/child_process:302:5)
Error: Process completed with exit code 1.
```

#### Desired Behavior
cypress tests should not error out due to starting Meshery UI in development mode throwing a webpack 4 error coming from changes in internal open-ssl lib from Node ([webpack issue #14532](https://github.com/webpack/webpack/issues/14532)).

#### Implementation
According to [StackOverflow "Error message "error:0308010C:digital envelope routines::unsupported" question](https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported) there are several ways to solve it but the wisest one is not to downgrade nor use legacy openssl flag because it leaves several security vulnerabilities unpatched and according to [reply "For me adding this in the script once is better than restricting the node version, the long term fix would be to migrate to webpack@5, I don't see additional value in sticking with node16"](https://github.com/webpack/webpack/issues/14532#issuecomment-1370851349) in [webpack issue #14532](https://github.com/webpack/webpack/issues/14532), long term fix is to migrate to webpack v5.

#### Acceptance Tests

???

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by MarioArriaga92**
**Notes for Reviewers**

This PR fixes #6864.

Trying this out don't merge yet please.

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by acald-creator** [comment]
Please note that I have already done some of the leg work on this PR, which will explain some of the packages that broke in the CI build and local development.

https://github.com/meshery/meshery/pull/6747

I added `.npmrc` with `legacy-peer-deps=true` in order to get the old packages to stay installed in for the time being. I suggested it to @leecalcote as a short term fix until I finish the code editor portion, and migrate MUI.

Please note that in the midst of migrating to MUI v5, see here on MUI installation page where they are relying on React 17. 

https://mui.com/system/styles/basics/

So in my PR, I suggested to upgrade to minimum Next 12. Because when it comes to migrating MUI from v4 to v5, I also suggest using `@mui/styles` as a temporary package to use until we migrate completely onto MUI v5.

`@mui/styles` does not work directly on React 18.

https://mui.com/system/styles/basics/

So it is either go all in, and skip `@mui/styles` or use `@mui/styles` temporarily so we can gradually move all styles to the newest way of MUI.

To finalize this, we can use `.npmrc` in order for the packages that rely on a certain version of Next.js and/or React in order to move forward to Next.js 13/React 18.

**Comment by acald-creator** [comment]
While making changes to this PR, I ran into this issue.

```bash
INFO[2023-01-10T21:35:39-06:00] Updated object: cluster-dns/kube-system of kind: ConfigMap in the database  app=meshery
DEBU[0181] No valid mesh adapter(s) found.               file=events_streamer
DEBU[0186] No valid mesh adapter(s) found.               file=events_streamer
DEBU[0191] No valid mesh adapter(s) found.               file=events_streamer
DEBU[0196] No valid mesh adapter(s) found.               file=events_streamer
DEBU[0201] No valid mesh adapter(s) found.               file=events_streamer
DEBU[0206] No valid mesh adapter(s) found.               file=events_streamer
DEBU[0211] No valid mesh adapter(s) found.               file=events_streamer
DEBU[0216] No valid mesh adapter(s) found.               file=events_streamer
DEBU[0221] No valid mesh adapter(s) found.               file=events_streamer
INFO[2023-01-10T21:36:19-06:00] k3d-k3s-default components for contextID:14b3dd7438b74b84525dd6ff0091ab59 registered  app=meshery
panic: definitions: field not found: a

goroutine 16664 [running]:
github.com/layer5io/meshery/server/models/meshmodel/core.getResolvedManifest({0xc007646000, 0x3f8014})
        /home/phxvlabs-io/go/src/github.com/workspace/meshery/server/models/meshmodel/core/register.go:158 +0x31e
github.com/layer5io/meshery/server/models/meshmodel/core.getCRDsFromManifest({0xc007646000?, 0xc005886000?}, {0xc0005a6000, 0x4f, 0x0?})
        /home/phxvlabs-io/go/src/github.com/workspace/meshery/server/models/meshmodel/core/register.go:165 +0x46
github.com/layer5io/meshery/server/models/meshmodel/core.GetK8sMeshModelComponents({0x40ad560?, 0xc006a88480?}, {0xc000cf5000?, 0x192?, 0x5d?})
        /home/phxvlabs-io/go/src/github.com/workspace/meshery/server/models/meshmodel/core/register.go:119 +0x5eb
github.com/layer5io/meshery/server/handlers.RegisterK8sMeshModelComponents({0x463d4f8?, 0xc000122000?}, {0xc000cf5000?, 0xf?, 0xc0011c2ae0?}, {0xc001d431a0, 0x20}, 0x15?)
        /home/phxvlabs-io/go/src/github.com/workspace/meshery/server/handlers/k8sconfig_handler.go:349 +0x5e
github.com/layer5io/meshery/server/models.(*ComponentsRegistrationHelper).RegisterComponents.func1(0xc001123440?)
        /home/phxvlabs-io/go/src/github.com/workspace/meshery/server/models/k8s_components_registration.go:94 +0x25e
created by github.com/layer5io/meshery/server/models.(*ComponentsRegistrationHelper).RegisterComponents
        /home/phxvlabs-io/go/src/github.com/workspace/meshery/server/models/k8s_components_registration.go:71 +0x58a
exit status 2
make: *** [Makefile:103: server] Error 1
```

Will need this fixed before I can move forward.

**Comment by MarioArriaga92** [comment]
@acald-creator here's some warnings, not sure if we can ignore them for now:
```
warn  - Url '/' defines a query parameter '__nextDefaultLocale' that is missing in exportPathMap
(node:1889) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 client/ listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1889) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 server/ listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit
```

But now it seems that running the Meshery UI dev server doesn't fail although cypress fails because of some uncaught exception in the frontend (which I've seen before), I'll see if I can fix it by following ["cypress handling errors" recipe](https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/fundamentals__errors#handling-application-errors) we've used in the past:
```
1) Test if UI components are displayed on Index Page
       "after each" hook for "Left Navigation Panel":
     TypeError: The following error originated from your application code, not from Cypress.

  > Cannot set properties of null (setting 'onopen')

When Cypress detects uncaught errors originating from your application it will automatically fail the current test.

This behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.
```

**Comment by acald-creator** [comment]
> @acald-creator here's some warnings, not sure if we can ignore them for now:
> 
> ```
> warn  - Url '/' defines a query parameter '__nextDefaultLocale' that is missing in exportPathMap
> (node:1889) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 client/ listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit
> (Use `node --trace-warnings ...` to show where the warning was created)
> (node:1889) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 server/ listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit
> ```
> 
> But now it seems that running the Meshery UI dev server doesn't fail although cypress fails because of some uncaught exception in the frontend (which I've seen before), I'll see if I can fix it by following ["cypress handling errors" recipe](https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/fundamentals__errors#handling-application-errors) we've used in the past:
> 
> ```
> 1) Test if UI components are displayed on Index Page
>        "after each" hook for "Left Navigation Panel":
>      TypeError: The following error originated from your application code, not from Cypress.
> 
>   > Cannot set properties of null (setting 'onopen')
> 
> When Cypress detects uncaught errors originating from your application it will automatically fail the current test.
> 
> This behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.
> ```

The first part can be ignored for now. This is something that will needs to be configured in `next.config.js` but it is just a warning.

The second part refers to when redux and websocket is being called for, and in the process, I believe there is not a timer to check for redux and also websocket until it is actually up. Last I check in the processing of building UI and the server, there is a delay before the server is officially up, where the ui is already looking for the server to be running. Therefore, the error comes up.

**Comment by leecalcote** [comment]
Good to close this out?

**Comment by acald-creator** [comment]
We can close this out for now, as we're using Node 18 in GitHub Actions, and I will need to do some research on how to use Cypress to test for changes from Redux/React-Redux.

We are also we `webpack` version 5, so we should be good for now. We can revisit if issues come up again.

**Pull request closed without merging**
