### PR TITLE
Update 2024-08-15-newcomers-meeting.md

### PR DESCRIPTION
**Pull request by AnkityadavIITR**
**Notes for Reviewers**

This PR fixes #
Newcomers attendance

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 8be11e47d7a9b7fe54d6021adf3ccdcec776591e at: https://66be09cd6d5adc34da188e16--meshery-docs-preview.netlify.app

**Comment by AnkityadavIITR** [comment]
> @AnkityadavIITR Missing DCO. Check the steps to include sign off in your commit here: https://github.com/meshery/meshery/pull/11665/checks?check_run_id=28814619893

image
in the image summary has the correct notation, can you help me , how to re commit this

**Comment by vishalvivekm** [comment]
Please follow this: 

`
To add your Signed-off-by line to every commit in this branch:

Ensure you have a local copy of your branch by [checking out the pull request locally via command line](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/checking-out-pull-requests-locally).
In your local branch, run: git rebase HEAD~1 --signoff
Force push your changes to overwrite the branch: git push --force-with-lease origin patch-2
`

**Review by leecalcote — APPROVED** [review]
LGTM. Thanks, @AnkityadavIITR

**Review by leecalcote — APPROVED** [review]

**Comment by l5io** [comment]
🚀 Preview for commit 7170018cefe6b13355b60a0203b655adb1ff56f0 at: https://66be48e62e79771d6ee44e4e--meshery-docs-preview.netlify.app

**Pull request merged**
