### PR TITLE
[Docs] Add code for additional alert types and eliminate duplicate entries

### LINKED ISSUE #9224: [Docs]  Add code for additional alert types and eliminate duplicate entries.
### Current State

Currently, this file - https://github.com/meshery/meshery/blob/master/docs/_sass/alert.scss, doesn't support all alert types listed in the docs - https://docs.meshery.io/project/contributing/contributing-docs#alerts

### Desired State
 - Add code for rest other alert types as listed in the docs -  `danger,success, primary and secondary`
 - Remove duplicate entries for alerts section

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by coder12git**
**Notes for Reviewers**

This PR fixes #9224

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 27ee44c9e63459640add9ac3864b48fcae200b64 at: https://653c3b5d2f3724008f657a97--meshery-docs-preview.netlify.app

**Comment by vishalvivekm** [comment]
@coder12git Let's discuss it on the websites call today.
I've added this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima).

**Comment by coder12git** [comment]
@leecalcote please check this

**Comment by coder12git** [comment]
https://653c3b5d2f3724008f657a97--meshery-docs-preview.netlify.app/project/contributing/contributing-docs#alerts

**Comment by leecalcote** [comment]
Thank you. Of the places where we have used alerts already, how did these look?

**Comment by coder12git** [comment]
> Thank you. Of the places where we have used alerts already, how did these look?

I think, it will look good there, because I have used standard colors that are define for each type of alert.

**Comment by abhijeetgauravm** [comment]
Let's discuss this on Meshery Development Meeting today at 8:30 PM IST / 9 AM Central time. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#).

**Pull request merged**
