### PR TITLE
Fix typo in the contributing-guidelines page

### LINKED ISSUE #3500: [Docs]
#### Current State
A typo in the [Contributing Guidelines](https://docs.meshery.io/project/contributing-guide) page. (Highlighted in the screenshot)

Issue-1

#### Desired State
Must be fixed to "functionality"
---

#### Contributor Resources

- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/meshery/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
- [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by Anand-Theertha**
Signed-off-by: Anand-Theertha <anandtheerthav3@gmail.com>

**Description**

This PR fixes #3500 
A typo found in https://docs.meshery.io/project/contributing-guide, the typo being highlighted in the screenshot added below. 

https://user-images.githubusercontent.com/54447234/125572256-688222bf-8121-4626-b38d-e46d53aa8529.PNG

**Notes for Reviewers**
Satisfies desired behavior of the issue. The word has been changed to "functionality". 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 78864207cdd6c9e2c287d9dcac7eaaf02b9cf748 at: https://60eeabd1faeeb22e451ccda7--meshery-docs-preview.netlify.app

**Review by alphaX86 — APPROVED** [review]
LGTM on my side 👍

**Comment by alphaX86** [comment]
@Anand-Theertha if possible rename the title as "Fix typo in contributing guidelines..." like that :)

**Review by sayantan1413 — APPROVED** [review]
LGTM and +1 with @alphaX86 last comment. Thanks @Anand-Theertha.

**Review by Anita-ihuman — APPROVED** [review]
Thank you  @Anand-Theertha, Great job.

**Comment by Anand-Theertha** [comment]
@alphaX86 @sayantan1413 Made the change mentioned! Thanks!

**Comment by alphaX86** [comment]
Just wait until a maintainer checks and merges it :) don't close too early

**Comment by l5io** [comment]
🚀 Preview for commit 78864207cdd6c9e2c287d9dcac7eaaf02b9cf748 at: https://60eef225c1deba43a43011cb--meshery-docs-preview.netlify.app

**Comment by Anita-ihuman** [comment]
@Anand-Theertha please write a description for this PR and I will go ahead and merge it.

**Comment by Anand-Theertha** [comment]
@alphaX86 Ohh, I messed that up, my bad. @Anita-ihuman Is the description "descriptive" enough? xD

**Comment by Anita-ihuman** [comment]
congratulations

**Pull request merged**
