### PR TITLE
Selected Items don't disappear in Table view when deletion denied in modal in Application page

### LINKED ISSUE #6754: [UI] Selected Items disappear in Table view, Even when deletion denied in modal
#### Current Behavior

Currently at /configuration/filters, /configuration/applications, /configuration/patterns. On clicking the delete icon all the selected items get disappeared. Even when NO is selected in the delete modal.

https://user-images.githubusercontent.com/103871275/208772597-e638472e-c9f0-47f7-9fb4-1ecbb1d6288e.mp4

#### Desired Behavior

Items should appear after NO is selected in the delete modal.

#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by hs05june**
**Notes for Reviewers**

This PR fixes #6754 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by hs05june** [comment]
Hey @leecalcote Please review the PR.

**Comment by hs05june** [comment]
Hey @leecalcote . Please suggest if I have to make some changes in the PR.

**Review by Chadha93 — COMMENTED** [review]
Thank you for this @hs05june. Could you also confirm the behavior in the designs/filters page, if they also require an update?

**Comment by Chadha93** [comment]
@hs05june  Let's discuss this on the Meshery Dev call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#) if you would. :)

**Comment by hs05june** [comment]
Yes @Chadha93 . Filters page also requires an update. Designs page has already been updated in my previous PR.

**Review by Abhishek-kumar09 — APPROVED** [review]
The changes looks good, as @Chadha93 asks if you can put the fix for filters page as well.

**Review by Abhishek-kumar09 — CHANGES_REQUESTED** [review]
@hs05june https://github.com/meshery/meshery/pull/6758/files In this PR you have already created the CustomToolbarSelection component. Since the three pages, design, applications and filters are all similar, can you resuse the same component and pass the deletion function as prop rather.

**Comment by hs05june** [comment]
@Abhishek-kumar09 The delete function which is being passed as a prop in the custom toolbar component is similar for applications and filters page. But it is very different for designs page. I thought to do that but couldn't figure out how to tackle the delete function.
Screenshot from 2022-12-28 17-03-41
Screenshot from 2022-12-28 17-03-12
Screenshot from 2022-12-28 17-04-31

**Comment by hs05june** [comment]
https://user-images.githubusercontent.com/103871275/209952769-797e7fb0-ae8e-47d2-ad25-24ebba6df5b5.mp4

@Abhishek-kumar09 Fixed for filters page using the same custom toolbar select. Since, the delete function for designs wasn't same as in application and filter. I didn't use the same toolbar as made in pr #6758.

**Pull request merged**
