### PR TITLE
tools section gets hidden in many components of docs

### LINKED ISSUE #5812: [Docs] tools section gets hidden in many components of docs
#### Current State
Tools Section gets hidden behind header in many components
1. Concepts (https://docs.meshery.io/concepts)
2. Functionality (https://docs.meshery.io/functionality)
3. Guides (https://docs.meshery.io/guides)
4. Reference (https://docs.meshery.io/reference)
Screenshot from 2022-07-13 17-59-26

#### Desired State
Tools should be shown properly like in normal components
Screenshot from 2022-07-13 18-01-47

---

#### [Contributor Guides](https://docs.meshery.io/project/contributing) and Resources
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

i would like to solve this issue

### PR DESCRIPTION
**Pull request by manikmmalhotra**
Signed-off-by: manikmmalhotra <manikmalhotra2113@gmail.com>

**Description**
tools section gets hidden in many components of docs, Solved now
This PR fixes #5812 

**Notes for Reviewers**
Always open for suggestions and improvements. Please point me out if anything should be added/corrected.

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 5a26245d14ce122d9099db988dd70f4406650fde at: https://62db15c4509fb60d02dcca30--meshery-docs-preview.netlify.app

**Comment by leecalcote** [comment]
How does this not negatively impact pages that already have enough padding/margin?

**Comment by manikmmalhotra** [comment]
@leecalcote yeah i just saw that i've messed up with this solution i'll fix this up right now

**Comment by l5io** [comment]
🚀 Preview for commit cce7e100ff1e617134587cc584278160f88d1cf7 at: https://62db22d3a363651717531537--meshery-docs-preview.netlify.app

**Comment by manikmmalhotra** [comment]
@leecalcote fixed now as the toc component was assigned fixed height of 100vh which causing extra scroll and for components with less content on the main component it pushes the toc to top causing the error , i now changed it to 100% which will optimize according to contents hence solving our issue

**Comment by leecalcote** [comment]
@adithyaakrishna

**Comment by leecalcote** [comment]
@adithyaakrishna you're review here would be helpful.

**Comment by adithyaakrishna** [comment]
@manikmmalhotra LGTM, thank you for working on this 🚀 

Checked across the 4 pages mentioned in the issue description along with a couple of other pages(to confirm it does not break on other pages) and the fix seems to be working 🎉 

**Ref:**
1. https://62db22d3a363651717531537--meshery-docs-preview.netlify.app/concepts
2. https://62db22d3a363651717531537--meshery-docs-preview.netlify.app/functionality
3. https://62db22d3a363651717531537--meshery-docs-preview.netlify.app/reference
4. https://62db22d3a363651717531537--meshery-docs-preview.netlify.app/guides

**Review by adithyaakrishna — APPROVED** [review]

**Comment by adithyaakrishna** [comment]
@leecalcote Apologies for the delay, I missed a lot of notifications and going through them one by one 👀

**Comment by leecalcote** [comment]
Thanks! 😄

**Pull request merged**
