### PR TITLE
UI/InfoModal: Move Copy Link Button 

### PR DESCRIPTION
**Pull request by dottharun**
Signed-off-by: Tharun T <tharun242424@gmail.com>

**Notes for Reviewers**

- Blocked by https://github.com/layer5io/sistent/pull/674

This PR fixes the CopyLink button
image

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — CHANGES_REQUESTED** [review]
@dottharun, if you agree that one of these other two locations encircled in red are a more intuitive placement in terms of indicating what the chain icon does, will you please relocate it?

350407106-9b9e392b-f564-4ca5-a54a-a94b86bccd4a

**Comment by dottharun** [comment]
@leecalcote Changes are done.

**Comment by leecalcote** [comment]
> @leecalcote Changes are done.

Looking real good, @dottharun! 🎈 

I see that the do-not-merge label is attached to this PR. Is that ready to be removed?

**Review by leecalcote — APPROVED** [review]

**Comment by dottharun** [comment]
> I see that the do-not-merge label is attached to this PR. Is that ready to be removed?

Yes, I have removed it now.

**Comment by leecalcote** [comment]
Good deal. Two points of feedback from review today:

1. A request to remove the redundant design name under the snapshot
2. A request to change the visibility label to a dropdown. I think this is handled in a different PR. Please find that PR and assist in getting it merged, if you would.

**Comment by leecalcote** [comment]
@dottharun still do not merge?

**Comment by dottharun** [comment]
> @dottharun still do not merge?

Since we decided to use shareModel, this is blocked by https://github.com/layer5io/sistent/pull/674

**Pull request closed without merging**
