### PR TITLE
docs: fix language in functionality

### LINKED ISSUE #4561: [Docs] Remove the link directing to the English page from the Spanish page.
#### Current State
We have link to pages of both languages (English and Spanish) on this page https://docs.meshery.io/es/functionality.

#### Desired State
There should be links to only Spanish language pages on this page.

#### How can it be solved?
A similar issue has been solved via PR #4516. Go check out the PR and if you still have any doubt please feel free to reach out.

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by taltrums**
Signed-off-by: Mohd Talha <mohmmad.talha@outlook.com>

**Description**

This PR fixes #4561

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.
 

meshery-links-spanish

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit d295b21fb4bdc3d069f42f8d82d6adba556340ef at: https://6182f937f2ae6419f5c61017--meshery-docs-preview.netlify.app

**Review by adithyaakrishna — APPROVED** [review]
@sidecodes Thank you for your contribution 🎉 

**Verified:** https://6182f937f2ae6419f5c61017--meshery-docs-preview.netlify.app/es/functionality

**Review by shubham-tyagi — APPROVED** [review]
Good stuff 😃 @sidecodes

**Review by shubham-tyagi — APPROVED** [review]
Great stuff !! @sidecodes

**Pull request merged**
