### PR TITLE
[Docs] Custom Callback

### PR DESCRIPTION
**Pull request by tangledbytes**
**Description**

This PR adds docs for support of `custom callback` which was added in meshery release `v0.5.39`

**Notes for Reviewers**
Not quite sure if there are other places where this needs to be added :thinking: 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by utkarsh-pro** [comment]
// @samirparhi-dev

**Comment by l5io** [comment]
🚀 Preview for commit febe080a796dde499ea013e1879e32d211e117e9 at: https://60fff4943a48f4de39842145--meshery-docs-preview.netlify.app

**Review by leecalcote — CHANGES_REQUESTED** [review]
Here is another spot - https://docs.meshery.io/extensibility/providers - that can be updated.

**Review by leecalcote — APPROVED** [review]
@samirparhi-dev you'll have to let us know if this works for you.

**Pull request merged**
