### PR TITLE
[UI] Connections: External Link and Light Mode Issue

### PR DESCRIPTION
**Pull request by senali-d**
**Notes for Reviewers**

This PR fixes #
- [x] Dark mode issues (status chip)
- [x]  Add Server Location as a external link to element column 
- [x] Remove row expand icon (Row expand on click the row)

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — DISMISSED** [review]

**Comment by leecalcote** [comment]
@senali-d are these dark and light mode changes for the Connections page consideration of their potential impact across Meshery UI?

**Comment by leecalcote** [comment]
The external link styling has improved, but the connect state chips, don't seem to be.
Screenshot 2023-08-18 at 3 40 24 PM

**Comment by senali-d** [comment]
> The external link styling has improved, but the connect state chips, don't seem to be. Screenshot 2023-08-18 at 3 40 24 PM

@ritiksaxena124 Look like "Deleted" status chip color was not works in dark mode.

**Comment by senali-d** [comment]
> @senali-d are these dark and light mode changes for the Connections page consideration of their potential impact across Meshery UI?

@leecalcote Still those colors are only used in connections page.

**Comment by leecalcote** [comment]
> > @senali-d are these dark and light mode changes for the Connections page consideration of their potential impact across Meshery UI?
> 
> @leecalcote Still those colors are only used in connections page.

ok, good deal. 👍 

We'll need to increase the contrast, @senali-d @ritiksaxena124

**Comment by leecalcote** [comment]
I think this is pending one more update - https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?type=design&node-id=16188-38481&mode=design&t=gsWPvU7dJR23IIaQ-4

**Comment by ritiksaxena124** [comment]
@senali-d could you please share the screenshot of how it looks now in dark and light mode?

**Pull request merged**
