### PR TITLE
Fixed many links including the issue  #9892

### LINKED ISSUE #9892: [UI] environments links are not working
### Current Behavior

image

### Desired Behavior

links are not working showing 404 error

[https://docs.meshery.io/concepts/logical/credentials](https://docs.meshery.io/concepts/logical/credentials)

### Screenshots/Logs

Screenshot 2024-01-09 125336

### Environment

- Browser: Chrome
- Host OS: Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by Conqxeror**
**Notes for Reviewers**

This PR fixes #9892
There were more links not working on the page. Fixed them too.

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [y ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 7f4b8a527e09780536bf577f0661a35cc639a70a at: https://659fa6bdd1a32f413be9cb24--meshery-docs-preview.netlify.app

**Review by leecalcote — CHANGES_REQUESTED** [review]
Thanks, @Conqxeror. Will you please change this PR to publish the pages under `/concepts/logical/....`? In other words, the links are correct, but its the publication of the pages that need to change their location.

**Comment by l5io** [comment]
🚀 Preview for commit ece28cbece49ec107d039e330945c3ad8a13613b at: https://65a06c42bbae7147d456e6ce--meshery-docs-preview.netlify.app

**Review by leecalcote — APPROVED** [review]
I tossed in those fixes. Thanks for taking care of this, @Conqxeror 👍

**Comment by Conqxeror** [comment]
> I tossed in those fixes. Thanks for taking care of this, @Conqxeror 👍

Thank You😊 You're welcome 😊.

**Pull request merged**
