### PR TITLE
Improve error message

### PR DESCRIPTION
**Pull request by MUzairS15**
Signed-off-by: MUzairS15 <muzair.shaikh810@gmail.com>

**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
@MUzairS15  the verbiage itself is fine as-is. The issue here is that this log is being sent redundantly, so it’s the logic by which is sent that needs review.

**Comment by leecalcote** [comment]
Gents, what's next here?

**Comment by leecalcote** [comment]
merge conflict...

**Comment by leecalcote** [comment]
@MUzairS15 please give this one more shot, if you would.

**Comment by MUzairS15** [comment]
@leecalcote will give a shot

**Pull request closed without merging**
