### PR TITLE
Nikhil/feature/performance profile

### PR DESCRIPTION
**Pull request by Nikhil-Ladha**
**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by Nikhil-Ladha** [comment]
@kushthedude ^^

**Comment by Nikhil-Ladha** [comment]
Will fix those. For the view and edit button, how about of use the icon of a pen/pencil? Like this one 
Screenshot_20200904-095404__01
Or this one
Screenshot_20200904-095429__01

**Comment by leecalcote** [comment]
Those edits icons will do the trick, @Nikhil-Ladha 👍

**Comment by leecalcote** [comment]
@Nikhil-Ladha these last commits are a nice improvement. I don't think I can find a responsive issue here. Looks good.

- [on the page] the ability to search might be nice.
- [on the page] the ability to add a new test profile (providing a modal of the /performance page or redirecting to it).
- [on the card] a confirmation dialogue when "delete" is clicked would be good.
- [on the card] a small "Last run: Sept. 7th, 2020 12:09pm" could be helpful.

**Comment by Nikhil-Ladha** [comment]
Something happened and instead of pushing changes to this branch, a new PR got created. So closing this one.
New PR #1643

**Pull request closed without merging**
