### PR TITLE
Add Handler for fetching connection by ID in Meshery Server

### LINKED ISSUE #11418: [Server] Add support for fetching connection by ID in Meshery Server
### Current Behavior

The [connection handler](https://github.com/meshery/meshery/blob/master/server/handlers/connections_handlers.go) lacks a handler function for the corresponding API endpoint to fetch a connection by its ID. Although the [provider functions](https://github.com/meshery/meshery/blob/fce14a61472bc114be3e47983ae1f6355a560f80/server/models/remote_provider.go#L3892) for retrieving a connection by ID have already been implemented, they are not currently utilized by the server's handlers. This limitation restricts the ability to query connections directly by their IDs through the API.
### Desired Behavior

Implement a handler function in the Meshery Server that allows a connection to be fetched by its ID. Additionally, an API endpoint should be added to expose this functionality. This will enable users to query specific connections directly by their IDs, improving the flexibility and usability of the API.
### Mockups

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by singh1203**
**Notes for Reviewers**
Implement a handler function in the Meshery Server that allows a connection to be fetched by its ID
Added GET request method for `/api/integrations/connections/{connectionId}`

This PR fixes #11418 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Ashparshp** [comment]
@singh1203 @Yashsharma1911, let's discuss this PR during the Meshery dev meeting call, if you would. Please add it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit?usp=drivesdk).

**Review by Yashsharma1911 — APPROVED** [review]
LGTM

**Comment by leecalcote** [comment]
Failing checks are expected or no?

**Comment by lekaf974** [comment]
Looks we had a discussion related to this implementation since we have already this GET on `connectionKind` in the router https://github.com/meshery/meshery/blob/e756329fa4386a03f18c4449a3ea827432580ffd/server/router/server.go#L413 

I don't think we can do this, did you test your solution and validate it was working as expected ?

**Comment by lekaf974** [comment]
@MUzairS15 any concern ?

**Comment by lekaf974** [comment]
> Looks we had a discussion related to this implementation since we have already this GET on `connectionKind` in the router
> 
> https://github.com/meshery/meshery/blob/e756329fa4386a03f18c4449a3ea827432580ffd/server/router/server.go#L413
> 
> I don't think we can do this, did you test your solution and validate it was working as expected ?

found the thread https://layer5io.slack.com/archives/C0130BQ4L3T/p1715782477999799?thread_ts=1715684626.374219&cid=C0130BQ4L3T

**Comment by Ashparshp** [comment]
@singh1203 let's discuss this PR during the Meshery dev meeting call if has to share anything, if you would. Please add it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit?usp=drivesdk).

**Review by leecalcote — APPROVED** [review]

**Pull request closed without merging**
