### PR TITLE
docs: updated command reference for mesheryctl filter

### LINKED ISSUE #8207: [Docs] Update command reference for mesheryctl filter
#### Current State
https://docs.meshery.io/reference/mesheryctl#data-plane-intelligence-experimental-feature
image

#### Desired State
1. Remove `(experimental feature)`
2. Add `mesheryctl filter import` subcommand
3. Currently the subcommands are linked to `home/reference/mesheryctl/exp/filter/<subcommand>`. Since `mesheryctl` filter has been removed from under`exp` (experimental feature), the subcommand should now be linked to the pages `home/reference/mesheryctl/filter/<subcommand>`
image
image
4. Reflect any changes in [mesheryctl filter](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0&range=A123:A131) to the docs.

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by Yana-Gupta**
**Notes for Reviewers**

This PR fixes #8207

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 3ff46218985ae7ecbd2bcee7af667e776572d0de at: https://64b8fff29dcc33630cf8943f--meshery-docs-preview.netlify.app

**Review by leecalcote — APPROVED** [review]
Good work, @Yana-Gupta. 

@alphaX86 @abdullah1308 @suhail34 @hexxdump fyi

**Comment by leecalcote** [comment]
@thisiskaransgit we're failing on deploy previews for docs, it seems.

**Comment by thisiskaransgit** [comment]
@Yana-Gupta, why was there a dependency update in the lockfile?

**Comment by Yana-Gupta** [comment]
> @Yana-Gupta, why was there a dependency update in the lockfile?

It updated automatically while running command `bundle install`

**Comment by thisiskaransgit** [comment]
@Yana-Gupta, please avoid pushing any unwanted modifications and ensure that manifest files or lockfiles remain unchanged unless directly relevant to this pull request. Hope you will keep that in mind as we look forward to see more contributions from you 😄

**Pull request merged**
