### PR TITLE
[Server] Supporting `v1beta1` constructs.

### PR DESCRIPTION
**Pull request by MUzairS15**
**Notes for Reviewers**

This PR updates the server to use new `v1beta1` constructs for models, components, relationships and designs.

The complete support requires an update / refactoring in

- [x] Model generator.
- [x] Updating the registration logic to support new changes.
- [x] Upgrading the Graphql schema and its resolvers.
- [x] Pattern engine
   - [x] Provisioning/De-provisioning of designs.
   - [x] Dry Run on designs.
- [x] Updating the Adapter grpc interface.
- [x] Migrating from `hosts` to `connection` for registrants.
- [x] Test for converting and validating existing designs against designs v1beta1 format.
- [x] Meshery pattern APIs to support real-time conversion of old designs.
- [x] Ensuring conversion of k8s/compose/helmchart to designs.
- [x] Adding `capabiliites` for the models and components.
- [ ] Migrating the existing 
     - [x] models
     - [ ] components
     - [x] relationships
- [x] Update in the relationship evaluation logic. (Using  relationships block from designs, and v1beta1 properties)
   Almost half of the migration of the evaluation logic is done. (Edge bindings, hierarchical inventory relationships now support referring the relationship def to perform the patch action)

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
@humblenginr, in the short-term this has been done:

> Updating the Adapter grpc interface.

An ideal future is one of the adapter simply passing along one or more Models as OCI images, allowing the existing registration logic in Meshery Server to handle the rest.

**Comment by leecalcote** [comment]
This is good:
 
- [x] Migrating from hosts to connection for registrants.

However, Meshery Server should not circumvent the registration process by seeding "GitHub", "Artifact Hub", and other connections on boot. Instead, Meshery Server needs to be a client just like any other as it presents itself as a registrant (as one or more connections) with models for registration (at boot time). If Meshery Server is honoring the registration process, the boot time registration process should invoke an individual registration operation for each model being registered. Connections should not be duplicated. Code from Meshery Adapters should be reused by Meshery Server for this initialization process.

**Review by leecalcote — APPROVED** [review]

**Comment by l5io** [comment]
🚀 Preview for commit 1cc147c3e5f887b5a23dcdad8b01406d437c2559 at: https://66bb36a2450da3f07965c392--meshery-docs-preview.netlify.app

**Comment by MUzairS15** [comment]
- [ ] Issues with models and registrant APIs 
   - [ ] [API doesn't return all models and registrants despite having them registered.]
   - [ ] Models with registrant as `Unknown` getting registered. (Might be issue with the migration script, as it includes some logic to assign Unknown registrant).
- [ ] Migration of components to v1beta1 format `https://github.com/meshery/schemas/pull/137`
- [ ] Migration of old designs to v1beta1 format. https://github.com/meshery/schemas/blob/master/models/v1beta1/pattern/design_conversion.go
- [ ] Relationships and policies
   - [ ] Siblings matchlabels relationship and policy.
   - [ ] Policies for hierarchical parent and inventory relationships.
   - [ ] Policies for edge bindings relationships. 
   - [ ] Relationships converted to `v1alpha3` [no scripts was required]

**Comment by l5io** [comment]
🚀 Preview for commit 40716e590ba06805bc6ab71b41684bcd462ac9c5 at: https://66bb81db94302c509944f979--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 2a7fb97ede47405313ab1a4c2a5f18d1179d0abd at: https://66bb8dfc66193e6d29f3f303--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit ca197a61c3f12d11d9e35a36bbb4927d3d4b504c at: https://66bbacd54adcc491d47be005--meshery-docs-preview.netlify.app

**Comment by leecalcote** [comment]
I resolved conflicts with discussion forum post content. These json documents shouldn't be included in this PR, though.

**Comment by l5io** [comment]
🚀 Preview for commit ab676eb7df3346b5a789dd5ef5da1b320876a0f6 at: https://66bd59e422b4b937d7707831--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 870f0c6429b7d036d4c5834fce41b7ea5ed673db at: https://66be07c91822e83228dc0a59--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit a4df6298a28f705a5bd384aec1fc1fd57a46d3d3 at: https://66be3cd7c248980f36946c3f--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit fc5a1f091045001e36d180988ce76ec8a6f88876 at: https://66be63101f58233cf1d6f6b9--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 9c46d9197493b4a4b4e7a8362c9418292c3f9acb at: https://66bee7dc9b90ffb969d8d4de--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 62d6dc3c76d564f3bcb9f98505704147918a80d4 at: https://66bef3bf9b90ffc56ed8d47c--meshery-docs-preview.netlify.app

**Pull request merged**
