### PR TITLE
[UI] Fix Search bar label styling in configurations

### LINKED ISSUE #8419: [UI] Fix Search bar styles in configurations
#### Current Behavior
The search bar has a blue label and unwanted bottom padding.
image

#### Desired Behavior
Change the label active and inactive color according to theme and this reference - https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?type=design&node-id=17282-40292&mode=design&t=CYTzY0i2w3npMrzR-0

#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by mikenrowland**
**Notes for Reviewers**

This PR fixes #8419

Changes:

- Added styling for active state of the search bar label as per [design](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?type=design&node-id=17282-40292&mode=design&t=CYTzY0i2w3npMrzR-0)

Video link: https://app.screencast.com/sm7QykpTIeE8d

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
@Yana-Gupta will you assist with a review?

**Comment by Yana-Gupta** [comment]
> @Yana-Gupta will you assist with a review?

Yes

**Comment by Yana-Gupta** [comment]
@mikenrowland you need to sign off your commits.

**Comment by mikenrowland** [comment]
Oh I did in the initial commit. Let me do it again. Thanks

**Comment by mikenrowland** [comment]
Commit signed @Yana-Gupta. Thanks

**Review by Yana-Gupta — CHANGES_REQUESTED** [review]
Please use the same hex code color user [here](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?type=design&node-id=17362-40540&mode=design&t=MkouQd4692VZrVAt-0) for dark mode

**Comment by mikenrowland** [comment]
> Please use the same hex color code used [here](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?type=design&node-id=17362-40540&mode=design&t=MkouQd4692VZrVAt-0) for dark mode

Done

**Comment by Yana-Gupta** [comment]
Thanks @mikenrowland for working on this issue but as @sudhanshutech has pointed out that the search which is being shown is no longer shown, now a standard toolbar is being used in its place. 

image

So now this pull request is no longer valid. 

Till then you can take some other issues.

**Comment by mikenrowland** [comment]
Oh that's sad, unfortunately the new design was not observed when I cloned the repo or on the meshery playground when I picked up the ticket.

**Pull request closed without merging**
