### PR TITLE
Added Application UI

### LINKED ISSUE #3163: Add applications page on the UI
#### Current Behavior

Meshery server is now about to support CRUD for application.

#### Desired Behavior

Meshery should have a Applications page on the UI which will be used work with applications. 

The UI will look similar to the Patterns UI (/configuration/patterns).

Screenshot from 2021-05-02 10-45-08

Initially it should support CRUD for application files similar to the current implementation of patterns and filters and later deploy and other functionalities will be added.

#### Implementation

Implementation would be similar to the existing patterns page but including the changes mentioned above.

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

### PR DESCRIPTION
**Pull request by Chadha93**
Signed-off-by: Gaurav Chadha <gauravchadha1676@gmail.com>

**Description**
Application UI is added.
Screenshot from 2021-06-10 14-14-19

This PR fixes #3163 

**[Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — APPROVED** [review]
Thank you, @Chadha93. Looks great. 👍 

@ramrodo, the build failure is orthogonal to the changes in this PR. Are you ok with moving forward and investigating the failed (unnecessary) docs builds separately?

**Comment by Chadha93** [comment]
> Thank you, @Chadha93. Looks great. 👍
> 
> @ramrodo, the build failure is orthogonal to the changes in this PR. Are you ok with moving forward and investigating the failed (unnecessary) docs builds separately?

Welcome @leecalcote. Yes, I was also wondering about the docs failure 👀.

**Comment by adithyaakrishna** [comment]
@leecalcote @Chadha93 The errors are due to a mismatched syntax in the main file of the docs, I've opened a PR for the same to fix it 👀

**Review by navendu-pottekkat — APPROVED** [review]
Thank you @Chadha93 🚀

**Comment by Chadha93** [comment]
> Thank you @Chadha93 🚀

Thanks 😊

**Comment by ramrodo** [comment]
> Thank you, @Chadha93. Looks great. +1
> 
> @ramrodo, the build failure is orthogonal to the changes in this PR. Are you ok with moving forward and investigating the failed (unnecessary) docs builds separately?

Yes. Those builds are separated but something is wrong with the Netlify builds. We can move forward if it is urgent. If not, I'll dig in that bug this weekend.

**Comment by navendu-pottekkat** [comment]
@ramrodo Let's go ahead with this PR and you can fix the docs build over the weekend.

**Comment by ramrodo** [comment]
> @ramrodo Let's go ahead with this PR and you can fix the docs build over the weekend.

Sure. Thanks.

**Pull request merged**
