### PR TITLE
Fix the docs to import designs in meshery

### PR DESCRIPTION
**Pull request by 11happy**
**Notes for Reviewers**

This PR aim to provide clearer and more accurate instructions for users.

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 8d9971a36888202ffe0f117f61e9e37663984909 at: https://66119b8f2f17ff1ae1c0184f--meshery-docs-preview.netlify.app

**Comment by vishalvivekm** [comment]
@11happy Let's discuss this on Meshery Dev call, add this as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit) , if you would, please.

**Comment by 11happy** [comment]
Sure @vishalvivekm

**Comment by 11happy** [comment]
Hello @vishalvivekm can you please help me why the PR may be failing & also what if any changes are required.
Thank you

**Review by leecalcote — APPROVED** [review]
Thank you, @11happy 💯

**Pull request merged**
