### PR TITLE
sidebar-menu

### LINKED ISSUE #11460: [UI] Submenu items do not open
### Current Behavior

In the sidebar of the [Meshery Docs](https://docs.meshery.io/), the subitems open only on clicking the toggle(arrow) button

### Expected Behavior

The menu should also open on clicking the menu item

### Screenshots/Logs

Screenshot 2024-07-26 at 4 29 50 PM

### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by vaishnaviadhau**
**Notes for Reviewers**

This PR fixes #11460 

https://github.com/user-attachments/assets/eb31b068-a43f-4c55-8081-49c05fc6030b

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit d72b72c491946acc2770ce04f44dab46b2bbb3ab at: https://66a528a74a43fc50cd0e70bd--meshery-docs-preview.netlify.app

**Comment by leecalcote** [comment]
Thanks, @vaishnaviadhau!

**Comment by leecalcote** [comment]
@hargunkaur286, you might like to review...

**Comment by vishalvivekm** [comment]
@vaishnaviadhau 
Let's discuss this on the website's call today at 5:30 PM IST. Adding this as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit).

**Comment by vaishnaviadhau** [comment]
@vishalvivekm  sir I didnt finf the link pls send me the meeting link

**Review by Ashparshp — APPROVED** [review]
LGTM!

**Pull request merged**
