### PR TITLE
changed the command from layer5io/tap to meshery/tap

### PR DESCRIPTION
**Pull request by manikmmalhotra**
Signed-off-by: manikmmalhotra <manikmalhotra2113@gmail.com>

**Description**
updated the command from layer5io/tap to meshery/tap
This PR fixes None
discussed here: https://github.com/meshery/homebrew-tap/pull/31

**Notes for Reviewers**
Always open for suggestions and improvements. Please point me out if anything should be added/corrected.

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit b1b151f2e631db7ed8b05ca32fcfc4bffc0a300b at: https://62cacc50a341ee39fb0a8b4a--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 639938f25d744018ba32b41363999c4ac40e84ff at: https://62cb260d50e7d172259ecd3b--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 8c797acd48d60f9e468ade334a804e58a897ef96 at: https://62cb3951a341ee02220a8cc2--meshery-docs-preview.netlify.app

**Comment by leecalcote** [comment]
@nishantwrp, a PR for your review.

**Comment by manikmmalhotra** [comment]
@nishantwrp there are some issues in this PR i'll make the changes and re-open this

**Pull request closed without merging**
