### PR TITLE
Fix invalid SVG on dynamic meshmodel kubernetes component

### PR DESCRIPTION
**Pull request by Revolyssup**
**Notes for Reviewers**

This PR fixes #

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — APPROVED** [review]

**Review by leecalcote — APPROVED** [review]

**Comment by Abhishek-kumar09** [comment]
Screenshot 2023-03-15 at 8 22 27 PM

Still normal svgs for some specific components.

**Comment by Abhishek-kumar09** [comment]
in the integration doc, I could see the correct SVG URL placed

**Review by leecalcote — APPROVED** [review]
@Revolyssup still working on this, right?

**Comment by Abhishek-kumar09** [comment]
> Screenshot 2023-03-15 at 8 22 27 PM
> 
> Still normal svgs for some specific components.

Lets catchup in some other PR, @Revolyssup

**Pull request merged**
