### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by arghac14**
Added the 'Contributing' section to the Overview page.

### CODE REVIEW

**Comment by arghac14** [comment]
@leecalcote

**Comment by leecalcote** [comment]
@arghac14 we're good to go after you follow these instructions for updating this PR - https://github.com/layer5io/meshery/pull/182/checks?check_run_id=184048454.

Don't forget to ensure that your commit(s) are signed. There are some tips on ensuring your commits are signed under the July 12th, 2019 section of the community meeting minutes doc - https://docs.google.com/document/d/1c07UO9dS7_tFD-ClCWHIrEzRnzUJoFQ10EzfJTpS7FY/edit#heading=h.nsaspa7c79n7 (these instructions will help on new PRs).

**Comment by leecalcote** [comment]
@arghac14 ping on Slack, if I can help tie off the DCO requirement.

**Comment by leecalcote** [comment]
Hi @arghac14, just a reminder to add a quick sign-off on your commit using the instructions above.

**Pull request merged**
