### PR TITLE
docs: Fix ruby version in contributing-docs page

### LINKED ISSUE #9772: [Docs] Fix ruby version in documentation
### Current State
https://docs.meshery.io/project/contributing/contributing-docs#install-ruby
The ruby version provided while running `rbenv install 2.7.5` in incorrect. The ruby-version provided in the docs repo is 3.2.2 as stated in https://github.com/meshery/meshery/blob/master/docs/.ruby-version 

### Desired State
We need to update the installation docs based on the current version.

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by lakshz**
**Notes for Reviewers**

This PR fixes #9772 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit e653f9c55c2bd5fd13d15f829432d39250c1cb40 at: https://6593f59e23ca8c006bc046d0--meshery-docs-preview.netlify.app

**Comment by saurabh100ni** [comment]
Hi @LakshyaSatpal ,

Thanks for your PR! 🚀 I encourage you to share this in the Meshery Development Meet tomorrow at 8:30 PM IST. Share your screen, and walk us through it. It's cool to take and share feedback. Check the Doc [here](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit) to include this PR.

You're welcome in the meeting today

Cheers, and Happy New Year 🥂,

Subscribe to [community calendar ](https://layer5.io/community/calendar)for more details of meetings at Layer5.

**Comment by LakshyaSatpal** [comment]
Thanks, will be happy to join.

**Review by leecalcote — APPROVED** [review]
Thanks, @LakshyaSatpal

**Pull request merged**
