### PR TITLE
Updated search input 

### LINKED ISSUE #7106: [Docs] Styles not applied to search bar
#### Current State
styles are not applied to search field
Screenshot from 2023-02-17 09-57-19

#### Desired State

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by VIKAS0264**
**Notes for Reviewers**

This PR fixes #7106
before :
Screenshot from 2023-02-17 09-57-19

after :
Screenshot from 2023-02-17 15-13-07

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 5ee5d9501d60b854483e5f05d8a665f857a6de47 at: https://63ef4dc5aa408852451c7226--meshery-docs-preview.netlify.app

**Comment by deepakdinesh1123** [comment]
@VIKAS0264 The search icon that was right next to the search bar is now below the search bar, could you please fix that?

**Review by swagataroy30 — COMMENTED** [review]
I would like to pass some suggestions - maybe some padding and the font size needs to be increased so that the text inside the input filed is quite visible. Thank you!

**Comment by ritiksaxena124** [comment]
These are my suggestions: 
- There may be no need for that search button outside the search bar as we are also including the icon inside the bar or we can remove the icon inside the bar and have a separate button.
- the length of the search is full of the width of the container which can be reduced.
- we can have something like a clear or cross to empty the search bar if someone typed incorrectly.

**Comment by VIKAS0264** [comment]
i have gone through your suggestions @ritiksaxena124 @swagataroy30 @deepakdinesh1123 i will work on it and create a new pr.

**Comment by deepakdinesh1123** [comment]
@VIKAS0264 Don't create a new PR just add a commit to this one

**Comment by l5io** [comment]
🚀 Preview for commit 697e5bb8afbe934429cec91ecca1f47dbbb01d23 at: https://63f3622cc155444a8ae60228--meshery-docs-preview.netlify.app

**Comment by VIKAS0264** [comment]
* ### styles of the search input are changed ###
Screenshot from 2023-02-20 17-35-32

* ### search input from the search page was not fetching results missing form tags were added to fetch results ###

**Comment by l5io** [comment]
🚀 Preview for commit 7e3eea0b6afa4332ebdeb7eb4dcb459d63f6b3bc at: https://63f4494a37dfa102e357f887--meshery-docs-preview.netlify.app

**Comment by deepakdinesh1123** [comment]
@ritiksaxena124 @VIKAS0264 what do you guys think about the idea of populating the search field with the search query? It kinda feels odd to see that disappear every time. And then the showing results line can be moved down.

**Comment by VIKAS0264** [comment]
> @ritiksaxena124 @VIKAS0264 what do you guys think about the idea of populating the search field with the search query? It kinda feels odd to see that disappear every time. And then the showing results line can be moved down.

yeah it can be populated just by removing autcomplete off i can add a new commit and make it populate

**Comment by Chadha93** [comment]
@VIKAS0264  Let's discuss this on the Meshery Dev call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#) if you would. :)

**Comment by leecalcote** [comment]
Lots of activity here. Great.

Good of you to see this one through, @VIKAS0264 👍

**Comment by VIKAS0264** [comment]
> Lots of activity here. Great.
> 
> Good of you to see this one through, @VIKAS0264 👍 

Thank you @leecalcote

**Comment by l5io** [comment]
🚀 Preview for commit 44d30d7c6f4bc60a54f2ddb525a4010dc6543790 at: https://63f8509014c05e4d6c1d7b81--meshery-docs-preview.netlify.app

**Comment by VIKAS0264** [comment]
hey @deepakdinesh1123 @ritiksaxena124 @Chadha93 @leecalcote I've updated the search input according to your suggestions.

### In these new commits
* search input in the main field will be populated with query string
* styles to search input is modified
* search input now fetches results which was not working previously

**Comment by ritiksaxena124** [comment]
Hey @VIKAS0264 slight change, It would be great if you can put some spacing between the search bar and the showing results, the second change is the font style of text inside the search bar doesn't resembles the font style of the page

issue in spacing

**Comment by VIKAS0264** [comment]
Hey @ritiksaxena124 I've added margin checkout the latest preview i will work on Changing the font

**Review by asubedy — CHANGES_REQUESTED** [review]
image
It seems like the color here are changed @VIKAS0264. Please look into this, this change is not wanted.

**Comment by VIKAS0264** [comment]
> image
> It seems like the color here are changed @VIKAS0264. Please look into this, this change is not wanted.

Hey @asubedy thank you for highlighting first of all the main.css link was not linked to head, but styles to this search input were written in main.css i thought of including it's overriding other pages styles also. I guess i need some help moving forward with this issue @deepakdinesh1123 @ritiksaxena124

**Pull request closed without merging**
