### PR TITLE
fixed the repition in table of contents

### LINKED ISSUE #5785: Repetition in table of contents in Docs
#### Current Behavior

In documentation table of content  for some headings are repeating their content

#### Expected Behavior

there shouldn't be repetition in table of content which affect the scroll highlight view too.
#### Screenshots/Logs

Overview
Screenshot from 2022-07-09 16-28-35

Concepts
Screenshot from 2022-07-09 16-29-23

Guides
Screenshot from 2022-07-09 16-30-33

Refrence
Screenshot from 2022-07-09 16-31-06

#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

i'd be happy to solve this bug.

### PR DESCRIPTION
**Pull request by manikmmalhotra**
**Description**
there shouldn't be repetition in table of content which affect the scroll highlight view too.
This PR fixes #5785 

**Notes for Reviewers**
Always open for suggestions and improvements. Please point me out if anything should be added/corrected.

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit b53bf54e278784b3f0031e861a1cab679f141f53 at: https://62cb3ad5fb082604962a88d4--meshery-docs-preview.netlify.app

**Review by warunicorn19 — COMMENTED** [review]
THis PR seems to have changes from a different branch as well.

**Comment by manikmmalhotra** [comment]
@warunicorn19 yeah i messed this commit as prev commits were'nt accepted and as i pushed into different branch the commits came along, any solution to this? the code works fine

**Comment by leecalcote** [comment]
> @warunicorn19 yeah i messed this commit as prev commits were'nt accepted and as i pushed into different branch the commits came along, any solution to this? the code works fine

Yes, you can sync your fork with this upstream repo.

**Pull request closed without merging**
