### PR TITLE
[Docs] Improve dark mode visibility of code snippet and click feedback to copy button.

### LINKED ISSUE #7120: [Docs] Improve dark mode visibility of code snippets and feeback of copy button.
#### Current State
The code snippets in dark mode are on the brighter side and copy button has no feedback for the user to know that they have successfully copied the code.

Screenshot from 2023-02-20 22-24-05

#### Desired State
Improve dark mode visibility, probably make it look the same as in light mode. And add functionality to display a copied message when the user clicks the copy clipboard button.

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by chinu-anand**
**Notes for Reviewers**

This PR fixes #7120 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit b371b1637d6393fd921e11f624cd33a757b1dcdc at: https://63f723758465d74ba6f6a5ca--meshery-docs-preview.netlify.app

**Review by Chadha93 — COMMENTED** [review]
@chinu-anand Good stuff here, will add a couple of more items, shows a tooltip of copy and copied(after clicking copy icon), and for the horizontal scrollbar use the scrollbar style used in the navigator(sidebar) of docs.

**Comment by chinu-anand** [comment]
Sure, will add those.

**Comment by l5io** [comment]
🚀 Preview for commit 1bb6efba052e4f15057bb16efd6b063688e94c30 at: https://63f8a4e96e678211226063c1--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit c3566acc1fe2d626f7e69877a048d5b2ea162cad at: https://63fc3546d685f609f48c34c8--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit fc431f96c785b2b80547fda328386edff57edc88 at: https://63fcadf61d2aae022db3a2c4--meshery-docs-preview.netlify.app

**Comment by chinu-anand** [comment]
@Chadha93 Please review the PR.

**Comment by adithyaakrishna** [comment]
@chinu-anand Could you please update the branch?

**Comment by l5io** [comment]
🚀 Preview for commit 0765ce284dd4bbfd9217800b67a2ed430739e64e at: https://6411b5de2b715605cdcec904--meshery-docs-preview.netlify.app

**Review by adithyaakrishna — APPROVED** [review]

**Comment by adithyaakrishna** [comment]
Verified everything at, https://6411b5de2b715605cdcec904--meshery-docs-preview.netlify.app/project/contributing/contributing-docs and Merged the PR :)

**Pull request merged**
