### PR TITLE
[CI] Relocate workflow config file

### PR DESCRIPTION
**Pull request by leecalcote**
**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by navendu-pottekkat — CHANGES_REQUESTED** [review]
`golangci-lint` expects a file `.golangci.yml` in the root of the repo as mentioned here. If it doesn't find one, it will search till it reaches the root [as mentioned here](https://golangci-lint.run/usage/configuration/).

This PR changes the filename and the path of the file which is not needed. What this means is that `golangci-lint` can't find the configuration file `.golangci.yml` and defaults to its preset configuration which runs tests we haven't previously (see [commented out code in .golangci.yml](https://github.com/meshery/meshery/blob/e2770a703afc5510eb66119d012576ceae8d0ebc/.golangci.yml#L77)). This is what causing the new lint errors in this PR.

I propose to keep the file back in the root of the repo and reinvestigate the tests that are skipped and check if they should be added to the linter and open a PR fixing those lint errors along with it.

**Comment by leecalcote** [comment]
I'm trying to cleanup our root directory. Cleanup is the purpose of this investigation.

**Comment by leecalcote** [comment]
This linger uses the .github/workflows/ directory in its example setup configuration. Does it not support this config file location?

**Comment by navendu-pottekkat** [comment]
@leecalcote The file in `.github/workflows` runs the action. We already have the action configured to run in places like this https://github.com/meshery/meshery/blob/e2770a703afc5510eb66119d012576ceae8d0ebc/.github/workflows/mesheryctl-ci.yml#L21 (mesheryctl and Meshery server CI).

From [their documentation](https://golangci-lint.run/usage/configuration/), it will check for the configuration file in the current working directory. Which in this case would be the root of our repo.

It will also go up the tree till it reaches root to check for the configuration file. This can work in cases like running the lint check when you are in the mesheryctl folder.

You can also see that `golangci-lint` have their configuration file in the root of the repo: https://github.com/golangci/golangci-lint/blob/master/.golangci.yml

**Comment by navendu-pottekkat** [comment]
It was good that we looked into this. I wasn't aware of this configuration. I will close the existing issue and open up a new one so that we can propose changes to the checks being run with the linter.

**Comment by navendu-pottekkat** [comment]
Opened issue to track this: https://github.com/meshery/meshery/issues/5163

**Pull request closed without merging**
