### PR TITLE
[CI] Testing Helm Chart Release workflow

### PR DESCRIPTION
**Pull request by leecalcote**
**Description**

Just a test of the new workflow.

### CODE REVIEW

**Comment by Vi1234sh12** [comment]
hey @leecalcote  I'm Update Path install/kubernetes/helm/meshery then lint-test  Pass but again show new Error  
Copy index.yml  to meshery.io/charts  can you give me correct source path  
Screenshot (684) | Screenshot (683)

**Comment by leecalcote** [comment]
Screen Shot 2021-04-27 at 5 20 27 PM

@Aisuko FYI the filepath referenced needs a tweak.

**Comment by leecalcote** [comment]
@Vi1234sh12 I missed your prior comment. That makes sense. Yes, here is the target: https://github.com/layer5io/meshery.io/tree/master/charts

**Comment by Aisuko** [comment]
> Screen Shot 2021-04-27 at 5 20 27 PM
> 
> @Aisuko FYI the filepath referenced needs a tweak.

I will check this.

**Comment by leecalcote** [comment]
@Vi1234sh12 any progress to report?

**Comment by Vi1234sh12** [comment]
error
Hey @leecalcote @Aisuko  , Actually I'm trouble to solve this , just I need to Source Path

**Comment by Aisuko** [comment]
> error
> Hey @leecalcote @Aisuko , Actually I'm trouble to solve this , just I need to Source Path

Do not worry, I can solve this, if we can trigger GitHub Action at our local that would be more easier to debug, https://github.com/nektos/act/issues/583

**Comment by Vi1234sh12** [comment]
@Aisuko  Thank you

**Comment by leecalcote** [comment]
@Vi1234sh12 @Aisuko any luck on publishing? The action seems to be a bit hard to configure for the remote repo.

**Pull request closed without merging**
