### PR TITLE
fix: undefined error in perf results

### LINKED ISSUE #1980: Performance results details throw up undefined error
**Description**

Performance results details throw up undefined error
**Expected Behavior**

Performance details should load up

[Optional] **Additional Context**

In containerised environment

### PR DESCRIPTION
**Pull request by kushthedude**
Signed-off-by: Kush Trivedi <kushthedude@gmail.com>

**Description**

This PR fixes #1980

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by kushthedude** [comment]
^^ @leecalcote autolabeler is here, did you reinstall it?

**Comment by leecalcote** [comment]
@kushthedude no, I didn't make updates to the GitHub org or the workflows in a number of weeks.

**Review by leecalcote — APPROVED** [review]

**Comment by kushthedude** [comment]
> @kushthedude no, I didn't make updates to the GitHub org or the workflows in a number of weeks.

Let's hope the labeller stays here for good 😄

**Comment by leecalcote** [comment]
So much more efficient when its here. 😄

**Pull request merged**
