### PR TITLE
Added Traefik Mesh Lab to docs

### LINKED ISSUE #4120: [Docs]Add Traefik Mesh lab to docs
#### Current State
The recently made Traefik Mesh lab is not in the Docs.
#### Desired State
Let's add that lab to the docs for Traefik Mesh adapter.
https://docs.meshery.io/service-meshes/adapters/traefik-mesh

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by iambami**
Signed-off-by: Atinuke Bami Kayode <titatinuks@gmail.com>

**Description**
Added Traefik Mesh Lab to Meshery docs 

This PR fixes #4120

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by iambami** [comment]
@warunicorn19 ready for review

**Comment by l5io** [comment]
🚀 Preview for commit 184fb98e03cae27fc56523223477bae870a2fa6f at: https://613afa8e06cbd16a5972bc6d--meshery-docs-preview.netlify.app

**Review by warunicorn19 — APPROVED** [review]
LGTM🎉, Thanks for this @iambami 😄

**Review by leecalcote — APPROVED** [review]
Nice

**Comment by leecalcote** [comment]
Adding the docs label...

**Pull request merged**
