### PR TITLE
Common search view for grid and data-table

### LINKED ISSUE #8059: [UI] Refactor: move search option out of the table
#### Current Behavior

Currently the search is residing in the table. Which should be out of the table. So you can search for both grid and list view.

image

#### Desired Behavior

The options should be a part of table iself 

#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by sudhanshutech**
**Notes for Reviewers**

This PR fixes #8059 
1. Common search component across `applications`, `filters`, `designs` across grid and table view
2. Fix search bug in designs 

https://github.com/meshery/meshery/assets/90546692/ba9eb89b-d763-4949-a2e0-88f712a884e5

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
All feedback incorporated?

**Review by vaibhav135 — APPROVED** [review]
LGTM.

**Comment by sudhanshutech** [comment]
> All feedback incorporated?

yes

**Comment by vaibhav135** [comment]
@sudhanshutech can you please mention this issue on this PR https://github.com/meshery/meshery/issues/8059

**Pull request merged**
