### PR TITLE
[Server] Remove hardcoded `registrant/host`

### PR DESCRIPTION
**Pull request by MUzairS15**
**Notes for Reviewers**

This PR fixes #

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by MUzairS15** [comment]
// @Jougan-0 @leecalcote

**Comment by Jougan-0** [comment]
> // @Jougan-0 @leecalcote

Will update my pr accordingly.

**Review by leecalcote — APPROVED** [review]
Lgtm

**Comment by leecalcote** [comment]
@Jougan-0 good to merge?

**Comment by Jougan-0** [comment]
LGTM

**Pull request merged**
