### PR TITLE
[UI] Migrate Connection Component to use MUI v5 Styling and Sistent Component 

### LINKED ISSUE #12122: [UI] Migrate Connection Component to use MUI v5 Styling and Sistent Component
### Current Behavior
This [Connection](https://github.com/meshery/meshery/blob/268c1667a6ab6a8bbdcbd960df20023d8ecbfb3a/ui/components/connections/index.js#L170) Component uses MUI v4's styling. These need to be updated for improved performance and consistency.

### Desired Behavior
- [ ]  use [Sistent](https://github.com/layer5io/sistent) components for  MUI v4 to MUI v5 migration

Sistent is our design system that uses MUI v5, you can also refer to this [doc](https://docs.meshery.io/project/contributing/contributing-ui-sistent) to understand how to use Sistent.

### Acceptance Tests
The component must be updated without introducing any breaking changes in functionality or theming across all instances where it is used.

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by Divyansh200102**
**Notes for Reviewers**

- This PR fixes #12122

- For ui changes: Please add a screenshot showcasing the UI before/after changes. 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by vishalvivekm** [comment]
@Divyansh200102 Thank you for your contributions! Let's discuss this during Wednesday's Meshery Development call at 9:00 AM CT | 8:30 PM IST. Adding it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit?pli=1#) || [meeting link](https://meet.layer5.io/).

**Comment by SAHU-01** [comment]
Thank you for working on this @Divyansh200102 could you confirm aftter your styling changes, how this look sboth in dark and light theme?

**Comment by Divyansh200102** [comment]
> Thank you for working on this @Divyansh200102 could you confirm after your styling changes, how this looks both in dark and light theme? If there is a discrepancy in the dark-light mode do refer to the palette in sistent and make the necessary changes. And do let me know if you have any other queries.

Sure i'll do that.One thing can you confirm the code changes do they look good to you @SAHU-01 ?

**Comment by Divyansh200102** [comment]
> Thank you for working on this @Divyansh200102 could you confirm after your styling changes, how this looks both in dark and light theme? If there is a discrepancy in the dark-light mode do refer to the palette in sistent and make the necessary changes.
> And do let me know if you have any other queries.

Sure some test cases seems to failing I'll have a look and attach the screenshots

**Pull request closed without merging**
