### PR TITLE
Updated filter view command to accept multi-word filters and filter ID 

### LINKED ISSUE #11316: [mesheryctl] `filter view` command does not support id and multiword name
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

### Current Behavior

When we run `mesheryctl filter view [id]` and provide id then it does not work. It does not support multi-word models.
### Desired Behavior

- [ ] Support ID
- [ ] Support for multiword models

### Screenshots/Logs

```
./mesheryctl filter view Unitled Filter File
Error: accepts at most 1 arg(s), received 3
```
```
./mesheryctl filter view 910ed6f8-8edb-4427-849b-6661c4d56da9
Response Status Code 404, possibly Server error
```
### Environment

- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- 📺 [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- ⌨️ [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- ⌨️ [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by Aviral0702**
**Notes for Reviewers**

This PR fixes #11316 

In this PR I have fixed the filter view command to accept the multi-word filters and filter ID as well. 
Added a new test case for the multi-word case.
Two new golden files for the multi-word filters have been added. One file is added in fixtures and other in Testdata.
All the tests have been passed as shown below: 

image

image

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Jougan-0** [comment]
image
Good work on support for multi-word filter name but still the ID is not supported.

**Comment by vishalvivekm** [comment]
@Aviral0702 
Let's discuss this in Meshery Dev meeting starting 7:30 PM IST Today. Adding this as an agenda item....
Meeting minutes: https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit?pli=1#
Meeting link: https://meet.layer5.io/meshery

**Comment by Jougan-0** [comment]
Filter view by ID will not work so error in cloud. Needs investigation low priority for now.

**Comment by Jougan-0** [comment]
I'll test and approve it today. Thanks @Aviral0702

**Comment by Aviral0702** [comment]
> I'll test and approve it today. Thanks @Aviral0702
@Jougan-0 Thanks!

**Review by alphaX86 — COMMENTED** [review]
Let me test this and come back...

**Comment by leecalcote** [comment]
@MunishMummadi, would you like to offer review?

**Review by Jougan-0 — APPROVED** [review]

**Review by alphaX86 — APPROVED** [review]

**Pull request merged**
