### PR TITLE
Enabled navigation of application grid

### LINKED ISSUE #6609: [UI] Applications: Unable to navigate to pages other than 1 (the first page)
#### Current Behavior
On the Applications page (http://localhost:9081/configuration/applications), pagination appears to be dysfunctional in grid view, but does work in table view.

#### Screenshots/Logs
No console logs on click of a page number.

Sample

https://user-images.githubusercontent.com/7570704/205134326-93874242-a9a8-4a0b-b82d-4b89aa859944.mov

#### Environment

- Browser: Safari
- Host OS: Mac
- Meshery Server Version: v0.6.30

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by hs05june**
Signed-off-by: hs05june <harpreet.singh.cse21@itbhu.ac.in>

**Notes for Reviewers**

This PR fixes #6609 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by Chadha93 — CHANGES_REQUESTED** [review]
:eyes:  These package changes are unwanted. Please revert them.

**Comment by leecalcote** [comment]
Thanks for contributing, @hs05june 👍

**Comment by hs05june** [comment]
@Chadha93 Done

**Comment by Chadha93** [comment]
Thank you @hs05june. Good work. :1st_place_medal:

**Pull request merged**
