### PR TITLE
Config file input box visibility fix

### LINKED ISSUE #3013: [Meshery] Input field for the config file works but looks disabled
#### Description
1.)In the orange box marked in the below screenshot, there is an input whose transparency is just very low. 
2.)The Input in green box marked in the below screenshot, the input is disabled presently.

#### Current Behaviour
1.)That input is just having low transparency and making a gap and making it asymmetrical that is not required.
2.)On hovering, neither the cursor in changed nor there is a change in the input field, so don't give a sense that file is to be uploaded.
#### Desired Behaviour
1.)That input could be removed without any change in functionality.
2.)It could be enabled or on hover the, cursor should become pointer so that the user know that file need to be uploaded here.

#### Screenshots/Logs
Screenshot 2021-05-24 at 10 14 54 PM

####Environment:
- Meshery Version: any
- Kubernetes Version: any
- Host OS: Any
- Browser: Any

### PR DESCRIPTION
**Pull request by Ayush-Khandelwal-007**
This PR fixes #3013

https://user-images.githubusercontent.com/59086855/119398042-9f902c00-bcf4-11eb-8c10-b527af896c1d.mov

- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
@Ayush-Khandelwal-007, you're on a roll. 🙂

**Review by leecalcote — APPROVED** [review]
looking good, @Ayush-Khandelwal-007 👍

**Comment by Ayush-Khandelwal-007** [comment]
Thank you😀

**Comment by adithyaakrishna** [comment]
Nice Work @Ayush-Khandelwal-007  🎉

**Comment by Ayush-Khandelwal-007** [comment]
Thanks @adithyaakrishna

**Pull request merged**
