### PR TITLE
Fix: responsiveness

### PR DESCRIPTION
**Pull request by abhishekmmgn**
**Notes for Reviewers**

This PR fixes #

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by betelgeuse-code — APPROVED** [review]

**Review by Yashsharma1911 — COMMENTED** [review]
@dragon-slayer875 can you check and approve this PR if good to go?

**Comment by dragon-slayer875** [comment]
The tab names should not be clipped. Maybe `width: 'max-content'` can work here? 

Screenshot from 2024-05-10 01-41-09

**Comment by dragon-slayer875** [comment]
The icons in these cards should be centered.

Screenshot from 2024-05-10 01-41-52

**Comment by dragon-slayer875** [comment]
When navigating to the configurations (designs) page in mobile mode, the page loads with these desktop dimensions for a few seconds.

Screenshot from 2024-05-10 01-42-38

**Comment by dragon-slayer875** [comment]
The view icon is out of the bar, and the long names on cards need to be formatted with word breaks and ellipses properties.

Screenshot from 2024-05-10 01-43-18

**Comment by dragon-slayer875** [comment]
The data table's checkboxes persist over other information. 

Screenshot from 2024-05-10 01-43-38

**Comment by dragon-slayer875** [comment]
The registry tab widths and section heights need fixing.

Screenshot from 2024-05-10 01-44-51
Screenshot from 2024-05-10 01-44-48

**Review by dragon-slayer875 — CHANGES_REQUESTED** [review]
The changes have been tested on a 400px x 840px viewport in Chrome browser.
Please see to it that they are addressed

**Comment by sudhanshutech** [comment]
@lakshz are you willing to take over this pr ? If yes just first complete the dashboard part for responsiveness and rest in iterations.

**Comment by sudhanshutech** [comment]
or @dragon-slayer875 if you have nothing in plate you can take over

**Pull request closed without merging**
