### PR TITLE
skip workflow run on forks

### LINKED ISSUE #3429: [CI] Skipping workflow runs on forks
_Originally raised by @samirparhi-dev in https://discuss.layer5.io/t/github-wf-issue-during-pull-request/125_
#### Current Behavior

When a contributor pushes to their fork, many workflows which should ideally run only on https://github.com/meshery/meshery also get triggered. They need some secrets to complete successfully but we don't provide secrets to our forks because it may have bad consequences. Thus the runs end up failing on forks which is annoying.

#### Desired Behavior

Recognize such workflows and add conditions to trigger them only when a commit is created in https://github.com/meshery/meshery.

#### Implementation

Example workflow https://github.com/meshery/meshery/blob/master/.github/workflows/build-and-release-edge.yml
Change the job
```yaml
    name: Docker build and push
    env:
```
to
```yaml
    name: Docker build and push
    if: github.repository == 'meshery/meshery'
    env:
```

### PR DESCRIPTION
**Pull request by iamsdas**
Signed-off-by: Suryashankar Das <suryashankardas.2002@gmail.com>

**Description**

This PR fixes #3429 

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by mgfeller — CHANGES_REQUESTED** [review]
Thanks for this PR, @iamsdas !

In general, tests, validations, static analysis etc should run also in forks, and not be restricted to the upstream repository, in order to detect problems and fail as early as possibly. 

As mentioned, jobs that require secrets only available/useful in upstream repos, deploy artifacts, trigger other jobs (probably) should be excluded by default, whilst all other need to be considered individually. Some secrets are just config values that are also configured in forks (like GO_VERSION). I don't know details of all jobs here, but I guess e.g. `invitations` is also one that is not suitable for running in forks.

**Comment by iamsdas** [comment]
I did not know that `secrets.GO_VERSION` was just a config value which could be configured in the forks too. I was just going through all the files with `secrets.<variable>` in them. So I'll not do anything to those jobs with only `secrets.<language>_version` in them. So am I correct to assume that the other secrets will not be configurable/present in the forks?

**Comment by mgfeller** [comment]
> I did not know that `secrets.GO_VERSION` was just a config value which could be configured in the forks too. I was just going through all the files with `secrets.<variable>` in them. I'll not do anything to those jobs with only `secrets.<language>_version` in them. So am I correct to assume that the other secrets will not be configurable/present in the forks?

Good points - it took me a while to figure that out. When you fork a repo, neither secret definitions (like GO_VERSION) nor their values (like 1.15) are propagated. But you're free to create and set their value. Also user names, passwords, tokens if you have access to the target, and/or the target can be configured to one where you have access. It often make sense not to deploy artifacts from forks, though.

So I think as a rule of thumb jobs that require tokens etc probably in general do not make sense to run in forks.

And tests, static code analysis etc  should run also in forks.

**Comment by iamsdas** [comment]
Now the PR is only skipping jobs when they are using some token like `GLOBAL_TOKEN` or `GH_ACCESS_TOKEN` and is not skipping any tests. This should be ready for review now.

**Review by mgfeller — COMMENTED** [review]
I don't have complete overview, but shouldn't `build-and-release-edge` be executed only in the upstream repo as well?

**Comment by iamsdas** [comment]
Actually this issue is being done by two people as both of us had started working on it. After a discussion on slack it was decided to divide the work. So this PR only partially fixes the issue and the `build-and-release-edge` part should be resolved in the other PR.

**Comment by DelusionalOptimist** [comment]
@mgfeller Thanks for taking a look into this. Here is the other PR: https://github.com/meshery/meshery/pull/3431

**Review by mgfeller — APPROVED** [review]
AFAIKS LGTM :smile:

**Comment by mgfeller** [comment]
@ramrodo would you like to have a look here too?

**Comment by iamsdas** [comment]
> Actually this issue is being done by two people as both of us had started working on it. After a discussion on slack it was decided to divide the work. So this PR only partially fixes the issue and the `build-and-release-edge` part should be resolved in the other PR.

It seems like the other PR got merged with changes to only a single file and i believe two other files/jobs are still left:
* `.github/workflows/slack.yml`
* `.github/workflows/release-drafter.yml`

Should I add the changes for these files in this PR or should I make a separate PR?

**Comment by mgfeller** [comment]
> > Actually this issue is being done by two people as both of us had started working on it. After a discussion on slack it was decided to divide the work. So this PR only partially fixes the issue and the `build-and-release-edge` part should be resolved in the other PR.
> 
> It seems like the other PR got merged with changes to only a single file and i believe two other files/jobs are still left:
> 
>     * `.github/workflows/slack.yml`
> 
>     * `.github/workflows/release-drafter.yml`
> 
> 
> Should I add the changes for these files in this PR or should I make a separate PR?

@iamsdas I think it's ok to add them here, as they address the same issue, and there is one fewer PR to review, but it's up to you two of course.

**Comment by iamsdas** [comment]
Made the changes

**Review by mgfeller — APPROVED** [review]
Regarding the workflows that are excluded from forks, and workflows with tests and static analysis that can (and should imho) run also on forks, this looks good to me. I'm not familiar with all workflows, maybe there are others like `label-commenter` where it does not make sense to run on forks, but maybe some are not triggered there anyway?

**Comment by ramrodo** [comment]
I think we need to build the Preview site also in Forks (those PRs that will be merged to meshery master), don't we?

**Comment by iamsdas** [comment]
I may be wrong, but aren't the PRs considered a part of the main repo and not the fork?

**Comment by ramrodo** [comment]
They are considered a part of the main repo but also, part of the fork. This is useful for us to see the changes in the Netlify site before merging the PR to master. Or let me know if this change you're suggesting considers this case also?

**Comment by iamsdas** [comment]
@ramrodo, The Netlify preview should work when creating **pull requests to the main repo**. The changes I have made should prevent creating a preview for **pull requests to the forked repos** as the forked repos do not the have the required secret tokens and end up failing as said in the original issue.

**Comment by ramrodo** [comment]
Ok, sounds good. Sorry for the misunderstanding. We can merge this and see what happens then and to know if we need to update something. Thanks for the contribution :)

**Review by ramrodo — APPROVED** [review]

**Pull request merged**
