### PR TITLE
[UI] Fix Tab Navigation Issue on Create Modal

### LINKED ISSUE #11302: [UI] Add Tabindex to Create Workspace modal
### Current Behavior

https://github.com/meshery/meshery/assets/7570704/f12851e5-86fc-4568-8e10-2766be0010cf

### Implementation

This behavior may need to be addressed inside of the Sistent component or it may need to be addressed universe inside of the associated RJSF UI schema.

### Acceptance Tests
Users can press their TAB key to move through fields sequentially, rolling over to the start when they reach the bottom.

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by UtkarshAhuja2003**
**Notes for Reviewers**

Fixed tab navigation issue caused by the help icon in CustomBaseInput for Environment and Workspace modals

This PR fixes #11302 

## Testing tab press on create modal

https://github.com/user-attachments/assets/a9967a80-0174-461d-8148-7b30be943820

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by sudhanshutech** [comment]
@Yashsharma1911 is this correct way or is it require any update in rjsf for tab to work?

**Review by Yashsharma1911 — COMMENTED** [review]
Yeah this makes sense to not have tab index focus on tooltip, @UtkarshAhuja2003 can you share video of infoModal too?, you can find it inside configuration>designs and click on "i" button on card, if it also works fine we are good to go

**Comment by UtkarshAhuja2003** [comment]
> @UtkarshAhuja2003 can you share video of infoModal too?


https://github.com/user-attachments/assets/c996b9d3-0a91-487e-833d-434a0e62d666

**Review by Yashsharma1911 — COMMENTED** [review]
Great thanks for sharing screen, can you do same for error icon too? checkout line 95

**Comment by UtkarshAhuja2003** [comment]
> can you do same for error icon too? checkout line 95

Done✨

https://github.com/user-attachments/assets/5289ab42-aa48-469a-a41a-2ef01da2ec4a

**Review by Yashsharma1911 — APPROVED** [review]
Thankyou @UtkarshAhuja2003

**Comment by Yashsharma1911** [comment]
Ohh ho DCO check is failing, @UtkarshAhuja2003 please make sure you have signed your commits, checkout details of DCO test to fix it

**Comment by l5io** [comment]
🚀 Preview for commit 1bc73cb42b80ef220e0c37bea65ff35ad0eeef3f at: https://66b583c24e9146da004eb941--meshery-docs-preview.netlify.app

**Comment by UtkarshAhuja2003** [comment]
> Ohh ho DCO check is failing, @UtkarshAhuja2003 please make sure you have signed your commits, checkout details of DCO test to fix it

I'm really sorry, I accidentally signed off all the commits while rebasing. Could you guide me on how to fix this?

**Comment by l5io** [comment]
🚀 Preview for commit 7bbcacd12a24ccd197559d95405375f3a7300648 at: https://66b62a26a366a40431aad8ef--meshery-docs-preview.netlify.app

**Comment by UtkarshAhuja2003** [comment]
@Yashsharma1911 I have fixed the pull request. Please review it

**Comment by Ashparshp** [comment]
@UtkarshAhuja2003 let's discuss this PR during the Meshery dev meeting call, if you would. Please add it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit?usp=drivesdk).

**Review by jameshorton2337 — APPROVED** [review]
Yay, @UtkarshAhuja2003 💯

**Pull request merged**
