### PR TITLE
fix(UI): table filters not rendering due to custom header

### PR DESCRIPTION
**Pull request by kushthedude**
Signed-off-by: Kush Trivedi <kushthedude@gmail.com>

### CODE REVIEW

**Comment by kushthedude** [comment]
@dhruv0000 This PR mostly reverts the changes made in the Table Tweaks, alas but seems that custom header components are causing issues with the sort filters. So I suggest you re-open the issue concerning the tweaks you had made in the results table.

**Comment by dhruv0000** [comment]
Hmm. The custom headers were used to make the fonts bolder. Let me look into it.

**Comment by kushthedude** [comment]
> Hmm. The custom headers were used to make the fonts bolder. Let me look into it.

If that was all the function the custom renders were to provide, then we are good without them ig.

**Comment by dhruv0000** [comment]
#1694 Should fix the sorting option.

**Comment by kushthedude** [comment]
Duplicate of #1694

**Pull request closed without merging**
