### PR TITLE
add v0.5.0 to mesheryctl roadmap

### PR DESCRIPTION
**Pull request by Micost**
Signed-off-by: Micost <zmicost@gmail.com>

**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by Micost** [comment]
@Aisuko please help to review

**Comment by leecalcote** [comment]
Good work, @Micost 👍

**Review by Aisuko — APPROVED** [review]
LGTM

**Comment by Aisuko** [comment]
@Micost Thanks

**Pull request merged**
