### PR TITLE
add designs containing related models on integration pages

### PR DESCRIPTION
**Pull request by CalebZoe**
**Notes for Reviewers**

This PR fixes #

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by CalebZoe** [comment]
do not merge this pr

**Comment by l5io** [comment]
🚀 Preview for commit 7b840027dd2ec9321412a5f1261965127da066fc at: https://67099cf21469b45f1603c02a--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit b593eea992900af46c863d2172c2d9c94966108a at: https://6709a298953934676431412d--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 8a5b8675fb5e46680f2a36d144d1fa327db9dd17 at: https://6709a5c12ae6256a995c836f--meshery-docs-preview.netlify.app

**Comment by CalebZoe** [comment]
on `/extensibility/integrations/amd-gpu` page
image

clicking on links take to design's location in cloud i.e. for Simple Kubernetes Pod https://meshery.layer5.io/catalog/content/catalog/328ceb3f-970c-4e70-93f9-61e987d7952c

**Comment by l5io** [comment]
🚀 Preview for commit b3bfb86da4f94f6ea5d75a239f3acaace01a8168 at: https://6709a7c1e9aca36846b4a97f--meshery-docs-preview.netlify.app

**Comment by CalebZoe** [comment]
@leecalcote ^^

**Review by leecalcote — APPROVED** [review]
🎈

**Pull request merged**
