### PR TITLE
[Docs]: Reduce font size in Meshery REST API page

### LINKED ISSUE #10900: [Docs] Reduce font size in Meshery REST API page
### Current State
https://docs.meshery.io/reference/rest-apis uses overly large font sizes

Screenshot 2024-05-08 at 12 26 26 PM

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by jasonmokk**
**Notes for Reviewers**

This PR fixes #10900 

Reduced font size for the REST API documentation at https://docs.meshery.io/reference/rest-apis

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit b982b50d00d3a5ad43369b25bfc3a4e79354785f at: https://663d499513e93262337cd406--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit c8128802574dbbab508ac622728bf152ad6d7be4 at: https://663d4c16cb477366da996e19--meshery-docs-preview.netlify.app

**Comment by leecalcote** [comment]
Thank you, @jasonmokk 👍

**Review by leecalcote — CHANGES_REQUESTED** [review]
This is looking good, @jasonmokk.

There's one other aspect to these docs that could make do with a size reduction: tables.

Screenshot 2024-05-10 at 6 41 46 PM


Do you mind bumping this down as well?

**Comment by jasonmokk** [comment]
@leecalcote Sure, I'll push that change as well!

**Comment by l5io** [comment]
🚀 Preview for commit c6140fd7eced2a43dba6965f00528468e552c1be at: https://663ec5ca5206567d6670472b--meshery-docs-preview.netlify.app

**Comment by vishalvivekm** [comment]
Hey @jasonmokk, let's discuss this on today's website meeting today at  7 AM CT. I am adding this as an [agenda item](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.69qskjv558bk). Please Join [https://meet.layer5.io/websites](https://www.google.com/url?q=http://meet.layer5.io/websites&sa=D&source=calendar&usd=2&usg=AOvVaw1CNpNwmYd_rTFcQa_7fBB5) if you are available during the meet.

**Review by leecalcote — APPROVED** [review]
Michael appreciated, @jasonmokk 🤠

**Pull request merged**
