### PR TITLE
Add support for persistence

### PR DESCRIPTION
**Pull request by aabidsofi19**
**Notes for Reviewers**

This PR fixes #

Add client side  persistence support for notifications : 
- Notifications are stored in local-storage 
- notification are uniquely stored for user_id 
- All notifications are stored and the redux_store and localstorage is kept in sink 
- Added a history tab for viewed notification 
- Minor Refactors to the component ( I am only refactoring the parts that i am using or touching to make proper decisions) 

https://github.com/meshery/meshery/assets/65964225/033ea10d-8e34-429b-a98b-5544d08a04a7

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Relevant, but slightly to the side: will you make the "image hub downloaded" notification of "Info" severity (blue)?

**Comment by leecalcote** [comment]
Perhaps, in the tabbed menus, we'll have a count of the number of notifications under that category.

```
All (12)         Error (6)       Warning (3)        Info (3)
```

**Comment by leecalcote** [comment]
@Avi-88 there is standard tabbed menu styling that you are to be adding. This applies to the Notification Center, too. 

@ritiksaxena124 let's update the tabbed menu component in Figma to match.

**Comment by aabidsofi19** [comment]
> Perhaps, in the tabbed menus, we'll have a count of the number of notifications under that category.
> 
> ```
> All (12)         Error (6)       Warning (3)        Info (3)
> ```

image

**Pull request merged**
