### PR TITLE
Updated link for installation of Meshery with Minikube using helm

### LINKED ISSUE #11169: [Docs] Broken link in mesheryctl installation minikube
### Current State

While I was trying to read the installation steps https://docs.meshery.io/installation/kubernetes/minikube#installation-using-helm

I found that the link provided  is not working

image

Clicking result on 404 error

image

### Desired State

The link provided should target the right resource
Current target: https://docs.meshery.io/installation/helm 
Should be: https://docs.meshery.io/installation/kubernetes/helm

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by Aviral0702**
**Notes for Reviewers**

This PR fixes #11169 
### Previous Behavior : Inaccurate link for the installation of meshery with Minikube using helm was provided.
image

### Current Behavior: Updated the correct link for the installation with Minikube using helm.
image
 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit cc270e4c8ebee405f5404eeef816b87d3e3c7fc7 at: https://666c26f9975825bfa2d1884a--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit cc270e4c8ebee405f5404eeef816b87d3e3c7fc7 at: https://666c2d7b19c45a32bc933132--meshery-docs-preview.netlify.app

**Review by leecalcote — APPROVED** [review]
Thank you, @Aviral0702 👍

**Comment by leecalcote** [comment]
Please do sign your commit. Execute these commands to do so: https://github.com/meshery/meshery/pull/11179/checks?check_run_id=26228976306

**Comment by l5io** [comment]
🚀 Preview for commit f055c425abd0aab681cade1260bc249fb7619a4b at: https://666ca0bea29f4ebab67ed752--meshery-docs-preview.netlify.app

**Pull request closed without merging**
