### PR TITLE
Fix 'UI build' PR workflow job - provider-ui npm ERR! code EBADPLATFORM due to how optional dependencies are resolved in npm v6

### LINKED ISSUE #4674: [CI] UI build PR workflow - provider-ui npm ERR! code EBADPLATFORM opt dep @next/swc-darwin-x64@11.1.1
#### Current Behavior
UI Build UI build PR workflow fails due to optional dependency @next/swc-darwin-x64@11.1.1.

I was able to replicate issue locally with node v14.8.1 inside /provider-ui with npm install **(that's the node version we use in Github Actions workflow)**:
image

#### Desired Behavior
We should:
1. Modify [Meshery/.github/workflows/ci.yaml](https://github.com/meshery/meshery/blob/master/.github/workflows/ci.yml) so `build-ui` job uses npm v7.
2. Add [.nvmrc file](https://github.com/nvm-sh/nvm#nvmrc) in both /provider-ui/ & /ui so contributors can use either [Node Version Manager](https://github.com/nvm-sh/nvm#node-version-manager---) in linux/mac os systems or [NVM for Windows](https://github.com/coreybutler/nvm-windows#nvm-for-windows) on Windows systems so single `nvm use` simplifies installing and using correct node version locallly (v14.8.1), see [NVM Intro](https://github.com/nvm-sh/nvm#intro) for details.
3. Document in [Contributor Guide for UI component](https://github.com/meshery/meshery/tree/master/ui#contributor-guide-for-ui-component) which npm version to use (npm v7) as a means of contributors being able to troubleshoot issue locally, if encountered.

#### Implementation
By default node seems to come with npm v6.14.15. ERR’s go away if we make sure to upgrade npm to v7 (npm i -g npm@7 locally or something equivalent in github actions workflow) before `npm i` command:
image

#### Acceptance Tests
UI Build job in PR does not fail due to error mentioned above.

### PR DESCRIPTION
**Pull request by MarioArriaga92**
Signed-off-by: Mario Arriaga <ing.mario.arriaga@gmail.com>

**Description**

This PR fixes #4674
image

**Notes for Reviewers**

By default node seems to come with npm v6.14.15. ERR’s go away if we make sure to upgrade npm to v7 (npm i -g npm@7 locally or something equivalent in github actions workflow) before npm i command:
image

This is scope of contribution:
1. Modify Meshery/.github/workflows/ci.yaml so build-ui job uses npm v7.
2. Add .nvmrc file in both /provider-ui/ & /ui so contributors can use either [Node Version Manager](https://github.com/nvm-sh/nvm#node-version-manager---) in linux/mac os systems or [NVM for Windows](https://github.com/coreybutler/nvm-windows#nvm-for-windows) on Windows systems so single nvm use simplifies installing and using correct node version locally (v14.8.1), see [NVM Intro](https://github.com/nvm-sh/nvm#intro) for details.
3. Document in Contributor Guide for UI component which npm version to use (npm v7) as a means of contributors being able to troubleshoot issue locally, if encountered.
*. Note: applied per-repository configuration for line endings as I noticed certain files show as all diff'd when only changed some lines as per: https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings#per-repository-settings (by adding `.gitattributes` file and commands described in https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings#refreshing-a-repository-after-changing-line-endings)

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit d1d50e3e5cc11275dbff2ba50e322fc18f10dca3 at: https://61a00af86875965db643f4a2--meshery-docs-preview.netlify.app

**Comment by ramrodo** [comment]
Nice! @MarioArriaga92 
Just one thing, it seems there were 83 files that were changed in total. Could you add/include only those that are related to the fix?

**Comment by MarioArriaga92** [comment]
@ramrodo reason for the other 79 files being changed is fix for line endings as per in PR note:

*. Note: **applied per-repository configuration for line endings as I noticed certain files show as all diff'd when only changed some lines as per**: https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings#per-repository-settings (by adding .gitattributes file and commands described in https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings#refreshing-a-repository-after-changing-line-endings)

**Comment by ramrodo** [comment]
I see. I overlooked that note. Thanks for the explanation :)

**Review by ramrodo — APPROVED** [review]

**Comment by leecalcote** [comment]
Uh-oh. I wonder if this issue isn't completely put to bed, yet - https://github.com/meshery/meshery/runs/4342098995?check_suite_focus=true

**Comment by MarioArriaga92** [comment]
@leecalcote interesting, I'll take a look

**Pull request merged**
