### PR TITLE
Upgrade @mui/icons-material from 5.14.19 to 5.15.11

### PR DESCRIPTION
**Pull request by deepak4566**
<h3> This PR to upgrade @mui/icons-material from 5.14.19 to 5.15.11.</h3>

- The recommended version is **12 versions** ahead of your current version.
- The recommended version was released **22 days ago**, on 2024-02-24.

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
@dependabot rebase

**Comment by leecalcote** [comment]
haha! I'm so used to @dependabot updates that in my haste I thought this was one. 😆 

@deepak4566, please note the merge conflict.

**Comment by leecalcote** [comment]
Checking in...

**Comment by deepak4566** [comment]
> haha! I'm so used to @dependabot updates that in my haste I thought this was one. 😆
> 
> @deepak4566, please note the merge conflict.

@dependabot  has been raised pr and merged  the same update just after i raised pr  😆 , 
 https://github.com/meshery/meshery/pull/10660
That's why conflict is there , im closing this PR

**Pull request closed without merging**
