### PR TITLE
[CI] Chore: Update Sistent package to v0.14.93

### LINKED ISSUE #12096: [CI] Dependency: Sistent v0.14.93 - a newer package is available
### Current Behavior
I would like to help update this package to the latest version.

### Desired Behavior
In Meshery UI

### Implementation
I won't change any code other than just the dependency.

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
- Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)
- 🧪 [Meshery Test Plan Spreadsheet](https://docs.google.com/spreadsheets/d/13Ir4gfaKoAX9r8qYjAFFl_U9ntke4X5ndREY1T7bnVs/edit#gid=0)

### PR DESCRIPTION
**Pull request by ritzorama**
**Notes for Reviewers**

[CI] Chore: Update Sistent package to v0.14.93

This PR fixes #12096.

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by ritzorama** [comment]
Ooooh, I don't think the build checks will run without approval.

**Review by ritzorama — COMMENTED** [review]
I think this works, but I'm not sure, because usually the package-lock.json is changed, too.

**Comment by jamieplu** [comment]
I think this works, but I'm not sure, because usually the package-lock.json is changed, too.

**Review by jamieplu — CHANGES_REQUESTED** [review]
Probably need the other json file, too

**Pull request merged**
