### PR TITLE
fixed the command from layer5io/tap to meshery/tap

### PR DESCRIPTION
**Pull request by manikmmalhotra**
Signed-off-by: manikmmalhotra <manikmalhotra2113@gmail.com>

**Description**
updated the command from layer5io/tap to meshery/tap

This PR fixes None

discussed here: https://github.com/meshery/homebrew-tap/pull/31

**Notes for Reviewers**
Always open for suggestions and improvements. Please point me out if anything should be added/corrected.

[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by manikmmalhotra** [comment]
@nishantwrp can you review this PR.

**Comment by l5io** [comment]
🚀 Preview for commit 9bc83709c7f1cb3103d7df7ddad75b06517f27cc at: https://62ceb957acda6911b4b47b8b--meshery-docs-preview.netlify.app

**Review by nishantwrp — APPROVED** [review]
looks good to me!

**Review by leecalcote — APPROVED** [review]
Nice work, @manikmmalhotra. Thanks, @nishantwrp

**Pull request merged**
