### PR TITLE
fixed the link for meshery-architecture svg

### LINKED ISSUE #6115: [Docs] Wrong url for meshery client architecture svg
When clicked on the meshery architecture svg it opens the old svg url (maybe). 

#### Current State

url: https://raw.githubusercontent.com/meshery/meshery/master/assets/img/readme/Meshery-client-architecture.svg

image

#### Desired State

url: https://raw.githubusercontent.com/meshery/meshery/master/docs/assets/img/architecture/Meshery-client-architecture.svg

image

---

### PR DESCRIPTION
**Pull request by vaibhav135**
**Description**

This PR fixes #6115

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — CHANGES_REQUESTED** [review]
@asubedy please ensure that all readme images are stored in the .github folder.

**Comment by vaibhav135** [comment]
@leecalcote should I just change all the README.md images links from docs to .github ones

**Comment by vaibhav135** [comment]
@leecalcote made some changes please check.

**Comment by leecalcote** [comment]
Where is the readme referencing images like that of those in the architecture folder? If it isn't, those should not be included.

 https://github.com/meshery/meshery/pull/6118/files#diff-f9789aac3c201b90407d4617bacea30161450ff57e65cf70ddadde67b7d5c6c2?

**Comment by leecalcote** [comment]
> @leecalcote should I just change all the README.md images links from docs to .github ones

No.

**Comment by vaibhav135** [comment]
@leecalcote sorry for the late reply I've made the necessary changes.

**Comment by leecalcote** [comment]
Oh my goodness. Now, I'm the tardy one. OK, taking a look...

**Review by leecalcote — APPROVED** [review]
LGTM

**Pull request merged**
