### PR TITLE
[Docs Designs] Removed Repeated Phrase #9995 Fixed

### LINKED ISSUE #9995: [Docs Designs] Repeated phrase
### Current State
Link: [Meshery Docs](https://docs.meshery.io/concepts/logical/designs)

Currently the phrase "All the resources and their properties that you want for a single deployment written in..." has been duplicated within the same paragraph.

### Desired State

Remove the repeated phrase so the sentence reads as follows: "A Design describes all the resources and their properties that you want for a single deployment written in YAML based on Meshery’s declarative syntax (see [Meshery Schemas repo](https://docs.meshery.io/concepts/logical/(https://github.com/meshery/schemas)))."

#### Screenshots
bug1

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by ASK-03**
**Notes for Reviewers**
This PR fixes the repeated phrase in the [docs](https://docs.meshery.io/concepts/logical/designs). See issue #9995 for reference images.

This PR fixes #9995 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 4a482ce797f741c87d66936e62f266e334d11003 at: https://65a82af3e1f83e0b39bd40f0--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit f60784e32fbc35747dfc04073f231759a40941d4 at: https://65a82c2e04be730cb2575190--meshery-docs-preview.netlify.app

**Review by sandramsc — APPROVED** [review]
Thank you for your contribution @ASK-03, this LGTM.

**Review by leecalcote — APPROVED** [review]
Yay, @ASK-03! 🎈

**Pull request merged**
