### PR TITLE
add meshery docs release for v0.5.40

### LINKED ISSUE #3739: [Docs] Release Notes for v0.5.40 are missing
#### Current State
Docs are missing this entry.

#### Desired State
Paste the following into a new .md file:

```
## What's New
## 🔤 General
- patch NavigatetoBrowser for missing xdg-open @navendu-pottekkat (#3665)
- added swagger api video link to docs @warunicorn19 (#3663)
- added check for docker or kubernetes platform @nehaLohia27 (#3562)
- Migrated GraphQL resolver logic to models @dhruv0000 (#3652)
- [mesheryctl] Added PreRunE Health Checks for multiple system commands @piyushsingariya (#3649)
- Open API Docs /system endpoint @piyushsingariya (#3641)
- [UI] Bulk selection and delete operation in Filters UI  @Chadha93 (#3650)
- Update Maintainer.md @sayantan1413 (#3648)

## 📖 Documentation

- [Docs] Open API: Provider endpoint @piyushsingariya (#3578)

## 👨🏽‍💻 Contributors

Thank you to our contributors for making this release possible:
@Chadha93, @Nikhil-Ladha, @dhruv0000, @leecalcote, @navendu-pottekkat, @nehaLohia27, @piyushsingariya, @sayantan1413 and @warunicorn19

```

---

#### Contributor Resources

- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/meshery/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
- [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by nehaLohia27**
Signed-off-by: Neha Lohia <nehapithadiya444@gmail.com>

**Description**

This PR fixes #3739 

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Review by sayantan1413 — APPROVED** [review]
LGTM 🎉. Thank you @nehaLohia27 💪.

**Review by warunicorn19 — APPROVED** [review]
LGTM! thanks @nehaLohia27

**Comment by leecalcote** [comment]
Thank you, all.

**Comment by leecalcote** [comment]
@nehaLohia27, @warunicorn19 @sayantan1413 please consider affixing labels to PRs, if you would. These labels provide information to the release notes drafter so that each item in the changelog is categorized under it appropriate section.

Example

Screen Shot 2021-08-11 at 9 00 26 AM

**Pull request merged**
