### PR TITLE
Applying operator for docker on start and stop

### LINKED ISSUE #2861: [mesheryctl] docker platform does not deploy meshery-operator
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior

Running `mesheryctl system start` on the `docker` platform does not deploy the meshery-operator.

#### Desired Behavior

Similar to `platform: kubernetes` the `docker` platform should also call the same function and deploy the operator manifests in `start` and remove the deployments in `stop`.

---

#### Contributor Resources

- [mesheryctl Contributing Guide](https://github.com/layer5io/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)

### PR DESCRIPTION
**Pull request by metonymic-smokey**
Signed-off-by: metonymic-smokey <ahuja.aditi@gmail.com>

**Description**
This applies the operator manifest when the platform is docker, on the commands `system start` and `system stop`.
Refactored code to reuse existing code for applying the operator manifest. 

This PR fixes #2861 

**Screenshots**
1. `system start`
image

2. `system stop`
image

**[Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by metonymic-smokey** [comment]
@navendu-pottekkat I was thinking adding a pre-requisite check for Kubernetes should be done before applying operator manifest. What do you think?

**Comment by navendu-pottekkat** [comment]
We do check for an available cluster right? In the pre-flight checks?

**Comment by metonymic-smokey** [comment]
> We do check for an available cluster right? In the pre-flight checks?

Isn't that only when platform is Kubernetes?

**Comment by piyushsingariya** [comment]
@navendu-pottekkat I get the idea of what's happening here!
now Kubernetes is required in both the cases of the platform so, don't worry I'll push and make changes for PreRunE to be platform docker.

**Review by leecalcote — APPROVED** [review]
You're tearing it up, @metonymic-smokey. Awesome. 😄

**Pull request merged**
