### PR TITLE
Fix contrast issue

### PR DESCRIPTION
**Pull request by ptdatta**
**Notes for Reviewers**

This PR fixes 
1. Disable cursor on disable button.
2. Remove hover effect.
3. Remove hardcoded text.
4. Changed the chevrons.

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by abhijeetgauravm** [comment]
Let's discuss this on Meshery Development Meeting tomorrow at 8:30 PM IST / 9 AM Central time. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#).

**Comment by ptdatta** [comment]
> Let's discuss this on Meshery Development Meeting today at 8:30 PM IST / 9 AM Central time. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#).

Sure

**Review by aabidsofi19 — APPROVED** [review]

**Comment by aabidsofi19** [comment]
@ptdatta  there are stiil some issues pending : 
-  Default height for the registrants is too much ( make it take maxHeight 26rem ) 
-  The onScroll component fetching is not working inside Registrants

**Comment by ptdatta** [comment]
@aabidsofi19 yes I know I have a practical exam today that's why I didn't do anything

**Pull request merged**
