### PR TITLE
[CI] Implement Code Coverage for Cypress tests

### LINKED ISSUE #2251: Implement a minimum Code Coverage Report to meshery project
#### Current Behavior

We need to be able to see a Code Coverage Report and measure how many tests we have and those that are missing. This will allow us 

#### Desired Behavior

Have a Code Coverage Report on every PR and/or in the README.md.
We can start with the simplest implementation that measures the code coverage of unit tests or an only workflow. Then, we can create more issues to improve it.

---
[Optional]

#### Implementation

There are many tools that can be used: codecov or others. Feel free to choose the best.

### PR DESCRIPTION
**Pull request by ramrodo**
**Description**

This PR implement Code Coverage for Cypress tests following the official guide:
https://docs.cypress.io/guides/tooling/code-coverage.html

and using [`codecov-action` Github action](https://github.com/codecov/codecov-action) to upload the report

This PR fixes #2251

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by ramrodo** [comment]
There are two errors at running CI tests:

- 1. Related to the package `babel-plugin-istanbul`:
```
Error: Cannot find module 'babel-plugin-istanbul'
```
See [workflow](https://github.com/layer5io/meshery/pull/2258/checks?check_run_id=1718013660)

- 2. Related to ingesting [Google Tag Manager](https://github.com/utkarsh-pro/meshery/blob/ed3c0d594161c1570fab331b0fc376c3497c73c4/ui/pages/_document.js#L44):

```
  > cov_qkqcmc95l is not defined
```
See [workflow](https://github.com/layer5io/meshery/pull/2258/checks?check_run_id=1718021843)

Working on solving these issues...

**Comment by ramrodo** [comment]
> There are two errors at running CI tests:

This was solved by:
- 1. Moving `@cypress/code-coverage` to production dependencies 
- 2. Not including coverage babel transpile to the Google Tag Manager implementation

Tests [pass now](https://github.com/layer5io/meshery/pull/2258/checks?check_run_id=1718332662). Working on uploading the coverage report...

**Comment by ramrodo** [comment]
> No coverage uploaded for pull request base (master@2353160)

Codecov says that because there is not a previous report on `master` to make a diff. It is ok for now.

**Review by shubhank-saxena — APPROVED** [review]

**Comment by leecalcote** [comment]
Thank goodness for the e2e tests that have been written, which are the only reason for a ~30% coverage. 😅

**Review by Aisuko — APPROVED** [review]
LGTM

**Comment by Aisuko** [comment]
Thank you guys.

**Review by leecalcote — APPROVED** [review]
Pretty neat to see this come through.

**Pull request merged**
