### PR TITLE
Style the version component

### LINKED ISSUE #4921: [Docs][UI] Style the version component.
#### Current State
There is not much style on the version of the new docs dropdown component
Screenshot from 2022-01-11 11-16-51

#### Desired State
Add styles and make it look similar to the other tabs in the navbar, follow the same color scheme

---

#### [Contributor Guides](https://docs.meshery.io/project/contributing) and Resources
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by AbhishekJamhoriya**
Signed-off-by: AbhishekJamhoriya <jamhoriya.1@iitj.ac.in>

**Description**
[Docs][UI] Style the version component
This PR fixes #4921

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 5b823bb4a9547bb937e5bdcb723275decf5b6c9d at: https://6204ca6e1d69817f60d3a8ed--meshery-docs-preview.netlify.app

**Comment by AbhishekJamhoriya** [comment]
Hi, @leecalcote I have resolved the issue. This is what it looks like now.
mes

**Comment by AbhishekJamhoriya** [comment]
Hi, @leecalcote can you please review this PR now.

**Review by asubedy — CHANGES_REQUESTED** [review]
@AbhishekJamhoriya can you remove the outline of the version component selector. Or add some css to design it better. This is because although it is looking good on chrome, when opened in safari it looks bad, here is a screenshot 
image

So in my opinion you can remove the outline of the component, or if we can style it in such a way that it remains same across different browser.

**Comment by AbhishekJamhoriya** [comment]
@asubedy, let me explore and see what best I can do from my side to make it look better in both browsers.

**Comment by asubedy** [comment]
> @asubedy, let me explore and see what best I can do from my side to make it look better in both browsers.

You can check Material UI docs or react boot strap  docs you'll get some ideas

**Comment by warunicorn19** [comment]
Actually we dont use material UI in docs, it has to be done through plain CSS or bootstrap

**Comment by asubedy** [comment]
> Actually we dont use material UI in docs, it has to be done through plain CSS or bootstrap 

Yes I was saying to look into those docs and get inspired on how they have styled their version selector.

**Comment by warunicorn19** [comment]
hey @AbhishekJamhoriya please put your topic down in the minutes if you'd like to discuss this. https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#

**Review by alphaX86 — COMMENTED** [review]
I checked the output, its great but only thing I have for suggestion is that the selector can be made a bit rounder, like.... With rounded edges. IDK if that depends on browser (if you already made it so coz I use Brave). If that's can be done with CSS, IG we're good to go. What's your say @warunicorn19 @asubedy?

**Comment by asubedy** [comment]
> I checked the output, its great but only thing I have for suggestion is that the selector can be made a bit rounder, like.... With rounded edges. IDK if that depends on browser (if you already made it so coz I use Brave). If that's can be done with CSS, IG we're good to go. What's your say @warunicorn19 @asubedy?

Yes having a uniform design across all browser is what we need and yes a selector with round edges will be a good change.

**Comment by l5io** [comment]
🚀 Preview for commit b732a6b4b41666c3dbe51e3e9cc7561e6e587cf8 at: https://620ed2fc2d0e5e6c738ef544--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 27995baaea3184e3aa0806bc68bbd83cd9e893c2 at: https://620ed9c2b5ab2473914c3c41--meshery-docs-preview.netlify.app

**Comment by leecalcote** [comment]
Taken from a late model iPhone. Be contentious of mobile view. 

image

**Comment by leecalcote** [comment]
mobile styling is in need of improvement.

**Comment by AbhishekJamhoriya** [comment]
Sorry, @leecalcote I was busy with some other stuff. I will do this by the end of the day.

**Comment by AbhishekJamhoriya** [comment]
Hi, @leecalcote I checked it multiple times and this is how the website looks on iphone5 and iPhoneSE.
iphone5
iphone SE
currently, I don't find any issue on mobile view. So can you please specify the model of the iPhone so that I can recheck it?

**Comment by leecalcote** [comment]
The bottom of the input/select field is being cutoff.

**Comment by l5io** [comment]
🚀 Preview for commit e20f899f2d03cef3fab4a07bd0d95eeb5e218216 at: https://62168b036f041228a8dcb3e1--meshery-docs-preview.netlify.app

**Comment by AbhishekJamhoriya** [comment]
@leecalcote  please have a look. does it look fine now?

**Comment by leecalcote** [comment]
Hmm... the glass look really doesn't go with the rest of the site...
Screen Shot 2022-03-04 at 5 42 10 PM

**Comment by leecalcote** [comment]
@alphaX86 will you assist in seeing that this is completed?

**Review by leecalcote — APPROVED** [review]

**Pull request merged**
