### PR TITLE
Aijeyomah/feature/list exp relationship

### PR DESCRIPTION
**Pull request by Jougan-0**
**Notes for Reviewers**

This PR fixes #

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — APPROVED** [review]

**Comment by leecalcote** [comment]
@lekaf974 I wonder if we'll need a separate docs PR here...

**Comment by leecalcote** [comment]
@Jougan-0 have you asked the original author to review?

**Comment by Jougan-0** [comment]
Yes, I asked him to do so on slack.

**Comment by lekaf974** [comment]
> @lekaf974 I wonder if we'll need a separate docs PR here...

Yes we can have a separate PR, I'll try to work on it this

**Comment by leecalcote** [comment]
@Jougan-0 @lekaf974, oh, ok. Sounds good. I'll let the two of you carry forward here as you like.

**Comment by MUzairS15** [comment]
// @dusdjhyeon

**Comment by dusdjhyeon** [comment]
> // @dusdjhyeon

I'll create an issue related to this docs and work on it if possible, is that okay?

**Comment by leecalcote** [comment]
> > // @dusdjhyeon
> 
> I'll create an issue related to this docs and work on it if possible, is that okay?

Yes, please.

**Pull request merged**
