### PR TITLE
Improve config_test coverage

### LINKED ISSUE #3988: [mesheryctl] Increase code coverage in `mesheryctl` upto 80%
#### Current Behavior

The current code coverage is less than 30% check here https://app.codecov.io/gh/meshery/meshery

#### Expected Behavior

Increase this code coverage up to 80%, this time!

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by Freedisch**
**Notes for Reviewers**

This PR fixes #3988 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — CHANGES_REQUESTED** [review]
@Freedisch a few golang lint items to attend to here.

**Comment by alphaX86** [comment]
@Freedisch any progress you want to notify here? 👀 Or shall we close this stale PR?

**Comment by Chadha93** [comment]
@Freedisch  Let's discuss this on the Meshery Dev call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#) if you would. :)

**Comment by Freedisch** [comment]
@alphaX86 this can be closed, I re-wrote those tests for another PR following my Latest PR

**Pull request closed without merging**
