### PR TITLE
Feature/node info

### PR DESCRIPTION
**Pull request by girishranganathan**

### CODE REVIEW

**Comment by leecalcote** [comment]
@girishranganathan the docker build failed. Do we have an issue that needs to be addressed prior to merge?

**Comment by girishranganathan** [comment]
> @girishranganathan the docker build failed. Do we have an issue that needs to be addressed prior to merge?

The issue with the docker builds is that we were using a GitHub's own docker action for running all our docker commands in the CI flow. Today the official docker actions repo was either deleted or moved: https://github.com/actions/docker. This is breaking all our builds. I will get this fixed today.

**Comment by girishranganathan** [comment]
@leecalcote builds are back in this branch. Others will have to sync their branch with master to get the builds working. . .

**Comment by leecalcote** [comment]
Wow. This may be the first PR that we've had with passing tests across the board since instituting GitHub Actions. Flying colors for @girishranganathan. :)

**Pull request merged**
