### PR TITLE
Fix webpack HMR websocket connection

### LINKED ISSUE #8497: [UI] Next.js v12 HRM (Webpack Hot Module Replacement) connection uses WebSocket, so ui dev server proxy shouldn't proxy such upgrade events to our server
### Current Behavior

While debugging cypress test failure in #8481, noticed hmr websocket connections weren't being established:
image

According to https://github.com/vercel/next.js/issues/30491 and [next.js v12 upgraded guide / HMR connection now uses a WebSocket](https://nextjs.org/docs/pages/building-your-application/upgrading/version-12#hmr-connection-now-uses-a-websocket), any dev proxy being used should be updated so it properly passes `'/_next/webpack-hmr'` requests to next js app so hot module reloading webpack feature works properly.

### Desired Behavior

`WebSocket connection to 'ws://localhost:3000/_next/webpack-hmr' failed: Invalid frame header` errors shouldn't show up in browser console and modifying Meshery UI code while `npm run dev` script is running should reflect instantly with HMR webpack feature.

### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by MarioArriaga92**
**Notes for Reviewers**

This PR fixes #8497
UI dev server is updated so proxy doesn't proxy `GET :ws://localhost:3000/_next/webpack-hmr` requests to meshery server and allows them to be served properly by next.js

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Still needs some review or you think that this is mergable?

**Comment by leecalcote** [comment]
> Still needs some review or you think that this is mergable?

I will hold off on the current release in case this isn't quite ready, yet, @MarioArriaga92

**Comment by MarioArriaga92** [comment]
> > Still needs some review or you think that this is mergable?
> 
> I will hold off on the current release in case this isn't quite ready, yet, @MarioArriaga92

Hey @leecalcote, this change should be dev-facing only as webpack Hot Module Replacement is only used on dev builds but I just fetched latest upstream/master and merged it onto this branch hoping [Docker build errors](https://github.com/meshery/meshery/actions/runs/5884650823/job/15959751801?pr=8498) go away.. although I just noticed [this error](https://github.com/meshery/meshery/actions/runs/5884650823/job/15959808691?pr=8498) during UI end-to-end tests job, taking a look right now:
```
> meshery-ui@1.0.0 start
> NODE_ENV=production node ui_dev_server.js

http://localhost:3000 timed out on retry 91 of 3, elapsed 90281ms, limit 90000ms
Error: connect ECONNREFUSED 127.0.0.1:3000
```

**Comment by leecalcote** [comment]
Thanks, @MarioArriaga92. Are the bill checks on this PR working as you would hope in terms of using the changes that you have in this PR while running those bill checks? Or do we need to merge to really find out?

**Comment by leecalcote** [comment]
> ...as its fixed by using `ui-server`.
Use of `make` targets... 👏

**Pull request merged**
