### PR TITLE
v0.4, v0.5, v0.6 added to excludes

### PR DESCRIPTION
**Pull request by iArchitSharma**
**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 924ba54be3b4546ea8635476767672a1c7f76d74 at: https://65ae81fa9ea59d111befde7e--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 9cbde9aae9edcceb97dfcf8089dd3b79b89e4bcd at: https://65aea701cc6e492fcb55568c--meshery-docs-preview.netlify.app

**Review by leecalcote — APPROVED** [review]
Should be a big jump in build speed (but, overall still slow ☹️)

**Comment by leecalcote** [comment]
Thanks for taking this suggestion and running with it, @iArchitSharma 👍

**Pull request merged**
