### PR TITLE
[UI] Supports accordion style menu in collapsed menu drawer

### LINKED ISSUE #3825: [UI] Support accordion-style menu when Meshery menu drawer is collapsed.
#### Current Behavior
Meshery menu is perpetually expanded to show all menu items when the drawer is collapsed.

Screen Shot 2021-08-09 at 1 27 19 PM

#### Desired Behavior
Offer the same accordion-style behavior when the menu drawer is collapsed as when the menu drawer is fully open.

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by CipherGirl**
**Description**
Supports accordion style in the Meshery menu when the menu drawer is collapsed..

This PR fixes #3825 

**Notes for Reviewers**
It took me a while to find out the problem for which all the collapsed list items were shown in the collapsed menu drawer. A very small change fixed that. But now I'm having a problem with the expand more icon style. I need suggestions for what should be done.

**Behaviour of this PR:**  

https://user-images.githubusercontent.com/37832457/129479444-f2d044d4-c745-4a3a-8e33-152702fb4cff.mp4

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by CipherGirl** [comment]
@sudo-NithishKarthik @warunicorn19 suggestions please!

**Comment by sudo-NithishKarthik** [comment]
Let's make it such that, the item expands when hovering over it.
What do you guys think ?

**Comment by warunicorn19** [comment]
@sudo-NithishKarthik so you mean like hovering over the icon? If so, then how would it close?🤔

**Comment by sudo-NithishKarthik** [comment]
> @sudo-NithishKarthik so you mean like hovering over the icon? If so, then how would it close?🤔

When the cursor is not inside any of the items of the accordion which is open..
makes sense ?

**Comment by CipherGirl** [comment]
I thought about the hover event too, but then what would be the behaviour in mobile view? 🤔

**Comment by leecalcote** [comment]
@Abhishek-kumar09 will you have a look here?

**Comment by warunicorn19** [comment]
@sudo-NithishKarthik do we maybe want to add the hover feature when the drawer is opened as well, something of this sort.

https://user-images.githubusercontent.com/53532328/129709916-b9f305fd-5168-4f16-bcfd-edc2b4ebca73.mov

**Comment by sudo-NithishKarthik** [comment]
It looks good to me @warunicorn19 , thank you 😄
It would be perfect, if it collapses when the cursor is out of the navbar as well, @CipherGirl , can you implement this ?

**Comment by warunicorn19** [comment]
Yes, i was thinking the same, i just sent this as a demo for @CipherGirl. Also, please feel free to text on slack if you run into any problems.

**Comment by Abhishek-kumar09** [comment]
The hoverEffect is looing cool, when it expands in the collapsed view.
Can we get rid of the small chevron in collapsed menu and instead change the color depicting the item has activated/expanded, since there is very less space to show chevron in collapsed view, so we can omit that?

**Comment by CipherGirl** [comment]
I have made changes here's how it works now:

https://user-images.githubusercontent.com/37832457/129871896-3555436a-f4da-4e8d-8219-97785b17b098.mp4

I didn't collapse the child when another list is hovered because it looks odd when multiple icons are being added and removed. Visually it looks confusing as the names are in the tooltip.

**Review by warunicorn19 — APPROVED** [review]
Wow this looks really cool, thanks @CipherGirl.
@sudo-NithishKarthik anymore changes?

**Comment by sudo-NithishKarthik** [comment]
I feel that, if we are going to use that hover feature, it's better to use it even when it is open, because, it will become a point of confusion for the user

**Comment by sudo-NithishKarthik** [comment]
> I feel that, if we are going to use that hover feature, it's better to use it even when it is open, because, it will become a point of confusion for the user

@CipherGirl , what do you think ?

// @warunicorn19

**Comment by warunicorn19** [comment]
Completely missed this comment. Yes, I think it'll be better if we add the hover feature when it's opened, and we should probably make the dropdown chevron fixed so that it is understandable that it extends. // @sudo-NithishKarthik

**Comment by CipherGirl** [comment]
I also think that will be better to make the UI consistent.. I will make the changes..

**Comment by CipherGirl** [comment]
Does it look okay?
https://user-images.githubusercontent.com/37832457/130425938-9e34cb36-38ce-4aa1-8a73-ce7f1dd7af4c.mp4

**Comment by sudo-NithishKarthik** [comment]
> Does it look okay?
Looks good to me @CipherGirl  😃 .

// @leecalcote  @warunicorn19 @Abhishek-kumar09

**Comment by warunicorn19** [comment]
NIceee, looks awesome @CipherGirl

**Comment by leecalcote** [comment]
It's so nice to see this many screen recordings. Those are most helpful for reviews.

**Comment by leecalcote** [comment]
Watching this last screen recording...unfortunately, no, this isn't quite what we're looking for. It's a bit late for me to type it out. This will make for a good topic of discussion at tomorrow's Meshery Dev meeting (today for @CipherGirl)

**Comment by CipherGirl** [comment]
Update: After discussing in the developer meeting and with Soham. I am proposing the following:

https://user-images.githubusercontent.com/37832457/131225526-675d1fbf-894d-4a5f-bc1c-2c25e0fe4e06.mp4

About some further modifications, a discussion is going on the slack channel..

**Comment by Abhishek-kumar09** [comment]
That looks nice. Can we think of changing the color of parent icons so that it is distinctly visible as parent in the crowd of many childrens.

**Comment by CipherGirl** [comment]
UPDATED PR VIEW:

Expanded:
image

Collapsed:
image

**Comment by leecalcote** [comment]
This is great work. Every piece of feedback incorporated from what I can tell. 👍 

Last item - ideally, the menu category is darker, while the sub menu item is lighter.

**Comment by leecalcote** [comment]
When collapsed the chevron is slightly off-center, sticking to the left:

https://user-images.githubusercontent.com/7570704/132413080-b704aaa8-879b-4ad2-9e9e-ffc80743c326.mov

Zooming in, this you see the effect even more easily:

These recordings are done using Safari. When using Chrome the effect is lessened, although the chevron is still hugging the lefthand side some.

https://user-images.githubusercontent.com/7570704/132413234-16def6fc-bd51-4e64-b9d5-a607fa927a71.mov

**Review by leecalcote — APPROVED** [review]
This is exciting to see move forward. A follow up issue has been opened to track the remainder of the feedback - #4105

**Pull request merged**
