### PR TITLE
[Extension] Add loading component for the load of meshery extension

### PR DESCRIPTION
**Pull request by Abhishek-kumar09**
**Description**
1. Add an animated meshsync logo for the sync progress
2. Provide small message about the things happening
SS: 
[video-webm.zip](https://github.com/meshery/meshery/files/8056292/nn_1.zip)

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by warunicorn19** [comment]
I don't see any animation happening in the meshsync logo, is it spinning @Abhishek-kumar09 ?

**Comment by Abhishek-kumar09** [comment]
Seems like a problem with cluster discovery. The kubernetes context has problems setting up in the github ci?

**Comment by warunicorn19** [comment]
re-running made it worse🥲, Two tests failing now.

**Comment by Abhishek-kumar09** [comment]
It's strange that it doesn't change or touch any previous functionality.

**Comment by warunicorn19** [comment]
@leecalcote since the test failures are being fixed here https://github.com/meshery/meshery/pull/5069, should we move forward with this PR, or are there more updates required design-wise?

**Review by leecalcote — CHANGES_REQUESTED** [review]
Seeing the video now, no, we're not in a good spot design-wise. The request here is to create a custom wait indicator using either the MeshSync logo or the Service Mesh Patterns logo (ultimately, both to create two different spinners) to create an animated spinner. What has happened is a swapping of the Meshery logo with the MeshSync logo, which isn't desired. 

To move this forward, please create one of the following and open an issue for each of the other two:

1) Partners icon only with activity text (e.g. Loading Designer...)
2) MeshSync icon only with activity text (e.g. Loading Visualizer...)
3) Meshery icon only with activity text (e.g. Loading performance results...)

**Comment by Abhishek-kumar09** [comment]
@leecalcote 
The logo has circular animation. Infact you will see animations, when you are using it. Try to checkout the branch, if possible. Probably, we may think to increase the speed if it is not visible. 

I added the Meshery logo (Text) just for a good look, nothing rock solid. If it's not needed, then we can surely remove it. 

It is 2sec animation time, right now. Want it faster?

**Comment by Abhishek-kumar09** [comment]
Let's get created the animation for Patterns and Meshery-logo tooo.

**Review by leecalcote — APPROVED** [review]

**Pull request merged**
