### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by helloausrine**
Hello,

I improved the spelling within the README.

Great project! Keep up the good work!

Peace and Love.

### CODE REVIEW

**Review by Chadha93 — CHANGES_REQUESTED** [review]
good work, @helloausrine, would you please follow https://docs.meshery.io/project/contributing
for signing-off your commits.

**Comment by alphaX86** [comment]
@helloausrine hello there! If you just sign-off your commits then we'll look on your PR so just do that step...

Coz it's a necessary step here while opening a PR and adding changes

**Comment by leecalcote** [comment]
Specific commands to execute in order to sign-off on the commit in this PR - https://github.com/meshery/meshery/pull/4321/checks?check_run_id=3786067810

**Comment by leecalcote** [comment]
hello @helloausrine hello ausrine. Do you need assistance?

**Pull request merged**
