### PR TITLE
[UI] Added theme neutral background for meshery logo

### LINKED ISSUE #7327: [UI]-Meshery not visible under light mode!!
#### Current Behavior
Mehery not visible under light mode only visible under dark mode

#### Desired Behavior
Meshery must be visible under light mode.

@leecalcote @Chadha93 I think rather than taking care of light/dark mode. It was hard-coded
You can assign me to work on this😊

#### Screenshots/Logs

https://user-images.githubusercontent.com/91942072/224090709-840d1e30-bf8c-455e-939a-8104902aada2.mp4

#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by soham4abc**
**Notes for Reviewers**

This PR fixes #7327 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.
 
 Light mode:
image

Dark Mode:
image

### CODE REVIEW

**Review by Yashsharma1911 — CHANGES_REQUESTED** [review]
@soham4abc request here to change the Meshery logo according to dark mode and light mode and not changing its background

**Comment by soham4abc** [comment]
> @soham4abc request here to change the Meshery logo according to dark mode and light mode and not changing its background

Done as per request

Light mode:
image

Dark Mode:
image


Do let me know if anything else is required!

**Review by Yashsharma1911 — APPROVED** [review]
LGTM 👏 @soham4abc

**Review by leecalcote — COMMENTED** [review]
Could we, pretty please, use SVGs only?

**Comment by soham4abc** [comment]
> Could we, pretty please, use SVGs only?

For sure!!

**Review by hirentimbadiya — COMMENTED** [review]
as @leecalcote said @soham4abc used svgs and logo is also neutral regardless the dark/light theme but there is not any link for preview site to see changes but looks good to me , although you can review this PR also @leecalcote @Yashsharma1911

**Comment by soham4abc** [comment]
> @soham4abc Let's discuss this on the Meshery Dev call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#) if you would. :)

For Sure!

**Comment by soham4abc** [comment]
@Chadha93 Please do provide me the edit access for the meeting minutes. I have sent you a edit access over the mail please to have a look at it!

**Review by Chadha93 — APPROVED** [review]
LGTM, thank you @soham4abc

**Pull request merged**
