### PR TITLE
[UI] Fix Runtime Error 

### LINKED ISSUE #4096: [UI] Runtime Error in UI
#### Current Behavior

When the following command is run
```
make run-ui-dev
```

A server runs at `localhost:3000`.

When the following is done:
1. Go to `http://localhost:3000/performance/profiles` and click the icon shown in the image below
fd23aa31-aa29-4a94-b700-26115dc7ada0

The error shown in the image below pos up:
Screenshot from 2021-09-07 11-07-38

2.Visit `http://localhost:3000/smi_results`. The error in the image below will be shown:
Screenshot from 2021-09-07 11-08-00

#### Desired Behavior

Proper error handling should have been done and corresponding flash messages should be displayed.

#### Environment

- Browser: Brave
- Host OS: Zorin 15(Ubuntu-18)
- Meshery Server Version: Not sure
- Meshery Client Version: Not sure
- Platform: Didn't configure

I just ran `make run-ui-dev` as I was working with UI. Didn't run `make run-local`

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by K-Kumar-01**
Signed-off-by: k-kumar-01 <kushalkumargupta4@gmail.com>

**Description**
use optional chaining to avoid UI break.

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by K-Kumar-01** [comment]
@warunicorn19 @sudo-NithishKarthik 
Requesting your review.

Some context regarding the PR.

state won't be undefined but state.get('user') might be so optional chain after this.

No redirection done as of now. Since, it was to be handled in redux as @sudo-NithishKarthik said so currently UI won't break.

Apart from the 2 pages mentioned in the issue, I have also done optional chaining for all pages where there was `state.get('user')` as a precaution.

**Comment by leecalcote** [comment]
@sudo-NithishKarthik will you clarify whether a fix for #4096 is desired?

**Review by sudo-NithishKarthik — APPROVED** [review]
LGTM 🎉 , Thank you @K-Kumar-01

**Comment by sudo-NithishKarthik** [comment]
This does not close the issue #4096 but this will take care of the error handling for now.

**Pull request merged**
