### PR TITLE
Write SVG on UI file system

### PR DESCRIPTION
**Pull request by Revolyssup**
Signed-off-by: Ashish Tiwari <ashishjaitiwari15112000@gmail.com>

**Notes for Reviewers**

This PR adds functionality to write SVGs of MeshModel components on file system for UI.
The approach:
1. Since the svg files are something demanded by the UI for optimised performance, persisting them along with JSON files is redundant. So these SVG files are persisted temporarily when the components are registered under ui/public/static/img and as the server stop they are removed from there. Hence the SVGs under that directory directly correspond to what is inside the registry whereas the JSON files in meshmodel/components are completely static.
2. Moreover keeping the SVGs in meshmode/components is a bad idea because other components may also register along with their SVGs like adapters and those components are not available under meshmodel/components.
3. This change augments the behaviour of registration in a clean way. 
4. The SVGs will be written only for components which have SVGs in their metadata.

The structure of filesystem from where the SVGs are served while Meshery is running will be:
ui/public/static/img/meshmodels/<model-name>/<color/white>/<ComponentName.svg>
Although the exact structure of path will not matter to UI as they will be able to fetch the exact path from ComponentDefinition metadata.

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — CHANGES_REQUESTED** [review]
This is the least desirable approach of those that have been suggested. Please investigate a "virtual directory" capability of nextjs first.

**Comment by leecalcote** [comment]
> 

@acald-creator like Apache's virtual directory concept, do you know if Nextjs has something smilier to alias / symlink a directory?

**Comment by acald-creator** [comment]
> > 
> 
> @acald-creator like Apache's virtual directory concept, do you know if Nextjs has something smilier to alias / symlink a directory?

Researching this.

**Comment by leecalcote** [comment]
I can't say that I agree with point #2.

**Review by leecalcote — APPROVED** [review]

**Comment by Revolyssup** [comment]
@Abhishek-kumar09 Please do your final checks and approve the PR

**Comment by Abhishek-kumar09** [comment]
the vector for the component should be present as well.

**Comment by leecalcote** [comment]
@Revolyssup we seem to be missing this filesystem structure:

<google-sheets-html-origin style="font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0);">

\|- | account |   |   |   |   |   | "account" meaning user domain/company/organization |  
-- | -- | -- | -- | -- | -- | -- | -- | --
  | \|- | relationships |   |   |   |   |   | (account scope)
  |   | -- | relationship.yaml |   |   |   |   |  
  | \|- | policies |   |   |   |   |   | (account scope)
  |   | -- | policy.yaml |   |   |   |   |  
  | \|- | group |   |   |   |   | "group" meaning user group / user org; e.g. developers |  
  |   | \|- | relationships |   |   |   |   | (group scope)
  |   |   | -- | relationship.yaml |   |   |   |  
  |   | \|- | policies |   |   |   |   | (group scope)
  |   |   | -- | policy.yaml |   |   |   |  
  |   |   | \|- | model |   |   |   |  
  |   |   |   | \|- | relationships |   |   | (model scope)
  |   |   |   |   | -- | relationship.yaml |   |  
  |   |   |   | \|- | policies |   |   | (model scope)
  |   |   |   |   | -- | policy.yaml |   |  
  |   |   |   | \|- | components |   |   |  
  |   |   |   |   | -- | component.json |   | e.g. "pod"
  |   |   |   |   | \|- | icons |   |  
  |   |   |   |   |   | \|- | color |  
  |   |   |   |   |   |   | -- abc-color-icon.svg |  
  |   |   |   |   |   | \|- | white |  
  |   |   |   |   |   |   | -- abc-white-icon.svg

</google-sheets-html-origin>

**Comment by leecalcote** [comment]
Minimally, we can start with:

<google-sheets-html-origin style="font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0);">

\|- | model |   |   |  
-- | -- | -- | -- | --
  | \|- | relationships |   |  
  |   | -- | relationship.yaml |  
  | \|- | policies |   |  
  |   | -- | policy.yaml |  
  | \|- | components |   |  
  |   | -- | component.json |  
  |   | \|- | icons |  
  |   |   | \|- | color
  |   |   |   | -- abc-color-icon.svg
  |   |   | \|- | white
  |   |   |   | -- abc-white-icon.svg

</google-sheets-html-origin>

**Review by Abhishek-kumar09 — APPROVED** [review]

**Pull request merged**
