### PR TITLE
cpx adapter two logos are added

### PR DESCRIPTION
**Pull request by gunjanmimo**
Signed-off-by: gunjanmimo <gunjan.mtbpaul@gmail.com>

### CODE REVIEW

**Comment by leecalcote** [comment]
@gunjanmimo thanks for this. Ideally, what we want here is an SVG of the black (or blue) Citrix circle logo. I don't see this available from Citrix's brand resources. I'll reach out to their marketing team for a logo in this format.

**Comment by gunjanmimo** [comment]
sir here is a new logo I have just found it on google

**Comment by gunjanmimo** [comment]
fixes #566

**Comment by leecalcote** [comment]
@gunjanmimo thank you very much for this. Given the recent change to white / off-white logos, let's close this PR in lieu of [citrix-light-gray](https://raw.githubusercontent.com/layer5io/meshery/master/ui/static/img/citrix-light-gray.svg) and [citrix.svg](https://raw.githubusercontent.com/layer5io/meshery/master/ui/static/img/citrix.svg)

**Pull request closed without merging**
