### PR TITLE
Fixed the issue with objects in results page

### LINKED ISSUE #1004: [UI] Performance test results with MeshSync information failing to display
**Description**
Performance test results that include environment information from MeshSync do not display in the /results page.

**Expected Behavior**
The modal window should show the perf test results and environment information gathered by MeshSync (Kubernetes and node information).

**Screenshots**

1. The first results shown here are from a test run when Meshery **is not** connected to Kubernetes (does not run MeshSync). 
1. The second results shown here (in error) are from a test run when Meshery **is** connected to Kubernetes (does run MeshSync).

Untitled

### PR DESCRIPTION
**Pull request by Nikhil-Ladha**
Signed-off-by: Nikhil-Ladha <nikhilladha1999@gmail.com>

This PR fixes #1004 

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Nikhil-Ladha** [comment]
@leecalcote , please do confirm this change in your local once. By running a test and opening the results.

**Comment by leecalcote** [comment]
Will do, @Nikhil-Ladha. Thank you for this fix.

**Comment by leecalcote** [comment]
@nidhinmahesh I still get the following error when trying to retrieve certain results:

```
Warning: Each child in a list should have a unique "key" prop.
```

**Comment by Nikhil-Ladha** [comment]
> @nidhinmahesh I still get the following error when trying to retrieve certain results:
> 
> ```
> Warning: Each child in a list should have a unique "key" prop.
> ```
> 
> Untitled

@leecalcote what configuration are you using for the tests?

**Comment by leecalcote** [comment]
@Nikhil-Ladha good question. These are actually old tests that were previously run. My hunch is that truly locking down a fix on this issue might take us getting on a call to diagnose further. The particulars of this issue has been elusive.

**Comment by Nikhil-Ladha** [comment]
> @Nikhil-Ladha good question. These are actually old tests that were previously run. My hunch is that truly locking down a fix on this issue might take us getting on a call to diagnose further. The particulars of this issue has been elusive.

Hmmm....cool. We will discuss it on a call

**Comment by Nikhil-Ladha** [comment]
Closing this one. Will make a new one.

**Pull request closed without merging**
