### PR TITLE
Update ci.yml

### PR DESCRIPTION
**Pull request by N-Usha**
Hi,
We are the maintainers of the docker-login action that you are consuming in your workflow. And we have moved the code from azure/container-actions/docker-login to a new repo: Azure/docker-login. Kindly request you to start consuming the same. Thanks!

### CODE REVIEW

**Comment by leecalcote** [comment]
Thank you, @N-Usha!

Thank you for triaging this issue, @ashiscs

**Comment by girishranganathan** [comment]
@N-Usha, one request, can you please fix the DCO issue as well for us?

**Comment by leecalcote** [comment]
> @N-Usha, one request, can you please fix the DCO issue as well for us?

@N-Usha, here you are - https://github.com/layer5io/meshery/pull/535/checks?check_run_id=360759690

**Comment by N-Usha** [comment]
Thanks folks for accepting the PR changes. Hope you are having a good experience with using GH Actions. Please feel to revert if you need any further help from the product team. Cheers!

**Comment by leecalcote** [comment]
Thanks much, @N-Usha. 👍

**Comment by leecalcote** [comment]
@n-usha, we're having workflow failures now. The issue seems to be a failed login. In this PR, you have set the `login-server` to: ``` login-server: ${{ secrets.IMAGE_NAME }}```. Is this correct or should it point to the location of our docker registry?

When I set `login-server` to "https://index.docker.io/v1/", the workflow still fails.

**Comment by N-Usha** [comment]
@leecalcote Apologies for reverting late. Thanks for you have now moved to using the new action. login-server should point to docker registry path and takes the default value of 'https://index.docker.io/v1/'. Please let us know if you facing issues when you use the field.

**Pull request merged**
