### PR TITLE
[UI] dashboard bug - check types for meshScan

### LINKED ISSUE #4025: [UI] Dashboard Crashes in v0.5.50
#### Current Behavior
Screen Shot 2021-08-29 at 9 43 17 AM
Screen Shot 2021-08-29 at 9 44 43 AM

#### Environment

- Browser: Safari
- Host OS: Mac
- Meshery Server Version: stable-v0.5.50
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by bariqhibat**
Signed-off-by: Bariq <bariqhibat@gmail.com>

**Description**

This PR fixes #4025

**Notes for Reviewers**
Add type checks for meshScan state

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by bariqhibat** [comment]
Could you check whether this fixes it for you? From my side, it fixes it. @leecalcote

**Comment by warunicorn19** [comment]
@bariqhibat, seems to be fixing the issue, but the backend build is failing. could you re-run the tests?

**Comment by bariqhibat** [comment]
> @bariqhibat, seems to be fixing the issue, but the backend build is failing. could you re-run the tests?
> 

hmm weird, I didn't change anything on the backend. Sure.

**Comment by bariqhibat** [comment]
> @bariqhibat, seems to be fixing the issue, but the backend build is failing. could you re-run the tests?

I check on the test, and it seems like it's something external. It couldn't retrieve the packages from a specific site

**Review by leecalcote — APPROVED** [review]
Let's get this tested in an edge release. Merging....

**Comment by leecalcote** [comment]
The backend failure is a red herring.

**Pull request merged**
