### PR TITLE
[Docs] Updated the width of the single column in responsive view

### LINKED ISSUE #9686: [Docs] single column responsive view is too narrow
### Current State
image

### Desired State

Wider column to increase legibility. 

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by Aniumbott**
**Notes for Reviewers**

This PR fixes #9686

https://github.com/meshery/meshery/assets/76243585/14e01394-6cf2-49c8-b72f-12bf0a05d1ed

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit c2565514d1d60f7039d6e9e3846451cf8b2a41d7 at: https://658bd5213098fa31ced5c010--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit b3e9fcf59b3c70428d6eb0182b931d3a45935d5e at: https://658c32852ac87726a3dd95dd--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 58f3883c56bc4f061525db11f96b6b5b33233ac7 at: https://658c63f5e363920f0a4bccf4--meshery-docs-preview.netlify.app

**Review by leecalcote — APPROVED** [review]
Thank you, @Aniumbott. Looks good. 👍

**Comment by leecalcote** [comment]
The screen recording is helpful. ✅

**Pull request merged**
