### PR TITLE
[UI] Settings: Addressing inconsistencies between sections

### LINKED ISSUE #7700: [UI]: Inconsistent UI in meshery settings
#### Current Behavior
UI is inconsistent across tabs inside settings. 

https://github.com/meshery/meshery/assets/31584129/9afafadb-8d14-439b-b314-323197b428c9

#### Desired Behavior
1. Tabs should be at the root and the rest of the UI should be below them. 
2. Select Component should not push down the UI. 

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by smartdev09**
**Notes for Reviewers**

This PR fixes #7700 

**How should this be tested ?**

https://github.com/meshery/meshery/assets/31584129/641b98e4-ef1b-4ae4-a703-d652fce40d5f

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by 8rxn — CHANGES_REQUESTED** [review]
Hey @leecalcote and @UsmanDev09 ,
I looked at the PR and found that,
There's some styling inconsistencies in the Select options, the following lack any padding:
image
image

While this section is normally styled
image

Other than this, everything seems Good to go.🚀 
The UI is consistent between sections apart from this small thing that I mentioned

**Comment by leecalcote** [comment]
Thank you, @8rxn 👍

**Review by 8rxn — APPROVED** [review]
Seems good to go 🚀

**Comment by leecalcote** [comment]
Thank you, gents. 🚀

**Pull request merged**
