### PR TITLE
Added logic of HTML entity encoding in RJSF Text fields widget

### PR DESCRIPTION
**Pull request by Yashsharma1911**
**Notes for Reviewers**

This PR fixes #

This PR adds the logic of encoding HTML entities inside RJSF field itself. In its default configuration, the RJSF fields do not encode HTML entities. However, adding `x-encode-to-uri` property in schema, will allow HTML entity encoding on a per-field basis. Setting the x-encode-in-uri property to true enables the automatic encoding of HTML entities for the specified field.

Data without property `x-encode-in-uri` 
```
Okay so this is test publish

Added space.  with  : speacial character

fdsa34324 432432614 " "

fsdf
```

Data with `x-encode-in-uri` as true
```
Okay%20so%20this%20is%20test%20publish%0A%0AAdded%20space.%20%20with%20%20%3A%20speacial%20character%0A%0Afdsa34324%20432432614%20%22%20%22%0A%0Afsdf
```

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
The catalogs and the info and publish modals decode this as expected?

**Comment by Yashsharma1911** [comment]
> The catalogs and the info and publish modals decode this as expected?

Yes they does, we need to make small changes in the schema which I already did here https://github.com/meshery/meshkit/pull/436

**Comment by leecalcote** [comment]
> > The catalogs and the info and publish modals decode this as expected?
> 
> Yes they does, we need to make small changes in the schema which I already did here [meshery/meshkit#436](https://github.com/meshery/meshkit/pull/436)

In this response, you've confirmed that both Catalogs are compatible, too.

**Comment by Yashsharma1911** [comment]
> > > The catalogs and the info and publish modals decode this as expected?
> > 
> > 
> > Yes they does, we need to make small changes in the schema which I already did here [meshery/meshkit#436](https://github.com/meshery/meshkit/pull/436)
> 
> In this response, you've confirmed that both Catalogs are compatible, too.

Write now not and this merge will not affect them, until we merge the schema PR, so I'll make changes their too, first pushing changes for meshery.io catalog

**Pull request merged**
