### PR TITLE
move script.sh to docs folder

### LINKED ISSUE #3360: [CI] Relocate netlify script to /docs directory
@nehaLohia27 can we have this file https://github.com/meshery/meshery/blob/master/script.sh moved to the /docs directory? // @Nikhil-Ladha

_Originally posted by @leecalcote in https://github.com/meshery/meshery/discussions/3210#discussioncomment-944626_

### PR DESCRIPTION
**Pull request by nehaLohia27**
Signed-off-by: Neha Lohia <nehapithadiya444@gmail.com>

**Description**

This PR fixes #3360 

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit a51dc6bedc8b832d5a8398e487001380250214f9 at: https://60dee777f36dd5b064fc74ad--meshery-docs-preview.netlify.app

**Review by Nikhil-Ladha — APPROVED** [review]

**Review by includestdlibrary — APPROVED** [review]

**Comment by Nikhil-Ladha** [comment]
@ramrodo I suspect the failing UI-Integration test doesn't have to do anything with the changes in the PR?

**Comment by leecalcote** [comment]
> @ramrodo I suspect the failing UI-end-to-end test doesn't have to do anything with the changes in the PR? And, we are good to merge?

@Nikhil-Ladha, right. I don't see how the two could be related.

**Comment by Nikhil-Ladha** [comment]
Cool, then let's take it in 👍🏼

**Comment by ramrodo** [comment]
> @ramrodo I suspect the failing UI-end-to-end test doesn't have to do anything with the changes in the PR? And, we are good to merge?

Yeah, it could be a Flaky one. Next time or in these cases, we can re-kick manually the workflow to ensure that everything is good.

**Comment by Nikhil-Ladha** [comment]
Actually I did re-kick the workflow and it still failed 😐

**Pull request merged**
