### PR TITLE
[CI] Add GitHub action for labeler 

### LINKED ISSUE #2669: [CI] Label Bot: Design Required label
#### Current Behavior
GitHub issues that receive the "issue/design required" label do not automatically receive helpful, additional context like a comment from a bot with a link to the process document, [Creating a Functional Specification](https://docs.google.com/document/d/1RP3IWLc-MiQS-QYasqCoVuCH7--G87p5ezE5f_nOzB8/edit?usp=sharing). Contributors are not likely to know where to find this document or how to proceed with creating a design specification.

See the comments in this example issue: https://github.com/layer5io/meshery/issues/2668

#### Desired Behavior
Ideally, a bot will fire up and comment a helpful comment that includes a link to the document.

#### Reference:
- [Meshery Build & Release Strategy](https://docs.google.com/document/d/11nAxYtz2SUusCYZ0JeNRrOLIxkgmmbUVWz63MBZV2oE/edit#)

### PR DESCRIPTION
**Pull request by alphaX86**
Signed-off-by: Aadhitya A <aadhitya864@gmail.com>

**Description**
This PR is all about a new action to comment on labels...

This PR fixes #2669

**Notes for Reviewers**
CI Maintainers/Contributors, please test if this action works or not...

**[Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by alphaX86** [comment]
Hmm.... How we can test this?....

**Review by leecalcote — APPROVED** [review]
Thanks, @alphaX86. Let's try this out...

**Comment by leecalcote** [comment]
@alphaX86 I added this same workflow to the meshkit repo as a test. Here's an issue with the `issue/design required` label: https://github.com/layer5io/meshkit/issues/9#issuecomment-831546883. What do you think? Room for improvement in the message?

Given the nature of the design being required prior to PR, I commented out that portion. On second thought, it is probably valid to include it to the extent that someone submits a PR that in fact does need a design spec written.

**Comment by alphaX86** [comment]
@leecalcote I saw the test comment. Seems its great! And yeah, as you said for PR it may need such. Anyway, it works!

**Comment by leecalcote** [comment]
Nice work, @alphaX86. Next, we could use auto-labeling of PRs based on changes to particular filepaths:

- area/docs for changes in /docs/*
- component/mesheryctl for changes in /mesheryctl/*

**Comment by alphaX86** [comment]
Nice! Will make an issue and PR on this soon! 👍

**Pull request merged**
