### PR TITLE
Remove all instances of api.github.com

### LINKED ISSUE #4787: [Docs]Remove all instances of  `api.github.com` in docs
#### Current State
There are a lot of commented out API calls in Meshery docs
#### Desired State
All these API calls should be removed. 
---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by msaini28r**
**Description**

This PR fixes #4787 

I have removed all the instances of api.github.com from the docs.

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit eedbe29287a9909a2efe1a32aba248d5c8345050 at: https://61bf0f003b43f2abcc187c75--meshery-docs-preview.netlify.app

**Comment by msaini0r** [comment]
@warunicorn19  can you please merge this pull request

**Comment by l5io** [comment]
🚀 Preview for commit 14e4fe54588c3f5e0a1903613323596f37a8cc85 at: https://61bf10e5ccad56a12eed5075--meshery-docs-preview.netlify.app

**Comment by leecalcote** [comment]
I might be missing it... how does this not break the docs? @msaini0r  @navendu-pottekkat

**Comment by warunicorn19** [comment]
@leecalcote all these lines of code are commented out, so removing them wont make a difference.

**Comment by leecalcote** [comment]
@msaini0r please undo any immaterial changes to spacing, line returns, code formatting. With about 200 files included in this PR, let's get any extraneous changes undone, so that maintainers might be able to focus on the specific changes at-hand.

**Comment by leecalcote** [comment]
@warunicorn19, we may not desire for any changes in v0.4. Food for thought.

**Comment by leecalcote** [comment]
> @leecalcote all these lines of code are commented out, so removing them wont make a difference.

Oh. This requested change is just for good hygiene, then? 

It's bad hygiene to leave a broken function. Perhaps, remove in its entirety or not at all. 

Unless you're going to regenerate v0.4, I suggest those files go unchanged.

**Comment by warunicorn19** [comment]
Yes, in general we dont want to change anything in 0.4 or 0.5, but in this case it wouldn't make a difference, we can go ahead with this.

**Comment by warunicorn19** [comment]
@msaini0r could you please remove the entire commented out portion and not just the one line.

**Comment by msaini0r** [comment]
Sure, I can remove the whole commented-out portion. @warunicorn19

**Pull request closed without merging**
