### PR TITLE
[Docs] Improving navigability of error code guide

### LINKED ISSUE #3765: [Docs] UX: Create better layout for Error Code Reference
#### Current State
The current tabular layout of the [Meshery Error Code Reference](https://docs.meshery.io/reference/error-codes) can be difficult to read. 

#### Desired State
- Design and present a new layout for improved legibility and navigation.
- Present design, and once approved, implement.

---
#### Contributor Resources
- [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by shubham-tyagi**
**Description**

This PR fixes #3765

**Notes for Reviewers**
Please let me know if I missed something or if anything else is needed to be done.

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 11d08ec26a18286eff0946008890f131145a7de2 at: https://61eea020c2378dcdb815f1d8--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit b28289f7601a84980533ebe11fa742673cfb4af2 at: https://61eea3c54232c0b304455bfe--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 9dc56a9e28472fd9e7b31b4789c9ff28f97fe1be at: https://61eeac3fe87d6b009fed3d63--meshery-docs-preview.netlify.app

**Review by leecalcote — CHANGES_REQUESTED** [review]
Feedback provided on today's websites meeting.

**Comment by warunicorn19** [comment]
@shubham-tyagi any updates you'd like to share on the meshery dev call?

**Comment by shubham-tyagi** [comment]
@warunicorn19 I don't have any updates yet, will surely inform you if I do.

**Comment by leecalcote** [comment]
@shubham-tyagi, you'll want to review @asubedy's recent, relevant work. I'll let him point out his PR.

**Comment by shubham-tyagi** [comment]
sure @leecalcote, would be happy to look at it. @asubedy can you point out the PR lee is talking about.

**Comment by asubedy** [comment]
> sure @leecalcote, would be happy to look at it. @asubedy can you point out the PR lee is talking about.

Hi @shubham-tyagi  sorry missed this, I have not made a PR as there were some missing component, but I will make PR in current state. This will be just a initial phase and not the final implementation

**Comment by asubedy** [comment]
@shubham-tyagi You can see the PR here #5009 . It's not complete but you can get an idea of how the page will be looking.

**Comment by shubham-tyagi** [comment]
Thanks @asubedy, for pointing out the PR.

**Comment by l5io** [comment]
🚀 Preview for commit 517cd4f3fe6696b6e7bf859b8249f1f46910a1ae at: https://61f5af02c78544d5e9b43016--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit c4c5f68bdcc87cc1204002536d8da0a19325ed83 at: https://61f5b507628278b2bb17dc5d--meshery-docs-preview.netlify.app

**Review by asubedy — CHANGES_REQUESTED** [review]
Hi everything looks great. I just want to propose one change, can we have some kind of indication that the said error has remediation or probable cause. A small arrow of sort beside ErrorName would be great.

**Comment by shubham-tyagi** [comment]
yeah @asubedy, I will surely try to add that. And I wanted suggestion regarding one more thing, The severity column should have a colored background like yellow for `alert` and red for `fatal` something like that.

**Comment by asubedy** [comment]
> yeah @asubedy, I will surely try to add that. And I wanted suggestion regarding one more thing, The severity column should have a colored background like yellow for `alert` and red for `fatal` something like that ?

Yes this is a great idea, but I am not sure how will this go with the current design scheme of the page. So maybe you can implement this change and show the result here so that everyone can comment on how it looks, and then we can decide whether to go forward with the change or not.

**Comment by l5io** [comment]
🚀 Preview for commit 575f33112f76ea657b2ac501097bafc2d7fb6d4e at: https://61f786906cf2214de7567514--meshery-docs-preview.netlify.app

**Comment by shubham-tyagi** [comment]
Hey @asubedy, I have tried to give an indication to the user whether the current error have more info or not. Can you see if this looks fine and also can you give your opinion on the background color on on severity.  [link](https://61f786906cf2214de7567514--meshery-docs-preview.netlify.app/reference/error-codes)  ?

**Comment by l5io** [comment]
🚀 Preview for commit eef2df4d876e31f04e3a4b9de274d73a5a193471 at: https://61f789c6bf4b254aab6a9ea3--meshery-docs-preview.netlify.app

**Comment by leecalcote** [comment]
Getting closer. Please hide the Long Description from first view, too, showing it only when the user clicks on a row.

Browsing the latest deploy preview above, when I click on a table row, nothing happens.

**Review by warunicorn19 — CHANGES_REQUESTED** [review]
I think the error codes which dont have a suggested remediation those dont open right? Let's have it in such a way that everything opens on click even if it's blank.

**Comment by warunicorn19** [comment]
I forgot to click comment button on the review that I had left 🤦🏽

**Comment by shubham-tyagi** [comment]
> Getting closer. Please hide the Long Description from first view, too, showing it only when the user clicks on a row.
> 
> Browsing the latest deploy preview above, when I click on a table row, nothing happens.

I will try to hide long description as well. Yeah some errors don't have suggested remediation and probable cause, for those I didn't implemented the row clicking behaviour, will move forward with as suggested by @warunicorn19

**Comment by warunicorn19** [comment]
@shubham-tyagi it would be great if you could demo on the meshery development call.

**Comment by shubham-tyagi** [comment]
sure @warunicorn19.

**Comment by shubham-tyagi** [comment]
> @shubham-tyagi it would be great if you could demo on the meshery development call.

sure @warunicorn19

**Comment by l5io** [comment]
🚀 Preview for commit fc1c563fa3445640b12ee4fa4cc43ca5bfa403f7 at: https://6203cb93da8916535f60eafe--meshery-docs-preview.netlify.app

**Comment by warunicorn19** [comment]
Some error codes seem to have no information at all, @leecalcote should we move forward as is or maybe update the error codes first to at least have some basic information. (Just a severity). CC @Revolyssup

**Comment by shubham-tyagi** [comment]
Hey @warunicorn19, Actually some changes were requested in the previous development meeting. The layout and alignment of extra info was needed to be changed to vertical rather than horizontal, I have not done it yet. But, yeah there are many error codes which does not have any extra info at all.

**Comment by leecalcote** [comment]
@shubham-tyagi, what you have currently is a healthy step forward. Depending upon how far away your final updates are, we can merge this now and allow the remainder to come in through another PR.

**Comment by shubham-tyagi** [comment]
sorry @leecalcote, stuck somewhere, will make modification as suggested in the meeting and make another PR soon.

**Pull request merged**
