### PR TITLE
Made Navigator Icons Consistent

### LINKED ISSUE #6860: [UI] Inconsistency in the sidebar icons
#### Current Behavior

Only few icons in the sidebar  get blue, when user has selected them.
#### Desired Behavior

All icons in the sidebar shold get blue, when user has selected them. So that, user can know where he is.
#### Screenshots/Logs

https://user-images.githubusercontent.com/103871275/211491333-f2b90467-b52c-4c8e-9566-416d2b2acb07.mp4

#### Environment

- Browser: Firefox
- Host OS:Linux 
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by hs05june**
**Notes for Reviewers**

This PR fixes #6860 

https://user-images.githubusercontent.com/103871275/221410081-0d1e29c1-b6c2-4290-8fed-a133d7295fbb.mp4

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by hs05june** [comment]
Hey @leecalcote @Abhishek-kumar09 Please review

**Comment by Abhishek-kumar09** [comment]
Screenshot 2023-03-01 at 5 58 09 PM
Is it just black screen in recording, or something wrong with my system? // @hs05june

**Comment by hs05june** [comment]
@Abhishek-kumar09 Seems like I have uploaded wrong video. My mistake.

**Comment by hs05june** [comment]
https://user-images.githubusercontent.com/103871275/222143658-b86acb0b-efc9-458a-9c9d-b15839523233.mp4
@Abhishek-kumar09

**Pull request merged**
