### PR TITLE
add data-cy for mesh adapter url element

### LINKED ISSUE #7623: [Cypress] Failing Integration Test - settings_spec.
#### Current Behavior
Currently one of the integration specs is failing - https://github.com/meshery/meshery/actions/runs/4822176767/jobs/8589252677?pr=7621#step:5:195
image

#### Expected Behavior
The test should pass

#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by MarioArriaga92**
**Notes for Reviewers**

This PR fixes #7623

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Close, but no cigar?

**Comment by MarioArriaga92** [comment]
> @MarioArriaga92 👀 https://github.com/meshery/meshery/actions/runs/4888341259/jobs/8725962396?pr=7657#step:5:158

Oh sorry @Chadha93 I thought it was evident that failing tests are unrelated to the one I fixed as part of this PR

**Comment by MarioArriaga92** [comment]
Screenshot_2023-05-11-22-12-41-510_com android chrome

**Comment by MarioArriaga92** [comment]
I'll take a look at the failing tests

**Comment by leecalcote** [comment]
> I'll take a look at the failing tests

Thank you

**Comment by MarioArriaga92** [comment]
Merged these changes along with #7658, which is WIP and we're aiming it to include fixes for all tests. So far we've identified several intermittent problems which we're hoping are not an issue any more after adding some cypress configs to give a bit more time to request responses and UI elements to render, when needed.

**Pull request closed without merging**
