### PR TITLE
Mesherycontrollerhelper sync

### PR DESCRIPTION
**Pull request by Azanul**
**Notes for Reviewers**

This PR converts `Mesherycontrollerhelper` methods to synchronous, transferring the sync/async decision to calling function & resolving a data race.

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by Azanul** [comment]
@leecalcote @Revolyssup

**Comment by Chadha93** [comment]
@Azanul  Let's discuss this on the Meshery Dev call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#) if you would. :)

**Comment by Revolyssup** [comment]
@Azanul I can see the race condition. But the only question that I have is, did you see any latency being introduces due to making these synchronous.

**Comment by Azanul** [comment]
> @Azanul I can see the race condition. But the only question that I have is, did you see any latency being introduces due to making these synchronous.

I have only 3 contexts so no. I think it can be an issue over 50 or 100 assuming someone would have that many.

A potential solution would be to add only the required context instead of adding all of them as I don't think there are any other than one request that needs ore than one context.

**Comment by Revolyssup** [comment]
> > @Azanul I can see the race condition. But the only question that I have is, did you see any latency being introduces due to making these synchronous.
> 
> I have only 3 contexts so no. I think it can be an issue over 50 or 100 assuming someone would have that many.
> 
> A potential solution would be to add only the required context instead of adding all of them as I don't think there are any other than one request that needs ore than one context.

Given the fact that these middlewares are on only specific endpoints, I will give it a green flag for now as this wont be a bottleneck. But you can test out with upto 10 contexts (you can add duplicate contexts in your kubeconfig for same kubernetes cluster) and compare latency wrt 1,2,3,4 contexts.  Though it just loops over once so the high level complexity is O(n) but inside each iteration it makes a network request to broker, which might become bottleneck.
I am LGTMing for now and lets get this merged. But you can do some profiling and benchmarking later.

**Comment by Azanul** [comment]
I'll try to keep benchmarking in my mind

**Review by Revolyssup — APPROVED** [review]

**Comment by leecalcote** [comment]
[Token unit test](https://github.com/meshery/meshery/actions/runs/4381995227/jobs/7670605359#step:5:375) for mesheryctl is failing. I'm resending with master to re-run tests. // @alphaX86

**Comment by alphaX86** [comment]
> [Token unit test](https://github.com/meshery/meshery/actions/runs/4381995227/jobs/7670605359#step:5:375) for mesheryctl is failing. I'm resending with master to re-run tests. // @alphaX86

Looking on this

**Comment by Revolyssup** [comment]
@Azanul Will you address and fix the failing lint tests here?

**Comment by Azanul** [comment]
> @Azanul Will you address and fix the failing lint tests here?

On it

**Comment by Chadha93** [comment]
@Azanul Let's discuss this on the Meshery Dev call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#) if you would. :)

**Pull request merged**
