### PR TITLE
created a logger struct

### PR DESCRIPTION
**Pull request by Shreyas220**
Signed-off-by: Shreyas220 <shreyas.ny@gmail.com>

**Description**
Added a logger struct for model package 
for issue #3468

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Shreyas220** [comment]
@sayantan1413

**Comment by sayantan1413** [comment]
Hey @kumarabd @dhruv0000 @DelusionalOptimist @mgfeller we created a logger struct in the `models/adapter.go` file so that we can log the error like `l.log.Error(..)`. Please share your views on this.

**Comment by Shreyas220** [comment]
We do not log in model 
No need for this ; )

**Comment by sayantan1413** [comment]
Oh okay so we can close this pull request @Shreyas220

**Pull request closed without merging**
