### PR TITLE
modified doc for EKS

### PR DESCRIPTION
**Pull request by Althaf66**
**Notes for Reviewers**

This PR is the documentation for the pr #10099 
Modified documentation for EKS

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit f2527e8ee4dbcfbad1a8a79409b318858061eefe at: https://65b6a3d8213eee8edc80d301--meshery-docs-preview.netlify.app

**Comment by saurabh100ni** [comment]
Hi @Althaf66 ,
Thanks for your PR! I encourage you to share this in the Website Meeting today at 6:30 PM IST. Share your screen, and walk us through it. It's cool to take and share feedback. Check the [Doc](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit) here to include this PR.

You're welcome at the meeting

Check to [community calendar](https://layer5.io/community/calendar) for more details of meetings at Layers.

**Review by leecalcote — CHANGES_REQUESTED** [review]
Provide an example, please.

Always capitalize Meshery.

What configuration file and what changes?

**Comment by leecalcote** [comment]
@Althaf66 will you be incorporating this feedback?

**Comment by leecalcote** [comment]
@Althaf66 are you working on this any longer?

**Comment by Althaf66** [comment]
yes,I am writing

**Comment by l5io** [comment]
🚀 Preview for commit e82de977175b27fd3856336f230ef713c785933f at: https://65c673710a51b52bb355295a--meshery-docs-preview.netlify.app

**Comment by leecalcote** [comment]
@Althaf66 we could really use another demo / review on one of the project meetings on this and the adjoining PR.

**Pull request closed without merging**
