### PR TITLE
Add Meshery Release v0.4.2 to Release page

### LINKED ISSUE #1594: [Docs] Add Meshery Release v0.4.2 to Release page
**Desired State:**
The [Releases page](https://meshery.layer5.io/docs/project/releases) needs the v0.4.2 release and release notes added.

The v0.4.2 release notes are here - https://github.com/layer5io/meshery/releases/tag/v0.4.2

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

### PR DESCRIPTION
**Pull request by ghost**
Signed-off-by: Efereyan Karen Simisola <thedevkaren@gmail.com>

**Description**
Added Meshery Release v0.4.2 to Releases Page

This PR fixes #1594

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x ] Yes, I signed my commits.

### CODE REVIEW

**Review by chandrashritii — APPROVED** [review]
Looks good 👍 @KarenEfereyan This can be merged.

**Comment by chandrashritii** [comment]
Adding a screenshot for other Reviewers:
Screenshot_2020-10-02

**Comment by KarenEfereyan** [comment]
Thanks Shriti

**Comment by leecalcote** [comment]
💥

**Comment by KarenEfereyan** [comment]
> 💥

Merci Lee

**Pull request merged**
