### PR TITLE
[meshery]: chore / smps to smp

### LINKED ISSUE #1542: Move from SMPS to SMP
**Current Behavior**
SMPS has been renamed to SMP. (https://github.com/layer5io/service-mesh-performance/pull/119)

**Desired Behavior**
Use of the SMP package and all references to "SMPS" should be updated to "SMP".

References - https://github.com/layer5io/meshery/search?q=smps&unscoped_q=smps

### PR DESCRIPTION
**Pull request by 0xfirefist**
Signed-off-by: Dev Kalra <kalradev@outlook.com>

**Description**
Changed every instance of smps to smp.

Except at one place 
In router.go where the api route is /api/perf/load-test-smps.
We have to change it in the frontend too.

This PR fixes #1542 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — COMMENTED** [review]
@JubayerJoy, you'd be proud.

Thank you, @kalradev.

**Review by leecalcote — APPROVED** [review]

**Comment by KarenEfereyan** [comment]
Waow @kalradev this is great. Can i come learn from you?

**Comment by kalradev** [comment]
> Waow @kalradev this is great. Can i come learn from you?

Sure !!
Ping me on slack. I will be happy to help 😃.

**Review by JubayerJoy — COMMENTED** [review]
@kalradev thank you for making a world where `SMPS` doesn't exist! :rocket:

**Pull request merged**
