### PR TITLE
Issue#3946 Added dropdown in docs sidebar menu

### PR DESCRIPTION
**Pull request by harshit-dxt**
Signed-off-by: Harshit Dixit <harshitdxt3004@gmail.com>

**Description**

This PR fixes # 3946

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 26dbfb117a909fea428374731e77256b18c62b8a at: https://6121d95ff671656d2b9bb2f7--meshery-docs-preview.netlify.app

**Review by warunicorn19 — CHANGES_REQUESTED** [review]
So a couple of things:
1. The icon isn't visible, this is probably because you haven't called the icon in this file.
2. It would be better if on clicking of the chevron just the dropdown extends instead of taking the user to the page itself.

https://user-images.githubusercontent.com/53532328/130343086-0fee4799-10a7-443a-9fbf-b7eac8f6d6c2.mov

**Comment by harshit-dxt** [comment]
To be clear, if on clicking of the chevron, we don't take the user to the page itself, won't it make the pages under them useless?
Clicking on Contributing takes us to /project/contributing which has some content. So, is that desirable?

**Comment by leecalcote** [comment]
Thanks for working on this, @harshit-dxt 👍

**Comment by Meghana-12** [comment]
Thanks for the PR @harshit-dxt ! A small suggestion, how about we add the icon before the title? I think the UI looks more consistent that way.

**Comment by warunicorn19** [comment]
> Thanks for the PR @harshit-dxt ! A small suggestion, how about we add the icon before the title? I think the UI looks more consistent that way.

+1

**Comment by harshit-dxt** [comment]
Hey @Meghana-12,
meshery
I tried adding the icon first before the title. But that seems to hit the alignment since most of the section titles don't have a drop-down. Should I go ahead with this?

**Comment by Meghana-12** [comment]
Oh! I meant something like the image I've shared [here](https://github.com/meshery/meshery/issues/3946#issue-976085720). Could you try to maintain the alignment like that?

**Comment by leecalcote** [comment]
> Oh! I meant something like the image I've shared [here](https://github.com/meshery/meshery/issues/3946#issue-976085720). Could you try to maintain the alignment like that?

@harshit-dxt please do take @Meghana-12's feedback into consideration. Ping when you've refactored and are ready for a review. Thanks!

**Comment by harshit-dxt** [comment]
@leecalcote I will do this today itself. I will take help from a MeshMate in this regard and try to do it by today or tomorrow at max.

**Comment by leecalcote** [comment]
Sounds real good, @harshit-dxt. I'm tagging @iambami here as another helpful contributor, skilled and willing in this regard.

**Comment by iambami** [comment]
> Sounds real good, @harshit-dxt. I'm tagging @iambami here as another helpful contributor, skilled and willing to help in this regard.

Lol, @leecalcote Do you want me to work on this too? @harshit-dxt we could work on it together

**Comment by warunicorn19** [comment]
hey, @iambami @harshit-dxt any updates here? are you guys working on this?🙂

**Comment by iambami** [comment]
I'll start now

**Pull request closed without merging**
