### PR TITLE
Fixed mobile search results 

### LINKED ISSUE #9612: No search result for Mobile devices
No search result for Mobile devices 

### Current Behavior
While searching on docs website on mobile devices no result were found but the same query had results for desktop view

### Screenshots/Logs

4d6dad2e-ddcb-4c79-9ec7-2cd754d51458

### Environment

- *OS* : Mobile(Android)

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by Savio629**
**Notes for Reviewers**
Fixed mobile search results for meshery docs

This PR fixes #9612 

### Screenshot
dba98587-3c22-43c1-9e13-63715d15f969

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 8d6da7fbfb32ab30e30de9ecbb3ab69f87b029e0 at: https://6575c7a01ae76d277799f8ec--meshery-docs-preview.netlify.app

**Comment by iArchitSharma** [comment]
how can removing meta tags solve the problem?

**Comment by iArchitSharma** [comment]
This problem is occurring only on iOS devices, testing on Android will not help

**Comment by Savio629** [comment]
It is occurring on android too..
Check the screenshot assigned in #9612 issue

**Comment by iArchitSharma** [comment]
@Savio629 I tried on Android again and its working as desired, can you test again for your Android

**Comment by Savio629** [comment]
So the issue is the search results are loading for localhost but not for docs.meshery.io website on mobile devices
https://github.com/meshery/meshery/assets/91362589/af2107e2-33cb-4a4c-b4f1-8b29bbd92285

**Comment by vishalvivekm** [comment]
@Savio629 let's discuss this on websites call today, I'll be adding it in agenda item : https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit

**Comment by Savio629** [comment]
Yeah @Lucif3r-in 
Only when you run it locally on your system, it works.

**Comment by l5io** [comment]
🚀 Preview for commit cd500a9e9c67f85bd09cb9066d49a0dd109b330c at: https://6597e932b8805f0fa5475e34--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 6d80b2692ee5a7abe68bae17703d1594d1651dc6 at: https://6597eb1ba163de0065393f44--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 388f2bb362e38a7e1281766dfa49f60ec75aebb5 at: https://6597f845d47ab0006508ebe5--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit cbc3c3e6b423170477dc202462ede5c95f0d062a at: https://6597ff9bd5ec3e0536c89ceb--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit d6fb4e69e557e39ac2554564518275036388ec9e at: https://659802cc6247540604c2e1ce--meshery-docs-preview.netlify.app

**Comment by Savio629** [comment]
@vishalvivekm @iArchitSharma @ashutosh-rath02 Check if it works now...

**Review by iArchitSharma — APPROVED** [review]
LGTM its working on my IOS device

**Pull request merged**
