### PR TITLE
Improve responsiveness on Remote Provider page w/signoff

### LINKED ISSUE #10743: Responsiveness on 'Remote Provider' page.
### Current Behavior
 Remote provider capabilities & extensions were recently included in the Meshery UI's preferences, however, there is a responsiveness issue that needs fixing, primarily in mobile view. See attached image.

### Expected Behavior
 A responsive site that accounts for the mobile view of this new page. Here's a possible solution [in Figma]. (https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?type=design&node-id=29694%3A19485&mode=design&t=mElCikdb8NjkLBBo-1)

### Screenshots/Logs
What we have: 
Remote provider issue

What we could have: 
Figma remote provider page

### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by emmanuelhashy**
**Notes for Reviewers**

This PR fixes #10743

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
@dragon-slayer875 please review

**Review by dragon-slayer875 — CHANGES_REQUESTED** [review]
@emmanuelhashy Thanks for your PR!
I am afraid this PR needs a bit more work still.
Though you have done well to try and make the page responsive, these actions that you have hidden in your PR are crucial to Meshery's UX.
It's necessary that all of them are available to the user in mobile view. 
Current Prod:
image
Your PR:
image

Moreover, the changes in your PR break these tabs.
image

Lastly, I realise that you have tried to replicate the colors and border radius from the images provided in the issue, but we have since then decided to stay on the current styling (color and border radius) scheme for now.
So please revert any such changes that you have made in your PR.

Waiting to see the updates you make. :D

**Comment by emmanuelhashy** [comment]
Thanks for the review @dragon-slayer875. The hidden actions can be found in the side nav on mobile. I made reference to the design while implementing the fix. I'd like to know if the reference design provided in the issue is still valid.

**Comment by dragon-slayer875** [comment]
> the issue is still

Yes but only settings is available there. The other actions such as org switcher and notification drawer and kubernetes context selector are not available in your PR's mobile view.

The reference is 5 months old at this point and was not essentially finalized at the time too.
The UI has seen some changes since then. 
It is still a good reference. But it will still not be called a finalized design that can be implemented as is. 
I would suggest to be ask for opinions on your UI changes publically in the meshery-ui slack channel first before making updates here.

**Comment by emmanuelhashy** [comment]
Alright I will.

> > Thanks for the review @dragon-slayer875. The hidden actions can be found in the side nav on mobile. I made reference to the design while implementing the fix. I'd like to know if the reference design provided in the issue is still valid.
> 
> Yes but only settings is available there. The other actions such as org switcher and notification drawer and kubernetes context selector are not available in your PR's mobile view.
> 
> The reference is 5 months old at this point and was not essentially finalized at the time too. The UI has seen some changes since then. It is still a good reference. But it will still not be called a finalized design that can be implemented as is. I would suggest to be ask for opinions on your UI changes publically in the meshery-ui slack channel first before making updates here.

**Comment by dragon-slayer875** [comment]
Any updates @emmanuelhashy ? :eyes:

**Comment by Ashparshp** [comment]
Thank you @emmanuelhashy, let's discuss this PR during the Meshery dev meeting call, if you would. Adding it as an agenda item to the meeting minutes.

Timing: 7:30 PM IST / 9:00 AM CT (Wednesday)
Meeting minutes: [Google Doc](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit)
Meeting link: [meet.layer5.io/meshery](https://meet.layer5.io/meshery)

**Comment by Ashparshp** [comment]
@emmanuelhashy, joining?

**Comment by emmanuelhashy** [comment]
Hi @Ashparshp, I was admitted to the hospital last week, and my current health condition won't allow me to continue with this anytime soon. My apologies. I'll resume making contributions when I'm discharged and in good health.

**Comment by Ashparshp** [comment]
@emmanuelhashy, thanks for the update—it really helps sending words. Please focus on getting better, and take all the time you need. Wishing you a smooth and speedy recovery!

**Comment by leecalcote** [comment]
@dragon-slayer875 will you take over this PR and complete the work?

@emmanuelhashy, I hope you're back to 100% soon!

**Comment by sudhanshutech** [comment]
@dragon-slayer875 checking in.

**Pull request closed without merging**
