### PR TITLE
refactor(server): remove redundant `len` check

### PR DESCRIPTION
**Pull request by Juneezee**
**Notes for Reviewers**

From the Go specification [^1]:

> "1. For a nil slice, the number of iterations is 0."

`len` returns 0 if the slice is nil [^2]. Therefore, checking `len(v) > 0` or `len(v) != 0` before a loop is unnecessary.

[^1]: https://go.dev/ref/spec#For_range
[^2]: https://pkg.go.dev/builtin#len

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by Juneezee — COMMENTED** [review]
Tip: Hide the whitespace to make the diff easier to read

image

image

**Comment by saurabh100ni** [comment]
Let's discuss this on the Meshery dev call tomorrow,
Please add this as your agenda item in Docs: https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit

**Comment by Juneezee** [comment]
> Let's discuss this on the Meshery dev call tomorrow, Please add this as your agenda item in Docs: https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit

Hi @saurabh100ni. Sorry but I am an external contributor, do I also need to attend the meeting?

**Comment by saurabh100ni** [comment]
Yes! @Juneezee and it's not only to present your agenda but to connect with other contributors too, so that we can share feedbacks and ideas.
See you in the meet 😉

**Review by Philip-21 — APPROVED** [review]
@leecalcote LGTM, since the Templating, comps and Panel structs are an empty slice, we don't need to check its length explicitly,  these structs just defines the slice of the objects but not the items for each object to loop through. 
@Juneezee nice work the changes you made here,   makes the code more concise and follows Go's idiomatic style.

**Review by leecalcote — APPROVED** [review]
Thanks, @Juneezee and @Philip-21 👍

**Pull request merged**
