### PR TITLE
[mesheryctl] Enhance User Experience of `model export` Command

### PR DESCRIPTION
**Pull request by humblenginr**
**Notes for Reviewers**

Changes made in this PR:
1. `oci` is now listed as a supported output-type, and is the default export type. 
2. `oci` exported images are compressed as tar files by default
3. A message confirming that the model was exported and its location is being displayed to the user. 
4. Change the `include-components` flag to `discard-components` (same for relationships). Components and relationships are included in the model by default. 
5. Update docs 

Screenshot 2024-08-06 at 2 10 00 PM

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 714a5d669c8298996822e2a5f66e7e4cb48c761b at: https://66b1e629fadd32b409571960--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit e5ea99e6512ca14154cc5db76872c6f70d3f1495 at: https://66b229ae1e57631ee9ff7e84--meshery-docs-preview.netlify.app

**Comment by leecalcote** [comment]
@humblenginr, thank you. What's the use case for the `discard-components` and `discard-relationships` flag? @Jougan-0 @MUzairS15

**Comment by humblenginr** [comment]
I actually am not sure, but I included thinking this is trivial and safe to include it. Maybe the user just wants to export the metadata of the model because he wants to re-import with different set of relationships and components? Just thinking...

**Comment by leecalcote** [comment]
> I actually am not sure, but I included thinking this is trivial and safe to include. Maybe the user just wants to export the metadata of the model because he wants to re-import with different set of relationships and components? Just thinking...

It's nice to have options. It also means more to maintain.

**Pull request merged**
