### PR TITLE
Fixed clickable area issue in header settings button.

### LINKED ISSUE #7132: [UI] Notification Center button only actives on click of icon, not on click of button
#### Current Behavior
Please see the screen recording for a demonstration of the behavior.

#### Desired Behavior
The entire button should be clickable and activate the notification center sidebar.

#### Screenshots/Logs

https://user-images.githubusercontent.com/7570704/220229090-50487b2a-2bcd-4425-bedc-0667e87ebe91.mov

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by sidtohan**
fixed the responsiveness issue in settings button, now the full button is clickable not just the icon.

**Notes for Reviewers**

This PR fixes #7132.
The notification button seems to be working as expected, but I ended up finding the issue of settings button while working on this. I think it can be fixed under this only.

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by sidtohan** [comment]
@leecalcote do have a look at this whenever possible. Thanks

**Review by leecalcote — CHANGES_REQUESTED** [review]
Thank you, @sidtohan. 

Will please remove the changes to package-lock.json and package.json?

**Comment by sidtohan** [comment]
@leecalcote I have performed the changes, can you please have a look? 
Thanks.

**Comment by leecalcote** [comment]
@sidtohan much better. 

@Revolyssup also reported the original issue of the button (not the icon) click not working to open the Notification Center sidebar. I believe he was using Chrome, while I'm using Safari. Will you confirm that you have fixed the original issue?

**Comment by sidtohan** [comment]
I tried on brave(chromium based) and firefox. It worked on both. I'll try on chrome just in case and get back to you.

**Comment by sidtohan** [comment]
@leecalcote is it alright now? if there are any issues please let me know so that I can fix them.
Thanks.

**Review by leecalcote — CHANGES_REQUESTED** [review]
I just built your changes and tested again. It's a no-go. Here's a recording from Chrome:


https://user-images.githubusercontent.com/7570704/221324240-8a36e7f6-d8fb-4d98-8ba4-95e214ac1277.mov

**Comment by sidtohan** [comment]
@leecalcote I see. I tried it on my system on both chromium and chrome and found it be working. Here's a recording attached.

Kazam_screencast_00001

Is there any way I can figure out how to identify the root cause of this. Any help would be appreciated.
Thanks.

**Comment by leecalcote** [comment]
Oh, no. 😆 it’s no wonder that we’re having trouble. Our systems are behaving two different ways. “System” being likely the operative word in this case. I suspect it this boils down to a difference in operating system behavior. I’m on macOS. Perhaps, we might find another contributor with macOS to help take a look.

**Comment by sidtohan** [comment]
> Oh, no. laughing it’s no wonder that we’re having trouble. Our systems are behaving two different ways. “System” being likely the operative word in this case. I suspect it this boils down to a difference in operating system behavior. I’m on macOS. Perhaps, we might find another contributor with macOS to help take a look.

Oh that makes sense. The people on macOS may be able to help in this issue. I'll try asking in slack channels for the same.
Thanks a ton for your help and guidance.

**Comment by leecalcote** [comment]
Great suggestion. If you come to mind: @asubedy, @theBeginner86, @Abhishek-kumar09

**Comment by leecalcote** [comment]
@sidtohan you might try bringing this up in the Meshery Development Meeting on Wednesdays and see if anyone with macOS might collaborate.

**Comment by asubedy** [comment]
@sidtohan, this should fix the issue. A final check would be good @leecalcote

**Comment by sidtohan** [comment]
Oh that's awesome @asubedy. Hope it's not too much to ask but how does this fix the issue though? I mean, do we need to we have that blank element as parent for the notification element? I want to understand for future reference.
Thanks a lot.

**Comment by leecalcote** [comment]
My test failed, but let’s try it out.

**Comment by leecalcote** [comment]
@asubedy has probably fixed it and I probably have a cache issue.

**Pull request merged**
