### PR TITLE
Doc fix for Providers

### PR DESCRIPTION
**Pull request by MUzairS15**
Signed-off-by: MUzairS15 <muzair.shaikh810@gmail.com>

**Description**
Doc fix for Providers
**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 04ce141203d778f9f63870ac3146fe3fcb60b130 at: https://61d9d308d94b179d59c2f8bc--meshery-docs-preview.netlify.app

**Comment by MUzairS15** [comment]
image
Renders correctly on my side.

**Review by warunicorn19 — CHANGES_REQUESTED** [review]
It still doesn't look too different from what we already have, ideally,  we should have `Name`, `Type`, `Description` in bold and in 3 different lines. 

Screenshot 2022-01-08 at 1 16 03 PM

**Comment by warunicorn19** [comment]
Also the term `<your-name-here>` should also get printed.

**Comment by MUzairS15** [comment]
https://github.com/meshery/meshery/pull/4908#issuecomment-1008088207
I am getting this on my side.

**Comment by l5io** [comment]
🚀 Preview for commit 52d51690496e0c37e9d2a376f7ad2cb8053f69f2 at: https://61da437f45fa191aa9467b64--meshery-docs-preview.netlify.app

**Review by warunicorn19 — APPROVED** [review]
Looking good, Thank you @MUzairS15

**Pull request merged**
