### PR TITLE
Database summary - Add table size/record count to System Reset screen

### LINKED ISSUE #6333: [Database] Add table size/record count to System Reset screen
#### Description
Users who are considering a system reset, which is an archival of the current Meshery Database and a reinitialization of an empty Meshery Database, would benefit from a summary of the current table sizes of their existing database.

This information will also help as people are trying to troubleshoot whether or not MeshSync and GraphQL subscriptions are all working or not. 

#### Implementation
1. Meshery Server REST API enhancement to /api/system/database: GET returns summary: list of table names and number of records for each table.

#### Acceptance Tests
1. Meshery UI displays a summary of the current database with a list of table names and number of records per table.
1. [Meshery API Endpoints spreadsheet](https://docs.google.com/spreadsheets/d/1ABJCbfQRi0uN_YoP2kmHZ-lTI4S4QuvRk1_unomKNRE/edit#gid=1241442399) is up-to-date.
1. Meshery Docs has updated REST API details for /system/database.

#### Current screen
Screen Shot 2022-10-05 at 2 43 35 PM

#### Proposed screen
Environment Settings

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by Meyazhagan**
**Notes for Reviewers**

This PR fixes #6333 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
@UsmanDev09 what feedback do you have here?

**Comment by leecalcote** [comment]
Merge conflict

**Comment by UsmanDev09** [comment]
@Meyazhagan Please move Database Summary logic and state into its own component.

**Comment by Meyazhagan** [comment]
@UsmanDev09 I made the changes, and resolved merge conflict

**Comment by UsmanDev09** [comment]
@Meyazhagan The UI needs a bit of revamping. 

You can try to be creative on your own or ping me to discuss how it should look like.

database_summary

**Comment by Meyazhagan** [comment]
@UsmanDev09 I updated the UI
image

**Comment by UsmanDev09** [comment]
Looks good to me. Were you able to implement pagination too?

**Comment by Meyazhagan** [comment]
> Were you able to implement pagination too?

@UsmanDev09 Thanks for reminding me. I added pagination

**Comment by UsmanDev09** [comment]
LGTM @Meyazhagan. Good Work!

**Review by UsmanDev09 — APPROVED** [review]

**Review by MUzairS15 — APPROVED** [review]
Great work @Meyazhagan 🙌🎉

**Comment by MUzairS15** [comment]
@Meyazhagan before we merge will you push the Eslint fix??

**Comment by Meyazhagan** [comment]
@MUzairS15 I fixed the lint errors

**Pull request merged**
