### PR TITLE
[Docs] Fix position of buttons in the code snippets on quick start page.

### PR DESCRIPTION
**Pull request by chinu-anand**
**Notes for Reviewers**

This PR fixes the weird position of buttons on Quick Start Guide page in Meshery Docs. https://docs.meshery.io/installation/quick-start

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit c285ca874e9bd23351e3e1a3ab1979950b9bdd75 at: https://64016d2cd8fa147218019a74--meshery-docs-preview.netlify.app

**Comment by soham4abc** [comment]
Hello @chinu-anand I tested the preview and saw this particular page:

image

I guess the problem still persists. Will you please look into it.

**Comment by chinu-anand** [comment]
Yikes! I will fix that ASAP.

**Comment by rinkuhasija** [comment]
hey @chinu-anand , which issue does this PR fix ? I am asking this because an Issue is already opened (#7229 ) which has some parts of Issue in common with the Issue you are trying to fix with this PR, and I've already raised a PR for that. So, please check that once and do not fix the common part (merging of icons of codeblock with sidebar on quick-start page) because my PR already fixes that.
@soham4abc The Issue with the page you mentioned above, will be fixed by my PR. Please check that once.

**Comment by chinu-anand** [comment]
@rinkuhasija This PR is not about just setting z-index to auto, it's part of the visual redesign of the code snippet of Meshery Docs. This PR is not referenced to an issue because it's a direct PR. Waiting to be reviewed and approved by @Chadha93.

**Comment by rinkuhasija** [comment]
> @rinkuhasija This PR is not about just setting z-index to auto, it's part of the visual redesign of the code snippet of Meshery Docs. This PR is not referenced to an issue because it's a direct PR. Waiting to be reviewed and approved by @Chadha93. So if I don't fix that icon bug, my work will be imperfect which is not my working style.
> 
> Now it depends upon the reviewer whether to consider that particular change from my PR or yours, I feel it would be much better if your PR merges before me, my extra work will be reduced 😁.

Yes, that's what is want. I commented here so that our PR's don't create any merge conflicts. And if my PR merges, the issue already opened will be closed, and your extra work will also be reduced. 😉

**Comment by l5io** [comment]
🚀 Preview for commit 71539f06ebe5e2e7fbc578f1b9e71a6b2a969e80 at: https://6402c93784f6a44e37b0e02f--meshery-docs-preview.netlify.app

**Comment by soham4abc** [comment]
@chinu-anand  The changes look good to me

@leecalcote would you have a look?

**Comment by soham4abc** [comment]
> hey @chinu-anand , which issue does this PR fix ? I am asking this because an Issue is already opened (#7229 ) which has some parts of Issue in common with the Issue you are trying to fix with this PR, and I've already raised a PR for that. So, please check that once and do not work with the common part (merging of icons of codeblock with sidebar on quick-start page) because my PR already fixes that. @soham4abc The Issue with the page you mentioned above, will be fixed by my PR. Please check that once.

@rinkuhasija 
Can you mention the number of your PR please?

**Review by vishalvivekm — DISMISSED** [review]
Nice! @chinu-anand 🚀

**Review by sudhanshutech — CHANGES_REQUESTED** [review]
The copy icon is not visible in dark mode. Are you working on that also @chinu-anand ?

**Comment by vishalvivekm** [comment]
> The copy icon is not visible in dark mode. Are you working on that also @chinu-anand ?

 Demonstrated in the call. He's it all fixed in a open PR ( the visibility and the feedback ) refer #7166 @sudhanshutech

**Comment by sudhanshutech** [comment]
> > The copy icon is not visible in dark mode. Are you working on that also @chinu-anand ?
> 
> Demonstrated in the call. He's it all fixed in a open PR ( the visibility and the feedback ) refer #7166 @sudhanshutech

Okay that's great

**Comment by l5io** [comment]
🚀 Preview for commit c0be29a01274b9167b74af6c8ff714cd60552505 at: https://6406ad92774f59223f892e93--meshery-docs-preview.netlify.app

**Comment by leecalcote** [comment]
@chinu-anand I have a request to make of you regarding quick start buttons. If you'll be on the Websites meeting today, I'll describe it to you.

**Comment by l5io** [comment]
🚀 Preview for commit cd366b4af1da4b8974113ac33c32077b1b2ffc3c at: https://6411ea244d13f14685599f75--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit cd366b4af1da4b8974113ac33c32077b1b2ffc3c at: https://64550c0ae1454f14d29cc433--meshery-docs-preview.netlify.app

**Comment by vishalvivekm** [comment]
This PR is good to go.
@chinu-anand would you be on websites call today ( T minus 10) ? let's discuss and get it merged.

**Comment by sudhanshutech** [comment]
@vishalvivekm are we good to go with this pr ?

**Comment by Chadha93** [comment]
@vishalvivekm How are we moving with this PR?

**Comment by vishalvivekm** [comment]
@sudhanshutech @Chadha93 
Except for the color suggestions on the three • icons, which wasn't incorporated, this PR is good to go with.

**Comment by sudhanshutech** [comment]
> @sudhanshutech @Chadha93 Except for the color suggestions on the three • icons, which wasn't incorporated, this PR is good to go with. 

I guess its not a matter of fact now , major bug has been solved so we can go for it .

**Review by sudhanshutech — APPROVED** [review]

**Review by vishalvivekm — APPROVED** [review]

**Review by leecalcote — APPROVED** [review]
Thanks, @chinu-anand 👍

**Pull request merged**
