### PR TITLE
Add SMI Conformance capability to Istio Adapter

### LINKED ISSUE #1486: [Docs] List SMI Conformance as a feature of the adapter for Istio
**Current State:**
The documentation for the [Meshery adapter for Istio](https://meshery.layer5.io/docs/service-meshes/adapters/istio) is missing a list and description of all of the operations that it supports. 

**Desired State:**
Another supported feature of the adapter for Kuma is SMI Conformance - https://meshery.layer5.io/docs/functionality/smi-conformance. This needs to be highlighted as  functionality in each of the adapter docs.

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

### PR DESCRIPTION
**Pull request by ghost**
**Description**

This PR fixes #1486

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by PluckyPrecious** [comment]
Eureka, She did it! 🥳👀

**Comment by KarenEfereyan** [comment]
> Eureka, She did it! 🥳👀

Told you i would

**Comment by leecalcote** [comment]
@KarenEfereyan you’ll want to avoid having duplicative commits between two different PRs, if you can.

**Comment by KarenEfereyan** [comment]
Im sorry lee. Ill watch out for that in the future

**Comment by leecalcote** [comment]
Sounds real good. No sweat. I can’t tell you how many times I’ve done the same thing. The root cause here is an outdated fork / branch. Syncing your fork with the remote upstream (this repo) will solve the issue (you can still do this on this branch (this PR)). Instructions in the second contributing.md.

**Comment by KarenEfereyan** [comment]
@chandrashritii can you kindly review?

**Comment by chandrashritii** [comment]
Looks good @KarenEfereyan 

@leecalcote The documentation has been updated to include the SMI conformance section for the OSM and Kuma adapters. Do we want the scroll bar and the extra dots? I'm not sure it looks right (Attaching screenshots below):

Screenshot_2020-09-17 Kuma Adapter

Screenshot_2020-09-17 Open Service Mesh Adapter

**Comment by KarenEfereyan** [comment]
It can be removed @chandrashritii though that's how it is all around the other adapters. I don't think it has so much of a negative impact though

**Comment by chandrashritii** [comment]
This looks good for now @leecalcote Any further updates, if we choose to do them, can be done in another PR. This one can be merged.

@KarenEfereyan You're right there. Good work!

**Review by chandrashritii — APPROVED** [review]

**Comment by KarenEfereyan** [comment]
Thanks sis @chandrashritii

**Pull request merged**
