### PR TITLE
[mesheryctl] perf should not require a running Docker process #2763

### LINKED ISSUE #2763: [mesheryctl] `perf` should not require a running Docker process
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior
`mesheryctl perf` requires require Docker to be running.

**Example**

```
$ mesheryctl perf
Docker is not running.
Start Docker now [y/n]? 
```

#### Desired Behavior
`mesheryctl perf` should not require Docker to be running.

- Meshery Version: v0.5.2
- Platform: Docker

#### Contributor Resources

- [mesheryctl Contributing Guide](https://github.com/layer5io/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)

### PR DESCRIPTION
**Pull request by Naimaoye**
**Description**

This PR fixes #2763

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by adithyaakrishna — APPROVED** [review]
LGTM. Thanks for working on this 🎉 @Naimaoye 
But I would have to wait for @navendu-pottekkat 's review regarding the work :)

**Review by leecalcote — APPROVED** [review]
Finalizing PR #2776 involves this complication: 

While Docker’s availability is not a universal prerequisite for perf, Docker’s availability is a prereq in the event of the current-context platform being Docker. Which is to say that `perf` will need a preflight as a PreRunE, I think, and will need to be an error, not just a warning.

Considering the timeliness of #2776's merging, yes, we can move forward with merging in that even though it will not include the final, necessary logic, it will be an improvement from the current logic, which (currently) prevents kubernetes users from using `perf`.

**Review by navendu-pottekkat — APPROVED** [review]
Thank you @Naimaoye . LGTM 🚀

**Comment by navendu-pottekkat** [comment]
@piyushsingariya consider to add the updated preflight check in this command when you add the new function.

**Pull request merged**
