### PR TITLE
[OPA] Add namespace-hierarchichal policy

### PR DESCRIPTION
**Pull request by Abhishek-kumar09**
**Notes for Reviewers**

This PR fixes #
Add Namespace hierarchical policy, that fetches the available namespaces and their relationship with other nodes in the design.

https://github.com/meshery/meshery/assets/48255244/3ad0ccba-7adc-4080-a31b-62b448ef7dab

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
> [](https://meshery.layer5.io/catalog/applications)

@Abhishek-kumar09 do we know what happened here?

**Comment by leecalcote** [comment]
Are the "service"s mentioned in this PR patternfile services or k8s services?

**Review by leecalcote — COMMENTED** [review]
Let's ensure that this policy is highly reusable for any parent-child relationship.

Shall we pour our effort into 7900 instead?

**Comment by leecalcote** [comment]
> Let's ensure that this policy is highly reusable for any parent-child relationship.
> 
> Shall we pour our effort into #7900 instead?

Pending a decision, @Abhishek-kumar09

**Comment by Abhishek-kumar09** [comment]
I forgot to send a note here, but sent it on slack, that yes, lets do. I'm updating this WASM policy to work on any parent-child relationship that too should operate on cytoscapeJson.

**Pull request merged**
