### PR TITLE
added "language: en" to the frontmatter of all Docs pages that are in English 

### LINKED ISSUE #7283: [Docs] Add "language: en" to the frontmatter of all Docs pages that are in English
#### Current State
A Spanish translation of Meshery's docs exists. In order to facilitate a separation between viewing the dark speak in different languages, it would be good to have all pages containing a `language` frontmatter setting. Currently, not all of the English pages have this setting.

Example of a page missing this setting - https://github.com/meshery/meshery/blob/master/docs/pages/reference/rest-api-reference.md?plain=1

Example of a page having this setting - https://github.com/meshery/meshery/blob/master/docs/pages/reference/troubleshooting/installation.md?plain=1

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by hirentimbadiya**
**Notes for Reviewers**
@leecalcote I have created this new PR that includes only my commits and also made sure that  I have not made changes to v0.4 or v0.5 files In releases folder.

This PR fixes #7283 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 1e2f7a618e7f3cc35ee6ae3de498dd3d95d417f2 at: https://640948aab8c2154ed1022ed7--meshery-docs-preview.netlify.app

**Review by leecalcote — APPROVED** [review]
Looks great, @hirentimbadiya 👏

**Comment by leecalcote** [comment]
Yay, @hirentimbadiya! 🎈

**Comment by hirentimbadiya** [comment]
> Yay, @hirentimbadiya! 🎈

Thank you @leecalcote , just the beginning!!

**Pull request merged**
