### PR TITLE
[Server] Boottime: add registrant's name for Model registration log

### LINKED ISSUE #11475: [Server] Boottime: Model registration log missing registrant's name
### Current Behavior

The following log is displayed at boot time of Meshery Server:

```
INFO[2024-07-28T14:50:43-05:00] For registrant   successfully imported 12 models 108 relationships  app=meshery
```

### Expected Behavior
The name of the registrant should be included between "registrant" and  "successfully" in the same fashion that registrant's names are included in similar log.

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by alloydm**
**Notes for Reviewers**

This PR fixes #11475 
There was no default RelationshipHostname if registrant's name was empty. Fixed it by adding default Relationship HostName

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — COMMENTED** [review]
Thanks, @alloydm.

@humblenginr, @Jougan-0, I understand that this registration logic is under heavy activity currently. Acknowledging that most of this logic will be moved to MeshKit soon, I wonder if we can't slip in this contribution from @alloydm beforehand.

@alloydm, heads-up there is a similar error message defined in https://gitHub.com/meshery/meshkit.

**Comment by Jougan-0** [comment]
The server is running and not closing @alloydm

**Comment by alloydm** [comment]
> The server is running and not closing @alloydm for [workflow](https://github.com/meshery/meshery/actions/runs/10192302607/job/28195013999?pr=11511). Add the missing close statement if you would.

okay, I don't see my changes reflected in the integration test, that you have shared. Is this a regression?

**Comment by humblenginr** [comment]
> Thanks, @alloydm.
> 
> @humblenginr, @Jougan-0, I understand that this registration logic is under heavy activity currently. Acknowledging that most of this logic will be moved to MeshKit soon, I wonder if we can't slip in this contribution from @alloydm beforehand.
> 
> @alloydm, heads-up there is a similar error message defined in https://gitHub.com/meshery/meshkit.

yes, it's being tracked here - https://github.com/meshery/meshery/issues/11512

**Review by Jougan-0 — APPROVED** [review]

**Pull request merged**
