### PR TITLE
Populating content field

### LINKED ISSUE #7159: [UI] - Content field is empty
#### Current Behavior
In the top right corner, the tools card has content section empty.

#### Desired Behavior
Either it should be removed or some other links could be added.

#### Screenshots/Logs
image

#### Environment

- Browser: Chrome
- Host OS: Windows

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by gurpreet-legend**
**Notes for Reviewers**

- The empty content section needs to be filled with the page navigations. 
**Task:** Create a yaml file having information of every page's navigation links along with their title and integrate it with the current setup. 

- The data for every page needs to be added in `docs/_data/content.yml` and corresponding `docs/_layouts/default.html` file needs to be updated with conditional values for each page.

**Screenshot of sample population:**
image

This PR fixes #7159 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 18a047048ddda5673a4d78b49e377a92d2294ec1 at: https://640289600dfed03ab4d8efd6--meshery-docs-preview.netlify.app

**Comment by gurpreet-legend** [comment]
@leecalcote @Nikhil-Ladha @eeshaanSA can you check if this is the format we want for the content section?

**Comment by Chadha93** [comment]
@gurpreet-legend Let's discuss this on the Meshery Dev call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#) if you would. :)

**Review by vishalvivekm — COMMENTED** [review]
done via #7307 // @leecalcote

**Review by leecalcote — CHANGES_REQUESTED** [review]
Folks, we need for this intra-page table of contents to be dynamically generated and not require manual itemization of each heading. 

1) We won't be successful in initial itemization. This PR is a prime example of an incomplete job in this regard.
2) We won't be successful in sustaining of ongoing itemization as contributors come by and will be unaware of the need for separate, manual itemization.

Please return to the drawing board here.

**Comment by gurpreet-legend** [comment]
> Folks, we need for this intra-page table of contents to be dynamically generated and not require manual itemization of each heading. 
> 
> 1) We won't be successful in initial itemization. This PR is a prime example of an incomplete job in this regard.
> 2) We won't be successful in sustaining of ongoing itemization as contributors come by and will be unaware of the need for separate, manual itemization.
> 
> Please return to the drawing board here.

Sure @leecalcote 
Actually I was planning on implementing a more dynamic approach here, but I guess someone beat me in that regard becuase this has already been implemented by #7307

**Comment by vishalvivekm** [comment]
let's close this PR @gurpreet-legend // done by #7307

**Comment by Chadha93** [comment]
Thank you gents.

**Pull request closed without merging**
