### PR TITLE
Time stamp removed from mesheryctl

### PR DESCRIPTION
**Pull request by anandrkskd**
Signed-off-by: anandrkskd <anandrkskd@gmail.com>
#601 
This PR removes Time stamp from mesheryctl

### CODE REVIEW

**Comment by leecalcote** [comment]
@Nikhil-Ladha @nunix could you test this new version of `mesheryctl` (v0.3.8) on Windows? We're hopeful that this addresses some ugliness on Windows as well.

**Comment by nunix** [comment]
@leecalcote sorry for the delay. Now it displays beautfifully 👍 great work

image

**Comment by leecalcote** [comment]
Sooo much better, @anandrkskd. 👍

**Comment by anandrkskd** [comment]
Now this felt much better

**Pull request merged**
