### PR TITLE
Create Shubham-Attendence

### PR DESCRIPTION
**Pull request by ShubhamAXS19**
**Notes for Reviewers**

- This PR fixes #

- For ui changes: Please add a screenshot showcasing the UI before/after changes. 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 4f2e72c6d69422b70c039d62fe8f2c7504b85d24 at: https://671a4c6136ee03fef06e6d22--meshery-docs-preview.netlify.app

**Review by sudhanshutech — APPROVED** [review]

**Comment by sudhanshutech** [comment]
@ShubhamAXS19 will you sign off your commits please

**Comment by l5io** [comment]
🚀 Preview for commit 826bfe380447c5a6b536f4ad08b66bb4d4709585 at: https://671a5c1647d2e40a8899c979--meshery-docs-preview.netlify.app

**Review by leecalcote — CHANGES_REQUESTED** [review]
Thanks, @ShubhamAXS19. Please amend your commits with signoff by following these intersections - https://github.com/meshery/meshery/pull/12473/checks?check_run_id=32014483505

**Comment by vishalvivekm** [comment]
> Thanks, @ShubhamAXS19. Please amend your commits with signoff by following these intersections - https://github.com/meshery/meshery/pull/12473/checks?check_run_id=32014483505

@ShubhamAXS19

**Comment by ShubhamAXS19** [comment]
Sorry @sudhanshutech @vishalvivekm @leecalcote .
While signing attendence on thursday i never cloned the repo because of the internet. I closed this pr and made a new one. The new one is signed by me. 

Please do let me know if i need to do anything else

**Comment by leecalcote** [comment]
@ShubhamAXS19, OK, I let you know that you didn't signoff on your commit on the new one either.

**Pull request closed without merging**
