### PR TITLE
typo fixed

### LINKED ISSUE #3543: [Docs] "satrt" should be "start"
#### Current State
typo in documentation : `mesheryctl system satrt`
#### Desired State
should be `mesheryctl system start`
---

#### Contributor Resources

- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/meshery/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
- [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by nitinosiris**
Signed-off-by: nitinosiris <nitinwartkar58@gmail.com>

**Description**

This PR fixes #3543 

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit af14808b07d5ca4b99a5241774895d4e7185ba4e at: https://60f30974f706db415c1b6af9--meshery-docs-preview.netlify.app

**Review by alphaX86 — APPROVED** [review]
LGTM on my side 👍

**Review by leecalcote — APPROVED** [review]

**Comment by mgfeller** [comment]
This typo is intentional. It illustrates how cobra can be used to handled typos :smile:

**Comment by nitinosiris** [comment]
> This typo is intentional. It illustrates how cobra can be used to handled typos 😄

Ohh no :}

**Comment by alphaX86** [comment]
> This typo is intentional. It illustrates how cobra can be used to handled typos 😄

Right.... OwO seems we need to revert it then

**Comment by alphaX86** [comment]
I didn't notice this.... :/ anyway @nitinosiris can you revert this in a new PR.

**Comment by leecalcote** [comment]
Oh, boy. I saw that a typo was fixed and moved briskly on merging.

**Comment by nitinosiris** [comment]
> I didn't notice this.... :/ anyway @nitinosiris can you revert this in a new PR?

I'll try, but don't have local copy of meshery, since I had to reinstall it.

**Comment by alphaX86** [comment]
Reclone?........ I guess you don't need it actually to do that, I know a short cut kind but could you chat me on Slack so that I can help you?

**Comment by nitinosiris** [comment]
> Reclone?........ I guess you don't need it actually to do that, I know a short cut kind but could you chat me on Slack so that I can help you? Don't worry I'll say a thing that will pass the DCO check without worrying the clone for sign-off

Lets chat on slack

**Comment by nitinosiris** [comment]
> Reclone?........ I guess you don't need it actually to do that, I know a short cut kind but could you chat me on Slack so that I can help you? Don't worry I'll say a thing that will pass the DCO check without worrying the clone for sign-off

Slack I'd : Nitin wartkar

**Pull request merged**
