### PR TITLE
Create dorine_tipo.md

### PR DESCRIPTION
**Pull request by MissTipo**
**Notes for Reviewers**

This PR fixes #

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 35e7ac0e8f836eedf9d890e17b3bd0e8154998f6 at: https://66e2ec86f2f0c97fc136fbde--meshery-docs-preview.netlify.app

**Comment by vishalvivekm** [comment]
Thank you @MissTipo 
Will you follow https://github.com/meshery/meshery/pull/11995/checks?check_run_id=30054563518 to pass the dco ?

**Comment by vishalvivekm** [comment]
Here know more about DCO: https://docs.meshery.io/project/contributing#general-contribution-flow

**Comment by l5io** [comment]
🚀 Preview for commit e59ce7054169eba5ae586119ae77b02f418f8d71 at: https://66e30d536180892a054c1717--meshery-docs-preview.netlify.app

**Review by leecalcote — APPROVED** [review]

**Comment by l5io** [comment]
🚀 Preview for commit 5bdae39a2fbc9934682f905b615239799562ced1 at: https://66e40e98f0e44df22438ecca--meshery-docs-preview.netlify.app

**Review by leecalcote — APPROVED** [review]

**Pull request merged**
