### PR TITLE
Fix Grafana issue and CI misspell os name

### LINKED ISSUE #817: Go Compile error with Grafana_helper.go
When compiling current code with latest grafana_helper. There is error
` c.GetActualOrg undefined (type *sdk.Client has no field or method GetActualOrg) ` on line 61,129 at grafana_helper.go 

Fix this error 

Reference :
https://github.com/grafana-tools/sdk/blob/f0431e44c1c35b20751dc4c210a00b4c0d09d1d5/rest-org.go#L76
See here and update the code.

### PR DESCRIPTION
**Pull request by Aisuko**
Signed-off-by: Aisuko <urakiny@gmail.com>

#### Description

This PR fixes  #817   

#### Checklist

- [x] [DCO](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin) signed.
- [x] Title of the PR starts with area name, e.g. `meshery:`, `mesheryctl:`, `ui:`.

### CODE REVIEW

**Comment by leecalcote** [comment]
Thanks for this @Aisuko! This bug has been an ugly one for too long.

**Comment by Aisuko** [comment]
> Thanks for this @Aisuko! This bug has been an ugly one for too long.

@Lee You are welcome. I'm working on how to test this PR. As you know we lost many of the unit tests. So, the PR can be merged after I test the change is working well. Welcome to share any idea of how to test

**Comment by Aisuko** [comment]
Here I'd like to show you guys the test I was running. In order to show that the Grafana dashboard in this PR can be work very well.  I deployed Linkerd2 app demo, and run the performance test with `Meshery`

Screen Shot 2020-04-20 at 11 20 04 AM

Screen Shot 2020-04-20 at 11 19 39 AM

**Comment by Aisuko** [comment]
@leecalcote May you help to check the Grafana panel. I'm not sure I know how to deal with the Meshery Grafana.

**Comment by leecalcote** [comment]
@Aisuko good question. Here is how you can go about deploying and connect to a Grafana and Prometheus instance:

1. Using Meshery, deploy Istio.
1. Using Meshery, deploy BookInfo.
1. Using kubectl, edit the Grafana and Prometheus services in the `Istio-system` namespace:
```
kubectl edit svc grafana -n istio-system
```
1. Change `spec.type` from ClusterIP to NodePort.
1. Save changes and get the newly assigned port for the service.
```
$ kubectl get svc grafana -n istio-system
NAME      TYPE       CLUSTER-IP      EXTERNAL-IP   PORT(S)          AGE
grafana   NodePort   10.100.67.144   <none>        3000:30188/TCP   3d11h
```
1. Using your host's IP address, enter `http://<host-ip>:30188` into the Metrics panel in Meshery's Settings page (replace 30188 with your environment's port number).

**Comment by leecalcote** [comment]
@Aisuko, I know this test setup is a little involved, so I thought I would ask if you were successful with setting one up. I can test as well.

**Comment by Aisuko** [comment]
> @Aisuko, I know this test setup is a little involved, so I thought I would ask if you were successful with setting one up. I can test as well.

The Istio is not working for me and you know the reason🤣🤣

**Comment by leecalcote** [comment]
Quick note - This one is still on my to-do list!

**Comment by Aisuko** [comment]
@leecalcote  Isaw the Grafana issue was fixed by PR #912 yesterday. So, I rebase from the that. And this PR not include any important contents just some style warning. So, feel free merge

**Comment by leecalcote** [comment]
Oh, very good, @Aisuko. 👍

**Pull request merged**
