### PR TITLE
[adapters] Change proto to accomodate adapter information

### PR DESCRIPTION
**Pull request by uds5501**
Signed-off-by: Uddeshya Singh <singhuddeshyaofficial@gmail.com>

**Description**
Currently checking out adapter configurations

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Hey, hey. Pretty neat to see this, @uds5501. 😎

**Comment by leecalcote** [comment]
Hi @uds5501, as we near the release date for v0.5.0, we'll need to evaluate which final PRs will make it into the release. What are your thoughts on the state of the effort in this PR?

**Comment by leecalcote** [comment]
FYI, @mgfeller relevant, stale work.

**Comment by mgfeller** [comment]
> FYI, @mgfeller relevant, stale work.

Thanks, @leecalcote

**Comment by mgfeller** [comment]
Closing this one as the work and discussions was carried over to https://github.com/layer5io/meshery/pull/2454

**Pull request closed without merging**
