### PR TITLE
Add Link Mesheryctl Command Reference

### LINKED ISSUE #2859: [Docs] Broken link: mesheryctl command reference
**Current State:**
The link the mesheryctl command reference at the bottom of this page is broken - https://docs.meshery.io/guides/mesheryctl/configuring-autocompletion-for-mesheryctl

**Desired State:**
Should point to `/reference/mesheryctl`

Screen Shot 2021-05-06 at 9 28 36 PM

---
**Contributor Resources**
- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

### PR DESCRIPTION
**Pull request by Vi1234sh12**
Signed-off-by: Vishal Dhanure <vishald41234@gmail.com>

**Description**

This PR fixes #2859 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by Vi1234sh12** [comment]
hey @Nikhil-Ladha,  can  you close  the previous pull request "Update Link Mesheryctl Command Reference #2860" 

Here, I'm updated Pull Request

**Comment by Nikhil-Ladha** [comment]
Could you please rebase your branch? Using the CLI or the option given above?

**Comment by Vi1234sh12** [comment]
> Could you please rebase your branch? Using the CLI or the option given above?



> Could you please rebase your branch? Using the CLI or the option given above?
Sorry, But I Do Not understand,  Can you give me a command

**Comment by Nikhil-Ladha** [comment]
> > Sorry, But I Do Not understand,  Can you give me a command

There is an `Update branch` button just above the `Merge pull request` button, or the CLI command is:
- `git checkout master`
- `git fetch upstream`
- `git merge upstream/master`
- `git push`
- `git checkout <to-your-development-branch>(.i,e the branch using which you made the PR)`
- `git rebase master`
- `git push --force origin <current-branch`

**Comment by Nikhil-Ladha** [comment]
Also, I asked you to follow the contributing guidelines in the last PR, which clearly mentioned `create/checkout to a new branch` while submitting/making changes, but you are still making PR from your master branch. Why?

**Comment by Vi1234sh12** [comment]
> Also, I asked you to follow the contributing guidelines in the last PR, which clearly mentioned `create/checkout to a new branch` while submitting/making changes, but you are still making PR from your master branch. Why?

Actually, I Forget This One

**Review by Nikhil-Ladha — APPROVED** [review]

**Pull request merged**
