### PR TITLE
#9935 changed the link from /guides/configuration-management/creating…

### PR DESCRIPTION
**Pull request by muthu9594**
…-a-meshrey-design to /guides/creating-a-meshrey-design

**Notes for Reviewers**

This PR fixes #

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 42bc03f4380875481f64ab6d783f9c434c730662 at: https://65a0cf24511fda83728610b1--meshery-docs-preview.netlify.app

**Comment by saurabh100ni** [comment]
Hi @muthu9594   ,
Thanks for your PR! I encourage you to share this in the Website Meeting tomorrow at 6:30 PM IST. Share your screen, and walk us through it. It's cool to take and share feedback. Check the [Doc](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit) here to include this PR.

You're welcome at the meeting

Check to [community calendar](https://layer5.io/community/calendar) for more details of meetings at Layers.

**Review by MUzairS15 — COMMENTED** [review]
@muthu9594 Fix the DCO issue, then we are good here.

**Comment by sudhanshutech** [comment]
@muthu9594 are you there?

**Pull request merged**
