### PR TITLE
chore(ci/cd): Update e2e tests with newer k8s versions

### LINKED ISSUE #9662: [CI] Add support to run e2e tests on latest K8s version
### Current Behavior

Currently, all the e2e test that Meshery runs are performed on old k8s version.
See https://docs.meshery.io/installation/compatibility-matrix

### Desired Behavior

Add support to run e2e tests on newer k8s version.

This was discussed in Build and Release call on December 14th, 2023. See https://discuss.layer5.io/t/build-and-release-meeting-dec-14th-2023/4344 for more details. 

### Implementation

Update: https://github.com/meshery/meshery/blob/master/.github/workflows/test_adaptersv2.yaml

### Acceptance Tests

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
- Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)
- 🧪 [Meshery Test Plan Spreadsheet](https://docs.google.com/spreadsheets/d/13Ir4gfaKoAX9r8qYjAFFl_U9ntke4X5ndREY1T7bnVs/edit#gid=0)

### PR DESCRIPTION
**Pull request by webstradev**
**Notes for Reviewers**

This PR closes #9662 

I've added the latest patch version of the last 4 releases as displayed on https://kubernetes.io/releases/

Didn't test this locally as I think these can only be tested in the githb actions.

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
@webstradev, most excellent!

**Review by theBeginner86 — APPROVED** [review]
LGTM 🚀 

Thanks @webstradev

**Review by leecalcote — APPROVED** [review]
Ditto. Looking good. With any luck, we'll need new K8s versions show up here - https://docs.meshery.io/installation/compatibility-matrix.

**Comment by leecalcote** [comment]
Yay, @webstradev! 🎈

**Pull request merged**
