### PR TITLE
Added Namespace Background SVGs

### PR DESCRIPTION
**Pull request by Harshit-Dandriyal**
Signed-off-by: Harshit Dandriyal <56961488+Harshit-Dandriyal@users.noreply.github.com>

**Description**
Added Namespace Background SVGs

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Why do we need another copy of these SVGs? Just use CSS to style the existing SVGs?

**Comment by leecalcote** [comment]
Ok, sounds good. In the past, I have recommend that we apply a framework:

- <logo>.svg (color, logo only, no name)
- <logo_white.svg (no color, white only, logo only, no name) - mandatory naming convention. 
- primary color in #HEX _required_
- secondary color in #HEX _optional_

**Comment by Harshit-Dandriyal** [comment]
> Ok, sounds good. In the past, I have recommend that we apply a framework:
> 
> * <logo>.svg (color, logo only, no name)
> * <logo_white.svg> (no color, white only, logo only, no name) - mandatory naming convention.
> * primary color in #HEX _required_
> * secondary color in #HEX _optional_

okk, on it :+1:

**Review by leecalcote — CHANGES_REQUESTED** [review]
@Harshit-Dandriyal @Abhishek-kumar09 why is "namespace" and "background" part of the filename for a white-colored copy of a component logo?

@Harshit-Dandriyal we seem to continue to have fundamental misunderstandings.

**Review by Abhishek-kumar09 — APPROVED** [review]

**Pull request merged**
