### PR TITLE
fix meshmodel duplicates 

### PR DESCRIPTION
**Pull request by Revolyssup**
**Notes for Reviewers**

This PR fixes #

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
What was the cause of this issue?

**Comment by Revolyssup** [comment]
> What was the cause of this issue?

There were two issues. One of which was my oversight, where components of all modelVersion were present inside a specific ModelVersion due to an incorrect filter.

**Comment by leecalcote** [comment]
Thanks. It'd be nice to see this logic moved out of main.go and into an import function.

**Comment by leecalcote** [comment]
Perhaps, something that @Azanul can work on. Having said that, I having seen any progress on a connection state machine just yet, though.

**Comment by Azanul** [comment]
> Perhaps, something that @Azanul can work on.

Sure

> Having said that, I having seen any progress on a connection state machine just yet, though.

I'm assuming that's a "haven't". The connection state machine 🔮 presents itself to mortals when they're ready for it.

**Pull request merged**
