### PR TITLE
[FIXED] Server error utility CI failure

### PR DESCRIPTION
**Pull request by zakisk**
**Notes for Reviewers**

This PR fixes #

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — DISMISSED** [review]

**Comment by leecalcote** [comment]
@zakisk there's a merge conflict to have a look at.

**Comment by leecalcote** [comment]
@zakisk thanks much for this. I wonder if the commit went on hiatus.

**Comment by MUzairS15** [comment]
@zakisk I don’t think we need this any longer, it was updated in one of my PR.

**Comment by leecalcote** [comment]
Thank you, gents.

**Pull request closed without merging**
