### PR TITLE
Added "first timers' welcome guide" link to meshery.layer5.io/docs/project

### PR DESCRIPTION
**Pull request by seun-beta**
**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
@seun-beta Thanks! Looking good. Will you execute these git commands to sign-off on your commits? https://github.com/layer5io/meshery/pull/1418/checks?check_run_id=994243155

**Comment by seun-beta** [comment]
> @seun-beta Thanks! Looking good. Will you execute these git commands to sign-off on your commits? https://github.com/layer5io/meshery/pull/1418/checks?check_run_id=994243155

Thank you @leecalcote

**Comment by PluckyPrecious** [comment]
Welldone 👍🏽 @seun-beta could you please edit your commit comment to fill the PR form appropriately and sign DCO? Click on the [DCO error details](https://github.com/layer5io/meshery/pull/1418/checks?check_run_id=994243155) for steps to get it sorted.

**Comment by seun-beta** [comment]
> Welldone 👍🏽 @seun-beta could you please edit your commit comment to fill the PR form appropriately and sign DCO? Click on the [DCO error details](https://github.com/layer5io/meshery/pull/1418/checks?check_run_id=994243155) for steps to get it sorted. 

I would get it sorted once I can access my laptop this night.

**Comment by leecalcote** [comment]
@seun-beta this is a fix for https://github.com/layer5io/meshery/issues/1405, correct? Please reference the issue you're fixing in the issue description.

// @kennygrace

**Comment by seun-beta** [comment]
Tried over and over again, can't seem to get a hand of using VS Code with GitHub. Apologies

**Comment by leecalcote** [comment]
@seun-beta keep trying. You can simply execute the git commands in your terminal that @PluckyPrecious provided.

**Comment by PluckyPrecious** [comment]
Hi @seun-beta kindly check the workspace, we would be glad to give you a hand.🙂

**Comment by seun-beta** [comment]
@leecalcote I am still on it.

**Pull request closed without merging**
