### PR TITLE
adding alias for bitcask repo

### LINKED ISSUE #3513: [mesheryctl]: make command fails
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior

make command is giving error 
`go build -ldflags="-w -s -X github.com/layer5io/meshery/mesheryctl/internal/cli/root/constants.version=v0.5.37 -X github.com/layer5io/meshery/mesheryctl/internal/cli/root/constants.commitsha=0d75f9fd5f2fbb16f3b9133a135a663264106cb6 -X github.com/layer5io/meshery/mesheryctl/internal/cli/root/constants.releasechannel="edge"" -o mesheryctl cmd/mesheryctl/main.go
go: github.com/prologic/bitcask@v0.3.9: reading github.com/prologic/bitcask/go.mod at revision v0.3.9: unknown revision v0.3.9
make: *** [Makefile:8: make] Error 1`
Thanks **Muskan Khedia** for pointing out.

#### Desired Behavior

Make command should run without any error
#### Screenshots/Logs

err

#### Environment

- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker or Kubernetes

#### Mockups

---

#### Contributor Resources

- [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by nitinosiris**
Signed-off-by: nitinosiris <nitinwartkar58@gmail.com>

**Description**

This PR fixes #3513 

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by mgfeller — CHANGES_REQUESTED** [review]
Thanks @nitinosiris ! 
`make make` on my system (Ubuntu 18.04) works, bitcask is resolved correctly (according to download log in IntelliJ). 

If you could run `go mod tidy` to tidy up `go.mod` and `go.sum` wrt your change and commit those that would be great!

**Comment by nitinosiris** [comment]
> Thanks @nitinosiris !
> `make make` on my system (Ubuntu 18.04) works, bitcask is resolved correctly (according to download log in IntelliJ).
> 
> If you could run `go mod tidy` to tidy up `go.mod` and `go.sum` wrt your change and commit those that would be great!

done

**Review by mgfeller — APPROVED** [review]
LGTM :+1:

**Comment by leecalcote** [comment]
Yay, @nitinosiris! 🎈 You line up the issues, and you knock 'em down, too. 🙂

**Comment by nitinosiris** [comment]
> Yay, @nitinosiris! 🎈 You line up the issues, and you knock 'em down, too. 🙂

Thanks, looking forward make good PR' s! 😀

**Pull request merged**
