### PR TITLE
[CI] updated current workflows to put appropriate labels on PRs according to the files changed.

### LINKED ISSUE #3992: [CI] Augment existing build workflows to affix appropriate labels to PRs
**Description:**
Meshery release notes are auto-generated by Release Drafter. Release Drafter uses PR labels to create release notes and place changelogs into specific categories (e.g. Features, Maintenance, Docs...)

Contributors can manually affix labels to PRs. These labels provide information to the release notes drafter, so that each item in the changelog is categorized under it appropriate section.

**Request:**
Augment existing build workflows to affix appropriate labels to PRs based on changes to files in specific paths (e.g. `file-path: /docs` --> label: `area/docs`.

**Example of Release Notes being categorized:**

Screen Shot 2021-08-11 at 9 00 26 AM

_Originally posted by @leecalcote in https://github.com/meshery/meshery/issues/3851#issuecomment-897140731_

### PR DESCRIPTION
**Pull request by asubedy**
Signed-off-by: Aaditya N. Subedy <frexpe@pm.me>

**Description**
The changes should now automatically put labels on pull requests according to the files changed.

This PR fixes #3992

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — APPROVED** [review]
Looks good to me, @asubedy 👍

**Review by DelusionalOptimist — COMMENTED** [review]
@asubedy we would also need to update the workflow file at
https://github.com/meshery/meshery/blob/5cd223dffb3ab0b79152d5815211093ad78fafdb/.github/workflows/release-drafter.yml#L3-L6
to run the action in PRs too.
A new pull_request target would be needed, looking something like:
```
 pull_request:
    types: [opened, reopened, synchronize]
```

**Comment by asubedy** [comment]
@DelusionalOptimist  Oops yes, i forgot yo check the release-drafter file at the workflow folder. I will be changing it and submitting a new PR. Thank you

**Comment by warunicorn19** [comment]
@asubedy you could just do the changes in this PR itself.

**Review by DelusionalOptimist — APPROVED** [review]
Looks good.
Thanks @asubedy :+1:

**Pull request merged**
