### PR TITLE
Explicitly set UTF-8 encoding for SVG images 

### LINKED ISSUE #5872: [UI] Explicitly set UTF-8 encoding for SVG images
#### Current Behavior
UTF8 formatting is needed for SVG image capability with specific UI libraries used in Meshery.

#### Desired Behavior
All SVGs within the `/ui` directory should be explicitly set to use `utf-8` encoding.

#### Implementation

```
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<svg>...</svg>
```

or

```
'background-image': 'data:image/svg+xml;charset=utf-8,' + encodeURIComponent(svg)
```

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by manikmmalhotra**
Signed-off-by: manikmmalhotra <manikmalhotra2113@gmail.com>

**Description**
All SVGs within the /ui directory should be explicitly set to use utf-8 encoding.
This PR fixes #5872 

**Notes for Reviewers**
Always open for suggestions and improvements. Please point me out if anything should be added/corrected.

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
@asubedy I don't think this will work as this breaks our ability to import the SVGs. Is that right?

**Review by Chadha93 — COMMENTED** [review]
This seems repetition, 
1. ui/public/static/img/citrix_service_mesh.svg

2. ui/public/static/img/citrixservicemesh.svg

Please also look for others, remove repetitions

**Comment by Chadha93** [comment]
This will break the svg in UI, since the imports where these svgs are referenced/used also need to be updated.

**Comment by manikmmalhotra** [comment]
@Chadha93 i'll work on the changes

**Comment by manikmmalhotra** [comment]
@Chadha93 i've removed the  repetitions here, but i've some doubts with change in the import statements, do u have any blog i can refer to for better understanding??

**Comment by leecalcote** [comment]
@Abhishek-kumar09 are the changes here what is needed?

**Comment by leecalcote** [comment]
> @Abhishek-kumar09 are the changes here what is needed?

@Abhishek-kumar09 what's the verdict?

**Review by Abhishek-kumar09 — CHANGES_REQUESTED** [review]
@manikmmalhotra 
Great work done here, in naming as well as setting the utf character. But for the correct change we need to add the string as follows
`<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE svg>`

The diff: 
```diff
+ <?xml version="1.0" encoding="UTF-8"?><!DOCTYPE svg>
-  <?xml version="1.0" encoding="UTF-8"?>
```

**Comment by Abhishek-kumar09** [comment]
Sorry for kept missing the notifications here, @leecalcote , @manikmmalhotra 😢

**Comment by leecalcote** [comment]
@Abhishek-kumar09 what are we doing here?

**Review by Abhishek-kumar09 — CHANGES_REQUESTED** [review]
This needs to be updated. Anyways the utf encoding string was most required for only the component svgs that were rendered on cytoscape, but doing this good change doesn't hurt, so thank you @manikmmalhotra .

Also, the updates need to be done here once this https://github.com/meshery/meshery/pull/6375 is merged. Rest everything is looking fine to me. There is some redundancy of logos, because the same logo is present in `img/component-svg` folder, Can we use those and delete these extra svgs, @manikmmalhotra Again the statement holds only true when the PR mentioned above is merged.

**Pull request closed without merging**
