### PR TITLE
Heading included for Related Integration sections

### PR DESCRIPTION
**Pull request by iArchitSharma**
**Notes for Reviewers**

This PR fixes #

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 5829d71e33517d585044d651b5a7b080fab596d7 at: https://6672d75f076d6e23ce666892--meshery-docs-preview.netlify.app

**Comment by leecalcote** [comment]
I swear that this was causing duplicates previously.

**Review by leecalcote — COMMENTED** [review]
This doesn't case duplication of sections, does it?

**Comment by leecalcote** [comment]
@iArchitSharma?

**Review by leecalcote — CHANGES_REQUESTED** [review]
Screenshot 2024-06-20 at 4 00 21 PM

Did you test this, @iArchitSharma?

**Comment by iArchitSharma** [comment]
@leecalcote I did but didn't saw the repeated heading in end earlier, let me fix

**Comment by leecalcote** [comment]
Thank you.😊

**Comment by l5io** [comment]
🚀 Preview for commit d2914997e7d1ec356b51ed70aa85c5f938f35c90 at: https://66751322ab5bad24027b0282--meshery-docs-preview.netlify.app

**Review by leecalcote — CHANGES_REQUESTED** [review]
Copy/pasting the default layout makes the site harder to maintain. What other approach o you have? What change was needed? I can’t tell given the brand new file.

**Comment by l5io** [comment]
🚀 Preview for commit 53f1242c3800429f5e60f5e0b9bcac1f67fabdfc at: https://66756a5bff107b6ece3e5216--meshery-docs-preview.netlify.app

**Comment by iArchitSharma** [comment]
I don't know why **conditional check** wasn't working earlier, but now it did

**Review by leecalcote — APPROVED** [review]

**Pull request merged**
