### PR TITLE
Remove Meshery Adapter for Meshery Octarine entry from adaptersList

### LINKED ISSUE #8289: [UI] Extensions: Remove Meshery Adapter for Octarine card
#### Current Behavior
This adapter has been archived and is no longer supported.

#### Desired Behavior
Remove its extension card entry under http://localhost:9081/extensions page in Meshery UI.

#### Screenshots/Logs
Screenshot 2023-07-26 at 5 49 21 PM 1

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by supzi-del**
**Notes for Reviewers**

This PR fixes #8289 

Hey there! This simple PR took me a while as it was my first time around exploring the project. Please let me know if any changes are required. 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by ShivangRawat30 — APPROVED** [review]
@leecalcote The PR looks good to me.

**Review by leecalcote — APPROVED** [review]
Thanks. Will you do the same thing for the Open Service Mesh Adapter?

**Review by leecalcote — DISMISSED** [review]
LGTM. Thank you, @supzi-del 👍

**Comment by leecalcote** [comment]
@supzi-del will you execute the git commands on this page to ensure that DCO check passes and your commits are signed off? https://github.com/meshery/meshery/pull/8302/checks?check_run_id=15436256439

**Comment by supzi-del** [comment]
[Remove Meshery Adapter for Meshery Octarine entry from adaptersList](https://github.com/meshery/meshery/pull/8302/commits/7fb45135d189b92df5f236c63ec0d2f1607a0e93) 
[7fb4513](https://github.com/meshery/meshery/pull/8302/commits/7fb45135d189b92df5f236c63ec0d2f1607a0e93)

[Remove Open Service Mesh Adapter Card](https://github.com/meshery/meshery/pull/8302/commits/02e0c85c1ae30a5945a5db28b3a8772d83eda45b) 
[02e0c85](https://github.com/meshery/meshery/pull/8302/commits/02e0c85c1ae30a5945a5db28b3a8772d83eda45b)

The above commits are signed-off

**Pull request merged**
