### PR TITLE
Marked Attendance

### PR DESCRIPTION
**Pull request by Sayan4444**
**Notes for Reviewers**

- This PR fixes #

- For ui changes: Please add a screenshot showcasing the UI before/after changes. 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit daf96654371193b0c92178e42d31194907b7c4b5 at: https://67238b1bc24e6810f228d0be--meshery-docs-preview.netlify.app

**Comment by leecalcote** [comment]
@Sayan4444 execute these instructions - https://github.com/meshery/meshery/pull/12533/checks?check_run_id=32338229745

**Comment by l5io** [comment]
🚀 Preview for commit ae9f4db62f44853937ee2806edf2f941f867eb41 at: https://6725bea1df9db0140dcd5955--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit a16a00ba2e1f9a340f7b1fad0ee7c0f3cc9ac883 at: https://6725c3e2d58019311840465f--meshery-docs-preview.netlify.app

**Comment by Sayan4444** [comment]
> @Sayan4444 execute these instructions - https://github.com/meshery/meshery/pull/12533/checks?check_run_id=32338229745

Thanks a lot sir

**Review by hargunkaur286 — APPROVED** [review]

**Pull request merged**
