### PR TITLE
Confirmation (files) + Typo fix in Patterns/Filters/Applications/PerformanceProfile 

### PR DESCRIPTION
**Pull request by Chadha93**
Signed-off-by: Gaurav Chadha <gauravchadha1676@gmail.com>

**Description**
Typo fix in Patterns/Filters/Applications/PerformanceProfile

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Is the plural form only shown when someone is deleting multiple entries? Or does this invert the bug and show plural nouns when only a single object is being deleted?

**Comment by Chadha93** [comment]
> Is the plural form only shown when someone is deleting multiple entries? Or does this invert the bug and show plural nouns when only a single object is being deleted?

@leecalcote  Gotcha, to eliminate this situation I have used Parenthetical plural(s), this will be fine for both singular or plural . 
Should I update this way :
Screenshot from 2021-09-02 11-52-45

**Comment by leecalcote** [comment]
Thanks, @Chadha93. This will work, yes. It's not ideal as it makes Meshery appear as if it doesn't quite know what is going on. We should be able to discern whether the user is sending a single delete or multiple and use language dedicated to that scenario.

**Comment by leecalcote** [comment]
Ideally, we will provide the users feedback on bulk deletes by including the count of items that they are confirming to delete.

**Comment by Chadha93** [comment]
> Thanks, @Chadha93. This will work, yes. It's not ideal as it makes Meshery appear as if it doesn't quite know what is going on. We should be able to discern whether the user is sending a single delete or multiple and use language dedicated to that scenario.

Got it, found a common functionality example for ideation it will be perfect IMO
Screenshot from 2021-09-06 18-10-48
It's similar when we perform delete in our editor/system.

**Comment by Chadha93** [comment]
Delete modal
mockup

**Comment by leecalcote** [comment]
Looking real good. Yes, this is on the money.

**Comment by leecalcote** [comment]
@Chadha93 a merge conflict has arisen...

**Pull request closed without merging**
