### PR TITLE
[Connection Register] - Register MeshSync data as a connection

### PR DESCRIPTION
**Pull request by senali-d**
**Notes for Reviewers**

This PR fixes #

https://github.com/meshery/meshery/assets/52546856/5b8f9d08-3b4c-4882-9e4e-498235355b5b

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
I tweaked a component import reference to overcome the build failure.

**Review by MUzairS15 — CHANGES_REQUESTED** [review]
There is no option to start the registration process.

https://github.com/meshery/meshery/assets/79860504/9c80c026-23c2-4f11-8c94-3b537e4bc0b6

Screenshot 2023-12-05 at 2 21 29 PM

Duplicate options are still available.
Screenshot 2023-12-05 at 2 22 22 PM
No able to sort by `Discovered At`.

**Comment by MUzairS15** [comment]
@senali-d I made some changes and have added comments.

**Comment by senali-d** [comment]
@MUzairS15 I'm just check the sorting is not works for Discovered At. So that's why sorting was not enable in the UI.
When I use `creation_timestamp` as column name. It throws a error there is no column in the the table. I think it's due to `creation_timestamp` is in the `Kubernetes_resource_object_meta` table. Is there any other param need to add other than column name.

**Comment by Yashsharma1911** [comment]
Testing

**Comment by leecalcote** [comment]
@MUzairS15 @senali-d ready for merge?

**Comment by MUzairS15** [comment]
Yes

**Review by MUzairS15 — APPROVED** [review]

**Pull request merged**
