### PR TITLE
MeshSync: Support discovery of Citrix Service Mesh #745

### LINKED ISSUE #745: [MeshSync] Support discovery of Citrix Service Mesh
**Current Behavior**
The /performance page scans the environment to detect the presence and details of deployed service meshes. Currently, this functionality is partially provided for Istio (just for Istio's presence and version #). 

**Desired Behavior**
Meshery should scan the environment for all known types of service meshes and their details, including Citrix CPX.

**Implementation**
Using [kubernetes-scan.go](https://github.com/layer5io/meshery/blob/master/helpers/kubernetes-scan.go) and [istio-scan.go](https://github.com/layer5io/meshery/blob/master/helpers/istio-scan.go) an example, create scans for each of the other types of Meshery-supported service meshes.

**Future:** each scan needs to be enhanced to gather service mesh-specific configuration details.

### PR DESCRIPTION
**Pull request by vijcheru**
Signed-off-by: vijcheru <vijcheru@gmail.com>

#### Description

This PR fixes #745     

#### Checklist

- [x] [DCO](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin) signed.
- [x] Title of the PR starts with area name, e.g. `meshery:`, `mesheryctl:`, `ui:`.

### CODE REVIEW

**Comment by nveenjain** [comment]
Nice work @vijcheru, I've no objection with this PR getting merged, however if you could also add `Octarine` service mesh's meta information too in this, then that would be great!

**Comment by vijcheru** [comment]
> 
> 
> Nice work @vijcheru, I've no objection with this PR getting merged. This PR fulfils it's objective. however, if you could also add `Octarine` service mesh's meta information too in this, then that would be great!

Would that be octarinesec/microservice-proxy?

**Comment by nveenjain** [comment]
I looked into the dockerhub and couldn't find a separate image for service mesh... I guess, we can open a separate issue to track it, and then ask user to install octarine and check which images are used and populate them into this file.

**Comment by nveenjain** [comment]
@leecalcote , it's good to be merged!!!

**Comment by dheerajng** [comment]
> @dheerajng in terms of determining whether a Citrix Service Mesh is present I the environment, we will look for a container image with the name “cpx” in it, correct?

We need to look for two container images:
i) quay.io/citrix/citrix-istio-adaptor
ii) quay.io/citrix/citrix-k8s-cpx-ingress

`docker.io/citrix/citrix-k8s-ingress-controller` is not the right image. This is for [ingress controller](https://github.com/citrix/citrix-k8s-ingress-controller).

**Pull request merged**
