### PR TITLE
Keys table added

### PR DESCRIPTION
**Pull request by iArchitSharma**
**Notes for Reviewers**

xx

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit fcf572b597c52164aba2c6f5a9db8ba0da15c89c at: https://66261741427b5f728530f75f--meshery-docs-preview.netlify.app

**Review by leecalcote — APPROVED** [review]

**Comment by leecalcote** [comment]
@iArchitSharma what other pages link to this page? Is it tagged with frontmatter such that it shows up in the main index page? Is is manually added to the TOC?

**Comment by l5io** [comment]
🚀 Preview for commit 547a80eb4bed07596882c8d0db5533931b20a016 at: https://662df237fd575284b84ec2f3--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 52cf209aea2f808c065434661cc544e83882b3b0 at: https://6635af64c2628297b9e888e5--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 2313557f050c0c56ea2f1a44b19c726b1c35ab91 at: https://6641a82f5f644a6a9d002b26--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit b44e12c3b1d09ca2fdf56061eeb75c5decd54542 at: https://6641ab699af0167171a06fcb--meshery-docs-preview.netlify.app

**Comment by iArchitSharma** [comment]
image
image

**Comment by l5io** [comment]
🚀 Preview for commit 9906e33a48a156a55fbb87d5db3ee24968069738 at: https://6641b30abcb7ce73bb800be3--meshery-docs-preview.netlify.app

**Comment by iArchitSharma** [comment]
@ShivamCoder23 its complete now waiting for review

**Comment by l5io** [comment]
🚀 Preview for commit 9e55af3967eb4443fcc9e8b12b9568a36379bab4 at: https://6644b7666e477b158a977fba--meshery-docs-preview.netlify.app

**Review by leecalcote — DISMISSED** [review]
Why are the SQL statements included?
Screenshot 2024-05-16 at 10 36 31 AM

**Comment by iArchitSharma** [comment]
@leecalcote i forgot to push my last commit, it ready for merge now!

**Comment by l5io** [comment]
🚀 Preview for commit 8f258b29fadc31dc75cb71868a37949a88db6ef0 at: https://6646427b7aa3e50c31ffda96--meshery-docs-preview.netlify.app

**Comment by iArchitSharma** [comment]
image

**Comment by l5io** [comment]
🚀 Preview for commit ca61bbe93ccbe91d9813d237e6cba3aa3c62a5d8 at: https://664643af67e6b51aa8a6e03b--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 44288aa766656220eca588207f3ca94601e43665 at: https://66464705ab96fe23c589657b--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 6aafe030565e9ec3a9680689a04372bc9530bcda at: https://66464823453c371f1b2b64cc--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit c87aea9b0b6f52bd31b239e57999a815e6dd1f4c at: https://664667a456a651008508f68f--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit c4de26f4b255f1cb12310c3f8b74e6b38bc2e26d at: https://6646685a7c57ca04f4ac9463--meshery-docs-preview.netlify.app

**Comment by dragon-slayer875** [comment]
@iArchitSharma Maybe the table contents can be scrolled through horizontally too when in mobile mode?

image

**Comment by l5io** [comment]
🚀 Preview for commit a7b00ceca4bfe34a19176d437c2e5a5cb8d80cdd at: https://664d78095caf3d9341e24f76--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 012d10772136c7a61531823650db8be753ab69e4 at: https://664db6c1f06a64cb72ef27fd--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 73e81b63ee62a6959a519a331da1a47690d4d2c2 at: https://664ddea60ea540f87e152002--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit b17035a9f40c64ac240894a3f79f1bd5d6d94bdb at: https://664deca7d0044e0463a7c957--meshery-docs-preview.netlify.app

**Review by Yashsharma1911 — APPROVED** [review]
LGTM now, two items remaining

1. Categories keys table similar to docs.layer5.io
2. Allow to show key id if user want to see, bydefault hide it

you can take care of these items in separate PR

**Pull request merged**
