### PR TITLE
API endpoints for WASM filter CRUD

### LINKED ISSUE #2741: CRUD for WASM filters
#### Desired Behavior

Meshery should have 2 new API endpoints-

`/api/experimental/filter` `(GET- get details of all filters POST- create a new filter)`

`/api/experimental/filter/{id}` `(GET- get details of a specific filter)`

In addition to the new API endpoints, `mesheryctl` should also have a new experimental command `mesheryctl exp filter` which leverages the above API endpoints for CRUD commands.

### PR DESCRIPTION
**Pull request by pottekkat**
**Description**

This PR fixes #2741 

Added two new endpoints `/api/experimental/filter` (`GET` `POST`) and `/api/experimental/filter/{id}` (`GET`)

This is implemented similar to the `pattern` endpoint.

**Notes for Reviewers**

"Apply" not added. Only "Import added".

Should this be separate endpoints or persist the file and then apply in one go?

- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
> Should this be separate endpoints or persist the file and then apply in one go?

We landed on having two separate endpoints and making it the client's responsibility to determine whether to invoke both endpoints back-to-back or not.

**Review by leecalcote — DISMISSED** [review]
LGTM

**Comment by navendu-pottekkat** [comment]
@leecalcote Okay, then I will add the other endpoints too so that the client can both import and deploy separately. We can merge after that...

**Review by leecalcote — APPROVED** [review]

**Comment by leecalcote** [comment]
Lgtm. A separate PR for the deploy function. @utkarsh-pro to confirm endpoint name/design.

**Comment by navendu-pottekkat** [comment]
Did not add the DELETE function... Adding it... I guess we can merge after that...

Deploy will be added in a separate PR.

**Comment by navendu-pottekkat** [comment]
@leecalcote Done, please merge the changes

**Pull request merged**
