### PR TITLE
Added about uninstalling meshery using a Docker Extension platform

### LINKED ISSUE #7431: [Docs] uninstallation method for each installation method
#### Current State
There are no uninstallation methods provided in the documentation for respective installations.

#### Desired State
A new central page (or section) and for each installation method, we need an uninstallation method.

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by Srishtihere**
**Notes for Reviewers**

This PR fixes #7431 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit a4d2fff110274c5ced9782173df5b5cdf827b8e3 at: https://64f2533dd758940ed9229160--meshery-docs-preview.netlify.app

**Comment by leecalcote** [comment]
Thanks, @Srishtihere!

**Review by Aisuko — COMMENTED** [review]
Thanks for your contribution. Please do sign off.

**Comment by Srishtihere** [comment]
hey @Aisuko can you guide me how to do sign-off

**Comment by Srishtihere** [comment]
> hey @Aisuko can you guide me how to do sign-off

its done. I have signed off

**Comment by l5io** [comment]
🚀 Preview for commit efd84a2bed00ecf15ee21619ca12a45583ab28e6 at: https://64f357628db6110e6406076e--meshery-docs-preview.netlify.app

**Comment by vishalvivekm** [comment]
@Srishtihere still missing DCO.

Let's discuss it on the websites call.
Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima), if you would :)

**Comment by Ghat0tkach** [comment]
Hello @Srishtihere , 
Let's discuss it on the websites call.
Please add this as an agenda item in the meeting minutes, if you would :)

https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima

**Comment by Srishtihere** [comment]
Hey when will be the meeting, I was not present today around 5.30. Saw this message a little late, would love to join it the next meet

**Comment by Srishtihere** [comment]
hey is their a way i can make some more changes in doc maybe write uninstallation method using windows ?? and add sign off, because I followed https://github.com/meshery/meshery/pull/8638/checks?check_run_id=16442016120 these steps earlier but still no progress

**Comment by leecalcote** [comment]
> Hey when will be the meeting, I was not present today around 5.30. Saw this message a little late, would love to join it the next meet

Here you are: https://meshery.io/calendar

**Comment by leecalcote** [comment]
> hey is their a way i can make some more changes in doc maybe write uninstallation method using windows ?? and add sign off, because I followed https://github.com/meshery/meshery/pull/8638/checks?check_run_id=16442016120 these steps earlier but still no progress

Sounds real good. You can add those Windows commits to this same PR.

**Comment by Srishtihere** [comment]
For the docker extension I have done a sign off. Won't be a problem anymore. For windows working on it

**Comment by l5io** [comment]
🚀 Preview for commit ecb4a8c074215e1841cb8616b947512cd968de3c at: https://64f9ff27c89beb2010aaeee5--meshery-docs-preview.netlify.app

**Comment by leecalcote** [comment]
@Srishtihere please execute the `git` commands listed here - https://github.com/meshery/meshery/pull/8638/checks?check_run_id=16590200757

**Review by leecalcote — CHANGES_REQUESTED** [review]
@Srishtihere thanks for this effort. This much use of the large command prompts is overpowering and make the instructions difficult to follow. Will you refactor into plain `<code>` or 
```
code
``` 
display?

**Comment by saurabh100ni** [comment]
if there are any updates to it let's discuss it on the website call.
Please add this as an agenda item in the meeting minutes, if you would :)
https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima

**Comment by iArchitSharma** [comment]
@Srishtihere are you still there?

**Review by leecalcote — DISMISSED** [review]

**Pull request merged**
