### PR TITLE
Update all code snippets to new style in Meshery Docs

### LINKED ISSUE #7088: [Docs] Update all code snippets with the new code component.
#### Current State
All code snippets are using this default code snippet style provided by Markdown.

Screenshot from 2023-02-15 12-32-01

#### Desired State
Update all code snippets to the new style by using the custom built jekyll `code` component.

image

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by chinu-anand**
**Notes for Reviewers**
Wrapped all code snippets in the newly created `code` component and also updated documentation about using that component in Contributing>Mehsery Docs.

This PR fixes #7088 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit e81abfe7705f990a4e514e0777aa9812230b9343 at: https://63edd2e9c87a264f429fb05e--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 58aca3dd793d65304991df734e076c8cc9b27eaa at: https://63ede4464fe6485dc0468a02--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 85640e1efa4f7feb465ad74414cd6816cd677e2f at: https://63ee0a468c1bee13b4c24974--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 502cc5f89f299fc01d8449c251213914f0f841e5 at: https://63ee0c738c1bee152fc249de--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 37e28cc770cb5695d61b392d15b642296fe27cac at: https://63ef37b32691b9422f26fa7f--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit f320fab62edcda35faf87b447c46654773228ea4 at: https://63ef4049caa1af4a9452d094--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit af5d5378fa4d9ab6ef5e8f6fd8148ae1c21e06a1 at: https://63ef85daad399e0493a88146--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 9da051f0b3596c2cffc05b17f2282022c636067f at: https://63f0fe8b565a832adaa09557--meshery-docs-preview.netlify.app

**Review by leecalcote — DISMISSED** [review]
@chinu-anand, this is looking great. 👍

**Comment by leecalcote** [comment]
All done? or are there a few places left?

**Comment by chinu-anand** [comment]
> All done? or are there a few places left?

Almost done, 3-4 pages left only.

**Comment by l5io** [comment]
🚀 Preview for commit b8b8eef00a987e2ce8b82798581aca4a4697ee53 at: https://63f315efe945926db9d435e2--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 7bd24e8906b55802ec3405278d06d2fa89d6dbc0 at: https://63f31ac46938f506e455d645--meshery-docs-preview.netlify.app

**Review by leecalcote — APPROVED** [review]
Great work, @chinu-anand 👏

**Pull request merged**
