### PR TITLE
Create Ian.md

### PR DESCRIPTION
**Pull request by ianrwhitney**
**Notes for Reviewers**

This PR fixes #

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 40eceeada6a9de3ea9daa2145dea2b4eeeef2e60 at: https://66ec254d1f336daf318a0b31--meshery-docs-preview.netlify.app

**Comment by marblom007** [comment]
It's nice to have you participating on the Meshery project and in the Layer5 community. 🙂 We encourage all newcomers to star the Meshery repo. Have you [added your star](https://github.com/meshery/meshery/stargazers)? ⭐

**Comment by ianrwhitney** [comment]
@marblom007 Yes, I have! thank you !

**Review by leecalcote — APPROVED** [review]
Excellent

**Pull request merged**
