### PR TITLE
Change jitsi helm chart link

### LINKED ISSUE #11233: [Models] Jitsi component showing in CloudNativePG design
### Current Situation

Python Sample App fails to deploy on Meshery Playground because the custom resource component uses the Jitsi model instead of the CloudNativePG model. This custom resource is part of the CloudNativePG operator and is used to manage PostgreSQL clusters on Kubernetes.

Screenshot 2024-06-21 at 8 56 16 PM

**Links to Meshery Designs** -> [Sample Application](https://playground.meshery.io/extension/meshmap?mode=design&design=87380dae-15c4-4234-be45-baed1cbb33c2) and [CloudNativePG](https://playground.meshery.io/extension/meshmap?mode=design&design=cc3ddaa5-2f71-4ebe-9df1-563a9c187888)

**Cluster Resource manifest**
```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: my-postgresql
  namespace: default
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:15.4
  instances: 3
  storage:
    size: 1Gi
  bootstrap:
    initdb:
      database: goals_database
      owner: goals_user
      secret:
        name: my-postgresql-credentials
```

### Proposed Change

---
A CloudNativePG model needs to be created and the jitsi helm chart repo link needs to updated to a [release here](https://github.com/jitsi-contrib/jitsi-helm/releases/)

### General Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### Understanding Meshery Models

- 🖥 [Models Overview](https://docs.google.com/presentation/d/1SQMfyu5shjpGKlYONdVzOtd7UYTgLWBcgUvHMLCZ2tY/edit#slide=id.g226f5de5180_19_259)
- 👨‍💻[Models Repository](https://github.com/meshery/meshery/tree/master/server/meshmodel)

### Contributing to Meshery Models

- https://docs.meshery.io/project/contributing/contributing-models

### Contributing to Meshery Relationships

- https://docs.meshery.io/project/contributing/contributing-relationships

  Review a prior pull request as an example of how to define a Relationships:   https://github.com/meshery/meshery/pull/9880/files

### PR DESCRIPTION
**Pull request by alero-awani**
**Notes for Reviewers**

This PR fixes #11233

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — APPROVED** [review]
LGTM. @Alero-Awani, was this change also made in the Meshery Integrations spreadsheet?

**Comment by vishalvivekm** [comment]
@Alero-Awani 
Let's discuss this in Meshery Dev meeting on Wednesday. Adding this as an agenda item....
Meeting minutes: https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit?pli=1#
Meeting link: https://meet.layer5.io/meshery

**Comment by leecalcote** [comment]
> LGTM. @Alero-Awani, was this change also made in the Meshery Integrations spreadsheet?

**Comment by Alero-Awani** [comment]
@leecalcote Yes, the correct link was already on the spreadsheet.

**Review by leecalcote — APPROVED** [review]

**Pull request merged**
