### PR TITLE
[UI] Connection Wizard

### LINKED ISSUE #2434: [UI] Configuration Wizard
#### Current Behavior
While Meshery is opinionated and assumes sensible defaults for users, some environments and some users will benefit from a multi-step configuration wizard that walks them through each of the areas of their Meshery deployment that they might need to initialize or change the configuration of.

#### Desired Behavior
Users are presented with an optional configuration wizard. The wizard and all of its steps should be idempotent. In many respects, the configuration wizard represents an assembly of existing functionality and settings that the user can configure. This multi-step form, however, provides a guide to successfully configuration a Meshery deployment.

Initial design should have four steps in the Configuration Wizard.

Step 1. Connect to Kubernetes.
Step 2. Deploy and Connect Meshery Operator (MeshSync).
Step 3. (Optional) Deploy or connect to one or more service meshes.
Step 4. (Optional) Deploy or connect to Prometheus and/or Grafana.

#### Implementation
- use and customize a react multi-stepper.
- partner with Golang-capable contributor (e.g. @Nikhil-Ladha or @navendu-pottekkat) new backend functionality might be needed. Create separate GH issue(s), if needed.
- partner with UX designer (@austinogiza)

#### Acceptance Tests
1. Users may pull up the configuration wizard during initial deployment of Meshery and anytime thereafter.
2. Users are allowed to skip steps that are marked as optional.
3. Configuration wizard should be accessible from the global navigation bar as a new icon (see screenshot with red arrow).

#### Mockups
- Configuration wizard icon location
  - Screen Shot 2021-02-21 at 8 40 37 PM

- Configuration wizard steps
  - See Figma (https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/?node-id=403%3A6811).

### PR DESCRIPTION
**Pull request by bartkalanski**
**Description**

This is a draft PR for the highly anticipated configuration wizard. Fixes #2434 

**[Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.
 

Signed-off-by: Bart Kalanski <bkalanski@gmail.com>

### CODE REVIEW

**Comment by navendu-pottekkat** [comment]
@bartkalanski Linked this PR to #2434

**Comment by leecalcote** [comment]
Some good looking progress demonstrated this week, @bartkalanski 👍

**Comment by bartkalanski** [comment]
Thank you @leecalcote

**Comment by adithyaakrishna** [comment]
@bartkalanski Could you squash the commits? 👀

**Comment by adithyaakrishna** [comment]
@leecalcote I'll checkout to this branch and go through the UI once. @bartkalanski Can we have a call regarding this, I'll help you out with the Failing checks.

**Comment by leecalcote** [comment]
Gents, we're nearing our final descent for the landing of Release v0.6.0. I'm checking in on how far out you consider this effort is.

**Comment by adithyaakrishna** [comment]
> Gents, we're nearing our final descent for the landing of Release v0.6.0. I'm checking in on how far out you consider this effort is.

I'm taking this up today, as discussed @leecalcote I'll checkout to this branch, check the docker and tests workflow and create a new PR. That would be okay right?

**Comment by adithyaakrishna** [comment]
@navendu-pottekkat @dhruv0000 There are like N conflicts regarding golang code which even after I tried in #3394 I couldn't get some stuff, bc I was a bit worried about breaking changes. Could you help me & @sudo-NithishKarthik  with this 👀

**Comment by sudo-NithishKarthik** [comment]
Sure thing @adithyaakrishna 😃

**Comment by sudo-NithishKarthik** [comment]
Addressed in #3501

**Pull request closed without merging**
