### PR TITLE
Fix for issue#6357  (race condition)

### LINKED ISSUE #6357: [Server] Race condition in K8s component registration
In the following code, the reference to range value `ctx` at line 86 generates a race condition because it is a reference in the body of a gorutine.

https://github.com/meshery/meshery/blob/f2b1ef8c7b987175f6e3af8e1d1cee2d0a9f3163/server/models/k8s_components_registration.go#L50-L96

([here](https://go.dev/play/p/pmmyHsSwkL2) a simplified version of the bug)

Bug found by [revive](https://github.com/mgechev/revive)

### PR DESCRIPTION
**Pull request by PratikforCoding**
**Description**
PR to solve issue of race condition becuase parameter was passed in the goroutine body

This PR fixes #6357 

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Thank you, @PratikforCoding

**Review by leecalcote — CHANGES_REQUESTED** [review]
Do take note of the failed lint check.

**Comment by PratikforCoding** [comment]
ok @leecalcote sir... trying to fix that

**Comment by PratikforCoding** [comment]
facing some problem in my "fix-6357" branch. closing the pull request and opening a new one.

**Pull request closed without merging**
