### PR TITLE
[Refactor] Added Patterns page

### PR DESCRIPTION
**Pull request by YashKamboj**
Signed-off-by: Yash Kamboj <yashkamboj29@gmail.com>

**Description**
Added Patterns page

Screenshot (198)
Screenshot (199)
Screenshot (197)
Screenshot (196)

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by YashKamboj** [comment]
@sudo-NithishKarthik @Chadha93 Review??

**Comment by leecalcote** [comment]
@YashKamboj please note: "Patterns" are now "Designs". You'll need to update to reflect this wording change.

**Comment by YashKamboj** [comment]
@leecalcote We also have to merge these PRs https://github.com/meshery/meshery/pull/5863 ,  https://github.com/meshery/meshery/pull/5764 .
As these PRs are interconnected  to the merged pr

**Comment by leecalcote** [comment]
Gotcha.

**Pull request merged**
