### PR TITLE
[WIP] Update Meshery results to follow SMP

### LINKED ISSUE #896: meshery: Update meshery results export to follow SMP
**Description**

Currently when you export a result, then a yaml file is downloaded. This file doesn't support SMP.
It only follows SMP partially... 

**Expected Behavior**

Exported yaml should follow SMP.

**Screenshots**
image
Click on download button

**Environment:**
 - OS: Any
 - Browser: ANy
 - Version: Latest
 - Device: Any
---
[Optional] **To Reproduce**
1. Create a performance result for any mesh
2. Click on results
3. Scroll down to any result, select it and click on download on top bar
4. Downloaded file doesn't follow SMPS.

[Optional] **Additional Context**

Currently results are downloaded in this format:-

```yaml
start_time: 2020-04-02T03:43:59.524931729+05:30
end_time: 2020-04-02T03:44:09.526222812+05:30
exp_uuid: assafs-XXXX-XXXX-XXXX-XXXXXXXX
endpoint_url: http://10.0.2.15:31380/productpage
env:
  kubernetes: v1.17.3
client:
  connections: 5
  rps: 1232.3408945620827
  latencies_ms:
    min: 0.000133302
    average: 0.004056244610385397
    p50: 0.002047835195530726
    p90: 0.009221491228070174
    p99: 0.025705645161290324
    max: 0.243865731
metrics: {}
```
This result should follow https://github.com/layer5io/service-mesh-performance-specification/blob/master/smps.yaml

### PR DESCRIPTION
**Pull request by pottekkat**
**Description**

This PR fixes #896 | **This is in WIP**

I was able to refactor the results in the YAML file but I'm stuck in getting the other missing results. I'm also not sure what those values mean and how I can access them...

Screenshot from 2021-03-25 21-12-12

- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
This is good. I should clarify that not all values have been implemented and so only a subset are available for export. This might be all that is available currently. 

We need to work toward implementing the rest. We might want to merge this work as a step forward in the meantime.

**Comment by navendu-pottekkat** [comment]
@leecalcote Yes, I have been trying to figure out where to pick these values from... There are some missing values here but this result follows SMP and only the rest of the values need to be filled...

**Comment by navendu-pottekkat** [comment]
@leecalcote Yes, I have been trying to figure out where to pick these values from... There are some missing values here but this result follows SMP and only the rest of the values need to be filled...

**Comment by navendu-pottekkat** [comment]
@leecalcote I have resolved the merge conflicts...

**Pull request merged**
