### PR TITLE
Update Readme.md (wrap words)

### LINKED ISSUE #7496: [Docs] Wrap words around images in readme.md
#### Current State
In this repo's readme.md two images are set to block display and not allowing words to wrap around them. 

Screenshot 2023-04-06 at 6 01 00 PM

#### Desired State
Have them wrap like the “Find your MeshMate” section does. Here is another example - https://github.com/layer5io/layer5#-community-and-contributions

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by HetviSoni**
**Notes for Reviewers**
Words wrapped around the image as asked in the issue.
image

This PR fixes #7496

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by HetviSoni** [comment]
Please review this @leecalcote

**Review by Aisuko — COMMENTED** [review]
It looks good to go. Please update the code to the latest version.

**Review by Aisuko — APPROVED** [review]
LGTM

**Comment by Aisuko** [comment]
Thanks for your contribution.

**Comment by HetviSoni** [comment]
> Thanks for your contribution.

Welcome. Looking forward to make more contributions☺️

**Pull request merged**
