### PR TITLE
[CI] UI: OS and Arch for fsevents package

### PR DESCRIPTION
**Pull request by leecalcote**
Signed-off-by: leecalcote <leecalcote@gmail.com>

**Description**

Added "linux" and "x64" as an OS and arch for the `fsevents` node module.

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
I’m seeing green!

**Comment by MarioArriaga92** [comment]
@leecalcote taking a look, were those values added manually or through a specific npm command?

**Comment by MarioArriaga92** [comment]
And can we get contributors with linux-based and win OS's to get this branch and do an "npm I'm inside the /ui folder?

**Comment by leecalcote** [comment]
@Nikhil-Ladha might have a Windows machine to test on.

**Comment by MarioArriaga92** [comment]
@leecalcote I've posted on slack to ask other contributors for help with this quick check https://layer5io.slack.com/archives/C011VPREG2Z/p1647445663606419

**Comment by leecalcote** [comment]
Merging as the critical item here is Linux building and releasing cleanly in Meshery releases. Other PR build checks can now start passing, hopefully.

**Comment by MarioArriaga92** [comment]
@leecalcote this issue is still happening in [PR 5171 - [Cypress] Add ui tests for lifecycle](https://github.com/meshery/meshery/pull/5171)

Failed Run:
https://github.com/meshery/meshery/runs/5603653688?check_suite_focus=true

Screenshot:
Screen Shot 2022-03-18 at 10 42 01

**Comment by leecalcote** [comment]
@MarioArriaga92 I have sync'ed this branch with master - https://github.com/meshery/meshery/pull/5235. Let's see how these checks turn out...

**Comment by warunicorn19** [comment]
All greens on https://github.com/meshery/meshery/pull/5235.

**Pull request merged**
