### PR TITLE
Change naming convention for Matrix markdown files

### LINKED ISSUE #4819: [Bug/Docs] Naming convention on compatibility matrix `md` files need to be fixed
#### Current Behavior
The updated repo of meshery contains doc files which are used for making the compatibility matrix. But due to naming convention in the markdown files, Windows users are now unable to clone/fetch repo. This bug must be fixed at earliest.

#### Files need to be fixed
image

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by alphaX86**
**Description**

This PR fixes #4819 

**Notes for Reviewers**
Don't merge PR ASAP. WIP!!

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit cfc23c51b69d400cc8f1756aa6a1ba8baa34d2dd at: https://61c47cb2fa1ce4d57d596a2d--meshery-docs-preview.netlify.app

**Comment by warunicorn19** [comment]
It's actually line 96 here https://github.com/meshery/meshery-istio/blob/master/.github/workflows/e2etest-servicemeshandaddon.yaml that's causing the issue.

**Comment by warunicorn19** [comment]
Not only here but that line in all the adapters is causing the issu

**Comment by l5io** [comment]
🚀 Preview for commit e2f2f53ac69364f57f5a605591372c8243bfb81c at: https://61c47dc0f3060da87628c5c2--meshery-docs-preview.netlify.app

**Comment by alphaX86** [comment]
I noticed it... I'm doing these for some adapters now

**Comment by alphaX86** [comment]
@warunicorn19 I suppose guess it's done for 3 adapters so far by the looks of the files in the main repo... right?

**Comment by warunicorn19** [comment]
Yes, linkerd osm and istio

**Comment by alphaX86** [comment]
> Yes, linkerd osm and istio

Got it!!!

**Comment by l5io** [comment]
🚀 Preview for commit 04a3a60d6305276f45725ceeebcf27bb994d0160 at: https://61c4837b5b5083d71583f6e6--meshery-docs-preview.netlify.app

**Comment by alphaX86** [comment]
@leecalcote I need review and merge of above 3 PRs done in adapter repo

**Comment by leecalcote** [comment]
Let's see if we can:

- use <date_commitsha>.md as the filename.
- have a `timestamp` entry in the front matter of each .md file.

**Comment by alphaX86** [comment]
> Let's see if we can:
> 
> - use <date_commitsha>.md as the filename.
> - have a `timestamp` entry in the front matter of each .md file.

Commit SHA as filename?? Need to think a way to implement it...

**Comment by leecalcote** [comment]
> > Let's see if we can:
> > 
> > * use <date_commitsha>.md as the filename.
> > * have a `timestamp` entry in the front matter of each .md file.
> 
> Commit SHA as filename?? Need to think a way to implement it...

Long form: `GITHUB_SHA` (see https://docs.github.com/en/actions/learn-github-actions/environment-variables)

or short form:

```
      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Check outputs
        run: echo ${{ steps.vars.outputs.sha_short }}
```

**Review by leecalcote — APPROVED** [review]

**Pull request merged**
