### PR TITLE
[Test] Disable dysfunctional catalog extension test

### PR DESCRIPTION
**Pull request by leecalcote**
**Notes for Reviewers**

This PR disables a test that is incomplete and not ready for inclusion and consideration of whether a PR should merge or not.

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by fitzergerald — APPROVED** [review]
Looks good to me

**Review by winkletinkle — APPROVED** [review]
Me, too. ✔️

**Comment by winkletinkle** [comment]
Wait, one test is still failing...

**Comment by leecalcote** [comment]
@jerensl do we need more tests disabled?

**Comment by leecalcote** [comment]
oh, I see. This extension is supposed to be enabled by default, but it users are supposed to be allowed to disable it.

**Comment by leecalcote** [comment]
> @leecalcote this one is a bug from the API when u try to toggle Meshery Catalog Content button from this page https://playground.meshery.io/user/preferences, it will be always enabled

Let's get to a passing state and work forward from there.

**Pull request merged**
