### PR TITLE
[Docs] Relationships page update

### PR DESCRIPTION
**Pull request by ritiksaxena124**
**Notes for Reviewers**

This PR 
- [x] Update the images of Relationships that MeshMap supports [WIP] 
- [x] Update the structure of the representation of relationships

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 398594e0f50248537cf1269d0ab42b50591f0735 at: https://65ea35f41d950c700b020352--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 65806fdde9ebd02a0db88f58c430d2cc71a6c724 at: https://65ea36f72faa5c747082b7b6--meshery-docs-preview.netlify.app

**Review by leecalcote — APPROVED** [review]
@ritiksaxena124 can we merge as work in progress, but a healthy first step?

**Comment by ritiksaxena124** [comment]
Yes now we can merge this PR

**Comment by l5io** [comment]
🚀 Preview for commit 81e0dacd5d660060f759d07fcfca3b8d1bcd2bfa at: https://65ec6ba3f0eed8a9014a2ef8--meshery-docs-preview.netlify.app

**Comment by vishalvivekm** [comment]
> Yes now we can merge this PR

@ritiksaxena124 Let's discuss this on websites call. Add this as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit), if you would :)

**Comment by l5io** [comment]
🚀 Preview for commit dc42f8eaa0d2f693640f38cc0cf18bedb73f0253 at: https://65f069c83f84950090faaa14--meshery-docs-preview.netlify.app

**Pull request merged**
