### PR TITLE
Made Configuration Icon consistent as other icons

### LINKED ISSUE #6636: [UI] Configurations navigation icon is not having arrow and fix tooltip position
#### Current Behavior
1. The new configuration icon in the Navigator is not showing a dropdown arrow on hover like other items under navigator.
2. The tooltip should not overlap with the navigator.
3. See the video for issue details:

https://user-images.githubusercontent.com/65453826/205725451-c378e2c2-2352-4963-a624-b59f4d8da8bf.mp4

#### Desired Behavior
Make the behavior consistent like other icons.

#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by hs05june**
**Notes for Reviewers**

This PR fixes #6636 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.
 

[ScreenRecording](https://user-images.githubusercontent.com/103871275/205976064-444e1c8a-5844-4a90-bdad-47ee524e0a61.webm)

### CODE REVIEW

**Review by Chadha93 — COMMENTED** [review]
@hs05june Could you please try fixing the DCO. check the steps in the details of workflow failure.

**Comment by Chadha93** [comment]
@hs05june  Let's discuss this on the Meshery Dev call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#) if you would. :)

**Comment by leecalcote** [comment]
Thank you, @hs05june 👏

**Comment by hs05june** [comment]
@Chadha93 I will be checking it

**Comment by hs05june** [comment]
@Chadha93 I have made another PR which has passed DCO

**Comment by Chadha93** [comment]
> @Chadha93 I have made another PR which has passed DCO

Gotcha.

**Pull request closed without merging**
