### PR TITLE
fix: #9399 Changed hovering effect

### LINKED ISSUE #9399: [UI] Kubernetes Config Modal Hovering Effect Deviation
### Current Behavior
[284250329-71a5d129-b84d-4628-a3e7-46aeb4e66716.webm](https://github.com/meshery/meshery/assets/128807866/395a1e07-ace0-489b-b42d-8948198435f6)

### Desired Behavior
We should be using our standard  styling for action buttons.

### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by Raj100679**
**Notes for Reviewers**

This PR fixes #9399 

Fixed hover effect in light mode on import button

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Raj100679** [comment]
@vaibhavpnimkar Hey Sorry took a long time for it, but i guess it's done

**Comment by leecalcote** [comment]
@vaibhavpnimkar ready for review.

**Comment by vaibhavpnimkar** [comment]
@leecalcote i have suggested him a change once its done it will be ready for review.

**Comment by Raj100679** [comment]
@vaibhavpnimkar I have signed off commits , are there any more changes ?

**Comment by vaibhavpnimkar** [comment]
@Raj100679 
you have changes this
 `backgroundColor: theme.palette.secondary.focused,` 
to this:
`backgroundColor: theme.palette.secondary[promptVariant || 'primary'],`
this change is not needed replace this : `backgroundColor: theme.palette.secondary.focused,`

**Comment by vaibhavpnimkar** [comment]
and share the screen recoring of changed hovering effect also @Raj100679 so we can confirm that it is working fine

**Comment by Raj100679** [comment]
Sure @vaibhavpnimkar will update till night

**Comment by Raj100679** [comment]
@vaibhavpnimkar if i change to this "backgroundColor: theme.palette.secondary.focused" instead of "backgroundColor: theme.palette.secondary[promptVariant || 'primary']" , the hover effect and the prompt button without hover will get same style .
Screenshot (131)
What should I change, can you tell me?

**Comment by Raj100679** [comment]
@vaibhavpnimkar is it correct? If it is correct I will push the changes
https://github.com/meshery/meshery/assets/85561967/5f56c7ab-2623-4c5e-90c1-490bbc6bf3c5

**Comment by vaibhavpnimkar** [comment]
Yes push the changes

**Comment by Raj100679** [comment]
@vaibhavpnimkar done

**Comment by vaibhavpnimkar** [comment]
@leecalcote @yash37158 THIS PR IS READY FOR REVIEW!!

**Comment by leecalcote** [comment]
> @leecalcote @yash37158 @Yashsharma1911 THIS PR IS READY FOR REVIEW!!everything look good to me!

Excellent. Thank you, gentlemen.

**Review by Yashsharma1911 — APPROVED** [review]
LGTM thankyou @Raj100679

**Pull request merged**
