### PR TITLE
Added Details-Summary tag

### PR DESCRIPTION
**Pull request by Mithil05**
Signed-off-by: Mithil Jogi <mithiljogi@gmail.com>
Issue fixed: #7455 

Added the required Details-Summary tags in the contributing.html file and achieved the desired state.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 599e239466a59b5c9e1677d613a053d2010bc890 at: https://642b0701c6424778ae0f2c4b--meshery-docs-preview.netlify.app

**Comment by Mithil05** [comment]
Signoff by "mithiljogi@gmail.com" Mithil Jogi
Issue fixed: #7455

Added the required Details-Summary tags in the contributing.html file and achieved the desired state.

**Comment by Mithil05** [comment]
Signed-off-by: Mithil Jogi "mithiljogi@gmail.com"
Issue fixed: #7455

Added the required Details-Summary tags in the contributing.html file and achieved the desired state.

**Comment by l5io** [comment]
🚀 Preview for commit 599e239466a59b5c9e1677d613a053d2010bc890 at: https://642b09cfcaa5da5bf2e9eaa8--meshery-docs-preview.netlify.app

**Comment by Mithil05** [comment]
Signed-off-by: Mithil Jogi <mithiljogi@gmail.com>
Issue fixed: https://github.com/meshery/meshery/issues/7455

Added the required Details-Summary tags in the contributing.html file and achieved the desired state.

**Comment by l5io** [comment]
🚀 Preview for commit 599e239466a59b5c9e1677d613a053d2010bc890 at: https://642b0d630c08995fbcc7e74d--meshery-docs-preview.netlify.app

**Comment by Mithil05** [comment]
Signed-off-by: Mithil Jogi <mithiljogi@gmail.com>
Issue fixed: #7455

Added the required Details-Summary tags in the contributing.html file and achieved the desired state.

**Comment by l5io** [comment]
🚀 Preview for commit 1b836d172dec09978e84949ea774078ed5c4bfb4 at: https://642b10933144000c9712af32--meshery-docs-preview.netlify.app

**Comment by Mithil05** [comment]
Signed-off-by: Mithil05 <mithiljogi@gmail.com>
Issue fixed: #7455

Added the required Details-Summary tags in the contributing.html file and achieved the desired state.

**Comment by l5io** [comment]
🚀 Preview for commit 1b836d172dec09978e84949ea774078ed5c4bfb4 at: https://642b1e4ddea63b18da8b62b4--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit ff273a66f3e6aa72fe50f1052af707a3c1510658 at: https://642b22b7a6d58962ca0122f2--meshery-docs-preview.netlify.app

**Review by leecalcote — CHANGES_REQUESTED** [review]
Thanks. Your change doesn’t seem to have had an effect - https://642b22b7a6d58962ca0122f2--meshery-docs-preview.netlify.app/project/contributing

**Comment by Mithil05** [comment]
Yes @leecalcote Sorry for that, I will be soon making changes

**Pull request closed without merging**
