### PR TITLE
[Docs] feature-guide-update

### PR DESCRIPTION
**Pull request by chandrashritii**
- New quickstart guide
- `mesheryctl` instructions extracted to an independent guide
- New sample apps guide
- Screenshots added

Signed-off-by: Shriti <shritichan@gmail.com>

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by tripathyprateek** [comment]
was there a netlify preview for this PR?

**Review by leecalcote — APPROVED** [review]
Thank you, @chandrashritii. A big lift here. 👍

**Comment by leecalcote** [comment]
> was there a netlify preview for this PR?

Oh, hmm. I'm not sure, @tripathyprateek

**Comment by tripathyprateek** [comment]
> > was there a netlify preview for this PR?
> 
> Oh, hmm. I'm not sure, @tripathyprateek 

Oh okay. I was reviewing it on local.

**Pull request merged**
