### PR TITLE
[RJSF] fixed the size of the input field 

### PR DESCRIPTION
**Pull request by harkiratsm**
Signed-off-by: harkiratsm <multaniharry714@gmail.com>

**Description**

This PR fixes #

**Notes for Reviewers**
image

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by harkiratsm** [comment]
@leecalcote Any Thoughts !

**Comment by harkiratsm** [comment]
image

**Comment by harkiratsm** [comment]
@leecalcote I hope you like it

**Review by adithyaakrishna — APPROVED** [review]
LGTM

**Comment by adithyaakrishna** [comment]
@harkiratsm Could you please update the branch?

**Comment by harkiratsm** [comment]
@leecalcote

**Comment by leecalcote** [comment]
Updated. Golang lint issues are being fixed @pk-218

**Pull request merged**
