### PR TITLE
[Meshmodels] - Displaying duplicate components and models

### PR DESCRIPTION
**Pull request by smartdev09**
**Notes for Reviewers**

This PR fixes #

https://github.com/meshery/meshery/assets/31584129/b770b179-f13b-4ffb-8331-f111057955cf

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — CHANGES_REQUESTED** [review]
Docker image  build failure...

**Comment by leecalcote** [comment]
@UsmanDev09 eslint issues - https://github.com/meshery/meshery/actions/runs/5657998083/job/15328325645?pr=8275#step:3:36

**Comment by leecalcote** [comment]
> @UsmanDev09 eslint issues - https://github.com/meshery/meshery/actions/runs/5657998083/job/15328325645?pr=8275#step:3:36

**Comment by UsmanDev09** [comment]
@MUzairS15 I have handled the large json file issue as follows: 

https://github.com/meshery/meshery/assets/31584129/ed1f766b-dc6a-4c42-a8e0-1a70e690a918

I have also handled the empty additional option edge case.

**Pull request merged**
