### PR TITLE
Created and Added new SVGs

### PR DESCRIPTION
**Pull request by Harshit-Dandriyal**
Signed-off-by: Harshit Dandriyal <56961488+Harshit-Dandriyal@users.noreply.github.com>

**Description**
Created and Added new SVGs.

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — CHANGES_REQUESTED** [review]
Inconsistent margins.

Shape and icon need to be kept separate.

**Comment by leecalcote** [comment]
@Harshit-Dandriyal is this still needed?

**Comment by Harshit-Dandriyal** [comment]
Yes, It should be merged first I mean but yes some nodes are unnecessary here, Removing..

**Review by Abhishek-kumar09 — APPROVED** [review]

**Comment by Abhishek-kumar09** [comment]
// @leecalcote Any padding changes you see or require to see here?

**Pull request merged**
