### PR TITLE
Added operator-light

### PR DESCRIPTION
**Pull request by Harshit-Dandriyal**
Signed-off-by: Harshit Dandriyal <56961488+Harshit-Dandriyal@users.noreply.github.com>

**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Abhishek-kumar09** [comment]
The source blob I am seeing, is totally unoptimized. These svgs are not something to be coded on, so don't prettify it. Adding tabs and spaces and indenetations make it bigger. 
Your svg file: https://github.com/meshery/meshery/blob/6a86f4fc1e19dfb835808e6ae22a32e7d842789c/ui/public/static/img/component-svg/operator-light.svg?short_path=2c5daa4

Please download as is from figma. 

Additionally, all svgs should have: `<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE svg>` as their header. See what cytoscape suggests: https://js.cytoscape.org/#style/background-image

**Comment by Harshit-Dandriyal** [comment]
@Abhishek-kumar09 Sorry, it was meshery-operator.js being used not operator.js, We can merge this now.

**Comment by Harshit-Dandriyal** [comment]
> The source blob I am seeing, is totally unoptimized. These svgs are not something to be coded on, so don't prettify it. Adding tabs and spaces and indenetations make it bigger. Your svg file: https://github.com/meshery/meshery/blob/6a86f4fc1e19dfb835808e6ae22a32e7d842789c/ui/public/static/img/component-svg/operator-light.svg?short_path=2c5daa4
> 
> Please download as is from figma.
> 
> Additionally, all svgs should have: `<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE svg>` as their header. See what cytoscape suggests: https://js.cytoscape.org/#style/background-image

on it..

**Comment by Harshit-Dandriyal** [comment]
@Abhishek-kumar09 done.

**Comment by Abhishek-kumar09** [comment]
Thank You @Harshit-Dandriyal

**Review by Abhishek-kumar09 — APPROVED** [review]

**Pull request merged**
