### PR TITLE
[UI] Add Sidebar Peek for Notification Center

### LINKED ISSUE #6683: [UI] Add Sidebar Peek on hover of Notification Center bell
### Current Behavior
Global menu controls are too subtle, not interactive enough.

### Desired Behavior
1) **K8s context switcher**
Increase the range of the downward peek effect.

2) **Notification Center Sidebar** 
Add an on hover effect to have the Notification Center sidebar peek out from the right edge of the screen when the bell icon is hovered over, behaving the same way as the hover effect for the k8s context switcher.

### Implementation
1. k8s context switcher: translateY(1.25rem)
1. Notification Center sidebar: same distance as the k8s context switcher, but sliding horizontally, not vertically. 

### Mockups
See screen recording below.

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by theBeginner86**
**Notes for Reviewers**

This PR:
- [x] Adds sidebar peek for notification center
- [x] Increases the peek transform for the context switcher
- [x] Fixes bug for undefined notification count badge (notification tooltip shows `undefined events` when event.length is undefined on Meshery startup)

This PR fixes #6683

https://user-images.githubusercontent.com/73700530/208294148-d67d4e09-359f-4fec-9220-68d9f4995452.mov

before:

Screenshot 2022-12-18 at 4 17 05 PM

after:

Screenshot 2022-12-18 at 4 16 40 PM

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
@partik03 you might want to review.


@theBeginner86 thanks for this. We'll have to make the k8s context switcher peek down only as far as until the first K8s context would start to show. Otherwise, users will think that the menu is buggy (that it should be fully displayed, but gets stuck halfway). 

Screenshot 2022-12-18 at 9 13 53 AM


In a similar way, so too should the Notification Center only peek outward up to about halfway through the bell icon inside the sidebar.


Screenshot 2022-12-18 at 9 16 41 AM

**Comment by leecalcote** [comment]
Thank you for taking care of the `undefined` bug, too. This is great, @theBeginner86

**Comment by theBeginner86** [comment]
Update:

https://user-images.githubusercontent.com/73700530/208321708-6532d487-9a62-4da2-94a8-bff8c9776ce4.mov

**Comment by leecalcote** [comment]
Nice!

**Pull request merged**
