### PR TITLE
Prerequisite added for testing Go code. #Issue 2588

### PR DESCRIPTION
**Pull request by sakshi3537**
**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Good stuff, @sakshi3537. Will you give the git commands a quick run? - https://github.com/layer5io/meshery/pull/2721/checks?check_run_id=2369473494

**Comment by sakshi3537** [comment]
Hey @leecalcote I tried running those git commands and the commits are signed off but it says "This commit does not belong to any branch on this repository". Can you please help me with resolving this?

**Comment by leecalcote** [comment]
@sakshi3537, yeah, that is a bit of a head-scratcher. Hmm. I have manually flagged this check as passing considering your attempts and comment above. Good to go now. 👍

**Comment by Nikhil-Ladha** [comment]
> Hey @leecalcote I tried running those git commands and the commits are signed off but it says "This commit does not belong to any branch on this repository". Can you please help me with resolving this?

Ohh, you need not worry about that. Because, this was to only update the signoff and it doesn't does any code changes. Moreover, I think it happens because of amend.

**Comment by leecalcote** [comment]
Your help here is much appreciated, @sakshi3537. If you've not already joined the community Slack (http://slack.layer5.io) or completed a member form (https://layer5.io/newcomer), I encourage you to do so. There's a collection of warm and welcoming open source contributors inside.

**Review by leecalcote — APPROVED** [review]

**Pull request merged**
