### PR TITLE
Fixing the Broken image of Meshery Architecture in README

### LINKED ISSUE #1645: [Docs] README: Broken image of Meshery Architecture
**Current State:**
Diagrams of Meshery's architecture were recently updated. This caused a broken link in the [architecture section of the main README](https://github.com/layer5io/meshery#meshery-architecture)

**Screenshot:**
Screen Shot 2020-10-04 at 8 50 10 PM

**Desired State:**
1. This image may be used to show Meshery's architecture - https://github.com/layer5io/meshery/blob/master/docs/assets/img/architecture/Meshery-client-architecture.svg
1. This image should be copied to the `docs/assets/img/readme` folder, so as to avoid having it broken again.

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

### PR DESCRIPTION
**Pull request by spielers**
**Description**

This PR fixes #1645 

**Notes for Reviewers**
This PR will Fix the Broken image of Mystery Architecture. I have added the SVG according to the description of the issue.

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by spielers** [comment]
OK I got it ill sign it 👍

**Comment by spielers** [comment]
Guy, does anyone help regarding the failing check I am not getting it where it gonna wrong :(

**Comment by leecalcote** [comment]
@spielers it looks like your DCO (commit sign-off) is good to go. This other failed check stems from a prior pull request. You're all set here with respect to build checks.

**Review by leecalcote — APPROVED** [review]
Beautiful. Thanks for this @spielers. 👍

**Comment by leecalcote** [comment]
Awesome, @spielers 🎈

**Comment by spielers** [comment]
@leecalcote thanks for this I would like to receive an invitation for contribution from layer5 (member invitation)

best,
spielers

**Pull request merged**
