### PR TITLE
Changed “pertainting” to “pertaining”

### LINKED ISSUE #8919: [Docs] Typo in Meshery Contributing Guide
### Current State
There's a typo in the paragraph under the Meshery Server APIs subheading on [this page](https://docs.meshery.io/project/contributing/contributing-ui).

Typo in Meshery Contribution guide

### Desired State
"pertainting" should be corrected to "pertaining"

___

### PR DESCRIPTION
**Pull request by nwanduka**
**Notes for Reviewers**

This PR fixes #8919

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 3da6ced81e50b2de1bd7d64648c004afd09b7cdd at: https://651213603ad05803e3f8b9bd--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit bd67a9832945b31debf4503eee5f8c593f4251bb at: https://6512898429d04325c328504c--meshery-docs-preview.netlify.app

**Review by abhijeetgauravm — APPROVED** [review]
LGTM!

**Review by leecalcote — APPROVED** [review]
Good eye, @nwanduka. Thanks much. 👍

**Pull request merged**
