### PR TITLE
[UI] custom table header for selected row

### LINKED ISSUE #4528: [UI] Selected row name change
#### Current Behavior
when selected a row from the table, it appears ()rows selected.

#### Desired Behavior
change that rows selected to configuration type, example: ()pattern(s) selected / ()filter(s) selected .....

#### Implementation
Implement this for patterns, filters, applications, and performance profiles

#### Mockups
issuename

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by theBeginner86**
**Description**
This PR fixes UI by changing the table header with the custom configuration type for selected no of rows.

For:
- application table: (no-of-rows) application(s) selected
- pattern table: (no-of-rows) pattern(s) selected
- filter table: (no-of-rows) filter(s) selected
- performance profile: (no-of-rows) profile(s) selected

This PR fixes #4528

**Notes for Reviewers**

Demo:

- Application Table:

https://user-images.githubusercontent.com/73700530/140497410-9bf83ad5-2095-4424-bc3d-40905b1079cf.mov

- Pattern Table:

https://user-images.githubusercontent.com/73700530/140497486-892ab9b3-e9dd-496c-ab41-bb5e8c307b51.mov

- Filter Table:

https://user-images.githubusercontent.com/73700530/140497518-823f1596-7d3d-4b5d-888b-2958ed81f51a.mov

- Performance Profile table:

https://user-images.githubusercontent.com/73700530/140497561-d7cacacd-777f-4da4-8875-893bad031cd3.mov

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by Chadha93 — APPROVED** [review]
Thanks, @theBeginner86 Good work

**Comment by leecalcote** [comment]
I love seeing these screen recordings. Nice work, @theBeginner86 👍

**Review by leecalcote — APPROVED** [review]

**Comment by leecalcote** [comment]
Yay, @theBeginner86! 🎈

**Comment by theBeginner86** [comment]
Thanks, @leecalcote @Chadha93 😁

**Pull request merged**
