### PR TITLE
Update navigation bar [Docs]

### PR DESCRIPTION
**Pull request by pranav767**
**Notes for Reviewers**

This PR fixes #
Kindly have look at https://github.com/meshery/meshery/pull/6862

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by sassukeuchiha** [comment]
Hey @leecalcote back again with the same pr 😄 
Need to understand git real quick to avoid creating same pr again and again 😞

**Comment by Chadha93** [comment]
@sassukeuchiha  Let's discuss this on the Meshery Dev call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#) if you would. :)

**Comment by Chadha93** [comment]
You can include [Docs] in PR title.

**Comment by sassukeuchiha** [comment]
Done @Chadha93 .
This PR was already discussed in the previous meeting, but I was not able to figure out how to resolve merge conflicts, so I raised another PR. So should I still add my name to our agenda or let it go?

**Review by leecalcote — APPROVED** [review]
Thank you, gents. All clear here. Looks great, @sassukeuchiha.

**Comment by leecalcote** [comment]
Yay! 🎖️

**Comment by sassukeuchiha** [comment]
Thankss a lot @leecalcote 😁

**Pull request merged**
