### PR TITLE
[Docs] Styling of Docs overview page

### PR DESCRIPTION
**Pull request by leecalcote**
Signed-off-by: leecalcote <leecalcote@gmail.com>

**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 6291c688173a1ae949da3d064dd9cafdde426fa5 at: https://61d0748cbd5723f5882db021--meshery-docs-preview.netlify.app

**Comment by warunicorn19** [comment]
Is this the look you were going for? 
Screenshot 2022-01-01 at 10 43 32 AM

**Comment by leecalcote** [comment]
Essentially:

- vertically-slimmed down category heading (green buttons)
- horizontally-same size category heading
- switch to horizontal logo

**Comment by warunicorn19** [comment]
@leecalcote we can close this now, right?

**Comment by leecalcote** [comment]
@warunicorn19 no. Let's treat them separately.

**Pull request merged**
