### PR TITLE
[UI] Add Connection Stats Chart

### LINKED ISSUE #8161: [UI] Create A Donut Chart To Visualise Connections Data  In Dashboard.
#### Current Behavior
In the Dashboard we are not currently showing any information about the connections . 

#### Desired Behavior
It is desired to enhance the Dashboard by adding charts that display information about the connections, including their state and count.

#### Implementation
Develop a new chart component specifically designed to represent the count of connections in different states. This chart will provide a visual representation of the distribution of connections based on their states.

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by aabidsofi19**
**Notes for Reviewers**
- The data used is dummy 

This PR fixes #8161 #8406

image
image

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
@abdullah1308 you'll be providing the data source. Message when the status fields of connections is available.

**Comment by vishalvivekm** [comment]
@aabidsofi19 Let's discuss this on Meshery Dev call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#) if you would. :)

**Comment by aabidsofi19** [comment]
Latest changes :
- Hooked to Api 
- Fixed the legend 
image

**Comment by aabidsofi19** [comment]
@leecalcote  is this good to be merged

**Comment by leecalcote** [comment]
Look like real data. ✅

**Pull request merged**
