### PR TITLE
[Design Configurator] Create design configurator with MeshModel support

### PR DESCRIPTION
**Pull request by Abhishek-kumar09**
**Notes for Reviewers**
Demo: https://youtu.be/B65tuzyjxic
This PR fixes #

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — COMMENTED** [review]
Abhi, did you say that this new page is not linked from the menu... yet?

The page title seems to be missing...

**Comment by leecalcote** [comment]
@Abhishek-kumar09 I can't save or delete in card view, but can do so in table view. 
Screenshot 2023-04-20 at 3 14 58 PM
Screenshot 2023-04-20 at 3 14 48 PM

**Comment by leecalcote** [comment]
@Abhishek-kumar09, yes, there are small items like you mentioned that can be followed up on, but this PR is GTG and gets this feature area working once again.

**Comment by Abhishek-kumar09** [comment]
> @Abhishek-kumar09 I can't save or delete in grid card view, but can do so in table view.
> 
> ## Grid View
> Screenshot 2023-04-20 at 3 14 48 PM
> 
> ## Table View
> Screenshot 2023-04-20 at 3 14 58 PM

@leecalcote This is out of context of my PR, but definitely an issue.

> Abhi, did you say that this new page is not linked from the menu... yet?

Yes, at the time of recording it wasn't linked, but now it is.

> The page title seems to be missing...

Oh, checking that out.

**Pull request merged**
