### PR TITLE
[CI] Disable Cypress e2e tests

### PR DESCRIPTION
**Pull request by leecalcote**
**Notes for Reviewers**

This PR disables Cypress tests, which have proven more trouble than they are worth.

Meshery needs a new e2e testing framework and high confidence test results.

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Freedisch** [comment]
@leecalcote , this is related to this https://github.com/meshery/meshery/issues/8129

I will look into it

**Comment by MarioArriaga92** [comment]
@leecalcote what about removing the faulty tests? 

We can also:
 - disable the default cypress behavior of reporting tests as failed when an unhandled exception is thrown in the browser
 - increase global response timeout and
 - remove waiting on requests in test scripts as API interfaces change too often and our contributors seem to have a have a hard time identifying which tests should be updated **(besides GraphQL subscriptions are async so no test framework seems yo reliably help e2e tests wait for them, instead there should be clear frontend indicators both users and tests should be able to wait on before performing actions against UI components)**

Otherwise, lets disable cypress altogether and I can setup some basic new tests with one of the alternatives we've identified and see how well that runs in our CI processes.

**Comment by leecalcote** [comment]
@MarioArriaga92 I'm up for any of these suggestions. Here's an example PR opened a little earlier - https://github.com/meshery/meshery/actions/runs/5905510108/job/16020097585?pr=8537. 3 out of 4 tests failing. If you think any of these three will address these failures, are worth fixing, and Cypress worth continuing to invest into, we can close this PR.

**Comment by MarioArriaga92** [comment]
@leecalcote those 3 test failures seem unrelated to cypress problem:
```
The request we sent was:

Method: GET
URL: http://localhost:3000/api/provider?provider=None
Headers: {
  "Connection": "keep-alive",
  "user-agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36",
  "accept": "*/*",
  "accept-encoding": "gzip, deflate"
}

-----------------------------------------------------------

The response we got was:

Status: 500 - Internal Server Error
Headers: {
  "content-type": "text/plain",
  "date": "Fri, 18 Aug 2023 18:13:04 GMT",
  "connection": "keep-alive",
  "keep-alive": "timeout=5",
  "transfer-encoding": "chunked"
}
Body: Proxy issue in Meshery-UI
```

For some reason there was an error with the proxy during `GET http://localhost:3000/api/provider?provider=None` request

**Comment by leecalcote** [comment]
@MarioArriaga92, I'll let you address / fix.

**Comment by leecalcote** [comment]
Does Friday work as our deadline for go/no-go decision on removal of Cypress?

**Comment by MarioArriaga92** [comment]
> @leecalcote those 3 test failures seem unrelated to cypress problem:
> 
> ```
> The request we sent was:
> 
> Method: GET
> URL: http://localhost:3000/api/provider?provider=None
> Headers: {
>   "Connection": "keep-alive",
>   "user-agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36",
>   "accept": "*/*",
>   "accept-encoding": "gzip, deflate"
> }
> 
> -----------------------------------------------------------
> 
> The response we got was:
> 
> Status: 500 - Internal Server Error
> Headers: {
>   "content-type": "text/plain",
>   "date": "Fri, 18 Aug 2023 18:13:04 GMT",
>   "connection": "keep-alive",
>   "keep-alive": "timeout=5",
>   "transfer-encoding": "chunked"
> }
> Body: Proxy issue in Meshery-UI
> ```
> 
> For some reason there was an error with the proxy during `GET http://localhost:3000/api/provider?provider=None` request

@leecalcote its clear that the specific error above happened in [/ui/ui_dev_server.js](https://github.com/meshery/meshery/blob/master/ui/ui_dev_server.js)? And if so, should there be a separate issue to track that problem?

Cypress isn't involved in what happens in `npm run start` script, as that script invokes `NODE_ENV=production node ui_dev_server.js` command and for some unknown reason the error in [/ui/ui_dev_server.js#L16](https://github.com/meshery/meshery/blob/master/ui/ui_dev_server.js#L16) is thrown, perhaps due to some next.js or http or http-proxy package bumps that might introduce issues or breaking changes.

**Comment by leecalcote** [comment]
Conflicts resolved. We're coming up on ~another month of false positives.

**Pull request closed without merging**
