### PR TITLE
Notification center consistently opens when clicked

### LINKED ISSUE #6896: [UI] Notification Center: Doesn't always fully open on click
#### Current Behavior
While the Notification Center is to peek out on hover of the Notification Center button (usually a bell, but sometimes can exclamation mark icon), it should always fully open when are use her clicks on the button. In the attached video, you can see that despite being clicked on the sidebar, never fully opens. This behavior might differ (but shouldn't) between when notification messages are present vs when they are not.

#### Desired Behavior
Sidebar open and remain open on click.

#### Screenshots/Logs

https://user-images.githubusercontent.com/7570704/212572486-8a4d9ac8-825e-427a-89be-ef7198d9592b.mov

#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: edge

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by deepakdinesh1123**
Signed-off-by: deepakdinesh1123 <d.deepakdinesh13@gmail.com>

**Notes for Reviewers**

This PR fixes #6896 

The notification center button did not open the notification drawer sometimes as the ClickawayListener listened to the clicks of some elements in the UI and closed the drawer as soon as it was opened. I have modified the onClickAway function in ClickAwayListener to ignore the clicks of these elements 

Result:

[2023-01-17 22-34-25.webm](https://user-images.githubusercontent.com/52698821/212964927-668656d9-8a13-4a44-a00c-2ceb69c53b9b.webm)

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Chadha93** [comment]
@deepakdinesh1123  Let's discuss this on the Meshery Dev call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#) if you would. :)

**Comment by leecalcote** [comment]
Great to see this, @deepakdinesh1123

**Comment by leecalcote** [comment]
@theBeginner86

**Comment by acald-creator** [comment]
Looking now

**Comment by acald-creator** [comment]
Looking at this PR, the modal is still peeking when you hover over the notification bell.

**Comment by deepakdinesh1123** [comment]
@acald-creator The issue did not mention that the peek on hover must be removed, looking at the UI it felt a bit odd to have it (my personal opinion), Should I remove it?

**Comment by leecalcote** [comment]
@ajaysinghpanwar2002 do you have any feedback here?

**Review by leecalcote — APPROVED** [review]

**Pull request merged**
