### PR TITLE
added guide to version docs

### PR DESCRIPTION
**Pull request by warunicorn19**
Signed-off-by: Aditya Chatterjee <speak2adi@gmail.com>

**Description**
Added docs to add support for versioning in docs. 
This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 00980d0240572bf5cb737d9717b8f7177a553daa at: https://61c0c0bb1961e125e8f69ed5--meshery-docs-preview.netlify.app

**Review by leecalcote — COMMENTED** [review]
Do you mind moving this to the https://docs.meshery.io/project/build-and-release page?

**Comment by warunicorn19** [comment]
Sure I'll do that.

**Comment by warunicorn19** [comment]
@leecalcote updated PR.

**Comment by l5io** [comment]
🚀 Preview for commit 9df38f8e9b37717b1328d5d11e0996dea508c5f5 at: https://61c11c071961e188f2f69a1c--meshery-docs-preview.netlify.app

**Comment by leecalcote** [comment]
Thank you, sir.

**Review by leecalcote — APPROVED** [review]

**Pull request merged**
