### PR TITLE
[UI] Convert Index.js and settings.js from class-based component to functional component 

### LINKED ISSUE #8673: [UI] Convert `Index.js` and `settings.js` from class-based component to functional component
### Current Behavior
`Index.js` and `settings.js` are class-based component

### Desired Behavior
`Index.js` and `settings.js` should be a class-based component

### Implementation
Here is a quick blog you can read : [Link](https://www.digitalocean.com/community/tutorials/five-ways-to-convert-react-class-components-to-functional-components-with-react-hooks)

### Mockups

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by ShatilKhan**
**Notes for Reviewers**

This PR fixes #8673 

Files Changed:
- [X] ui/pages/index.js
- [X] ui/pages/settings.js ( in progress)

Description:
This PR converts the above files from class based components to functional React components.

Here's a video of `index.js` working properly:

https://github.com/meshery/meshery/assets/52494840/0c778338-ac8c-49a6-8bef-dc8c3906a3b7

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by Rajdip019** [comment]
Hey @ShatilKhan . The `index.js` looks awesome.  I don't think we need any change here. Keep working on the `settings.js` do let me know if any help is required.

**Comment by Rajdip019** [comment]
Give a update video when the `settings.js` is done @ShatilKhan

**Comment by Ghat0tkach** [comment]
hey @ShatilKhan 

 Let's discuss this on Meshery Dev call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#) if you would. :)

**Comment by ShatilKhan** [comment]
@Rajdip019 Here's the video for `settings.js` 

https://github.com/meshery/meshery/assets/52494840/1fdd1c54-bc19-4c38-bd31-d5ea09b4d211

Also sorry for the delay 😅

And yes @Ghat0tkach I would love to discuss this on the Dev Call tommorow , I'll add it to the agenda!

**Review by Rajdip019 — APPROVED** [review]
LGTM

**Comment by aabidsofi19** [comment]
are any tasks pending

**Comment by Rajdip019** [comment]
> are any tasks pending

I have checked the components from my side. Anything left @ShatilKhan

**Comment by Donhab** [comment]
Am new here, just observing first

**Comment by Rajdip019** [comment]
@aabidsofi19 looks like it is done. We can go ahead and merge this.

**Comment by ShatilKhan** [comment]
Thanks for reviewing guys, if everything seems fine, then go ahead and merge ✨

**Review by sudhanshutech — APPROVED** [review]

**Comment by sudhanshutech** [comment]
@ShatilKhan please ensure to update the description of PR when all changes  are done.
LGTM

**Comment by ShatilKhan** [comment]
> @ShatilKhan please ensure to update the description of PR when all changes are done. LGTM

Done @sudhanshutech!

**Pull request merged**
