### PR TITLE
Update architecture.md to provide right image paths to the respective topic to improvise docs

### LINKED ISSUE #8804: [Docs] Improvement suggestion
### Current State

The file https://github.com/meshery/meshery/blob/master/docs/pages/concepts/architectural/architecture.md
has documentation issues (please correct me if I am wrong), I think the site URLs mentioned in the have not been hyperlinked with the site in markdown format.

### Desired State

Example,

[Client architecture]({{ site.baseurl }}/assets/img/architecture/Meshery-client-architecture.svg)

This link should redirect me to the desired website mentioned but it is not being detected by markdown as a hyperlink.
Please respond to me on this and I will raise a PR on this.

Thank you.

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by ShubhamJagtap2000**
**Notes for Reviewers**

This PR fixes #8804 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 94a593c94ebd2ef24cae50c39ff47692a799bf24 at: https://651919566399a324d530f247--meshery-docs-preview.netlify.app

**Comment by ShubhamJagtap2000** [comment]
> 🚀 Preview for commit [94a593c](https://github.com/meshery/meshery/commit/94a593c94ebd2ef24cae50c39ff47692a799bf24) at: https://651919566399a324d530f247--meshery-docs-preview.netlify.app

Yes, the changes are visible here in `Architecture` tab.

**Comment by saurabh100ni** [comment]
Let's discuss this Item in tomorrow's website call, 
please add it as your agenda if you would: 
https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit

**Comment by saurabh100ni** [comment]
Let's discuss this Item in tomorrow's website call, 
please add it as your agenda if you would: 
https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit

**Comment by ShubhamJagtap2000** [comment]
Hello @saurabh100ni, I am not a part of the org, but an individual contributor to Meshery, and I don't think I have Meshery configured on my system. Would that be within Meshery privacy protocols to attend your org meetings?

**Comment by l5io** [comment]
🚀 Preview for commit ca73138a5be242c81517a60b40d1a6c228c08bcf at: https://6519cb202e43b204b3393b8f--meshery-docs-preview.netlify.app

**Comment by vishalvivekm** [comment]
> Hello @saurabh100ni, I am not a part of the org, but an individual contributor to Meshery, and I don't think I have Meshery configured on my system. Would that be within Meshery privacy protocols to attend your org meetings?

@ShubhamJagtap2000 
Meshery, one of the projects that the Layer5 community stewards, is a community-driven effort.
All are welcome to join the weekly community meetings and present their items ( open PRs/Issues, help-wanted items, UI-UX and the list goes on.)
See you in the websites meeting today at 5:30 PM IST @ShubhamJagtap2000.
Find the meeting details here: https://meet.layer5.io

**Review by vishalvivekm — COMMENTED** [review]
https://github.com/meshery/meshery/issues/8804#issuecomment-1742616617

**Review by leecalcote — CHANGES_REQUESTED** [review]
@ShubhamJagtap2000 thanks for this effort. The image links are broken in this PR.

Screenshot 2023-10-02 at 3 10 51 PM


Let's go ahead and close this PR and find you a new issue to work on as the issue that you have reported isn't an active concern. Thanks for contributing. If you don't find an open issue to work on, please follow up @vishalvivekm and @saurabh100ni's suggestions.

**Pull request closed without merging**
