### PR TITLE
Updated docs site footer with current social buttons

### LINKED ISSUE #394: Update docs site footer with current social buttons
**Enhancement Description**
Update [the current docs footer](https://github.com/layer5io/meshery/blob/master/docs/_includes/footer.html) to use [the same social buttons](https://github.com/layer5io/layer5/blob/master/_includes/partials/hori-social.html) as those used on layer5.io as shown [in this screencast](https://youtu.be/FZ4Mi68CsGM).

### PR DESCRIPTION
**Pull request by gunjanmimo**
fixes #394

### CODE REVIEW

**Comment by leecalcote** [comment]
@gunjanimo would you like to get together with @madhabpaul on this one?

**Comment by leecalcote** [comment]
@gunjanimo would you like to get together with @madhabpaul on this one?

**Comment by gunjanmimo** [comment]
yes @leecalcote sir, I need some help in this issue and due to my upcoming semester exam, I cant focus on issues.

**Comment by leecalcote** [comment]
@gunjanmimo thanks for highlighting your exam. The exam _**must**_ take priority. No sweat - we'll get some help here. Either I will or @madhabpaul, @Nikhil-Ladha, or @subhamkrai will jump in to assist on this one.

**Comment by leecalcote** [comment]
Gents, a quick reminder to take another look at this PR...

**Comment by leecalcote** [comment]
Thanks for this @gunjanmimo. We're good to close here given the updates in #568.

**Pull request closed without merging**
