### PR TITLE
Made error message more user friendly

### PR DESCRIPTION
**Pull request by ujju20**
**Notes for Reviewers**

- In this PR I have made some complex to understand errors easy to read for users.
- Also, Capitalizes first letter of first word of error message where it was applicable.

This PR fixes #6794 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by alphaX86** [comment]
@ujju20 I believe a similar one is already being worked on via PR #6781 do have a look

Maybe you can try working on fixing other messages other than the JSON Unmarshalling error message so that it won't conflict with that PR

**Comment by alphaX86** [comment]
Oh and, sign-off your commits to fix DCO error. Refer this check log for steps, https://github.com/meshery/meshery/pull/6816/checks

**Comment by ujju20** [comment]
> @ujju20 I believe a similar one is already being worked on via PR #6781 do have a look
> 
> Maybe you can try working on fixing other messages other than the JSON Unmarshalling error message so that it won't conflict with that PR

OK sure

**Comment by Chadha93** [comment]
@ujju20  Let's discuss the update of this PR on the Meshery Dev call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#) if you would. :)

**Pull request closed without merging**
