### PR TITLE
[UI]: Refactors meshery docs footer to match with Layer5 and Meshery websites.

### LINKED ISSUE #4767: [Docs]  Footer modification
#### Current State

Changes required on https://docs.meshery.io/ :
- we don't have layer5 discuss icon in docs footer
- The slack icon needs to be changed.
- the calendar icon doesn't have a hover effect.

#### Desired State

- add the layer5 discuss forum icon in docs footer.
- The slack icon needs to be modified to what we have on the [layer5](https://layer5.io/) website footer. You could checkout [#613](https://github.com/meshery/meshery.io/pull/613) to see how to add a hover effect to the slack icon.
- add a hover effect for the calendar icon.

**If there are still some doubts feel free to comment here or discuss it on slack.**

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by Nik-09**
Signed-off-by: Nik-09 <nikhil.agarwal.2019@gmail.com>

**Description**

This PR fixes #4767 

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 21776d40b27f4f8a6e0a327b515f2f2a75a41183 at: https://61f62cf88861222aaafb07bd--meshery-docs-preview.netlify.app

**Comment by Nik-09** [comment]
@leecalcote Please take a look.
Thank you.

**Comment by l5io** [comment]
🚀 Preview for commit 830866f6aa678d70aab1d788b61516d7f60fcb39 at: https://61f6b1d959dcbf3e2b75f32a--meshery-docs-preview.netlify.app

**Review by adithyaakrishna — APPROVED** [review]
LGTM 🎉

**Comment by adithyaakrishna** [comment]
**Verified Changes:**
image

**Comment by adithyaakrishna** [comment]
Thanks for your contribution @Nik-09 🎉 🚀

**Pull request merged**
