### PR TITLE
Added GraphQL capability using Relay

### PR DESCRIPTION
**Pull request by dhruv0000**
**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
@dhruv0000 will this be ready for demo on Thursday?

**Comment by leecalcote** [comment]
A couple conflicts to address, but nearly ready for review, @dhruv0000 ?

**Comment by dhruv0000** [comment]
Yes. Let's merge this by tonight.

**Review by vineethvanga18 — APPROVED** [review]
LGTM 
Maybe run gofmt on go code for ci checks

**Review by leecalcote — APPROVED** [review]

**Review by leecalcote — CHANGES_REQUESTED** [review]
@dhruv0000 @vineethvanga18 please address the conflicts in this PR.

**Review by leecalcote — CHANGES_REQUESTED** [review]
Need a clean bill of health. :)

Will you address? - https://github.com/layer5io/meshery/pull/2065/checks?check_run_id=1630630058#step:3:68

**Comment by dhruv0000** [comment]
[#2250](https://github.com/layer5io/meshery/pull/2205) and [#2](https://github.com/layer5labs/meshery-extensions/pull/2) in meshery-extentions makes this PR no longer required.

**Pull request closed without merging**
