### PR TITLE
modified README.md for implementation of light/dark mode logos

### LINKED ISSUE #5550: [Docs] Improve visibility in readme files by setting logos according to light/dark mode
#### Current State
In current state some logos have low contrast in either light or dark mode which makes it difficult to read.

#### Desired State
Change the logos according to light/dark mode by using #gh-light-only or #gh- dark-only-method

---

#### [Contributor Guides](https://docs.meshery.io/project/contributing) and Resources
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by krisharyan**
Signed-off-by: KrishAryan <krisharyan.36@gmail.com>

**Description**Need links of logos so that different logos can be set during light and dark mode to improve document readability.

This PR fixes #5550 

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by KrishAryan** [comment]
need links like-https://raw.githubusercontent.com/meshery/meshery/master/.github/assets/images/meshery/meshery-logo-tag-light-text-side.png

**Comment by KrishAryan** [comment]
Readme preview:
screenshot (51)
screenshot (52)
screenshot (53)
screenshot (54)

**Comment by KrishAryan** [comment]
All links are working too

**Comment by l5io** [comment]
🚀 Preview for commit c19264193da7ea5ae713b2eca346b8fcbf3037b1 at: https://6295be09ef6ded0706f674d6--meshery-docs-preview.netlify.app

**Comment by KrishAryan** [comment]
All changes done please merge so this because I need this pr to be merged so that I can implement this feature in other layer5 projects

**Review by leecalcote — APPROVED** [review]
LGTM

**Pull request merged**
