### PR TITLE
Modify `Default` to `default` in token

### PR DESCRIPTION
**Pull request by alphaX86**
**Notes for Reviewers**

This PR fixes #

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit d7770b322e07a627ba09e9a0d67450e4f2bb2fba at: https://6408ba258f58c963a886d9a0--meshery-docs-preview.netlify.app

**Review by leecalcote — APPROVED** [review]
Thank you, @alphaX86. It takes an impressive number of changes for a small change like this. :)

**Comment by leecalcote** [comment]
Which is why I requested that you do it, so that it would be done correctly.

**Review by leecalcote — APPROVED** [review]
Good

**Pull request merged**
