### PR TITLE
Added MeshSync Chip, Snackbar and Toolbar

### LINKED ISSUE #3576: [Server] MeshSync Lifecycle: Ad-hoc connectivity test
**Current Behavior**
Once Meshery Operator, and subsequently, MeshSync is deployed, users will inevitably be in need of verifying connectivity to MeshSync in Settings and Connection Wizard.

Like other Meshery-connected components, users need the ability to verify connectivity to that component.

**Desired Behavior**
In the same fashion that users are allowed to perform ad-hoc connectivity tests to the Kubernetes and service mesh chips, users should be allowed to perform ad-hoc connectivity tests to verify Meshery's point-in-time ability to interact with MeshSync (therein retrieving MeshSync component details: version, health).

**Acceptance Criteria**
This enhancement is complete when:
- [x] Users are able to invoke an ad-hoc connectivity test with MeshSync.
- [ ] Connectivity test retrieves MeshSync version for display in a tooltip when the user hovers the mouse over the chip.
- [ ] Connectivity tests display either a success message: "MeshSync successfully pinged!" or a failure message: "Could not connect to MeshSync."

---

**Future**
- [ ] Users should be able to invoke an ad-hoc connectivity test with *each* connected MeshSync instance.

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

### PR DESCRIPTION
**Pull request by meghanacosmos**
**Description**
Added MeshSync chip, and Snackbar that shows if the ping was successful and a Tooltip that shows the version of MeshSync

This PR fixes #3576 

**Notes for Reviewers**
My VSCode prettier settings caused a lot of changes, I hope that's okay. The mains changes added are function `handleMeshSyncClick` on line 523 and `Chip` for `MeshSync` ( and `Toolbar` wrapping the `Chip`) line 734. 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Meghana-12** [comment]
I think there'll be 2 fail cases (one when we aren't able to fetch operator status and one when meshsync is disabled, I guess), so I've kept the error messages similar to the ones of the Operator. Please let me know what the error messages should be.

**Comment by leecalcote** [comment]
@meshery/meshery-ui-maintainers, @Tanuj22, @sudo-NithishKarthik, regarding VS-Prettier settings...  do we have any pre-commit hooks, common lint configurations that will help enforce consistency?

**Comment by sudo-NithishKarthik** [comment]
As of now, we don't have any pre-commit hooks for `meshery-ui`
`.eslintrc` is the lint configuration file which we use to enforce consistency.
Yes, we can add quotation rules and other configurations to make it more consistent.

Currently, lint check runs on running `npm run dev`. Since we use that command in `UI Integration tests`, it would fail if there are any lint errors. But it would be better to have a pre-commit hook.

**Review by sudo-NithishKarthik — CHANGES_REQUESTED** [review]
Good work @Meghana-12  🎉 

Screenshot 2021-07-31 at 1 34 33 PM


Can you add some spacing between two chips ?
Making them aligned with their respective column would be more appealing

**Comment by leecalcote** [comment]
Good feedback, @sudo-NithishKarthik.

It's so 😎  to see this come through, @Meghana-12.

**Comment by adithyaakrishna** [comment]
@Meghana-12 Could you please check the DCO issue here at, https://github.com/meshery/meshery/pull/3698/checks?check_run_id=3215143818

**Comment by Meghana-12** [comment]
> https://github.com/meshery/meshery/pull/3698/checks?check_run_id=3215143818

Ahh, so sorry about that! I'll fix it right away.

**Comment by adithyaakrishna** [comment]
@sudo-NithishKarthik I was just thinking along with the Disabled text, how about if we have a Green or Red Status Dot?
Just flashed my mind, this can improve the UX as well. So a person can see the status dot directly 👀

**Comment by leecalcote** [comment]
Regarding MeshMate @adithyaakrishna's suggestions: these are good things to explore. In the meantime, here comes @Meghana-12's new MeshSync chip! 🥳

**Review by leecalcote — APPROVED** [review]

**Comment by adithyaakrishna** [comment]
Yayyyy @Meghana-12 🎉

**Pull request merged**
