### PR TITLE
[mesheryctl]: Change cleanup -> reset command

### LINKED ISSUE #855: Move mesheryctl cleanup -> mesheryctl reset
**Current Behavior**
mesheryctl cleanup is the command to remove old meshery.yml file with default one.

**Desired Behavior**
A renaming of  `mesheryctl cleanup` to `mesheryctl reset` as the name of the command.
so that `mesheryctl reset` should be  the command to remove current meshery.yml file with default meshery.yml.

### PR DESCRIPTION
**Pull request by Nikhil-Ladha**
Signed-off-by: Nikhil-Ladha <nikhilladha1999@gmail.com>

#### Description

This PR fixes #855  
#### Checklist

- [x] [Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin) signed.
- [x] PR includes `[<name of area>]`

### CODE REVIEW

**Comment by Nikhil-Ladha** [comment]
Hopefully, it did set a new land speed record :1st_place_medal:

**Comment by leecalcote** [comment]
Holy smokes. I think you did, because I didn't see you whiz by. 😜

**Comment by Nikhil-Ladha** [comment]
> Holy smokes. I think you did, because I didn't see you whiz by.

Haha, Thanks 😁

**Comment by leecalcote** [comment]
✔️ `mesheryctl system start --reset`
✔️ `mesheryctl system reset`
✔️ no more references to `cleanup`.
✔️ documentation updated.

**Comment by Nikhil-Ladha** [comment]
>  `mesheryctl system start --reset`
>  `mesheryctl system reset`
>  no more references to `cleanup`.
>  documentation updated.

Made a search of cleanup and replaced it with reset 😅. Simple 😁

**Comment by leecalcote** [comment]
Not seeing any other review comments, I'll move forward with merge.

**Pull request merged**
