### PR TITLE
[UI] Filter UI - Functionality Add + RJSF 

### PR DESCRIPTION
**Pull request by Chadha93**
Signed-off-by: Gaurav Chadha <gauravchadha1676@gmail.com>

**Description**
Issue - Functionality Add + allow user to config filters

**[Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Just a quick check-is this ready for review?

**Comment by Chadha93** [comment]
> Just a quick check-is this ready for review?

Nope, not at all 😅 will push changes by weekend

**Comment by Chadha93** [comment]
@leecalcote will push more changes after demoing this on the WASM call today.

**Comment by leecalcote** [comment]
WASM Filters call tomorrow.... could be a good time to review.

**Comment by leecalcote** [comment]
Hmm. https://github.com/meshery/meshery/pull/3201/checks?check_run_id=3047256655#step:5:47

Screen Shot 2021-07-14 at 6 11 08 PM

**Review by leecalcote — APPROVED** [review]

**Comment by leecalcote** [comment]
@Chadha93 do you know why this is failing? If not, will you create an agenda item for this week's CI meeting?

**Comment by Chadha93** [comment]
> @Chadha93 do you know why this is failing? If not, will you create an agenda item for this week's CI meeting?

@leecalcote Yepp I know, this is failing because the value "setOpenPopup" is the value that I would have used with a component, but didn't use for now. no issues with this UI Integration test.

**Comment by dhruv0000** [comment]
> > @Chadha93 do you know why this is failing? If not, will you create an agenda item for this week's CI meeting?
> 
> @leecalcote Yepp I know, this is failing because the value "setOpenPopup" is the value that I would have used with a component, but didn't use for now. no issues with this UI Integration test.

@Chadha93 Any updates? We can remove `setOpenPopup` from the `Popup` component for now. You can add it in the later PR where you have used it.

**Comment by Chadha93** [comment]
> > > @Chadha93 do you know why this is failing? If not, will you create an agenda item for this week's CI meeting?
> > 
> > 
> > @leecalcote Yepp I know, this is failing because the value "setOpenPopup" is the value that I would have used with a component, but didn't use for now. no issues with this UI Integration test.
> 
> @Chadha93 Any updates? We can remove `setOpenPopup` from the `Popup` component for now. You can add it in the later PR where you have used it.

@dhruv0000 I have kept this on hold because this functionality is also using RJSF and it's only showing the configuration for the filter but not having the full functionality.

**Pull request closed without merging**
