### PR TITLE
[Doc] Extensibility CASL

### LINKED ISSUE #9882: [Docs] Extensibility: CASL
### Desired State

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by Yashsharma1911**
**Notes for Reviewers**

This PR fixes #9882 

This document details the integration of CASL with Meshery for UI authorization.

Note: It does not include information on how contributors can contribute; that content will be provided on a separate page.

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit fc1ade3cc0c3eb4e38197e8625beeba155bba61c at: https://659d5ea596fa9f08de7aab12--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 86ed6b96a3d7071f90dc7b648d94930083b883b6 at: https://65a0b115191d1472cc82134a--meshery-docs-preview.netlify.app

**Comment by leecalcote** [comment]
Rewritten

**Comment by Yashsharma1911** [comment]
> Rewritten

Thankyou Lee

**Pull request merged**
