### PR TITLE
Updated the favicon of Meshery Docs w/signoff

### LINKED ISSUE #3125: [Docs] Favicon on docs.meshery.io should be of Meshery logo
#### Current State
The favicon on docs.meshery. io is not of the Meshery logo currently.

#### Desired State
Use Meshery logo from https://layer5.io/brand

---

#### Contributor Resources

- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
- [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by debjani1413**
Signed-off-by: debjani1413 <deydebjani916@gmail.com>

**Description**
The favicon on docs.meshery.io was not of the Meshery logo.

This PR fixes #3125 
The favicon on docs.meshery.io is changed to the Meshery logo from the mentioned brand kit.

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — CHANGES_REQUESTED** [review]
Thank you, @debjani1413. We should really give consideration to the remainder of the images for other user agents as well - https://github.com/layer5io/meshery/tree/master/docs/assets/favicons. 

The image in this PR looks somewhat blurred. I wonder if we can improve this.

**Comment by debjani1413** [comment]
Hey, @leecalcote I'll be changing the other images as well for other users, but not sure f the blurriness cause if I increase the pixel size of the logo the image won't appear, I've tried that, nonetheless will try that again, let's see .

**Comment by debjani1413** [comment]
@leecalcote I have updated the changes please let me know if I need to do any other changes...

**Review by leecalcote — APPROVED** [review]
Looking good, @debjani1413!

**Pull request merged**
