### PR TITLE
[Docs] Add doc for --verbose flag

### PR DESCRIPTION
**Pull request by pottekkat**
Signed-off-by: navendu-pottekkat <navendupottekkat@gmail.com>

**Description**

Added documentation for the newly added `--verbose` flag. Please refer this PR #2299 and Issue #2295 

This change is made in the https://docs.meshery.io/reference/mesheryctl page and under the "Global Commands and Flags" section.

- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
In terms of usage, I wonder if this isn’t a slightly better example: `mesheryctl <command> --verbose`, so that uses don’t think this only works for system commands.

not a big deal. It is under the global flags section.

**Comment by navendu-pottekkat** [comment]
> In terms of usage, I wonder if this isn’t a slightly better example: `mesheryctl <command> --verbose`, so that uses don’t think this only works for system commands.
> 
> not a big deal. It is under the global flags section.

Yes it is. I will change it

**Comment by navendu-pottekkat** [comment]
@leecalcote Made the changes. Can merge now...

**Review by leecalcote — APPROVED** [review]
Good work, @navendu-pottekkat. 👍 

I tossed in a short description of the command categories.

**Pull request merged**
