### PR TITLE
[mesheryctl] App subcommand list and view dysfunctional

### LINKED ISSUE #8091: [mesheryctl] App subcommand list and view dysfunctional
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior

image

#### Desired Behavior

If the token gets expired it should prompt user to perform login via `mesheryctl system login`
#### Environment

- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- 📺 [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- ⌨️ [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- ⌨️ [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by suhail34**
**Notes for Reviewers**

This PR fixes #8091

In this PR i have jwt token check for app subcommand wherever needed

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by harkiratsm** [comment]
Could you check if this is also happening with other commands?

**Comment by suhail34** [comment]
> Could you check if this is also happening with other commands?

yes it is an issue with other subcommands too

**Review by harkiratsm — COMMENTED** [review]
Do you plan to do the remaining subcommands in the same PR or in a different one ?

**Comment by suhail34** [comment]
I think in a different one as there will be lot of files

**Review by abdullah1308 — APPROVED** [review]

**Pull request merged**
