### PR TITLE
Fix search in MeshModel

### PR DESCRIPTION
**Pull request by Revolyssup**
**Notes for Reviewers**

This PR fixes #
1. Search in MeshModel 
2. Upgrades Meshkit which contains some fix for MeshSync status

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — CHANGES_REQUESTED** [review]
Please enhance API docs to include this behavior change and example(s).

**Comment by leecalcote** [comment]
Merge conflicts

**Comment by leecalcote** [comment]
Circling back on the merge conflicts, which still exist, @Revolyssup

**Comment by leecalcote** [comment]
There was a separate PR recently merged on this topic, I believe. What would you like to do with this PR, @Revolyssup?

**Comment by Revolyssup** [comment]
> There was a separate PR recently merged on this topic, I believe. What would you like to do with this PR, @Revolyssup?

This PR is obsolete now.

**Pull request closed without merging**
