### PR TITLE
docs(roadmap): add an entry for meshery v0.5.0

### LINKED ISSUE #2730: [Docs][roadmap] Docs: Update meshery section for v0.5.0
**Current State:**

**Desired State:**

---
**Contributor Resources**
- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

### PR DESCRIPTION
**Pull request by bnbjin**
resolves #2730

Signed-off-by: michaelhe <hejinyuan1993@gmail.com>

**Description**

This PR fixes #2730 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [Yes] Yes, I signed my commits.

### CODE REVIEW

**Comment by bnbjin** [comment]
@Aisuko plz review :)

**Review by Aisuko — APPROVED** [review]
LGTM

**Comment by Aisuko** [comment]
@bnbjin Thanks

**Comment by leecalcote** [comment]
Yay, @bnbjin!🎈

**Pull request merged**
