### PR TITLE
Update perf docs: instructions to download token and update action configuration

### LINKED ISSUE #4280: [Docs] Broken Image Links
#### Current State
Images are broken on this page - https://docs.meshery.io/functionality/performance-management

Screen Shot 2021-09-30 at 9 32 48 AM

#### Desired State
Images should be displayed.

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by pottekkat**
Signed-off-by: Navendu Pottekkat <navendupottekkat@gmail.com>

**Description**

Fixes #4280

This PR updates the [Performance Management with Meshery](https://docs.meshery.io/guides/performance-management) docs.

1. Adds instructions on downloading the token
2. Updates the sample action configuration file

These changes are reflected here [/guides/performance-management#running-performance-benchmarks-in-your-pipelines](https://61561e8f7d57010902209b5b--meshery-docs-preview.netlify.app/guides/performance-management#running-performance-benchmarks-in-your-pipelines)

- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by navendu-pottekkat** [comment]
Related change: https://github.com/layer5io/meshery-smp-action/pull/10

**Comment by l5io** [comment]
🚀 Preview for commit 47e03dcf46a284eb847f4f85d99583963468f0b5 at: https://61561e8f7d57010902209b5b--meshery-docs-preview.netlify.app

**Comment by leecalcote** [comment]
Using a generic reference to a service mesh, not a specific mesh is ideal

**Comment by navendu-pottekkat** [comment]
In the example? I thought it would be a concrete, ready to copy-paste example. Like we do with other examples in Meshery docs.

**Comment by navendu-pottekkat** [comment]
Oh, `istio-soak-test ` to `soak-test` right?

**Comment by l5io** [comment]
🚀 Preview for commit d29daa333c3fb35693a8376cbd781c7211eae23a at: https://615627e0c71cb81789c2736a--meshery-docs-preview.netlify.app

**Comment by adithyaakrishna** [comment]
@navendu-pottekkat These Images are not loading in the perf-management page [This Link](https://615627e0c71cb81789c2736a--meshery-docs-preview.netlify.app/functionality/performance-management)

Can you please fix that as well along with this PR?

SS:
Screenshot 2021-10-01 at 9 29 01 AM

**Review by adithyaakrishna — CHANGES_REQUESTED** [review]
LGTM 🎉 
Could you please make the above changes regarding the images and once done, I'll go ahead and merge this

**Comment by navendu-pottekkat** [comment]
@adithyaakrishna This should fix it. I had accidentally removed these images in an previous PR thinking it wasn't being used. Thank you for pointing this out.

**Comment by l5io** [comment]
🚀 Preview for commit c81be3b09462e5babf0f80c3c15b1722fa16f367 at: https://6156a9b1f03aa9818b5e6c84--meshery-docs-preview.netlify.app

**Comment by navendu-pottekkat** [comment]
@warunicorn19 Done.

**Review by adithyaakrishna — APPROVED** [review]
LGTM 🎈

**Pull request merged**
