### PR TITLE
run error util for mesheryctl error codes replacement

### PR DESCRIPTION
**Pull request by MUzairS15**
**Notes for Reviewers**

This PR adds a make target `error-util` for mesheryctl to run meshkit error utility for error code replacement. 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by MUzairS15** [comment]
// @Chadha93 @leecalcote

**Comment by MUzairS15** [comment]
@Philip-21 You need to look at duplicate error codes, I believe. https://github.com/meshery/meshery/actions/runs/6250971194/job/16971021729?pr=8846

**Review by leecalcote — APPROVED** [review]
LGTM

**Review by alphaX86 — APPROVED** [review]
LGTM

**Comment by Philip-21** [comment]
> @Philip-21 You need to look at duplicate error codes, I believe. https://github.com/meshery/meshery/actions/runs/6250971194/job/16971021729?pr=8846

I'll fix it @MUzairS15

**Pull request merged**
