### PR TITLE
[Bug] Fix undefined e.text()

### PR DESCRIPTION
**Pull request by theBeginner86**
Signed-off-by: Pranav Singh <pranavsingh02@hotmail.com>

**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Review by MUzairS15 — COMMENTED** [review]
This will again bring back false positive mesasges

**Review by Chadha93 — COMMENTED** [review]
Since this change is made in data-fetch do test importing in apps and other configurations.

**Comment by leecalcote** [comment]
Any findings to report here?

**Comment by MUzairS15** [comment]
```
else {
        throw res.text()
      }

    }).then(successFn)
    .catch((e) => e.then(text => errorFn(text)));
```
@theBeginner86 This should work

**Comment by theBeginner86** [comment]
This PR is ready to merge.

**Review by Chadha93 — APPROVED** [review]

**Comment by theBeginner86** [comment]
There is a second part to this problem.
Solved at: https://github.com/layer5labs/meshery-extensions/pull/1028

**Review by MUzairS15 — APPROVED** [review]

**Comment by Chadha93** [comment]
Restarting the UI integration test. Let's merge after that.

**Review by leecalcote — APPROVED** [review]

**Comment by Chadha93** [comment]
@Abhishek-kumar09 Could you please view the failing tests here?

**Comment by leecalcote** [comment]
Re-running tests

**Comment by leecalcote** [comment]
Tests still failing.

**Comment by Chadha93** [comment]
This Pr is covered in https://github.com/meshery/meshery/pull/5775/files#diff-e3ca1dcbd0ffec5939a4dbceb7c0c562b0da834b91b4d3c72a2e09db9eab6478, since it's a sync issue. We can close this one. // @theBeginner86

**Comment by theBeginner86** [comment]
> This Pr is covered in https://github.com/meshery/meshery/pull/5775/files#diff-e3ca1dcbd0ffec5939a4dbceb7c0c562b0da834b91b4d3c72a2e09db9eab6478, since it's a sync issue. We can close this one. // @theBeginner86

Thanks @Chadha93.

**Comment by theBeginner86** [comment]
Closing this PR

**Pull request closed without merging**
