### PR TITLE
Getting the aks quick start page, translation to es in the docs/pages…

### PR DESCRIPTION
**Pull request by alonsolopezr**
…/es/installation folder

Signed-off-by: JOSE ALONSO LOPEZ ROMO <alonso.lopez.r@gmail.com>

**Description**

This PR fixes #

**Notes for Reviewers**
@jesuslerma tagged for review. Thanks man...

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by jesuslerma** [comment]
The translation LGTM. Anyway @leecalcote  it looks that there is another changed file, that change is not critical. But please check it to give @alonsolopezr their second PR merged :) This is the other changed file in the PR:
docs/_data/toc.yml

**Review by jesuslerma — APPROVED** [review]

**Comment by leecalcote** [comment]
@alonsolopezr when you get an extra file or two in your PRs, that typically means that your fork is out of sync and that you'll need to update it with the remote origin (upstream).

**Comment by alonsolopezr** [comment]
I have noticed this just yesterday.... but I do this fetch from upstream on master always, whenever I'm starting a new translate, and then the merge then the new branch (Jesus Lerma instructed that very well)... but I'm 'git add .' So I think this is my main mistake... I will just be adding only the files changed by me.... greetings and Have a great weekend

**Comment by leecalcote** [comment]
@alonsolopezr you're doing great. This is a very common issue that many people (including me) run into. 😄  Here is a set of instructions that will help - https://github.com/layer5io/meshery/blob/master/CONTRIBUTING-gitflow.md

**Review by leecalcote — APPROVED** [review]

**Pull request merged**
