### PR TITLE
Relationship data table include

### PR DESCRIPTION
**Pull request by iArchitSharma**
image

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 983ed0f798bb01db14239fb8c426fd8af54b7501 at: https://660d56099eac33ea1ed44522--meshery-docs-preview.netlify.app

**Comment by leecalcote** [comment]
What new approach do you have, @iArchitSharma? Show how a summary of stats will be available on each model page.

**Comment by iArchitSharma** [comment]
@leecalcote My approach would be to display the same table on all models page, which will filter out the data from json file relevant to the model

**Comment by l5io** [comment]
🚀 Preview for commit 74c04f447bc063e3aa80a5bf4c4c1e27eac10059 at: https://661131222f17ffd1eec01832--meshery-docs-preview.netlify.app

**Pull request closed without merging**
