### PR TITLE
Amended transcription

### PR DESCRIPTION
**Pull request by ENUMERA8OR**
Amended transcription in various files in docs.
It matches the pull request number  #11347 which was merged days ago.

fixes #11347

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 03ecd494404dbba587932a593f1574e1e2a55d8b at: https://6694b85205661b4410f62342--meshery-docs-preview.netlify.app

**Comment by Ashparshp** [comment]
@ENUMERA8OR Could you please mention the issue number in your pull request description so that it links correctly?

**Comment by l5io** [comment]
🚀 Preview for commit d22f6e6101188bea14327899086e4bd837382af1 at: https://669514c7c84a201a03bed87f--meshery-docs-preview.netlify.app

**Comment by ENUMERA8OR** [comment]
Mentioned

**Review by leecalcote — APPROVED** [review]
Nice! Thank you, @ENUMERA8OR

**Comment by leecalcote** [comment]
I added "fixes #11347" to the PR description so that the issue is auto-closed on PR merge.

**Comment by leecalcote** [comment]
Or... never mind. That wasn't an issue to begin with, but a PR....

**Pull request merged**
