### PR TITLE
Separate CI build test for meshery and provider UI

### LINKED ISSUE #3438: [CI] UI Build test fails to give proper feedback
#### Current Behavior
while `UI Build test`, when it runs `make build-ui`, it attempts to build ‘meshery-ui’ and ‘provider-ui’. If ‘meshery-ui’ fails building and ‘provider-ui’ is successful, it considers the process to be successfully completed.

#### Desired Behavior
Current behaviour is deceiving. It should either run both of those as separate tests or it should break when an error occurs anywhere in the middle.

#### Screenshots
Screenshot 2021-07-09 at 12 30 47 PM

#### Acceptance Tests
`UI Build Test` should give proper feedback on completion of the test.

#### Reference:
- [Meshery Build & Release Strategy](https://docs.google.com/document/d/11nAxYtz2SUusCYZ0JeNRrOLIxkgmmbUVWz63MBZV2oE/edit#)

### PR DESCRIPTION
**Pull request by iamsdas**
Signed-off-by: Suryashankar Das <suryashankardas.2002@gmail.com>

**Description**
Adds the `build-provider-ui` and `build-meshery-ui` commands to the Makefile and separates the `build app` step for the UI build test into `build meshery-ui` and `build provider-ui` .

This PR fixes #3438 

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by sudo-NithishKarthik — APPROVED** [review]
LGTM 🎉 
Thank you @iamsdas  😄

**Comment by leecalcote** [comment]
Can we leave `make build ui` in the Makefile as a command that covers both Nextjs instances?

If not, all references to this command need to be updated across the contributing docs.

**Comment by sudo-NithishKarthik** [comment]
> Can we leave `make build ui` in the Makefile as a command that covers both Nextjs instances?
> 
> If not, all references to this command need to be updated across the contributing docs.

The command `make build-ui` is still intact, only two new commands have been added which are being used in the workflow

**Comment by leecalcote** [comment]
Thank you for confirming, @sudo-NithishKarthik

**Pull request merged**
