### PR TITLE
Osm port update

### LINKED ISSUE #1547: Change the ports for meshery-osm adaptor

### PR DESCRIPTION
**Pull request by ghost**
**Description**

This PR fixes #1547

**Notes for Reviewers**
It seems that a for loop runs through the adapters as is seen at docs/_adapters and for each adapter in there, it is assigned to the port reflected in its individual file. So, I just changed the port for OSM from 10010 to 10009

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X ] Yes, I signed my commits.

### CODE REVIEW

**Comment by KarenEfereyan** [comment]
@leecalcote my DCO check has successfully passed but im trying to resolve these conflicts

**Comment by kushthedude** [comment]
Please rebase your branch.

**Comment by KarenEfereyan** [comment]
@kushthedude i had lots of issues today. I made many mistakes. But Precious and Nupur helped me with them all. Ill make a better PR soon.

**Comment by KarenEfereyan** [comment]
@kushthedude and @leecalcote can you please close this PR? I have made a better one. Please

**Comment by KarenEfereyan** [comment]
@kushthedude and @leecalcote can this PR be closed? I have made a better one

**Pull request closed without merging**
