### PR TITLE
removed extra line in the file verbose.yml

### LINKED ISSUE #407: Docs: Change name of the "Playground" page to "Management"
**Description**
"Management" is a more accurate name for the page that is currently named "Playground".

**Expected Behavior**
"Management" should be seen in the navigation menu, not "Playground".
---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

### PR DESCRIPTION
**Pull request by alonsolopezr**
Signed-off-by: JOSE ALONSO LOPEZ ROMO <alonso.lopez.r@gmail.com>

**Description**
Yes, the file verbose.yml actually had and extra line
This PR fixes #407

**Notes for Reviewers**
@metonymic-smokey please check if this is fixed

**[Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X ] Yes, I signed my commits.

### CODE REVIEW

**Comment by metonymic-smokey** [comment]
@alonsolopezr 
When I check the docs from the preview built by the latest commit, I still see the extra line:

image

**Comment by alonsolopezr** [comment]
Wow, that 's weird, because I watch the preview and the extra blank line is gone (https://deploy-preview-2508--meshery-docs.netlify.app/reference/mesheryctl)

Captura de Pantalla 2021-03-05 a la(s) 9 56 33

**Review by leecalcote — APPROVED** [review]
LGTM

**Comment by metonymic-smokey** [comment]
@alonsolopezr 
You're right, the extra line is gone when I check now.
This does fix the issue.
Thanks!

**Pull request merged**
