### PR TITLE
update component w/signoff

### PR DESCRIPTION
**Pull request by Jougan-0**
**Notes for Reviewers**

This PR fixes #

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — COMMENTED** [review]
Why wouldn’t we update the component it if it does not have a description?

**Comment by Jougan-0** [comment]
> Why wouldn’t we update the component it if it does not have a description?

We update the component even though the description is not present. It is never returning it is just a check if the description is not present then don't create the key as `description` is not required in schema.

**Comment by Jougan-0** [comment]
DO NOT MERGE I'll pass all the fixes in this PR itself and we would be done with this today.

**Review by leecalcote — APPROVED** [review]

**Review by leecalcote — APPROVED** [review]

**Comment by leecalcote** [comment]
Complete with a new flag, too!

**Pull request merged**
