### PR TITLE
Cilium integration test not showing the latest test

### LINKED ISSUE #5607: [Docs] Cilium integration test not showing the latest test
#### Current State
The test results for cilium service mesh is not updating to the latest test results.

Screen Shot 2022-06-13 at 17 37 19

The table shows test result from `2022-05-10 12:32:04 UTC Tue` which is not the latest one which can be seen in the past results page:
image

#### Desired State

Change the logic for Cilium service mesh such that it shows the latest test results in the https://docs.meshery.io/project/compatibility-matrix page.

---

#### [Contributor Guides](https://docs.meshery.io/project/contributing) and Resources
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by karnatisrinivas**
Signed-off-by: karnatisrinivas <karnatisrinivasulareddy@gmail.com>

**Description**

This PR fixes #5607 

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 31e57737ff18508548749d8d5dd2fd507bc10ba0 at: https://62ad968985b350560b105827--meshery-docs-preview.netlify.app

**Comment by warunicorn19** [comment]
@karnatisrinivas would you like to discuss updates on this on the meshery dev call?

**Comment by l5io** [comment]
🚀 Preview for commit 31e57737ff18508548749d8d5dd2fd507bc10ba0 at: https://62f5e5d91a561e75808e6cc8--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 31e57737ff18508548749d8d5dd2fd507bc10ba0 at: https://637ea86f27e2835a46f48d1e--meshery-docs-preview.netlify.app

**Comment by Aisuko** [comment]
Hi guys, Have we got a solution for this PR? I saw this change only shows 3 adapters as @karnatisrinivas said.

**Comment by asubedy** [comment]
This issue has been solved in the current version of Meshery docs, PR can be closed

**Pull request closed without merging**
