### PR TITLE
Add Config Map Icon

### LINKED ISSUE #8753: [MeshModel] [UX]: Icon for Kubernetes Component - Config Map
### Current Behavior
Meshery is a powerful platform that contains over [200 integrations](https://layer5.io/cloud-native-management/meshery/integrations) for managing cloud-native applications. MeshMap is an extension of Meshery that visually represents these integrations and components. Currently, most of the icons used in MeshMap have the default shape of a circle. However, to improve visual clarity and consistency, we need to design custom icons for MeshMap components.

### Desired Behavior
A new Icon for  **Config Map** needs to be created. This issue calls for a volunteer to draft a new Icon.

### Instructions for Components
While the default shape for new components is a circle, each component should be considered for its best-fit shape.
1. Review and familiarize with the available set of predefined relationship types. Refer to the Cytoscape [node types](https://js.cytoscape.org/demos/node-types/) for a list of possible shapes. 
1. Propose a specific shape, best-suited to visually represent the Component. Example - Deployment as a pentagon, DaemonSet as a skull icon etc.
3. Create two versions of the icon one is white and another one is colored
4.  Make a PR after adding the icon inside the [new-icon folder](https://github.com/meshery/meshery/tree/master/ui/assets/new-icons) present in the meshery repository
5. Provide the icon in SVG format
6. Go to the [playground](https://playground.meshery.io/extension/meshmap) -> search for the component you are trying to design icon for and check whether the icon that you are designing is already present for another component or not if not then you can make a PR.
7. If you don't have access to Playground then you have to fill a [signup](https://play.meshery.io/) and get verified before you access the playground by the time you get access, you can go to [integrations](https://layer5.io/cloud-native-management/meshery/integrations) page in layer5.io site and search for the component and see whether an icon is already present or not.
8. Make sure icon for component is different from Model icon.
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- [MeshModel Repository](https://github.com/meshery/meshery/tree/master/server/meshmodel)
- 🖥 [MeshModel Overview](https://docs.google.com/presentation/d/1SQMfyu5shjpGKlYONdVzOtd7UYTgLWBcgUvHMLCZ2tY/edit#slide=id.g226f5de5180_19_259)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by ShatilKhan**
**Notes for Reviewers**

This PR fixes #8753

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.
 
Description: 
Add logo for k8s Config Map. The official one had lettering in it so I removed the lettering to correspond to Meshery Design Patterns.

Original Logo:
cm

Edited Logo:
svgviewer-output

### CODE REVIEW

**Comment by leecalcote** [comment]
Remember: we don't use lettering in the icons here.

**Comment by ShatilKhan** [comment]
I'm on it @leecalcote ✨

**Comment by jamieplu** [comment]
I like this initiative. Creating a large, fresh set of icons is exciting. :)

**Comment by leecalcote** [comment]
Good. We're getting closer. Be sure to center the icon. I haven't looked, but just in case, and as a reminder: only the icon should be included in the SVG, and not the shape (in this case the blue heptagon).

Will you try exploring concepts around "key-value pairs". Something akin to this: https://thenounproject.com/icon/key-value-database-1680886/

**Comment by saurabh100ni** [comment]
Let's discuss this on the Meshery dev call tomorrow,
Please add this as your agenda item in Docs: https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit

**Comment by ShatilKhan** [comment]
Sure @leecalcote ! thanks for the suggestion, I'll explore on that

@saurabh100ni I'll add it to tomorrows agenda!

**Review by leecalcote — CHANGES_REQUESTED** [review]
Please deliver only the colored and white icons, leaving the shape out.

**Comment by ShatilKhan** [comment]
Removed the shape @leecalcote

**Pull request merged**
