### PR TITLE
[Docs] Enhance enhanced layout with optional suggested-reading list

### PR DESCRIPTION
**Pull request by leecalcote**
Signed-off-by: Lee Calcote <lee.calcote@layer5.io>

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit ae9e5acf407c9304793500a1da48474695df69c7 at: https://65c5a4617a5279502c72d9e9--meshery-docs-preview.netlify.app

**Review by ashutosh-rath02 — APPROVED** [review]
LGTM🤖

**Review by iArchitSharma — APPROVED** [review]
Working correctly!!

**Comment by l5io** [comment]
🚀 Preview for commit 6604af7c6e1b8faba919fb496c16421af2bfcb91 at: https://65c63c5d4809de03c759b08d--meshery-docs-preview.netlify.app

**Pull request merged**
