### PR TITLE
Bug fix [UI] Make button responsive for Designs card 

### LINKED ISSUE #6257: [UI] Make button responsive for Designs card
#### Current Behavior
The design card buttons are not responsive and there is an unwanted character "``" floating near the design button.

#### Desired Behavior

- [ ] Remove unwanted symbol "``" at the left of clone/design button
- [ ] Make buttons responsive
- [ ] Hide labels on the smaller ratio
- [ ] Add labels to buttons

#### Screenshots/Logs
image

#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by siddheshjungade**
Signed-off-by: Siddhesh Jungade [connect@siddheshjungade.me](mailto:connect@siddheshjungade.me)

**Description**
Task acomplished
- [x] Remove unwanted symbol "``" at the left of clone/design button
- [x] Hide labels on the smaller ratio
- [x] Add labels to buttons
- [x] Make clone icon equivalent to others.
- [x] Make buttons responsive
Screenshot from 2022-09-29 21-22-53

https://user-images.githubusercontent.com/32316726/193085726-51b97f45-99e1-47c6-b329-98164077e3ca.mp4

- Hide labels on the smaller ratio
   Breakpoint end change to 1370px because button are overflowing when side control panel is open 

Still working on making button responsive. 

This PR fixes #6257

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by legendarykamal — CHANGES_REQUESTED** [review]
Looks nice, can you also take care of the overflowing at 0:06 of the video ?

**Comment by siddheshJungade** [comment]
Working on it ✌️

**Comment by leecalcote** [comment]
If more room is needed, the button labels can be dropped on smaller-sized screens.

**Comment by Chadha93** [comment]
@siddheshJungade heads-up: merge conflicts, only last check item is left. Do connect with @legendarykamal if any assistance is required.

**Comment by siddheshJungade** [comment]
Not yet will connect with him tomorrow

**Comment by Chadha93** [comment]
@legendarykamal @siddheshJungade Styles for Button responsiveness(on specific ratio), text-overflow, and label responsiveness on public designs still pending? 
image

**Comment by Chadha93** [comment]
Let me push a quick fix here.

**Comment by Chadha93** [comment]
https://user-images.githubusercontent.com/65453826/194069233-665762c1-e35b-4351-8337-c962ac637797.mp4

**Review by Chadha93 — APPROVED** [review]
Good work @siddheshJungade LGTM :1st_place_medal:

**Comment by legendarykamal** [comment]
@Chadha93 looks nice ready to be merged thank you for giving the finishing touches 👏

**Comment by siddheshJungade** [comment]
Thankx for accepting

**Pull request merged**
