### PR TITLE
updated style and fixed search in context switcher

### PR DESCRIPTION
**Pull request by warunicorn19**
Signed-off-by: Aditya Chatterjee <speak2adi@gmail.com>

**Description**
Fixed the style of the switcher similar to mockup.
Also fixed the bug with the search in the switcher. 

https://user-images.githubusercontent.com/53532328/154622787-7a8be11d-4736-4e88-a852-44f9fa162ffb.mov

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Very nice. The background of the chip didn't remain white. Hmpf.

**Comment by warunicorn19** [comment]
Ohh right, I missed that, I'll update it tomorrow. Will have to override the material ui chip styles to do it.

**Comment by warunicorn19** [comment]
Screenshot 2022-02-18 at 3 08 11 AM

**Review by leecalcote — APPROVED** [review]
Looks good

**Pull request merged**
