### PR TITLE
Added a white helm logo for dark mode

### LINKED ISSUE #7506: [UI] Use white Helm logo in Applications for source type in dark mode
#### Current Behavior
The Helm logo is not appealing at all in dark mode.

#### Desired Behavior
Use a light (white) helm SVG only for Dark Mode. 

#### Screenshots/Logs
image

#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by souravpy**
as asked in https://github.com/meshery/meshery/issues/7506

**Notes for Reviewers**

This PR fixes #7506 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Thanks, @souravpy. Will you confirm that this has been followed? https://docs.meshery.io/project/contributing/contributing-ui#static-files-icons-and-images

**Review by Chadha93 — COMMENTED** [review]
@souravpy Please use this icon with dark mode logic here https://github.com/meshery/meshery/blob/c08a700a08f579775737b78654a48cfb78c17d1e/ui/components/MesheryApplications/ApplicationsCard.js#L86

**Comment by souravpy** [comment]
Thank you @Chadha93 and @leecalcote for the feedback I'm looking right into it 👌

**Comment by souravpy** [comment]
I made the prescribed logo but failed to use the icon with the dark mode logic, Ive come up with a few solutions:
- help me with the logic, how to do it
- or merge the logo, and create a new good first issue that has the dark mode logic part
I'm eager to work on the issue if helped out with logic @leecalcote , @Chadha93

**Comment by DarrenDsouza7273** [comment]
hi @souravpy if you go through other logos which are present there is a dark mode logic applied to all of them so you can refer those and do changes accordingly

**Comment by souravpy** [comment]
> hi @souravpy if you go through other logos which are present there is a dark mode logic applied to all of them so you can refer those and do changes accordingly

I've made the logo, let's figure out the logic, keep me updated if you learn something new about it

**Comment by souravpy** [comment]
Its, Sourav Biswal

**Comment by souravpy** [comment]
> > > hi @souravpy if you go through other logos which are present there is a dark mode logic applied to all of them so you can refer those and do changes accordingly
> > 
> > I've made the logo, let's figure out the logic, keep me updated if you learn something new about it
> 
> i surely will get back to you, please mention your slack username it would be convenient to keep you updated on it there.
>  

It's Sourav Biswal, let's connect 👍

**Comment by souravpy** [comment]
Sure, thank you @vishalvivekm

**Comment by souravpy** [comment]
> Hey @souravpy you take reference from [this](https://github.com/layer5io/layer5/blob/master/src/theme/app/THEME.md) on SVG color change on theme change 

Really thanks @duckling69 , checking it out 😃

**Review by souravpy — COMMENTED** [review]
Does this work now?

**Comment by duckling69** [comment]
> Does this work now?

@souravpy you don't really have to make new a logo you just need to update the color of SVG on theme change

**Comment by souravpy** [comment]
> > Does this work now?
> 
> @souravpy you don't really have to make new a logo you just need to update the color of SVG on theme change

How can I?

**Comment by duckling69** [comment]
> > > Does this work now?
> > 
> > 
> > @souravpy you don't really have to make new a logo you just need to update the color of SVG on theme change
> 
> How can I?

image
Like its been done here 
image
you can give the parent div some classname and target img tag in it and change it's fill color to something like 
props => props.theme.blue0f1689Towhite

correct me if i'm wrong here @vishalvivekm

**Comment by leecalcote** [comment]
This bug has been an issue for too long. @duckling69 if you can get this done correctly, please do.

**Comment by DarrenDsouza7273** [comment]
> > > > Does this work now?
> > > 
> > > 
> > > @souravpy you don't really have to make new a logo you just need to update the color of SVG on theme change
> > 
> > 
> > How can I?
> 
> image Like its been done here image you can give the parent div some classname and target img tag in it and change it's fill color to something like props => props.theme.blue0f1689Towhite
> 
> correct me if i'm wrong here @vishalvivekm

 @duckling69 it might work this way.

**Comment by souravpy** [comment]
Getting this done asap

**Review by leecalcote — APPROVED** [review]

**Pull request merged**
