### PR TITLE
Fixed Meshary Integration Updater

### PR DESCRIPTION
**Pull request by ptdatta**
**Notes for Reviewers**

Fixed the workflow integration updater.

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by ptdatta** [comment]
@theBeginner86 I think I have fixed the integration updater issue. Currently, it showing like this as I don't have the Layer5 or Meshery docs repo in my local system but I think it will resolve the workflow issues. Can you please check this??
image

**Review by leecalcote — APPROVED** [review]
LGTM

@MUzairS15 ?

**Comment by leecalcote** [comment]
@MUzairS15, what do you think? Good to go?

**Comment by leecalcote** [comment]
@ptdatta please sign your commits.

Execute these instructions - https://github.com/meshery/meshery/pull/8774/checks?check_run_id=16806875997

**Comment by ptdatta** [comment]
> @ptdatta please sign your commits.
> 
> Execute these instructions - https://github.com/meshery/meshery/pull/8774/checks?check_run_id=16806875997

Done. ✅

**Review by MUzairS15 — APPROVED** [review]
LGTM

**Pull request merged**
