### PR TITLE
[UI] fixed meshery-ui not showing up after following make build-ui(Meshery docs)

### PR DESCRIPTION
**Pull request by Harshit-Dandriyal**
… docs)

Signed-off-by: Harshit-Dandriyal <dandriyalh9318@gmail.com>

**Description**
Meshery UI was not available on local host after following make build-ui from Meshery Docs. 
Desktop Screenshot 2022 03 19 - 11 08 09 88
That was due to next build failure, The nextjs was not generating the code in absence of webpack-cli and unmatched webpack version.
The issue is fixed Now.  
This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
@Abhijay007 will you confirm that this is an issue? @Harshit-Dandriyal, thank you for this PR. I haven't seen the Meshery UI failing to build previously, but I could be missing something.

**Comment by Harshit-Dandriyal** [comment]
@leecalcote @Abhijay007 Yes, I was also surprised to encounter this type of setup problem, I am sending a video of me setting up meshery from start, Video size is more than size limit in this, I am sending in slack

**Comment by Abhijay007** [comment]
> @Abhijay007 will you confirm that this is an issue? @Harshit-Dandriyal, thank you for this PR. I haven't seen the Meshery UI failing to build previously, but I could be missing something.

sure, will look into this

**Review by leecalcote — COMMENTED** [review]
Thank you for your help, @Harshit-Dandriyal 👏

**Review by leecalcote — APPROVED** [review]

**Pull request merged**
