### PR TITLE
`mesheryctl` installation instructructions for Brew #1785

### LINKED ISSUE #1785: [Docs] `mesheryctl` installation instructructions for Brew
**Current State:**
These three lines can be reduced to two lines.

Screen Shot 2020-10-29 at 12 07 01 AM

**Desired State:**
Two lines should be:

```
brew install layer5io/mesheryctl
mesheryctl system start
```

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

### PR DESCRIPTION
**Pull request by abhishekkumkar**
**Description**

This PR fixes #1785 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
@abhishekkumkar please follow these instructions - https://github.com/layer5io/meshery/pull/1794/checks?check_run_id=1331652935

**Review by kushthedude — APPROVED** [review]
nice work @abhishekkumkar

**Comment by abhishekkumkar** [comment]
@leecalcote thanks for your guidance. and @kushthedude thanks for approving

**Comment by leecalcote** [comment]
Looking good, @abhishekkumkar 🎈 😄

**Pull request merged**
