### PR TITLE
[UI] Fixes Notification Center Sneak Peak Behavior onClick 

### LINKED ISSUE #7879: [UI] Notification Center: Sneak Peak Behavior on-click
#### Current Behavior

https://github.com/meshery/meshery/assets/7570704/fd65fbcc-6a6e-400a-9c4d-b61ace18f040

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by Chadha93**
**Notes for Reviewers**
Reason: the icon button was wrapped under an extra div. 
There was a PR a few months back which stated that it was a Safari-specific issue, please also test this on Safari once, build on the dev server (live reload) when testing. 

This PR fixes #7879 

[notification-click-fix.webm](https://github.com/meshery/meshery/assets/65453826/b9573637-40fe-4e27-adcc-14ee4254911a)

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Chadha93** [comment]
@theBeginner86 @asubedy @yash37158 Could anyone please help with verifying this fix on Safari too?

**Comment by leecalcote** [comment]
> @theBeginner86 @asubedy @Yashsharma1911 Could anyone please help with verifying this fix on Safari too?

✋ I will

**Comment by leecalcote** [comment]
Unfortunately, my tests in Safari fail to prove that this fix works in this browser.

**Comment by leecalcote** [comment]
@asubedy thoughts?

**Comment by leecalcote** [comment]
I rebuilt again and double-checked. No, this doesn't work in Safari.

**Comment by asubedy** [comment]
Yep, not working for me too

**Comment by Yashsharma1911** [comment]
It's working fine in my case


https://github.com/meshery/meshery/assets/71271069/2b842b3b-4805-4225-be50-a5e94a67f958

**Comment by leecalcote** [comment]
Good screen recording. Ok, let's merge and see if my test and @asubedy's tests wrong misplaced. I hope that they are. That would be nice.

**Review by leecalcote — APPROVED** [review]
Let's give this a shot.

**Pull request merged**
