### PR TITLE
Fix: Visualizer crashes on first try | CU-1x74e8a

### PR DESCRIPTION
**Pull request by manav1403**
Signed-off-by: manav1403 <manavavni@gmail.com>

**Description**

The visualizer was crashing with an error of invalid route as logged in the console

**Notes for Reviewers**
The condition of error was arising because the routes `extendedEndpoints` were being called before they were initialized by the `LoadExtensionFromPackage` hence there was a race condition, to tackle that I shifted the Mutex lock to the starting of the function.

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
Task linked: [CU-1x74e8a Visualizer crashes on first try](https://app.clickup.com/t/1x74e8a)

**Review by warunicorn19 — DISMISSED** [review]
LGTM! @Revolyssup good to go right?

**Review by Revolyssup — CHANGES_REQUESTED** [review]
@manav1403  instead of doing it again and again Can you defer the unlock of mutex just after we lock it

**Review by Revolyssup — APPROVED** [review]

**Comment by leecalcote** [comment]
Nice work.

**Pull request merged**
