### PR TITLE
[UI] Moved `MesheryChart` and `MesheryChartDialog` from class based component to functional component

### LINKED ISSUE #8796: [UI] Convert `MesheryChart` and `MesheryChartDialog` from class based component to functional component
### Current Behavior
`MesheryChart` and `MesheryChartDialog` are class-based components

### Desired Behavior
`MesheryChart` and `MesheryChartDialog` should be functional components.

### Implementation
Convert all the Class-based components to new updated functional components. It is important here to convert a class-based component to a functional component you may need to convert some functions as well. Check if the function is used in other components or not.

Also, make sure to use the hooks while converting them. For example, you need to covert withNotify with useNotification, useRouter hook. Please check if a hook for functional components is available and use that.

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by mukeshkuiry**
**Notes for Reviewers**

This PR fixes #8796

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by mukeshkuiry** [comment]
image

**Comment by mukeshkuiry** [comment]
@Rajdip019 @EraKin575

**Comment by Rajdip019** [comment]
The changes look fine. It would be amazing if you could share a video of the working components. @mukeshkuiry

**Comment by mukeshkuiry** [comment]
https://github.com/meshery/meshery/assets/99157367/95b8a360-c53b-4b51-8fa7-022f7701ccc6

**Comment by mukeshkuiry** [comment]
@Rajdip019

**Comment by saurabh100ni** [comment]
Let's discuss this on the Meshery dev call tomorrow,
Please add this as your agenda item in Docs: https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit

**Review by Rajdip019 — APPROVED** [review]

**Comment by mukeshkuiry** [comment]
> Let's discuss this on the Meshery dev call tomorrow, Please add this as your agenda item in Docs: https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit

Sorry won't able to present on yesterdays call, busy with certain stuff

**Comment by mukeshkuiry** [comment]
@Rajdip019 I guess this problem is solved.
You can merge.

**Pull request closed without merging**
