### PR TITLE
[UI] Enhance Notification Center 

### PR DESCRIPTION
**Pull request by aabidsofi19**
**Notes for Reviewers**

Related to  #8485

This Pr Adds the following :

-  Custom Snackbar hook to enable sending toaster messages in notification center 
-  timestamp for events 
-  deeplink from toasts 
-  Refactored Applications Pages and Designs Page to use these new notifications for toasts 

https://github.com/meshery/meshery/assets/65964225/94d91322-71d3-4134-bf10-81865c0664de

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by aabidsofi19** [comment]
TODO :
- start using these new notifications in all other places ( simple copy pasta work )

**Review by Yashsharma1911 — COMMENTED** [review]
@aabidsofi19 I wonder if we can use hook similar that we have in [meshery cloud](https://github.com/layer5io/meshery-cloud/blob/master/ui/utility/notification-handlers.js) with customization so that we will be consistent on both side thoughts?

**Comment by aabidsofi19** [comment]
Notes :

- Added Support for Class Based Components , we can use the custom withNotify HOC to pass notify as a prop in CBC  and then use it as normal 
- Making the whole snackbar causes memory leaks . it is a issue with the version of snackbar we are using , but these simple abstractions we can easily upgrade it  when we move to mui5 and react 18

**Comment by leecalcote** [comment]
> Notes :
> 
> * Added Support for Class Based Components , we can use the custom withNotify HOC to pass notify as a prop in CBC  and then use it as normal
> * Making the whole snackbar clickable causes memory leaks . it is a issue with the version of snackbar we are using , but these simple abstractions we can easily upgrade it  when we move to mui5 and react 18

Great explanation.

**Pull request merged**
