### PR TITLE
[docs]: Add Providers Screenshot

### LINKED ISSUE #1213: [Docs] Add login page screenshot to "Providers" section
**Current State:**
There are no screenshots of the Meshery UI showing readers what it looks like to select a Provider and login.

**Desired State:**
Incorporate the screenshot below into the [Providers section](https://meshery.layer5.io/docs/extensibility#providers) of the Meshery Docs.

**Screenshot**
Meshery - Providers

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

### PR DESCRIPTION
**Pull request by Adeola-Adesoba**
Signed-off-by: Adeola <46505882+Adeola-Adesoba@users.noreply.github.com>
Fixes #1213 

**Description**

This PR fixes # 

**Notes to reviewers**

#### Checklist

- [] [Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin).
- [] PR title includes `[<name of area>]:<description>`

### CODE REVIEW

**Comment by morrme** [comment]
@leecalcote 🎊

**Comment by leecalcote** [comment]
Were we able to confirm that the size of the screenshot is appropriate? I haven't built and previewed this update, but suspect that this screenshot might be best served with a `width:50%` (or something similar) to show a thumbnail with a hyperlink to the full-sized screenshot.

**Comment by morrme** [comment]
@leecalcote  Here's how it looks on the page: 
extensibility.md

Here's `management.md` for size reference: 
management.md

**Comment by leecalcote** [comment]
Thank you, @morrme. I like how you've referenced the style in which other screenshots have been provided - consistency is an important consideration for the reader's experience. 👍

**Comment by Adeola-Adesoba** [comment]
@morrme thanks for that reference. 

@leecalcote thank you for approving the changes. Glad it came out great.

**Pull request merged**
