### PR TITLE
Fixed `handleOperatorClick` chip

### LINKED ISSUE #3139: [Meshery] Update operator chip endpoint
#### Description
Description from here - https://github.com/layer5io/meshery-operator/issues/163

#### Expected Behavior
The endpoint implementation needs to be updated to hit operator instance and return status.

#### Environment:
- Meshery Version: 
- Kubernetes Version: 
- Host OS:
- Browser: 

---

**Contributor Resources:**
- (Contributing Docs](https://docs.meshery.io/project/contributing)

### PR DESCRIPTION
**Pull request by dhruv0000**
Signed-off-by: dhruv0000 <patel.4@iitj.ac.in>

**Description**

This PR fixes #3139 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Heads up: there are integration tests failing

**Comment by kumarabd** [comment]
@dhruv0000 ref: https://github.com/layer5io/meshery/pull/3147

**Comment by leecalcote** [comment]
Looks like CodeCov might have a misconfiguration. What do you think, @ramrodo?

**Review by leecalcote — APPROVED** [review]

**Comment by ramrodo** [comment]
> Looks like CodeCov might have a misconfiguration. What do you think, @ramrodo?

I think it was because it was changed the version of the CodeCov Github Action and something changed in this one. It was necessary to update the version?

**Comment by leecalcote** [comment]
Oh, I'm not sure. I don't recall updating the CodeCov version.

**Comment by dhruv0000** [comment]
@ramrodo The same error still persisted in the v1. There were some [open issues](https://github.com/codecov/codecov-action/issues/43#issuecomment-564736839) about this in their repo, some suggesting to update the version to fix it. I was just giving it a go. Turned out, the error is still persistent.

**Pull request merged**
