### PR TITLE
Add Citi in Meshery adopters list

### PR DESCRIPTION
**Pull request by betelgeuse-code**
**Notes for Reviewers**

This PR fixes #

This PR adds [Citi](https://www.citi.com/) in Mehsery adopters list

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by betelgeuse-code** [comment]
Hey @alphaX86 would you please review this to make sure I added the correct information, please feel free to suggest a change if needed

**Comment by alphaX86** [comment]
> Hey @alphaX86 would you please review this to make sure I added the correct information, please feel free to suggest a change if needed

Hey @betelgeuse-code thanks for your PR! I'm not very sure if this can be officially added in the adopters list considering the policies we have. Let me double check if this is allowed and get back to you.

**Comment by alphaX86** [comment]
As per policies present in Citi, we can't add this in the adopters list, yet (unless if officially adopted by the org itself), so it's best to close this.

**Comment by alphaX86** [comment]
Thanks for your enthusiasm in helping and raising a PR though @betelgeuse-code 🙌

**Pull request closed without merging**
