### PR TITLE
[extensions] Fix Collaborator Extension Point Re-rendering

### PR DESCRIPTION
**Pull request by theBeginner86**
**Notes for Reviewers**

This PR fixes the collaborator extension point re-rendering by the use of `shouldComponentUpdate` function of React. Reference: https://legacy.reactjs.org/docs/optimizing-performance.html#avoid-reconciliation

Now we have a redux state that manages whether the extension point is mounted. Once mounted we would not be remounting it.

This PR fixes #

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by theBeginner86** [comment]
https://github.com/meshery/meshery/assets/73700530/a3a87a27-dc52-4cb7-a104-4c23c5bd66f2

**Review by aabidsofi19 — APPROVED** [review]
LGTM

**Comment by theBeginner86** [comment]
Thanks @aabidsofi19 for merging.
I would be reverting this PR for now, actually it wasn't ready as there is some issue with dark modal selection for it. I missed adding draft label yesterday.

I'll look into it and re-create a PR for this.

**Comment by aabidsofi19** [comment]
oh sorry, i was too excited to see this .

**Comment by theBeginner86** [comment]
> oh sorry, i was too excited to see this .

Ohh, thank you for pushing forward. It was my mistake for not putting the right set of labels. 

I've fixed all the issues now. Its ready for your eyes: https://github.com/meshery/meshery/pull/8904

**Pull request merged**
