### PR TITLE
[UI][Bug Hunt] Cluster Switcher + nav toggle btn fix | CU-22qqma1

### PR DESCRIPTION
**Pull request by Chadha93**
Signed-off-by: Gaurav Chadha <gauravchadha1676@gmail.com>
**Description**

- No line breaking

- Able to ping the context and have ‘X’ to remove the cluster from Meshery’s management

- Sidebar `collapse` button reduce the font size

- Search enhancements

- Color enhancements

This PR fixes #CU-22qqma1

**Notes for Reviewers**

https://user-images.githubusercontent.com/65453826/155874243-a9530cd8-67cb-470d-bac4-499cc7d1e60d.mp4

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
Task linked: [CU-22qqma1 Context Switcher + Nav svg](https://app.clickup.com/t/22qqma1)

**Comment by leecalcote** [comment]
When the user Xs the last remaining cluster chip, does the menu returning to empty state with "add context" button visible?

**Comment by Chadha93** [comment]
> When the user Xs the last remaining cluster chip, does the menu returning to empty state with "add context" button visible?

okay, will confirm and post another video :+1:

**Comment by warunicorn19** [comment]
In the mockup, the search icon was at the end of the search bar, are we moving it to the front now?

**Comment by leecalcote** [comment]
There were no changes to the Search input discussed, no.

**Comment by leecalcote** [comment]
That doesn't mean that enhancements can't be made… Just that changes weren't explicitly asked for.

**Review by leecalcote — CHANGES_REQUESTED** [review]
1. Do you mind reverting the style changes on the Search input?
1. Can you also have the peek be only at 7px (only have the menu drop by that much)?
1. Can you also have the menu rollback into the Page bar on removal of focus from the k8s button?

**Comment by leecalcote** [comment]
@Chadha93 did you complete all feedback?

**Comment by Chadha93** [comment]
> @Chadha93 did you complete all feedback?

Nope, will have to look for the 3rd one, the menu is currently sliding back to the page bar(header), rollback here refers specifically?

**Comment by leecalcote** [comment]
Right. It slides down to open, so it should slide back up to close, not disappear to close.

**Comment by leecalcote** [comment]
Merging current progress. Please open another PR for the remainder of the items.

**Comment by leecalcote** [comment]
@NikhilSharma03, should we be using a slide "up" to reverse the affect on click away? https://github.com/meshery/meshery/blob/7bc985df2ffc98a82597bd910a5d2f30732070f7/ui/components/Header.js#L208

**Comment by Chadha93** [comment]
> 

Okay @leecalcote the menu is sliding up as I mentioned, will get back to the transition behavior of the menu soon.

**Comment by Chadha93** [comment]
> Merging current progress. Please open another PR for the remainder of the feedback.

Sure

**Pull request merged**
