### PR TITLE
fix: #8911

### LINKED ISSUE #8911: [Docs] typo 'visitior'
### Current State
image
image

typo 'visitior' in publishing a design page [here](https://docs.meshery.io/extensions/publishing-a-design) and sharing a design page [here](https://docs.meshery.io/extensions/sharing-a-design).

### Desired State
It should be 'visitor'

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by Sumit21kumar**
**Notes for Reviewers**

This PR fixes #8911

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 54921d551028be3be8d02d62d7c2bb7e16ca78c9 at: https://65119aa65b7991346c52220e--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 54921d551028be3be8d02d62d7c2bb7e16ca78c9 at: https://65119b565d40e033313c4bdf--meshery-docs-preview.netlify.app

**Comment by abhijeetgauravm** [comment]
Hey @Sumit21kumar really appreciate your enthusiasm to contribute , However please refrain from creating direct PRs without getting assigned first .

**Review by leecalcote — APPROVED** [review]
Notwithstanding @abhijeetgauravm's guidance, thanks for jumping into the fray, @Sumit21kumar. 👍

**Pull request merged**
