### PR TITLE
Get pagination params in handlers from utils

### LINKED ISSUE #10825: Replace the repetitive logic for extracting `page, pagesize, search, offset` from API handlers to use  `getPaginationParams ` in `utils.go`.
Replace the repetitive logic for extracting `page, pagesize, search, offset` from API handlers to use  `getPaginationParams ` in `utils.go`.

_Originally posted by @MUzairS15 in https://github.com/meshery/meshery/pull/10824#discussion_r1585605275_

### PR DESCRIPTION
**Pull request by RyanCarlisle**
**Notes for Reviewers**

This PR fixes #10825 : the repetitive logic for extracting `page`, `pagesize`, `search`, `offset` from API handlers and uses `getPaginationParams` in `utils.go`

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by 864893031735973 — COMMENTED** [review]
Ok

**Comment by vishalvivekm** [comment]
Hey @RyanCarlisle, let's discuss this on today's Meshery Dev meeting at 7:30 PM IST. I am adding this as an [agenda item](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit?pli=1#). Please Join https://meet.layer5.io/meshery if you are available during the meet.

**Comment by MUzairS15** [comment]
@yash37158

**Review by MUzairS15 — COMMENTED** [review]
What testing have you performed @RyanCarlisle ?
Did you test the UI by building the server on this PR, did you faced any regression issues or failing APIs or incorrect results?
Did you verified if pagination and search still works fine in the UI.

**Comment by MUzairS15** [comment]
@Yashsharma1911

**Comment by RyanCarlisle** [comment]
@MUzairS15 I have tested a few APIs by building the UI and server with my code changes. However, I could not test it thoroughly as WSL/VIrtual Linux took around 5-6 GB of RAM (plus Google Chrome which took an extra 2 GB, totaling up to 8 GB) which slowed the entire system down, making it a bit difficult for me to continue testing.

**Comment by MUzairS15** [comment]
Can you list the APIs that you tested?
Are you running ui-dev-server as well?

**Comment by RyanCarlisle** [comment]
The commands that I had run were as mentioned in the guide. These were as follows:
1. make ui-build
2. make ui-setup
3. make server
4. make ui

I have not made a list but I shall try to make a list of the APIs after testing them out again.

**Comment by leecalcote** [comment]
Thanks for this PR, @RyanCarlisle. Keep at it. 👍

**Comment by MUzairS15** [comment]
@RyanCarlisle Any updates, because this change affects many APIs we beed to be careful.

**Comment by RyanCarlisle** [comment]
Apologies for the delay @MUzairS15 . I could not pick up the testing at all the past week due to emergency reasons. I shall pick it up and get fruitful data within two days.

**Comment by singh1203** [comment]
@MUzairS15 please assign

**Comment by MUzairS15** [comment]
@singh1203 please carry this forward

**Comment by RyanCarlisle** [comment]
Hi @singh1203 , you can take this up. I'm not sure why but my laptop has not permitted me to run tests on the APIs. After quite a few futile attempts, I have realized that it would not be possible for me to run tests for this. Might be a laptop configuration issue.

**Comment by leecalcote** [comment]
Merge conflicts to address, @singh1203

**Comment by singh1203** [comment]
Closing this PR as I already complete it. 
Thank you

**Comment by singh1203** [comment]
Closing this PR as I already completed it.
Thank you

**Pull request closed without merging**
