### PR TITLE
Add "Open Service Mesh" to navigation menu in Meshery docs

### LINKED ISSUE #1403: [Docs] Add "Open Service Mesh" to navigation menu in Meshery docs
**Current State:**
Open Service Mesh (OSM) is a service mesh supported by Meshery. A new page documenting the Meshery adapter for OSM has been created - https://meshery.layer5.io/docs/service-meshes/adapters/osm

**Desired State:**
An entry for this service mesh should be added to the navigation menu.

Screen Shot 2020-08-16 at 2 24 00 PM

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

### PR DESCRIPTION
**Pull request by badta5te**
Signed-off-by: Pavel Mikhaylov <mikhailov.sztu@gmail.com>

**Description**

This PR fixes #1403 

**Notes for Reviewers**
Added OSM to navigation menu

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by badta5te** [comment]
> Beautiful. Nice work, @badta5te. 👍

thanks, @leecalcote

**Comment by leecalcote** [comment]
Commit signed. Alphabetical ordering. Clean. 😄

**Comment by leecalcote** [comment]
@badta5te did we invite you to join the Layer5 Slack, yet? Jump in - http://slack.layer5.io. The community is warm.

**Comment by badta5te** [comment]
> @badta5te did we invite you to join the Layer5 Slack, yet? Jump in - http://slack.layer5.io. The community is warm.

already, thanks

**Pull request merged**
