### PR TITLE
lint issues in mesh_ops_handlers.go

### PR DESCRIPTION
**Pull request by ashiscs**

### CODE REVIEW

**Comment by ashiscs** [comment]
updated correctly

**Comment by girishranganathan** [comment]
@ashiscs, this branch has build issues: https://github.com/layer5io/meshery/pull/302/checks?check_run_id=235943888#step:4:208
Anytime you commit, can you please do a local build to see if things are building on your local?
And, anytime you create a PR, can you please check if at least the "Meshery build check" is passing?

**Comment by ashiscs** [comment]
Ok sir @girishranganathan

**Comment by leecalcote** [comment]
@ashiscs has this issue been overcome? - https://github.com/layer5io/meshery/pull/302/checks?check_run_id=235943888#step:4:208

**Comment by leecalcote** [comment]
@ashiscs heads-up, you'll need to resolve merge conflicts with `handlers/mesh_ops_handlers.go` here - https://github.com/layer5io/meshery/pull/302/conflicts

**Comment by leecalcote** [comment]
@ashiscs merge conflict eliminated!

Now, we need Meshery to build. Build error here - https://github.com/layer5io/meshery/pull/302/checks?check_run_id=246281567#step:4:208

**Comment by leecalcote** [comment]
@ashiscs given all the other changes to ```handlers/mesh_ops_handlers.go```, should we close this PR and then see where we stand on lint issues?

**Comment by ashiscs** [comment]
ok sir @leecalcote

**Pull request closed without merging**
