### PR TITLE
Bump to notistack to `v3` version and refactor accordingly

### PR DESCRIPTION
**Pull request by sudhanshutech**
**Notes for Reviewers**

This PR fixes #

- [x] Bump package
- [x] Class to functional for progress bar( because Higher order comp in notistack latest version doesn't support class) and refactor
- [x] remove all `withSnackbar` (its not supported in latest package)
- [x] remove all `withSnackbar` from meshmap
- [x] Restore theme 

>[!NOTE]
>Since notistack is a standalone package and do not not depend on material ui mean toggling Material-UI theme mode to Dark/Light would not affect the appearance of snackbars. We had to create a custom component to have full control over your snackbars. Documentation is defined this: https://notistack.com/migration#breaking-changes

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by sudhanshutech** [comment]
This pr is also for https://github.com/layer5labs/meshery-extensions/pull/2223

**Comment by sudhanshutech** [comment]
there is some issues that i have to work on because according new version there doc says
image

**Comment by leecalcote** [comment]
@sudhanshutech what's missing here? Is the merging of this blocked? Does this need to be coordinated with Extensions?

**Comment by leecalcote** [comment]
@sudhanshutech merge conflict.

**Comment by leecalcote** [comment]
@sudhanshutech still a merge conflict.

**Comment by sudhanshutech** [comment]
created a new pr: https://github.com/meshery/meshery/pull/11147
closing this

**Pull request closed without merging**
