### PR TITLE
[Server] Add Support for Dry Run

### PR DESCRIPTION
**Pull request by humblenginr**
**Description**
This PR 
- Adds `Dry Run` as a stage in the Pattern processing engine.
- Upgrades `client-go` to `v0.26` and other dependent packages to their newer versions.
- Changes the response format for the requests at `api/pattern/deploy`.
Earlier, a successful response would return a concatenated string of all the messages thus generated. But now, the response structure has been changed. A JSON response will directly be sent in place of a string of concatenated messages. These messages will still be a part of the response and can be accessed as a `messages` property at the root level of the JSON response. 
- Adds another query parameter (`?dryRun`) to the `api/pattern/deploy` endpoint.
The new `Dry Run` stage is added after the `Validation` stage in the chain. When the `dryRun` query parameter is set to `true`, the Design is processed until the `Dry Run` stage and the response is returned. The output from the `Dry Run` stage is passively added to the [`Other`](https://github.com/meshery/meshery/compare/nithish/feat/dry_run?expand=1#diff-d9ca9d3ed77be7d12ef1028606145efd18872c6ed484274d95f9f6ee9c3b32b5R54) placeholder. If needed, this information can be accessed in the following stages. 
- Updates the error messages in the `Validation` stage.
The error messages from the `Validation` stage have been made more simple and more concise so that the users aren't overwhelmed by them. 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by acald-creator** [comment]
@sudo-NithishKarthik please take a look at this PR https://github.com/meshery/meshery/pull/6902
and see if this can work with your current PR?

**Review by leecalcote — CHANGES_REQUESTED** [review]
@sudo-NithishKarthik merge conflicts.

@sudo-NithishKarthik please ensure compatibility with meshery/kompose.

**Comment by sudo-NithishKarthik** [comment]
@acald-creator , your PR includes all the dependency upgrades (and more) I need for making this work. So merging your PR will be helpful. But my primal brain starts shouting on seeing the `client-go` package upgraded from `v0.24` to `v1.5`. Since this is a huge upgrade, we might have to do rigorous testing before we merge it.

**Comment by leecalcote** [comment]
Merge conflict.

**Comment by leecalcote** [comment]
Eliminated merge conflict.

**Comment by leecalcote** [comment]
Eliminating conflicts. Updating go.mod.

**Comment by leecalcote** [comment]
I'm running into:

```
go: downloading oras.land/oras-go v1.2.2
go: downloading github.com/rubenv/sql-migrate v1.3.0
go: downloading go.starlark.net v0.0.0-20230112144946-fae38c8a6d89
# github.com/layer5io/meshery/server/models/pattern/patterns/k8s
../models/pattern/patterns/k8s/k8s.go:33:77: undefined: v1.StatusApplyConfiguration
../models/pattern/patterns/k8s/k8s.go:40:99: undefined: v1.StatusApplyConfiguration
../models/pattern/patterns/k8s/k8s.go:41:10: undefined: v1.Status
```

**Comment by leecalcote** [comment]
@Revolyssup please review. This effort has stalled.

**Comment by acald-creator** [comment]
@leecalcote I didn't see this, go mod worked for me.

I couldn't checkout this PR for some reason.

**Comment by leecalcote** [comment]
@acald-creator are you able to check out with ```gh pr checkout 6903```?

**Comment by acald-creator** [comment]
@leecalcote weird it wouldn't let me on the wsl ubuntu, im back on the mac, and i was able to check out the PR

**Review by leecalcote — APPROVED** [review]

**Pull request merged**
