### PR TITLE
K8s context switcher ping redirected notify to useNotification.

### LINKED ISSUE #8617: [UI] K8s context switcher ping test is broken.
### Current Behavior

When clicking `k8s` chip in context switcher no request is made to  perform connectivity/ping test.

https://github.com/meshery/meshery/assets/79860504/70ab0a3b-3d97-474b-968c-fdc6b06864f1

### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by ShailikaS**
**Notes for Reviewers**

This PR fixes #8617 

In the code base,
**Added Line** (to Header.js): 
Screenshot 2023-09-07 at 1 50 22 PM
Screenshot 2023-09-07 at 1 52 10 PM

**Removed Line**(from Header.js):
Screenshot 2023-09-07 at 1 52 29 PM
Screenshot 2023-09-07 at 1 52 39 PM

**Video:** Notification is working but in the video proper message has not come, As my Kubernetes Config is not valid.
https://github.com/meshery/meshery/assets/107252411/21f82ac7-dd4a-4e26-b086-d5805a617d18

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
@Rajdip019 does this follow suit with our latest approach to notifications? // @aabidsofi19

**Comment by leecalcote** [comment]
Have we documented that approach?

**Review by theBeginner86 — APPROVED** [review]
LGTM

Thanks @ShailikaS

**Comment by Rajdip019** [comment]
> @Rajdip019 does this follow suit with our latest approach to notifications? // @aabidsofi19

Yes, this does comply with the new `useNotification` hook. 

Here is a documentation 
[Notification.Center.pdf](https://github.com/meshery/meshery/files/12552043/Notification.Center.pdf)

**Pull request merged**
