### PR TITLE
[docs] Update Application Management

### PR DESCRIPTION
**Pull request by theBeginner86**
**Notes for Reviewers**

This PR fixes #

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit d43eeb65d2786d06b0da590fbb053e6865b6104e at: https://654e0b18471eb56500f455d5--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 01449c84a83288bd3a6e7d01789f92cdc6f26b77 at: https://654e0e013e6d636730ca76eb--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit f58109c269deae2a3fb3f4667394a454c5b87f67 at: https://654e0f814a4416694b0bd444--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 7997d31a903911e47ff95790b2b0105da0f8dc61 at: https://654e161cdad2216ff0d90a1a--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit fb563f7b3b1a649153b9e36490efad6294921d4e at: https://654e17913e6d636f15ca75a7--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 20e63fd3c520e39e404e4c8b779cdd0e999a15f9 at: https://654e19ddc49a677166e10c74--meshery-docs-preview.netlify.app

**Review by leecalcote — APPROVED** [review]

**Pull request merged**
