### PR TITLE
Convert 2 API calls to 1 for Applications 

### PR DESCRIPTION
**Pull request by Revolyssup**
**Notes for Reviewers**

This PR changes:
1. ApplicationRequestBody to add field for cytoscape where the cyto can be passed directly
2. It expects Name in the request body and ID inside ApplicationData.ID

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
Task linked: [CU-85zrgmcp7 Send one request for Applications](https://app.clickup.com/t/85zrgmcp7)

**Comment by leecalcote** [comment]
@Chadha93 Meshery UI Applications page will need to be updated to account for this.

**Comment by Abhishek-kumar09** [comment]
Can it be merged?

**Review by Chadha93 — APPROVED** [review]
No UI changes are required then as discussed today.

**Comment by Chadha93** [comment]
Just the Lint check needs a look here. @Revolyssup

**Pull request merged**
