### PR TITLE
updated architecture page

### LINKED ISSUE #7791: [Docs] Update Meshery Architecture Page
#### Current State
- Figures used in the following sections are outdated and are in need to be updated 
  https://docs.meshery.io/concepts/architecture
  https://docs.meshery.io/guides/upgrade

- Does not include the Docker Extension Architecture description in  [architecture](https://docs.meshery.io/concepts/architecture) page  
  
#### Desired State

- Update the figures with the help of the Meshery Architecture Slide  
- Add Docker Extension architecture sub section

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by thisiskaransgit**
**Notes for Reviewers**

This PR fixes #7791 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 462122e13187cbe4658646058f9f06d2c7d0464b at: https://648709bc0a8dcb24d69ba8d5--meshery-docs-preview.netlify.app

**Comment by Ghat0tkach** [comment]
Hey @thisiskaransgit , You have missed updating the https://docs.meshery.io/guides/upgrade
Svg 😅 with

**Review by leecalcote — APPROVED** [review]
Great job, @thisiskaransgit.

**Review by leecalcote — COMMENTED** [review]
Good feedback, @DarrenDsouza7273. 👍 

Perhaps, you might submit a follow up PR? You can export individual architecture deck slides to SVG...

**Comment by thisiskaransgit** [comment]
@leecalcote, there's some more information that's left to add,on the the page, and there's a topic of discussion, with reference to the meshery adapter slide and I'll incorporate the changes in this PR.

**Comment by l5io** [comment]
🚀 Preview for commit 7c7ae45999ab254f0a5426702156e50a9066d267 at: https://6488d62f8c14db226fdbe8fc--meshery-docs-preview.netlify.app

**Comment by Ghat0tkach** [comment]
> Good feedback, @DarrenDsouza7273. 👍 
> 
> Perhaps, you might submit a follow up PR? You can export individual architecture deck slides to SVG...

@leecalcote you tagged the wrong id 🥲

**Comment by leecalcote** [comment]
> @leecalcote, there's some more information that's left to add,on the the page, and there's a topic of discussion, with reference to the meshery adapter slide and I'll incorporate the changes in this PR.

Moving forward... hasten your step with the clicking of File --> Download --> SVG, @thisiskaransgit

**Pull request merged**
