### PR TITLE
Support ignoring models in Registry

### PR DESCRIPTION
**Pull request by Yashsharma1911**
**Notes for Reviewers**

This PR fixes #

This PR adds a Status selector in the details tab which allows to change the status of models for now, we will soon also support changing status for components and relationships from UI

This PR also fixes the issue https://github.com/meshery/meshery/issues/10340

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by Yashsharma1911** [comment]
Dependent Meshkit PR - https://github.com/meshery/meshkit/pull/456

**Review by leecalcote — COMMENTED** [review]
Let's hold off adding new functionality until the existing features work / are useful.

**Comment by leecalcote** [comment]
`do-not-merge` label removed. Note the merge conflict.

**Comment by leecalcote** [comment]
@Yashsharma1911 this will need to move to `status` with the MeshKit change, too. The `meshery/schemas` will need updated, too.

**Comment by Yashsharma1911** [comment]
This PR needs code cleanup

**Comment by Yashsharma1911** [comment]
New Meshkit release will fix the Mehery UI fail

**Pull request merged**
