### PR TITLE
fix the grammatical issue #9810

### PR DESCRIPTION
**Pull request by Althaf66**
**Notes for Reviewers**

This PR fixes the issue #9810 

@leecalcote ,Fixed the grammatical error in the mesheryctl

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by goldfishdolphin — APPROVED** [review]
Looking Good. 👍 
Thanks @Althaf66

**Comment by saurabh100ni** [comment]
Hi @Althaf66  ,

Thanks for your PR! 🚀 I encourage you to share this in the Meshery Development Meet tomorrow at 8:30 PM IST. Share your screen, and walk us through it. It's cool to take and share feedback. Check the Doc [here](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit) to include this PR.

You're welcome in the meeting today

Cheers, and Happy New Year 🥂,

Subscribe to [community calendar ](https://layer5.io/community/calendar)for more details of meetings at Layer5.

**Review by goldfishdolphin — APPROVED** [review]
Good work!

**Comment by leecalcote** [comment]
Thanks, @Althaf66. See the [failed check annotations](https://github.com/meshery/meshery/actions/runs/7384544622/job/20087775484?pr=9811)? Fixing these would be a great next step for you.

**Review by leecalcote — APPROVED** [review]

**Comment by yash37158** [comment]
Good work @Althaf66 🎉, also if you take a look at the linting issue

**Pull request merged**
