### PR TITLE
docs fix quick start copy to clipboard button

### LINKED ISSUE #9914: [Docs] Quick Start: Copy to clipboard not working
### Current State

image_720

Page - 

### Desired State

Should copy 

```
curl -L https://meshery.io/install | PLATFORM=kubernetes bash -
```

No `$` included.

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by ranjeetxsingh**
**Notes for Reviewers**

This PR fixes #9914  [Docs] Quick start : copy to clipboard not working issue

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit f57b9d4c370ab4bef3b7f1dee2452dc9c99ff0b5 at: https://65b2c46c65fa432dfef17aa6--meshery-docs-preview.netlify.app

**Review by goldfishdolphin — APPROVED** [review]
Looking good.  The code is being successfully copied to the clipboard.

Thanks @ranjeetxsingh!

**Comment by goldfishdolphin** [comment]
LGTM. 

Thanks @ranjeetxsingh!

**Review by sandramsc — APPROVED** [review]
LGTM - Code is copied to the clipboard without the dollar sign ($).

**Comment by leecalcote** [comment]
> LGTM - Code is copied to the clipboard without the dollar sign ($).
Thank you for verifying this functionality, @sandramsc 👏

**Review by leecalcote — APPROVED** [review]

**Comment by leecalcote** [comment]
Whoo-hoo! Congrats, @ranjeetxsingh 🎈

**Pull request merged**
