### PR TITLE
Fix unnecessary scrollbars showing up on code snippets

### LINKED ISSUE #7072: [Docs] Unnecessary scroll bars in code snippets
#### Current Behavior

Scroll bars in code sections even if not needed.

#### Expected Behavior

No scroll bars should be there unnecessarily.

#### Screenshots/Logs

Screenshot from 2023-02-13 10-46-47

#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Any
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by chinu-anand**
Signed-off-by: Chinu Anand <chinuanand81@gmail.com>

**Notes for Reviewers**

This PR fixes #7072 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit ebbe265002b2cd1dfffcc7159b04af0eb61cbf8a at: https://63eb4546e61f625f236d6586--meshery-docs-preview.netlify.app

**Review by Avi-88 — COMMENTED** [review]
I haven't checked if setting overflow to auto will also work , but if it does , then it would be better to have it as auto instead of hidden.

**Comment by Chadha93** [comment]
@chinu-anand Let's discuss this on the Meshery Dev call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#) if you would. :)

**Comment by leecalcote** [comment]
> I haven't checked if setting overflow to auto will also work , but if it does , then it would be better to have it as auto instead of hidden.

Thanks for offering review, @Avi-88 👍

**Comment by l5io** [comment]
🚀 Preview for commit 255f0f7f6d2bd386c7e41556f428423a82287526 at: https://63ec7768fcaaba7179a1bd9c--meshery-docs-preview.netlify.app

**Review by leecalcote — APPROVED** [review]
Excellent. Wonderful, @chinu-anand. Thank you. 👍

**Comment by chinu-anand** [comment]
@leecalcote I have created a component named 'code.html' in this PR which will create modern code snippets with clipboard.js integration (was already there but not used). So if all the existing code snippets in meshery docs are wrapped with this component, it will be much better.

**Comment by Avi-88** [comment]
Hi @leecalcote and @chinu-anand , like I mentioned earlier the overflow hidden will cause issues like this 
image

**Comment by chinu-anand** [comment]
@Avi-88 those are not normal code snippets, those are custom clipboard.js implemented code snippets. I am working on this in a different PR. Thanks for reporting the unusual behaviour though.

**Comment by Avi-88** [comment]
> @Avi-88 those are not normal code snippets, those are custom clipboard.js implemented code snippets. I am working on this in a different PR. Thanks for reporting the unusual behaviour though.

Oh cool, sorry my bad i should've checked for it beforehand.

**Pull request merged**
