### PR TITLE
Update terminology from `pattern` to `design` in configuration management guides

### PR DESCRIPTION
**Pull request by devhindo**
following on: meshery/meshery#12890 and meshery/meshery-kuma#444

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 6a8dba695d130aeffd980cc1daf23d7bd81dd850 at: https://676e60545623f5cd5de9db6c--meshery-docs-preview.netlify.app

**Review by lekaf974 — APPROVED** [review]

**Review by lekaf974 — CHANGES_REQUESTED** [review]
Style having pattern references in some documentation pages 

ex: https://676e60545623f5cd5de9db6c--meshery-docs-preview.netlify.app/project/contributing/contributing-cli

**Comment by devhindo** [comment]
done @lekaf974

**Comment by l5io** [comment]
🚀 Preview for commit f440a568a2ed141a281a25e03f049f125e1965d1 at: https://677123b05623f5d0d8e9dcf7--meshery-docs-preview.netlify.app

**Review by lekaf974 — APPROVED** [review]
LGTM

**Review by leecalcote — APPROVED** [review]

**Comment by leecalcote** [comment]
Thank you, @lekaf974. 👏

**Pull request merged**
