### PR TITLE
fixes issue Hyperlink not visible under dark mode ##7265

### LINKED ISSUE #7265: [UI]-Hyperlink under dark mode not visible
#### Current Behavior
The Hyperlink is not properly visible under dark mode.
raw

#### Desired Behavior
Color should be changed to make it visible
update

I have sucessfully made the changes @leecalcote just need your permission to PR can you please assign me.

#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by parmishh**
Fixes: #7265 
Fixes: https://github.com/meshery/meshery/issues/7265

**Notes for Reviewers**

This PR fixes #7265 

@leecalcote 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by Chadha93** [comment]
> [Click on the image](https://app.codesee.io/r/reviews?pr=7266&src=https%3A%2F%2Fgithub.com%2Fmeshery%2Fmeshery) for a new way to code review
> [Review these changes using an interactive CodeSee Map](https://app.codesee.io/r/reviews?pr=7266&src=https%3A%2F%2Fgithub.com%2Fmeshery%2Fmeshery)
> 
> #### Legend
> CodeSee Map legend

When this was added? :eyes:

**Review by Chadha93 — APPROVED** [review]
@parmishh Thank you for the PR, will you please look into eslint error? Please add a screenshot of your change.

**Review by Chadha93 — CHANGES_REQUESTED** [review]
@parmishh Thank you for the PR, will you please look into eslint error? Please add a screenshot of your change.

**Comment by parmishh** [comment]
@Chadha93 screenshot of the changes
changes

**Comment by Chadha93** [comment]
> @Chadha93 screenshot of the changes changes

Oh no I meant the UI changes screenshots.

**Comment by parmishh** [comment]
@Chadha93 
it looks good and matching with the theme both in dark and light mode so I have not made further changes

update

update2

**Comment by parmishh** [comment]
@Chadha93 actually that issue is already resolved by someone recently in #7191

**Comment by Chadha93** [comment]
> @Chadha93 actually that issue is already resolved by someone recently in #7191

Gotcha, please fix the eslint error then.

**Comment by leecalcote** [comment]
@Chadha93 that was added only about five hours ago. I don’t know that we want to keep it. I’m interested in your and everyone’s opinion after you try it a few times. It was added facilitate having Meshery listed in on opensourcehub dot io website.

**Comment by parmishh** [comment]
@leecalcote are you  referring to meshery logo or the hyperlink link color which mixed up with the background.
because I see the link theme-color issue is not yet updated.

**Pull request closed without merging**
