### PR TITLE
meshsync v0.6.19

### PR DESCRIPTION
**Pull request by leecalcote**
Signed-off-by: Lee Calcote <lee.calcote@layer5.io>

**Notes for Reviewers**

This PR fixes #

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Meshery Server crashes....

**Comment by leecalcote** [comment]
We won't be able to move forward on @KiptoonKipkurui's MeshSync enhancements until this issue is resolved.

**Comment by Aisuko** [comment]
I will check this later.

**Review by Aisuko — CHANGES_REQUESTED** [review]
I suggest to change this line. https://github.com/meshery/meshery/blob/56798bcca7f3977274a508443b1f9a3999fbe414/go.mod#L7

And it should replace by `github.com/docker/docker => github.com/moby/moby v20.10.24+incompatible` According to the solution of the security issue below.

Furthermore, it is also an `High` security issue of our project. More about is here.https://github.com/meshery/meshkit/security/dependabot/59


And I am working on update this in meshkit. And It needs to test in every adapter, make sure it will work well. Here is an example: https://github.com/meshery/meshkit/pull/389

**Comment by leecalcote** [comment]
Thank you very much for this, @Aisuko

**Pull request closed without merging**
