### PR TITLE
Add Mutation in pattern engine

### PR DESCRIPTION
**Pull request by Revolyssup**
Signed-off-by: revolyssup <ashishjaitiwari15112000@gmail.com>

**Description**
This PR adds support for deploying CRDs first before deploying any other resources. Further such mutations can be later added.

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Adding the “hold” label for new features until Meshery Operator and its controllers are constantly deploying reporting status, and underlying. Let’s raise the quality bar in that area as a precursor to new work here. 👍

**Comment by leecalcote** [comment]
> Adding the “hold” label for new features until Meshery Operator and its controllers are constantly deploying reporting status, and underlying. Let’s raise the quality bar in that area as a precursor to new work here. 👍

@Revolyssup how will we know when this prerequisite is met? I suggest using the [Meshery Test Plan](https://docs.google.com/spreadsheets/d/13Ir4gfaKoAX9r8qYjAFFl_U9ntke4X5ndREY1T7bnVs/edit#gid=0).

**Comment by leecalcote** [comment]
@Revolyssup is the Meshery Operator/MeshSync clean up complete?

**Comment by leecalcote** [comment]
> @Revolyssup is the Meshery Operator/MeshSync clean up complete?

@Revolyssup here's another one - https://github.com/meshery/meshery/pull/6431

**Comment by leecalcote** [comment]
@Revolyssup let's ensure this lands, too - https://github.com/meshery/meshery/pull/6409

**Comment by leecalcote** [comment]
What controls do we expose to control this behavior?

Under what circumstances will CRDs be automatically deployed and under which will they not?

**Comment by Revolyssup** [comment]
> What controls do we expose to control this behavior?
> 
> Under what circumstances will CRDs be automatically deployed and under which will they not?

With this change, **Always** the CRDs in a design will be deployed first. Users can't override this.

**Review by leecalcote — APPROVED** [review]

**Review by leecalcote — APPROVED** [review]

**Pull request merged**
