### PR TITLE
Add updated_after query parameter

### PR DESCRIPTION
**Pull request by Revolyssup**
Signed-off-by: Ashish Tiwari <ashishjaitiwari15112000@gmail.com>

**Notes for Reviewers**

This PR adds `updated_after` query parameter on applications and patterns on REST as well as graphql.
The format is YYYY-MM-DD HH:MM:SS
Example: `/api/pattern?updated_after=2023-01-20+00:58:00`

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — CHANGES_REQUESTED** [review]
Missing API docs.

**Comment by Revolyssup** [comment]
> Missing API docs.

Done

**Comment by l5io** [comment]
🚀 Preview for commit 899c11e9ac018b23977734c2f1c0ad6e91e0e0d7 at: https://63ca8c02621eb41f28255726--meshery-docs-preview.netlify.app

**Review by leecalcote — APPROVED** [review]

**Review by leecalcote — CHANGES_REQUESTED** [review]
6 or so golang lint checks failing.

**Comment by l5io** [comment]
🚀 Preview for commit 078ed52eb0cf43dc49302fc1da0a1f3e034f7aec at: https://63cac285e6201b695b95667b--meshery-docs-preview.netlify.app

**Pull request merged**
