### PR TITLE
[UI] Meshery Operator and MeshSync Chips overlapped fixed

### LINKED ISSUE #3855: [UI] Meshery Operator and MeshSync chips getting overlapped
#### Current Behavior
At a reduced screen size the meshery operator chip and meshsync chip overlap 

#### Desired Behavior
They should not overlap and be distinct

#### Screenshots/Logs
SAFARI-

Screenshot 2021-08-11 at 11 30 04 PM

CHROME-

Screenshot 2021-08-11 at 11 34 02 PM

#### Environment

- Browser: Chrome Safari 
- Host OS: Mac 
- Meshery Server Version: stable
- Meshery Client Version: stable
- Platform: Docker 

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by NikhilSharma03**
Signed-off-by: Nikhil Sharma <nikhilsharmamusic2000@gmail.com>

**Description**
<h2>This PR fixes #3855 </h2>

- The Meshery Operator and MeshSync Chips were overlapping
129081588-32f6a293-2d8e-47ed-98ee-0605ca58ece9

## After Changes
Screenshot from 2021-08-14 18-37-28

Screenshot from 2021-08-14 18-37-37

**Notes for Reviewers**
- Let me know if there are any other changes we can make.

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by warunicorn19 — APPROVED** [review]
Good job, @NikhilSharma03, tested it locally on safari and chrome, works great!🎉, thanks @NikhilSharma03

**Comment by leecalcote** [comment]
@NikhilSharma03 is dipping into Meshery  UI... this is great to see. 😀

**Comment by sudo-NithishKarthik** [comment]
Resolved the merge conflicts ...

**Comment by sudo-NithishKarthik** [comment]
The cypress test is failing because of an issue with `subscriptions-transport-ws` library.
It is stated in the docs that the library is no longer actively maintained and suggests that we use [graphql-ws](https://github.com/enisdenjo/graphql-ws) instead.

Downgrading `subscriptions-transport-ws` to `0.9.16` seems to be fixing the issue.

Related Issue : [#808](https://github.com/apollographql/subscriptions-transport-ws/issues/808)

// @leecalcote  @dhruv0000 @utkarsh-pro  @meshery/meshery-ui-maintainers

**Comment by dhruv0000** [comment]
> The cypress test is failing because of an issue with `subscriptions-transport-ws` library.
> It is stated in the docs that the library is _no longer actively maintained_ and suggests that we use [graphql-ws](https://github.com/enisdenjo/graphql-ws) instead.
> 
> Related Issue : [#808](https://github.com/apollographql/subscriptions-transport-ws/issues/808)
> 
> Downgrading `subscriptions-transport-ws` to `0.9.16` seems to be fixing the issue for now.
> 
> // @leecalcote @dhruv0000 @utkarsh-pro @meshery/meshery-ui-maintainers

Seems like the tests are passing.

**Comment by dhruv0000** [comment]
Either case `graphql-ws`'s protocol ` GraphQL over WebSocket Protocol` is **not** cross compatible with `subscriptions-transport-ws`'s protocol. 
https://github.com/enisdenjo/graphql-ws#disclaimer

And GQLGEN supports `subscriptions-transport-ws`'s protocol.
https://stackoverflow.com/questions/67675102/getting-websocket-connection-to-ws-localhost7080-query-failed-on-connecting

**Comment by sudo-NithishKarthik** [comment]
> Seems like the tests are passing.

Yes, seems like it only happens sometimes.

**Comment by sudo-NithishKarthik** [comment]
> Either case `graphql-ws`'s protocol ` GraphQL over WebSocket Protocol` is **not** cross compatible with `subscriptions-transport-ws`'s protocol.
> https://github.com/enisdenjo/graphql-ws#disclaimer
> 
> And GQLGEN supports `subscriptions-transport-ws`'s protocol.
> https://stackoverflow.com/questions/67675102/getting-websocket-connection-to-ws-localhost7080-query-failed-on-connecting

Ok, anyways, it probably is not something that we have to worry about _now_ since it doesn't seem to be causing much of a trouble, but something to be aware of.

**Review by sudo-NithishKarthik — APPROVED** [review]

**Pull request merged**
