### PR TITLE
[WIP] Enforced CASL in UI

### LINKED ISSUE #9721: Implementation of permission framework in Meshery UI
### Current Behavior

Meshery UI lacks a permissions framework. The existing internal implementation is extremely simple and fragile and is “does the user have a role with this name assigned?“. So, it must be completely set aside / rewritten.

### Desired Behavior

We're aiming to implement CASL which is dynamic and extensible permissions framework, 

- Render UI based on user's permission within a selected organization.
- Improved user experience with the ability to re-render the UI after switching the organization.
- Shift from role-based implementation to keys-based implementation for granular control.

### Implementation

- [X] [UI] Integrate CASL in meshery UI. #8945 @Mohith234 
- [x] [Server] Add keys API in meshery UI as capabilities. #9731 
- [x] [Server] Seed new keys for Meshery in remote and local provider [#1832](https://github.com/layer5io/meshery-cloud/pull/1832/files) #9771 
- [x] [UI] Use Redux, Rtk to update CASL ability with fetched keys to make it available to the application. #9778 
- [x] [UI] Add permission constant file in UI and Enforce CASL in UI #9778 
- [ ] [UI] Expose CASL in MeshMap extension point

### Acceptance Tests

- [x] Rerender UI on switching organization.

### Mockups

No mockups provided. Visual representation may be added as needed.

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by Yashsharma1911**
This PR fixes #9721

# Meshery UI Authorization Enhancement

### Enhancing Authorization with CASL:

In this PR, several key improvements have been made to Meshery's UI, with a primary focus on enhancing authorization and access control. The introduction of CASL (Code Access Security Language) is a pivotal step in achieving this goal.

#### CASL Setup and Permission Constants:
- [x] **CASL Integration:** Implemented CASL, a powerful and flexible JavaScript library for handling permissions and access control within the Meshery UI.
- [x] **Permission Constants:** Added explicit permission constants for Meshery, providing a centralized and easy-to-maintain approach to managing permissions throughout the codebase.

### Import Alias Refactoring:

In an effort to improve code readability and maintainability, there has been a refactoring of import aliases. The shift from "../../" to "@/component" for root-level directories ensures cleaner and more concise references in the UI codebase.

### Dynamic Abilities Update:

To adapt to changing organizational contexts, the Meshery UI now dynamically fetches new abilities upon organization switching. The integration includes maintaining keys in session storage and preventing splashing unauthorized access on UI.

### Updated Pages with Permission Integration:

  - [X] Meshery Pattern (both table and grid)
  - [x] Meshery Filters (both table and grid)
  - [x] Connections page (both connections and Meshsync table)
  - [x] Settings
  - [x] Environment
  - [x] Workspace
  - [x] Extension page
  - [x] Performance page
  - [ ] Service Mesh
 
**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Merge conflict

**Comment by leecalcote** [comment]
@Yashsharma1911 did you finish today? It seems that the week escaped you. You were *this* close. :/

**Comment by Yashsharma1911** [comment]
Resolving conflicts

**Comment by Yashsharma1911** [comment]
LGTM now merging

**Pull request merged**
