### PR TITLE
Updated lightbox.js & main.js

### PR DESCRIPTION
**Pull request by ENUMERA8OR**
For lightbox.js,

In this modified version, I've replaced all arrow functions with traditional function syntax. This should resolve the issues related to ES6 compatibility. The functionality of the code remains the same, but it's now compatible with older JavaScript environments that don't support ES6 features.

For main.js,

1.Added missing semicolons throughout the code.

2.Changed the IIFE (Immediately Invoked Function Expression) syntax to use parentheses correctly: (function($) { ... })(jQuery);

3.Removed the comma after the init function in the Search object.

4.Replaced arrow functions with traditional function syntax for better compatibility.

5.Made sure all variables are properly declared with var.

For zIndex.js,

1.Added a JSHint directive at the top of the file to specify ES6 usage: /* jshint esversion: 6 */

2.Kept the ES6 features intact, including:

3.export statement
  const declaration
  Default parameter
  Arrow function syntax
  let declarations

4.Removed the template literal syntax warning by using standard string concatenation (although the original code didn't use template literals, so this wasn't necessary to change).

5.The "Expected an assignment or function call" warning is not applicable in this case, as the function is correctly returning a value.

For webApis.js,

1.Added a JSHint directive at the top of the file to specify ES11 usage: /* jshint esversion: 11 */
This addresses all the ES6 and ES11 feature warnings, including:

export statements
let declarations
Arrow function syntax
Optional chaining

2.Kept all ES6 and ES11 features intact, as they are now explicitly allowed by the JSHint directive.

3.No other changes were necessary to the actual code, as the linter suggestions were all related to ECMAScript version compatibility.

For connections.spec.js,

1.Added a JSHint directive at the top of the file to specify ES11 usage: /* jshint esversion: 11 */
This addresses all the ES6, ES8, and ES11 feature warnings, including:

import statements
const and let declarations
Arrow function syntax
Async functions
Destructuring binding
Template literal syntax
For...of loops
Trailing commas in function arguments and object literals

2.Kept all ES6, ES8, and ES11 features intact, as they are now explicitly allowed by the JSHint directive.

3.Removed trailing commas from function calls and object literals where they were causing issues (ES8 feature).

4.No other changes were necessary to the actual code, as the linter suggestions were all related to ECMAScript version compatibility.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 8ff23292467aa00f46255e8d4b4d322b61f9fde1 at: https://669d7cab59d015502760b362--meshery-docs-preview.netlify.app

**Comment by leecalcote** [comment]
Thanks, @ENUMERA8OR. Do we have an open issue on this?

**Comment by vishalvivekm** [comment]
> Thanks, @ENUMERA8OR. Do we have an open issue on this?

@ENUMERA8OR ?

**Comment by ENUMERA8OR** [comment]
Don't think so but will check again just to be sure...

**Comment by ENUMERA8OR** [comment]
There is no issue I could find regarding this specifically...
@leecalcote 
@vishalvivekm

**Comment by l5io** [comment]
🚀 Preview for commit c95f7c08089af7ea3cd71cf830587c42945c71fa at: https://66a368d9a07a1700ae8f0dd9--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit c035dda60146c170edc4b1cfb90c78517660a5e1 at: https://66a36f6a1fbfd6089aec3b89--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 5ef0d27809ca0e9b8d369b389bad00f101abc208 at: https://66a37244812e41008582927a--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 672da9aa9f33aabc4db6e4f81c96e3b5caa6d0cd at: https://66a696ed02b89e7880008ec5--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit fef1a31df3b398cd7d60e309ab15922a9ea968eb at: https://66a7fa03b0e41974b8cff327--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 1fe32cc2d12ef0ab13fcfba084dd2ee45785e75f at: https://66a7fe6e99d8e97acc8b81e6--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 1fc264dd63f76c1da8c241b14a5f2d3e695aa692 at: https://66cbbf73d4764d4623cdf391--meshery-docs-preview.netlify.app

**Comment by ENUMERA8OR** [comment]
A call to maintainers, please review...

**Pull request closed without merging**
