### PR TITLE
[UI] Filter publish, unpublish, clone 

### PR DESCRIPTION
**Pull request by Chadha93**
Signed-off-by: Gaurav Chadha <gauravchadha1676@gmail.com>

**Notes for Reviewers**

- [x] Fixes broken publish operation in filters UI.
- [x] Cards button responsiveness fix.
- [x] Updated toaster verbiage
- [x] [Server] - clone and unpublish operation needs an update in the backend (meshery-cloud not accepting id) @MUzairS15 

This PR fixes #

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Chadha93** [comment]
Server/Cloud needs an update wrt clone and unpublish. Discussed with @MUzairS15

**Comment by Chadha93** [comment]
@Abhishek-kumar09

**Review by theBeginner86 — APPROVED** [review]
LGTM

**Comment by theBeginner86** [comment]
Conflicts resolved.

**Comment by theBeginner86** [comment]
Thanks @harkiratsm @Chadha93

**Review by theBeginner86 — APPROVED** [review]

**Comment by theBeginner86** [comment]
> [Server] - clone and unpublish operation needs an update in the backend (meshery-cloud not accepting id)

This has been fixed in a recent PR in Remote Provider 👍

**Pull request merged**
