### PR TITLE
Added support for k8s pattern generation

### PR DESCRIPTION
**Pull request by Revolyssup**
**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Revolyssup** [comment]
@leecalcote  test out the changes locally if you can
Sidenote- For remote provider, config gets cached, cross on the chip and "discover cluster", 
For local provider- it will happen everytime you start 
it takes at max 2 min and minimum 1 minute for all components to be registered

**Comment by leecalcote** [comment]
This is working for me on the Remote Provider. 👍

**Comment by leecalcote** [comment]
We seem to be conflating Kubernetes and "core". Let's clarify these two terms and their use.

**Review by leecalcote — APPROVED** [review]

**Comment by Revolyssup** [comment]
> We seem to be conflating Kubernetes and "core". Let's clarify these two terms and their use.

"kubernetes" are the api-resources returned by k8s.
"core" are the capabilities that meshery natively packages

**Comment by Revolyssup** [comment]
> > We seem to be conflating Kubernetes and "core". Let's clarify these two terms and their use.
> 
> "kubernetes" are the api-resources returned by k8s. (so components that can be handled by k8s)
"core" are the capabilities that meshery natively packages

**Comment by leecalcote** [comment]
I'm getting that twinkle, twinkle little star song playing in my head... I don't think that I can hold out much longer, @utkarsh-pro

**Review by utkarsh-pro — APPROVED** [review]
LGTM.

**Pull request merged**
