### PR TITLE
move dark mode under preferences menu

### LINKED ISSUE #7377: [UI]Move the dark mode option under preferences section
#### Current Behavior

Currently, dark mode option is in the dropdown section under the profile
image

#### Desired Behavior

The dark mode option could be moved to the preference section under the general category maintaining proper ui
image

#### Implementation

Move the dark mode component from the User.js file under the preferences section

#### Mockups

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by sudhanshutech**
**Notes for Reviewers**

This PR fixes #7377 
The dark mode section is moved under preferences in general section

https://github.com/meshery/meshery/assets/90546692/70b84cfb-2c6a-4c3d-b6fe-f4c79bd6db22

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
This is great. Please use the same component with label placement for this theme section.

**Review by leecalcote — CHANGES_REQUESTED** [review]
Pending resizing

**Review by leecalcote — CHANGES_REQUESTED** [review]
Pending resizing

**Comment by sudhanshutech** [comment]
> Pending resizing
are you referring to this
image

**Pull request merged**
