### PR TITLE
[CI] Restructure makefile

### PR DESCRIPTION
**Pull request by leecalcote**
Signed-off-by: leecalcote <leecalcote@gmail.com>

**Description**

This PR organizes the Makefile by section and breaks out global variables into a separate file.

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by Abhijay007 — COMMENTED** [review]
Suggestion: it will be great if we include `default` target in the `makeFile` and add the following instructions related to different targets/commands so that in case the user just run `make` will get the instructions to follow further targets and get an idea about which commands to run next in order to run, build, or test, etc.

**Comment by leecalcote** [comment]
@Abhijay007 good suggestions. Does `all` achieve our desired "default"?

**Comment by leecalcote** [comment]
@Abhijay007, I did another pass, adding the ability for the makefile to self-document, printing help when `make` is run by itself.
Screen Shot 2022-03-27 at 9 30 39 PM

**Comment by Abhijay007** [comment]
LGTM 👍

**Comment by leecalcote** [comment]
Thanks for this review @Abhijay007

**Pull request merged**
