### PR TITLE
check if package.json has changed before caching node_modules

### PR DESCRIPTION
**Pull request by anirudhjain75**
Signed-off-by: Anirudh Jain <anirudh.jain@outlook.com>

### CODE REVIEW

**Comment by kushthedude** [comment]
This check is absurd, let me push my commit to this branch for the CI fix.

**Comment by leecalcote** [comment]
Thank you for taking this on, @anirudhjain75. What an eyesore that red ❌has been in every PR.

**Comment by anirudhjain75** [comment]
This PR just says that this is one way to solve it... It was annoying me with failed emails

**Comment by leecalcote** [comment]
@kushthedude the feedback you left here is not aligned with our code of conduct and is unbecoming of a Layer5 community member.

**Pull request closed without merging**
