### PR TITLE
deprecated version property fix

### LINKED ISSUE #11875: [CI] `version` is a deprecated property of Docker Compose files
### Current Behavior
Meshery users who deploy Meshery on Docker using `mesheryctl system start` as a platform see the following warning:

```
.../.meshery/meshery.yaml: `version` is obsolete
```

### Desired Behavior
Ideally, users don't see any warning message.

### Implementation
1. Remove the`version` property from Meshery's docker-compose files under the `/install` folder.

### Acceptance Tests
1. Users can still `system start` a Meshery deployment on Docker, but don't see this warning message.

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
- Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)
- 🧪 [Meshery Test Plan Spreadsheet](https://docs.google.com/spreadsheets/d/13Ir4gfaKoAX9r8qYjAFFl_U9ntke4X5ndREY1T7bnVs/edit#gid=0)

### PR DESCRIPTION
**Pull request by Raghav1783**
**Notes for Reviewers**

This PR fixes #11875 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by vishalvivekm** [comment]
@Raghav1783 
Let's discuss this PR on Meshery development call today. Adding it as an agenda item to the meeting minutes.

Timing: 9:00 AM CT
Meeting minutes: [Google Docs](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit)
Meeting link: [meet.layer5.io/meshery](https://meet.layer5.io/meshery)

**Comment by Ashparshp** [comment]
@Raghav1783, Join meeting please and also, [join slack.](https://join.slack.com/t/layer5io/shared_invite/zt-2pyliaxz6-dAud7zIWr1NzB5mAc5ukCg)

**Comment by Raghav1783** [comment]
@Ashparshp i have joined slack, what should i do with this pr can anyone guide me?

**Review by leecalcote — APPROVED** [review]
Thanks, @Raghav1783 👍

**Pull request merged**
