### PR TITLE
Feat/rvm description/#1452

### PR DESCRIPTION
**Pull request by MoeRayo**
**Description**
The addition of extra RVM note for windows user.

This PR fixes #
It fixes issue #1452 opened by @PluckyPrecious 

**Notes for Reviewers**
The new addition can be seen by scrolling to `Set up your development environment`  in the docs
Screenshot_2020-08-26 Markdown Live Preview

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by PluckyPrecious** [comment]
Hi, @MoeRayo need help getting through? Please head over to the #first-timers lounge on the Layer5 slack community.  PS: your branch should be `feat/MoeRayo/1452` 👍🏽

**Comment by leecalcote** [comment]
@MoeRayo this was looking good. 👍

**Comment by MoeRayo** [comment]
okay, noted! thanks @PluckyPrecious

**Comment by MoeRayo** [comment]
@leecalcote Yea, thanks. i thought I missed some things, so I closed it...

**Pull request closed without merging**
