### PR TITLE
[mesheryctl] Consider OS specific paths in system config CLIs

### LINKED ISSUE #1894: [mesheryctl] `system config` assumes user's OS is Mac or Linux
**Description**
`mesheryctl system config aks` configure access to an AKS cluster using the `az` cli. It writes a kubeconfig file to `/tmp`, which is not a filesystem location that is compatible with Windows.
The same is the case with other Kubernetes provider like minikube & GCP, all the scripts should be OS-Aware and should handle the stuff.

**Expected Behavior**
All `mesheryctl` commands should be OS-agnostic or take the OS into considering and support each OS specifically.

**Environment:**
- Host OS: Windows
- Meshery Version: v0.4.18

**Solution:**
This issue can be solved by writing the kubeconfig file to the same location of other Meshery application files: `$HOME/.meshery`

### PR DESCRIPTION
**Pull request by hexxdump**
**Description**
mesheryctl system config XXX CLIs were generating kubeconfig.yaml
in $HOME directiory, this works only for *nix variant OSes.
Made changes to consider Windows OS as well.

This PR fixes #1894

**Notes for Reviewers**
I have tested the file path and folder creation-related logic independently on linux and Windows OSes.
Could not test all the config types due to the non-availability of setups.
TODO: convert the entire code in scripts.go to golang code, rather than relying on bash/sh scripts.

**[Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.
 
Signed-off-by: Hussaina Begum Nandyala <hexxdump@gmail.com>

### CODE REVIEW

**Comment by leecalcote** [comment]
Outside of the govet checks, I think this looks good.

**Review by navendu-pottekkat — COMMENTED** [review]
Will the usage of MeshKit and k8s go-client be on a future PR?

Suggestion for failing lint checks is to use [golangci-lint](https://github.com/golangci/golangci-lint) and install it locally and run it. It will show the lines where the lint check fails.

**Comment by navendu-pottekkat** [comment]
This is the lint error shown when I ran it locally-

Screenshot from 2021-02-18 09-42-42

In the lines mentioned, the print statement has 3 `%s` and there are only 2 string arguments passed.

**Comment by hexxdump** [comment]
> This is the lint error shown when I ran it locally-
> 
> Screenshot from 2021-02-18 09-42-42
> 
> In the lines mentioned, the print statement has 3 `%s` and there are only 2 string arguments passed.

Thanks @navendu-pottekkat ! Fixed the issue.

**Comment by hexxdump** [comment]
> Will the usage of MeshKit and k8s go-client be on a future PR?
> 
> Suggestion for failing lint checks is to use [golangci-lint](https://github.com/golangci/golangci-lint) and install it locally and run it. It will show the lines where the lint check fails.

Will take care of the go-client implementation in new PR.

**Review by leecalcote — APPROVED** [review]
Good, good. Forward progress.

**Pull request merged**
