### PR TITLE
[UI] Made the Search Fully functional

### LINKED ISSUE #5922: [UI] Deployment Modal: Search dysfunctional
**Description**
Search doesn't seem to work with the Deployment modal. This screenshot w what is taken from the Designs page.

**Screenshots**

Screen Shot 2022-07-28 at 2 16 56 PM

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by harkiratsm**
Signed-off-by: harkiratsm <multaniharry714@gmail.com>

**Description**

This PR fixes #5922

**Notes for Reviewers**

https://user-images.githubusercontent.com/71957674/182403481-96712315-00ef-44fc-8fa5-f6c8d38e9509.mp4

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Review by adithyaakrishna — APPROVED** [review]
LGTM

**Comment by adithyaakrishna** [comment]
@harkiratsm Let's wait for @Chadha93 's review on this PR

**Comment by leecalcote** [comment]
Thank you, gents. 👍

**Review by leecalcote — APPROVED** [review]
This is working great in each of my tests. 👍

**Pull request merged**
