### PR TITLE
[doc] fix routing for command-reference redirects

### LINKED ISSUE #4565: [Docs] Breadcrumbs routing issue
#### Current State
Once we go to `home / reference / command reference`, and click on an argument of any main command say, `apply` argument  of  `perf` command, it takes you to `home / reference / mesheryctl / perf / mesheryctl perf apply`. As of now, we can't go back one step backward on `home / reference / mesheryctl / perf` by clicking on `perf` due to the routing issue on this page https://docs.meshery.io/reference/mesheryctl/perf/apply. Similarly we cant go to these:

-  `home / reference / mesheryctl / mesh` by clicking on `mesh` on this page
https://docs.meshery.io/reference/mesheryctl/mesh/validate.
-  `home / reference / mesheryctl / mesheryctl pattern` by clicking on `pattern` on this page https://docs.meshery.io/reference/mesheryctl/apps/onboard.
- `home / reference / mesheryctl / mesheryctl app` by clicking on `app` on this page https://docs.meshery.io/reference/mesheryctl/apps/onboard.

#### Desired State
Redirect user to desired page.

#### How can it be solved ?
A similar issue has been solved using this PR #4564 . You can see this PR as a reference to solve this issue. If you still have any doubt, feel free to reach out.

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by Et-008**
- Added redirect_from, for all links in command-refernce page

Signed-off-by: Arun Et <arunet008@gmail.com>

**Description**

This PR fixes #4565

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit d85799d84a078b3203925f59eb08b8c9aec8cd1b at: https://618b78e8bf23b69306033efa--meshery-docs-preview.netlify.app

**Review by shubham-tyagi — APPROVED** [review]
No breadcrumbs routing issue on every command page now. Great stuff @Et-008, LGTM !!!

**Review by alphaX86 — APPROVED** [review]
No issues faced for now... So LGTM

**Review by warunicorn19 — APPROVED** [review]
Thank you @Et-008

**Pull request merged**
