### PR TITLE
[Meshery] DockerApp source files

### PR DESCRIPTION
**Pull request by nunix**
#### Description
these files contain the source for creating a CNAB bundle with DockerApp.
How to use it will referenced in a future blog

#### Notes to reviewers:
You can follow the steps in the demo from the community meeting of the 7th february 2020

#### Checklist
Place an '[x]' (no spaces) in all applicable fields.
- [x] [DCO](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin) signed.
- [x] Title of the PR starts with area name, e.g. `meshery:`, `mesheryctl:`, `ui:`.

Signed-off-by: Nuno do Carmo <nnd@ferring.com>

### CODE REVIEW

**Comment by leecalcote** [comment]
Link to Feb. 7th community meeting - https://www.youtube.com/watch?v=Cofv4LI4N1Q

**Comment by leecalcote** [comment]
@nidhinmahesh FYI - https://docs.docker.com/app/working-with-app/

**Comment by leecalcote** [comment]
@nunix did you run into this when running `docker-compose up`?

```
ERROR: Invalid interpolation format for "labels" option in service "meshery": "${labels.watchtower}"
```

**Comment by nunix** [comment]
Hi @leecalcote 
Ok I see what is the issue: even if the file resembles to a docker-compose file, if you do a compose up, you will get the error you saw.

In order to run it with docker-compose, you will need to run `docker app render | docker-compose -f - up`

hope this clarifies it 😄

**Comment by leecalcote** [comment]
Let's give this a whirl. Thank you, @nunix !

**Comment by leecalcote** [comment]
Thank you, @nunix 👍

**Pull request merged**
