### PR TITLE
implemented eslint checks w/signoff

### LINKED ISSUE #5953: [UI/Eslint] Enable important eslint checks
#### Current Behavior

The eslint is a great complement with JS to catch the errors in front during parse time. But some important checks being on `off` state introduces bugs in the code and failures that can be otherwise rectified in advance. Such checks are jsx keys and "no-dupe-keys". 

#### Desired Behavior
```
 "react/jsx-key" : "off",
 "no-dupe-keys" : "off",
```

WARN on "react/jsx-key"
Error on "no-dupe-keys"

#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by kamalbuilds**
Signed-off-by: Kamal <geniusamansingh@gmail.com>

This PR fixes #5953

**Description**
Enabled important eslint checks

WARN on "react/jsx-key"
Error on "no-dupe-keys"

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by legendarykamal** [comment]
this needs one more commit to be completed @MarioArriaga92 help me in this 
https://github.com/meshery/meshery/blob/master/provider-ui/components/ProviderComponent.js line 122 
you have declared the key twice, is it needed? as am not familiar with connection.

**Comment by MarioArriaga92** [comment]
Thanks for tag in slack @leecalcote 

Regarding this @legendarykamal:
> this needs one more commit to be completed @MarioArriaga92 help me in this https://github.com/meshery/meshery/blob/master/provider-ui/components/ProviderComponent.js line 122 you have declared the key twice, is it needed? as am not familiar with connection.

So I just checked but this is line 122 in master branch so I'm not following:
`credentials: "same-origin",`

**Comment by legendarykamal** [comment]
let me make more clear  @MarioArriaga92 that and line 124 look at this 
https://github.com/meshery/meshery/blob/5324a4146d122984609d1ac72fd3d9a5b6a31aca/provider-ui/components/ProviderComponent.js#L124

so you see we have two keys called credentials at 122 and 124 hence eslint error.

**Comment by legendarykamal** [comment]
sorry due to the creation of a new fork this auto matically got closed , I will create a new PR
btw @MarioArriaga92 any thoughts on this ?

**Pull request closed without merging**
