### PR TITLE
Bump next js to 11.0.1 in provider ui

### PR DESCRIPTION
**Pull request by humblenginr**
**Description**

This pr refactors some outdated code in `provider-ui` and bumps next js from 10.2.3 to 11.0.1 which was already attempted and failed in #3315

**Note for Reviewers**

Since version 11.0.0 of NextJS, they have included linting using eslint during build. It requires us to add `eslint-plugin-next` as a dev dependency to the project. Since while docker build, it uses `npm install --only=production` command, it will not install `eslint-plugin-next` and hence the build will fail. So, as a temporary fix, i have made next js ignore linting while building. We have not been running lints while build before and so this shouldn't affect anything. If we want to enforce such a behaviour, we might have to come up with a fix for this. 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — APPROVED** [review]
LGTM

**Comment by Nikhil-Ladha** [comment]
Are the changes in other files related to the dependency update?

**Comment by sudo-NithishKarthik** [comment]
> Are the changes in other files related to the dependency update?

other files ??

**Comment by Nikhil-Ladha** [comment]
> > Are the changes in other files related to the dependency update?
> 
> other files ??

Filename changes, import changes and so...

**Comment by sudo-NithishKarthik** [comment]
> > > Are the changes in other files related to the dependency update?
> > 
> > 
> > other files ??
> 
> Filename changes, import changes and so...

Yes, some of them are deprecated like, the use of `container` wrapper component and use of static folder.

**Review by Nikhil-Ladha — APPROVED** [review]
lgtm

**Pull request merged**
