### PR TITLE
[UI] Replicate Imports for Filters and Applications similar to Patterns

### PR DESCRIPTION
**Pull request by SAEb-ai**
**Description**

This PR fixes https://github.com/meshery/meshery/issues/5121

**Notes for Reviewers**

https://user-images.githubusercontent.com/69013647/157873412-b9dc21d4-d8be-4d9b-b4db-e2723b3da01f.mp4

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by SAEb-ai** [comment]
@Chadha93 @leecalcote Please take a look. Thanks!!

**Review by Chadha93 — CHANGES_REQUESTED** [review]
@SAEb-ai Please change the text and titles from the button and modal to "Import Filters" and "Import Applications" accordingly. Design is only for Patterns.

**Review by warunicorn19 — CHANGES_REQUESTED** [review]
Changes looking good, just a small nitpick though could you please add a handleClose function or something so that when a file is uploaded the modal closes because it's not good UX to have the modal opened even after a file has been uploaded. 

Good stuff @SAEb-ai 👍

**Comment by leecalcote** [comment]
Please have a look at this failure - https://github.com/meshery/meshery/runs/5515109648?check_suite_focus=true#step:6:350. Cypress tests will need updated based on the changes in this PR...?

**Comment by SAEb-ai** [comment]
Thanks for the review @warunicorn19!! Addressed your concerns, PTAL. Also @Chadha93 PTAL. Thanks!!

https://user-images.githubusercontent.com/69013647/158011169-5f68140b-3e8d-4782-aaba-fc00fd5b0108.mp4

**Review by Chadha93 — APPROVED** [review]
Thanks @SAEb-ai LGTM :1st_place_medal:

**Comment by Chadha93** [comment]
UI e2e tests are failing // @MarioArriaga92 @Abhishek-kumar09

**Comment by warunicorn19** [comment]
Yes @leecalcote the cypress test will need to be updated, since the import/upload button has changed. Hence the failing test.

**Comment by SAEb-ai** [comment]
@leecalcote Please take a look. Thanks!!

**Comment by leecalcote** [comment]
@SAEb-ai very good. Test cases passing. ✅

**Comment by MarioArriaga92** [comment]
@leecalcote What needs to be updated is to add `data-cy="file-upload-button"` attribute back to elements that represent local file upload (removed "CustomToolbar" functions had that attribute). Cypress UI end-to-end tests use that to locate button to initiate local file upload. (/ui/cypress/integration/e2e/service_mesh_configuration_management_spec.js

**Comment by MarioArriaga92** [comment]
Why was PR merged with multiple failing checks? (Se prior comment on reason for failing e2e cypress tests)
Screenshot_2022-03-14-07-32-51-247_com android chrome

**Comment by leecalcote** [comment]
My eyes lost that last one in the mix with the Netlify failures. @SAEb-ai, will you work to fix this failing build check?

https://user-images.githubusercontent.com/7570704/158184649-fe9582c4-36ba-4ef7-b2a5-4dc1878fc6a0.mov

**Comment by SAEb-ai** [comment]
First of all a big sorry. My PR brought a regression in the end to end tests in the codebase.

Here's the reason why I first ignored the end to end tests failure:-

- The failure of the [integration test](https://github.com/meshery/meshery/runs/5515109648?check_suite_focus=true#step:6:350) which @leecalcote pointed me had a clear error message pointing from where the error was coming([line 134](https://github.com/meshery/meshery/runs/5515109648?check_suite_focus=true#step:6:134)).
```AssertionError: Timed out retrying after 4000ms: Expected to find element: `[data-cy="file-upload-button"]`, but never found it.```

- The error message coming from the end to end tests failure was not clear to me because it involved npm error logs. It was 
   due to this reason that I thought it might be a setup issue. 
   

   

> npm ERR! code EBADPLATFORM
> 
>    npm ERR! notsup Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin"} (current: {"os":"linux","arch":"x64"})
>    npm ERR! notsup Valid OS:    darwin
>    npm ERR! notsup Valid Arch:  undefined
>    npm ERR! notsup Actual OS:   linux
>    npm ERR! notsup Actual Arch: x64
> 
>   npm ERR! A complete log of this run can be found in:
>   npm ERR!     /home/runner/.npm/_logs/[20](https://github.com/meshery/meshery/runs/5520948306? 
>   check_suite_focus=true#step:14:20)[22](https://github.com/meshery/meshery/runs/5520948306? 
>   check_suite_focus=true#step:14:22)-03-12T08_55_25_304Z-debug-0.log
>   Error: The process '/usr/local/bin/npm' failed with exit code 1
> 

P.S. Now, I have identified the error. I will shortly implement a fix.

**Pull request merged**
