### PR TITLE
fix: test for delete filter command

### PR DESCRIPTION
**Pull request by Yana-Gupta**
**Notes for Reviewers**

This PR fixes failing test [ in delete_test.go](https://github.com/meshery/meshery/actions/runs/5762393510/job/15622098246?pr=8370#step:5:12)

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Yana-Gupta** [comment]
// @theBeginner86

**Review by leecalcote — COMMENTED** [review]
Gosh, I can't quite tell what the change is here...

**Comment by Yana-Gupta** [comment]
> Gosh, I can't quite tell what the change is here...

Added space empty space `\n`  to match both expected and actual responses, the actual response contains space at end but the expected doesn't so, by adding an empty single line at the end of those coming responses from `delete.kuma.output.golden` and `delete.rollout.output.golden` from where those strings(expected response) are coming the test cases will get passed.

**Review by Philip-21 — COMMENTED** [review]
@Yana-Gupta with or without these spaces the testcase still passes

**Comment by Yana-Gupta** [comment]
some tests are failing [here](https://github.com/meshery/meshery/actions/runs/5801208004/job/15725078855?pr=8414)

**Comment by zakisk** [comment]
@Yana-Gupta are copying the output from the terminal to the golden file?

**Comment by zakisk** [comment]
@Yana-Gupta if so then copying output from terminal to the golden file doesn't copy the exact output generated by CLI. in order to get exact output in golden file use output operator `>` in terminal do this, (assuming you're in `meshery/mesheryctl/` directory) `./mesheryctl filter delete c0c6035a-b1b9-412d-aab2-4ed1f1d51f84 Kuma-Test > ./internal/cli/root/filter/fixtures/delete.kuma.output.golden`. it will store the exact output in the output golden file.

**Comment by Yana-Gupta** [comment]
> @Yana-Gupta if so then copying output from terminal to the golden file doesn't copy the exact output generated by CLI. in order to get exact output in golden file use output operator `>` in terminal do this, (assuming you're in `meshery/mesheryctl/` directory) `./mesheryctl filter delete c0c6035a-b1b9-412d-aab2-4ed1f1d51f84 Kuma-Test > ./internal/cli/root/filter/fixtures/delete.kuma.output.golden`. it will store the exact output in the output golden file.

Okay thanks for informing I understood I just added space from the terminal to make both string equal.. that was wrong. I thought that those outputs were manually provided so I just edited it there. Thanks for your answer.
Also could you answer if both of the strings are being generated.. then why a difference of space is coming in both strings.
Then should I trim the space from the actualResponse string to make the strings equal?

**Comment by Yana-Gupta** [comment]
> @Yana-Gupta if so then copying output from terminal to the golden file doesn't copy the exact output generated by CLI. in order to get exact output in golden file use output operator `>` in terminal do this, (assuming you're in `meshery/mesheryctl/` directory) `./mesheryctl filter delete c0c6035a-b1b9-412d-aab2-4ed1f1d51f84 Kuma-Test > ./internal/cli/root/filter/fixtures/delete.kuma.output.golden`. it will store the exact output in the output golden file.

@zakisk Thanks for informing

**Review by leecalcote — CHANGES_REQUESTED** [review]
I still don't see a difference... what was changed here?

**Comment by leecalcote** [comment]
@Yana-Gupta what did you change in this PR from what is in `master`?

**Comment by Yana-Gupta** [comment]
> @Yana-Gupta what did you change in this PR from what is in `master`?
only an empty line difference was changed, before it was not there in `master` I just added it.

**Comment by vishalvivekm** [comment]
@Yana-Gupta Let's discuss this on Meshery Dev call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#) if you would. :)

**Comment by Yana-Gupta** [comment]
> @Yana-Gupta Let's discuss this on Meshery Dev call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#) if you would. :)

Thanks @vishalvivekm it was already discussed earlier on Meshery build and release call.

**Comment by leecalcote** [comment]
> > @Yana-Gupta what did you change in this PR from what is in `master`?
> 
> only an empty line difference was changed, before it was not there in `master` I just added it.

Sounds real good. Or do you mean that you removed an extraneous line return?

**Comment by Philip-21** [comment]
@Yana-Gupta Thanks i see what you meant by this indent you made. The test passed with the additional changes i made . 
delete-test

**Comment by Yana-Gupta** [comment]
> > > @Yana-Gupta what did you change in this PR from what is in `master`?
> > 
> > 
> > only an empty line difference was changed, before it was not there in `master` I just added it.
> 
> Sounds real good. Or do you mean that you removed an extraneous line return?

I adjusted the lines to pass the test case.. but I have added space to pass the testcase in the testdata files.. I don't know why the changes are not same as of my local system

**Comment by Philip-21** [comment]
> > > > @Yana-Gupta what did you change in this PR from what is in `master`?
> > > 
> > > 
> > > only an empty line difference was changed, before it was not there in `master` I just added it.
> > 
> > Sounds real good. Or do you mean that you removed an extraneous line return?
> 
> I adjusted the lines to pass the test case.. but I have added space to pass the testcase in the testdata files.. I don't know why the changes are not same as of my local system

I was able to sort that out in this [pr](https://github.com/meshery/meshery/pull/8501), but other changes are still ongoing in it

**Pull request merged**
