### PR TITLE
Fixing e2e test for user_spec

### LINKED ISSUE #7622: [Cypress] Failing E2E tests in User Preference.
#### Current Behavior
Currently, E2E tests for User Preferences are failing - https://github.com/meshery/meshery/actions/runs/4822176767/jobs/8589252885?pr=7621#step:16:241 
image

#### Expected Behavior
All the tests should pass, logs can be checked from any failing PR. 

#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by Freedisch**
**Notes for Reviewers**

This PR fixes #7622 and #7623

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Abhishek-kumar09** [comment]
@Freedisch From the call today, lets apply the solution and see if it fixes the problem. Its a high priority item, so we require it to fix promptly. Would you start by adding the asterisk.

**Comment by Freedisch** [comment]
> @Freedisch From the call today, lets apply the solution and see if it fixes the problem. Its a high priority item, so we require it to fix promptly. Would you start by adding the asterisk.

sure, I'm on it

**Comment by Freedisch** [comment]
@Abhishek-kumar09 , it doesn't seem to change anything the tests keep failing. I wonder if it's not due to the testing environment in the workflow bcs currently, the tests seem to work locally.


image

**Comment by Abhishek-kumar09** [comment]
Okay, I just saw the recordings. The None provider isn't allowed to send user statistics. So, either inside the cypress the user has to be logged in (most likely a robot account) or this test need to be skipped on none-provider.

**Comment by Abhishek-kumar09** [comment]
[cypress-ss (11).zip](https://github.com/meshery/meshery/files/11456704/cypress-ss.11.zip)
The recording and screenshots which are available as artifacts on github, but sending it in this conversation to be tracked easily.

**Comment by Freedisch** [comment]
I was running those tests with a none provider

**Comment by l5io** [comment]
🚀 Preview for commit 4b6170a66972b876db612e5a807cedcbdbb6440c at: https://64640c4eebed972c8013a942--meshery-docs-preview.netlify.app

**Comment by MarioArriaga92** [comment]
@Freedisch @Abhishek-kumar09 hoping these last changes fix the intermittent issues but will monitor latest ci run to confirm so, will set this to "ready for review" once all tests pass but feel free to take a look at the changes before that happens

**Comment by Chadha93** [comment]
@Freedisch @MarioArriaga92  Let's discuss this on the Meshery Dev call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#) if you would. :)

**Comment by MarioArriaga92** [comment]
@Freedisch just FYI, I presented status of cypress integration & e2e tests and meshery dev meeting audience agreed we should merge this PR and open separate issue/PR for any other failing tests such as e2e user preferences anonymous usage/performance statistics tests

**Comment by MarioArriaga92** [comment]
@Azanul @Abhishek-kumar09 will set to "Ready for review" as soon as CI test runs finish

**Comment by MarioArriaga92** [comment]
@Chadha93 @leecalcote @Freedisch @Abhishek-kumar09 will open a separate issue for [these](https://github.com/meshery/meshery/actions/runs/5070113396/jobs/9104839533?pr=7658) user preferences cypress e2e test failures:
CleanShot 2023-05-24 at 09 27 05

**Comment by Azanul** [comment]
@MarioArriaga92 @Freedisch Awesome work!

**Review by MarioArriaga92 — APPROVED** [review]

**Pull request merged**
