### PR TITLE
Pattern Unit test

### LINKED ISSUE #8087: [Unit Tests] Writing more Unit tests for mesheryctls  Packages
#### Current Behavior
Not much unit test for the [packages](https://github.com/meshery/meshery/blob/master/mesheryctl/internal/cli/root) in mesheryctl 
#### Desired Behavior
Adding more Unit tests to test the units and individual components of the codes in [mesheryctl's  packages](https://github.com/meshery/meshery/blob/master/mesheryctl/internal/cli/root) to improve ci coverage

#### Acceptance Tests

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
- Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)
- 🧪 [Meshery Test Plan Spreadsheet](https://docs.google.com/spreadsheets/d/13Ir4gfaKoAX9r8qYjAFFl_U9ntke4X5ndREY1T7bnVs/edit#gid=0)

### PR DESCRIPTION
**Pull request by Philip-21**
**Notes for Reviewers**

This PR fixes #8087

Unit tests for [Pattern.go](https://github.com/meshery/meshery/blob/master/mesheryctl/internal/cli/root/pattern/pattern.go) in ` pattern` package 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — DISMISSED** [review]
Let's give this a shot...

**Comment by leecalcote** [comment]
```
    --- FAIL: TestPatterncmd/pattern_list (0.00s)
        pattern_test.go:153: could not read file pattern.list.golden: open /home/runner/work/meshery/meshery/mesheryctl/internal/cli/root/pattern/fixtures/pattern.list.golden: no such file or directory
```

**Comment by Philip-21** [comment]
> ```
>     --- FAIL: TestPatterncmd/pattern_list (0.00s)
>         pattern_test.go:153: could not read file pattern.list.golden: open /home/runner/work/meshery/meshery/mesheryctl/internal/cli/root/pattern/fixtures/pattern.list.golden: no such file or directory
> ```

I am working on generating outputs

**Comment by Philip-21** [comment]
@leecalcote  the golden files are created  and generated successfully and i shortened the User ID to 8 characters in the ` list.go`  for  the patterns package

**Comment by vishalvivekm** [comment]
@Philip-21 Let's discuss this on Meshery Dev call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#) if you would. :)

**Comment by Philip-21** [comment]
@leecalcote , @suhail34 , @zakisk this pr has tackled the error [here](https://github.com/meshery/meshery/actions/runs/5657521386/job/15326944619?pr=8272#step:5:31)

I added adjustments to certain fields and i included more fields that were incomplete, so the ouputs are generated successfully
I had to do some renaming to differentiate testcase names amongst the pattern and the filter package 
I also created unit test for the `pattern.go`

**Comment by Philip-21** [comment]
The error for [this](https://github.com/meshery/meshery/actions/runs/5802089714/job/15727771173?pr=8324#step:5:159) will be implemented in another pr.

**Comment by leecalcote** [comment]
Thank you for confirming, @Philip-21 👍

**Comment by Philip-21** [comment]
🙂

**Comment by Philip-21** [comment]
> Thank you for confirming, @Philip-21 👍 

🙂

**Pull request merged**
