### PR TITLE
changed class based to functional based component

### PR DESCRIPTION
**Pull request by kundan766**
**Notes for Reviewers**

This PR fixes #
This PR changed class based component to functional based components 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by saurabh100ni** [comment]
Let's discuss this on the Meshery dev call tomorrow,
Please add this as your agenda item in Docs: https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit

**Comment by sudhanshutech** [comment]
@kundan766 merge conflicts

**Comment by sudhanshutech** [comment]
It would be good to mention which component you migrate from class to functional

**Review by nebula-aac — CHANGES_REQUESTED** [review]
@kundan766 

Thanks for submitting your PR on converting Navigator to Function Component.

First thing I want to point out is to remove the commented lines. There's no need to have that, as we have the ability to revert if your PR does not work as expected.

**Comment by nebula-aac** [comment]
We also use DCO when we sign out commits, can you also review this instructions on this page to sign your last commit?

https://github.com/meshery/meshery/pull/9004/checks?check_run_id=17338250090

**Comment by nebula-aac** [comment]
Can you also update your fork as well?

**Comment by nebula-aac** [comment]
And lastly, can you provide a quick video of making sure that the navigator works as expected after you have done the steps above? This will make reviewing a lot quicker, and easier for everyone, new and seasoned when we provide feedback.

**Comment by abhijeetgauravm** [comment]
@kundan766 Also edit the description with This PR fixes #issue_no .

**Review by Yashsharma1911 — COMMENTED** [review]
@kundan766  merge conflict

**Comment by Yashsharma1911** [comment]
@kundan766 checking in last time, Are you still working on it? if yes please resolve merge conflict and let's get this merge

**Comment by kundan766** [comment]
yes i will

**Comment by leecalcote** [comment]
@kundan766 has abandoned this PR.

**Pull request closed without merging**
