### PR TITLE
Adding playwright tests for performance page

### LINKED ISSUE #11557: Playwright Tests for UI/Meshery-server Service Mesh Performance Management
### Current Behavior
As we are migrating our e2e tests to Playwright. In this migration, we will include comprehensive tests for the Service Mesh Performance Management component. This will ensure that functionalities such as running performance tests, viewing and editing performance profiles, deleting profiles, viewing and comparing test results, and scheduling tests are thoroughly tested and tracked in  [ Meshery Test Plan](https://docs.google.com/spreadsheets/d/13Ir4gfaKoAX9r8qYjAFFl_U9ntke4X5ndREY1T7bnVs/edit?pli=1&gid=0#gid=0).

### Desired Behavior
Migrate the existing tests to Playwright to achieve a more robust and efficient testing framework. The new Playwright tests should cover the following scenarios:

- [x] `Run a performance test`

- [x]  `Run a performance test with a performance profile`

- [x]  `View/Edit the configuration of a performance profile`

- [ ]  `Delete a performance profile`

- [x]  `View results from a performance profile`

- [x] ` View detailed result of a performance profile (Graph Visualiser)`

- [ ] `Download, compare and schedule a performance test`

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by yash37158**
**Notes for Reviewers**
This code is a set of automated tests written in Playwright for managing performance profiles. The tests focus on various actions like running performance tests, viewing detailed results, managing profiles, and editing configurations.

This PR fixes #11557 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by jerensl — CHANGES_REQUESTED** [review]
https://github.com/meshery/meshery/pull/11811/files#diff-fca7e9dcc189b32237c83af054b157e76b2c5d37fc168fef5145ae82441411e3R136
Let's use a selector that is resistant to change like data-testid and so when there are changes in a name like a button or text

**Comment by yash37158** [comment]
Sure @jerensl

**Comment by yash37158** [comment]
@senthil-athiban , GitHub seems to be acting up. Could you please send me a screenshot of the suggestion

**Comment by senthil-athiban** [comment]
@yash37158, 
create a re-usable fixture for Performance page, [Ref](https://github.com/meshery/meshery/blob/master/ui/tests/e2e/fixtures/pages.js#L69)
We should not prefer [css locators](https://playwright.dev/docs/other-locators#css-locator), as it will break the test, rather prefer [this](https://playwright.dev/docs/locators#quick-guide)

**Comment by yash37158** [comment]
@jerensl @senthil-athiban I've implemented the changes you suggested. However, some elements still rely on CSS or text selectors because there's no specific data-testid available. Please review and let me know if the updates are satisfactory.

**Comment by senthil-athiban** [comment]
If you find that there are no selectors, then inject the `datates-id` attribute

**Comment by yash37158** [comment]
Sure @senthil-athiban

**Comment by yash37158** [comment]
@senthil-athiban

**Review by jerensl — APPROVED** [review]

**Comment by yash37158** [comment]
@jerensl are we good to merge this ?

**Comment by jerensl** [comment]
@yash37158 Just need to fix the linter error and we are good

**Comment by yash37158** [comment]
@jerensl I fix the es-lint issue if you could verify that

**Comment by jerensl** [comment]
@yash37158 Thanks, great work 👏.

Seems like DCO is failing can you rebase and re-sign the last 2 commits?
https://github.com/meshery/meshery/pull/11811/checks?check_run_id=29761084642

**Comment by l5io** [comment]
🚀 Preview for commit eec87cffacb1f7e7556c56784120a56e413dc0c7 at: https://66dad8acaeaf6451680bb09d--meshery-docs-preview.netlify.app

**Comment by yash37158** [comment]
@jerensl The old commits were already signed off as I edited them manually in Git, which is why the DCO checks are failing

**Review by jerensl — APPROVED** [review]

**Comment by jerensl** [comment]
LGTM

**Pull request merged**
