### PR TITLE
added release drafter for the respository

### PR DESCRIPTION
**Pull request by jomefavourite**
Signed-off-by: jomefavourite <jfjomefavourite@gmail.com>

**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
@jomefavourite perhaps, you intended this change for a different repo. Is that right?

**Review by Ruth-ikegah — CHANGES_REQUESTED** [review]
Hi @jomefavourite nice work but you are submitting this PR to the wrong repository. If you check, this repository already has a release drafter. 

**Quick tip**: Before creating a PR, ensure there is an issue on that repository requiring the change

So, unfortunately, this PR is invalid for this repository as there is already a release drafter configured here. 

In case you are not clear on this, feel free to ask a question!

**Comment by jomefavourite** [comment]
Oh, I'm sorry 
I should have asked better

**Comment by Ruth-ikegah** [comment]
> Oh, I'm sorry
> I should have asked better

that's fine @jomefavourite, I'd check for another issue or one needing this change and send you a message on slack.

**Comment by kushthedude** [comment]
>Oh, I'm sorry
I should have asked better

Hey @jomefavourite no issues, we appreciate you contributing to the community. You can file the similar PR for this https://github.com/layer5io/meshery-cpx/issues/40 where we need to add the release-drafter!

Thanks!

**Pull request closed without merging**
