### PR TITLE
[UI] Snackbar Closing and Settings Btn Fixed

### LINKED ISSUE #3910: [UI] Unable to click "Settings" button in toaster notification
#### Current Behavior

https://user-images.githubusercontent.com/7570704/129776659-254962c3-9eb3-47ef-9153-62a034a17b20.mov

#### Environment

- Browser: Chrome
- Host OS: Mac
- Meshery Server Version: stable-v0.5.47
- Platform: Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by NikhilSharma03**
Signed-off-by: Nikhil Sharma <nikhilsharmamusic2000@gmail.com>

**Description**

<h4>This PR fixes #3910 and #3918 </h4>

## Fixed `X` to close the snackbar

https://user-images.githubusercontent.com/58226527/129906600-4a5d0e2d-0ffd-4d9f-a2a5-5b6b5f2c32d5.mp4

## Fixed `Settings` button

https://user-images.githubusercontent.com/58226527/129906867-cb2fcb23-ff98-4ee1-8a75-230771839d7f.mp4

**Notes for Reviewers**
- Let me know if there are any other changes we can make.

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by warunicorn19 — APPROVED** [review]
Tested it out on local, works great🎉, thanks @NikhilSharma03

**Comment by warunicorn19** [comment]
@sudo-NithishKarthik UI integration failing again, could you please re-run the test, i think that requires write access

**Comment by Chadha93** [comment]
> Tested it out on local, works great, thanks @NikhilSharma03
@warunicorn19 Thanks for testing, did you also tested out for the performance/other UI's, everywhere also(just confirming) :P

**Comment by warunicorn19** [comment]
Yup @Chadha93 , tested it out all over. It works

**Review by Chadha93 — APPROVED** [review]
great work @NikhilSharma03

**Comment by sudo-NithishKarthik** [comment]
Oh, thanks for pointing out @warunicorn19

**Review by leecalcote — APPROVED** [review]
As a directional comment, let's move to `rem` or `vh`/`wh` as our unit of measure and away from `px`.

**Pull request merged**
