### PR TITLE
[server]Fix Index Out of Range Error Handling in Meshery Component Handler

### LINKED ISSUE #8654: [Server] Database deadlock
### Screenshots/Logs
```
database is locked
20:34:32 http: panic serving 172.21.0.1:40486: runtime error: index out of range [0] with length 0
goroutine 452927 [running]:
net/http.(*conn).serve.func1()
	/usr/local/go/src/net/http/server.go:1850 +0xbf
panic({0x4847440, 0xc470c88780})
	/usr/local/go/src/runtime/panic.go:890 +0x262
github.com/layer5io/meshery/server/handlers.(*Handler).GetMeshmodelModels(0xc0024d1e80, {0x5036e10, 0xc20482b420}, 0xc15d02ed00)
	/github.com/meshery/meshery/server/handlers/component_handler.go:219 +0xd85
net/http.HandlerFunc.ServeHTTP(0xc187e024e0?, {0x5036e10?, 0xc20482b420?}, 0xc187e024e0?)
	/usr/local/go/src/net/http/server.go:2109 +0x2f
github.com/layer5io/meshery/server/handlers.(*Handler).AuthMiddleware.func1({0x5036e10?, 0xc20482b420?}, 0xc15d02ed00?)
	/github.com/meshery/meshery/server/handlers/middlewares.go:102 +0x282
net/http.HandlerFunc.ServeHTTP(0x5039f10?, {0x5036e10?, 0xc20482b420?}, 0x4ff2070?)
	/usr/local/go/src/net/http/server.go:2109 +0x2f
github.com/layer5io/meshery/server/handlers.(*Handler).ProviderMiddleware.func1({0x5036e10, 0xc20482b420}, 0xc15d02ec00)
	/github.com/meshery/meshery/server/handlers/middlewares.go:54 +0x44d
net/http.HandlerFunc.ServeHTTP(0xc15d02eb00?, {0x5036e10?, 0xc20482b420?}, 0x800?)
	/usr/local/go/src/net/http/server.go:2109 +0x2f
github.com/gorilla/mux.(*Router).ServeHTTP(0xc001c26900, {0x5036e10, 0xc20482b420}, 0xc15d02ea00)
	/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0x1cf
net/http.serverHandler.ServeHTTP({0xc187e022d0?}, {0x5036e10, 0xc20482b420}, 0xc15d02ea00)
	/usr/local/go/src/net/http/server.go:2947 +0x30c
net/http.(*conn).serve(0xc0f5596000, {0x5039f10, 0xc00059e3c0})
	/usr/local/go/src/net/http/server.go:1991 +0x607
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3102 +0x4db
```

### Environment
Playground
- **Host OS:** Linux
- **Platform:** Docker
- **Meshery Server Version:** stable-v0.6.134

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by Shiva953**
**Notes for Reviewers**

This PR fixes #8654 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Ghat0tkach** [comment]
hey @Shiva953 

 Let's discuss this on Meshery Dev call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#) if you would. :)

**Review by leecalcote — APPROVED** [review]
Thanks, @Shiva953 👍

**Comment by leecalcote** [comment]
@MUzairS15 look good?

**Review by MUzairS15 — APPROVED** [review]
Thanks

**Pull request merged**
