### PR TITLE
Fix the CI format issues.

### LINKED ISSUE #971: [CI]  CI configuration file indentation issue.
**Description**

Indentation issue in the vet_check chapter of CI configuration.

**Expected Behavior**

All configuration chapters remain uniformly indented.

**Screenshots**

image

**Environment:**
 - OS: [e.g. Ubuntu]
 - Browser: [e.g. Chrome, Safari]
 - Version: [e.g. 22]
 - Device: [e.g. laptop, iPhone 8]

---
[Optional] **To Reproduce**

[Optional] **Additional Context**

### PR DESCRIPTION
**Pull request by hydra-bu**
Signed-off-by: youngman <shengquan.bu@iquantex.com>

#### Description

This PR fixes #971 #902     

#### Checklist

- [x] [DCO](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin) signed.
- [] Title of the PR starts with area name, e.g. `meshery:`, `mesheryctl:`, `ui:`.

### CODE REVIEW

**Comment by Aisuko** [comment]
@leecalcote Please take a look

**Comment by leecalcote** [comment]
So, cool to see a PR from @spring-bu. 😄

**Comment by leecalcote** [comment]
> @spring-bu Great work! I had doubt rather calling cache actions multiple times, can we remove the duplications ?

It seems that each job repeats the setup of Go and the setup of Cache. I assume that these tasks do not persist from job to job, is that right?

**Comment by leecalcote** [comment]
We have this issue of repetition in each of the jobs as they are defined today, and so I don't think we're compounding the issue.

It would be good to investigate any streamlining that can be done here, @Saim-Safdar @rav121

**Comment by kushthedude** [comment]
> Thanks for your contribution to the Layer5 community! 
> 
> Congrats!

Nice

**Comment by spring-bu** [comment]
> @spring-bu Great work! I had doubt rather calling cache actions multiple times, can we remove the duplications ?

Hi, @kushthedude 
The CI configuration contains multiple jobs, and each job is built separately. so, I think that adding a cache to each job will not actually affect it.

**Pull request merged**
