### PR TITLE
Added action to tweet PR/issue

### PR DESCRIPTION
**Pull request by siddhikhapare**
**Notes for Reviewers**

This PR fixes #

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — CHANGES_REQUESTED** [review]
Missing link to PR

**Comment by leecalcote** [comment]
@Revolyssup please put this on today's Meshery CI meeting agenda.

**Comment by siddhikhapare** [comment]
@leecalcote  which link should I mention?  I used resources that one Do I include here?

**Comment by siddhikhapare** [comment]
@leecalcote Do you want me to include api keys of meshery twitter account in .env file?

**Comment by leecalcote** [comment]
> @leecalcote Do you want me to include api keys of meshery twitter account in .env file?

In a GitHub secret, yes.

**Comment by leecalcote** [comment]
I see the secrets that you've identified in the workflow. I'll ensure that these secrets are available to the workflow at runtime.

**Comment by siddhikhapare** [comment]
@leecalcote  How do I get access meshery's twitter api keys and tokens?
 If I setup my own Twitter developer account then I will get my own api keys  so I haven't added in workflow.
what should I do? Can you guide me?

**Comment by leecalcote** [comment]
> @leecalcote How do I get access meshery's twitter api keys and tokens?
> If I setup my own Twitter developer account then I will get my own api keys so I haven't added in workflow.
> what should I do? Can you guide me?

Guidance offered in today's Meshery CI meeting.

**Comment by siddhikhapare** [comment]
@leecalcote I got error while creating developer twitter account which will be used to test this code. I have reported support team of twitter.

**Comment by siddhikhapare** [comment]
Twitter developer portal provides me this mentioned error. I tried to add my phone no.  in my twitter account but it's showing invalid number but I put it correctly. `https://drive.google.com/file/d/17D4hOHz3BxQgErsCNP9PsKhs48kAmyk9/view?usp=share_link`

**Comment by siddhikhapare** [comment]
@leecalcote I apologize that I could not work on this issue because of  technical glitch while  creating twitter developer account is not getting resolved so I can't check how twitter API work with my setup.

**Pull request closed without merging**
