### PR TITLE
Converted MesheryNotification.js to functional

### LINKED ISSUE #8677: [UI] Convert `MesheryNotification` class-based component to functional component
### Current Behavior
`MesheryNotification` is a class-based component.

### Desired Behavior
`MesheryNotification` is a functional component.

### Implementation
Here is a quick blog that will help you get started with : [Link](https://www.digitalocean.com/community/tutorials/five-ways-to-convert-react-class-components-to-functional-components-with-react-hooks)

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by ishashankmittal**
**Notes for Reviewers**

This PR fixes #8677 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by EraKin575** [comment]
please make sure to always sign-off your commits

**Comment by ishashankmittal** [comment]
> please make sure to always sign-off your commits

I tried to sign the commit again, but i am unable to do it now. Let me know if it is required this time. 
I'll definitely sign the commits next time.

**Comment by aabidsofi19** [comment]
this component becomes redundant with the new notification center updates .

**Comment by aabidsofi19** [comment]
more efforts here might go in vain .

**Comment by ishashankmittal** [comment]
> more efforts here might go in vain .

I was assigned this task for the issue #8677 by @Rajdip019 . Will this be merged or not?

**Comment by Rajdip019** [comment]
Can you check all the other components as well in this issue #8668 @aabidsofi19 . There could be other components as well which may become obsolete after new updates people are working on.

**Comment by leecalcote** [comment]
Thanks, @ishashankmittal 👏 


Heads-up: there's a merge conflict to look into.

**Comment by saurabh100ni** [comment]
Hey @ishashankmittal 
Let's discuss this as your agenda item for today's Meshery development meeting,
Please add it if it's not already there : https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit

**Pull request closed without merging**
