### PR TITLE
Update Secrets list in Build and Release

### LINKED ISSUE #11331: [Docs] Secrets list in Build and Release
### Current State
This page is in need of an enhanced list of org-level secrets - https://docs.meshery.io/project/contributing/build-and-release#secrets

### Desired State
The following list contains valid secret names and secret name that, if present, need to be -removed-:

-AKS_PLAYGROUND_KUBECONFIG-
-AZ_PLAYGROUND_HOST-
-AZ_PLAYGROUND_KEY-
-AZ_PLAYGROUND_USERNAME-
-CYPRESS_RECORD_KEY-
DOCKER_PASSWORD
DOCKER_USERNAME
GH_ACCESS_TOKEN
-GH_ACCESS_TOKEN_POSTGRES_TEST-
GO_VERSION
INTEGRATION_SPREADSHEET_CRED
MAIL_PASSWORD
MAIL_USERNAME
MESHERY_PROVIDER_TOKEN
MESHERY_TOKEN
METAL_AUTH_TOKEN
METAL_SERVER1
METAL_SERVER2
METAL_SERVER3
NETLIFY_AUTH_TOKEN
NETLIFY_SITE_ID
NPM_TOKEN
PLAYGROUND_CONFIG
PROVIDER_TOKEN
RELEASEDRAFTER_PAT
RELEASE_NOTES_PAT
SLACK_BOT_TOKEN
-TWITTER_CONSUMER_API_KEY_MESHERY-
-TWITTER_CONSUMER_API_SECRET_MESHERY-

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by Jacobojijo**
**Notes for Reviewers**

This PR fixes #11331 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit e6cad4f45e88fc354341e00fe6b295a6db7767c6 at: https://668e540eb3ffaf174f68dcf6--meshery-docs-preview.netlify.app

**Comment by leecalcote** [comment]
@surajgjadhav review?

**Review by leecalcote — APPROVED** [review]
Thanks, @Jacobojijo!

**Comment by leecalcote** [comment]
> @surajgjadhav review?

Nope.

**Pull request merged**
