### PR TITLE
Working with Tags page added

### PR DESCRIPTION
**Pull request by iArchitSharma**
**Notes for Reviewers**

This PR fixes #

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 70db107680e40626c392434a65bfb1dd152918b6 at: https://66787a65ff107bcb9f3e5151--meshery-docs-preview.netlify.app

**Comment by vishalvivekm** [comment]
Thank you for your contribution.
Let's discuss this on Websites's call. Add this as an agenda item into the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit), if you would :)

**Review by rishabhsharma1997 — APPROVED** [review]

**Comment by l5io** [comment]
🚀 Preview for commit 04e5324fc0f978e270bb81833f664e4babc4debf at: https://667edca2f102c13dacc4e6c5--meshery-docs-preview.netlify.app

**Review by leecalcote — COMMENTED** [review]
@iArchitSharma is this being moved to l5 docs?

**Comment by iArchitSharma** [comment]
this

> @iArchitSharma is this being moved to l5 docs?

this one is already in l5 docs, So we aren't adding it here?

**Comment by Deepak0320Singhal** [comment]
@iArchitSharma Let's discuss this in Meshery Dev meeting on Wednesday. Adding this as an agenda item....
Meeting minutes: https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit?pli=1#
Meeting link: https://meet.layer5.io/meshery

**Pull request merged**
