### PR TITLE
Fixing typo in the troubleshooting/installation page

### LINKED ISSUE #12987: [Docs]Typo in the troubleshooting/installation page
A typo is found in the page [troubleshooting/installation](https://docs.meshery.io/guides/troubleshooting/installation), <br /><br />the misspelled word is:<br />  *Destkop*<br /><br /><br /> thanks !

### PR DESCRIPTION
**Pull request by lhajouji**
**Notes for Reviewers**

- This PR fixes #12987

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 676c8abba7ca48f3974bc2fb4cfc3047a03479d4 at: https://676a9d95c6eae6b0f8ec72ff--meshery-docs-preview.netlify.app

**Review by miacycle — APPROVED** [review]
LGTM. Thanks, @lhajouji!

**Comment by lhajouji** [comment]
@miacycle happy to contribute even to this great project !

**Comment by lhajouji** [comment]
This PR has been combined into #13000

**Pull request closed without merging**
