### PR TITLE
fixed jquery error 

### LINKED ISSUE #7133: [Docs] jquery throws an error unrecognised expression error whenever search input is used
#### Current State

Screenshot from 2023-02-21 10-02-47

#### Desired State
No error should be displayed on console

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by VIKAS0264**
**Notes for Reviewers**

This PR fixes #7133

jquery throws unrecognised expression error because of incorrect jquery selector it is fixed in this PR.

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 67da861da156ee219ee9b5ada3485bf5d1c446d6 at: https://63f44ede9e215904edaeca88--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 44a87313a7797fdeed6eaa19c1cce1fb69c1a52a at: https://63f45d7037dfa1112757f77f--meshery-docs-preview.netlify.app

**Comment by Chadha93** [comment]
@VIKAS0264  Let's discuss this on the Meshery Dev call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#) if you would. :)

**Review by leecalcote — APPROVED** [review]
This looks good to me. Thank you, @VIKAS0264 👍

**Pull request merged**
