### PR TITLE
[CI] Security: Upgrade to docker image to Alpine 3.15

### PR DESCRIPTION
**Pull request by leecalcote**

### CODE REVIEW

**Comment by leecalcote** [comment]
The golang unit tests have failed on two separate runs of the workflows for this PR.

**Review by alphaX86 — COMMENTED** [review]
The changes look good, but the coverage tests report as "no test files found" for some pattern files :(
image

**Comment by leecalcote** [comment]
@Revolyssup @navendu-pottekkat @piyushsingariya do you know what is causing this?

**Comment by Revolyssup** [comment]
> @Revolyssup @navendu-pottekkat @piyushsingariya do you know what is causing this?

Has been fixed on the master branch

**Comment by leecalcote** [comment]
Thank you, @Revolyssup. Branch sync'ed with master.

**Comment by leecalcote** [comment]
All green lights 🟢

**Pull request merged**
