### PR TITLE
Fix invalid markdown lifecycle management page

### LINKED ISSUE #2025: [Docs] Invalid markdown in heading on lifecycle management page
**Current State:**
This page (https://meshery.layer5.io/docs/functionality/lifecycle-management) has the following issue:
Screen Shot 2020-12-03 at 12 48 45 AM

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

### PR DESCRIPTION
**Pull request by Shulammite-Aso**
**Description**

This PR fixes #2025 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
@kushthedude is the PR labeler getting in the way of the Welcome bot again?

**Comment by leecalcote** [comment]
@Shulammite-Aso thank you. There's a small item to attend to on your commit. All Layer5 projects require that each commit carries a sign-off. See https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin for details.

To add your sign-off on the commit in this PR, you will simply execute the commands here - https://github.com/layer5io/meshery/pull/2027/checks?check_run_id=1491089961

**Comment by Shulammite-Aso** [comment]
> @Shulammite-Aso thank you. There's a small item to attend to on your commit. All Layer5 projects require that each commit carries a sign-off. See https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin for details.
> 
> To add your sign-off on the commit in this PR, you will simply execute the commands here - https://github.com/layer5io/meshery/pull/2027/checks?check_run_id=1491089961

Okey @leecalcote will do this now.

**Comment by leecalcote** [comment]
@Shulammite-Aso, I welcome you to join the [Layer5 community](https://layer5.io/community) here - http://slack.layer5.io - if you aren't in there already. Lot's of helpful folks like MeshMates @PluckyPrecious and @Ruth-ikegah.

**Comment by Ruth-ikegah** [comment]
Yeah @Shulammite-Aso feel free to ask questions

**Comment by PluckyPrecious** [comment]
Welldone on your first contribution to the Layer5 project @Shulammite-Aso 🥳

**Comment by Shulammite-Aso** [comment]
Hi all. sorry it looked like i went silent for a while.  I had earlier made my changes on the browser without yet having a local clone of the project. But i saw i needed to make my changes locally for me to be able to include the dco, figured out it might take me some more minutes to setup the project locally then make my amendments. So thought it would probably be better for me if i came back to it after making food, eating and taking my medications. (i was getting down at the time :smiley: )

**Comment by Shulammite-Aso** [comment]
I'm done and back now.  And happy that @Ruth-ikegah has already reached out to me about moving on from here

**Comment by Shulammite-Aso** [comment]
@leecalcote please review. dco is now signed.

**Review by leecalcote — APPROVED** [review]
Looking good. Thanks, @Shulammite-Aso 👍

**Pull request merged**
