### PR TITLE
[UI] Settings: Added white background in Metrics

### LINKED ISSUE #7303: [UI] Settings: Metrics background should be white
#### Screenshots/Logs
Screenshot 2023-03-07 at 4 40 13 PM

Screenshot 2023-03-07 at 4 39 35 PM

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by Yashsharma1911**
**Notes for Reviewers**

This PR fixes #7303 

There background was transparent which is fixed in this PR

Screenshot 2023-07-05 at 6 24 53 PM
Screenshot 2023-07-05 at 6 25 23 PM

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by Yashsharma1911** [comment]
@samyakshah3008 will you review this?

**Comment by samyakshah3008** [comment]
For sure @Yashsharma1911

**Review by samyakshah3008 — COMMENTED** [review]
Nice small fix @Yashsharma1911 ✅ 
Can you please check on why that one check is failing? 
Rest looks good to merge ✅

**Review by leecalcote — APPROVED** [review]
In this case, the failing test case is ignorable.

Thank you, gents.

**Pull request merged**
