### PR TITLE
Update mesheryctl.md

### PR DESCRIPTION
**Pull request by dA505819**
#### Description

This PR fixes #  Typo in mesheryctl.md  

#### Checklist

- [x] [DCO](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin) signed.
- [x] Title of the PR starts with area name, e.g. `meshery:`, `mesheryctl:`, `ui:`.

### CODE REVIEW

**Comment by dA505819** [comment]
I followed all procedures of signing the commit but still it didn't signed. ); I am sorry
I will again sign it.

**Comment by leecalcote** [comment]
You got it, @dA505819!

**Comment by dA505819** [comment]
@leecalcote Thankyou! It took lot of time.

**Comment by leecalcote** [comment]
@dA505819 👍 The next ones will get easier as you'll have this part of the process behind you.

**Comment by dA505819** [comment]
@leecalcote Yaa.

**Pull request merged**
