### PR TITLE
Solved the issue of responsiveness of footer in home/extension under docs section

### PR DESCRIPTION
**Pull request by AdityaRaimec22**
**Notes for Reviewers**

This PR fixes #

The non-Responsive behavior of header in home/extension under docs section of meshery

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit f856626400f9dd4763554b837acf4364570cf079 at: https://64be1a095ffc1028866dc53a--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 1d86ae5f2796895c9c0d3575915e8de372c7ca07 at: https://64be1adb4bb2042993a9418f--meshery-docs-preview.netlify.app

**Comment by vishalvivekm** [comment]
@AdityaRaimec22 Let's discuss this on Websites Meeting call on Monday. Please add this as an agenda item in the [meeting mintes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.69qskjv558bk) if you would. :)

**Review by vishalvivekm — CHANGES_REQUESTED** [review]
Gemfile.lock changes aren't to be pushed.
Please revert these @AdityaRaimec22 if you would.

**Comment by l5io** [comment]
🚀 Preview for commit 8ce264ddf4320416426fc78f625c176e94f0c042 at: https://64be3f24846f6e412f395818--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit ac55dc36fe01b61d55347a3cb0d97cd1ff603a02 at: https://64c0cf9eff6c2f372aa8814b--meshery-docs-preview.netlify.app

**Comment by Chadha93** [comment]
@AdityaRaimec22  Let's discuss this on the Meshery Dev call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#) if you would. :)

**Comment by AdityaRaimec22** [comment]
@Chadha93 @vishalvivekm Currently I am unable to add this agenda in meeting minuted becomes I don't have required edit permissions.

**Comment by vishalvivekm** [comment]
> @Chadha93 @vishalvivekm Currently I am unable to add this agenda in meeting minuted becomes I don't have required edit permissions.

@AdityaRaimec22 Please fill the newcomers' form : https://layer5.io/newcomers, if you've not yet.
Also make sure to use the same email while accessing the meeting minutes

**Comment by Chadha93** [comment]
> > @Chadha93 @vishalvivekm Currently I am unable to add this agenda in meeting minuted becomes I don't have required edit permissions.
> 
> @AdityaRaimec22 Please fill the newcomers' form : [layer5.io/newcomers](https://layer5.io/newcomers), if you've not yet. Also make sure to use the same email while accessing the meeting minutes

@AdityaRaimec22 You can add your topic as suggestion.

**Comment by l5io** [comment]
🚀 Preview for commit 60d46b4ad5aec44cba16074d277954b60f400428 at: https://64c89a255b09553cfceeeed0--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 748ef40783f1ee2670bd35503ef026268d82a00c at: https://64c8cf73e990765f79cd8cae--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 1338c539bccf8a31e65283e00329156f25c9765c at: https://64c9d0b17280e957fbf34f8c--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 652f66a10630eb6b59e8dabac7bda6f64d4ebe71 at: https://64c9d1e05d21554f269bf197--meshery-docs-preview.netlify.app

**Pull request closed without merging**
