### PR TITLE
increase navbar width in docs

### LINKED ISSUE #5040: [Docs] Navbar enhancement
#### Current State

The navbar on [Meshery Docs](https://docs.meshery.io/) and the navbar on [meshery.io](https://meshery.io/) have unequal width.

Screenshot 2022-02-03 at 2 29 52 AM
Screenshot 2022-02-03 at 2 29 24 AM

#### Desired State

Make the navbar on [Meshery Docs](https://docs.meshery.io/) the same width as the navbar on [meshery.io](https://meshery.io/) website. This will allow a more subtle transition from the website to the documentation.

---

#### [Contributor Guides](https://docs.meshery.io/project/contributing) and Resources
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by Sunnyio**
Signed-off-by: Sunny Kumar <sunny514173@gmail.com>

**Description**

This PR fixes #5040 

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit af1040ceb148b68fb156aee2da3e0a07a1e0c708 at: https://61fb861b75fed34862511d95--meshery-docs-preview.netlify.app

**Review by Chadha93 — CHANGES_REQUESTED** [review]
@Sunnyio good work, some minors to look at,  the content below(see search bar) the navbar is getting chopped, need to play more with padding :) 
Screenshot from 2022-02-03 14-53-24

**Comment by Sunnyio** [comment]
Oh! I didn't notice that. Doing it now.

**Comment by l5io** [comment]
🚀 Preview for commit a18c8e247e9d78974f0a7178f06472c8674ff0aa at: https://61fbad47804d9477d7c3d365--meshery-docs-preview.netlify.app

**Review by Chadha93 — APPROVED** [review]
LGTM :1st_place_medal:

**Pull request merged**
