### PR TITLE
fix: remove mapping navigator

### PR DESCRIPTION
**Pull request by Udit-takkar**
**Notes for Reviewers**

This PR fixes  Follow up https://github.com/meshery/meshery/pull/7728/files#r1204849350. added isBeta property here https://github.com/layer5io/meshery-cloud/pull/850

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by theBeginner86 — COMMENTED** [review]
Is this ready for review?

**Review by theBeginner86 — COMMENTED** [review]
Uh-oh, a merge conflict to resolve...

**Comment by theBeginner86** [comment]
When I built your PR locally, then I wasn’t seeing BETA label on MeshMap. Would you please confirm  from your end?

> Just to be sure that I wasn’t having any build cache

**Comment by leecalcote** [comment]
A couple of merge conflicts to look at @Udit-takkar ...

**Review by theBeginner86 — APPROVED** [review]
👏

**Comment by theBeginner86** [comment]
Thanks @Udit-takkar for seeing through this diligently

**Pull request merged**
