### PR TITLE
updated copyright notice w/signoff

### LINKED ISSUE #4230: [Docs] Update copyright notice in footer
#### Current State
The footer of docs.meshery.io has ""

#### Desired State
Change to "© 2021 The Meshery Authors": 

```
<div class="text">&copy; {{ site.time | date: '%Y' }} The Meshery Authors</div>
```

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by fuadnafiz98**
Signed-off-by: fuadnafiz98 <fuadnafiz98@gmail.com>

**Description**

This PR fixes #4230

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 39a6d25412a2b8a6d734371a92b5f40c5ffe148b at: https://614b6abd41f2e6161314f908--meshery-docs-preview.netlify.app

**Review by warunicorn19 — CHANGES_REQUESTED** [review]
@fuadnafiz98 good work, just a minor nitpick, if you could please change the text-color to white.

**Comment by fuadnafiz98** [comment]
Ok, I am working on it.

**Comment by l5io** [comment]
🚀 Preview for commit 11cfde00dbe192dd069b304d76a64cf47c66275b at: https://614b6e3fbb707c2d08a8a6b5--meshery-docs-preview.netlify.app

**Review by warunicorn19 — APPROVED** [review]
LGTM🎉, @fuadnafiz98 thanks for this.

**Comment by fuadnafiz98** [comment]
Thanks for the opportunity!

**Pull request merged**
