### PR TITLE
Remove dry-run from backend slowing down requests

### PR DESCRIPTION
**Pull request by Revolyssup**
Signed-off-by: ashish <ashishjaitiwari15112000@gmail.com>

**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by Revolyssup** [comment]
> Under what circumstances will the dry runs be performed?

After this PR none. Since we are doing validation via /api/meshmode/validate, we don't need this.

**Comment by leecalcote** [comment]
Thanks. When are we doing /meshmodel/validate? I’m looking to confirm that comprehensive thought has been given the overall system flows and that a change here doesn’t have and adverse effect. So that this set of thoughts doesn’t get lost in a GH PR, please point me to a sequence diagram in the Meshery Architecture deck.

**Comment by Revolyssup** [comment]
> Thanks. When are we doing /meshmodel/validate? I’m looking to confirm that comprehensive thought has been given the overall system flows and that a change here doesn’t have and adverse effect. So that this set of thoughts doesn’t get lost in a GH PR, please point me to a sequence diagram in the Meshery Architecture deck.

This change wont break anything as this change wasn't even consumed by any client. This was added as a feature that could have been potentially used by the clients to grey out some designs but was never actually used. So this is just removal of a redundant step.

**Comment by leecalcote** [comment]
@Revolyssup good deal. Irrespective, please point me to a sequence diagram in the Meshery Architecture deck.

**Comment by leecalcote** [comment]
Is https://github.com/meshery/meshery/pull/6195 a more complete implementation given that it comments out lines in multiple files? Please comment this code.

**Comment by Revolyssup** [comment]
> Is #6195 a more complete implementation given that it comments out lines in multiple files? Please comment this code.

Yes, therefore closing this one.

**Pull request closed without merging**
