### PR TITLE
Added end-to-end playwright tests for `UI/Connections` component 

### PR DESCRIPTION
**Pull request by DevRish**
**Notes for Reviewers**

This PR adds end-to-end Playwright tests for Meshery UI (#10890)

Tests added in this PR:
- `UI/Connections`: Open `Connections` page and verify connections are listed 
- `UI/Connections`: Upload kubeconfig file and add cluster (create a new connection)
- `UI/Connections`: Transition between all possible states of connections
  - `connected` state to `disconnected` state and back to `connected` state
  - `connected` state to `ignored` state and back to `connected` state
  - `connected` state to `not found` state and back to `connected` state

This completes all `UI/Connections` tests mentioned in the [Meshery Test Plan](https://docs.google.com/spreadsheets/d/13Ir4gfaKoAX9r8qYjAFFl_U9ntke4X5ndREY1T7bnVs/edit?gid=0#gid=0)

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by vishalvivekm** [comment]
@DevRish Thank you for contributions.
Let's discuss this in Meshery Dev meeting on Wednesday. Adding this as an agenda item....
Meeting minutes: https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit?pli=1#
Meeting link: https://meet.layer5.io/meshery

**Comment by DevRish** [comment]
**Updates:**

Completed all the tests marked as `UI/Connections` from the [Meshery Test Plan](https://docs.google.com/spreadsheets/d/13Ir4gfaKoAX9r8qYjAFFl_U9ntke4X5ndREY1T7bnVs/edit?gid=0#gid=0)

Please review @aabidsofi19 @leecalcote

**Comment by leecalcote** [comment]
@DevRish gooood. Where are your tests running? https://github.com/meshery/meshery/actions/runs/9666731051/job/26666918434?pr=11220 

Let's get them enabled within the workflow (in this PR) so that we can confirm their validity. 👍

**Comment by leecalcote** [comment]
@DevRish are you new tests executing in these lint checks?

**Comment by DevRish** [comment]
The setup to execute them is done. But there is a problem because of which they are failing. 
The very first step required for every test is the authentication, and that test is failing because of a difference in behaviour in the local environment and the github actions environment...
The problem is that, after successful login, the local instance redirects back to `localhost:9081`, but the github actions instance is redirecting to `meshery.layer5.io/dashboard`.
I have been trying to fix it since yesterday.. 
I tried changing environment variables; using minikube instead of helm kind cluster; replicating exactly the steps I followed for the local instance instead of the ones in the previous cypress workflow; but that redirect is still happening  in the github actions instance...

**Comment by leecalcote** [comment]
@DevRish, there's a merge conflict in the Makefile...

**Pull request merged**
