### PR TITLE
update css for mobile view

### PR DESCRIPTION
**Pull request by vishalvivekm**
**Notes for Reviewers**

Related with #10705 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 17293f032dd1eaa968e4f3748d575a7c038f4855 at: https://66157a0d50609f0bcbc23605--meshery-docs-preview.netlify.app

**Comment by vishalvivekm** [comment]
After these changes:

**Review by abhishekmmgn — CHANGES_REQUESTED** [review]
This gives us an immediate fix for the padding.
However, the navbar's height on the smaller-width device has to be reduced.

Also, if we don't have any references, can we reduce the padding to say, 20 or 24 px?

Like this.

image

**Comment by leecalcote** [comment]
@abhishekmmgn you can make suggested code changes inline of the review.

**Comment by leecalcote** [comment]
I added a few more size and padding changes.

**Review by leecalcote — APPROVED** [review]

**Pull request merged**
