### PR TITLE
Merge monikers and error-code columns

### PR DESCRIPTION
**Pull request by vishalvivekm**
**Notes for Reviewers**

This PR fixes /meshery/meshery.io#1020

a couple of changes that this PR does: 
 1. corrects a [typo](https://docs.meshery.io/reference/error-codes#:~:text=Meshery%20and-,it%E2%80%99s,-components%20use%20a) "it's" to "its" 
 2. updates alignment of [Error Code Categories by Component](https://docs.meshery.io/reference/error-codes#error-code-categories-by-component) Table
 3. merges Moniker and Error-Code columns together on reference/error-codes
 
Error Code Categories by Component Table
error-codes

 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
Signed-off-by: Vivek Vishal <110674407+vishalvivekm@users.noreply.github.com>
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit e3f4fd6dc74a354d2daed8b9cbc309abd6ea969e at: https://63fa0b4bf2bf7b10004d8fba--meshery-docs-preview.netlify.app

**Comment by vishalvivekm** [comment]
@leecalcote done!

**Comment by leecalcote** [comment]
Thanks, @vishalvivekm!

@acald-creator, @Revolyssup how can we push this merging even further back into MeshKit Errors, so that the error number is not displayed in the Notification Center separate from the moniker?

Here's an example:
Screenshot 2023-02-27 at 1 57 53 PM

**Review by leecalcote — CHANGES_REQUESTED** [review]
@vishalvivekm will you please bring the two together in the following format:

```
MONIKER-NUMBER
```

**Comment by l5io** [comment]
🚀 Preview for commit 1d94b978254dd4943e8533fc9c3a9b4fc9176d92 at: https://63feeb5bd08d543b23e7e98d--meshery-docs-preview.netlify.app

**Comment by vishalvivekm** [comment]
> @vishalvivekm will you please bring the two together in the following format:
> 
> ```
> MONIKER-NUMBER
> ```
> 
> Example:
> 
> ```
> ErrEmptyConfigCode-1000

You asked for it, Here it's: @leecalcote 
 
updated moniker code format

**Comment by leecalcote** [comment]
Thank you. I neglected to mention that the whole error code should be hyperlinked.

**Comment by vishalvivekm** [comment]
> Thank you. I neglected to mention that the whole error code should be hyperlinked.

@leecalcote It's like, either you click on moniker or the code, it opens a description, probable cause and steps-to-folow for that particular error moniker/code ( watch the video below):
I'd appreciate a little detailing on "whole error code should be hyperlinked".

https://user-images.githubusercontent.com/110674407/222140155-cd524622-a189-423d-867e-a5ab1f211588.mp4

**Pull request merged**
