### PR TITLE
[CI] Enhance Edge Release Channel with Versioning

### LINKED ISSUE #8049: [Docs] Build and Release: Edge Channel now includes versioned releases
#### Current State
Meshery's Edge Release Channel now includes versioned releases. See this week's [Meshery CI meeting minutes](https://docs.google.com/document/d/1GrVdGHZAYeu6wHNLLoiaKNqBtk7enXE9XeDRCvdA4bY/edit#) for an example with screenshot. 

#### Desired State
The description of the Edge Release Channel needs to be updated to reflect this change - https://docs.meshery.io/project/contributing/build-and-release#edge-channel

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by thevaibhavmaurya**
**Notes for Reviewers**

Updated Edge channel with dynamic versioning and improved compatibility for a seamless experience with remote providers. Docker image tags remain consistent.

This PR fixes #8049 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by vaibhav-xt** [comment]
@vishalvivekm, I would appreciate it if you could take a look at the revised content below. I've made some modifications, hoping to address the concerns. If you still find any issues with this version, kindly let me know.

**Comment by l5io** [comment]
🚀 Preview for commit 690d60acb73c277a148c95fa124f7a3c97cb8052 at: https://64bd6805b6caba429e982ec4--meshery-docs-preview.netlify.app

**Review by Freedisch — CHANGES_REQUESTED** [review]
You also need to update a sample of the `version release`  like on the screenshot here

image

**Comment by Chadha93** [comment]
@vaibhav-xt  Let's discuss this on the Meshery Dev call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#) if you would. :)

**Comment by l5io** [comment]
🚀 Preview for commit 7418b51beaccedb6f74e021d378cfbd68fc2da1c at: https://64c290dea5a00c09ae1eb73c--meshery-docs-preview.netlify.app

**Review by leecalcote — APPROVED** [review]

**Pull request merged**
