### PR TITLE
Meshworks

### LINKED ISSUE #2383: [UI] Configuration and Patterns menus
#### Current Behavior
Meshery will be able to ingest and orchestrate service mesh patterns.

#### Desired Behavior
Users will need to access this area of the UI.

#### Implementation
1. Create a new "Configuration" menu.
2. Create a new "Patterns" menu item.

#### Acceptance Tests
1. When the user clicks on the "Configuration" menu, nothing happens.
1. When the user clicks on the "Patterns" menu, they are directed to the /configuration/pattern page, showing either:
  1. a table of existing patterns and actions to take on them or
  1. an empty paper with a button to import a pattern file.

#### Mockups
Screen Template

### PR DESCRIPTION
**Pull request by tangledbytes**
**Description**

This PR fixes #2383

This PR improves meshery server's parallel task execution capability by making the communication between nodes non-blocking.

This PR adds several http endpoints to meshery server like:
1. Persist pattern file
2. Read persisted pattern files
3. Update persisted pattern files
4. Delete persisted pattern files
5. Convert patternfile => cytoscapejs json
6. Convert cytoscapejs json => patternfile

This PR also adds a UI for the user to be able to perform CRUD on the pattern files, which is shown in the video.

meshery_patterns

**Notes for Reviewers**
Please review the UI and suggest if any changes are needed there

**[Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
If I didn't know any better I'd say this PR is full of CRUD.

**Comment by leecalcote** [comment]
I'm not sure that the movie clip fully uploaded.

**Comment by utkarsh-pro** [comment]
> I'm not sure that the movie clip fully uploaded.

@leecalcote replaced it with a gif, hope that resolves the issue

**Comment by leecalcote** [comment]
In this case, viper is no good, because ________________. It doesn't support non-blocking, parallel task execution?

Reuse the same editor component and it allows saving an updated pattern, too. Nice. No action taken from here other than making the pattern available to be translated to cytoscape json and imported via browser, right?

**Review by kumarabd — APPROVED** [review]

**Pull request merged**
