### PR TITLE
Updated Suported Service Meshes table

### LINKED ISSUE #2376: [Docs] Promote Meshery Adapter for NGINX SM to beta
**Current State:**
The Meshery Adapter for NGINX SM is in beta state.

**Desired State:**
The following areas should reflect a "beta" status for this adapter:
- [ ] The README in the root of this repo.
- [x] https://docs.meshery.io/service-meshes/adapters/nginx-sm.

Related - https://github.com/layer5io/meshery.io/issues/398
---
**Contributor Resources**
- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

### PR DESCRIPTION
**Pull request by bartkalanski**
Signed-off-by: Bart Kalanski bkalanski@gmail.com

**Description**
Promoted Meshery adapter for Kuma and Meshery adapter for Open Service Mesh to "stable"

This PR fixes #2376

**Notes for Reviewers**

Apologies about the lack of sign off, I updated the file on GitHub as I could quickly preview the changes.

**[Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — APPROVED** [review]
Thank you, Bart!

**Comment by leecalcote** [comment]
@bartkalanski will you execute these commands? https://github.com/layer5io/meshery/pull/2447/checks?check_run_id=1963930992

More context here - https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#commit-signing

**Comment by bartkalanski** [comment]
> @bartkalanski will you execute these commands? https://github.com/layer5io/meshery/pull/2447/checks?check_run_id=1963930992
> 
> More context here - https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#commit-signing

Notes for Reviewers

Apologies, I updated the file on GitHub, rather than cloning it to my machine as I could quickly preview the changes. I put the sign-off in the description of the PR though, however I dont think GitHub takes that into account. I will from now on clone the repo and update the changes on my machine to avoid the sign-off issue from happening again!

**Comment by leecalcote** [comment]
@bartkalanski, oh, I see. Ok, gotcha. Very frustrating that GitHub doesn't support this.

**Pull request merged**
