### PR TITLE
[Docs] Relocate Contrib-Community location in TOC

### PR DESCRIPTION
**Pull request by leecalcote**
Signed-off-by: Lee Calcote <lee.calcote@layer5.io>

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 0aca7649e680fb81d44fe93875bb427dadaca17f at: https://65b20bebbc39db36c7d591f4--meshery-docs-preview.netlify.app

**Review by iArchitSharma — APPROVED** [review]
LGTM, I've remove `Gemfile.lock`

**Comment by l5io** [comment]
🚀 Preview for commit 1452c40d8b6058054c752ac709a022fc8db31d37 at: https://65b26f265d68b58407b1ae70--meshery-docs-preview.netlify.app

**Comment by leecalcote** [comment]
Thank you much, @iArchitSharma 👍

**Pull request merged**
