### PR TITLE
[Docs] Add menu toggle. Collapsed by default

### PR DESCRIPTION
**Pull request by leecalcote**
Signed-off-by: Lee Calcote <lee.calcote@layer5.io>

**Notes for Reviewers**

This PR collapses the doc sections and adds an expand/collapse toggle. 

#### Problem:

When a user navigates to the children/grandchildren, the page refreshes, causing the menu to show collapsed again. This is confusing to users and they are unable to see the grandchildren items until manually expanding the same section again.

@yash37158 @vishalvivekm, help, help! Your assistance here would be much appreciated.

Untitled

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 794569341265decbf8081c8fce1bb7026238459c at: https://659ddb18927e356a6b7ba0a0--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 30bd409726c30388f6ab156d1dc16c527b718f25 at: https://659ddc64c772596a644eac5b--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit c163f09b0dad1a31a904a3453f640973cbba6d22 at: https://65a00258bd4b0723b89f28ad--meshery-docs-preview.netlify.app

**Comment by iArchitSharma** [comment]
@leecalcote the problem with navigation to the children/grandchildren is solved

**Comment by l5io** [comment]
🚀 Preview for commit 34daaf00d22a4b667d08908b4dc28f3ea9c5cf39 at: https://65a003f37d2904237d8566d6--meshery-docs-preview.netlify.app

**Comment by leecalcote** [comment]
We're close. Open Concepts --> Logical --> Models. Three clicks. See that the menu isn't open.

**Comment by yash37158** [comment]
Good work @iArchitSharma

**Comment by leecalcote** [comment]
@yash37158 do you have suggestions on how to finish the final portion?

**Comment by leecalcote** [comment]
We're still in need of a final fix here.

I'm merging in the meantime.

**Pull request merged**
