### PR TITLE
added links in MeshMap Documentation

### PR DESCRIPTION
**Pull request by ATREAY**
**Notes for Reviewers**
This Pull request adds links in the documentation to direct users to the respective "Designer" and "Visualizer" sections of the Layer5 website.

This PR fixes #
fixes: #9032

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 94de759fe39637a7b115b2b996ff945c74f691a3 at: https://6523a944890583475b1407a1--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 4e4f52801154e27fabefbe7dbf824e3253103195 at: https://6523b4998fddba53cddad809--meshery-docs-preview.netlify.app

**Comment by Ckbhatia** [comment]
Good job. Working well!

**Review by Ckbhatia — APPROVED** [review]

**Comment by l5io** [comment]
🚀 Preview for commit 6151f928c3d260c584c7dc0e3ef0f34641c4086a at: https://652422e276356e00a504c6ef--meshery-docs-preview.netlify.app

**Review by Yashsharma1911 — APPROVED** [review]
LGTM thankyou @ATREAY for fixing it

**Comment by Yashsharma1911** [comment]
Yay 🎈

**Comment by ATREAY** [comment]
Thanks, @Yashsharma1911, for accepting the PR!

**Pull request merged**
