### PR TITLE
Support nighthawk in mesheryctl system start, stop, and restart commands

### LINKED ISSUE #10371: [mesheryctl] Install: Support new Meshery Adapter for Nighthawk
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

### Current Behavior
A new Meshery Adapter is being created in the v0.8 release: https://github.com/meshery/meshery-nighthawk

### Desired Behavior
`mesheryctl system` commands (start, stop, restart, logs and context) all need to support this new adapter.

### Acceptance Tests
1. `mesheryctl system context create --components` supports this new adapter.
2. `mesheryctl system start`
3. `mesheryctl system stop`
4. `mesheryctl system ....` and others

---

### Contributor Resources

- ⌨️ [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](http://discuss.meshery.io) and [Layer5 Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by KunyueXing**
**Notes for Reviewers**

This PR fixes #10371 

Hi, I've included nighthawk adapter in `mesheryctl system` commands - `start`, `restart`, `stop`. Both platforms, docker and Kubernetes, are considered.

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by KunyueXing** [comment]
Hi @leecalcote, @gyohuangxin,

I submitted this PR to fix the [issue 10371](https://github.com/meshery/meshery/issues/10371). Can you please review the PR?

I've included the Nighthawk adapter in `mesheryctl system` commands - `start`, `restart`, `stop`. 

In the issue, it also suggests to support this adapter in `mesheryctl system context create --components`, which I found that I don't need to do any modification. From my understanding, it's the user who could provided this adapter through the command [`mesheryctl system context create context-name --components meshery-nsm --platform docker --url http://localhost:9081 --set --yes`](https://github.com/meshery/meshery/blob/20b803deb2d91c9b59110da379856279a6e8af33/mesheryctl/internal/cli/root/system/context.go#L63), and the input components will be added to the context's components list and apply to [`err := config.AddContextToConfig(args[0], tempCntxt, viper.ConfigFileUsed(), set, false)`](https://github.com/meshery/meshery/blob/20b803deb2d91c9b59110da379856279a6e8af33/mesheryctl/internal/cli/root/system/context.go#L106).  Please let me know if I missed anything.

**Comment by vishalvivekm** [comment]
Thank you @KunyueXing 
Let's discuss this PR on Meshery development call today. Adding it as an agenda item to the meeting minutes.

Timing: 9:00 AM CT
Meeting minutes: [Google Docs](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit)
Meeting link: [meet.layer5.io/meshery](https://meet.layer5.io/meshery)

**Review by leecalcote — COMMENTED** [review]
Thank you, @KunyueXing.

@gyohuangxin, let's hold off on merging this PR until the adapter is ready, otherwise users will see errors.

**Comment by KunyueXing** [comment]
Hi @vishalvivekm, the meeting is held at 7am at my local time and I'm not able to attend it. Could we adjust the meeting time so that it could be more convenient for people in pacific time to join?

**Review by gyohuangxin — APPROVED** [review]
LGTM. Thanks!

**Comment by Ashparshp** [comment]
Thank you @KunyueXing, let's discuss this PR during the Meshery dev meeting call, if you would. Adding it as an agenda item to the meeting minutes.

Timing: 7:30 PM IST / 9:00 AM CT (Wednesday)
Meeting minutes: [Google Doc](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit)
Meeting link: [meet.layer5.io/meshery](https://meet.layer5.io/meshery)

**Pull request closed without merging**
