### PR TITLE
chore: update link to wireframes and designs for Meshery UI in Figma …

### LINKED ISSUE #8142: [CI] GitHub Issue Templates: Update link to Figma team
#### Current Behavior
The project's current issue templates are missing an open invitation link where new contributors can join the community's Figma team and view user interface designs and other UX projects.

#### Desired Behavior
Each template that has a reference to Figma in its resources section should an invite link added.

#### Implementation

In these issue templates:

1. [meshery-ui_bug.md](../blob/master/.github/ISSUE_TEMPLATE/meshery-ui_bug.md)
1. [meshery-ui_feature.md](https://github.com/meshery/meshery/blob/master/.github/ISSUE_TEMPLATE/meshery-ui_feature.md)
1. [meshery-extensions_feature.md](https://github.com/meshery/meshery/blob/master/.github/ISSUE_TEMPLATE/meshery-extensions_feature.md)
1. [meshery-extensions_bug.md](https://github.com/meshery/meshery/blob/master/.github/ISSUE_TEMPLATE/meshery-extensions_bug.md)
1. [fbug_report.md](https://github.com/meshery/meshery/blob/master/.github/ISSUE_TEMPLATE/fbug_report.md)
1. [documentation.md](https://github.com/meshery/meshery/blob/master/.github/ISSUE_TEMPLATE/documentation.md)

replace the current line referring to Figma with this line:

```
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)```

#### Acceptance Tests
1. All references to Figma include the "open invite" link.

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
- Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)
- 🧪 [Meshery Test Plan Spreadsheet](https://docs.google.com/spreadsheets/d/13Ir4gfaKoAX9r8qYjAFFl_U9ntke4X5ndREY1T7bnVs/edit#gid=0)

### PR DESCRIPTION
**Pull request by rupeshshandilya**
This PR fixes #8142

added open link invitation to Figma

Signed-off-by: Rupesh Shandilya <rupeshkshandilya@gmail.com>

### CODE REVIEW

**Review by leecalcote — APPROVED** [review]
Excellent.

**Comment by rupeshshandilya** [comment]
> Please do take care of the DCO issue (sign your commits -- https://github.com/meshery/meshery/pull/8144/checks?check_run_id=14964575329), @rupeshshandilya

okay i take care of it from next time

**Comment by leecalcote** [comment]
> > Please do take care of the DCO issue (sign your commits -- https://github.com/meshery/meshery/pull/8144/checks?check_run_id=14964575329), @rupeshshandilya
> 
> okay i take care of it from next time

Excellent. And you'll take care of it this time, too, using the instructions that are provided in the link that I have handed to you.

**Review by leecalcote — CHANGES_REQUESTED** [review]
> > Please do take care of the DCO issue (sign your commits -- https://github.com/meshery/meshery/pull/8144/checks?check_run_id=14964575329), @rupeshshandilya
> 
> okay i take care of it from next time

Excellent. And you'll take care of it this time, too, using the instructions that are provided in the link that I have handed to you.

**Pull request closed without merging**
