### PR TITLE
[Docs] update the helm charts installation steps

### LINKED ISSUE #6236: [Docs] update the helm charts installation steps
#### Current State
In https://docs.meshery.io/installation/platforms/kubernetes#using-helm-charts,  the helm installation steps are :
```
helm repo add meshery https://meshery.io/charts/
helm install meshery meshery/meshery
```
#### Desired State
update them to be :
```
helm repo add meshery https://meshery.io/charts/
helm install meshery-operator meshery/meshery-operator 
helm install meshery meshery/meshery
```

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by XDRAGON2002**
Signed-off-by: Anant Vijay <anantvijay3@gmail.com>

**Description**
Added `helm install meshery-operator meshery/meshery-oerator`

This PR fixes #6236 

**Notes for Reviewers**
Helm charts installation steps have been updated as requested

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit f78faa4df12ff919b57cb8737b3484bb4ea18ac8 at: https://632db101f8fb5610a91c6b0d--meshery-docs-preview.netlify.app

**Review by nitinmewar — DISMISSED** [review]
lgtm!!

**Comment by leecalcote** [comment]
Thank you for this review, @nitinmewar 👍 

And thank you for this PR, @XDRAGON2002 👍

**Review by leecalcote — CHANGES_REQUESTED** [review]
Please swap the position of the Meshery Server chart and the Meshery Operator chart.

**Comment by XDRAGON2002** [comment]
@leecalcote made the requested changes.

**Comment by l5io** [comment]
🚀 Preview for commit 8621cbc460f26090ff3d5ea2b6132992f5877345 at: https://632ef82342ba860669900de5--meshery-docs-preview.netlify.app

**Review by leecalcote — COMMENTED** [review]
Good! Did you also update the copy to clipboard text?

**Comment by l5io** [comment]
🚀 Preview for commit 89d2fd9be590525b6f4d73a2276ff10be215e6da at: https://6331e8e6e628ae1d87c313de--meshery-docs-preview.netlify.app

**Comment by leecalcote** [comment]
@CyrineG, I'll let you take over reviewing from here. The text in the clipboard area must be updated to match.

**Comment by XDRAGON2002** [comment]
I had made the change in docs/pages/installation/kubernetes.md, do I need to deal with clip board separately?

**Comment by CyrineG** [comment]
@leecalcote the [using helm charts](https://docs.meshery.io/installation/platforms/kubernetes#using-helm-charts) page doesn't have a copy to clipboard function.

**Review by CyrineG — APPROVED** [review]
@XDRAGON2002 LGTM!

**Review by leecalcote — APPROVED** [review]
Thank you, @CyrineG 

Good work, @XDRAGON2002

**Comment by leecalcote** [comment]
🎈 Yay, @XDRAGON2002 🎈

**Comment by XDRAGON2002** [comment]
> 🎈 Yay, @XDRAGON2002 🎈

Thanks!

**Pull request merged**
