### PR TITLE
Refactor/dashboard Remove Connection Status Section

### LINKED ISSUE #7867: [UI] Remove connection status section in the dashboard
#### Current Behavior
As discussed with @leecalcote the connection status section is showing redundant information which are either already present in other sections or could be in a separate section itself. 

#### Desired Behavior
Remove the connection status section and make the workspace and service-mesh section wider (expand  with respect to the whole dashboard).

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by aabidsofi19**
**Notes for Reviewers**

This PR fixes #7867 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — CHANGES_REQUESTED** [review]
Please investigate - https://github.com/meshery/meshery/actions/runs/5292441952/jobs/9579445596?pr=7881

**Comment by leecalcote** [comment]
> The integration tests are failing when looking for the connection-status components inside index page . But i am confused with the e2e test because it is failing when waiting for a component on /management page .

A great question for the #cypress-test channel with @MarioArriaga92

**Comment by aabidsofi19** [comment]
Should I fix the integration tests for the index page?

**Comment by aabidsofi19** [comment]
@leecalcote  yay! all lights green now .

**Comment by aabidsofi19** [comment]
> Please investigate - https://github.com/meshery/meshery/actions/runs/5292441952/jobs/9579445596?pr=7881

done

**Comment by leecalcote** [comment]
This puts us down a test, taking a step backwards. Will you see that this test is relocated to the settings page?

**Comment by aabidsofi19** [comment]
Shouli had removed the test that was looking for connection status in index page .. but  we didn't relocate the deleted components so I don't think of a way to accomodate the test .

**Comment by leecalcote** [comment]
@aabidsofi19 we'll need to either relocate the test (see the Settings page) or will need to confirm that there is an existing test covering this same thing in the Settings page. 👍

**Comment by aabidsofi19** [comment]
@lee i am a little bit confused , how can we test for connection-status in  settings , if the component is not there ..

**Comment by leecalcote** [comment]
> @lee i am a little bit confused , how can we test for connection-status in settings , if the component is not there ..

We covered this in our prior conversation, @aabidsofi19. The components / the connections _are_ present:

Screenshot 2023-06-20 at 6 38 36 PM

**Comment by aabidsofi19** [comment]
@leecalcote, sorry for bothering. I completely lost the fact that they were duplicated in the settings 🫣. I will double-check for the test or move them to the appropriate location. Thank you very much. 🙂

**Comment by leecalcote** [comment]
Wonderful. Much appreciated.

**Comment by Abhishek-kumar09** [comment]
https://github.com/meshery/meshery/issues/7867#issuecomment-1594958918

**Pull request merged**
