### PR TITLE
[docs] fix "Managing Events with Notification Center" link not working properly

### LINKED ISSUE #10043: Two links for "Managing Events with Notification Center" one not working properly.
Screenshot 2024-01-21 at 3 36 05 AM

### CurrentBehavior
On the [main page](https://docs.meshery.io/), there are two links  for "Managing Events with Notification Center" and one of the links is not redirecting to  the desired webpage 
Screenshot 2024-01-21 at 3 42 16 AM

### Desired Behavior
fix the broken second link 

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by dottharun**
**Notes for Reviewers**

This PR fixes #10043 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — APPROVED** [review]
Much appreciated, @dottharun 👍

**Comment by leecalcote** [comment]
Good work! If you haven't joined the [Layer5 Community Slack](https://slack.layer5.io), yet, I invite you to jump in.

**Comment by leecalcote** [comment]
Congratulations on your first PR in this repo, @dottharun 🎈 The first of many?

**Comment by dottharun** [comment]
Great to hear, @leecalcote 
Absolutely, looking forward to many more contributions

**Pull request merged**
