### PR TITLE
[Docs] v0.6 snapshot

### PR DESCRIPTION
**Pull request by leecalcote**
**Notes for Reviewers**

This PR takes a snapshot in time as a copy of the documentation site at the end of the v0.6.x release cycle.

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit d7b2052d21d51ef3fb0684175d5d3d59d65f84d1 at: https://653b27672a07ac7806509ef5--meshery-docs-preview.netlify.app

**Comment by leecalcote** [comment]
⚠️ The snapshot selector (e.g `v0.6`) is not remember across page-to-page navigation.

**Comment by l5io** [comment]
🚀 Preview for commit 327a215adf45288d5cd53ddf8e453b48c42316b3 at: https://653b2df9783fbf7e06571df1--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit cfcbe9e7a66e376bfc3526e4fe6f0f19331f3f39 at: https://653bff238e2f056a7d4e9277--meshery-docs-preview.netlify.app

**Pull request merged**
