### PR TITLE
[WIP] Added workflow_call trigger to DDE workflow

### LINKED ISSUE #5428: [CI] Docker Extension: Invoke Release workflow after Meshery Release completion
#### Current Behavior
Docker Extension builds are reliant on the availability of `mesheryctl`. 

Edge releases of the Docker Extension can and will already simply use pre-published, CLI binaries of the latest Meshery stable release. Stable releases of the Docker Extension need to be involved at the end of a Meshery release workflow because the stable releases of the Docker Extension will need to include the freshly built binaries of the Meshery release.

#### Desired Behavior
The Docker extension workflow should not trigger on a release event, but should trigger on push to master and be capable of being manually dispatched as well (which it already is).

#### Implementation
1. Remove the trigger on release.
1. Have the Meshery stable release workflow invoke the Docker Extension workflow after the `mesheryctl` binaries are uploaded to the release as assets.

#### Acceptance Tests
1. Stable releases of the Docker Extension after successful and include the respectively built `mesheryctl` binary for the given Meshery release.

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by hershd23**
Signed-off-by: hershd23 <hershdhillon23@gmail.com>

**Description**

This PR fixes #5428.

This PR is still work in progress.
@leecalcote I have a question. How do we get the `release-ver` and `stripped-release-ver` from the build-and-release workflow, so that we can pass them to the DDE workflow?

**Notes for Reviewers**

Using the approach mentioned here :-https://docs.github.com/en/actions/using-workflows/reusing-workflows

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Here is an example workflow that kicks off another repo's workflow while providing dispatch inputs - https://github.com/meshery/meshery/blob/master/.github/workflows/notify-providers.yaml

**Comment by hershd23** [comment]
That is calling a separate action here : https://github.com/layer5io/trigger-remote-provider-action/blob/master/action.yml

That's what I am a little confused between, although actions and workflows have similar syntax. I guess what I have done should work as well

**Comment by hershd23** [comment]
Back to my first question how do we extract the release-ver and stripped-ver tags?

**Comment by hershd23** [comment]
Is the difference between GIT_VERSION and GIT_STRIPPED_VERSION just a 'v' in the very beginning?

https://github.com/meshery/meshery/blob/147bcd7b74f40c0c39b9b751034d24333c36e253/.github/workflows/build-and-release.yml#L32

In this line the `${GITHUB_REF/refs\/tags\//} ` ultimately gives us the GIT_VERSION right? Because I don't see any other label that could one is `stable-latest` and the other is `stable-${GITHUB_SHA::8}` which would append the SHA to it.

In that case this could be straightaway assigned to release-ver right?

**Comment by leecalcote** [comment]
@hershd23 you're right, yes.

In terms of testing, _sigh_, this has been rough. Can you "release" on a fork? I don't know. That would help, if so. 

The stable release triggers on push to master, filtering on the presence of a tag containing "v":

```
on:
  push:
    tags:
      - 'v*'
```

Which is slightly different than a release event / trigger (and might help).

**Comment by hershd23** [comment]
@leecalcote check this out. I created a dummy test workflow in my local fork's master and I called DDE-workflow from that.

https://github.com/hershd23/meshery/runs/6198474889?check_suite_focus=true

If you see this : https://github.com/hershd23/meshery/runs/6198474889?check_suite_focus=true#step:6:13

It actually does figure out GIT_VERSION or GIT_STRIPPED_VERSION from refs

**Comment by leecalcote** [comment]
This sounds promising.

**Review by leecalcote — APPROVED** [review]

**Review by leecalcote — APPROVED** [review]
Wow. You make this look easy, @hershd23. 😄

**Pull request merged**
