### PR TITLE
fix right align issue of radio group rjsf model

### PR DESCRIPTION
**Pull request by amitamrutiya**
**Notes for Reviewers**
image

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — COMMENTED** [review]
Make sure that this doesn't negatively impact any other forms.

**Comment by amitamrutiya** [comment]
@sudhanshutech you made this changes. Let me know for which issue you made those changes.

**Comment by sudhanshutech** [comment]
@amitamrutiya after this change will you confirm the rjsf forms in meshmap where we configure components the checkboxes and radio there working fine with no overflow.

**Comment by amitamrutiya** [comment]
I checked all of the rjsf forms. All LGTM.

**Review by leecalcote — APPROVED** [review]

**Pull request merged**
