### PR TITLE
[UI] Meshery Navigator Menu Re-iteration

### LINKED ISSUE #3771: [UI] Revamp Meshery Dashboard
#### Current Behavior

Meshery Dashboard need some revamp.

Current Items to be done:
- [ ] Add Accordion 
- [ ] Fix collapse button to bottom

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by Abhishek-kumar09**
**Description**
- [x] Add Collapsible Drawer icon in Navigator

I didn't used `Accordion` since it has pre-written styles that was hindering the whole Navigator UI. ALso it is built upon paper component which has it's own properties that has to be removed before using thus nullifying the overall benefit of that.

This PR fixes #3771

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Thanks for the explanation of your approach. This makes sense.

**Comment by leecalcote** [comment]
@Abhishek-kumar09 this is looking pretty great. 

Two items on the Help button:
1. Will you evaluate it's alignment? On collapse of the drawer it should be center-aligned with the rest of the icons in the menu above. On open of the drawer, it should be equidistant from the right edge of the drawer as the chevron is from the right side of the drawer.
2. It was good to try out the light blue color. Having tried it, let's revert to the same off-white as the rest of the buttons (should be #FFF with 80% opacity).

On the accordion effort:
1. Let's start off collapsed with only the top-level menus displayed.
2. Let's include the expand/collapse behavior on click of the menu row (not just the dynamic, vertical chevron).

**Comment by Abhishek-kumar09** [comment]
@leecalcote Changes Done. Please have a look.

**Comment by Abhishek-kumar09** [comment]
Centering items is still the hardest thing for developers :laughing:

**Comment by leecalcote** [comment]
Getting closer. The following checkboxes need a check in them.

**Help button:**
- Will you evaluate it's alignment? 
   - [x] On collapse of the drawer it should be center-aligned with the rest of the icons in the menu above. 
   - [ ] On open of the drawer, it should be equidistant from the right edge of the drawer as the chevron is from the right side of the drawer.
   - [ ] On hover of the button, it jumps, but shouldn't move.
- [x] It was good to try out the light blue color. Having tried it, let's revert to the same off-white as the rest of the buttons (should be #FFF with 80% opacity).

**Accordion effort:**
- [x] Let's start off collapsed with only the top-level menus displayed.
- Let's include the expand/collapse behavior on click of the menu row (not just the dynamic, vertical chevron).
  - [x] expand onclick
  - [ ] collapse onclick

**Comment by Abhishek-kumar09** [comment]
Actually the chevron icon is aligned to right with the same level as drawer bottom items.
zzzzz

But If we want to be more aligned towards right, then sending the fix.

**Comment by Abhishek-kumar09** [comment]
Remaining item done except:
- [ ] On hover of the button, it jumps, but shouldn't move.

I saw every style configuration but couldn't find the possible reason for the slight jump behaviour in chevron. Will see more.

**Comment by leecalcote** [comment]
@Abhishek-kumar09, gotcha. Ok, let's merge this one in the meantime. 👍

**Pull request merged**
