### PR TITLE
[chore] Removed OSM

### PR DESCRIPTION
**Pull request by nebula-aac**
**Notes for Reviewers**

This PR is related to https://github.com/meshery/meshery/issues/8305

OSM is being removed from
- [x] Meshery Server
- [x] Docker Extension
- [x] Docker Kubernetes deployment
- [x] `mesheryctl`
- [x] Meshery UI

Still needs to remove this from other places.

Also I'm removing CPX because we're not even using this, and it can be misleading on the UI that there is an adapter we may support.

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — APPROVED** [review]
LGTM

**Comment by leecalcote** [comment]
@theBeginner86 is this expected? https://github.com/meshery/meshery/actions/runs/5763623576/job/15625842540?pr=8375#step:4:23

**Comment by nebula-aac** [comment]
@leecalcote it's probably because i touched one of the files in Helm but I'm sure I didn't, but I wasn't sure

**Comment by leecalcote** [comment]
@theBeginner86 it seems to be the removal of `namespace: {{ .Release.Namespace }}` in template files that is causing this lint failure.

**Comment by leecalcote** [comment]
Failed mesheryctl unit test is not related.

**Pull request merged**
