### PR TITLE
small ui fix for grafana boards

### LINKED ISSUE #2450: [Grafana] Istio two bundled boards not loading
#### Description
Two of the Grafana dashboards that come bundled with the Grafana add-on, there are two that fail to load while the rest load and show metrics. The two that fail are: “Istio Service Dashboard” and “Istio Workload Dashboard”. 

#### Expected Behavior
Boards and metrics should load and display.

#### Screenshots/Logs
https://user-images.githubusercontent.com/7570704/108917096-d8850b80-75f4-11eb-842a-ae2d285cec11.mov

#### Environment:
- Meshery Version: v0.5.0-rc-3

### PR DESCRIPTION
**Pull request by vineethvanga18**
Signed-off-by: vineethvanga18 <reddy.8@iitj.ac.in>

**Description**

This PR fixes #2450

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Vineeth, will you describe the logic behind this change? What did having the ? do and what affect does having it removed have?

**Comment by vineethvanga18** [comment]
@leecalcote previously because of the error we couldnt select these two boards. But now we wont be getting any error and so we could select them.

**Comment by leecalcote** [comment]
So, the user will get the data (panels and charts) from these boards now? Please explain in technical detail what behavior change this PR makes. Is this preventing the throwing of a javascript error only?

**Comment by vineethvanga18** [comment]
@leecalcote Yes this just prevents javascript error and so we will be able to select these boards. 
Getting the data is totally upto grafanaclient(backend). I checked it and can confirm that it is an issue on the backend itself.

**Comment by leecalcote** [comment]
Thank you, @vineethvanga18

**Pull request merged**
