### PR TITLE
Fix Duplicated Kubernetes Subheading in home/guides/tutorials of Docs

### PR DESCRIPTION
**Pull request by devbird007**
**Notes for Reviewers**
The https://docs.meshery.io/guides/tutorials section has two Kubernetes subsections.
This PR fixes this issue.

Before:
Screenshot from 2024-08-27 11-13-02

After:
Screenshot from 2024-08-27 11-14-14

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 24fe1056e4acc3d3a4f5e9362903f7d12a785f01 at: https://66cda8df0a0f55d3a1e2eee7--meshery-docs-preview.netlify.app

**Comment by Alero-Awani** [comment]
Nice! Thank you 🚀

**Comment by leecalcote** [comment]
Thanks, @devbird007!

**Review by hargunkaur286 — APPROVED** [review]

**Comment by hargunkaur286** [comment]
LGTM! 🚀

**Comment by l5io** [comment]
🚀 Preview for commit 9d98a80dbba580661c0fa6deee54a9a1aecf3ed6 at: https://66ce2fc3401f1c7a1fb7aa74--meshery-docs-preview.netlify.app

**Comment by Ashparshp** [comment]
@devbird007, let's discuss this PR during the Meshery dev meeting call, if you would. Please add it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit?usp=drivesdk).

**Review by leecalcote — APPROVED** [review]

**Pull request merged**
