### PR TITLE
fix: failing golint-ci test for mesheryctl

### PR DESCRIPTION
**Pull request by RipulHandoo**
**Notes for Reviewers**

This PR fixes #
1.  golangci-lint checks (example: https://github.com/meshery/meshery/actions/runs/7993330368/job/21828900989?pr=10365)

Desired Result:
Screenshot 2024-02-23 005449

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by RipulHandoo** [comment]
No more undefined error messages from docs_test.go.

**Review by leecalcote — APPROVED** [review]
Library of choice: testify

**Comment by leecalcote** [comment]
@alphaX86 does this look good to you?

**Review by alphaX86 — COMMENTED** [review]
Usage of testify library? This sounds intriguing! 

Also, let me check if the package can be renamed to `doc` instead of `main` to avoid conflicts real quick...

EDIT: Ok, it worked

**Review by alphaX86 — APPROVED** [review]
LGTM!

**Review by Althaf66 — APPROVED** [review]
Great!

**Pull request merged**
