### PR TITLE
Reverted the Secret names in Update first-time-contributor.yml

### PR DESCRIPTION
**Pull request by aryannargotra**
**Notes for Reviewers**

This PR fixes #

This PR fixes #1234.

**Changes Made:**

Reverted the secret name to its original value.

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [.] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Be sure to signoff your commits, @aryannargotra  - https://github.com/meshery/meshery/pull/12446/checks?check_run_id=31814462502

**Comment by aryannargotra** [comment]
> Be sure to signoff your commits, @aryannargotra - https://github.com/meshery/meshery/pull/12446/checks?check_run_id=31814462502

Sorry, My bad.

**Comment by l5io** [comment]
🚀 Preview for commit 45328088597d4e85ce5d48e50a51f14167beb81a at: https://671bbaf04328155d5458d952--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 209f03bd20c61a96dd48e4d557acb10ca2edc1d0 at: https://671bbf94f49ca56661ac1030--meshery-docs-preview.netlify.app

**Comment by leecalcote** [comment]
@aryannargotra DCO check is still failing.

**Pull request closed without merging**
