### PR TITLE
chore: remove commented out GitHub link in navigation.yml

### PR DESCRIPTION
**Pull request by leecalcote**
Signed-off-by: Lee Calcote <lee.calcote@layer5.io>

**Notes for Reviewers**

This PR removes both a commented out link, and also, removes the existing GitHub link.

**Justification**
The link to Meshery's org/repos is in the footer and in many places. We want to ensure that users ready the docs see the Playground button and really explore the project by using the Playground. Removing the duplicate GitHub link here helps ensure the playground button is visible.

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit a845a7ec2959dfeaa596b15a2aad27e58c28af3d at: https://667c741305f236b259b7ca03--meshery-docs-preview.netlify.app

**Comment by leecalcote** [comment]
Testing new comment on snapshot image...

**Comment by l5io** [comment]
🚀 Preview for commit 9cf90554fd53a90a06878eb9986825edd6784a00 at: https://667cfabefab9d06d40b7b1ed--meshery-docs-preview.netlify.app

**Review by goldfishdolphin — APPROVED** [review]
LGTM

**Review by vishalvivekm — APPROVED** [review]

**Comment by l5io** [comment]
🚀 Preview for commit 385a46d86a9135795c1e55ff8c7b7778b17caf83 at: https://66827981fb856500892462e5--meshery-docs-preview.netlify.app

**Pull request merged**
