### PR TITLE
[UI] Fixed Overlay cards in Meshery Performance

### LINKED ISSUE #3920: [UI] [Performance] Remove overlay of cards
#### Current Behavior
In Meshery Performance, the cards are placed above another card.

#### Desired Behavior
Remove the overlay card and let's have the data on a single card itself.

#### Mockups
WhatsApp Image 2021-08-18 at 12 36 15

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by mani9896**
**Description**

This PR fixes #3920 on mehsry performance Dashboard

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by warunicorn19 — APPROVED** [review]
Screenshot 2021-08-25 at 12 03 39 PM

Looks nice and clean.🎉 Thanks for this @mani9896

**Comment by piyushsingariya** [comment]
Could you rename the PR with a better summary?

**Comment by mani9896** [comment]
> Screenshot 2021-08-25 at 12 03 39 PM
> 
> Looks nice and clean. Thanks for this @mani9896

thanks for the review

**Comment by mani9896** [comment]
> Could you rename the PR with a better summary?

hey done , is this new change fine?

**Review by sudo-NithishKarthik — COMMENTED** [review]
Can we have a divider between run test and profiles ?

**Comment by warunicorn19** [comment]
Yup this is better

**Comment by mani9896** [comment]
Done made the latest PR

**Review by warunicorn19 — APPROVED** [review]
Thanks for this @mani9896 🎉

**Comment by mani9896** [comment]
> Thanks for this @mani9896

Hey when can this Pr be merged?

**Comment by mani9896** [comment]
@sudo-NithishKarthik Hey any review on this?

**Comment by sudo-NithishKarthik** [comment]
Yep, 

1. Can you make that a little bit shorter ( approx 65% of the height of the card) ?
2. Can you try charcoal color for the line ?

**Comment by mani9896** [comment]
> Yep,
> 
> 1. Can you make that a little bit shorter ( approx 65% of the height of the card) ?
> 2. Can you try charcoal color for the line ?

yeah sure

**Comment by mani9896** [comment]
> Yep,
> 
> 1. Can you make that a little bit shorter ( approx 65% of the height of the card) ?
> 2. Can you try charcoal color for the line ?

Screenshot from 2021-08-29 11-30-51

**Comment by sudo-NithishKarthik** [comment]
Yep, just reduce the opacity a bit and we will be good to go

**Comment by sudo-NithishKarthik** [comment]
you can push this commit.

**Comment by mani9896** [comment]
> you can push this commit.

done

**Review by sudo-NithishKarthik — APPROVED** [review]

**Pull request merged**
