### PR TITLE
removed requirements for k8s connections

### LINKED ISSUE #8364: [mesheryctl] `perf` should not require connection to Kubernetes
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior
```
$ mesheryctl perf
Error: Get "https://localhost:9443/api/v1/pods": dial tcp [::1]:9443: connect: connection refused.
The Kubernetes cluster is not accessible. Please confirm that the token is valid. See https://docs.meshery.io/installation/quick-start for additional instructions
```

#### Environment

- Meshery Client Version: stable-v0.6.115

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- 📺 [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- ⌨️ [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- ⌨️ [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by EraKin575**
**Notes for Reviewers**

This PR fixes #8364 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — APPROVED** [review]
LGTM

@EraKin575 did you verify that the command runs smoothly when there is no K8s cluster available?

**Comment by EraKin575** [comment]
@leecalcote yep! It no longer asks for connectionn to k8s to run perf command .
image

**Comment by leecalcote** [comment]
Thanks. However, my question is whether or not the command itself performs its duty appropriately (successfully).

**Comment by EraKin575** [comment]
> Thanks. However, my question is whether or not the command itself performs its duty appropriately (successfully).
I think it works :)
image

**Review by Philip-21 — APPROVED** [review]
@leecalcote it LGTM, the health checks he removed are more related to `mesheryctl system check`. But one will have to monitor he perormance command.

**Comment by saurabh100ni** [comment]
Let's discuss this on the Meshery dev call tomorrow,
Please add this as your agenda item in Docs: https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit

**Review by MUzairS15 — APPROVED** [review]
LGTM.
@zakisk Will you perform the testing as well?

**Comment by zakisk** [comment]
@leecalcote @EraKin575 

> Thanks. However, my question is whether or not the command itself performs its duty appropriately (successfully).

@leecalcote Yes, it works.

**Review by zakisk — APPROVED** [review]

**Pull request merged**
