### PR TITLE
Moved meshery adapter for osm

### LINKED ISSUE #1451: [Docs] Move "Meshery Adapter for Open Service Mesh" from alpha to beta in Meshery README
**Current State:**
The Meshery Adapter for Open Service Mesh is listed in the alpha section of the [Supported Service Meshes](https://github.com/layer5io/meshery#supported-service-meshes) table.

**Desired State:**
The Meshery Adapter for Open Service Mesh should be listed in the beta section of the [Supported Service Meshes](https://github.com/layer5io/meshery#supported-service-meshes) table.

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

### PR DESCRIPTION
**Pull request by codequinn**
Signed-off-by: hikky08 <ikrambabs@gmail.com>

**Description**

This PR fixes #1451

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by PluckyPrecious — CHANGES_REQUESTED** [review]
Welldone @hikky08 🥳  could you kindly make changes to the rowspan? Change line 85 -beta from "3" to  "4", line 102 alpha from "8" to "5" to make the table a pefect fit.

**Comment by leecalcote** [comment]
Thank you, @hikky08 and @PluckyPrecious 👍

**Comment by PluckyPrecious** [comment]
Yippie! 🥳

**Comment by leecalcote** [comment]
Yay, @hikky08!

**Comment by Ruth-ikegah** [comment]
Welldone @hikky08 nice job!

**Comment by hikky08** [comment]
> Looking good! @hikky08

Thank you

**Pull request merged**
