### PR TITLE
fix improper passing and usage of props

### PR DESCRIPTION
**Pull request by MUzairS15**
**Notes for Reviewers**

This PR fixes #

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by MUzairS15** [comment]
// @yash37158

**Comment by MUzairS15** [comment]
// @yash37158

**Comment by MUzairS15** [comment]
// @Yashsharma1911

**Review by Yashsharma1911 — APPROVED** [review]

**Comment by Yashsharma1911** [comment]
Uhh ho merge conflict

**Comment by Yashsharma1911** [comment]
Screenshot 2024-04-10 at 6 05 31 AM

**Review by Yashsharma1911 — APPROVED** [review]
LGTM

**Pull request merged**
