### PR TITLE
[<Navigator/>]: Navigation highlight fix on subsections under Management section

### LINKED ISSUE #3268: [UI] Navigation highlight not working properly for subsections under Management section
#### Description
Subsections under **Management** section are not getting highlighted when navigated to those sections. But rather, **Management** is getting highlighted

#### Expected Behavior
The navigated subsection should be highlighted. 

#### Screenshots/Logs

https://user-images.githubusercontent.com/75248557/123373245-b00d1e00-d5a2-11eb-8cc3-c6ce42317257.mov

#### Environment:
- Meshery Version: stable-v0.5.26
- Kubernetes Version: v1.19.7
- Host OS: Big Sur
- Browser: Brave 

---

**Contributor Resources:**
- (Contributing Docs](https://docs.meshery.io/project/contributing)

### PR DESCRIPTION
**Pull request by nishit-prasad**
Signed-off-by: Nishit Prasad <prasad.nishit0@gmail.com>

**Description**
Subsections under Management section were not getting highlighted when navigated to those sections.
This PR fixes #3268 

**Notes for Reviewers**
The below screen recording shows the fix verified in both `localhost:3000` and `localhost:9081`
ScreenRecord

**[Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Good stuff, @nishit-prasad. We're going to need to hold on merging this PR until Meshery's routes are not pointed at the emergent next-generation management UI (the one with the broken interface at the moment).

**Review by sudo-NithishKarthik — APPROVED** [review]
Looks good to me ! ✌🏽

**Comment by nishit-prasad** [comment]
Rebased and force-pushed (re-wrote the history within this branch). Hopefully it's ready for merge soon.

**Comment by sudo-NithishKarthik** [comment]
Thank you @nishit-prasad  😄

**Comment by leecalcote** [comment]
Yes! I hope so, too, @nishit-prasad. We'd very much like to see this land.

@sudo-NithishKarthik @dhruv0000 @Ayush-Khandelwal-007, I'll await your go-ahead here.

**Comment by leecalcote** [comment]
@Ayush-Khandelwal-007, what do you think? Any foreseeable issues here? @dhruv0000 ?

**Comment by nishit-prasad** [comment]
@leecalcote Kindly let me know when it is ready for merge and I will rebase it again, if needed.
Appreciate the consistent follow ups.

**Comment by dhruv0000** [comment]
The navigation sub-sections are only getting highlighted for unconnected adaptors and not for connected adaptors.
This is likely because the connected adaptors are redirected to `/management?adapter=mesherylocal.layer5.io:10000` endpoint which has the prefix `/management` and not `/management/istio` (hence the heighlighting of `Management` section and not `Istio` sub-section).


 We might want to rethink how adaptor endpoints work, or how UI handles them. Suggestions @piyushsingariya @sudo-NithishKarthik ?

management

**Comment by piyushsingariya** [comment]
> The navigation sub-sections are only getting highlighted for unconnected adaptors and not for connected adaptors.
> This is likely because the connected adaptors are redirected to `/management?adapter=mesherylocal.layer5.io:10000` endpoint which has the prefix `/management` and not `/management/istio` (hence the heighlighting of `Management` section and not `Istio` sub-section).
> 
> We might want to rethink how adaptor endpoints work, or how UI handles them. Suggestions @piyushsingariya @sudo-NithishKarthik ?
> 
> management

yeah, you're right. We should handle this redirect correctly for the connected adapters. :+1:

**Comment by Ayush-Khandelwal-007** [comment]
> The navigation sub-sections are only getting highlighted for unconnected adaptors and not for connected adaptors.
> This is likely because the connected adaptors are redirected to `/management?adapter=mesherylocal.layer5.io:10000` endpoint which has the prefix `/management` and not `/management/istio` (hence the heighlighting of `Management` section and not `Istio` sub-section).
> 
> We might want to rethink how adaptor endpoints work, or how UI handles them. Suggestions @piyushsingariya @sudo-NithishKarthik ?
> 
> management

Agreed! This was one of my suggestion few days back when I had asked if we could have separate routes for all adopters.

**Comment by sudo-NithishKarthik** [comment]
> The navigation sub-sections are only getting highlighted for unconnected adaptors and not for connected adaptors.
> This is likely because the connected adaptors are redirected to `/management?adapter=mesherylocal.layer5.io:10000` endpoint which has the prefix `/management` and not `/management/istio` (hence the heighlighting of `Management` section and not `Istio` sub-section).
> 
> We might want to rethink how adaptor endpoints work, or how UI handles them. Suggestions @piyushsingariya @sudo-NithishKarthik ?
> 
> management

Yes @dhruv0000 , agreed. We can just have a single endpoint of the format `/management/[service_mesh]` and conditionally render the dashboards based on the connection status of the adapters.

**Comment by sudo-NithishKarthik** [comment]
Merging this PR will do no harm, we can track the other issues separately.

**Review by sudo-NithishKarthik — APPROVED** [review]
Thank you @nishit-prasad 🎉

**Pull request merged**
