### PR TITLE
Update system status and system logs

### LINKED ISSUE #2698: [mesheryctl] logs: unable to see a Meshery container's logs on Kubernetes platform
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior
Unable to view logs for a Meshery container.

#### Screenshots/Logs
```
➜  ~ kubectl get pods -A
NAMESPACE      NAME                                     READY   STATUS    RESTARTS   AGE
istio-system   istio-egressgateway-96cf6b468-vv5bc      1/1     Running   0          9m41s
istio-system   istio-ingressgateway-57b94d999-f6kl4     1/1     Running   0          9m40s
istio-system   istiod-58c5fdd87b-mllzf                  1/1     Running   0          10m
kube-system    coredns-f9fd979d6-8h89q                  1/1     Running   3          2d2h
kube-system    coredns-f9fd979d6-lm2bm                  1/1     Running   3          2d2h
kube-system    etcd-docker-desktop                      1/1     Running   3          2d2h
kube-system    kube-apiserver-docker-desktop            1/1     Running   3          2d2h
kube-system    kube-controller-manager-docker-desktop   1/1     Running   3          2d2h
kube-system    kube-proxy-dq85p                         1/1     Running   3          2d2h
kube-system    kube-scheduler-docker-desktop            1/1     Running   3          2d2h
kube-system    storage-provisioner                      1/1     Running   5          2d2h
kube-system    vpnkit-controller                        1/1     Running   3          2d2h
meshery        meshery-74745fb8c9-6bkh2                 1/1     Running   0          14m
meshery        meshery-consul-6c77dcd486-684cp          1/1     Running   0          14m
meshery        meshery-cpx-5bc6f8dddf-c6zsv             1/1     Running   0          14m
meshery        meshery-istio-5977448cb8-qrl48           1/1     Running   0          14m
meshery        meshery-kuma-9c4f9879c-kb8b7             1/1     Running   0          14m
meshery        meshery-linkerd-f4c6db56d-vdhm2          1/1     Running   0          14m
meshery        meshery-nsm-6bb69cc498-52z5l             1/1     Running   0          14m
meshery        meshery-operator-549bf67565-4v4m5        2/2     Running   0          19m
meshery        meshery-osm-f4f7b47c6-hptk5              1/1     Running   0          14m
meshery        meshery-traefik-mesh-cd95d64b-npr8r      1/1     Running   0          14m
➜  ~ mesheryctl system logs meshery-cpx-5bc6f8dddf-c6zsv
Error: unknown command "meshery-cpx-5bc6f8dddf-c6zsv" for "mesheryctl system logs"
Usage:
  mesheryctl system logs [flags]

Flags:
  -h, --help   help for logs

Global Flags:
      --config string    config file (default location is: /Users/lee/.meshery/config.yaml)
  -c, --context string   (optional) temporarily change the current context.
  -v, --verbose          verbose output
  -y, --yes              (optional) assume yes for user interactive prompts.
```

- Meshery Version: v0.5.2
- PlatformL kubernetes

---

#### Contributor Resources

- [mesheryctl Contributing Guide](https://github.com/layer5io/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)

### LINKED ISSUE #2699: [mesheryctl] `system status` does not provide necessary output for use in `system logs`
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior
Users are forced to run a `kubectl` command in order to find the pod name for the Meshery container's logs that they want to view.

#### Desired Behavior
1. Allow deployment name to be used instead of pod name.
or
2. Provide pod name with `system status`

---

```
➜  ~ kg pods -A
NAMESPACE      NAME                                     READY   STATUS    RESTARTS   AGE
istio-system   istio-egressgateway-96cf6b468-vv5bc      1/1     Running   0          9m41s
istio-system   istio-ingressgateway-57b94d999-f6kl4     1/1     Running   0          9m40s
istio-system   istiod-58c5fdd87b-mllzf                  1/1     Running   0          10m
kube-system    coredns-f9fd979d6-8h89q                  1/1     Running   3          2d2h
kube-system    coredns-f9fd979d6-lm2bm                  1/1     Running   3          2d2h
kube-system    etcd-docker-desktop                      1/1     Running   3          2d2h
kube-system    kube-apiserver-docker-desktop            1/1     Running   3          2d2h
kube-system    kube-controller-manager-docker-desktop   1/1     Running   3          2d2h
kube-system    kube-proxy-dq85p                         1/1     Running   3          2d2h
kube-system    kube-scheduler-docker-desktop            1/1     Running   3          2d2h
kube-system    storage-provisioner                      1/1     Running   5          2d2h
kube-system    vpnkit-controller                        1/1     Running   3          2d2h
meshery        meshery-74745fb8c9-6bkh2                 1/1     Running   0          14m
meshery        meshery-consul-6c77dcd486-684cp          1/1     Running   0          14m
meshery        meshery-cpx-5bc6f8dddf-c6zsv             1/1     Running   0          14m
meshery        meshery-istio-5977448cb8-qrl48           1/1     Running   0          14m
meshery        meshery-kuma-9c4f9879c-kb8b7             1/1     Running   0          14m
meshery        meshery-linkerd-f4c6db56d-vdhm2          1/1     Running   0          14m
meshery        meshery-nsm-6bb69cc498-52z5l             1/1     Running   0          14m
meshery        meshery-operator-549bf67565-4v4m5        2/2     Running   0          19m
meshery        meshery-osm-f4f7b47c6-hptk5              1/1     Running   0          14m
meshery        meshery-traefik-mesh-cd95d64b-npr8r      1/1     Running   0          14m
➜  ~ mesheryctl system logs meshery-cpx-5bc6f8dddf-c6zsv
Error: unknown command "meshery-cpx-5bc6f8dddf-c6zsv" for "mesheryctl system logs"
Usage:
  mesheryctl system logs [flags]

Flags:
  -h, --help   help for logs

Global Flags:
      --config string    config file (default location is: /Users/lee/.meshery/config.yaml)
  -c, --context string   (optional) temporarily change the current context.
  -v, --verbose          verbose output
  -y, --yes              (optional) assume yes for user interactive prompts.
```

#### Environment

- Host OS: 
- Meshery Version: v0.5.2
- Platform: Kubernetes

---

#### Contributor Resources

- [mesheryctl Contributing Guide](https://github.com/layer5io/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)

### LINKED ISSUE #2932: [mesheryctl] `system status` does not show the status of the `meshery-operator` for `platform: docker`
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior

`system status` for `platform: docker` does not show the status of the `meshery-operator`-

Screenshot from 2021-05-15 14-06-17

#### Desired Behavior

It should also display the operator status.

---

#### Contributor Resources

- [mesheryctl Contributing Guide](https://github.com/layer5io/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)

### PR DESCRIPTION
**Pull request by pottekkat**
Signed-off-by: navendu-pottekkat <navendupottekkat@gmail.com>

**Description**

This PR fixes #2699 , fixes #2698 and also fixes #2932

Basically fix bugs and improve logic in `system status` and `system logs`.

**Changes and Added features**

`system status` will show output that can be used for `system logs`-

Screenshot from 2021-05-14 15-59-51

`system logs` can obtain logs from a specific pod-

Screenshot from 2021-05-14 16-00-06

`system logs` can obtain logs from multiple specified pods-

Screenshot from 2021-05-14 16-00-50

`system logs` can identify which logs to show even if the pod name is not fully specified-

Screenshot from 2021-05-14 16-02-16

`system logs` suggests the user to use `system status` to see the available pods if the specified pod is invalid-

Screenshot from 2021-05-14 16-25-38

- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
How sweet this is, @navendu-pottekkat - "`system logs` can identify which logs to show even if the pod name is not fully specified." 🥇 

Given the great UX of `system logs`, will you consider not outputting the full pod ID in `system status`, leaving the full ID for a `-v` flag?

**Comment by leecalcote** [comment]
`meshery-bob` foiled again. Dang.

**Comment by navendu-pottekkat** [comment]
@leecalcote Bob is back!

Yes I will make those changes now 🤝

**Comment by navendu-pottekkat** [comment]
Actually, there is a catch here if we make that change.

If you try to output logs for `meshery`, it will also show the logs for all other pods since it begins with `meshery`.

Also, the pod names are not consistent so I do not think we cannot easily "chop off" the unwanted parts and only display the parts we need.

**Comment by navendu-pottekkat** [comment]
Updated the `system status` command to show better logs-

Screenshot from 2021-05-15 12-46-38

The greedy search(user not having to type the full pod name) still works because we search from the `meshery` pod.

They can get the names from either `system status` or `kubectl get pods` and use that name to get logs in `system logs`-

Screenshot from 2021-05-15 12-46-44

Screenshot from 2021-05-15 12-46-52

Screenshot from 2021-05-15 12-50-51

// @leecalcote Please review the changes.

**Comment by navendu-pottekkat** [comment]
Will add a fix here on the docker system status as well to this PR

**Comment by navendu-pottekkat** [comment]
Fixed.

Now, it will also show logs for docker platform.

Screenshot from 2021-05-15 14-46-07

**Comment by leecalcote** [comment]
This is great. I think a user of `system logs` on Docker, my wonder why the operator is displayed separately without a section label identifying one section as on Docker and the other as on Kubernetes, but this is a small concern.

**Pull request merged**
