### PR TITLE
[chore] feat: add test plan sheets

### LINKED ISSUE #7738: [CI] [Testing] Meshery Test plan link & guidelines for using it to "Continuous Integration / DevOps" template (.github/ISSUE_TEMPLATE/ci.md)
#### Current Behavior
“Continuous Integration / DevOps - Improve or update workflows or other automation” issue template does not include links nor guidelines on how to work with Meshery Test Plan Google Docs spreadsheets

#### Desired Behavior
Any contributor using the “Continuous Integration / DevOps - Improve or update workflows or other automation” issue template [.github/ISSUE_TEMPLATE/ci.md](https://github.com/meshery/meshery/blob/master/.github/ISSUE_TEMPLATE/ci.md?plain=1) from the [New issue template list](https://github.com/meshery/meshery/issues/new/choose) should see:
- Link to [Meshery Test Plan - v0.7.0 sheet](https://docs.google.com/spreadsheets/d/13Ir4gfaKoAX9r8qYjAFFl_U9ntke4X5ndREY1T7bnVs/edit#gid=0)
- Link to [Meshery Test Plan - Automated Tests/Builds sheet](https://docs.google.com/spreadsheets/d/13Ir4gfaKoAX9r8qYjAFFl_U9ntke4X5ndREY1T7bnVs/edit#gid=1214153102) Google sheet
- Some guidelines for using them, keeping them updated, etc.

#### Implementation
@Revolyssup, @theBeginner86, @Abhishek-kumar09, @leecalcote, myself, and any other contributors are welcome to update this section or enter issue comments making suggestions but here are some initial thoughts:
1. Add new row to v0.7.0 sheet in case a new Test Scenario **(Combination of Test Group, Component Under Test, Platform, Service Mesh, Action and/or Expected Outcome)**: 
   - Started existing recently as per implemented **(merged PR targeting 'master' branch)**
   - Will exist as per upcoming New Features/Enhancements being discussed/implemented. **(New Test Group, Component Under Test, Platform, etc.)**
2. Update existing row to v0.7.0 sheet in case an existing Test Scenario **(see point 1 for definition)**:
   - Has changed in a significant/relevant way **(different Component, , etc.)**
   - "Actual Outcome" and/or "Additional Remarks" should be updated when an issue, abnormal or unexpected behavior has occurred during usage with Meshery UI, Mesheryctl CLI, Meshery Docker Extension, a specific Meshery adapter and/or Meshmap extension as a user through a recent release (or when building from source).

#### Acceptance Tests
"Continuous Integration / DevOps" issue template's **Contributor [Guides]** section is updated with a new bullet with link and guidelines mentioned above:
CleanShot 2023-05-25 at 13 00 34

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by Ghat0tkach**
Added test plans sheet and guidelines regarding updating them in ci.md

**Notes for Reviewers**

This PR fixes #7738 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Ghat0tkach** [comment]
@MarioArriaga92 Please review the request and suggest any desired changes. 

Thank You!

**Comment by leecalcote** [comment]
Thanks, @Ghat0tkach. I wonder if this can be made much more concise.

**Comment by Ghat0tkach** [comment]
> Thanks, @Ghat0tkach. I wonder if this can be made much more concise.

Yes ,  I m thinking the same will look into it .
Thank you

**Comment by Ghat0tkach** [comment]
@leecalcote , Please have a look and suggest the changes.

Thank you

**Review by leecalcote — CHANGES_REQUESTED** [review]
Thanks for this, @Ghat0tkach.

Please reduce this to a single new, bulleted line that points to a page in the Meshery Docs contributing guide where the rest of this information is captured.

**Comment by Ghat0tkach** [comment]
> Thanks for this, @Ghat0tkach.
> 
> Please reduce this to a single new, bulleted line that points to a page in the Meshery Docs contributing guide where the rest of this information is captured.

Thanks for your quick reply , Apologies for the confusion but am I supposed to add this [meshery docs](https://docs.meshery.io/project/contributing/contributing-docs) link as bullet point?

**Comment by leecalcote** [comment]
> > Thanks for this, @Ghat0tkach.
> > Please reduce this to a single new, bulleted line that points to a page in the Meshery Docs contributing guide where the rest of this information is captured.
> 
> Thanks for your quick reply , Apologies for the confusion but am I supposed to add this [meshery docs](https://docs.meshery.io/project/contributing/contributing-docs) link as bullet point? I Have checked the website and found only mesheryctl, SMI and Cypress tests documentation 😅, dont we have a link to these sheets on the website where the guidelines have already been mentioned 😅?

I recommend that you raise this as a question in the Meshery CI meeting.

**Comment by Ghat0tkach** [comment]
@leecalcote , Thank you will do the same

**Review by leecalcote — APPROVED** [review]

**Comment by leecalcote** [comment]
I made the changes for you, @Ghat0tkach

**Comment by Ghat0tkach** [comment]
> I made the changes for you, @Ghat0tkach 

Thanks a lot @leecalcote , Much appreciated 🙌

**Pull request merged**
