### PR TITLE
Fixes the issue in Docs Search: Unwanted display of search result on separate line from bullet point in safari browser(7402)

### LINKED ISSUE #7402: [Docs] Search: Unwanted display of search result on separate line from bullet point
@VIKAS0264, thanks for this.

On a related note, we seem to have another bug present here: an unwanted line return:

Screenshot 2023-03-26 at 9 52 50 PM

I see this behavior in Safari.

_Originally posted by @leecalcote in https://github.com/meshery/meshery/issues/7347#issuecomment-1484405105_

### PR DESCRIPTION
**Pull request by phanithinks**
**Notes for Reviewers**

This PR fixes #7402

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 7ea41849d114a7e22201708b9a273bf47f1639ba at: https://64fb096b27d5636d6542c9e5--meshery-docs-preview.netlify.app

**Comment by leecalcote** [comment]
@phanithinks thanks. Will you run the `git` commands as instructed here - https://github.com/meshery/meshery/pull/8690/checks?check_run_id=16614759989

**Review by leecalcote — APPROVED** [review]
Behavior confirmed. This change works well, @phanithinks 👍

**Comment by phanithinks** [comment]
@leecalcote  Thanks for providing instruction. Updated the branch

**Comment by l5io** [comment]
🚀 Preview for commit f6c3aff7157bf3797cfff024d53bcc5a5f34daff at: https://64fe9635130f941f10f25ec3--meshery-docs-preview.netlify.app

**Pull request merged**
