### PR TITLE
[Docs] Show only english search results

### LINKED ISSUE #6120: [Docs] Search should show results only in English
#### Current State
Currently, the search show results in both English and Spanish.

#### Desired State
The search results should be shown in English only.

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by mharshita**
**Description**

This PR fixes #6120 

**Notes for Reviewers**
Search now shows results only in English.

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 5379dfdf5d3fa0335bce3f1f203080d22bbca9ce at: https://630f0fdc05d1da64f788a58c--meshery-docs-preview.netlify.app

**Comment by leecalcote** [comment]
Thanks, @mharshita 👏

**Review by asubedy — CHANGES_REQUESTED** [review]
@mharshita this approach does not seem to work. It not only hides Spanish results but also hides other English results. for eg. these are the images when searched the same query on  your PR and on master.
image
image

**Comment by l5io** [comment]
🚀 Preview for commit 57bfaf9699d4e11b68ca7a0f7d4b76b32a8b2f3c at: https://63118a0285a36e3d9688f044--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit a512a0c8be12454dd050f6872f629a922daf5ee2 at: https://63129dc7063a0929c4a88cfd--meshery-docs-preview.netlify.app

**Comment by Nikhil-Ladha** [comment]
The issue is happening because a lot of files don't have the `language` frontmatter specified. A possible solution for this is to add an or condition like `!post.language or post.language=="en"` (not sure about the syntax)

**Comment by l5io** [comment]
🚀 Preview for commit 9082cfac418cdfe32ab636f22b05f5d0709c5c25 at: https://6317467d5a36870291e7289f--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 932a2ccf28d73dcfd33ccdecadf053a2ad5b3368 at: https://63174a77dbaf530772960ee4--meshery-docs-preview.netlify.app

**Comment by leecalcote** [comment]
@mharshita ready for another round of review?

**Comment by leecalcote** [comment]
@mharshita please execute these `git` commands - https://github.com/meshery/meshery/pull/6133/checks?check_run_id=8207781128

**Comment by leecalcote** [comment]
@mharshita please execute these git commands - https://github.com/meshery/meshery/pull/6133/checks?check_run_id=8207781128

**Pull request closed without merging**
