### PR TITLE
docs: Updated CLI command reference

### LINKED ISSUE #10806: [Docs] Update Meshery Docs for Consolidated Command Structure
### Current State
Meshery Docs must update post consolidation of `app` command into `pattern` command and subcommand. 

Screenshot from 2024-04-29 12-28-33

### Desired State
Include remaining `pattern` subcommands in CLI reference; remove relevant section.

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by singh1203**
**Notes for Reviewers**

This PR fixes #10806 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 90ced285cc483354a558142b079ed2eef17f99f9 at: https://662f4b146f5eac77d788b976--meshery-docs-preview.netlify.app

**Comment by iArchitSharma** [comment]
@singh1203 Adding the item to agenda for website call on Monday: https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit

**Comment by l5io** [comment]
🚀 Preview for commit 994d705d1e8842a74e5038cadeb6e4284d0baa4f at: https://662fccc651b60b49213a7dec--meshery-docs-preview.netlify.app

**Comment by leecalcote** [comment]
@alphaX86 look good?

**Review by alphaX86 — APPROVED** [review]
LGTM!

**Comment by alphaX86** [comment]
Thanks @singh1203 we're good to go

**Comment by singh1203** [comment]
> Thanks @singh1203 we're good to go

Thank you for merging promptly. @alphaX86 & @iArchitSharma

**Pull request merged**
