### PR TITLE
One golangci-lint workflow

### PR DESCRIPTION
**Pull request by acald-creator**
Signed-off-by: Antonette Caldwell <pullmana8@gmail.com>

**Description**

This PR fixes https://github.com/meshery/meshery/issues/5993

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

For the purpose of this PR is to separate the `golangci-lint` workflow from the existing workflows, so that we can obtain the necessary reports from linting issues immediately, instead of stopping the existing workflow.

There will still need to be another PR to update the linting settings, which I'm currently working on.

### CODE REVIEW

**Comment by leecalcote** [comment]
Is segregating golang linting into its own workflow ideal? It would be good to address this in context of the spreadsheet that you're updating, @acald-creator (?) - https://docs.google.com/spreadsheets/d/13Ir4gfaKoAX9r8qYjAFFl_U9ntke4X5ndREY1T7bnVs/edit#gid=1214153102

**Comment by leecalcote** [comment]
Perhaps, a separate workflow that checks out the repo (again) and sets up golang (again) is less efficient?

**Comment by leecalcote** [comment]
@paularah @segunjkf

**Comment by leecalcote** [comment]
@acald-creator if we reuse the same linting workflow across the other workflows, separating it out might make sense. The build workflow is not referencing the golangci lint workflow here, though.

**Review by Revolyssup — APPROVED** [review]

**Pull request merged**
