### PR TITLE
[mesheryctl] Remove the release executable file

### PR DESCRIPTION
**Pull request by kushthedude**

### CODE REVIEW

**Comment by leecalcote** [comment]
Build checks failing. Re-running jobs.

**Comment by kushthedude** [comment]
Error in taskq version. They told me its fixed bow

**Comment by kushthedude** [comment]
> Build checks failing. Re-running jobs.

Build should be fixed now 🤞

**Comment by leecalcote** [comment]
Oh, very good, @kushthedude. Re-running build checks on this PR now...

**Comment by leecalcote** [comment]
No luck, yet, @kushthedude

**Comment by kushthedude** [comment]
🤞

**Comment by kushthedude** [comment]
🤞

**Comment by kushthedude** [comment]
> No luck, yet, @kushthedude

Pulling the master did the job, will tell those guys to make a new release. It is good to go @leecalcote

**Pull request merged**
