### PR TITLE
MesherySettingsPerformanceComponent.js converted class-based component into functional componen

### LINKED ISSUE #8813: [UI] Convert `MesherySettingsPerformanceComponent` class-based component to functional component
### Current Behavior
`MesherySettingsPerformanceComponent` is a  class-based component

### Desired Behavior
`MesherySettingsPerformanceComponent` should be a functional component

### Implementation
Convert all the Class-based components to new updated functional components. It is important here to convert a class-based component to a functional component you may need to convert some functions as well. Check if the function is used in other components or not.

Also, make sure to use the hooks while converting them. For example, you need to covert withNotify with useNotification, useRouter hook. Please check if a hook for functional components is available and use that.

Here is a quick blog that will help you get started with : [Link](https://www.digitalocean.com/community/tutorials/five-ways-to-convert-react-class-components-to-functional-components-with-react-hooks)

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by csengineer1990**
Converted MesherySettingsPerformanceComponent.js class-based component into a functional component

Notes for Reviewers
Please check the above changes if I did anything wrong please let me know.

This PR fixes #8813 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 91ccb25bed55fe5a1b0f57f55df7a107345a92f8 at: https://651ab424451fdb0f0347264d--meshery-docs-preview.netlify.app

**Comment by saurabh100ni** [comment]
Let's discuss this on the Meshery dev call tomorrow,
Please add this as your agenda item in Docs: https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit

**Comment by l5io** [comment]
🚀 Preview for commit 8571e8431d238a808b5d7734f2c3f86dfbf038fd at: https://651d529e2b96d64ffe9f3c82--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 677eb1ddf7670346ff29eea273c559d614e9f2c8 at: https://651d5a884049695df1a5921a--meshery-docs-preview.netlify.app

**Comment by csengineer1990** [comment]
Hi Sir, Could you please review my PR and let me know if there are any issues? I'm eager to earn the Meshery Hacktoberfest badge, and your guidance will be greatly appreciated.

**Comment by l5io** [comment]
🚀 Preview for commit a52defbc86158f506fa26220a350bf30a60b3f9b at: https://65390662813b09068d3afd20--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 3e61e5678a90ec866df4fd6294e85ec12600e344 at: https://65390785e54a6c09085743eb--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 1a70bcb4b72e2b8db5ffd9249bbbdbb264519a5e at: https://653be1311a881c2d3684a694--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 27431bbb857921ba975d08cca31df6dd79ac6392 at: https://653e4d26476a61684364a3c5--meshery-docs-preview.netlify.app

**Comment by csengineer1990** [comment]
> @csengineer1990 please revert unnecessary changes in this PR, I think this will also solve merge conflicts
> 
> It's hard to review your changes with unnecessary ones, pings us when you done with that let's get this merge


Sir, I apologize for the unnecessary changes in the pull request. It wasn't intentional, and I have now removed those changes and resolved the conflict. I don't know how these unnecessary changes occurred in the repository.

I appreciate your patience during this process. If the same issues persist, please guide me on the next steps to ensure the repository is synchronized without affecting the current pull request.  what should I do? and how can I solve with affecting the pull request? I would appreciate your help.

**Comment by l5io** [comment]
🚀 Preview for commit 6bb98203da00b3eaade0c672366b53db6b0be2e4 at: https://65447a075636ae428effd0e9--meshery-docs-preview.netlify.app

**Comment by csengineer1990** [comment]
Hi Sir, I often encounter issues with merging and updating branches, which can lead to unintentional, unnecessary changes in my main pull requests. This complicates the process of reviewing the changes. What do you think I should do to solve this, sir Please help me.

**Pull request closed without merging**
