### PR TITLE
added kuma service mesh

### PR DESCRIPTION
**Pull request by kumarabd**
Signed-off-by: kumarabd <abishekkumar92@gmail.com>

**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by anirudhjain75 — APPROVED** [review]
Seems fine to me 👍

**Review by kushthedude — CHANGES_REQUESTED** [review]
I guess you forgot to commit the icons

**Comment by leecalcote** [comment]
A perfect time to complete the documentation issue on this.

**Comment by leecalcote** [comment]
Here's the associated documentation issue to be addressed - https://github.com/layer5io/meshery/issues/1444

**Comment by leecalcote** [comment]
Adding `pr/dependencies` label. @kumarabd, this PR https://github.com/layer5io/meshery-kuma/pull/71 must be merged first. A release of Meshery Adapter for Kuma must be completed first.

**Pull request merged**
