### PR TITLE
The search bar is now not colliding with the Navbar from 768px to 995px 

### LINKED ISSUE #6512: The search bar is colliding with the Navbar from 768px to 988px
#### Current Behavior

The search bar is colliding with the Navbar from 768px to 988px

#### Expected Behavior

Give a margin to the Search bar (From the top)

#### Screenshots/Logs

image

#### Environment

- **Host OS:** Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by UtkarshMishra12**
Signed-off-by: Utkarsh Mishra <nasautkarsh@gmail.com>

**Notes for Reviewers**
The search bar is now not colliding with the Navbar from 768px to 995px 

This PR fixes #6512 

Before:
image

Now:

https://user-images.githubusercontent.com/67385503/205332114-9340d84b-86f0-4d0b-8683-620f2f51b74e.mp4

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 8ef117bbb2ecf3ecbaa74a63be2ddda397d97939 at: https://638a2053ff67563a54c3c4dc--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 1c3008b8f28a0a79babd23f1ce6112757afd0cea at: https://638a23eeb0317738230ac468--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 0f7852b9203ed2e739fb53bc89e65cb47cbf57ae at: https://638a570df62a076a7cdf948f--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit ad182c4e5f618ec7d8407927e608992f5dd1efac at: https://638a63dd58568c00a40440b2--meshery-docs-preview.netlify.app

**Review by leecalcote — APPROVED** [review]
Looks great. Thanks, @UtkarshMishra12 👍

**Pull request merged**
