### PR TITLE
set cursor to pointer

### LINKED ISSUE #5006: [UI] Apps, Filters, Patterns: Set cursor to pointer on row hover
#### Current Behavior
For Applications, Patterns, and Filters tables, the mouse cursor should be set to pointer on hover.

Each table row is clickable.

#### Desired Behavior
```
cursor: pointer;
```

#### Screenshots/Logs
Screen Shot 2022-01-27 at 2 45 27 PM

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by Sunnyio**
Signed-off-by: Sunny Kumar <sunny514173@gmail.com>

**Description**

This PR fixes #5006 

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by Chadha93 — DISMISSED** [review]
LGTM 🏅

**Review by warunicorn19 — CHANGES_REQUESTED** [review]
@Sunnyio could you please revert the change for filters for now, since the cell is not clickable for filters right now.

**Comment by Sunnyio** [comment]
Sure @warunicorn19, doing it now.

**Review by warunicorn19 — APPROVED** [review]
LGTM, Thank you @Sunnyio

**Pull request merged**
