### PR TITLE
Fix incorrect link in the docs

### LINKED ISSUE #7076: [Docs] Expired link in the docs "guides/mesheryctl/authenticate-with-meshery-via-cli"
#### Current State

When we go on the following [page](https://docs.meshery.io/guides/mesheryctl/authenticate-with-meshery-via-cli) and click on "provider":

image

The result is the following page:
image

Don't know if it's a docs related issue or a UI related one

#### Desired State

Should be redirected to the correct page

#### Environment

- Browser: Chrome
- Host OS: Windows
---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by pratik9315**
Signed-off-by: pratik2315 <pratikhaldankar360@gmail.com>

**Notes for Reviewers**

This PR fixes #7076 

Fix the incorrect link in the docs

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit adcdd5056095ef05d9eb679a781d549fd5f910da at: https://63ea5b8558aa1f317f678461--meshery-docs-preview.netlify.app

**Comment by Chadha93** [comment]
@pratik2315  Let's discuss this on the Meshery Dev call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#) if you would. :)

**Comment by pratik2315** [comment]
> @pratik2315 Let's discuss this on the Meshery Dev call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#) if you would. :)

Hey there @Chadha93 ! I am unable to add the name as the document is view only. Also to confirm, the meeting will be held at 9 am Central tomorrow right?

**Review by leecalcote — APPROVED** [review]
Good! Thanks, @pratik2315

**Pull request merged**
