### PR TITLE
[cypress] migrate to cypress version 12

### PR DESCRIPTION
**Pull request by Abhishek-kumar09**
Signed-off-by: Abhishek kr <abhimait1909@gmail.com>
Migrated to cypress version 10, locally its behaving fine, lets wait for the response of the CI.

If we have gone through it, we might require to migrate the meshery-extension-packages to cypress v10 also.

https://github.com/cypress-io/cypress/discussions/22128
**Notes for Reviewers**

This PR fixes #

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
🤞

**Comment by Abhishek-kumar09** [comment]
integration test passes, problems with e2e only. Perhaps this happening due to proxy problem with electron, changed the config to use chrome. 🤞

**Comment by Abhishek-kumar09** [comment]
There has been no intended result being seen even after updating to latest cypress version, which the cypress team suggests in the discussion: https://github.com/cypress-io/cypress/discussions/22128
It still needs some more reasearch.

**Comment by leecalcote** [comment]
@MarioArriaga92 no luck here, right? What's our next step?

Is this topic on the agenda for today's Meshery CI meeting, @Revolyssup? This should be the highest priority item. Failing builds should be priority #1.

**Comment by MarioArriaga92** [comment]
@Abhishek-kumar09 @Revolyssup @leecalcote is it possible we enable collection of meshery server logs during execution of e2e tests? It'd be helpful to see if there's any useful error message emitted during these 500's being thrown while the test tries to set the "none" provider.

Another option would be to try to reproduce the issue locally I can try that

**Comment by Revolyssup** [comment]
> @Abhishek-kumar09 @Revolyssup @leecalcote is it possible we enable collection of meshery server logs during execution of e2e tests? It'd be helpful to see if there's any useful error message emitted during these 500's being thrown while the test tries to set the "none" provider.
> 
> Another option would be to try to reproduce the issue locally I can try that

@MarioArriaga92 Let's discuss this in today's build and release call.

**Comment by leecalcote** [comment]
@Revolyssup you have removed sensitive tokens from being logged to stdout when DEBUG mode is on, right?

**Comment by leecalcote** [comment]
Oh, great call. @Revolyssup, some discussion around this is ideal. 👍

**Comment by MarioArriaga92** [comment]
> 

@Abhishek-kumar09 I see you already added the console log, great! Hoping subsequent CI run logs show details of what happened, in case the output is just [Error err] I suggest adding wrapping err with `JSON.stringify(err)`

**Comment by Abhishek-kumar09** [comment]
updates: Now ui e2e test passes, and integration tests are failing.

**Comment by leecalcote** [comment]
> updates: Now ui e2e test passes, and integration tests are failing.

I _think_ (hope) this means progress.

**Comment by Abhishek-kumar09** [comment]
> I think (hope) this means progress.

Definately, we're out of the issue now. Since we had not updated the code to the changes the tests are failing. I'll make the changes after the call.

**Comment by leecalcote** [comment]
Thank you.

**Comment by Abhishek-kumar09** [comment]
All tests integration as well as e2e are passing now.
Additonal Notes:
- There was a problem with integration test due to which it keeps on running, see the screenshot below from the last run that the tests have been running for more than hour with no results. That behaviour is also fixed.
Screenshot 2022-12-28 at 2 39 30 AM

- Also, meshery-istio is taking longer than expected to start, probably due to no. of components to register. So, I have modified the yaml to start the istio and consul adapter in beginning only that gives them enough time to register components to be visible in UI.

- Due to lack of cypress-cloud dashboard, I have started uploading the cypress screenshots and videos as artifacts to get the reason of failure if any.

**Comment by Abhishek-kumar09** [comment]
Merging the PR. @meshery/meshery-ui-contributors and @meshery/meshery-ui-maintainers needs to rebase their branch in order to get the tests passing.

**Pull request merged**
