### PR TITLE
[Cypress] Fix Failing e2e and integration tests in Meshery

### PR DESCRIPTION
**Pull request by Abhishek-kumar09**
**Description**

This PR fixes #
1. Fix lifecycle tests
2. Fix settings page tests
3. Add tests for pining istio from settings page
4. delete integratiuon tests for discover cluster, since its removed

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
@Abhishek-kumar09 are these failures from the new test or the old test versions?

**Comment by Abhishek-kumar09** [comment]
To my surprise the integration tests are running for so long....

**Comment by Abhishek-kumar09** [comment]
All the cypress e2e and integration tests are passing, I have tested locally. the e2e results are visible and passing in ci.

**Comment by Abhishek-kumar09** [comment]
inrtegration tests passes

**Comment by leecalcote** [comment]
Yay!

**Pull request merged**
