### PR TITLE
Solved Issue 6754 for Designs Page

### LINKED ISSUE #6754: [UI] Selected Items disappear in Table view, Even when deletion denied in modal
#### Current Behavior

Currently at /configuration/filters, /configuration/applications, /configuration/patterns. On clicking the delete icon all the selected items get disappeared. Even when NO is selected in the delete modal.

https://user-images.githubusercontent.com/103871275/208772597-e638472e-c9f0-47f7-9fb4-1ecbb1d6288e.mp4

#### Desired Behavior

Items should appear after NO is selected in the delete modal.

#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by hs05june**
**Notes for Reviewers**

This PR fixes #6754 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.
 

https://user-images.githubusercontent.com/103871275/208979853-1cb9e172-a115-4912-904f-7c0003009710.mp4

### CODE REVIEW

**Comment by leecalcote** [comment]
@hs05june, thanks for taking a screen recording. Regarding your note about it.... https://twitter.com/lcalcote/status/1451200314124632076?s=20&t=dzHwSg3VR9gCTVIy8ZBk8A

**Comment by leecalcote** [comment]
The behavior demonstrated in the video is ideal. 👏

**Comment by hs05june** [comment]
@eeshaanSA @UtkarshMishra12 @GaganpreetKaurKalsi Kindly review this PR.

**Review by leecalcote — APPROVED** [review]
Looks good to me.

**Comment by leecalcote** [comment]
Very cool, @hs05june! 🎈

**Pull request merged**
