### PR TITLE
fixed mesh deploy logs/signoff

### LINKED ISSUE #11320: [mesheryctl] `adapter deploy` and `adapter validate` logs
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

### Current Behavior

When we run `mesheryctl mesh deploy linkered` logs `Adapter for required mesh not found` but it says `deployed successfully`.
### Screenshots/Logs

```
./mesheryctl mesh deploy linkerd
Adapter for required mesh not found
Verifying prerequisites...
Adapter for required mesh not found

LINKERD infrastructure deployed successfully
```
### Environment

- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- 📺 [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- ⌨️ [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- ⌨️ [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by rahulrana701**
**Notes for Reviewers**

This PR fixes #11320

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by Jougan-0** [comment]
@rahulrana701 why return err and why was nil returned before. If we are logging it already then what's the point of returning.

**Comment by rahulrana701** [comment]
> @rahulrana701 why return err and why was nil returned before. If we are logging it already then what's the point of returning.

@Jougan-0 
Returning nil didn’t work because it allowed the command to continue executing even after encountering an error, which could lead to misleading results. Returning the error was important to stop further execution and ensure proper error handling. If we log and return the error together, it results in the same error message being logged twice, which seems unnecessary

**Comment by vishalvivekm** [comment]
@rahulrana701 Let's discuss this on the Meshery dev meeting starting 7:30 PM IST today. Adding it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit?usp=drivesdk)

**Comment by Jougan-0** [comment]
@rahulrana701 
Thank you for the explanation. I just wanted to mention that while you may have already checked this, not every error that you return necessarily breaks the code. It would be helpful if you could double-check.
The ideal thing is that the command run successfully so if you would look into why this is not working properly.

**Comment by rahulrana701** [comment]
Hi @Jougan-0, the issue we're facing is that when we run the command mesheryctl mesh deploy, we always encounter the error "Adapter for required mesh not found." After further investigation, I discovered that the response we receive from the server does not contain any adapters because the server-side adapters are not being registered properly. Additionally, we cannot test the changes made on the server side with these commands

**Comment by Ashparshp** [comment]
@rahulrana701 let's discuss this PR during the Meshery dev meeting call, if you would. Please add it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit?usp=drivesdk).

**Comment by MUzairS15** [comment]
What's the status of this PR? @rahulrana701

**Pull request closed without merging**
