### PR TITLE
ignore

### PR DESCRIPTION
**Pull request by kushthedude**
**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by kushthedude** [comment]
image

**Comment by kushthedude** [comment]
smi-conformance-with-meshery

**Comment by leecalcote** [comment]
I got so excited when I saw these screenshots.

**Comment by kushthedude** [comment]
I had to upload them to get a github preview link.

**Comment by leecalcote** [comment]
There's no question: you're a tease.

😄

**Pull request closed without merging**
