### PR TITLE
Added-icon-for-postgres-autoscaler

### PR DESCRIPTION
**Pull request by Ayush9026**
**Icon for Postgres Autoscaler**

This PR fixes #https://github.com/meshery/meshery/issues/8750

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Ckbhatia** [comment]
LGTM

**Comment by saurabh100ni** [comment]
Thanks for raising the PR, let's Discuss this in the Meshery Development Call today,
Please add this as an agenda in the Doc  : [Doc](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit)

**Comment by ritiksaxena124** [comment]
@Ayush9026 thanks for taking this up but we need icon for Postgres Autoscaler not of Postgres. The icon that you added is of Postgres. 

So when you will be designing another icon, go to the [playground](https://playground.meshery.io/extension/meshmap) -> search for the component you are trying to design icon for and check whether the icon that you are designing is already present for another component or not if not then you can make a PR

**Comment by leecalcote** [comment]
Discussed on the Meshery Dev meeting this week.

**Pull request closed without merging**
