### PR TITLE
Fix relative path check in config for token

### LINKED ISSUE #5570: [mesheryctl] Token location is hardcoded.
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior

```
contexts:
  local:
    endpoint: http://localhost:9081
    token: Default
    platform: kubernetes
    components: []
    channel: stable
    version: latest
current-context: local
tokens:
- location: ~/Downloads/test-2.json
  name: Default
```

`failed to write the token to the filesystem: open /Users/shabana/.meshery/~/Downloads/test-2.json: no such file or directory`
#### Desired Behavior

Token should be generated at path provided in config.
#### Environment

- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor Resources
- [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by alphaX86**
Signed-off-by: Aadhitya A <aadhitya864@gmail.com>

**Description**

This PR fixes #5570 

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by MUzairS15 — APPROVED** [review]
LGTM
It would be great if we could also support the environment variable.
eg: if the path is set as `${token}/mesheryctl-login.json`
WDYT

**Comment by alphaX86** [comment]
> LGTM It would be great if we could also support the environment variable. eg: if the path is set as `${token}/mesheryctl-login.json` WDYT

I feel it can be done... I'll check and introduce a change if I found a method to do

**Comment by alphaX86** [comment]
I'm thinking if we can use Viper to fetch the key from `.env` file but do we need such? WDYT @MUzairS15 

// cc: @meshery/mesheryctl-maintainers

**Comment by alphaX86** [comment]
Hmm... IG we can discuss this separately with other folks for review

**Review by leecalcote — APPROVED** [review]

**Pull request merged**
