### PR TITLE
fix: Result table not rendering due to undefined props

### LINKED ISSUE #868: [UI] TypeError: null is not an object (evaluating 'tableState.announceText.split')
**Description**

When I access to routers `/results` and will get the error

**Expected Behavior**

 The UI work well
**Screenshots**

Screen Shot 2020-04-20 at 11 28 13 AM

Screen Shot 2020-04-20 at 11 25 57 AM

**Environment:**
 - OS: [e.g. Ubuntu]
    * MacOS
 - Browser: [e.g. Chrome, Safari]
   * Safari
 - Version: [e.g. 22]
   * Version 13.0.2 (15608.2.30.1.1)
 - Device: [e.g. laptop, iPhone 8]

---
[Optional] **To Reproduce**

[Optional] **Additional Context**

**The Meshery was used by me is the version which includes the PR  #856, please to reproduce the behavior with the branch which includes the PR**

### PR DESCRIPTION
**Pull request by kushthedude**
Fixes #868 

- Tested Sorting & Rendering, both works quite well!

### CODE REVIEW

**Comment by kushthedude** [comment]
@leecalcote Please take a look here !

**Comment by leecalcote** [comment]
💪 @kushthedude

**Comment by leecalcote** [comment]
@kushthedude I'm having difficultly:

```
INFO[0255] retrieved user: {layer5   http://pbs.twimg.com/profile_images/1190059013544779776/mxxU_z_S_normal.jpg}
INFO[0255] retrieved user: {   }
17:21:20 http: panic serving [::1]:60797: runtime error: invalid memory address or nil pointer dereference
goroutine 1224 [running]:
net/http.(*conn).serve.func1(0xc0003221e0)
	/usr/local/Cellar/go/1.13.7/libexec/src/net/http/server.go:1767 +0x139
panic(0x5209200, 0x6190330)
	/usr/local/Cellar/go/1.13.7/libexec/src/runtime/panic.go:679 +0x1b2
github.com/layer5io/meshery/handlers.(*Handler).addAdapter(0xc0000b5330, 0x5665180, 0xc0008775c0, 0x634ce50, 0x0, 0x0, 0xc00055e600, 0xc00004200d, 0x1c, 0x0, ...)
	/Users/lee/code/meshery/handlers/mesh_ops_handlers.go:113 +0xf0
github.com/layer5io/meshery/handlers.(*Handler).SessionSyncHandler(0xc0000b5330, 0x5660180, 0xc000838ee0, 0xc000247500, 0xc00067ec80, 0xc00055e600, 0xc000802440, 0x568e380, 0xc000114070)
	/Users/lee/code/meshery/handlers/session_sync_handler.go:28 +0x185
github.com/layer5io/meshery/handlers.(*Handler).SessionInjectorMiddleware.func1(0x5660180, 0xc000838ee0, 0xc000247500)
	/Users/lee/code/meshery/handlers/middlewares.go:110 +0x27b
net/http.HandlerFunc.ServeHTTP(0xc0000b53c0, 0x5660180, 0xc000838ee0, 0xc000247500)
	/usr/local/Cellar/go/1.13.7/libexec/src/net/http/server.go:2007 +0x44
github.com/layer5io/meshery/handlers.(*Handler).AuthMiddleware.func1(0x5660180, 0xc000838ee0, 0xc000247500)
	/Users/lee/code/meshery/handlers/middlewares.go:64 +0x19b
net/http.HandlerFunc.ServeHTTP(0xc000258dc0, 0x5660180, 0xc000838ee0, 0xc000247500)
	/usr/local/Cellar/go/1.13.7/libexec/src/net/http/server.go:2007 +0x44
github.com/layer5io/meshery/handlers.(*Handler).ProviderMiddleware.func1(0x5660180, 0xc000838ee0, 0xc0004c2200)
	/Users/lee/code/meshery/handlers/middlewares.go:34 +0x1d5
net/http.HandlerFunc.ServeHTTP(0xc000258de0, 0x5660180, 0xc000838ee0, 0xc0004c2200)
	/usr/local/Cellar/go/1.13.7/libexec/src/net/http/server.go:2007 +0x44
net/http.(*ServeMux).ServeHTTP(0xc00025f940, 0x5660180, 0xc000838ee0, 0xc0004c2200)
	/usr/local/Cellar/go/1.13.7/libexec/src/net/http/server.go:2387 +0x1bd
net/http.serverHandler.ServeHTTP(0xc0002c62a0, 0x5660180, 0xc000838ee0, 0xc0004c2200)
	/usr/local/Cellar/go/1.13.7/libexec/src/net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc0003221e0, 0x56650c0, 0xc0008d01c0)
	/usr/local/Cellar/go/1.13.7/libexec/src/net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.13.7/libexec/src/net/http/server.go:2928 +0x384
INFO[0267] retrieved user: {layer5   http://pbs.twimg.com/profile_images/1190059013544779776/mxxU_z_S_normal.jpg}
INFO[0267] attempting to fetch results from cloud
DEBU[0267] constructed results url: https://meshery.layer5.io/results?order=asc&page=0&page_size=10
ERRO[0267] error while fetching results: unable to get meshery results
```

**Comment by kushthedude** [comment]
I checked the pagination param on my local and they were working fine.
I will take a look at it again tomorrow and let you know.

**Comment by kushthedude** [comment]
Blocked until #891 is solved

**Pull request closed without merging**
