### PR TITLE
Kuma dark mode logo resolve

### LINKED ISSUE #7981: [Docs]Dark mode logo issue for Meshery Adapter of Kuma
#### Current State
logo of Meshery Adapter for Kuma not visiable in dark mode at https://docs.meshery.io/
logo of meshery adapter for kuma not visiable in dark mode at /service-meshes/adapters/kuma/

#### Desired State
logo should be visiable

image
image

image
image

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by lanzkrish**
**Notes for Reviewers**

This PR fixes #7981 

261736198-ee6974d2-27d9-4bda-9095-f1f0ca468c8e
261736034-5e6e7158-bdd6-4f2c-b132-99d76fd4b747

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 50c461742299eb0781dd41db95ec0a373df10eae at: https://64e95d01ee3f7a67aeb700cd--meshery-docs-preview.netlify.app

**Comment by Ghat0tkach** [comment]
hii @lanzkrish 
Let's discuss it on the websites call.
Please add this as an agenda item in the meeting minutes, if you would :)
https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima

**Comment by leecalcote** [comment]
@lanzkrish will you refactor this to approach this is a universal way across all adapters?

**Review by leecalcote — CHANGES_REQUESTED** [review]
Revision in approach needed.

**Comment by lanzkrish** [comment]
> @lanzkrish will you refactor this to approach this is a universal way across all adapters?

ok, I will make the changes

**Comment by l5io** [comment]
🚀 Preview for commit 20bef3f4b77bc8c9435c9b5d392f4d1945e2230d at: https://64eebab3681e2e276f8c0478--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 5647ffb036193f1e63aee0f09c8594e05e2bfd03 at: https://64eff35f74548a147585fbd9--meshery-docs-preview.netlify.app

**Review by leecalcote — APPROVED** [review]
yay! @lanzkrish. Good work. 👍

**Pull request merged**
