### PR TITLE
Update ROADMAP.md

### PR DESCRIPTION
**Pull request by vedant-kakde**
Signed-off-by: Vedant Kakde <69970950+vedant-kakde@users.noreply.github.com>

**Description**
Update roadmap.md

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by Abhishek-kumar09 — APPROVED** [review]
LGTM, Good luck with your first contribution to Meshery. It's fun.

**Review by warunicorn19 — APPROVED** [review]
LGTM🎉, Thanks @vedant-kakde.

**Review by leecalcote — APPROVED** [review]
Looking good, @vedant-kakde

**Comment by leecalcote** [comment]
Yay, @vedant-kakde! 🎈

**Pull request merged**
