### PR TITLE
Changed server request for Publishing Catalog Content

### LINKED ISSUE #7404: [Server] Changing server request for Publishing Catalog Content
#### Current Behavior
Currently, the server sends a `200 OK` success status response code when a publish request is submitted.

#### Desired Behavior

Change server to send 202 `Accepted` when a publish request is submitted.

#### Mockups

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by Player256**
**Notes for Reviewers**

This PR fixes #7404 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by suhail34 — CHANGES_REQUESTED** [review]
Hey it wasn't just the docs update we need to return response status of Accepted(202) too from the server

**Comment by Player256** [comment]
> Hey it wasn't just the docs update we need to return response status of Accepted(202) too from the server

Should I just send this `rw.WriteHeader(http.StatusAccepted)` in the handler func

**Comment by suhail34** [comment]
yes wherever we make a publish request in filter and patterns both

**Comment by Player256** [comment]
Made the changes

**Comment by leecalcote** [comment]
Lack of sign-off on your commit(s). See the first comment on your PR for instructions for [making signing an implicit activity while performing a commit](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin).

**Comment by leecalcote** [comment]
For the commits within this poll request, follow and execute the git commands here - https://github.com/meshery/meshery/pull/8197/checks?check_run_id=15108254064

**Comment by leecalcote** [comment]
@MUzairS15 is this approach in following with the desired standard approach for Meshery Server?

**Review by suhail34 — CHANGES_REQUESTED** [review]
Hey @Player256 do see the api endpoints so you will have a better were you have to make the changes
https://github.com/meshery/meshery/blob/master/server/router/server.go

**Review by MUzairS15 — APPROVED** [review]

**Comment by leecalcote** [comment]
Yay, @Player256 🎈

**Pull request merged**
