### PR TITLE
[mesheryctl]add subcommands for system config command

### LINKED ISSUE #3758: [mesheryctl]`mesheryctl system config` throws an error when config type is not specified.
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior
`mesheryctl system config` command throws an error when the configuration type keyword is not provided.

#### Desired Behavior
`mesheryctl system config` command should enumerate the options available(minkube/eks/aks/gke).
Remove the error message as well and throw help text.

#### Screenshots/Logs
Screen Shot 2021-08-03 at 10 26 27 PM

#### Environment

- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

#### Mockups

---

#### Contributor Resources

- [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by hexxdump**
**Description**
`mesheryctl system config` command throws an error when config type of either aks/eks/gke/minikube is not specified.
changed the `mesheryctl system config` to have subcommands for each config type.
Also removed the dependency on users providing auth token as input, these subcommands try to fetch the auth token from constants.GetCurrentAuthToken() if its not specified on the CLI

This PR fixes #3758 #3282

**Notes for Reviewers**
Tested the refactored peices, e2e testing has not been performed on all the platforms.

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by navendu-pottekkat** [comment]
@hexxdump There is a lint error.

**Review by navendu-pottekkat — COMMENTED** [review]
Wouldn't adding each of the platforms as sub commands cause a lot of overhead?

When we support a new platform in the future, instead of adding a new case in a switch statement, we have to create a new command.

Also we would need to  ensure parity between all these subcommands and this can become a bigger task than it needs to be.

Instead of new subcommands, can we just show a custom error message showing the available platforms? It would provide the same UX as far as usability and documentation is our concern.

Am I missing any other detail on why subcommands are needed?

**Comment by hexxdump** [comment]
> Wouldn't adding each of the platforms as sub commands cause a lot of overhead?
> 
> When we support a new platform in the future, instead of adding a new case in a switch statement, we have to create a new command.
> 
> Also we would need to ensure parity between all these subcommands and this can become a bigger task than it needs to be.
> 
> Instead of new subcommands, can we just show a custom error message showing the available platforms? It would provide the same UX as far as usability and documentation is our concern.
> 
> Am I missing any other detail on why subcommands are needed?

@navendu-pottekkat, Going forward, it may not make sense to continue with a single config command and switch cases beneath it. We need to migrate to go-client SDKs for each platform. It would bloat each switch case and the parent configCmd's code(could become a big monolithic function).

**Comment by navendu-pottekkat** [comment]
Okay. Got it.

**Comment by leecalcote** [comment]
@alphaX86 it would be good reflect on how this changes the docs in the mesheryctl reference guide. @hexxdump, can we include a docs update in this PR? https://github.com/meshery/meshery/blob/master/docs/_data/mesheryctlcommands/cmds.yml

**Comment by alphaX86** [comment]
> @alphaX86 it would be good reflect on how this changes the docs in the mesheryctl reference guide. @hexxdump, can we include a docs update in this PR? https://github.com/meshery/meshery/blob/master/docs/_data/mesheryctlcommands/cmds.yml

Sounds good to me @leecalcote, let's wait for @hexxdump reply

**Comment by hexxdump** [comment]
> > @alphaX86 it would be good reflect on how this changes the docs in the mesheryctl reference guide. @hexxdump, can we include a docs update in this PR? https://github.com/meshery/meshery/blob/master/docs/_data/mesheryctlcommands/cmds.yml
> 
> Sounds good to me @leecalcote, let's wait for @hexxdump reply

Yes, cmds.yml should change accordingly. @alphaX86 will you be able to take care of this once this PR gets merged?

**Review by navendu-pottekkat — APPROVED** [review]
Thank you @hexxdump 

@alphaX86 Could you update the docs?

**Review by Shreyas220 — COMMENTED** [review]
@navendu-pottekkat I think @hexxdump is still working on issue 3282
image
I am still getting this for the perf command

**Comment by piyushsingariya** [comment]
> @navendu-pottekkat I think @hexxdump is still working on issue 3282
> image
> I am still getting this for the perf command

You gotta login first, with `mesheryctl system login`

**Comment by navendu-pottekkat** [comment]
@hexxdump Are you addressing any other concerns in this PR? Aren't we ready to merge this?

**Comment by hexxdump** [comment]
> @hexxdump Are you addressing any other concerns in this PR? Aren't we ready to merge this?

I am not addressing any other issues other than the ones mentioned in the description. I think we can merge this.

**Comment by navendu-pottekkat** [comment]
Thank you for clarifying. Merging this.

**Pull request merged**
