### PR TITLE
[mesheryctl] `--watch` flag for `mesh remove`

### LINKED ISSUE #3873: [mesheryctl] enhance `mesheryctl mesh remove`
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior
`mesheryctl mesh remove` doesn't use the event streamer utility and thus doesn't wait for remove operation event to complete.

#### Desired Behavior
The command should watch for events and wait till receiving an event signalling service mesh was removed successfully. If it is not removed, then the command should throw an error. 

#### Implementation
The implementation should be similar to the `mesheryctl mesh deploy` command. For reference, see
https://github.com/meshery/meshery/blob/c8dd33ae4f8756b0f69f06edb27e6cda5b904498/mesheryctl/internal/cli/root/mesh/deploy.go#L122-L173

#### Acceptance Tests
Exit with proper exit codes when operation fails.

#### Mockups

---

#### Contributor Resources

- ⌨️ [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by gr455**
**Description**

This PR fixes #3873

Implements a `--watch` flag for `mesh remove` that uses the EventStreamer utility to wait until the service mesh is removed.

Credits to @alphaX86 for #4261

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by gr455** [comment]
Continuing the discussion from #4261, it seems like the Event Streamer is not working properly? The events are only streamed to one of the connected clients and not all. This can explain the discrepency of it working sometimes. So if you close the UI and run the command, it should work no problem; but if the UI is open, usually the event is only streamed to the UI and not to mesheryctl.

**Comment by leecalcote** [comment]
@iamsdas available to review?

**Comment by gr455** [comment]
> Continuing the discussion from #4261, it seems like the Event Streamer is not working properly? The events are only streamed to one of the connected clients and not all. This can explain the discrepency of it working sometimes. So if you close the UI and run the command, it should work no problem; but if the UI is open, usually the event is only streamed to the UI and not to mesheryctl.
> 
> I am trying to look into what the problem with the event streamer maybe (if at all)
> 
> // cc @navendu-pottekkat @alphaX86

I dove into the code and found a little something. I maybe completely wrong so please correct me.

The flow [`listenForAdapterEvents()`](https://github.com/meshery/meshery/blob/master/handlers/events_streamer.go#L70) -> [`streamClient.Recv()`](https://github.com/meshery/meshery/blob/616452c074f06c4d188ec8616953a96f4dd61cba/handlers/events_streamer.go#L176) -> [`x.ClientStream.RecvMsg()`](https://github.com/meshery/meshery/blob/616452c074f06c4d188ec8616953a96f4dd61cba/meshes/meshops_grpc.pb.go#L110) is called for every client independently in different goroutines, the final call waits for the adapter to send message which ambiguously only sends to one of the waiting clients.

The [docs](https://pkg.go.dev/google.golang.org/grpc#ClientStream) for grpc also say that it is not safe to call Recv in different goroutines, which is what we are doing here.

The solution to this maybe to have a centralized Recv call and push the event data into channels for each client.

**Comment by gr455** [comment]
> @gr455 can you attach a recording here? Also linter is failing.

Hold on, this is not ready
There is an issue arising from a deeper problem with the event streamer. I will look into the event streamer the issue

**Comment by gr455** [comment]
There is more thought to be given on this. Let me close this for now.

**Pull request closed without merging**
