### PR TITLE
K8s context switcher ping test is broken #8617 - Fixed 

### LINKED ISSUE #8617: [UI] K8s context switcher ping test is broken.
### Current Behavior

When clicking `k8s` chip in context switcher no request is made to  perform connectivity/ping test.

https://github.com/meshery/meshery/assets/79860504/70ab0a3b-3d97-474b-968c-fdc6b06864f1

### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by ShailikaS**
**Notes for Reviewers**

This PR fixes #8617 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by sudhanshutech** [comment]
@ShailikaS please try to provide a proper description and heading for pr so that it could be understood by other contributors for review

**Review by sudhanshutech — COMMENTED** [review]
Screenshot or recording ?

**Comment by Ghat0tkach** [comment]
@ShailikaS 
Let's discuss this on Meshery Dev call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#) if you would. :)

**Comment by leecalcote** [comment]
@ShailikaS will you execute the `git` commands on this page in order to amend your commits with a signoff? https://github.com/meshery/meshery/pull/8667/checks?check_run_id=16540782711

**Comment by ShailikaS** [comment]
Hi @leecalcote no I didn't. 
is that for signoff I need to run these 2 commands:
1.In your local branch, run: git rebase HEAD~4 --signoff
2.Force push your changes to overwrite the branch: git push --force-with-lease origin bug/ShailikaS/8617

**Comment by ShailikaS** [comment]
Hi @sudhanshutech, 
Sure, thanks.
Yeah, it is working fine.
Here’s the new PR with proper details:
https://github.com/meshery/meshery/pull/8681

**Comment by Ckbhatia** [comment]
This PR should be closed as a recent duplicate PR got merged

**Pull request closed without merging**
