### PR TITLE
Patterns:  Add OAM patterns with RJSF form on every pattern column

### PR DESCRIPTION
**Pull request by Abhishek-kumar09**
**Description**
Add Oam Deployment pattern in configuration/pattern.
The RJFS form is using OAM schema.
The pattern can be duplicated from the previous deployed apps and other changes can be made on top of it to create a whole new pattern

**Notes For Reviewer**
The pattern is sharing some code that is also used by MeshMap interface, so have to check if the all the current functionalities in the meshMap interface remains unchanged

https://user-images.githubusercontent.com/48255244/129930566-3c3e0c29-8815-4984-8b42-5cabc532e80a.mp4

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Yes! 😍 

There are a few merge conflicts to attend to - https://github.com/meshery/meshery/pull/3925/conflicts - but this functionality is fantastic.

**Comment by warunicorn19** [comment]
Wow this by far the coolest thing Ive seen😳, awesome @Abhishek-kumar09

**Comment by sudo-NithishKarthik** [comment]
Great work here @Abhishek-kumar09 🎉 🙌🏽

**Comment by navendu-pottekkat** [comment]
💯

**Comment by sayantan1413** [comment]
Great work @Abhishek-kumar09 💯😍

**Comment by Abhishek-kumar09** [comment]
Thank You very much everyone :heart:

**Comment by leecalcote** [comment]
When I build this branch, I get:

```
/Users/lee/code/meshery/ui/components/MesheryPatterns.js
  592:10  error  'changedYaml' is assigned a value but never used     no-unused-vars
  592:23  error  'setChangedYaml' is assigned a value but never used  no-unused-vars
```

**Review by leecalcote — CHANGES_REQUESTED** [review]
Pease fix build lint errors.

**Comment by sudo-NithishKarthik** [comment]
@Abhishek-kumar09 , did pre-commit hooks run for you ?, if not, please run `npm install` so that it can be configured

**Review by sudo-NithishKarthik — APPROVED** [review]

**Pull request merged**
