### PR TITLE
fix v0.6 navbar dropdown and details marker in v0.6 meshery docs 

### LINKED ISSUE #9782: [Docs]fix meshery docs navbar v0.6
### Current State
Redirecting Links in the navbar of v0.6 are not working 

bug2

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by Aniket-76**
**Notes for Reviewers**

This PR fixes #9782

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 74585862611c6583b243ad8d26111304ebbc4374 at: https://65978d82a9f3f67cc2680191--meshery-docs-preview.netlify.app

**Review by leecalcote — APPROVED** [review]
Lgtm. Thanks, @Aniket-76

**Comment by l5io** [comment]
🚀 Preview for commit b323e132fa1d1b83a38580a1d6acfda664f69372 at: https://6597e567b8805f0d22475a0a--meshery-docs-preview.netlify.app

**Review by vishalvivekm — APPROVED** [review]
Thanks @Aniket-76

**Pull request merged**
