### PR TITLE
[Docs] Fix table of contents not auto generated and add auto-scrolling

### LINKED ISSUE #7293: [Docs] Table of contents is not being generated
#### Current State
image

#### Desired State
Table of contents to be generated automatically and add auto-scroll also so that when the user scrolls the main section the table of contents also scrolls to indicate which section they are in.

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by chinu-anand**
This PR fixes #7293 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 9f7c56fd14f4ec0cbb80458a4ecbfdf5ea9ce3ca at: https://64083cd5cb8791790ebf8f74--meshery-docs-preview.netlify.app

**Comment by Chadha93** [comment]
@chinu-anand  Let's discuss this on the Meshery Dev call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#) if you would. :)

**Comment by l5io** [comment]
🚀 Preview for commit d6b9420d25be880c7de56efa4e37dd4ba265277d at: https://640960a7bb4c8e62ba147922--meshery-docs-preview.netlify.app

**Review by vishalvivekm — APPROVED** [review]
Just checked @leecalcote 
Great Job, bro @chinu-anand 👍

**Comment by leecalcote** [comment]
Thank you, gents.

**Pull request merged**
