### PR TITLE
initial versioning of docs

### PR DESCRIPTION
**Pull request by warunicorn19**
Signed-off-by: Aditya Chaterjee <speak2adi@gmail.com>

**Description**
initial commit for versioning docs

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 1caa739fd8ee524fa3413ffd2a7ed8c4370acc4a at: https://6182660fa55a13cb426539a2--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit c4cb5e4116ec34216423a43af403a93b7ba1b338 at: https://618268f4425e32aca468ad01--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 15f76d1d2cca78ce3659fcb1d4a2b2a3680e89b1 at: https://61827847af5e23d4fdf563a6--meshery-docs-preview.netlify.app

**Comment by warunicorn19** [comment]
preview: https://61827847af5e23d4fdf563a6--meshery-docs-preview.netlify.app/v0.6/

**Comment by l5io** [comment]
🚀 Preview for commit 18505346d71bcfa69902a1cea65b94cdbabfb98d at: https://6188b2cd41845aa8adca1cae--meshery-docs-preview.netlify.app

**Comment by alphaX86** [comment]
@warunicorn19 you need to look at this and see if we can do this in our case too 👀 

https://github.com/justwriteclick/versions-jekyll

**Comment by warunicorn19** [comment]
Yeah @alphaX86  this is exactly what I'm trying to do rn, not sure if it works though, cause if you have a look that repo their website doesn't work.

**Comment by alphaX86** [comment]
> Yeah @alphaX86 this is exactly what I'm trying to do rn, not sure if it works though, cause if you have a look that repo their website doesn't work locally.

Sheesh :')

**Comment by l5io** [comment]
🚀 Preview for commit d0edb6ad5ec671a108751c9327054e84171b8961 at: https://618a61a06f87fd3f0ef2fabe--meshery-docs-preview.netlify.app

**Comment by warunicorn19** [comment]
https://user-images.githubusercontent.com/53532328/140925062-635c994d-b199-48e1-9634-6eefa040e15e.mov

seems to work fine locally.

**Comment by l5io** [comment]
🚀 Preview for commit 49d79c3abf037b3069f945059d7bef2d111e663d at: https://618bebd86524ed5053d6c523--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 4d6c0f79a6b1ac006c6d58dd3d2d621b6ba582c0 at: https://619237b9cf0f0ac9e52c6a9a--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 2430550ba8491f919a44f041275b4063cf127657 at: https://61923c98224af184378f304a--meshery-docs-preview.netlify.app

**Comment by leecalcote** [comment]
Yo, @Mr-DG-Wick! Here's a link to graphics you might incorporate into the article - https://drive.google.com/drive/u/0/folders/1QeevEVbVjkyvEkVNkHkRratVV-5oXdpH

**Comment by l5io** [comment]
🚀 Preview for commit 146353a13b3293136b5bbf5a4f1627e7d434e8f6 at: https://6194c2a9467babf0547d3799--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 9ceca31decb0fb7a8faa527fb6f1ae460310b711 at: https://6194d7f587b68d08b2f1563d--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit eb4c1599bb4b132d4d63df3618c81cb738c3b9fa at: https://6194e0a5ca3a721ee7009202--meshery-docs-preview.netlify.app

**Comment by leecalcote** [comment]
Instead of "0.6" in the selector, will you use "latest"?

Will you add "v" I front of the version numbers in the selector?

**Comment by alphaX86** [comment]
Great changes, I couldn't review line by line :') so I just saw the output. I noticed that for older versions, the page is taking a lot time to fetch and render. Did you imported a lot of old files and used them? Or alt way? And the delay for fetching the pages can be reduced...

That's what I feel from my side

**Comment by warunicorn19** [comment]
@alpha are you sure it's not an internet issue? it seems to be running quite fast for me

**Comment by alphaX86** [comment]
> @Alpha are you sure it's not an internet issue? it seems to be running quite fast for me

Well, since it's a new page a cached copy isn't present, so it took a while to load a page (not main page) in old versions. Plus, my username is not correct BTW :') it's someone

**Comment by warunicorn19** [comment]
oops sorry my bad. I checked on incognito as well, seems to be running for me. Anyway, i don't that'll be the case when it's deployed it's just happening now because of netlify.

**Comment by l5io** [comment]
🚀 Preview for commit f2dd4ad8bf83ccfdbb66bf0987bc7a92561dd67e at: https://619517cb8f5c5618930d7f41--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit ceebec63089588eb29880f15bb54be3c154ab790 at: https://61952098b09a22216cc0534a--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 6fd966b5d2b34cca51f95940460e4edc78fd268e at: https://619522b13dd0b722d6c74924--meshery-docs-preview.netlify.app

**Comment by warunicorn19** [comment]
@leecalcote so for the broken link which popped up in the dev call, in v0.4 there is no page for window(in supported platforms) so I'll just remove it from the sidebar right?

**Comment by leecalcote** [comment]
> @leecalcote so for the broken link which popped up in the dev call, in v0.4 there is no page for window(in supported platforms) so I'll just remove it from the sidebar right?

Right, assuming that this was just a bug that we were carrying at the time.

**Review by leecalcote — APPROVED** [review]

**Comment by l5io** [comment]
🚀 Preview for commit 39da6ea4e3968d51d86db5d210dd12370748e101 at: https://61953b0fff7ebf429f1ec2c8--meshery-docs-preview.netlify.app

**Review by leecalcote — APPROVED** [review]
Looking good!

**Pull request merged**
