### PR TITLE
[chore] Fix Filter Upload

### PR DESCRIPTION
**Pull request by theBeginner86**
**Notes for Reviewers**

Earlier UI was reading filter files as strings and that was changing the format of file during upload leading to misbehavior on deployment.
Now FilterFiles are read as binary files and hence their content type is untouched on upload leading to no unexpected behaviour.

I verified the upload and download using https://github.com/WebAssembly/wabt

This PR fixes #

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — APPROVED** [review]
Lgtm

**Review by MUzairS15 — COMMENTED** [review]
Thanks @theBeginner86 the import os working fine now. Though I found one issue, the filters are inserted twice.


https://github.com/meshery/meshery/assets/79860504/797ee729-d824-4379-bf1a-78000dcba37a

**Comment by theBeginner86** [comment]
> Thanks @theBeginner86 the import os working fine now. Though I found one issue, the filters are inserted twice.
> 
>  Screen.Recording.2023-08-04.at.8.31.30.PM.mov

Yes, I was just looking at it.
Its not inserted twice but due to some reason the API and GraphQL are returning duplicates.

Screenshot 2023-08-04 at 10 30 17 PM

Screenshot 2023-08-04 at 10 31 21 PM

Screenshot 2023-08-04 at 10 32 28 PM



Though I don't see this behavior when I run Remote Provider locally. I'm still checking this...

**Comment by theBeginner86** [comment]
Ok found it. Fixing...

**Comment by theBeginner86** [comment]
Its fixed now 👍

**Pull request merged**
