### PR TITLE
[UI] Migrate the PromptComponent to Functional component

### LINKED ISSUE #12121: [UI] Migrate Prompt to Functional Component with MUI v5 Styling and Sistent Component use
### Current Behavior
This [PromptComponent](https://github.com/meshery/meshery/blob/268c1667a6ab6a8bbdcbd960df20023d8ecbfb3a/ui/components/PromptComponent.js#L78) Component is a class-based component and it uses MUI v4's styling. These need to be updated for improved performance and consistency.

### Desired Behavior
- [ ]  migrate class-based component to a functional component
- [ ]  use [Sistent](https://github.com/layer5io/sistent) components for  MUI v4 to MUI v5 migration

Sistent is our design system that uses MUI v5, you can also refer to this [doc](https://docs.meshery.io/project/contributing/contributing-ui-sistent) to understand how to use Sistent.

### Acceptance Tests
The component must be updated without introducing any breaking changes in functionality or theming across all instances where it is used.

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by Divyansh200102**
**Notes for Reviewers**

This PR fixes #12121

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by vishalvivekm** [comment]
@Divyansh200102 Thank you for your contributions! Let's discuss this during the Meshery Development call today at 9:00 AM CT | 7:30 PM IST. Adding it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit?pli=1#) || [meeting link](https://meet.layer5.io/meshery).

**Review by pontusringblom — COMMENTED** [review]
Is there a Sistent component for this?

**Comment by Divyansh200102** [comment]
> Is there a Sistent component for this?

yes there seems to be a sistent component for this here [Link](https://github.com/layer5io/sistent/blob/329a20eb12c33c9e5190947a09757a43f2b49c89/src/custom/Prompt/promt-component.tsx#L42)

**Comment by Divyansh200102** [comment]
@pontusringblom do the changes look fine to you?

**Pull request closed without merging**
