### PR TITLE
[UI] Replicate Imports for Filters and Application similar to Patterns and fix e2e failure

### PR DESCRIPTION
**Pull request by SAEb-ai**
**Description**

This PR fixes https://github.com/meshery/meshery/issues/5121

**Notes for Reviewers**
Similar to https://github.com/meshery/meshery/pull/5203#issue-1166371776

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by SAEb-ai** [comment]
@MarioArriaga92 Please take a look. Thanks!

**Comment by leecalcote** [comment]
All greens here. ✅

**Review by MarioArriaga92 — APPROVED** [review]
LGTM, thanks for applying requested changes @SAEb-ai!

**Comment by SAEb-ai** [comment]
@leecalcote Can you please merge this for me? Thanks!!

**Comment by MarioArriaga92** [comment]
I can do it @SAEb-ai, hope @leecalcote is okay with that so 3.. 2.. 1..

**Comment by leecalcote** [comment]
Thank you much, gents.

**Pull request merged**
