### PR TITLE
Fix performance dashboard appearance

### PR DESCRIPTION
**Pull request by tangledbytes**
**Description**

This PR:
1. Changes default calendar view from month to day
2. Changes alignment of dashboard items as shown in the screenshots

Relevant Screenshots
Screenshot_20210912_181848

Screenshot_20210912_181750

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Looks great. While you're in there, do you think that you can hide the vertical separator that sits between the Results and Profiles at the breakpoint by which they vertically stack?

**Comment by warunicorn19** [comment]
@utkarsh-pro what happens to the calendar in Month view? does it fit in that space?

**Comment by utkarsh-pro** [comment]
@leecalcote are you referring to this separator?

Screenshot_20210912_181750

**Comment by leecalcote** [comment]
> @leecalcote are you referring to this separator?
> 
> Screenshot_20210912_181750

Yes, that's the one. 👍

**Comment by utkarsh-pro** [comment]
> > @leecalcote are you referring to this separator?
> > Screenshot_20210912_181750
> 
> Yes, that's the one.

Screenshot_20210913_003220

**Comment by utkarsh-pro** [comment]
@leecalcote I have fixed the separator issue, should be ready to be merged

**Comment by leecalcote** [comment]
Thank you, @utkarsh-pro 🥇

**Review by leecalcote — APPROVED** [review]

**Pull request merged**
