### PR TITLE
ui: Update js indent style

### PR DESCRIPTION
**Pull request by tsingh2k15**
#### Description

- This PR fixes # (https://github.com/layer5io/meshery/issues/1029)
- Update indentation rules to match with editorconfig (https://github.com/layer5io/meshery/pull/1020)

#### Checklist

- [x] [Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin) signed.
- [x] PR includes `[<name of area>]`

### CODE REVIEW

**Comment by kushthedude** [comment]
Hi @tsingh2k15,
You would want to edit rule at line 41 also, as we follow tab indents with spacing 4 in GoLang code IMO.

**Comment by tsingh2k15** [comment]
> Hi @tsingh2k15,
> You would want to edit rule at line 41 also, as we follow tab indents with spacing 4 in GoLang code IMO.

@kushthedude Thanks for the feedback, I will work on it. Also fyi that I am doing some research on how better to address style aspects in monorepo projects. I will share if I come across something useful.

**Comment by kushthedude** [comment]
> > Hi @tsingh2k15,
> > You would want to edit rule at line 41 also, as we follow tab indents with spacing 4 in GoLang code IMO.
> 
> @kushthedude Thanks for the feedback, I will work on it. Also fyi that I am doing some research on how better to address style aspects in monorepo projects. I will share if I come across something useful.

That would be great, Thanks @tsingh2k15 !

**Comment by kushthedude** [comment]
@leecalcote @tsingh2k15 
The whole point to change indents was to match golang style code. But as discussed in #1020, both the languages follow the different style guide, hence we went ahead with editorconfig for *.js & *.go.  I think we are good to close this PR then.

We can re-open the PR, if anyone thinks we still need it.
Thanks!

**Pull request closed without merging**
