### PR TITLE
made error codes component table mobile friendly

### LINKED ISSUE #3568: [Docs] Error Codes Categories not Mobile Friendly
#### Current State
 

In mobile the categories table is getting cut off.

#### Desired State
The entire table should be visible

---

#### Contributor Resources

- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/meshery/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
- [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by debo19**
Signed-off-by: Debopriya Bhattacharjee <debopriyabh1908@gmail.com>

**Description**

This PR fixes #3568 

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 883d4503a0e540b2cf1c02bc2fd884218bf377d3 at: https://60f70d3e889d2447b22b155b--meshery-docs-preview.netlify.app

**Review by leecalcote — DISMISSED** [review]
Looking good, @debo19. Thank you. 👍

**Comment by warunicorn19** [comment]
yup looks good @debo19 , thanks!

**Comment by l5io** [comment]
🚀 Preview for commit 650999d1b68a318d386bffe87b7e001e5586e592 at: https://60f7167c9fcaa74fe2fd4381--meshery-docs-preview.netlify.app

**Review by leecalcote — APPROVED** [review]
Away we go! Thank you, @debo19 👍

**Pull request merged**
