### PR TITLE
Update mesheryctl.md

### PR DESCRIPTION
**Pull request by dA505819**
Signed-off-by: dA505819 dhruvaggarwal6@gmail.com

#### Description

Corrected typo.

This PR fixes #    

#### Checklist

- [] [DCO](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin) signed.
- [] Title of the PR starts with area name, e.g. `meshery:`, `mesheryctl:`, `ui:`.

### CODE REVIEW

**Comment by dA505819** [comment]
@leecalcote Please review it.

**Comment by dA505819** [comment]
@shivaylamba  When signing, it's generating an error.
`error: failed to push some refs to 'https://github.com/layer5io/meshery.git'
`

**Comment by snitin315** [comment]
Use --force

**Comment by dA505819** [comment]
@snitin315 Using --force only, but still the error persists.
`$ git push --force-with-lease origin patch-1

error: src refspec patch-1 does not match any
`

**Comment by snitin315** [comment]
Can you show the output of `git remote -v` and `git branch`

**Comment by dA505819** [comment]
@shivaylamba I have generated the gpg key and added to github account. But still the error shows:
```
$ git commit --amend --signoff
error: cannot spawn C:\Program Files\Git\usr\bin\gpg.exe
: No such file or directory
error: gpg failed to sign the data
fatal: failed to write commit object
```

**Comment by leecalcote** [comment]
@dA505819 Thanks for this PR!

Here are instructions on how to amend the commit(s) in this particular PR: https://github.com/layer5io/meshery/pull/831/checks?check_run_id=579655562

Here are instructions on how to ensure that your commits are automatically signed in the future: https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin

**Comment by dA505819** [comment]
@leecalcote I will follow it. 
Correcting this PR will take some more time.

**Comment by leecalcote** [comment]
@dA505819 no sweat. The instructions are to amend the commit in this PR are hard to understand, but simple to execute (a 30 second or so task).

**Comment by dA505819** [comment]
@leecalcote No worries Lee! Thankyou for the kind words. That's true but I was somewhere have to prioritize other work at this time.  I will execute the commits asap.

**Comment by dA505819** [comment]
I am generating another PR.

**Pull request closed without merging**
