### PR TITLE
[WIP] Tracking cookies to add a Popup in Meshery

### PR DESCRIPTION
**Pull request by warunicorn19**
Signed-off-by: Aditya Chatterjee <speak2adi@gmail.com>

**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by warunicorn19** [comment]
@leecalcote the cookie part of this is done, what all do you want me to add in the popup? 
Screenshot 2022-11-03 at 2 35 41 AM

**Comment by leecalcote** [comment]
A screenshot of MeshMap from Designer drawer over across canvas (so excluding the Meshery UI chrome, so to speak). 

Can this popup be a lower, right hand corner placement and not an all-consuming modal?

**Comment by warunicorn19** [comment]
Sure I can do that. Do you want me to remove the dark background as well and make it seem as if its part of the page itself?

**Comment by leecalcote** [comment]
> Sure I can do that. Do you want me to remove the dark background as well and make it seem as if its part of the page itself?

Yes, please, if you would.

**Comment by leecalcote** [comment]
Example: Screen Shot 2022-07-29 at 11 32 14 AM

**Comment by leecalcote** [comment]
Here is a different example of what might be modals to show in the future, but not for this particular advert.

Screen Shot 2022-07-29 at 5 23 40 PM

**Comment by warunicorn19** [comment]
Screenshot 2022-11-03 at 6 08 39 PM

Thoughts @leecalcote  ?

**Comment by leecalcote** [comment]
I missed this earlier, @warunicorn19. 

It's perfect. 👌

**Review by leecalcote — DISMISSED** [review]

**Pull request merged**
