### PR TITLE
Kumarabd/feature/graphqls

### PR DESCRIPTION
**Pull request by kumarabd**
**Description**

- Added graphql support on the same meshery server's HTTP port.
- Added workflow changes for plugin packaging
- Support for three major sections where MeshSync data is needed
1. Control plane information
2. Operator information
3. Metrics/Addons information on every adapter dashboard 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
This is _very_ exciting

**Comment by leecalcote** [comment]
🔔 ” unnecessary leading newline (whitespace)”

**Comment by kumarabd** [comment]
@utkarsh-pro Do test out your changes for this

**Comment by leecalcote** [comment]
We need to test this today. Is this still in-hold?

**Comment by kumarabd** [comment]
> We need to test this today. Is this still in-hold?

Aiming on getting it done by tonight. Graphql issues, we're testing and fixing stuff.

**Pull request merged**
