### PR TITLE
fix for Adapter and Metric in settings section

### PR DESCRIPTION
**Pull request by Shivam164**
**Notes for Reviewers**

This PR fixes [#7917](https://github.com/meshery/meshery/issues/7197)

This also fixes the dark mode issue with the Metrics section.

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.
 
Screenshot from 2023-03-02 10-59-24

Screenshot from 2023-03-02 10-59-32

Screenshot from 2023-03-02 10-59-41

Screenshot from 2023-03-02 11-04-21

### CODE REVIEW

**Review by hs05june — CHANGES_REQUESTED** [review]
Thank you for the PR @Shivam164 . Changes look good. I would love if you make similar changes in ui/components/telemetry/prometheus/PrometheusConfigComponent.js too 🤞

**Comment by Shivam164** [comment]
Hey @hs05june, I have made the requested changes.

**Comment by hs05june** [comment]
@Shivam164 Cool

**Review by hs05june — APPROVED** [review]

**Comment by leecalcote** [comment]
Thank you, gents. 👏

**Review by leecalcote — APPROVED** [review]

**Pull request merged**
