### PR TITLE
[UI] Resize sidebar to accomodate external links

### LINKED ISSUE #2008: [UI] Collapsed NavBar not showing External Links properly
**Description**

image

**Expected Behavior**

**Screenshots**

**Environment:**
- Browser: Chrome

---
[Optional] **To Reproduce**
1. Go to meshery
2. Click on collapse navigation

[Optional] **Additional Context**

### PR DESCRIPTION
**Pull request by uds5501**
Signed-off-by: Uddeshya Singh <singhuddeshyaofficial@gmail.com>

**Description**

This PR fixes #2008

**Notes for Reviewers**
- I have created collapsed states for both logo and logo text for the collapsed column.
- Tried changing the placement to the top but couldn't pull that off, ended up with increasing the collapsed column size a bit and expanding the margins for meshery logo accordingly
- Not sure why the changes proposed are so many, it happened during commit i guess, please let me know if this needs to be fixed.

### For reference: 
image

**[Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by kushthedude** [comment]
> Not sure why the changes proposed are so many, it happened during commit i guess, please let me know if this needs to be fixed.

It's because of conflicts between your editor configuration and our editorconfig file. Try resetting your editorconfigs

**Comment by uds5501** [comment]
@kushthedude thanks for the pointer, maybe take a look now?

**Review by kushthedude — APPROVED** [review]
lgtm

**Comment by Nikhil-Ladha** [comment]
The `new-window` icon for slack seems a bit misaligned, in the image you shared as well. Is it feasible to fix that one?

**Comment by uds5501** [comment]
@Nikhil-Ladha @kushthedude Updated the alignment, now it looks like this, will this be fine?
image

**Comment by Nikhil-Ladha** [comment]
The `Meshery` logo and the `collapse` button is still a bit off alignment. Once that's fixed I think we are good to go :+1:

**Comment by uds5501** [comment]
@Nikhil-Ladha 
image
Looks good?

**Review by Nikhil-Ladha — APPROVED** [review]
Yes, it does!

**Comment by kushthedude** [comment]
Congrats on your first PR @uds5501 🥳 🥳 ! I am sure if we had welcome bot enabled you would have got a better message.

**Comment by uds5501** [comment]
Thank you @kushthedude !

**Pull request merged**
