### PR TITLE
fix: Citrix logo in adapter fetch list

### LINKED ISSUE #876: Wrong logo of Citrix service mesh in Adapter URL
Wrong logo of Citrix service mesh in Adapter URL

#### Screenshot 

Screenshot 2020-04-21 at 4 50 17 PM

### PR DESCRIPTION
**Pull request by kushthedude**
Fixes #876 

#### Screenshot :- 
Screenshot 2020-04-21 at 4 52 09 PM

### CODE REVIEW

**Comment by kushthedude** [comment]
@leecalcote Please review & merge!

**Comment by leecalcote** [comment]
Related to #756. Good catch, @kushthedude. This particular bug goes a layer deeper in that a fix in one area (of the logo), breaks another area (provisioning (in the adapter?)). I’ll look to the calendar for a spot to do troubleshooting with you, and @dheerajng

**Comment by kushthedude** [comment]
Cool!

**Comment by leecalcote** [comment]
Closing this PR given the merge of #746. Thanks for this, @kushthedude.

**Pull request closed without merging**
