### PR TITLE
creating issue/remind label text

### PR DESCRIPTION
**Pull request by Anita-ihuman**
Signed-off-by: Anita-ihuman <charlesanita403@gmail.com>

**Description**
modified workflow to include a comment on the application of an `issue/remind` label. 
This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — APPROVED** [review]
@Anita-ihuman thank you. I've made an update to the wording. Are you ok with this?

**Comment by leecalcote** [comment]
It would be great to get another one of these for `issue/dco`.

**Review by Anita-ihuman — COMMENTED** [review]
This sounds a lot better.

**Comment by Anita-ihuman** [comment]
> It would be great to get another one of these for `issue/dco`.

Sure, I will get to that.

**Pull request merged**
