### PR TITLE
[meshery] Support KinD doc

### LINKED ISSUE #526: Docs: Platform Support for KinD
**Current State:**
Meshery is compatible with WSL2 and with KinD, however, in order for Meshery to be able to communicate with KinD additional environment setup is necessary.

**Desired State:**
1. KinD listed as a supported platform.
1. Additional networking configuration documented.

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

### PR DESCRIPTION
**Pull request by Aisuko**
Signed-off-by: Aisuko <urakiny@gmail.com>

**Description**

This PR fixes #526 

**Notes to reviewers**

#### Checklist

- [x] [Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin).
- [x] PR title includes `[<name of area>]:<description>`

### CODE REVIEW

**Comment by leecalcote** [comment]
Goood! A new line item in Meshery main Readme is appropriate as well.

**Comment by Aisuko** [comment]
I'd like to add the label to split the issue by type and trigger the CI [backend UI]. Because every PR the CI jobs all run to test, there may no sense

**Comment by Aisuko** [comment]
> Thanks, @Aisuko. Please add KinD to the list of supported platforms in the `meshery` repo readme.

Thanks for helping me update the Readme.

**Comment by leecalcote** [comment]
Teamwork. 😄

**Pull request merged**
