### PR TITLE
Removed unnecessary packages and updated dependencies

### PR DESCRIPTION
**Pull request by AradhyaDixit18**
Pull Request Description

 **Title:** Remove Unnecessary Packages and Update Dependencies

 **Summary:**
This pull request addresses the removal of unused or outdated packages from the `meshery/ui` project and updates the dependency management for better optimization and maintenance.

 **Changes Made:**
- **Removed the following unused or outdated packages:**
  - `glob-parent`
  - `@types/react-relay`
  - `caniuse-lite`
  - `color-string`
  - `@babel/traverse`
  - `cron-time-generator`
  - `set-value`
  - `minimist`
  - `webpack-cli` (Not needed directly due to Next.js internally handling Webpack in versions above 11)

- **Kept the following package:**
  - `webpack` (Required for Cypress testing)

- **Removed `next-compose`** as Next.js now has better support for plugins and this package is over 5 years old.

 **Reasoning:**
- **Optimization:** Removing these packages reduces the project's footprint and potential security vulnerabilities from outdated dependencies.
- **Simplification:** Next.js natively supports many of the functionalities that some of these packages provided, rendering them unnecessary.
- **Maintenance:** Keeping only the necessary dependencies makes the project easier to maintain and reduces the risk of issues arising from unneeded packages.

 **Testing:**
- Verified that the UI builds and functions as expected after the removal of the packages.
- Cypress tests were run to ensure no breaking changes occurred due to the modifications.

#### **Next Steps:**
- Review the PR for any potential edge cases or dependencies that might have been overlooked.
- Merge the branch after approval to implement these optimizations in the main codebase.

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by Yashsharma1911 — COMMENTED** [review]
Thankyou, merge conflicts @AradhyaDixit18

**Review by leecalcote — COMMENTED** [review]
Thanks, @AradhyaDixit18. If webpack is only included for Cypress, should be able to remove it as the project has switched to Playwright.

> - webpack (Required for Cypress testing)

**Comment by AradhyaDixit18** [comment]
Sure sir i'll try to be present in the meeting

**Comment by Ashparshp** [comment]
@AradhyaDixit18, Join meeting please and also, [join slack.](https://join.slack.com/t/layer5io/shared_invite/zt-2pyliaxz6-dAud7zIWr1NzB5mAc5ukCg)

**Comment by leecalcote** [comment]
Merge conflict

**Comment by leecalcote** [comment]
Merge conflicts are still here, @AradhyaDixit18

**Comment by leecalcote** [comment]
I went ahead and eliminated the merge conflict.

**Review by leecalcote — APPROVED** [review]

**Pull request merged**
