### PR TITLE
[Spaces] Finalize support for Environments

### PR DESCRIPTION
**Pull request by theBeginner86**
**Notes for Reviewers**

1. Adds support for orgs
2. Updates APIs docs
3. Adds new redux store for selected org
4. Use capability for env
5. Cleanup env APIs

This PR fixes #

Meshery Provider:
Screenshot 2023-12-13 at 11 00 06 PM

None Provider:

Screenshot 2023-12-13 at 11 00 17 PM

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 822b0a29c941a7bb2769ae882d9682eb0fad0d4e at: https://6579ad6286424f0e6ed22b35--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 56e83e3fd51724045b3225dc6e6d19dcd80ad81d at: https://6579bd7437091a1aaacd09aa--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 817188ce2afab887e03bbc2ba81d9a9b3a04d1a3 at: https://6579c58937091a20f6cd0955--meshery-docs-preview.netlify.app

**Comment by theBeginner86** [comment]
Merging this now...
Will be creating a subsequent PR for docs update about the inclusion of Orgs and what it means for Remote Providers. And Separately a PR for workspaces.

// @leecalcote

**Pull request merged**
