### PR TITLE
fix: update parsinggithub test to prevent failing issue

### PR DESCRIPTION
**Pull request by lekaf974**
**Notes for Reviewers**

This PR fixes #

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by vishalvivekm** [comment]
@lekaf974 
Thank you for your contributions! Let's discuss this during the Meshery Development call today at 9:00 AM CT.
Adding it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit?pli=1#) || [meeting link](https://meet.layer5.io/meshery).

**Review by leecalcote — CHANGES_REQUESTED** [review]
Do we need this test? 

If yes, what functionality is it testing?

If not, are we better off deleting it?

**Comment by lekaf974** [comment]
I'd rather delete this test since I am not sure it is really relevant

**Comment by lekaf974** [comment]
Finally remove the test

**Review by leecalcote — APPROVED** [review]
Excellent. 🙂

**Pull request merged**
