### PR TITLE
feat: relationship between ConfigMap using volume mounts

### LINKED ISSUE #9821: [Models] Relationships for Kubernetes ConfigMap using Volume Mounts
### Current Situation
See PR #9816 

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- [MeshModel Repository](https://github.com/meshery/meshery/tree/master/server/meshmodel)
- 🖥 [MeshModel Overview](https://docs.google.com/presentation/d/1SQMfyu5shjpGKlYONdVzOtd7UYTgLWBcgUvHMLCZ2tY/edit#slide=id.g226f5de5180_19_259)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

## Contributing to Meshery Models

!! See https://docs.meshery.io/project/contributing/contributing-models

### Instructions for Models

_Forthcoming_

### Instructions for Components
While the default shape for new components is a circle, each component should be considered for its best-fit shape.
1. Review and familiarize with the available set of predefined relationship types. Refer the Cytoscape [node types](https://js.cytoscape.org/demos/node-types/) for a list of possible shapes. 
1. Propose a specific shape, best-suited to visually represent the Component. _Example - Deployment as a pentagon._
1. Proposee a specific icon, best-suited to visually represent the Component. _Example - DaemonSet as a skull icon._

### Instructions for Relationships
1. Identify the relationship and any specific constraints to be enforced between the two specific components, their models or potentially other components, models, or environmental considerations.
1. Propose a specific visual representation for the relationship. Visual representation examples: [Hierarchical](https://docs.meshery.io/assets/img/meshmodel/relationships/hierarchical_relationship.png), [Sibling](https://docs.meshery.io/assets/img/meshmodel/relationships/sibling_relationship.png), [Binding](https://docs.meshery.io/assets/img/meshmodel/relationships/binding_relationship.png), [Edge](https://docs.meshery.io/assets/img/meshmodel/relationships/mount_edge_relationship.png)
1. Prospose the appropriate relationship type, using one of the predefined set of relationship types or suggest a new relationship where an existing type does not fit.
1. Create a Relationship Definition (yaml). See the [Relationship Schema](https://github.com/meshery/meshery/tree/master/server/meshmodel/schemas) in MeshModel and [examples]([url](https://github.com/meshery/meshery/tree/master/server/meshmodel/relationships)).
1. Create a policy for evaluation of the relationship (rego). See examples.

### Instructions for Policies
1. _Forthcoming_
### Instructions for Policies
1. _Forthcoming_

### PR DESCRIPTION
**Pull request by RipulHandoo**
**Notes for Reviewers**

This PR fixes #9821 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by RipulHandoo** [comment]
@MUzairS15 Will you please take a look at this. Thanks.

**Comment by leecalcote** [comment]
Are we ready to merge our 10,000th PR?

**Comment by RipulHandoo** [comment]
> Are we ready to merge our 10,000th PR?

Yes, we are ready to merge. As discussed with @MUzairS15, I have implemented the suggested changes. However, please note that the `MeshMap ScreenShot Service` tests are currently failing for all the PRs

**Comment by saurabh100ni** [comment]
Hi @RipulHandoo  ,
Thanks for your PR! I encourage you to share this in the Website Meeting tomorrow at 6:30 PM IST. Share your screen, and walk us through it. It's cool to take and share feedback. Check the [Doc](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit) here to include this PR.

You're welcome at the meeting

Check to [community calendar](https://layer5.io/community/calendar) for more details of meetings at Layers.

**Comment by RipulHandoo** [comment]
Sure @saurabh100ni I'll be there.

**Review by leecalcote — CHANGES_REQUESTED** [review]
merge conflict.

no proof of working relationship

**Review by leecalcote — DISMISSED** [review]

**Comment by leecalcote** [comment]
@RipulHandoo, will you be incorporating and addressing this feedback?

**Comment by RipulHandoo** [comment]
> merge conflict.
> 
> no proof of working relationship

@leecalcote, I will address the merge conflicts and provide a video demonstrating the functionality of the relationship

**Comment by leecalcote** [comment]
> > merge conflict.
> > no proof of working relationship
> 
> @leecalcote, I will address the merge conflicts and provide a video demonstrating the functionality of the relationship

Thank you, @RipulHandoo

**Comment by MUzairS15** [comment]
@RipulHandoo Please add the limitation we discussed.

**Comment by leecalcote** [comment]
@RipulHandoo let's finish off and get this stalebot off our back. 👍

**Pull request closed without merging**
