### PR TITLE
[Settings] Support multiple contexts

### PR DESCRIPTION
**Pull request by MUzairS15**
**Description**

This PR fixes #

**Notes for Reviewers**
WIP
Redesigning `Settings` page.

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.
 

https://user-images.githubusercontent.com/79860504/172114715-c33203c7-e8c6-4514-8613-1e94e78bf8eb.mov

### CODE REVIEW

**Comment by MUzairS15** [comment]
`Cuurently operator/meshsync state, version...` are not specifc to context as API calls are not ready for that, once it is done I will make necessary changes, so that each `  operator/meshsync state, version...` are reflected of corressponding contexts.
// @Abhishek-kumar09

**Comment by MUzairS15** [comment]
Screenshot 2022-06-06 at 12 47 28 PM


Tests needs to be updated.

**Comment by MUzairS15** [comment]
For uploading the config, there are two steps:
1. Upload the config, system detects all context,
2. Ask User which to connect.

I am facing issue with this, as it will require parsing of config file, and if there are 2/3... contexts and user doesn't selects all of them, a new `config` file with selected contexts needs to be created. 
So this all logic should be handled on client side or should I expose an endpoint. Or some other approach or should we drop this idea.

// @leecalcote  @Abhishek-kumar09

**Comment by MUzairS15** [comment]
For now I have kept functionality of just uploading file.

**Comment by leecalcote** [comment]
@MUzairS15 @Revolyssup " a new config file with selected contexts needs to be created." Is this true? Why do we need to create a config file at all? The context data is kept in local and remote provider databases, so, why the need to generate a new kubeconfig file?

**Comment by leecalcote** [comment]
@MUzairS15 heads-up: a merge conflict.

**Comment by MUzairS15** [comment]
Closing commits pushed in https://github.com/meshery/meshery/pull/5528

**Pull request closed without merging**
