### PR TITLE
Fix issue #6273 - updated api endpoints and improved error messages for 'mesheryctl exp filter' commands

### LINKED ISSUE #6273: [mesheryctl] improve the error messages shown to users for "mesheryctl exp filter"
**Description**: Improve the error messages in mesheryctl commands from the user's perspective. 
**Commands in scope of this issue**: `mesheryctl exp`, `mesheryctl exp filter`, `mesheryctl exp filter apply`, `mesheryctl exp delete`, `mesheryctl exp list`, `mesheryctl exp view`

---

We need to make sure of the following things
- There are proper error messages when users
  - Give more arguments to a command than required
  - Misspell a command
  - Do not give the required input via flags or args
  - Use the command without any arguments or flags.
- The error messages being displayed to users are meaningful from user's perspective. And if applicable, a potential fix for the problem should be shown too.  For example
  - "failed to unmarshal response body" could be modified to "couldn't process JSON response from server"
  - "manifest not found" could be modified to "manifest not found. Please provide the path to the app manifest."
  
 --- 
  #### Contributor Resources

- ⌨️ [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

For additional context, head over to this [pr](https://github.com/meshery/meshery/pull/5661).

### PR DESCRIPTION
**Pull request by SufyaanKhateeb**
**Description**

This PR fixes #6273 

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
@SufyaanKhateeb Some good work here. Do you mind updating the PR title to be more descriptive of the changes included? If you're available to present your changes on this week's Meshery Development Meeting, please do. Drop a note on the meeting agenda to confirm - https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit

**Comment by SufyaanKhateeb** [comment]
> @SufyaanKhateeb Some good work here. Do you mind updating the PR title to be more descriptive of the changes included? If you're available to present your changes on this week's Meshery Development Meeting, please do. Drop a note on the meeting agenda to confirm - https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit

**Review by piyushsingariya — APPROVED** [review]
LGTM

**Review by alphaX86 — APPROVED** [review]
Well this looks pretty to me... LGTM

**Comment by leecalcote** [comment]
Thank you, @SufyaanKhateeb 👏

**Pull request merged**
