### PR TITLE
fix: broken link

### LINKED ISSUE #10133: [Docs] The link is broken in https://docs.meshery.io/concepts/logical/models
### Current State

The link of [components examples](https://github.com/meshery/meshery/blob/20bbdb696a2587886b72138a3caa31723dd67197/docs/pages/concepts/logical/models.md?plain=1#L50) in https://docs.meshery.io/concepts/logical/models is broken (404).

### Desired State

We should find and link another model which have components definition.

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by RipulHandoo**
**Notes for Reviewers**

This PR fixes #10133 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit aff0a0aa3e5f666c47f99171e03533081425bd8b at: https://65bb45430295e544caef76ad--meshery-docs-preview.netlify.app

**Review by leecalcote — CHANGES_REQUESTED** [review]
Let's stop linking to the source code, especially on user-facing pages.

**Comment by l5io** [comment]
🚀 Preview for commit 3cb9b87b509a218a0122f577a9ca415af749b355 at: https://65bb9e9302c6e108b2b32054--meshery-docs-preview.netlify.app

**Comment by RipulHandoo** [comment]
> Let's stop linking to the source code, especially on user-facing pages.

Is there any alternative option.

**Comment by leecalcote** [comment]
> > Let's stop linking to the source code, especially on user-facing pages.
> 
> Is there any alternative option.

Yes, link to the user-facing pages the correspond to each entity.

**Pull request closed without merging**
