### PR TITLE
Minor fix in API doc

### PR DESCRIPTION
**Pull request by prachinandi**
**Notes for Reviewers**

This PR fixes https://github.com/meshery/meshery/issues/11495#issuecomment-2383926535

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit ccba443fc48195c5a70ba3d2fd6a6a58823cef1a at: https://66fd5607764d000463d606c3--meshery-docs-preview.netlify.app

**Comment by lekaf974** [comment]
@prachinandi thank you for your work can you fix DCO check error

**Review by leecalcote — APPROVED** [review]
Thanks!

**Comment by leecalcote** [comment]
@prachinandi, you'll need to sign this commit. Follow these instructions:

To add your Signed-off-by line to every commit in this branch:

Ensure you have a local copy of your branch by [checking out the pull request locally via command line](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/checking-out-pull-requests-locally).
In your local branch, run: git rebase HEAD~1 --signoff
Force push your changes to overwrite the branch: git push --force-with-lease origin apidoc

**Comment by sudhanshutech** [comment]
@prachinandi will you signoff your commits please.

**Comment by l5io** [comment]
🚀 Preview for commit b9123cf88e3664729393890401580a082b82b120 at: https://66fecb741c356fe91863ad0e--meshery-docs-preview.netlify.app

**Review by lekaf974 — APPROVED** [review]

**Review by lekaf974 — APPROVED** [review]
Thanks

**Pull request merged**
