### PR TITLE
Refactor/remove cypress

### PR DESCRIPTION
**Pull request by senthil-athiban**
**Notes for Reviewers**

This PR fixes #
- [x] Uninstalled cypress packages
- [x] Removed cypress test and fixtures in `provider-ui` and `meshery-ui`

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by senthil-athiban** [comment]
@jerensl do we have any workflow that uses cypress?

**Comment by jerensl** [comment]
@senthil-athiban It's all nice to me. Great work 👏. I have just one question. How do we track the migration process? I think some test cases that have not migrated yet can be useful for tracking progress. What do you think?

**Comment by senthil-athiban** [comment]
@jerensl, I am not aware of any tracking sheet from cypress to playwright. However, I'm sure about that the existing cypress test are migrated to playwright.

**Comment by yash37158** [comment]
@senthil-athiban @jerensl, I believe we definitely need to add a column in the [Meshery Test Plan](https://docs.google.com/spreadsheets/d/13Ir4gfaKoAX9r8qYjAFFl_U9ntke4X5ndREY1T7bnVs/edit?pli=1&gid=0#gid=0) to track the migration.

**Review by jerensl — APPROVED** [review]

**Pull request merged**
