### PR TITLE
Make tables responsive on small screens

### LINKED ISSUE #11622: Tables are not fully responsive on small screens, leading to content being cut off or not displayed properly.
(https://docs.meshery.io/reference/mesheryctl)

### Desired State

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by vaishnaviadhau**
**Notes for Reviewers**

This PR fixes #11622 

Now, the tables are fully responsive on small screens as well.

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit c04d5c066334ef070b2653e685c633a8a4c58d51 at: https://66c123ec9b90ffe0e9d8d42d--meshery-docs-preview.netlify.app

**Review by amitamrutiya — COMMENTED** [review]
@vaishnaviadhau Why did you change the board and color of the table? Was there any suggestion from others?

**Comment by vaishnaviadhau** [comment]
@amitamrutiya No, I'll fixed this.

**Comment by l5io** [comment]
🚀 Preview for commit 1dc882932ce87e332e470ee2ebda77da380e8130 at: https://66c24b63f0169fd8f4266069--meshery-docs-preview.netlify.app

**Comment by vaishnaviadhau** [comment]
@amitamrutiya I have fixed the issue you can check it now.

**Comment by Ashparshp** [comment]
@vaishnaviadhau, let's discuss this PR during the Meshery dev meeting call, if you would. Please add it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit?usp=drivesdk).

**Review by Ashparshp — COMMENTED** [review]
Looks good, but I suggest we try something similar to the Layer5 Meetings page (https://layer5.io/community/calendar#meetings), please review the table, check the code, and see if you can replicate it. Let me know if you encounter any issues.

**Comment by vaishnaviadhau** [comment]
@Ashparshp Apologies for the late response. I'll check the table and code now and let you know if I encounter any issues.

**Comment by Ashparshp** [comment]
@vaishnaviadhau, check out the [table](https://docs.meshery.io/concepts/architecture#meshery-connections-and-their-actions): Meshery Connections and their Actions

**Comment by leecalcote** [comment]
Checking in... @vaishnaviadhau, are you tying this one off?

**Comment by vaishnaviadhau** [comment]
@leecalcote  I  have already discussed it with @Ashparshp . The changes I made are yet to be confirmed by him 
Screenshot 2024-08-26 022957

**Comment by Ashparshp** [comment]
Have you joined the last call @vaishnaviadhau?

**Comment by vaishnaviadhau** [comment]
@Ashparshp Sorry I wasn't able to join due to some other work.

**Comment by Ashparshp** [comment]
Let's discuss on the next website meeting? If you would?

**Comment by vaishnaviadhau** [comment]
@Ashparshp I'll be there for the next meeting.

**Comment by leecalcote** [comment]
> @Ashparshp I'll be there for the next meeting.

@vaishnaviadhau, awesome. You've been hard at work contributing. This certainly doesn't go unnoticed. 😄  // @vishalvivekm

**Comment by Ashparshp** [comment]
Thank you @vaishnaviadhau,
Let's discuss this PR on Meshery development call today. Adding it as an agenda item to the meeting minutes. if you would :)

Timing: 9:00 AM CT
Meeting minutes: [Google Docs](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit)
Meeting link: [meet.layer5.io/meshery](https://meet.layer5.io/meshery)

**Comment by vaishnaviadhau** [comment]
I wanted to mention that the PR was already discussed in last Monday's meeting, where we agreed not to change the style. Apologies, due to a scheduled interview at 7:30, I won’t be able to attend today's meeting.

**Review by sudhanshutech — APPROVED** [review]

**Pull request merged**
