### PR TITLE
[Docs] Fixed sorting issue of Linkerd test results

### LINKED ISSUE #5618: Sortable Columns on the Integration Test Results pages
#### Current Behavior

[This](https://docs.meshery.io/project/compatibility-matrix/meshery-linkerd-past-results) page currently doesn't have proper sorting on columns.
#### Desired Behavior

Add proper sorting on each column.
#### Mockups

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by asubedy**
Signed-off-by: asubedy <frexpe@pm.me>

**Description**

This PR fixes #5618

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — CHANGES_REQUESTED** [review]
These might need to be updated, but is not the solution. The ask is to make the columns sortable. Allow users to click to switch between ascending / descending sort of each column.

**Comment by l5io** [comment]
🚀 Preview for commit f670ddd36db96ec0f3e30832a37aa71b6fe03fdb at: https://62aa3e2f651ff17fad01b516--meshery-docs-preview.netlify.app

**Comment by leecalcote** [comment]
> 

Yes, for all columns for all tables (compatibility matrix and integration tests).

**Comment by leecalcote** [comment]
See this section on the issue:

"**Desired Behavior**

Add proper sorting on each column."

**Comment by leecalcote** [comment]
@asubedy given the misunderstanding here, do you want to close and start again?

**Comment by asubedy** [comment]
No no I am working on this same branch lets not close this.

**Comment by leecalcote** [comment]
Alrighty... unless the stale bot gets to it first. ;)

**Comment by l5io** [comment]
🚀 Preview for commit 1b3bf77a6fb6f5232be6605dc19bbe6aec08a395 at: https://62cefaec29f5740dca49896d--meshery-docs-preview.netlify.app

**Review by warunicorn19 — DISMISSED** [review]

**Comment by leecalcote** [comment]
These section headers don't seem to sort - 
Screen Shot 2022-07-21 at 4 55 23 PM

**Comment by asubedy** [comment]
@leecalcote Do we need sorting on the the main integration table? Since we are showing the latest result only of a particular Meshery-component, I didn't think there was a need for the sorting feature here. If it is required it can be added here.

**Comment by l5io** [comment]
🚀 Preview for commit d30406d9595cf23d4c46cb21b989541d453ee3e0 at: https://62eab7e704c95e0f6fff8e47--meshery-docs-preview.netlify.app

**Comment by leecalcote** [comment]
Merge conflict, @asubedy.

Push to get this reviewed and merged. Or get it closed.

**Comment by l5io** [comment]
🚀 Preview for commit f9fbbc13277946ecf54d43c33e27cb0c4fba56d8 at: https://63032ab35f31e435d505ea7e--meshery-docs-preview.netlify.app

**Review by warunicorn19 — APPROVED** [review]
LGTM.

**Pull request merged**
