### PR TITLE
Migrate e2e ui testing workflow from cypress to playwright tests

### LINKED ISSUE #10988: [CI] migrate the e2e testing workflow to use playwright .
### Current Behavior

Migrate the meshery ui end to end testing workflow ( currently disabled ) to use the new playwright tests .
the playwright test suite  can be started using make commands .

### Acceptance Tests

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
- Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)
- 🧪 [Meshery Test Plan Spreadsheet](https://docs.google.com/spreadsheets/d/13Ir4gfaKoAX9r8qYjAFFl_U9ntke4X5ndREY1T7bnVs/edit#gid=0)

### PR DESCRIPTION
**Pull request by DevRish**
**Notes for Reviewers**

This PR fixes #10988 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Thank you, @DevRish! 

@captain-Akshay @dragon-slayer875 you might offer feedback here.

**Review by jameshorton2337 — CHANGES_REQUESTED** [review]
Thanks so much for this, @DevRish.

I'm afraid it completely misses the point, however. The point its to rewrite the tests from one tool to the next, not to re-enable the tool that we're no longer using.

**Comment by DevRish** [comment]
@jameshorton2337  Thanks for your review. 
But, I think this particular issue was associated with modifying the github workflows to use playwright tests instead of cypress ones, not for adding the tests themselves. 
I have seen that not many e2e tests have been written in playwright yet, but much of the necessary project setup has been completed for integrating with playwright (like the creation of tests directory, adding of test related goals to the make file, etc.). I thought this task was a part of such pre-required setup. 
I haven't just re-enabled the existing tool, I have kept the first part that is required for starting the services, and modified the last part to execute the playwright based `make` goals instead of the cypress ones.

**Comment by leecalcote** [comment]
@DevRish, if the tests haven't been rewritten, there's no sense in re-enabling the old tests that are intentionally disabled. Please re-approach the sequence of this work.

**Pull request closed without merging**
