### PR TITLE
fixed the alignment and space of some icons

### LINKED ISSUE #7269: [UI] improve the positon and spacing of icons in the UI
#### Current Behavior

While most of the icons are placed perfectly fine in the UI, there are some which are aligned in the wrong way, or have wrong amount of spacing.

#### Desired Behavior

The icons should be aligned properly and also have proper spacing to ensure the UI looks clean and polished.
For example:
Current: 
i2

Possible Improvement:
i3

#### Implementation

1. Identifying the icons which are wrong( already few examples are here, like the "heart" shape of the footer)
2. Applying styles that make the icons properly spaced and aligned.

#### Mockups

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by sidtohan**
**Notes for Reviewers**

This PR fixes #7269 
I have fixed the alignment of footer icon and also spacing of settings icons in some places. I'll check some more but in the meantime, I want to ensure these changes are acceptable.

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by sidtohan** [comment]
@yash37158 can you take a look and suggest any improvements for the same? thanks.

**Comment by Yashsharma1911** [comment]
LGTM 👏 @sidtohan can you share a screenshot of the changes that you have made

**Comment by sidtohan** [comment]
Sure @Yashsharma1911, here are the changes:
1. Footer
  - Before
i2

  - After
i3

2. Management
  - Before
i7

  - After
i4

3. Management Adapter Pages
  - Before
i1

  - After
i5


4. Collapse Button
  - Before
i6

  - After
i8

**Comment by Yashsharma1911** [comment]
nice work @sidtohan except `setting` button and `configure setting` button they still don't seem so different compared to before if you can align it properly it would be nice

**Comment by sidtohan** [comment]
> nice work @sidtohan except `setting` button and `configure setting` button they still don't seem so different compared to before if you can align it properly it would be nice

I did adjust the gap between icon and text a bit, but yes the alignment seems off. But this is the case with all other buttons right now from what I can see. I'll try to think of a solution for this.

**Comment by sidtohan** [comment]
@Yashsharma1911 so just one thing, I was looking at the exact orientation, and it seems the icon and text are indeed centered. It makes sense since the button itself does have flexbox with align-items:center. 
pr1
I suppose it looks a little "weird" because of the nature of the icon. But otherwise, the alignment seems ok.
One thing I did notice is that using align-self:"flex-start" does it make seem just very slightly better, but it may cause issue with responsiveness down the line. Also, this doesn't work with the configure settings button.
With center alignment:
i5

With flex-start alignment:
pr2

**Comment by hs05june** [comment]
> 

Well observed @sidtohan . Surely the flex-start alignment looks better. I am requesting to make that change.

**Review by hs05june — CHANGES_REQUESTED** [review]
Add flex-start in alignment

**Comment by sidtohan** [comment]
@hs05june i have added the flex start alignment to the required areas. Could you please have a look at this whenever possible and suggest any improvements? 
Thanks.

**Comment by Chadha93** [comment]
@sidtohan  Let's discuss this on the Meshery Dev call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#) if you would. :)

**Comment by sidtohan** [comment]
> @sidtohan  Let's discuss this on the Meshery Dev call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#) if you would. :)

Yes sure, but I seem to be unable to edit this. Could you approve my edit access for my mail siddhant.tohan@gmail.com?

**Comment by Chadha93** [comment]
> > @sidtohan  Let's discuss this on the Meshery Dev call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#) if you would. :)
> 
> Yes sure, but I seem to be unable to edit this. Could you approve my edit access for my mail [siddhant.tohan@gmail.com](mailto:siddhant.tohan@gmail.com)? @Chadha93

@sidtohan Please fill this form to access - https://layer5.io/newcomers. You can add your items as suggestions.

**Comment by sidtohan** [comment]
> > > @sidtohan  Let's discuss this on the Meshery Dev call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#) if you would. :)
> > 
> > Yes sure, but I seem to be unable to edit this. Could you approve my edit access for my mail [siddhant.tohan@gmail.com](mailto:siddhant.tohan@gmail.com)? @Chadha93
> 
> @sidtohan Please fill this form to access - https://layer5.io/newcomers. You can add your items as suggestions. 

Well the thing is I filled the form, but I used a non Gmail address which I use for development related work. I can fill the form again using my gmail address, but would that cause a problem?

**Comment by Chadha93** [comment]
@sidtohan Please add your agenda as suggestions.

**Comment by sidtohan** [comment]
@Chadha93 I am unable to add any suggestions as it also requires edit access. Sorry for the inconvenience but what should be done in this situation? If it helps, the email address I entered in the newcomers form is siddhant.tohan.in@protonmail.com

**Review by hs05june — APPROVED** [review]

**Review by Chadha93 — APPROVED** [review]

**Pull request merged**
