### PR TITLE
Design Panel Metrics Changes

### PR DESCRIPTION
**Pull request by Harshit-Dandriyal**
Signed-off-by: Harshit Dandriyal <56961488+Harshit-Dandriyal@users.noreply.github.com>

**Description**

Screenshot from 2022-09-01 23-45-47

Screenshot from 2022-09-01 23-45-35
.png)

Screenshot from 2022-09-01 23-45-17

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — CHANGES_REQUESTED** [review]
Revisit the description provided in the task. Title bar needs an update.

**Comment by leecalcote** [comment]
@Harshit-Dandriyal there's an accidental go submodule that has snuck in here. // @alphaX86 

@asubedy be aware of this submodule regarding the open wrk2 issue. // @EleisonC @gyohuangxin

**Comment by Harshit-Dandriyal** [comment]
> Revisit the description provided in the task. Title bar needs an update.

Yes, It will be PR of meshery-extention, not here :)

**Comment by Harshit-Dandriyal** [comment]
> Revisit the description provided in the task. Title bar needs an update.

oops, missed that, coming in minute.

**Comment by leecalcote** [comment]
Thanks, @Harshit-Dandriyal. You'll need to remove the ```Submodule gowrk2 added at aabd83```, too.

[cmd/gowrk2](https://github.com/meshery/meshery/pull/6158#diff-b7718f7aa3ff1aebe7af569867750505548ae111282afc43df9941bbdd6c354f)

**Comment by Harshit-Dandriyal** [comment]
> Thanks, @Harshit-Dandriyal. You'll need to remove the `Submodule gowrk2 added at aabd83`, too.
> 
> [cmd/gowrk2](https://github.com/meshery/meshery/pull/6158#diff-b7718f7aa3ff1aebe7af569867750505548ae111282afc43df9941bbdd6c354f)



> Thanks, @Harshit-Dandriyal. You'll need to remove the `Submodule gowrk2 added at aabd83`, too.
> 
> [cmd/gowrk2](https://github.com/meshery/meshery/pull/6158#diff-b7718f7aa3ff1aebe7af569867750505548ae111282afc43df9941bbdd6c354f)

sorted :+1:

**Comment by Harshit-Dandriyal** [comment]
Screenshot from 2022-09-02 00-23-18

We also have that hover animation on close.

**Review by leecalcote — APPROVED** [review]

**Comment by leecalcote** [comment]
thanks

**Comment by alphaX86** [comment]
> @Harshit-Dandriyal there's an accidental go submodule that has snuck in here. // @alphaX86
> 
> @asubedy be aware of this submodule regarding the open wrk2 issue. // @EleisonC @gyohuangxin

🥶 existing repo users need to remove that module manually, this is a problem in git submodules even if it's location changed

**Pull request merged**
