### PR TITLE
Migrated class based MesherySettings component to functional component.

### LINKED ISSUE #12698: [UI] Migrate MesherySettings Component to use MUI v5 Styling and Sistent Component
### Current Behavior
This MesherySettings Component uses MUI v4's styling and is a class component. These need to be updated for improved performance and consistency.

### Desired Behavior
migrate class-based component to a functional use [Sistent](https://github.com/layer5io/sistent) components for MUI v4 to MUI v5 migration

Sistent is our design system that uses MUI v5, you can also refer to this [doc](https://docs.meshery.io/project/contributing/contributing-ui-sistent) to understand how to use Sistent.

Update the class component to functional component.

### Acceptance Tests

The component must be updated without introducing any breaking changes in functionality or theming across all instances where it is used.

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by Pratik-050**
**Notes for Reviewers**

- This PR fixes #12698
Migrates existing class component to functional component.

https://github.com/user-attachments/assets/e85583a6-94ce-4dda-87b1-5ce1c3e913ff

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Pratik-050** [comment]
Hello @SAHU-01 here's the PR for the same as we discussed. Thanks!

**Comment by yash37158** [comment]
Thank you @Pratik-050 for migrating the component to a functional one, I have noticed the update didn’t fully implement Sistent components (MUI v5). Could you revisit this and align it with our design system? You can check this [PR](https://github.com/meshery/meshery/pull/11974) for guidance.

**Comment by leecalcote** [comment]
Thanks for including a screen recording! 👍

**Comment by Pratik-050** [comment]
> Thank you @Pratik-050 for migrating the component to a functional one, I have noticed the update didn’t fully implement Sistent components (MUI v5). Could you revisit this and align it with our design system? You can check this [PR](https://github.com/meshery/meshery/pull/11974) for guidance.

Hello @yash37158 I've discussed with @SAHU-01 and I was only doing the component migration the sistent migration will be done by her. Thanks for pointing out though!

**Review by SAHU-01 — COMMENTED** [review]
Thanks for this one @Pratik-050 , it looks good to me.

**Pull request merged**
