### PR TITLE
fix logo issue with dark mode

### PR DESCRIPTION
**Pull request by Shivam164**
**Notes for Reviewers**

This PR fixes the issue mentioned in https://github.com/meshery/meshery/issues/7154

Instead of a single image. I have added two images as done in the Navigator section.

### Screenshot
Screenshot from 2023-02-25 10-37-37

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by thisiskaransgit** [comment]
PTAL  @Abhishek-kumar09, @Chadha93

**Review by chinu-anand — DISMISSED** [review]
Thanks @Shivam164, that looks good.

**Review by thisiskaransgit — APPROVED** [review]

**Review by leecalcote — COMMENTED** [review]
How is this accounting for the user's setting of light mode vs dark mode?

**Comment by Shivam164** [comment]
Hey @leecalcote, I looked in the Navigator section for this and found out that the image used there was working well with the dark mode and light mode. So I implemented the same here.
[Navigator Section code](https://github.com/meshery/meshery/blob/7c46ed6697c48d19709da626e8bf9103a6ef631d/ui/components/Navigator.js#L1087)

**Comment by leecalcote** [comment]
Thank you, @Shivam164. While you're in here, can we get some theme coloring assigned to the hyperlink, too?

**Comment by Shivam164** [comment]
> Thank you, @Shivam164. While you're in here, can we get some theme coloring assigned to the hyperlink, too?

@leecalcote  Yeah, I will do that.

**Comment by parmishh** [comment]
@leecalcote I have solved the hyperlink color issue in Dark mode and made a corresponding issue regarding that at 
#7265
 could you please assign me so that I can do the PR.
It looks like this now
update

**Pull request merged**
