### PR TITLE
[CI] Fix release drafter

### PR DESCRIPTION
**Pull request by DelusionalOptimist**
Signed-off-by: Rudraksh Pareek <rudrakshpareek3601@gmail.com>

**Description**
This PR hopefully fixes #2612 

**Notes for Reviewers and Maintainers**
Publish release notes docs whenever a new release is published. 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by ramrodo — DISMISSED** [review]
Great! Hoping it works :)

**Comment by DelusionalOptimist** [comment]
No @ramrodo it won't work properly. I found later that it might mess up with some stuff. I need to do some more testing.

**Don't Merge It Yet**

**Comment by leecalcote** [comment]
Are we using the term "lazy" synonymously with "smart"?

**Comment by leecalcote** [comment]
We were bit again by the missing automation for pushing the .md file on release in v0.5.39.

**Comment by leecalcote** [comment]
Task linked: [CU-4hbkt7 Release drafter](https://app.clickup.com/t/4hbkt7)

**Review by leecalcote — APPROVED** [review]
The simple bird gets the worm.

**Pull request merged**
