### PR TITLE
Channel command update

### PR DESCRIPTION
**Pull request by Maxgit3**
**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.
 

Updating Channel Message to include message if user already subscribed to edge or stable channel  issue #2128

### CODE REVIEW

**Review by leecalcote — CHANGES_REQUESTED** [review]
Thank you, @Maxgit3. Will you merge latest changes from `master` into your remote branch and update?

**Comment by leecalcote** [comment]
@SudhanAruna you might have a review here...

**Comment by SudhanAruna** [comment]
> @SudhanAruna you might have a review here...

@leecalcote Sure, I'll check it

**Comment by Maxgit3** [comment]
@leecalcote sure I can merge updates

**Comment by anirudhjain75** [comment]
Hey, What does this entain ? @Maxgit3 @leecalcote

**Comment by Maxgit3** [comment]
https://github.com/layer5io/meshery/issues/2128#issue-772969739   the command "mesheryctl system channel"  should tell the user what channel they are subscribed to.  @anirudhjain75   I am not familiar with the review process for meshery.

**Comment by anirudhjain75** [comment]
Hey @Maxgit3 , I am already working on the PR that entails this. We have changed the architecture a bit which made me re-implement the channel command. To prevent duplicate work, please assign yourself the issue incase you are interested to work on it. @leecalcote What should we do in this case ?

**Comment by leecalcote** [comment]
@anirudhjain75, thanks for calling this out. @Maxgit3, the task of making all `mesheryctl system` commands `context`-aware has turned into something much larger, impacting thinking and design. I'll ping you in Slack now to catch up and get you settled.

**Comment by Maxgit3** [comment]
@leecalcote ok thanks.  I'll join slack.

**Comment by leecalcote** [comment]
@Maxgit3 good, good, good. 👍

**Comment by leecalcote** [comment]
Hi @Maxgit3, we very much appreciate your engagement here. It's great to see you making waves in other areas of the project already. 👍 

Considering the other PR covering this functionality, do we have your permission to close this particular PR? Also, please say hi to @anirudhjain75 and @navendu-pottekkat in Slack. Both of them are tracking feature epics for enhancements to `mesheryctl`. They are sure to warmly engage you.

**Comment by Maxgit3** [comment]
@leecalcote sure that's fine to close.  was interesting to see how cli gets built in go

**Comment by leecalcote** [comment]
Oh, that's good. Ok, on to the next challenge. :)

**Pull request closed without merging**
