### PR TITLE
[Build] UI dependency updates

### PR DESCRIPTION
**Pull request by leecalcote**
**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by warunicorn19** [comment]
@leecalcote some merge conflicts to address.

**Comment by leecalcote** [comment]
Thank you, @warunicorn19.  Updated.

**Review by navendu-pottekkat — APPROVED** [review]
LGTM

**Comment by navendu-pottekkat** [comment]
@meshery/meshery-ui-contributors Could you check and merge this? There is a failing UI integration test. IDK if this has already been fixed.

**Review by Abhishek-kumar09 — APPROVED** [review]

**Comment by leecalcote** [comment]
I think one of the dependencies might be causing an issue.

**Pull request closed without merging**
