### PR TITLE
More settings options in remote provider tab

### PR DESCRIPTION
**Pull request by theBeginner86**
**Description**
This is a supporting PR for expanding more settings options in the remote provider tab

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
@theBeginner86 would you like to close this out or keep open in order to land a generic approach?

**Comment by theBeginner86** [comment]
@leecalcote I've done that generic approach. I just need to clean up and send the commits. Will do it by evening.

**Comment by theBeginner86** [comment]
This PR is ready for review. // @leecalcote

**Comment by leecalcote** [comment]
Thanks, @theBeginner86. Still accurate to characterize this generic extension point as a single component extension point?

**Comment by leecalcote** [comment]
Confirming behavior: Does the Remote Provider menu tab show when users have chosen the Local Provider "None"?

**Comment by theBeginner86** [comment]
> Thanks, @theBeginner86. Still accurate to characterize this generic extension point as a single component extension point?

@leecalcote 
Yeah, I've tested it and things work as they were initially.
Please check the supporting PR on meshery-extension repo which I just created. That could add more context to the changes I made here.

**Comment by theBeginner86** [comment]
> Confirming behavior: Does the Remote Provider menu tab show when users have chosen the Local Provider "None"?

No it doesn't loads up in that case. I think in accordance to the initial architecture those settings would only load up with `Meshery` provider. Because we are persisting them in the meshery-cloud so we want them to be signed in with `Meshery` provider.
But to confirm, do we need that tab in `None` provider as well?

**Comment by leecalcote** [comment]
Thanks for confirming. The current behavior is ideal. Good stuff.

**Pull request merged**
