### PR TITLE
Add the MeshSync page in spanish

### LINKED ISSUE #4352: [Docs] Create/Update the MeshSync page in spanish, that goes in the CONCEPT section in the spanish docs site
#### Current State
The spanish docs site doesn't have the MeshSync page translation to spanish 
#### Desired State
The spanish docs site has the MeshSync page translated to spanish in the CONCEPT section 
---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by chal-gro**
Signed-off-by: Christian Alexis Castro Guerrero <christian.alexis.gro@gmail.com>

**Description**

This PR fixes #4352

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 7bb5fdc8bac97f017e77d83534633202cb3b8db3 at: https://6161fdeb367fbb909a585cc5--meshery-docs-preview.netlify.app

**Comment by alonsolopezr** [comment]
The es/concepts/architecture/meshsync looks very good! well Done! 
but, you edited the ENGLISH INDEX docs/page/index.md, instead of editing the docs/page/es/index.md page.

The spanish pages must be shown only in the docs/page/es/index.md page.

Just correct this and expect the approval 👍🏼

**Comment by l5io** [comment]
🚀 Preview for commit 668bf406a2a93b77e8640806dc649ed4d0aef925 at: https://616229f23311c3fc7d34030e--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit ff8eab9179858e08ff0681cc82f0fc9a1a305f99 at: https://61622e67a3152019752a46f0--meshery-docs-preview.netlify.app

**Pull request merged**
