### PR TITLE
[Docs] README - Add NGINX Service Mesh adapter

### LINKED ISSUE #1729: [Docs] README - Add NGINX Service Mesh adapter
**Current Behavior**
NGINX Service Mesh is missing. A new adapter has been created - https://github.com/layer5io/meshery-nginx-sm

**Desired Behavior**
- Meshery's readme should have NGINX Service Mesh adapter listed as an alpha adapter.
- use the Nginx service mesh logo recently included in the https://layer5.io/landscape

Screen Shot 2020-10-22 at 4 33 34 PM

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

### PR DESCRIPTION
**Pull request by unkletayo**
Signed-off-by: Adetayo <akinsanyaadetayo7@gmail.com>

**Description**
This commits adds NGINX Service Mesh adapter listed as an alpha adapter
This commit also uses the Nginx service mesh logo recently included in the https://layer5.io/landscape

This PR fixes #1729 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — CHANGES_REQUESTED** [review]
Hi @UnkleTayo, will you create a copy of the logo and place in this repo under the /docs/..assets../..img../..readme?

Cross-linked resources often find themselves broken, because remote dependencies go untracked.

**Comment by leecalcote** [comment]
Thank you for jumping in here, @UnkleTayo 👍

**Comment by UnkleTayo** [comment]
Hi, @leecalcote Thank you for your response, I will go ahead and create the image and make a new Pull request

**Review by leecalcote — APPROVED** [review]
Very good. This is just what is needed, @UnkleTayo. 👍

**Comment by leecalcote** [comment]
🎯@UnkleTayo! 🎈

**Pull request merged**
