### PR TITLE
removed installing mesheryctl from FAQ subheading

### PR DESCRIPTION
**Pull request by warunicorn19**
Signed-off-by: Aditya Chaterjee <speak2adi@gmail.com>

**Description**
Removed the mesheryctl subheading from the FAQ section.
This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 7c6223420c86ef67ccb68a8221ceac75c7491da1 at: https://6120da9b0f70c9b465ba8045--meshery-docs-preview.netlify.app

**Review by sayantan1413 — APPROVED** [review]
Good catch @warunicorn19 😎

**Comment by warunicorn19** [comment]
Credit goes to @Meghana-12 😅, she pointed it out.

**Comment by sayantan1413** [comment]
Ah ! I see, It's a good team work. One catching the bugs and the other destroying it. 🐛 are going to die soon😍

**Review by leecalcote — APPROVED** [review]

**Pull request merged**
