### PR TITLE
[CI]: Relocated netlify script file

### LINKED ISSUE #3360: [CI] Relocate netlify script to /docs directory
@nehaLohia27 can we have this file https://github.com/meshery/meshery/blob/master/script.sh moved to the /docs directory? // @Nikhil-Ladha

_Originally posted by @leecalcote in https://github.com/meshery/meshery/discussions/3210#discussioncomment-944626_

### PR DESCRIPTION
**Pull request by shuklaritvik06**
Signed-off-by: Ritvik Shukla <ritvikshukla261@gmail.com>

**Description**

This PR fixes #3360 

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
@nehaLohia27, will you review?

**Comment by nehaLohia27** [comment]
Sure @leecalcote

**Review by nehaLohia27 — APPROVED** [review]

**Review by nehaLohia27 — APPROVED** [review]

**Comment by Nikhil-Ladha** [comment]
@includestdlibrary can you also update the workflow to reflect this change: 
https://github.com/meshery/meshery/blob/d81178e77ea21443679c2ea3279fbd2eba2e4a2a/.github/workflows/build-and-preview-site.yml#L26

**Comment by nehaLohia27** [comment]
@includestdlibrary I have created new PR #3367 to fix the issue. The original PR is not complete fix. @leecalcote @Nikhil-Ladha Can we close this PR

**Comment by Nikhil-Ladha** [comment]
Thanks for the PR @includestdlibrary , but we are considering the other PR #3367 for this issue. Do take a look around and comment on issues which you want to work upon, and get it assigned to you before starting to work on it, so that there isn't any duplicate work for anyone :)

**Pull request closed without merging**
