### PR TITLE
[connections] Migrate K8sCtx to Connections

### PR DESCRIPTION
**Pull request by theBeginner86**
**Notes for Reviewers**

Migrates k8s_Contexts table to Connections Table.

This PR fixes #

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
@theBeginner86 does the adjoining remote provider PR include a new minimum compatibility version #?

**Review by leecalcote — CHANGES_REQUESTED** [review]
Branch build fails with:

```
# github.com/layer5io/meshery/server/models
../models/remote_provider.go:602:3: unknown field Metadata in struct literal of type ConnectionPayload
../models/remote_provider.go:606:2: err declared and not used
../models/remote_provider.go:648:1: missing return
make: *** [server] Error 1
```

**Comment by theBeginner86** [comment]
looking 👀

**Comment by theBeginner86** [comment]
https://github.com/meshery/meshery/assets/73700530/eaea9edb-f2f3-4f5f-af4d-457b908058c1

**Comment by theBeginner86** [comment]
Support for local provider is not included in this PR. 
Reason being that I realized, connections support it elf is not available currently for local provider and it will require a number of more changes. So, I'll take that in next PR.

**Pull request merged**
