### PR TITLE
Remove stale/demo test results

### PR DESCRIPTION
**Pull request by Revolyssup**
Signed-off-by: ashish <ashishjaitiwari15112000@gmail.com>

**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit e71535334151a1c34336fa5173c7d5266db82c32 at: https://61c1ae4d2d05403b94ed13c3--meshery-docs-preview.netlify.app

**Review by leecalcote — DISMISSED** [review]

**Comment by leecalcote** [comment]
@Revolyssup I checked out this branch, but didn't have any luck removing the conflict.

**Comment by l5io** [comment]
🚀 Preview for commit dd30587a919b47d7fa19d790c69c6e210d280a0c at: https://61cd58a00b7920d78b850746--meshery-docs-preview.netlify.app

**Comment by leecalcote** [comment]
Closing this out for now. Please reopen / re-delete any unwanted datafiles.

**Pull request closed without merging**
