### PR TITLE
Added the Correct Slack link in contributing.md

### LINKED ISSUE #1483: Iincorrect link to slack chat room on contributing.md [Docs]
**Current State:**
The link to the slack channel on contributing.md currently leads to the github 404 page as shown below:
issue
cause

**Desired State:**
The link should lead to the slack channel of layer5.io

---
**Contributor Resources**
- http://slack.layer5.io/

- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

### PR DESCRIPTION
**Pull request by akashgp09**
Signed-off-by: Akash Gupta <akashgp9@gmail.com>

**Description**
Added the correct link to slack chat room in contributing.md

This PR fixes #1483 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by shivaylamba — APPROVED** [review]
Thankyou for the contribution @akashgp09

**Review by UdokaVrede — APPROVED** [review]
@shivaylamba thanks for contributing to Layer5. You are doing great

**Comment by PluckyPrecious** [comment]
Welldone @akashgp09 🥳, what do you think about using `slack.layer5.io` instead? 🤔

**Comment by kushthedude** [comment]
Thank you for the contribution @akashgp09!

**Comment by akashgp09** [comment]
> Welldone @akashgp09 🥳, what do you think about using `slack.layer5.io` instead? 🤔

I did it already 😊.

**Pull request merged**
