### PR TITLE
[UI]: Table Pagination Fixed 

### LINKED ISSUE #7006: [UI]: MUI Datatable pagination and Rows Per Page is not working
#### Current Behavior

1. Wrong count of the rows in the data table
2. Pagination is not working
3. Rows Per Page changing feature is not working  

#### Desired Behavior

1. Count of the rows in the table should be shown correctly (90 instead of 2 in the below video)
2. Pagination should change the pages in the table 
3. Rows Per Page should change the number of rows in the table 

#### Screenshots/Logs
https://user-images.githubusercontent.com/78142732/216770745-9b61ceae-1707-444a-b985-ab6db97f18c2.mp4

#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Pop!_OS 22.04 LTS x86_64
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by anshkush92**
Signed-off-by: Ansh Singh anshkush92@gmail.com
**Notes for Reviewers**

This PR fixes #7006 

Fix Demonstration 

https://user-images.githubusercontent.com/78142732/216816233-a76f15e0-6b5b-432f-925c-d891593173eb.mp4

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Chadha93** [comment]
@anshkush92college  Let's discuss the update of this PR on the Meshery Dev call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#) if you would. :)

**Comment by anshkush92college** [comment]
> @anshkush92college Let's discuss the update of this PR on the Meshery Dev call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#) if you would. :)

I would love to add this, but I don't have edit access to the Meshery development meeting doc, and to be sure, it happens from 8:30 PM to 9:30 PM IST, right ?

**Review by Abhishek-kumar09 — COMMENTED** [review]
@anshkush92college Please remove the comments if you think your changes are  final.

**Comment by anshkush92college** [comment]
> @anshkush92college Please remove the comments if you think your changes are final.

Yes I will remove that, currently incorporating the changes that were discussed in the meshery dev call

**Comment by leecalcote** [comment]
@anshkush92college it's that time of the week again. Here are details to the Meshery Dev meeting: https://meet.layer5.io

**Comment by leecalcote** [comment]
Sign commits by following these instructions - https://github.com/meshery/meshery/pull/7009/checks?check_run_id=11372503548

**Comment by anshkush92college** [comment]
Sorry for the late reply, I had health issues 
I will start working on it as soon as my exams ends

**Comment by Chadha93** [comment]
@anshkush92college heads up. Merge conflicts.

**Comment by leecalcote** [comment]
PR abandoned.

**Pull request closed without merging**
