### PR TITLE
[Docs] Sort alphabetically and add windows to list

### PR DESCRIPTION
**Pull request by jack-champagne**
**Description**

This PR fixes the supported platforms menu in documentation tab by alphabetizing the options in ascending order and adding windows as a supported platform.

Please refer to Issue #1336 as this is what this commit intends to fix.
Also, this is my first PR ever/first OSS code contribution so I hope all looks well.

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Hi @jack-champagne! Thank you for this. It's so cool that we get to handle your first-ever open source contribution! 🎈 

The content of your changes looks great. There's a snag item that many snag on initially and that is signing-off on your commits.  To do so on this PR, you can execute these instructions - https://github.com/layer5io/meshery/pull/1338/checks?check_run_id=925248808

Here are instructions for [making signing an implicit activity while peforming a commit.](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)

**Comment by jack-champagne** [comment]
Thanks for your help! Hopefully that commit now has a proper signature.
For future reference, is making a branch for this small of a change encouraged in your opinion? Or could have it committed to master and did my PR off of that?

**Comment by leecalcote** [comment]
Yay, @jack-champagne! 🎈 Great question. Even though this is a small PR, yes, it's common convention to create a development branch for each PR. Often projects encourage a format like <username>/<issue-type>/<issue-number>. e.g., `jack-champagne/docs/1338`

Thank you for your efforts here. I welcome you to join the Layer5 community here - http://slack.layer5.io. It would be good to get you introduced to the broader community and its projects.

**Comment by leecalcote** [comment]
@jack-champagne, please add a star to this project, if you would be so kind - https://github.com/layer5io/meshery/stargazers

See you in Slack!

**Pull request merged**
