### PR TITLE
[Catalog] Support Unpublish Catalog Content

### PR DESCRIPTION
**Pull request by theBeginner86**
**Notes for Reviewers**

This PR adds support for Meshery users to unpublished a catalog item.
Only admins or curators are allowed this action.

Steps:
1. Updates the `visibility` from `published` to `private`
2. Removes the items from the https://meshery.io/catalog by calling a webhook to the [workflow](https://github.com/meshery/meshery.io/actions/workflows/delete-catalog.yml)

demo:

https://github.com/meshery/meshery/assets/73700530/5b75ef89-dcdb-4b77-8faa-5e3e64ec8544

This PR fixes #

Error message for non-admins or non-curators:

Screenshot 2023-06-08 at 3 16 14 AM

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit f9f31b66d4a663e55ea7562ea72231150d53a908 at: https://6480f9ee7fdf134a591bfaff--meshery-docs-preview.netlify.app

**Comment by theBeginner86** [comment]
_This PR also fixes a recent bug that removed GraphQL subscriptions from patterns page and removed catalog view preference._

**Comment by l5io** [comment]
🚀 Preview for commit d3cf744ed94606bab0c10086c359e48978f003e9 at: https://6482a2f2d2034314c425df45--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit f61443cf3658adbe252a08ce6dbf38537647664e at: https://648330fe617b4b10c8969110--meshery-docs-preview.netlify.app

**Comment by theBeginner86** [comment]
@Abhishek-kumar09 @MUzairS15 
Any objections here? ok to move forward here?

**Comment by l5io** [comment]
🚀 Preview for commit c53dd19425fd5abbaf33a560f405b3346819bd0d at: https://6487224a58602d366e8b9fb1--meshery-docs-preview.netlify.app

**Pull request merged**
