### PR TITLE
[UI] Finalise Provider-UI Lint

### LINKED ISSUE #696: Set up ESLint rules and Lint checker tests
Set up ESLint and Linting tests in CI for quality of code.

### PR DESCRIPTION
**Pull request by kushthedude**
Signed-off-by: kushthedude <kushthedude@gmail.com>

Fixes #696

- Finalises ESlint for Provider-UI.

### CODE REVIEW

**Comment by kushthedude** [comment]
Review after #797

**Comment by Nikhil-Ladha** [comment]
LGTM!

**Comment by leecalcote** [comment]
So far so good here, I think, but more left to tie-off, right?

**Comment by kushthedude** [comment]
Yeah some parts are left off, completing by today!

**Comment by kushthedude** [comment]
@leecalcote It is good to go now !

**Pull request merged**
