### PR TITLE
Integration sheet models added: whereabouts, victoria-metrics-k8s-stack, velero-s3-deployment, vela-workflow

### PR DESCRIPTION
**Pull request by SAHU-01**
**Notes for Reviewers**

This PR fixes [#5898](https://github.com/layer5io/layer5/issues/5898)

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
@Jougan-0 the `update` command only deals with the latest component version... @SAHU-01, you updated the older manually, and did not use `mesheryctl` for this, right?

**Comment by SAHU-01** [comment]
> @Jougan-0 the `update` command only deals with the latest component version... @SAHU-01, you updated the older manually, and did not use `mesheryctl` for this, right?

I used the following `mesheryctl` commands for this:

`./mesheryctl registry generate --spreadsheet-id "1ldfTx29vRmPOz95DJLyR5KeClHtxeYoEqaXpkKS3bsA" --spreadsheet-cred  $cred --model "model name"`

`./mesheryctl registry update -i ../server/meshmodel --spreadsheet-id "spreadsheet-id"  --spreadsheet-cred $cred`

**Comment by leecalcote** [comment]
I suspect this PR might be out of date and no longer necessary. Is that the case, @SAHU-01 @Jougan-0?

**Comment by SAHU-01** [comment]
> I suspect this PR might be out of date and no longer necessary. Is that the case, @SAHU-01 @Jougan-0?

Yes, this is no longer required, I've added these on the main sheet, it will reflect on another PR tommorow

**Pull request closed without merging**
