### PR TITLE
[Extension] Add Collaborator Extension Point

### PR DESCRIPTION
**Pull request by senali-d**
**Notes for Reviewers**

This PR fixes #

This PR:
1. Adds new Collaborator Extension Point
2. Moves the prefs for un/activating Collaboration into the UserPrefs Extension so that its visible in Meshery UI at (/user/preferences)

Screenshot 2023-08-09 at 6 55 05 PM

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — CHANGES_REQUESTED** [review]
@senali-d, please understand that what you are creating is an extension point. The actual component will be remotely created, published, and loaded upon user sign-in. Please refer to other UI extension points as an example.

**Comment by leecalcote** [comment]
> @senali-d, please understand that what you are creating is an extension point. The actual component will be remotely created, published, and loaded upon user sign-in. Please refer to other UI extension points as an example.

Have you reviewed the other UI extension points, @senali-d? Are you familiar with the approach - https://docs.meshery.io/extensibility/ui

**Comment by senali-d** [comment]
@leecalcote Yes I'm reviewing other UI extension points and try to figure out it.

**Comment by theBeginner86** [comment]
This PR is ready from my end

**Comment by theBeginner86** [comment]
@senali-d 
Once you are done with updating the loading animation component then lets merge this 👍

**Comment by theBeginner86** [comment]
Docs has been updated for this new Collaborator Extension Point

**Comment by senali-d** [comment]
@theBeginner86 Loading animation updated.

**Comment by theBeginner86** [comment]
> @theBeginner86 Loading animation updated.

Great!
Have you pushed the changes? I don't seem to see any new commit 😅

**Comment by l5io** [comment]
🚀 Preview for commit dcc2a34dd13d823917aa1cd9908122bee7da0c76 at: https://64d3f7eeafa90b0096ed4b81--meshery-docs-preview.netlify.app

**Comment by senali-d** [comment]
Oh I miss it. Pushed now. 😅

**Review by theBeginner86 — APPROVED** [review]

**Pull request merged**
