### PR TITLE
feat: rjsf dependency upgrade to v5

### PR DESCRIPTION
**Pull request by harkiratsm**
Signed-off-by: harkiratsm <multaniharry714@gmail.com>

**Notes for Reviewers**

This PR fixes #

Todo - 
- [x] Verify that patches are required or not, with some detailed explanation.
- [x] Fix the validation problems with rjsf.

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by harkiratsm** [comment]
@Abhishek-kumar09 the ui-build is failing due to patch.

**Comment by Abhishek-kumar09** [comment]
I will look into it today, @harkiratsm

**Comment by Abhishek-kumar09** [comment]
I'll push some final changes and test it to get it merged

**Comment by Abhishek-kumar09** [comment]
Docker build should pass now.

**Comment by leecalcote** [comment]
It does. 👍

**Pull request merged**
