### PR TITLE
[cli][system][fix]: return error if detected while creating manifests folder

### PR DESCRIPTION
**Pull request by VihasMakwana**
**Notes for Reviewers**
We should pass the error to the caller instead of returning nil as part of best practices

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
@VihasMakwana, thank you. It looks like we have a couple of residual, lint, check failures, unrelated to this PR, but that I wondered if you might have a look at...

Separately, will you run the commands on this page in order to sign your commits? -- https://github.com/meshery/meshery/pull/9469/checks?check_run_id=19070539654

**Review by leecalcote — APPROVED** [review]
Changes look good to me. Thanks much, @VihasMakwana

**Review by zakisk — APPROVED** [review]

**Comment by zakisk** [comment]
@leecalcote LGTM!

**Comment by VihasMakwana** [comment]
@leecalcote sure I will fix the CI failures. Thanks for your approval!
I will sign the commit properly and let you know.

**Comment by leecalcote** [comment]
Whoo-hoo, @VihasMakwana! 🎈

**Pull request merged**
