### PR TITLE
Added animated terminal in meshery docs

### PR DESCRIPTION
**Pull request by sourav-sharma7**
Signed-off-by: Sourav Sharma souravsharma1321@gmail.com
**Description**
 Added animated terminal for meshery docs 
This PR fixes # 734 of the meshery io site

**Notes for Reviewers**
 DO NOT MERGE
This is a draft pr need suggestion about the styling

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by sourav-sharma7** [comment]
This pr fixes issue #734 of the meshery io repo

**Review by alphaX86 — CHANGES_REQUESTED** [review]
@sourav-sharma7 could you rename the css and js files as "terminal" instead of "termynal"? :)

**Comment by l5io** [comment]
🚀 Preview for commit 8bf9b2f98ff4e38fff05890275372924b00c046f at: https://62ce6a10d8e5fd4b93b6353c--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit dd96acbaf109cb66fb2c91c9cdd9d453c7daa3c7 at: https://62ce71e4e80ac64d5dd997b2--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 11db19df15b0e05797bede768b8f82c4e93b7ce0 at: https://62ce85a64a94a15d99fcbf57--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 0174707a978ba921fdfd9ef54324ba4ef613edaf at: https://62ce86b67028835ef6c8e9a2--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 43496d8a71d4b595edb4e334e42406b9a35d6d34 at: https://62ce9db8b169b37366919d09--meshery-docs-preview.netlify.app

**Pull request closed without merging**
