### PR TITLE
docker extension user profile section refactored

### PR DESCRIPTION
**Pull request by Ambareen09**
**Notes for Reviewers**

This PR fixes subtask of #6255 

Before :
Screenshot from 2023-04-25 20-52-45

After: 
Screenshot from 2023-04-25 20-51-24

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Review by parmishh — APPROVED** [review]

**Comment by parmishh** [comment]
Great work 👏

**Comment by Ambareen09** [comment]
> Great work clap

Converting this from draft to open if it's alright then?

**Comment by Chadha93** [comment]
@Ambareen09  Let's discuss this on the Meshery Dev call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#) if you would. :)

**Comment by Ambareen09** [comment]
Knock, knock @leecalcote

**Comment by leecalcote** [comment]
I just built this version of the extension. I'm testing now...

**Comment by leecalcote** [comment]
Great work, @Ambareen09 💯

**Pull request merged**
