### PR TITLE
All releases between v0.4.22 and v0.4.4 added

### PR DESCRIPTION
**Pull request by ezioishan**
Signed-off-by: Ishan Sourav <ishansourav7@gmail.com>

**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by ezioishan** [comment]
why "Meshery / golangci-lint (pull_request)" this test is failing, i haven't modified any code? @leecalcote

**Review by leecalcote — APPROVED** [review]
Excellent! You nailed it, @ezioishan! 👍

**Comment by ezioishan** [comment]
Thank you sir!

**Comment by leecalcote** [comment]
@kushthedude do you know if this is just GitHub having difficulty or do we have an issue to address here? https://github.com/layer5io/meshery/pull/1943/checks?check_run_id=1408354786

**Comment by kushthedude** [comment]
> @kushthedude do you know if this is just GitHub having difficulty or do we have an issue to address here? https://github.com/layer5io/meshery/pull/1943/checks?check_run_id=1408354786

Golangci-lint needs to be updated 🤷

**Comment by leecalcote** [comment]
Whoo-hoo, @ezioishan! 🎈

**Pull request merged**
