### PR TITLE
fix typo in summary

### PR DESCRIPTION
**Pull request by shivamganwani**
Just a small typo fix in summary of a restful api

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit a6f432e91e246bcb3da8c337c382e76f04a1a5be at: https://644c2f0a847cab0cb8ed183c--meshery-docs-preview.netlify.app

**Review by Abhishek-kumar09 — APPROVED** [review]
Looks Good to Me

**Comment by shivamganwani** [comment]
What about the failed integration and end to end @Abhishek-kumar09 
Its timeout in end to end so no worries I guess 
What about the integration (cant understand this one)

**Comment by Abhishek-kumar09** [comment]
The failing tests is being worked on via https://github.com/meshery/meshery/issues/7623 and https://github.com/meshery/meshery/issues/7622. // @Freedisch @theBeginner86 @MarioArriaga92

**Comment by shivamganwani** [comment]
Cool then, next step is to merge right?
Sorry this is my first time, so not familiar with the process.

**Comment by senali-d** [comment]
#7625

**Pull request merged**
