### PR TITLE
Add eslint to enable no-undef errors

### PR DESCRIPTION
**Pull request by Abhishek-kumar09**
Signed-off-by: Abhishek kr <abhimait1909@gmail.com>

**Description**
In reponse of the Postmortem done that resulted into undef error later crashing UI.

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Abhishek-kumar09** [comment]
I will need some support to tie off this issue completely, since there are around 200 places in the UI, where variables are not defined but they are called, that may result in crash under special situations. // @leecalcote @Chadha93 @Harshit-Dandriyal @warunicorn19 
Screenshot 2022-08-02 at 4 47 40 PM

**Comment by Abhishek-kumar09** [comment]
Boiled to 19 Now.
Screenshot 2022-08-02 at 4 58 46 PM

**Comment by Abhishek-kumar09** [comment]
Additonally, lets add a eslint  github action to know it first hand.

**Comment by Abhishek-kumar09** [comment]
These eslint configurations being in off states scares me now:
```
    "react/jsx-key" : "off",
    "no-dupe-keys" : "off",
```

**Comment by leecalcote** [comment]
@harkiratsm your help here would be great.

**Comment by warunicorn19** [comment]
I can help too ✋

**Comment by Harshit-Dandriyal** [comment]
I would love to help here.. Count me in :hand:

**Comment by Abhishek-kumar09** [comment]
Thank you everyone. You can make changes to this branch with opening a PR against my branch i.e. [Abhishek-kumar09:Abhi/fix-crash](https://github.com/Abhishek-kumar09/meshery/tree/Abhi/fix-crash).

**Comment by harkiratsm** [comment]
Sure @leecalcote  I would definitely help 😄

**Comment by leecalcote** [comment]
Thank you, @harkiratsm

**Pull request merged**
