### PR TITLE
Krishna2323/enhancement/docs website

### PR DESCRIPTION
**Pull request by Krishna2323**
**Notes for Reviewers**
Enhancing the docs website.
This PR fixes #

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit a0809d9ddcca5dcd72073bf6c251349dcdab47d8 at: https://638eb638eae3365062f1169f--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 40b5cd4ad1ef4162a06e3e8b9885b5a40b9c02ac at: https://638fd87bd6e6f2047be5e8e2--meshery-docs-preview.netlify.app

**Comment by leecalcote** [comment]
In Safari and Chrome:

Screenshot 2022-12-07 at 7 43 50 AM

**Comment by l5io** [comment]
🚀 Preview for commit 8fc31bdb14117e197d38fe38805c86ed2314eee4 at: https://6391076ca54a18122074a342--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit e60fdfa4b30626ac766b415933342cf294880cf3 at: https://63910a2cfef4f0170afb8767--meshery-docs-preview.netlify.app

**Comment by leecalcote** [comment]
Progress. The main section remains. I'm adding the `pr/draft` label until you're ready for review, @Krishna2323

**Comment by l5io** [comment]
🚀 Preview for commit 9621b4e9e27cd99f382e76864b4d3d9350e7a4ef at: https://63956af0721fc33de024712e--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 3ac0d69cb275cea0e52e810b306bd22ee1047dad at: https://63956c421604bf3e8cba3b61--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 91f519b3de7f344802a67331efc48184610beb3f at: https://639570a4721fc3409c247163--meshery-docs-preview.netlify.app

**Comment by leecalcote** [comment]
Very pretty so far.

**Comment by l5io** [comment]
🚀 Preview for commit 3122423504d11e02d908915eb7e1f9d1042923ed at: https://6396bee93860053d04f3e790--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 2f4066cb3ae0bcdc5326838e2e217f8a5df3de7b at: https://6396caae07648c42041005c0--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 5ac49d63c7e312610f8e4d183189f5d367cecfc1 at: https://6396e37438600557d5f3ea22--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 350da58f9fffe85d9610590842eaa3dd7311049c at: https://6398039f1983413801a6df31--meshery-docs-preview.netlify.app

**Comment by leecalcote** [comment]
@Krishna2323 the linear gradients that I added will need to be lightened up order to match with the subtle TOC sidebar gradient.

**Comment by l5io** [comment]
🚀 Preview for commit f5896f9614b21d93457bd8414f9af06fb78ae57c at: https://6399266b1de58d54a41f7429--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 6bd0622c1c112f4effe98be0e6ab315374f7064a at: https://639934ab36325566fe39d3ab--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 79ce16cf167fb62e2fefc35700b3c7ea1cdbb264 at: https://6399381374ad245e4934eb69--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 9745e1a4b6c97f23ec1c7bba5c7aef825bc7b36d at: https://639abdcf6c97e720474e6764--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 49a47ab3844c1305d82c94aef2673fc85945658f at: https://639aec95d96ee554a6e7e698--meshery-docs-preview.netlify.app

**Comment by leecalcote** [comment]
Dark mode is coming along nicely.

**Comment by leecalcote** [comment]
@tinniaru3005 you might want to have another look and offer review.

**Comment by l5io** [comment]
🚀 Preview for commit 1c28ac4024b10422069b82cbbbc668bae861f59d at: https://639edc90e97dd35a08989e4f--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit c83d9b9f8413d3908a5a19ff8e31380b8d0e79f1 at: https://639ee1d9c1082f5a6ad1c3c6--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 369031e6c63fda0c5f5760d7916ecfc278340aa8 at: https://639ee513580637601623455d--meshery-docs-preview.netlify.app

**Comment by leecalcote** [comment]
@Krishna2323 the lefthand navigation bar is too quick to disappear.

The icon used to show/hide the sidebar needs changed to a pullout tab.

**Comment by Chadha93** [comment]
@Krishna2323 Will you please make an update here?

**Comment by leecalcote** [comment]
Uh-oh, some merge conflicts have cropped up here.

**Comment by GaganpreetKaurKalsi** [comment]
> Uh-oh, some merge conflicts have cropped up here.

Will fix it by tomorrow.

**Comment by gurpreet-legend** [comment]
@Krishna2323 , I might need to have a write permission for this branch as per @leecalcote 

Will start working on:
- Pull tab on the left hand sidebar
- Increase the size of font on smaller screen widths or to make it more dynamic

**Comment by l5io** [comment]
🚀 Preview for commit ed4211cbc2ade4a9ede36899b1f764ef64a6d7d6 at: https://63dc1c19b3a5413577843f63--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit afbe43c4bd3f94486da7432db76552fe17a78746 at: https://63dd67a19464f000aeeb1f5f--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit c864f6ce540a534b99058941edf14adc0ee04e44 at: https://63dd92a5b44d3016a7234f40--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 5dfd29b3d10c9d61bfa317e2ad9766ecea436b2a at: https://63dd974fe125e419a3726c66--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 2ab92886e52a5ab7320664eba2fe268e36acaf76 at: https://63e0f7ad2f2b735f228b5fde--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 767079617eeb04429281284c827d8e398581dcda at: https://63e1475db2d7e70357343c82--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 7f2889dee6596dd0e96f587ab61cd723d161e641 at: https://63e159990c20500d26576e3b--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 2e0b41d59523a0e814c848e0c0fa1e7ad3279e4d at: https://63e15ca85fe46c0feeea52cf--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 8d286d2d672487b6f4eda85ef53c7be87650426e at: https://63e15faa5fdece005faf4fea--meshery-docs-preview.netlify.app

**Review by Chadha93 — APPROVED** [review]
LGTM. Great work @GaganpreetKaurKalsi

**Pull request merged**
