### PR TITLE
[DOCS] Initialized Summary table for Compatibility Matrix

### LINKED ISSUE #2515: [Docs] Compatibility Matrix
**Current State:**
Integrations are a key aspect of the value Meshery offers to users. Details of the compatibility of Meshery and its components are available in various places in Meshery Docs (in Jekyll datafiles). Bringing this information together into a single location in a compatibility matrix (maybe multiple tables) will benefit users.

**Desired State:**
Create a visual compatibility matrix showing Meshery and `mesheryctl`'s compatibility with various systems. Include the following information:

- Operating System (if available - reuse existing information)
- Kuberenetes platform (reuse existing information)
- Service meshes (reuse existing information)

Two tables may be necessary to show supported platforms for Meshery and for `mesheryctl`.

**Examples**
Screen Shot 2021-03-09 at 7 39 49 AM

Link to [VMware compatibility matrix](https://interopmatrix.vmware.com/#/Interoperability?isHideGenSupported=true&isHideTechSupported=true&isHideCompatible=false&isHideIncompatible=false&isHideNTCompatible=false&isHideNotSupported=true&isCollection=false&col=2,5088,4276,3496,3457,3222,2862,2736,3364,2732,2332,2132,2136,998,695,431,792,611,578,508,1034,442,444,448,254,1035,462,392,252,140,2981,194,172,38,242,173,37,36,35&row=0,)

#### Child Issues

- [ ] [CI] Centralize Meshery Adapter Integration Test Results #4741 

---
**Contributor Resources**
- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

### PR DESCRIPTION
**Pull request by asubedy**
**Description**

This PR will, give us an overall compatibility of different adapters.

This PR fixes #2515 

**Notes for Reviewers**
Works left:
1. Filter overall compatibility according to Meshery Server version
2. Calculate the overall server version and assign suitable color code to it

Question:
If we are displaying the adapter compatibility according to the Meshery Server version, there will be adapters for which we don't haven test for a particular version, so what should we do in that case? 

My idea:
We display all the adapter in all cases and if the adapter does not have any test on a particular Meshery Server version, we show a gray color on the overall compatibility field with text : No test run for this server version.

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 0bf5dca8c63703d9e69adb2aa56062c3f7672589 at: https://62617223a81b457f8a85d334--meshery-docs-preview.netlify.app

**Review by alphaX86 — CHANGES_REQUESTED** [review]
We might need k8s version too as a column

**Comment by alphaX86** [comment]
image

Also, we might need text in the color boxes (stable/not stable)

**Comment by alphaX86** [comment]
Other than that, great!

**Comment by asubedy** [comment]
> image
> 
> Also, we might need text in the color boxes (stable/not stable)

Are we going to show percentage or text?

**Comment by asubedy** [comment]
> We might need k8s version too as a column

ok will add a column for this too 👍

**Comment by alphaX86** [comment]
> Are we going to show percentage or text?

Percentage seems bit good, else text is fine

**Comment by warunicorn19** [comment]
@asubedy let's talk about this on the meshery dev call today.

**Comment by l5io** [comment]
🚀 Preview for commit 754072b89bb49b8e2853adcb8f17ed6104a57fc2 at: https://62691e8c5f64570c061d8292--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 1a1db0c3f32732bb00d30bc5d81ea64a313f2b81 at: https://62694e7f3f741438da3def38--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit ce4820a23f3af79f93a1a817ea8209135d24ac57 at: https://62875bccf1c2e23f55eb8c22--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 80d840e1b508c47cd85fcdbc06c964e2ca0eb7d6 at: https://62877630c3d6d1476874f0e9--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit b20af702cd17bdc018afec56683b68a0f48ee8af at: https://62877cbcd7193f4bbc294756--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit fcf7913abacd10b842a849dd0ee725a24e84ee9e at: https://62877e71a0e4bc5142ada32a--meshery-docs-preview.netlify.app

**Comment by asubedy** [comment]
@warunicorn19 @alphaX86 Please have a look if everything seems ok, we can merge this.

**Review by alphaX86 — DISMISSED** [review]
Sorry for very late response, LGTM 👍

**Review by warunicorn19 — CHANGES_REQUESTED** [review]
I see this broken image in the first row of the compatibility matrix. Also, a very small nitpick, for the column which has the service-mesh name could you please add `whitespace: no-wrap" ` so that the name is in one line. 
Screenshot 2022-05-23 at 4 36 25 PM

**Comment by l5io** [comment]
🚀 Preview for commit 609bb5d32efcd34ccc34077b858806831943da40 at: https://628ce25490f2a9158db36594--meshery-docs-preview.netlify.app

**Comment by leecalcote** [comment]
Still `do-not-merge`, @asubedy? @gr455 will you review? The supported versions of service meshes can be displayed here as well.

This can link to the # of components each adapter supports, which can be displayed on https://docs.meshery.io/concepts/architecture/adapters

**Comment by asubedy** [comment]
@leecalcote , no I forgot to remove the tag, if we only want to show compatibility on the basis of kubernetes version this PR is good to merge.

**Comment by leecalcote** [comment]
It's a good starting point, let's merge and keep adding to the new matrix. @gr455 has some additional data points to bring forth from adapters, I believe. // @Revolyssup

**Pull request merged**
