### PR TITLE
[Docs] - Fixed CI Failing Issue Due to Error in Syntax of Main FIle

### PR DESCRIPTION
**Pull request by adithyaakrishna**
Signed-off-by: Adithya Krishna <aadithya794@gmail.com>
**Description**

This PR fixes Fixes the CI Failing Issue Caused by `endfor`
Logs: [Netlify Log](https://app.netlify.com/sites/meshery-docs/deploys/60c2d2932f495500082ea35b)

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by alphaX86** [comment]
Is this still work in progress @adithyaakrishna? I didn't review yet though but asking

**Comment by adithyaakrishna** [comment]
I closed this bc I guess it was fixed before only
@leecalcote Could you please confirm this?

**Comment by leecalcote** [comment]
I'm pretty sure that @ramrodo saved the day yesterday and fixed this issue.

**Comment by ramrodo** [comment]
It seems the error stills on master. I'll re-open this PR in order to test it.

**Comment by ramrodo** [comment]
@adithyaakrishna could you do a rebase from master to test these changes with the latest ones, please?

**Comment by adithyaakrishna** [comment]
> It seems the error stills on master. I'll re-open this PR in order to test it.

Ohh I thought soo too, but then saw a PR to fix the issue and got a bit confused. When I fixed it locally and ran it locally, it was successfully running.
Along with this, there are many redundant options which I've removed and updated the site also

**Comment by adithyaakrishna** [comment]
@ramrodo Can you please review this?

**Review by ramrodo — APPROVED** [review]

**Comment by ramrodo** [comment]
Great! It is solved. Thanks!

**Pull request merged**
