### PR TITLE
styling changes to extensions

### PR DESCRIPTION
**Pull request by warunicorn19**
Signed-off-by: Aditya Chatterjee <speak2adi@gmail.com>

**Description**
Removed Flip
Screenshot 2022-08-13 at 3 58 02 AM

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by warunicorn19** [comment]
Okay I forgot to add the coming soon, I'll push that tomorrow. We can either merge this and I'll push directly to master to I can push tomorrow on this branch.

**Comment by leecalcote** [comment]
Thank you. Looking good. There's a pesky purple color on the `a:visited`, but looking much better.

**Comment by leecalcote** [comment]
Leaving this open to allow for a follow up round.

**Comment by warunicorn19** [comment]
PR updated. 
Screenshot 2022-08-13 at 3 26 44 PM

**Comment by Chadha93** [comment]
@warunicorn19 could you please also add a tooltip for the extensions tab in the navigator?

**Pull request merged**
