### PR TITLE
oam pattern: Add OAM patterns with RJSF

### PR DESCRIPTION
**Pull request by Abhishek-kumar09**
Signed-off-by: Abhishek-kumar09 <abhimait1909@gmail.com>

**Description**
Add Oam Deployment pattern in `configuration/pattern`. 
The RJFS form is using OAM schema.
The pattern can be duplicated from the previous deployed apps and other changes can be made on top of it to create a whole new pattern

https://user-images.githubusercontent.com/48255244/128646936-b186e93a-24c3-4229-bb41-32ce26e95970.mp4

**Notes for Reviewers**
oam/workloads, rjsf

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
@Jashpatel1 we're in need of Sykes being applied here. How do we get those?

**Comment by leecalcote** [comment]
Will you apply this same logic to Applications and filters?

Any section of a yaml document that matches a registered component should be displayed for editing.￼

Does this PR support editing Istio Gateway, and Istio Virtual Services information as well?

**Comment by Abhishek-kumar09** [comment]
> Will you apply this same logic to Applications and filters?
> 
> Any section of a yaml document that matches a registered component should be displayed for editing.￼
> 
> Does this PR support editing Istio Gateway, and Istio Virtual Services information as well?

Not now, 

Since it is following the oam schema and traits coming from API request. and The schema only has deployment configuration for Applications.

Let's discuss how to proceed further in the meeting today

**Comment by Abhishek-kumar09** [comment]
Similar merged in #3925

**Pull request closed without merging**
