### PR TITLE
Added custom loading Animated Spinner 

### PR DESCRIPTION
**Pull request by sahilsuman933**
Signed-off-by: Sahil Suman <sahilsuman933@gmail.com>

**Description**

- Added custom animated spinner at Configuration -> Design Pattern Page

https://user-images.githubusercontent.com/34382211/188652816-42eb57b1-ab04-4898-978f-9baf47e0e987.mp4

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
Task linked: [CU-1hk2zp2 Custom animated spinner: patterns logo](https://app.clickup.com/t/1hk2zp2)

**Comment by sahilsuman933** [comment]
https://user-images.githubusercontent.com/34382211/188810526-1fc924f5-4c09-4be6-9d0b-fe86c15a44ea.mp4


https://user-images.githubusercontent.com/34382211/188810545-f70a9c10-f7a4-4c9f-99d4-366602b6441e.mp4

**Comment by leecalcote** [comment]
@sahilsuman933 why does the last leg never complete in the patterns spinner?

**Comment by sahilsuman933** [comment]
It is due to Kubernetes not configured @leecalcote. So, it takes some time to load these designs or filters. Sometimes it is pretty quick, and sometimes it is not.

**Comment by leecalcote** [comment]
> It is due to Kubernetes not configured @leecalcote. So, it takes some time to load these designs or filters. Sometimes it is pretty quick, and sometimes it is not.

Ok, I see. It's not an issue with the animation, then.

**Pull request merged**
