### PR TITLE
remove meshery-operator line from docs

### LINKED ISSUE #10849: [Docs] include --namespace meshery in meshery-operator installation command
### Current State
- On https://meshery.io , installing Meshery using helm commands: 
Screenshot from 2024-05-02 19-40-41

- In https://docs.meshery.io, on [Helm installation page](https://docs.meshery.io/installation/kubernetes/helm#install-meshery-on-your-kubernetes-cluster-using-helm)
image
```bash
helm repo add meshery https://meshery.io/charts/
helm install meshery meshery/meshery --namespace meshery --create-namespace
helm install meshery-operator meshery/meshery-operator
```
### Desired State
~~Change the third line in Docs for installing Meshery on Kubernetes using Helm i.e.
 `helm install meshery-operator meshery/meshery-operator` to
 `helm install meshery-operator meshery/meshery-operator --namespace meshery` 
or, `helm install meshery-operator meshery/meshery-operator -n meshery`~~

Edit: delete the line form meshery.io and docs as well.
---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by vishalvivekm**
**Notes for Reviewers**

This PR fixes #10849 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit fdca17027862ce4a31663faaefa78e28bcfed43d at: https://6633a80464bd2e1d2a7703a3--meshery-docs-preview.netlify.app

**Review by leecalcote — APPROVED** [review]
Thanks, @vishalvivekm. Please confirm meshery.io and layer5.io have been updated as well.

**Comment by leecalcote** [comment]
@vishalvivekm the netlify builds are still failing. Can you carry this forward?

**Comment by leecalcote** [comment]
@vishalvivekm we don't need the Netlify builds as we have a deployment preview solution already. Can you disable these?

**Pull request merged**
