### PR TITLE
fix: openssl-legacy-provider flag causing errors on doing ui-build in macos

### PR DESCRIPTION
**Pull request by nishantwrp**
Signed-off-by: Nishant Mittal <mittalnishant14@outlook.com>

**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Thanks for this. Are you determing $OSTYPE anywhere or is this commonplace environment variable or is the developer to preset this env var?

**Review by warunicorn19 — DISMISSED** [review]
LGTM

**Comment by nishantwrp** [comment]
> Thanks for this. Are you determing $OSTYPE anywhere or is this commonplace environment variable or is the developer to preset this env var?

It's a commonplace env variable.

**Comment by leecalcote** [comment]
@nishantwrp does `build-mac` need to be a another target in here? I'm missing the connection to an alternative set of build instructions when `darwin` is discovered.

**Comment by nishantwrp** [comment]
@leecalcote my bad. i forgot to push the updated `ui/package.json`. just did that.

**Review by leecalcote — APPROVED** [review]
Awesome. Thanks for this, @nishantwrp 👏 // @meshery/meshery-ui-maintainers

**Pull request merged**
