### PR TITLE
[UI] Swaped the position of two buttons- Upload K8's config

### LINKED ISSUE #5689: [UI] Settings: Upload K8s Config - Swap position of two buttons
#### Current Behavior
When adding a cluster, users are presented with this modal (screenshot) on the http://localhost:9081/settings Settings page.

Screen Shot 2022-06-27 at 4 28 28 PM

#### Desired Behavior
1. "Cancel" should be on the right side while "Upload" is on the left.2. 
1. Rename "Upload" to "Import"2. 
1. "Cancel" should be using the light gray background color, while "Import" uses the charcoal-ish color.

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.meshery.io) and [Community Slack](http://slack.meshery.io)

### PR DESCRIPTION
**Pull request by Rohith-Raju**
Signed-off-by: Rohith-Raju <rohithraju488@gmail.com>

**Description**

This PR fixes #5689

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Santosh1176** [comment]
@Rohith-Raju The config file upload functionality seems to be broken. Could you check out at your end.

**Comment by Rohith-Raju** [comment]
@Santosh1176 should be working now 😄

**Comment by Santosh1176** [comment]
That's great! Also, I guess some work is needed in styling these buttons as mentioned in pt 3 of the issue.

**Comment by Rohith-Raju** [comment]
3) "Cancel" should be using the light gray background color, while "Import" uses the charcoal-ish color.

@Santosh1176 Yea I noticed that, But when I swapped them **Cancel** button now has light grey and the **Import** button now has Charcoal-ish colour. Would that be sufficient @leecalcote?
image

**Comment by adithyaakrishna** [comment]
@Rohith-Raju This is good compared to the previous layout. In terms of UX, Positive Action (Import) should be on the right and Negative Action (Cancel) on the left.

@leecalcote @Abhishek-kumar09 Instead of Cancel button having a background color, how about we remove the background color and add only the borders?

image

Ref: https://uxmovement.com/buttons/how-button-color-contrast-guides-users-to-action/ , this is a pretty good read in terms of UX

**Comment by Rohith-Raju** [comment]
@adithyaakrishna Yes, I totally agree with this implementation

**Comment by leecalcote** [comment]
@adithyaakrishna sounds real good. I'll let you propose a change in the design language in Figma and then carryout execution of this in the Meshery UI Refactor effort in v0.7.0. 👍

**Review by leecalcote — APPROVED** [review]
Proceeding with v0.6.0 format.

**Comment by adithyaakrishna** [comment]
> @adithyaakrishna sounds real good. I'll let you propose a change in the design language in Figma and then carryout execution of this in the Meshery UI Refactor effort in v0.7.0. 👍

Ack, thanks so much @leecalcote 💯

**Pull request merged**
