### PR TITLE
[docs] fixed links to meshery adapters

### LINKED ISSUE #6003: [Docs] fix links to meshery adapters
#### Current State
All the links present [here](https://docs.meshery.io/project/compatibility-matrix) to various meshery adapters point to `meshery-istio`. 

#### Desired State
They should point to their own respective github link. 

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by sarthakkathpalia**
Signed-off-by: sarthakkathpalia <sarthakkathpalia@gmail.com>

**Description**
[docs] fixed links to meshery adapters present [here](https://docs.meshery.io/project/compatibility-matrix) . Previously all the links present to various meshery adapters pointed to meshery-istio.

This PR fixes #6003 

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit d305fcd423849936a9db6feab4aa33a425293802 at: https://6300e23982d48a4863ef62e6--meshery-docs-preview.netlify.app

**Comment by nishantwrp** [comment]
@sarthakkathpalia thanks for your pull request. I think a lot of unnecessary files were also committed. Can you revert that?

**Comment by sarthakkathpalia** [comment]
@nishantwrp sorry for this. Can you please guide me a little bit on how to revert the unnecessary files.

**Comment by leecalcote** [comment]
> @nishantwrp sorry for this. Can you please guide me a little bit on how to revert the unnecessary files.

You'll remove the `chruby-0.3.9.tar.gz` and the `chruby-0.3.9` folder from your local clone, commit, and push changes.

**Review by leecalcote — CHANGES_REQUESTED** [review]
Thanks, @sarthakkathpalia. In answer to your question - 

> @nishantwrp sorry for this. Can you please guide me a little bit on how to revert the unnecessary files.

You'll remove the `chruby-0.3.9.tar.gz` and the `chruby-0.3.9` folder from your local clone, commit, and push changes.

Or...

Close this pull request and try again.

**Comment by l5io** [comment]
🚀 Preview for commit e3f784ea195b7f0f5939bd5856c602181bdae60e at: https://630143687d001a0830fa15e4--meshery-docs-preview.netlify.app

**Comment by sarthakkathpalia** [comment]
@leecalcote deleted the unnecessary files. Can you please take a look

**Review by nishantwrp — APPROVED** [review]
lgtm 🎉

**Review by adithyaakrishna — APPROVED** [review]
LGTM 🎉

**Comment by sarthakkathpalia** [comment]
Thanks @nishantwrp @adithyaakrishna for approving. Just asking out of curiosity, so will this PR be merged? Excited as this is my first contribution in such big project 😊

**Review by asubedy — APPROVED** [review]
Good to merge 👍

**Review by Chadha93 — APPROVED** [review]
LGTM

**Comment by Chadha93** [comment]
@sarthakkathpalia. Yay :1st_place_medal:

**Pull request merged**
