### PR TITLE
[Docs] Additional guides/troubleshoot installation links in quickstart

### LINKED ISSUE #5598: [Docs] Quick Start: Need link to Installation Troubleshooting
#### Current State
The bottom of the Quick Start (https://docs.meshery.io/installation/quick-start) page ends without links to additional Guides.

#### Desired State
The bottom of the Quick Start (https://docs.meshery.io/installation/quick-start) page could use a Resources section with link to https://docs.meshery.io/guides/troubleshooting/installation and https://docs.meshery.io/reference/error-codes

and could use a description of or pointer to `mesheryctl system check`

---

#### [Contributor Guides](https://docs.meshery.io/project/contributing) and Resources
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by abhiyant-10**
Signed-off-by: abhiyant-10 <abhigwalani@gmail.com>

**Description**
Added links to additional guides with baseurl function and fixed error codes link on troubleshooting guide page https://docs.meshery.io/guides/troubleshooting

This PR fixes #5598

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit f31b8ba4ff6bc83abc1aec116bc22854c92dc60a at: https://62ad01fbd39be7009cd49287--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 271f14bb81766483048ed0685a2d75656b893d63 at: https://62ad04fc77999b00a606faad--meshery-docs-preview.netlify.app

**Review by leecalcote — COMMENTED** [review]
It'd be great if a new include file was created to make a standard "related pages" section.

**Review by leecalcote — APPROVED** [review]

**Comment by leecalcote** [comment]
Yay! @abhiyant-10 🎈

**Comment by abhiyant-10** [comment]
> Yay! @abhiyant-10 🎈

Looking forward for more contributions.

**Pull request merged**
