### PR TITLE
Meshmodel API restructure

### PR DESCRIPTION
**Pull request by Revolyssup**
**Notes for Reviewers**

This PR fixes #

1. Restructuring API to follow plural convention
2. Add category table
3. Change category structure from string to JSON containing name and metadata
4. Add model SVG in model metadata 
5. Fix bugs in component updater
**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit e6c7a71e06ed05f30db61cedefea6d77b04f0970 at: https://641896be22b59b7bde08118b--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 08175d836bf12235054f09fa5bb88e9935fb040f at: https://6418b6b8d49876039c3ebfd0--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit fab06a29b1c54412d1524d0104d78fb5513daed8 at: https://6418ba07ecfb2a0069c16610--meshery-docs-preview.netlify.app

**Review by Abhishek-kumar09 — APPROVED** [review]

**Comment by Abhishek-kumar09** [comment]
Merge conflicts....

**Comment by l5io** [comment]
🚀 Preview for commit 4ce68d5143c2e95524dec7c1cc3b770465f95078 at: https://641aa91a7052685aa18526ad--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 0804ab24f334802352c33d9a2752b93322b33049 at: https://641aacc4899e065c500eab73--meshery-docs-preview.netlify.app

**Pull request merged**
