### PR TITLE
fixing typo in the meshery-metrics page

### LINKED ISSUE #12991: [Docs]Typo in the performance-management/meshery-metrics page
A typo is found in the page [meshery-metrics](https://docs.meshery.io/guides/performance-management/meshery-metrics), <br /><br />the misspelled word is:<br />  *Retreive*<br /><br /><br /> thanks !

### PR DESCRIPTION
**Pull request by lhajouji**
**Notes for Reviewers**

- This PR fixes #12991

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 10119ccc56c7911452108a4c7c5dbf57b342b252 at: https://676a9f8883893ab9fea2bcd6--meshery-docs-preview.netlify.app

**Comment by sudhanshutech** [comment]
@lhajouji try to include all typo fix in single pr it makes hard to get all small prs to manage

**Comment by lhajouji** [comment]
@sudhanshutech of course ! But i've seen that some PR has been merged.
Do you confirm that all the remaining should be merged in one ?

**Comment by sudhanshutech** [comment]
> @sudhanshutech of course ! But i've seen that some PR has been merged. Do you confirm that all the remaining should be merged in one ?

yes move them to one

**Comment by lhajouji** [comment]
> > @sudhanshutech of course ! But i've seen that some PR has been merged. Do you confirm that all the remaining should be merged in one ?
> 
> yes move them to one

Here you go , All Remaining typo fixes merged into one PR #13000

**Pull request closed without merging**
