### PR TITLE
Bug/varunsaral/#4930

### LINKED ISSUE #4930: [Docs] Clicking the contributing breadcrumb from the Meshery Server page leads to a 404
#### Current State

Clicking the contributing breadcrumb (See top of first image) leads to a 404
Screenshot 2022-01-12 at 12 23 10 AM
Screenshot 2022-01-12 at 12 23 26 AM

On link inspection you can see that the actually see that the error is due to a trailing /

Actual link : `https://docs.meshery.io/project/contributing`
#### Desired State

Error link: `https://docs.meshery.io/project/contributing/`

Simply changing to the correct link should fix this issue
---

#### [Contributor Guides](https://docs.meshery.io/project/contributing) and Resources
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by varunsaral**
Signed-off-by: varun saral varunsaral47@gmail.com

**Description**

Tried to add redirect_from to maximum files to remove the trailing slash problem
This PR fixes #4930 #4919

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ *] Yes, I signed my commits.

### CODE REVIEW

**Comment by warunicorn19** [comment]
Looks like you forgot to sign-off, also have you checked these changes locally? I have a feeling these changes are gonna break the docs.

**Comment by varunsaral** [comment]
i signed i guess , and i tried to see the chanegs locally and it's working fine . didn't checked the whole docs yet. But they are running .

**Comment by varunsaral** [comment]
moreover after observing the root docs index.md , the index.md premalink has a traling slash and it works perfectly with or without slash in browser . should we add it ? or it going to break the things i don't think it will break it.

**Comment by warunicorn19** [comment]
Lots of file have repetition of the `redirect_from` frontmatter, something is causing the build to fail. Could you please take a look.

**Comment by warunicorn19** [comment]
this https://github.com/meshery/meshery/runs/4781294580?check_suite_focus=true#step:4:304 might help.

**Comment by varunsaral** [comment]
sure , i build a python file to do the work , as it's lot of work , let me check the duplicates

**Comment by varunsaral** [comment]
`mkdir': File exists @ dir_s_mkdir - /opt/build/repo/docs/_site/reference/mesheryctl/commands/subcommands/index.html lot of this kind of error , maybe i have to look where thing going wrong

**Comment by leecalcote** [comment]
@varunsaral will you take a moment to add a more descriptive PR title, including `[Docs]` at the beginning of the line? Thanks a bunch. This helps maintainers save time.

**Comment by leecalcote** [comment]
No need to build python. Just execute a couple `git` commands to amend your signoff.

The number of commits in this PR a little excessive. Its not necessary to make a `git commit` for each page changed. These changes can be bundled into one commit.

**Comment by leecalcote** [comment]
> moreover after observing the root docs index.md , the index.md premalink has a traling slash and it works perfectly with or without slash in browser . should we add it ? or it going to break the things i don't think it will break it.

Referring back to my previous explanation regarding Jekyll 4.x behavior, the need for the redirect has to do with dev vs prod builds.

**Comment by leecalcote** [comment]
@varunsaral ping if you could use some assistance.

**Pull request closed without merging**
