### PR TITLE
[Docs] Clipboard plugin

### LINKED ISSUE #1269: [Docs] Copy-to-clipboard for CLI commands
**Current State:**
CLI commands included in the Meshery documentation have to be highlighted and copied by the reader. Sometimes the reader will accidentally include the `$` in what they copy and paste to their terminal. 

**Desired State:**
Improve the reader experience for Meshery CLI commands incorporating https://clipboardjs.com to capture various terminal commands into the reader's clipboard on click of the mouse. 

1. See  https://layer5.io/meshery/#getting-started as an example of how to do this. 
1. Use the same clipboard icon from layer5.io

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

### PR DESCRIPTION
**Pull request by chandrashritii**
**Description**

This PR fixes #1269 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by chandrashritii** [comment]
@chebro Take it away :)

**Comment by chandrashritii** [comment]
The approach taken for the plugin has been documented in this [doc](https://docs.google.com/document/d/17guuaxb0xsfutBCzyj2CT6OZiFnMu9w4PzoILXhRXSo/edit?usp=sharing). The button needs to be styled (with CSS) as discussed @chebro

**Comment by chebro** [comment]
I'm a little busy with this week, will jump back in as soon as I can.

**Comment by chebro** [comment]
Any idea why the DCO is still failing?

**Review by leecalcote — APPROVED** [review]

**Pull request merged**
