### PR TITLE
add: Add description for relationship

### LINKED ISSUE #10287: [Models] Relationships: Descriptions of how one component affects the other(s)
Fill in the descriptions please.

_Originally posted by @MUzairS15 in https://github.com/meshery/meshery/pull/10244#pullrequestreview-1878824473_

### PR DESCRIPTION
**Pull request by RipulHandoo**
**Notes for Reviewers**

This PR fixes #10287

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — APPROVED** [review]
Good!

**Review by leecalcote — CHANGES_REQUESTED** [review]
@RipulHandoo, wait... rather than describe the resource itself, please describe the nature of the relationship, and how one modifies the other.

**Comment by RipulHandoo** [comment]
> @RipulHandoo, wait... rather than describe the resource itself, please describe the nature of the relationship, and how one modifies the other.

Gotcha. 🫡

**Review by leecalcote — APPROVED** [review]
Thanks!

**Pull request merged**
