### PR TITLE
changed snackbar notication hook to custom notification hook

### LINKED ISSUE #8512: [UI]  update Snackbar Calls to Use New Notification Hooks
## Current State:
Throughout the codebase, the notistack snackbars are being used for notifications. However, we have recently improved the notification experience by developing our own custom hooks and components for handling notifications.

## Desired State:
We need to replace all previous snackBar calls with the new notification hooks that we have created.

## Previous Snackbar Usage:

```
handleClick() {
  // Previous snackBar call
  enqueueSnackbar(message, {
    variant: "info",
    action: <Button> </Button>
  });
}
```
## New Notification Hook Usage:

```
const { notify } = useNotification();

handleClick() {
  // New notification hook call
  notify({ message: "hello", event_type: EVENT_TYPES.INFO });
}
```
We also have created a withNotify HOC to use in class based components 

## Steps To Work On This :

- Identify instances where the old snackBar calls are being used throughout the codebase.
- Replace the old snackBar calls with the new notify hook calls, using the provided code snippet as a guide.
- Test the application thoroughly to ensure that notifications are being displayed correctly using the new notification hooks.
- Ensure that the useNotify hook is imported and used correctly in the components where notifications are triggered.

 

### Mockups

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by EraKin575**
**Notes for Reviewers**

This PR fixes #8512 

this pr changed snackbar hook to custom hook 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by EraKin575** [comment]
@aabidsofi19 please take a look.

**Comment by aabidsofi19** [comment]
@EraKin575  sorry to say but you and Rajdip  have worked on common changes ( i clearly told not to )   so  i would like you to slow down as he has finished it in all places now . dont worry i will assign you some other issue  .

**Comment by EraKin575** [comment]
> @EraKin575 sorry to say but you and Rajdip have worked on common changes ( i clearly told not to ) so i would like you to slow down as he has finished it in all places now . dont worry i will assign you some other issue .

**Comment by EraKin575** [comment]
@aabidsofi19 oh. Alright, no worries.I will work on another assigned issues

**Pull request closed without merging**
