### PR TITLE
fix the wrong command 'mesheryctl mesh'

### LINKED ISSUE #12083: Command Display Error
### Current State
meshery-doc

### Desired State

Please fix the incorrect command to the correct one.

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by Standing-Man**
**Notes for Reviewers**

This PR fixes #12083

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 3de90f2e3bb7bfc937eb706f8a2fdd535e3d5373 at: https://66ed38cce165411d9a2fa4ac--meshery-docs-preview.netlify.app

**Review by alphaX86 — APPROVED** [review]
Approved. LGTM

**Review by lekaf974 — APPROVED** [review]
LGTM

**Comment by vishalvivekm** [comment]
@JianMinTang Thank you for your contributions! Let's discuss this during the Meshery Development call today at 7:30 PM IST (9:00 AM CT). Adding it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit?pli=1#) || [meeting link](https://meet.layer5.io/meshery).

**Review by lekaf974 — APPROVED** [review]

**Pull request merged**
