### PR TITLE
[DOCS] Suggested Reading bug fix

### LINKED ISSUE #9996: [Docs Designs] - List items descriptions are identicle
### Current Behavior

Link: [Meshery Docs](https://docs.meshery.io/concepts/logical/designs)

Currently the list items under "Suggested Reading" have identical descriptions.

### Expected Behavior

Listing the same description for each item appears repetitive and does not add value to the section.

- If the intention is to add a unique description for each listed item - then the appropriate/fitting content should be provided and added accordingly.
- If the intention is to have the current description for all the listed items - then the description should be added as a subheading, and list the items without a description.

### Screenshots/Logs

Screenshot 2024-01-17 201314

### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by iArchitSharma**
**Notes for Reviewers**

This PR fixes #9996 

image

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit bd69f5dfaa5d49c13edc26d9452dece8e55f5530 at: https://65aa61cdde06af14124866fe--meshery-docs-preview.netlify.app

**Review by sandramsc — CHANGES_REQUESTED** [review]
Currently reads as: "Connections - Meshery Connections are managed and unmanaged resources that either through discovery or manual entry are managed a state machine and used within one or more Environments."

This sentence requires a few grammar adjustments: "Connections - Meshery Connections are managed and unmanaged resources that either through discovery or manual entry are **managed a state machine and used within one or more Environments.**"

- did you mean to write "...managed as a state machine..."?
- the word environment in lowercase
------

Currently reads as: "Credentials - Meshery uses one or more Credentials when authenticating to a managed or unmanaged Connection."

This sentence requires a few grammar adjustments:
- the word connection in lowercase

------

Currently reads as: "Workspaces - Meshery Workspaces act as central collaboration points for teams"

This sentence requires a few grammar adjustments: "Workspaces - Meshery Workspaces act as central collaboration points for teams."
- missing full stop (**.**) at the end of the sentence

**Comment by iArchitSharma** [comment]
@sandramsc, that could be another issue because I am not writing descriptions, I am fetching those descriptions from the front matter of Markdown pages.

**Comment by l5io** [comment]
🚀 Preview for commit 85835ce43684608060588b326e2724df0d60f72f at: https://65ab7628f5229e6236ff5b05--meshery-docs-preview.netlify.app

**Comment by leecalcote** [comment]
> * did you mean to write "...managed as a state machine..."?
> * the word environment in lowercase

Yes, ideally, both of these are updated in accordance with your suggested change, @sandramsc 

- did you mean to write "...managed as a state machine..."?
- the word environment in lowercase

**Comment by leecalcote** [comment]
Oh, the reason that Environments and Credentials are uppercased is that we're treating them as keywords - Meshery core constructs.

We need to either uppercase all the time or lowercase all the time.

**Comment by leecalcote** [comment]
@sandramsc's feedback incorporated.

**Comment by l5io** [comment]
🚀 Preview for commit 05b96f60a3ed795ace1717087cd86e40e69b16dd at: https://65ab84107077ff6b0f4d98e7--meshery-docs-preview.netlify.app

**Pull request merged**
