### PR TITLE
[mesheryctl]Check for Meshery server status before opening in browser

### LINKED ISSUE #3034: `system start` does not check if Meshery pods are ready before trying to reach the Meshery server
#### Description

`system start` on the Kubernetes platform does not wait for Meshery to be fully deployed and the pods running before trying to open Meshery on the browser.

#### Expected Behavior

`system start` should check for the status of the pods and only open it on the browser when Meshery is running

### LINKED ISSUE #3282: [mesheryctl] Read the auth token from Meshery server rather than prompting user
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior
A set of mesheryctl subcommands depend on user to download auth.json from Meshery UI and provide it as command line argument. This does not give good UX.
Commands dependent on auth token:

`mesheryctl pattern`
`mesheryctl perf`
`mesheryctl system config`

#### Desired Behavior
Modify the mesheryctl to query meshery server for auth token and use it, rather than prompting users to provide token with "--token" option.

#### Environment

- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker or Kubernetes

#### Mockups

---

#### Contributor Resources

- [mesheryctl Contributing Guide](https://github.com/layer5io/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by hexxdump**
**Description**
At times, opening meshery endpoint in browser fails when the Meshery server is starting up.
Added a check to access the endpoint before opening the endpoint in browser.

This PR fixes #3034

**Notes for Reviewers**
10 second time out value is debatable. let me know your thoughts.

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by navendu-pottekkat — APPROVED** [review]
Looks good, 10s should work, we can change this if people face issues here.

**Comment by navendu-pottekkat** [comment]
@hexxdump Did you link this PR to the wrong issue?

**Review by leecalcote — APPROVED** [review]
Fantastic, @hexxdump 😄

**Comment by hexxdump** [comment]
> @hexxdump Did you link this PR to the wrong issue?

yes @navendu-pottekkat. Changed it to correct issue now.

**Pull request merged**
