### PR TITLE
Update README.md: Fix meshery badges

### PR DESCRIPTION
**Pull request by aminoxix**
_Signed-off-by: aminos 🇮🇳  <anshumaankrprasad76@gmail.com>_

**Description**
Updating README.md wth Netlify badge, fix Slack Badge & aligned to center.

**Notes for Reviewers**
I didn't create any issue for this, & will enhance anything if reqd...
Just suggest me!

Preview:-
image

**[Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by amino19** [comment]
@Anita-ihuman : Pl merge this. 😃

**Comment by amino19** [comment]
@alphaX86  : Needs your review!

**Review by alphaX86 — APPROVED** [review]
LGTM for me though!

**Comment by alphaX86** [comment]
Asking lee now....

**Comment by alphaX86** [comment]
// cc: @leecalcote

**Review by leecalcote — APPROVED** [review]
Thanks, Anshu!

**Pull request merged**
