### PR TITLE
Increased Istio logo size

### LINKED ISSUE #6446: [UI] Increase Istio logo size.
#### Current Behavior
[UI] Increase Istio logo size.
current

#### Desired Behavior
expected

#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by parthn2**
Signed-off-by: Parth <parthnanda002@gmail.com>

**Description**

This PR fixes #6446

**Notes for Reviewers**
New Behavio
Screenshot 2022-10-30 at 11 43 41 AM
ur

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by legendarykamal** [comment]
@parthn2 while the ss looks good but  aren't the two sizes equal but just different ? 

image

**Review by legendarykamal — COMMENTED** [review]
@parthn2 while the ss looks good but  aren't the two sizes equal but just different ? 

image

**Comment by parthn2** [comment]
> @parthn2 while the ss looks good but aren't the two sizes equal but just different ?
> 
> image

The size didn't need to be changed. The size of the image(logo) is relative to the width of the SVG. So just it was needed to be reduced to increase the size of image.

**Review by warunicorn19 — CHANGES_REQUESTED** [review]
Hey @parthn2 thanks for the PR, if you look closely you'll notice that the height at the top of the logo is not the same as that at the bottom. Ideally the logo should be equidistant.

**Comment by parthn2** [comment]
> Hey @parthn2 thanks for the PR, if you look closely you'll notice that the height at the top of the logo is not the same as that at the bottom. Ideally the logo should be equidistant.

I hope it seems better now. Please tell if any changes are still needed

**Review by warunicorn19 — APPROVED** [review]
LGTM, Thank you @parthn2

**Pull request merged**
