### PR TITLE
Fix URL validation.

### LINKED ISSUE #1611: [Perf] Field validation not honoring valid URLs
**Description**
See screen capture.

**Expected Behavior**
Allow valid endpoints.

**Screenshots**
Untitled

**Environment:**
- Version: v0.4.6

### PR DESCRIPTION
**Pull request by wryonik**
This commit adds "localhost" in the regex for valid URL.

Signed-off-by: shubhamgupta2956 <shubham.gupta2956@gmail.com>

**Description**

This PR fixes #1611 

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Thank you, @shubhamgupta2956. The validation was failing to match the up address 192.168.1.15. Will you verify these changes allow for IPv4 addresses as well?

**Comment by shubhamgupta2956** [comment]
@leecalcote I have verified the given ip address is working fine. Can you please tell me the steps to reproduce the error as it is working fine in my machine and should also work fine in other devices also.

**Comment by leecalcote** [comment]
Hi @shubhamgupta2956, I'm running v0.4.6 of Meshery (running from `mesheryctl system start`). I wonder if the version that you have built from `master` has differences here.

**Comment by leecalcote** [comment]
@shubhamgupta2956 I just tried again with the latest release of Meshery v0.4.8 and see the same behavior with this IP address. Will you try installing Meshery local (running on Docker) and see if you can reproduce? I'm using Safari as my browser.

**Comment by leecalcote** [comment]
@shubhamgupta2956 I take it back. It seems that I had an old session still running v0.4.6 of Meshery. Now that I am running v0.4.8, I don't see the same validation issue for the IP address any longer. 👍

**Review by leecalcote — APPROVED** [review]
Thanks for this fast turn around, @shubhamgupta2956 👍

**Pull request merged**
