### PR TITLE
feat: Addition of title for routes of Meshery & indentation rule

### LINKED ISSUE #979: Addition of Title for different routes of Meshery
**Current Behavior**

Currently, Title of every page is `Meshery`
**Desired Behavior**

Addition of Title for different routes of Meshery.

### PR DESCRIPTION
**Pull request by kushthedude**
Fixes #979

### CODE REVIEW

**Comment by leecalcote** [comment]
Gents, what say you to this format: "Meshery - <name of page>"?

**Comment by kushthedude** [comment]
'Route | Meshery', is more obeservable and cleaner then 'Meshery - Route'.
Also we are following same convention in layer5.io and meshery.io .
But I am ready for change if the later is more convenient.

**Comment by aayushdutt** [comment]
> Gents, what say you to this format: "Meshery - "?

@leecalcote Works for me. We should consider though that the main title might get hidden due to the short tab size.

**Comment by leecalcote** [comment]
@kushthedude, great call. I support 'Route | Meshery'. 👍

**Pull request merged**
