### PR TITLE
[UI] Dashboard enhancement 

### PR DESCRIPTION
**Pull request by theBeginner86**
**Notes for Reviewers**

- [x] Uppercase sub-titles
- [x]  Transition 

https://github.com/meshery/meshery/assets/73700530/3265980b-db36-4461-8e0c-5d7acf245249

This PR fixes #

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by sudhanshutech** [comment]
@theBeginner86 can't we use react-swipeable view here instead mui Slide

**Review by leecalcote — COMMENTED** [review]
Good! Can we avoid the initial slide-in? Upon selection of a tab on the menu, the page can load as it does now. The only sliding then being between two pages: the all Resources of one type Overview and specific resource Details pages.

**Comment by aabidsofi19** [comment]
@theBeginner86  @leecalcote  i have updated the behavior to only transition when we change from detail to overview

**Review by leecalcote — APPROVED** [review]
Thank you.

**Pull request merged**
