### PR TITLE
[policy] Add Sibling Policy

### PR DESCRIPTION
**Pull request by theBeginner86**
**Notes for Reviewers**

This PR fixes #

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — APPROVED** [review]
LGTM (so far)

**Comment by aabidsofi19** [comment]
@theBeginner86  does it make ense to transform the response to : 
``` 
group_objects_with_matching_fields : {
    label : { 
        <label-key> : [ { id : <component-id> , name : <component-name> } ... ] 
        } , 
        some-other-field : .... 
        }
```

**Comment by theBeginner86** [comment]
> @theBeginner86 does it make ense to transform the response to :
> 
> ```
> group_objects_with_matching_fields : {
>     label : { 
>         <label-key> : [ { id : <component-id> , name : <component-name> } ... ] 
>     } , 
>    annotation : {} ,
>    some-other-field : ....  // 
>    }
> }
> ```

done!

**Comment by aabidsofi19** [comment]
@theBeginner86  Thank you   :rocket:

**Pull request merged**
