### PR TITLE
Added Build and Release Meeting time and minutes link

### LINKED ISSUE #8048: [Docs] Add Build and Release Meeting time and minutes link
#### Current State
This page, https://docs.meshery.io/project/contributing/build-and-release, doesn't immediately offer information about the community meetings dedicated to Meshery CI.

#### Desired State
This page, https://docs.meshery.io/project/contributing/build-and-release, could use with an info box calling out the bi-weekly meetings. 
Details: https://meshery.io/calendar and minutes: https://docs.google.com/document/d/1GrVdGHZAYeu6wHNLLoiaKNqBtk7enXE9XeDRCvdA4bY/edit#

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by ranjanmangla1**
**Notes for Reviewers**
Added biweekly Build and Releae meeitng time and minutes link

This PR fixes #8048

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.
 
image

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit e44ffe746f611f418fe1723d3797ecf9d7cf5807 at: https://64aa59d26a675c7916c4cbe4--meshery-docs-preview.netlify.app

**Comment by vishalvivekm** [comment]
@ranjanmangla1 Let's discuss this on websites call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit) if you would :)

**Review by thisiskaransgit — CHANGES_REQUESTED** [review]
- Build and Release meeting happens biweekly every Thursday
-  Rephrase the sentence to cater to the contributors who are interested in contributing to ci/cd pipelines and DevOps-related works.

**Comment by ranjanmangla1** [comment]
@thisiskaransgit, i have rephrased the sentence, please review the changes

**Comment by thisiskaransgit** [comment]
@ranjanmangla1, please resolve the merge conflicts

**Review by leecalcote — APPROVED** [review]
LGTM

**Pull request merged**
