### PR TITLE
Meshmodel summary dark mode bug fixed

### LINKED ISSUE #6998: [UI] MeshModel summary does not change in dark mode
#### Current Behavior

When navigating to Settings, the part where you look at the MeshModel summary, the UI doesn't change in Dark Mode.

The styles for this section will need to include the Dark Mode toggle.

#### Screenshots/Logs

Screenshot_20230203_120242

#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by deepakdinesh1123**
Signed-off-by: deepakdinesh1123 <d.deepakdinesh13@gmail.com>

**Notes for Reviewers**

This PR fixes #6998 

In this PR I have experimented with a new way to define a theme for `mui-datatable`,the theme is defined in `ui/themes/configurationTableTheme.js`  and it can be overridden by passing a theme object to the `configurationTableTheme() or configurationTableThemeDark()` functions.

Before:
Screenshot from 2023-02-13 15-41-34
After:
Screenshot from 2023-02-13 15-41-46

**[Signed commits]**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Chadha93** [comment]
@deepakdinesh1123  Let's discuss this on the Meshery Dev call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#) if you would. :)

**Review by leecalcote — APPROVED** [review]
LGTM 

@deepakdinesh1123 👏

**Comment by leecalcote** [comment]
@harkiratsm I wonder if you have thoughts here.

**Comment by acald-creator** [comment]
@deepakdinesh1123 While this looks good to me, will this be interfere with the other PR on https://github.com/meshery/meshery/pull/6957?

The other PR is attempting to fix the layout to make it uniform across each of the tabs, and we would to account for if the other PR can easily be merged in with the dark mode options.

**Comment by leecalcote** [comment]
@partik03 what do you think?

**Comment by partik03** [comment]
> @partik03 what do you think?

@leecalcote I have my pr opened which makes the meshmodel thing consistent with other settings tabs,so if we can merge that first and after that this one can be merged and will be a great addition.

**Comment by leecalcote** [comment]
> > @partik03 what do you think?
> 
> @leecalcote I have my pr opened which makes the meshmodel thing consistent with other settings tabs,so if we can merge that first and after that this one can be merged and will be a great addition.

Thanks much, @partik03

**Comment by leecalcote** [comment]
@deepakdinesh1123 will you please take a moment to review and resolve these recent merge conflicts?

**Comment by acald-creator** [comment]
We can go ahead and merge this, after this PR bring in the latest changes, as the MeshModel section has been updated.

**Comment by leecalcote** [comment]
@deepakdinesh1123 merge conflicts still.

**Comment by acald-creator** [comment]
We should be good to go.

I just rebuilt Meshery, and I can see that the Dark theme isn't used in other sections of the Settings page. This should be fixed already from the other PR, if it hasn't been merged yet.

**Comment by leecalcote** [comment]
Thank you, @acald-creator. And @deepakdinesh1123 thanks you, too, right, @deepakdinesh1123? 😜

**Review by leecalcote — APPROVED** [review]

**Pull request merged**
