### PR TITLE
[Docs] Add Release Channel Selector to Compatibility Matrix

### LINKED ISSUE #5144: [Docs] Add Release Channel Selector to Compatibility Matrix
#### Current State
A release channel filter is available on past test result pages (e.g. https://docs.meshery.io/project/compatibility-matrix/meshery-istio-past-results), but not on the main compatibility results page (https://docs.meshery.io/project/compatibility-matrix).

Screen Shot 2022-02-27 at 5 52 00 PM

#### Desired State

The release channel filter should be available on the compatibility matrix page, too. 

---

#### [Contributor Guides](https://docs.meshery.io/project/contributing) and Resources
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by progmatic-99**
**Description**

This PR fixes #5144 

**Notes for Reviewers**
Screenshot 2022-03-03 at 11-57-15 Compatibility Matrix

Screenshot 2022-03-03 at 11-57-43 Compatibility Matrix

Screenshot 2022-03-03 at 11-57-59 Compatibility Matrix

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit bace871aca1bcaed7a120a16b1499b9a26c811e6 at: https://622064b2dcc5de6e3336e915--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 551c023a81919801993cbc94ee0f5d0e5d7b8320 at: https://6220684ed61264702fccfbda--meshery-docs-preview.netlify.app

**Review by shubham-tyagi — CHANGES_REQUESTED** [review]
Hey @progmatic-99, Everything looks great to me. A little change, can you have the space between both the checkboxes as we have in the first image.
image
image

**Comment by l5io** [comment]
🚀 Preview for commit a6cb0962b2cd7e662a8311be7ed372ad922af32d at: https://6220bd9702673ae4a7b093b3--meshery-docs-preview.netlify.app

**Comment by progmatic-99** [comment]
Screenshot 2022-03-03 at 19-05-33 Compatibility Matrix

**Review by asubedy — APPROVED** [review]
Looks good 👍

**Review by warunicorn19 — APPROVED** [review]
Looks good, Thank you @progmatic-99

**Review by Nikhil-Ladha — CHANGES_REQUESTED** [review]
Remove the `console.log` statements

**Comment by Nikhil-Ladha** [comment]
Dang @warunicorn19 . Shouldn't have added you as a reviewer 😂

**Comment by warunicorn19** [comment]
Oops, sorry @Nikhil-Ladha 🥲🥲😂😂

**Comment by warunicorn19** [comment]
We have the console logs on the other pages too, so I thought since its a copy paste we can just move forward with it 😅😅

**Comment by Nikhil-Ladha** [comment]
> We have the console logs on the other pages too, so I thought since its a copy paste we can just move forward with it sweat_smilesweat_smile

Ahh....no worries.

**Pull request merged**
