### PR TITLE
add exponential backoff strategy

### LINKED ISSUE #11157: [CI]Model Componet Generator and Updater Workflow Update
### Current Behavior
Currently, every night the [Model Component Generator and Updater](https://github.com/meshery/meshery/actions/workflows/model-generator.yml) fetches data from the [Meshery integration](https://docs.google.com/spreadsheets/d/1DZHnzxYWOlJ69Oguz4LkRVTFM79kC2tuvdwizOJmeMw/edit) spreadsheet and uses ArtifactHub to fetch the repository URL. ArtifactHub has its own rate limit, and the logic to handle this is implemented [here](https://github.com/meshery/meshery/blob/f7003dfb9f25ad05d340b206c5479f4d22e2049c/mesheryctl/internal/cli/root/registry/generate.go#L56). When the rate limit is hit, it returns a status 429 error.

### Desired Behavior
Implement an exponential backoff strategy so that whenever the rate limit is hit, the request retries with increasing intervals.
### Implementation

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
- Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)
- 🧪 [Meshery Test Plan Spreadsheet](https://docs.google.com/spreadsheets/d/13Ir4gfaKoAX9r8qYjAFFl_U9ntke4X5ndREY1T7bnVs/edit#gid=0)

### PR DESCRIPTION
**Pull request by milinddethe15**
**Notes for Reviewers**

This PR fixes #11157 #11034 

Values for artifactHubInitialDelay, artifactHubMaxDelay needs review.

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by vishalvivekm** [comment]
Thank you @milinddethe15 
Let's discuss this in Meshery Dev meeting starting in 20 minutes.
Meeting minutes: https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit?pli=1#
Meeting link: https://meet.layer5.io/meshery

**Review by MUzairS15 — CHANGES_REQUESTED** [review]
1. The retry and backoff needs to kickoff as we see the first 429 reatelimit error, as we we will use retires there is no sense to wait for certain batch of requests to complete.
2. We don't want to write the logic ourselves, there's already been implementation available.

**Review by MUzairS15 — CHANGES_REQUESTED** [review]
We are adding exponential backoff but where's retry? The backoff limit increases per batch size and not for the individual errors.

**Comment by leecalcote** [comment]
@milinddethe15 make sense. Will you be incorporating this feedback?

**Comment by milinddethe15** [comment]
Yes, sir. I am working on it

**Comment by leecalcote** [comment]
@milinddethe15, continuing our chat from Slack. Thanks for confirming that you're not available in the short-term to complete this effort. Feel free to return at any time to resume (reopen) this item or pickup a new item.

**Pull request closed without merging**
