### PR TITLE
[UI] ConfirmationModal - Changed the order of tabs

### PR DESCRIPTION
**Pull request by partik03**
Signed-off-by: Partik SIngh <partik.sbumrah.cse21@itbhu.ac.in>

**Notes for Reviewers**

This PR fixes #
#6719 
Before 
208052944-059170ba-fc3f-4e86-a60f-a8956c5fa3e4
After

https://user-images.githubusercontent.com/99184676/208107341-04041cc9-c3ce-4be6-ad6c-cac63f21e58c.mp4

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Chadha93** [comment]
@partik03 On validate it's crashing?

**Comment by partik03** [comment]
> @partik03 On validate it's crashing?

It's been crashing on my system I don't know why.It was crashing before as well but it's not because of the changes I made

**Comment by Chadha93** [comment]
> > @partik03 On validate it's crashing?
> 
> It's been crashing on my system I don't know why.It was crashing before as well but it's not because of the changes I made

Yeah, the changes so far looks good. I'll test the PR once and verify. Thank you.

**Comment by Chadha93** [comment]
@partik03 I tested the PR there is no call being made for deployment after the change. Will you look into this?

**Comment by Chadha93** [comment]
@partik03 I've fixed the bug with deploy.

**Review by Chadha93 — APPROVED** [review]

**Comment by partik03** [comment]
@Chadha93 sorry.I missed that😅.

**Comment by partik03** [comment]
> @partik03 I've fixed the bug with deploy.

Thank you

**Comment by Chadha93** [comment]
> @Chadha93 sorry.I missed thatsweat_smile.

No worries, Good work. PR LGTM :1st_place_medal: Let's wait for the checks and merge.

**Pull request merged**
