### PR TITLE
Optimizing mashpod information retrieval.

### PR DESCRIPTION
**Pull request by jinronga**
**Notes for Reviewers**

This is an optimization PR#

Optimize the retrieval of mesh pod information and remove unnecessary commented code.

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by vishalvivekm** [comment]
@jinronga Let's discuss this on Meshery Dev call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#) if you would. :)

**Comment by Chadha93** [comment]
@jinronga If we missed your topic last time, let's cover it today. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#) if you would. :)

**Comment by jinronga** [comment]
> 
I'm very sorry, I can't attend the meeting.

**Comment by jinronga** [comment]
> @jinronga如果我们上次错过了您的主题，那么今天我们就来讨论一下。如果愿意，请将此作为[会议纪要](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#)中的议程项目添加。:)

I'm very sorry, I can't attend the meeting.

**Pull request closed without merging**
