### PR TITLE
[meshery-ui_bug.md] Fixed broken link

### LINKED ISSUE #4715: contributing-ui page link is broken in github issue reference section for contribution [Docs]
#### Current State
Broken Link

https://user-images.githubusercontent.com/42253796/144662736-2ee0cbb0-0da1-47cf-b1df-249d05ca36db.mp4

#### Desired State
The link should point to https://docs.meshery.io/project/contributing/contributing-ui
---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by arunkarthicknm**
Signed-off-by: arunkarthick <arunkarthicknm@gmail.com>

**Description**

This PR fixes #4715 

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by arunkarthicknm** [comment]
Can someone please help me out with this??

**Comment by leecalcote** [comment]
Don't sweat the build failure. Your update looks good.

**Review by warunicorn19 — APPROVED** [review]
LGTM! Thank you @arunkarthicknm. Dont worry, docker build is failing due to other reasons.😄

**Comment by arunkarthicknm** [comment]
> Don't sweat the build failure. Your update looks good.

Oh okay sir, thank you!! 😅

**Comment by arunkarthicknm** [comment]
Yayy!!😊

**Pull request merged**
