### PR TITLE
[Registry][WIP] Show available relationships of component in component tab

### PR DESCRIPTION
**Pull request by Yashsharma1911**
**Notes for Reviewers**

This PR fixes #

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by Yashsharma1911** [comment]
This PR will need more updates, for RTK migration I'm raising new PR

**Comment by sudhanshutech** [comment]
@Yashsharma1911 conflicts... And what more updates is needed here?

**Comment by Yashsharma1911** [comment]
> @Yashsharma1911 conflicts... And what more updates is needed here?

Good UI to show relationships

**Review by leecalcote — APPROVED** [review]

**Comment by leecalcote** [comment]
@Yashsharma1911 merge conflicts to address

**Pull request closed without merging**
