### PR TITLE
Added a --set subcommand with the token create command

### LINKED ISSUE #4216: [mesheryctl] --set flag to set the newly created token as the token for the current-context
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior

`mesheryctl system context create <token-name>` creates a new token in the meshconfig file.

#### Desired Behavior

Add a `--set` flag to this subcommand which will set this newly created token as the token of the current context.

Screenshot 2021-09-20 at 3 33 56 PM

---

#### Contributor Resources
- [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by sayantan1413**
Signed-off-by: sayantan1413 <sayantanbose2001@gmail.com>

**Description**

Add a --set flag to this subcommand which will set this newly created token as the token of the current context.

This PR fixes #4216 

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by sayantan1413** [comment]
Screenshot 2021-09-25 at 11 54 29 PM

**Comment by leecalcote** [comment]
@navendu-pottekkat where is the guide for UX convention for subcommand vs flag? mesheryctl is using “set” as both currently.

**Comment by navendu-pottekkat** [comment]
`set` is a subcommand and also a flag.

`system context set <context name>` is used to set a particular context if it is already present in the meshconfig.

But without the `--set` flag, creating a new context and setting it as the current context will take 2 steps.

```
mesheryctl system context create <context name>
```
```
mesheryctl system context set <context name>
```

VS

```
mesheryctl system context create <context name> --set
```

The exact same behaviour is replicated here in `token`.

**Comment by leecalcote** [comment]
The lack of consistency with `mesheryctl system channel set` is disturbing.

**Comment by navendu-pottekkat** [comment]
@leecalcote `channel set` would be inconsistent in that it would not have a `--set` flag.

But we cannot create a channel. We can only choose `edge` or `latest`. So it could not be consistent here (?)

`--set` flag is very useful and we should not remove it from `context` and `token` IMO.

Is there any other way you are thinking about this?

**Comment by leecalcote** [comment]
TBH, I haven't really thought about it. I didn't create the feature request for this. I'm just calling out the lack of consistency in user experience. Whichever one is right or whichever one is wrong - in one respect, it doesn't matter: it's inconsistent.

Candidly, I'm out of time for such considerations and am hoping that each of you will practice the preachings of consistency = quality.

**Review by leecalcote — CHANGES_REQUESTED** [review]
Inconsistent UX. Requesting holistically consistent UX.

The `perf` command suffers in a similar vein.

**Comment by navendu-pottekkat** [comment]
- Consistency was the reason I opened the issue and we are creating this PR
  - `context create` has a `--set` flag which `token create` lacked
- This PR **will** ensure consistency across `token`, `context` and `channel`
- Since `channel` does not have a `channel create` command, it does not make sense to have a `--set` flag
- This PR is **not** about which was here first. Both a command and a flag should be used here for consistency

Consistency is key. I agree. I believe this PR is the right way to do that.

**Comment by sayantan1413** [comment]
Hey, @piyushsingariya can you please tell me the possible reason for the failing check?

**Comment by sayantan1413** [comment]
Thanks you @piyushsingariya .

**Pull request merged**
