### PR TITLE
[mesheryctl] fixed system context commands, removed dependency on models/mesheryctl_config.go

### LINKED ISSUE #2490: [mesheryctl] system context commands failing
#### Description
`mesheryctl system context` commands are failing becuase `models/mesheryctl_config.go`  is not updated to reflect updated structs of Token and Context.

Structs should be referred from `config.go`, `models/mesheryctl_config.go` dependency can be removed.

#### Expected Behavior
`mesheryctl system context` commands should work as expected

#### Screenshots/Logs
Screenshot from 2021-02-28 10-10-29

### PR DESCRIPTION
**Pull request by aneeshnema**
**Description**

This PR fixes #2490 

**[Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by navendu-pottekkat — COMMENTED** [review]
Is this the only place where the file from `models` folder was used?

**Comment by leecalcote** [comment]
Out with models! In with config!

**Comment by aneeshnema** [comment]
> Is this the only place where the file from `models` folder was used?

yes, is in mesheryctl that is the only place

**Review by navendu-pottekkat — APPROVED** [review]

**Comment by navendu-pottekkat** [comment]
@leecalcote Could you please merge this?

**Pull request merged**
