### PR TITLE
Fixed broken build-and-release link

### LINKED ISSUE #7394: [Docs]-broken "Build and Release" link
#### Current State
On [project/release](https://docs.meshery.io/project/releases) page the "Build and Release" link gives error404

#### Desired State
It should point to this [page](https://docs.meshery.io/project/contributing/build-and-release)

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by adarshrajpathak**
**Notes for Reviewers**

This PR fixes #7394 

- fixed broken build and release link on [project/releases](https://docs.meshery.io/project/releases) 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 1955e7b7c5223dcb2121834e0bdd112455e49b8f at: https://642027477164c01671f56678--meshery-docs-preview.netlify.app

**Comment by adarshrajpathak** [comment]
please have a review.
@Chadha93 @Nikhil-Ladha @leecalcote

**Review by leecalcote — APPROVED** [review]
LGTM. Thanks much, @adarshrajpathak 👍

**Comment by vishalvivekm** [comment]
Thanks @adarshrajpathak :rocket:

**Pull request merged**
