### PR TITLE
Notification Center 

### PR DESCRIPTION
**Pull request by aabidsofi19**
https://github.com/meshery/meshery/assets/65964225/345672de-3f61-4be0-b3c8-0e7480cc496c

## Notification Center 

The Latest enhancements to the NotificationCenter includes creating a new User Interface , Switching to Graphql Subscriptions and Implementing Robust Filtering . The Events are persisted on Backend and the state management on client is done using Redux Toolkit and RTK . 

User Facing Features Include :

-  A Robust  Filtering Support using Github Style Search based filtering 
-  Proper Hierarchial presentation of error details 
-  Suport for  notification status ( notifications can be marked as read and unread ) 
-  Live Subsription of Events using Graphql subscription  ( backend ) 
-  Infinite scroll for pagination  .

 
## StateManagement and Internal Details 

-  The State on client is managed using `Redux Tooltik` and `Rtk-query` 
-  Update and Delete operations are optimistically handled 
-  Network Request are cached and are invalidated when new events come or events are deleted/updated 
-  Due to need for infinite scroll and optimistic update the events are stored globally in redux 

## Input Based Filtering 

A new resusable component for input based filtering has also been created .  . It adheres to the GitHub-style syntax for filtering, offering a straightforward and adaptable way to filter and search data. 

The state for filtering is managed by a state machine created using reducer , it supports multiple filters ,  suggestions and completions  

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by aabidsofi19** [comment]
* i will run lint , when good to be merged

**Comment by aabidsofi19** [comment]
# TypingFilter Component Documentation

The `TypingFilter` component is a customizable React component that enables real-time filtering and selection based on user input. 
It provides a user-friendly interface for filtering data in your application.

## Table of Contents

- [Usage](#usage)
- [Props](#props)
- [Examples](#examples)

## Usage

The `TypingFilter` component is designed to provide an interactive filtering experience in your application. Here's how you can use it:

```javascript
import React from 'react';
import TypingFilter from './path-to-TypingFilter';

function MyComponent() {
  // Define a filter schema that describes the available filter options.
  const filterSchema = {
    // Define your filter categories here
    // Example:
    SEVERITY: {
      value: "severity",
      description: "Filter by severity",
      values: ["Low", "Medium", "High"],
      multiple : true // default
    },
    // Add more filter categories as needed
  };

  // Define a callback function to handle filter changes.
  const handleFilterChange = (filteredData) => {
    // Implement your logic to react to the filtered data.
    // This function will be called when the user applies a filter. ( on presing enter in input)
    console.log("Filtered data:", filteredData);
  };

  return (
    <div>
      <TypingFilter
        filterSchema={filterSchema}
        handleFilter={handleFilterChange}
      />
      {/* Your other components */}
    </div>
  );
}

export default MyComponent;
```

## Props

The `TypingFilter` component accepts the following props:

- `filterSchema` (object, required): An object that defines available filter options. Each property of this object represents a filter category with the following properties:
  - `value` (string, required): The filter name used for filtering within the category.
  - `description` (string, required): Description of the filter category.
  - `type` (string, optional): The data type of the filter (e.g., "string", "number").
  - `values` (array, optional): Possible values for the filter.

- `handleFilter` (function, required): A callback function that is called when the user applies a filter. This function receives the filtered data as an argument.


# Finite State Machine (FSM) for `TypingFilter` Component

This README provides an overview of the Finite State Machine (FSM) implementation used to manage the state of the `TypingFilter` component. 
The FSM is responsible for handling user interactions, such as selecting filters, entering values, and clearing the filter, within the component.

## Table of Contents

- [Overview](#overview)
- [State Definitions](#state-definitions)
- [Reducers](#reducers)
- [State Transitions](#state-transitions)
- [Initial State Handling](#initial-state-handling)

## Overview

The FSM implementation within the `TypingFilter` component ensures that user interactions are correctly processed and managed, resulting in a smooth and intuitive filtering experience. 

## State Definitions

The FSM code defines three sets of constants to represent important elements within the state management:

### 1. `FILTERING_STATE`

Defines the possible states that the `TypingFilter` component can be in. These states include:
- `IDLE`: Represents the initial state when the component is not actively filtering.
- `SELECTING_FILTER`: Indicates that the user is selecting a filter.
- `SELECTING_VALUE`: Indicates that the user is entering a filter value.

### 2. `FILTER_EVENTS`

Represents the events that trigger state transitions within the FSM. Some of the events include:
- `START`: Initiates the filtering process.
- `SELECT`: Indicates the selection of a filter.
- `INPUT_CHANGE`: Represents a change in the filter input.
- `CLEAR`: Clears the filter.
- `EXIT`: Exits the filtering process.

### 3. `Delimiter`

Defines delimiters used to separate filter and value entries within the component. Delimiters include:
- `FILTER`: Separates multiple filters.
- `FILTER_VALUE`: Separates filters from their corresponding values.

## Reducers

The FSM implementation includes two key reducer functions:

### 1. `commonReducer`

This common reducer function handles events that are common across all states. It includes logic to handle "CLEAR" and "EXIT" events, which reset the component's state and clear any entered values.

### 2. `filterSelectionReducer`

The `filterSelectionReducer` is a specific reducer used to manage transitions between "SELECTING_FILTER" and "SELECTING_VALUE" states. It handles events related to selecting filters and entering values. The logic ensures that delimiters are appropriately added or removed when the user interacts with the filter.

## State Transitions

State transitions are managed based on user actions and the current state of the component. For example, when the user selects a filter, the state transitions from "SELECTING_FILTER" to "SELECTING_VALUE." When the user inputs values or clears the filter, the state transitions are managed accordingly.

## Initial State Handling

The FSM implementation includes handling for the initial state, where it listens for the "START" event to transition from "IDLE" to "SELECTING_FILTER." This ensures that the filtering process is initiated when the user interacts with the component.

**Comment by aabidsofi19** [comment]
@leecalcote  can be reviewed now .

**Comment by leecalcote** [comment]
We need to capture this information in a new Contributing page in Meshery Docs.

**Comment by leecalcote** [comment]
@aabidsofi19 is there a dependency on another PR that we need to be aware of?

**Comment by leecalcote** [comment]
I added a new docs page.

**Comment by l5io** [comment]
🚀 Preview for commit dc0a3cd89611e88b2529f7e73cd5c40d109942c9 at: https://6504bcee0c4f2c278c04bc78--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit cdae34974df47b88250656bbe2c0abefc6791117 at: https://6504c3e190e9f32b15c2009f--meshery-docs-preview.netlify.app

**Comment by leecalcote** [comment]
@aabidsofi19 when marking a notification read, it doesn't seem to go to the archive section/status. If it is supposed to, the archive section icon is different than the read / unread checkmark icon, causing some confusion as to whether these are the same or different. In the future, when Acknowledge and Resolve actions are supported, they are likely to use a checkmark style icon, which will be the need for some refactoring. Can we do this now? - 

1. Add an "Archive" action using the archive icon to send the event to the archive view (increment the archived event count and change status to archived).
2. Change "Mark as Read" and "Mark as Unread" icons to the two ReadIcon and UnreadIcons that I have added to this branch (display or hide the extra vertical bar on the lefthand side of the notification).
3. Automatically, invoke the Mark as Read behavior upon unfurl of notification details.

Is it easy enough to:
1. Remove social network buttons from view until the Share button is clicked?

**Comment by l5io** [comment]
🚀 Preview for commit 0cbc2a86d8892b98e1b5e7499884b3f05ea97743 at: https://6504eb4308aa414003900b57--meshery-docs-preview.netlify.app

**Comment by leecalcote** [comment]
I'm not sure if this sort of behavior is occurring because I'm running this branch under `make ui`:3000 or not, but read status and archive count are off.
Screenshot 2023-09-15 at 6 42 07 PM

**Comment by aabidsofi19** [comment]
@leecalcote 
>1. Add an "Archive" action using the archive icon to send the event to the archive view (increment the archived event count and change status to archived). 
 - currently we are archiving by marking as read ( there is no archive status in backend ) 
> 2. Change "Mark as Read" and "Mark as Unread" icons to the two ReadIcon and UnreadIcons that I have added to this branch (display or hide the extra vertical bar on the lefthand side of the notification). 
 - Thanks ,   i will add them 
> 3. Automatically, invoke the Mark as Read behavior upon unfurl of notification details.
-  Makes sense 
> Is it easy enough to:
> 1. Remove social network buttons from view until the Share button is clicked?
-  yup it should be easy .

**Comment by aabidsofi19** [comment]
> @aabidsofi19 is there a dependency on another PR that we need to be aware of?

No everthing is based on master

**Comment by aabidsofi19** [comment]
> I'm not sure if this sort of behavior is occurring because I'm running this branch under `make ui`:3000 or not, but read status and archive count are off. Screenshot 2023-09-15 at 6 42 07 PM

as in picture , there is only one read ( the one with thicker border) , and the count is also one .

**Comment by l5io** [comment]
🚀 Preview for commit 95949a9d115219df709b5345903db626e356e59a at: https://650567c91b7ad9777486d39a--meshery-docs-preview.netlify.app

**Comment by aabidsofi19** [comment]
New Changes : 
- Change the status icons ( in header and in the mark as read/unread )
- Add slide animation when removing a filter from view 
- Remove notification from view on change of status if user is in a filtered view with status filter set other wise only mark it ( by showing that thick border ) 
- Change the archive icon to read icon and add tooltips  about the category

**Comment by l5io** [comment]
🚀 Preview for commit ea6463740be89bd39cf4c1c2f682a75405ac0340 at: https://65057368ef6fec7443b2c41b--meshery-docs-preview.netlify.app

**Comment by aabidsofi19** [comment]
New Changes :

- Change the status icons ( in header and in the mark as read/unread )
- Add slide animation when removing a filter from view
- Remove notification from view on change of status if user is in a filtered view with status filter set other wise only mark it ( by showing that thick border )
- Change the archive icon to read icon and add tooltips about the category

Just for Info : 

i have added a filteredViews support in statemanagement so we might in future be able to add the predefined ( saved) filter views support also .

**Comment by leecalcote** [comment]
> it might confuse users as some important notification gets marked as read automatically and they might think they lost it . ( thats why i didnt move them instantly when marked as read )

It absolutely would, which is why you're going to ask for an "archived" status on the backend.

**Comment by l5io** [comment]
🚀 Preview for commit 3c73dc5892fe9c5eb85942536729238ce90cd533 at: https://6505d9d3a043592e43680e0a--meshery-docs-preview.netlify.app

**Pull request merged**
