### PR TITLE
error boundary class to functional 

### PR DESCRIPTION
**Pull request by krishkumar84**
**Notes for Reviewers**

This PR fixes ##11493

in this pr i convert error boundary class component to functional  and use SistentErrorBoundary
and also convert mesherydatetime picker from class to function based component 
@leecalcote @nebula-aac @Yashsharma1911 kindly review this

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by krishkumar84** [comment]
> in this pr i convert error boundary class component to functional and use SistentErrorBoundary
> 
>  @Yashsharma1911 according to you i choosing subtask to work on UI Migration from MUI v4 to MUI v5 and Sistent #11493  this issue and contributing and i want to contribute more and participating in dev meetings and meet with community people and maintainers and also contribute in past in other layer5 repos as i want to contributing more on this issue through the LFX mentorship

**Comment by Ashparshp** [comment]
@krishkumar84 let's discuss this PR during the Meshery dev meeting call, if you would. Please add it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit?usp=drivesdk).

**Comment by leecalcote** [comment]
Thanks, @krishkumar84! Will you investigate why the build check is failing here? https://github.com/meshery/meshery/actions/runs/10351991000/job/28651657180?pr=11620

**Comment by krishkumar84** [comment]
@leecalcote  sure i will look into that and fix !

**Comment by leecalcote** [comment]
@sudhanshutech should this be resurrected?

**Pull request closed without merging**
