### PR TITLE
[chore] Support for Visibility in Content APIs | CU-85ztrgw1z

### PR DESCRIPTION
**Pull request by theBeginner86**
**Notes for Reviewers**

This PR adds  support for visibility filtering to 
1. Content APIs (patterns and filters).
2. GraphQL Configuration Subscription 
3. GraphQL Pattern/Filters Query 

Use case example:
1. API: 

Eg:
```
?visibility=["public", "published"]
```

2. GraphQL: Pass an array of visibility flags here: https://github.com/meshery/meshery/blob/575322bd435de01ab16090a03bdd942fc86e7d0f/ui/components/Filters.js#L677
https://github.com/meshery/meshery/blob/575322bd435de01ab16090a03bdd942fc86e7d0f/ui/components/MesheryPatterns.js#L505

Eg:
```
patternSelector: {
          pageSize: pagesize,
          page: pageNo,
          search: searchText,
          order: order,
            visibility: [VISIBILITY.PUBLISHED],
        }
```
```
        filterSelector: {
          pageSize: pagesize,
          page: pageNo,
          search: searchText,
          order: order,
          visibility: [VISIBILITY.PUBLISHED],
        },
```

This PR fixes https://github.com/meshery/meshery/issues/8547

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 18a8b25be9e59df1aeb8cb9f2a9fb3d1de08b3c3 at: https://65338c5c42df067e0a158e6c--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 745754495559ca20acbc83e3e0852114a7fc807b at: https://65338df3598cac4c077894f8--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 0d2c670ea29aa191afe4aa007b9dc8d160503278 at: https://65339724d9bdce033c8c9401--meshery-docs-preview.netlify.app

**Comment by aabidsofi19** [comment]
Thankyou @theBeginner86 .  for the events api we are using a array to pass multiple filters , can we use the same structure here , so we remain consistent and reuse the same functions and utils to parse and generate them .

**Comment by l5io** [comment]
Task linked: [CU-85ztrgw1z Update API of Content Endpoints to support filtering](https://app.clickup.com/t/85ztrgw1z)

**Comment by l5io** [comment]
Task linked: [CU-85ztrgw1z Update API of Content Endpoints to support filtering](https://app.clickup.com/t/85ztrgw1z)

**Comment by theBeginner86** [comment]
> Thankyou @theBeginner86 . for the events api we are using a array to pass multiple filters , can we use the same structure here , so we remain consistent and reuse the same functions and utils to parse and generate them .

I see you're referring to the `actions`, `severity`, and `category` parameters in v2/events. I can update the visibility parameter to work as an array. It's worth noting that the events API is the only place where we use an array to represent filters, while in other APIs, we use strings for filters. // @MUzairS15 
An older comment from @leecalcote at https://github.com/layer5io/meshery-cloud/pull/1481#issuecomment-1718302045 for related discussions about query param requirement for filtering. 


Nevertheless, I'll make the necessary updates to this PR. 👍

**Comment by theBeginner86** [comment]
@aabidsofi19, 
Updated 👍 

Looks good?

Screenshot 2023-10-22 at 6 57 19 PM
Screenshot 2023-10-22 at 6 54 41 PM

**Comment by l5io** [comment]
🚀 Preview for commit 1d27e7d598be0f52c95e2af6ad3edd07a6a53d6b at: https://653524a4307ae26eaec8504c--meshery-docs-preview.netlify.app

**Review by aabidsofi19 — APPROVED** [review]
Looks great :clap:

**Pull request merged**
