### PR TITLE
fix: #9399 Changed hover effect on Kubernetes config modal

### LINKED ISSUE #9399: [UI] Kubernetes Config Modal Hovering Effect Deviation
### Current Behavior
[284250329-71a5d129-b84d-4628-a3e7-46aeb4e66716.webm](https://github.com/meshery/meshery/assets/128807866/395a1e07-ace0-489b-b42d-8948198435f6)

### Desired Behavior
We should be using our standard  styling for action buttons.

### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by Raj100679**
**Notes for Reviewers**
I have updated hovering effect on Kubernetes config modal

This PR fixes #9399 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by vaibhavpnimkar** [comment]
hey why you closed your pr you did it right

**Comment by vaibhavpnimkar** [comment]
and if you are struggling with dco check then:
git config --global user.name "Your Name"
git config --global user.email "[your.email@example.com](mailto:your.email@example.com)"
git add .
git commit -s -m "your msg" // this will sign-off your commit
git push

run this

**Comment by Raj100679** [comment]
Actually I was stuck with dco thing, thought will create a new fork and then push the things again wirh signoff commits

**Comment by vaibhavpnimkar** [comment]
ya you can also follow steps i have provided you above

**Pull request closed without merging**
