### PR TITLE
UI: Remove smi conformance results chip

### LINKED ISSUE #1671: [UI] Remove "SMI Conformance results" chip from all Adapter pages
**Current Behavior**
The SMI Conformance results chip is shown in each Adapter page.

**Desired Behavior**
This chip (button) was a temporary solution. Now that a permanent solution is in place, it can be removed.

**Screenshot**

Adapter chip:

Screen Shot 2020-10-11 at 8 00 18 PM

### PR DESCRIPTION
**Pull request by daksh-sagar**
Signed-off-by: Daksh Sagar <daksh.sagar@yahoo.com>

**Description**

This PR fixes #1671 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by daksh-sagar** [comment]
istio
This is how it looks !

**Comment by daksh-sagar** [comment]
@leecalcote

**Comment by KarenEfereyan** [comment]
Nice work @daksh-sagar. This looks good @leecalcote it can be merged

**Review by leecalcote — APPROVED** [review]
Thank you, @daksh-sagar and @KarenEfereyan. 👍

**Review by KarenEfereyan — COMMENTED** [review]
Great job

**Pull request merged**
