### PR TITLE
[models] Consolidate Meshery Docs Generator

### PR DESCRIPTION
**Pull request by theBeginner86**
**Notes for Reviewers**

Related PRs:
1. https://github.com/meshery/meshery.io/pull/1585
2. https://github.com/layer5io/layer5/pull/5288

This PR fixes #

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
I can't help but share this before I toss it away:

```
 ---
layout: enhanced
title: Antrea
permalink: extensibility/integrations/antrea
type: extensibility
category: integrations
integration-category:
    - name: Runtime
      icon:  
        - /assets/img/integrations/category/runtime-green.svg
        - /assets/img/integrations/category/runtime-white.svg
integration-subcategory: 
    - name: Cloud Native Network
      icon:  
        - /assets/img/integrations/antrea/antrea-color.svg
        - /assets/img/integrations/antrea/antrea-white.svg
integration-model:
    - name: Antrea
      icon:  
        - /assets/img/integrations/antrea-color.svg
        - /assets/img/integrations/antrea-white.svg
integration-components:
    - name: Antrea
      icon:  
        - /assets/img/integrations/antrea-color.svg
        - /assets/img/integrations/antrea-white.svg
    - name: Antrea
      icon:  
        - /assets/img/integrations/antrea-color.svg
        - /assets/img/integrations/antrea-white.svg
integration-description: Antrea is a Kubernetes-native project that implements the Container Network Interface (CNI) and Kubernetes NetworkPolicy thereby providing network connectivity and security for pod workloads. Antrea extends the benefit of programmable networks from Open vSwitch (OVS) to Kubernetes.
display-title: "false"
language: en
list: include
---
```

Or something similar...

**Comment by l5io** [comment]
🚀 Preview for commit 16190c83a4097d6a2021fd3a8a5348f6aa5beaf4 at: https://65a553361af6e52033c0446a--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit e88c63a57d8503ffb2aa07e5080fd5f8a66beb24 at: https://65a581051c6b6522765ada55--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 8965bc41822e74e03d7b19f2b99492993ae5555e at: https://65a5ad99eef9103c77f5f523--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 51e4374a3eedb360b91155b5bffb935b9af7958c at: https://65a5c600a79a9250b1a848a5--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 711b1b55e6b7de0701b4fc4c5529ec2ace7bdce6 at: https://65a5d503faf43958861045cf--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 6e8547823454c6b1855ecc3ae6de4c61edf0ea0c at: https://65a7d55043d2070e0e825e60--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 3c2b911eaf6b51d92d37b922fb5f26eaa313bca4 at: https://65a8109190850a10322b0eeb--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 805151faf02e652dae42fcfcd99a2e83b00d714f at: https://65a81efc92a6fd00a6ed14a4--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 4b2de6e5c2cf4f6b7eeafad18fb02d2b4aec858f at: https://65a824f2a09e9600a58a1235--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 8a0944226db2d9ecb2544350516d7e7843f513af at: https://65a8263e7117b506ac071d4a--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 3ebfd8eedbdd3a214b8669a612957fdabb8c7b1f at: https://65a9948a375cd50d893c0b89--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 889c18c5dc2e1532c5ab8c1d88080e606bf0e848 at: https://65a99b66c515a30ad626cf59--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit f086116dc80f2fb6c838c2bbe040b9dc07c2b096 at: https://65a9f68ad86bec490895b3b2--meshery-docs-preview.netlify.app

**Comment by theBeginner86** [comment]
// @leecalcote @vishalvivekm

**Pull request merged**
