### PR TITLE
issue #7048 : Updating broken "UI" and "Meshery UI" links for getting Authentication Token

### LINKED ISSUE #7048: [Docs]"Meshery UI" and "UI" links direct to path `/concepts/architecture/ui` -> returns 404
#### Current State

"Meshery UI" and "UI" links direct to path `/concepts/architecture/ui` -> returns 404 (See attached SS)

image

image

image

#### Desired State

Unknown.

Quick fix, would be easy for new contributor.

Paths easily pound in meshery docs.

@Chadha93 say where UI link needs to point. 
---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by vishalvivekm**
**Notes for Reviewers**

This PR fixes #7048 

 The "UI" link on [extensibility page](https://docs.meshery.io/extensibility/api#what-are-authentication-tokens-1) and "Meshery UI" link in guides [here](https://docs.meshery.io/guides/mesheryctl/authenticate-with-meshery-via-cli#get-your-token) direct to path /concepts/architecture/ui,
which results in error404.
As both these links ( "UI' and "Meshery UI" ) are referenced for getting Authentication Token using Meshery UI,
 I've made them point to [this section](https://docs.meshery.io/extensibility/api#:~:text=Using%20Meshery%20UI,of%20profile%20section) which shows steps to get the Token using Meshery UI.  

Signed-off-by: Vivek Vishal <110674407+vishalvivekm@users.noreply.github.com>

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit ad721444e85ff7c9e1219124629487e758f33b95 at: https://63ea7dc438e9a01002a8df63--meshery-docs-preview.netlify.app

**Review by Revolyssup — APPROVED** [review]

**Review by b0id — CHANGES_REQUESTED** [review]
This works @leecalcote , but #7407 has the same links, Merge #7407 and let @vishalvivekm do the same there.

**Comment by vishalvivekm** [comment]
> 
Okay, So once @leecalcote merges #7404 , then I can update these links there ? 

@b0id can you please be a bit more elaborative as in what's there for me to do next in this issue ?
Thanks!

**Comment by b0id** [comment]
> > 
> 
> Okay, So once @leecalcote merges #7407, then I can update these links there ?
> 
> @b0id can you please be a bit more elaborative as in what's there for me to do next in this issue ? Thanks!

@vishalvivekm 
The API reference (both GraphQL and REST API guide) gave the same link that you modified in your PR, see #7407 for the files that were modfied for reference.

**Comment by vishalvivekm** [comment]
> > > 
> > 
> > 
> > Okay, So once @leecalcote merges #7407, then I can update these links there ?
> > @b0id can you please be a bit more elaborative as in what's there for me to do next in this issue ? Thanks!
> 
> @vishalvivekm The API reference (both GraphQL and REST API guide) gave the same link that you modified in your PR, see #7407 for the files that were modfied for reference.

Yeah got it now. Thanks for the help.
Should I like go modify those links there and create a PR ? @b0id

**Comment by Chadha93** [comment]
@vishalvivekm  Let's discuss this on the Meshery Dev call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#) if you would. :)

**Comment by vishalvivekm** [comment]
> @vishalvivekm Let's discuss this on the Meshery Dev call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#) if you would. :)

Yeah Sure, I'm adding this issue in the topics, with my name, will that be good ?

**Review by leecalcote — APPROVED** [review]
Thanks, @vishalvivekm 👍

**Pull request merged**
