### PR TITLE
Updated Kuma Logo

### LINKED ISSUE #1153: Update Kuma logo in README
**Description**
This logo is missing.

**Related**
https://github.com/layer5io/meshery.io/issues/219

### PR DESCRIPTION
**Pull request by ashiscs**
fixes #1153 
Signed-off-by: ashiscs <ashissingh640@gmail.com>

### CODE REVIEW

**Comment by ashiscs** [comment]
This pr should be merged after merging this [pr](https://github.com/layer5io/meshery.io/pull/220)

**Comment by leecalcote** [comment]
After you copy the image file to this repo, let's merge.

**Comment by ashiscs** [comment]
> After you copy the image file to this repo, let's merge.

Done sir !!

**Comment by ashiscs** [comment]
> @ashiscs did you verify this update?
> 
> The relative reference will likely have to be `docs/service-meshes/adapters/kuma/Kuma.svg`

Yes sir i verified it !

**Comment by ashiscs** [comment]
Screenshot from 2020-06-23 14-01-14

**Comment by leecalcote** [comment]
Looking good. 😄

**Pull request merged**
