### PR TITLE
Create Individual doc pages (WIP)

### LINKED ISSUE #2608: [Docs] Add Individual doc pages for `mesheryctl` commands
**Current State:**
It's been 5 days since the `mesheryctl` command reference has got a makeover, but it's void of individual doc pages, therefore each doc page has to be created for every command so that it can be linked to the table later on. 

**Desired State:**

The reference page must be updated with links to individual doc pages. Hence, this can be a big work, and can be spliced up into smaller tasks if granted. FYI, this is Phase-2 of the makeover. 

---
**Contributor Resources**
- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

### PR DESCRIPTION
**Pull request by alphaX86**
**Description**

This PR fixes #2608

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by alphaX86** [comment]
@leecalcote I recently noticed that the command tracker spreadsheet is now updated. So do I need to update them side by side then? Like previous PR I made??

**Comment by navendu-pottekkat** [comment]
@alphaX86 Yes, the Command Tracker page should be the true value everytime. So any changes made there should be reflected back here. But I do not think any major changes happened recently. Could you specify what change you are referring to?

**Comment by alphaX86** [comment]
> @alphaX86 Yes, the Command Tracker page should be the true value everytime. So any changes made there should be reflected back here. But I do not think any major changes happened recently. Could you specify what change you are referring to?

Well I meant some experimental commands are added and some new commands are added in `pattern`. That's why I asked should I update them

**Comment by navendu-pottekkat** [comment]
The pattern commands are still WIP I guess. I guess once we have it ready we can add to it. It should not be an issue.

**Comment by alphaX86** [comment]
@leecalcote @navendu-pottekkat doc pages are ready and I linked them in the command reference table (some commands aren't updated as they're new) and Lee, I didn't feel that `_config.yml` must be changed, as it printed exactly the changes and output is fine. But review them and suggest any feedback. (Especially on the layout)

**Comment by alphaX86** [comment]
The URL now works... I need feedback on layout though

**Review by navendu-pottekkat — COMMENTED** [review]
🏋🏼  Heavy lifting! You will be jacked up in no time! 💪🏼 

Couple of _suggestions_-

It would be better if each sub-command had a separate page dedicated to it. I will again refer that to the design of [GitHub CLI docs](https://cli.github.com/manual/gh_gist_create).

The individual doc pages should have more information than what we provide in the Command Reference Table.

The users should be able to get a clear idea of what each flag/subcommand does. This could be done by providing examples with clear comments on top as in [GitHub CLI docs](https://cli.github.com/manual/gh_gist_create).

For the layout, I guess we do not need to have separate code blocks for each one and can have it in a single block. Same goes for all the other code blocks.

Screenshot from 2021-04-09 16-20-39

I'm suggesting to refer the [GitHub CLI docs](https://cli.github.com/manual/gh_gist_create) because what they have done works really well and I believe that it should work just as well for mesheryctl docs and would make the life of the users much easier.

// @leecalcote @alphaX86 what do you think?

**Comment by alphaX86** [comment]
Hmm, need to refer those docs then for idea

**Comment by alphaX86** [comment]
I hope it ends within Mon, coz I need to look on internal exams too. 😫 I'll try to finish this within this week...

**Comment by navendu-pottekkat** [comment]
@alphaX86 Thanks for the update! Ping me and I will try to review things ASAP and not be a blocker.

**Comment by alphaX86** [comment]
Thanks! I'll let you know once it's done

**Comment by alphaX86** [comment]
Almost done... But IDK how to remove the sidebar on this one....

image

**Comment by alphaX86** [comment]
Plus, some formatting is a bit upside down, IDK what causes this

**Comment by alphaX86** [comment]
And @navendu-pottekkat how to add comments like this for examples as in GitHub CLI Docs? Any ideas? Or should I include  
description part (in YAML) as such (may cause repetition)? 

image

**Comment by alphaX86** [comment]
@navendu-pottekkat could you check and tell me what it lacks and needs to be done? IG I can work upto Tuesday for this...

**Comment by navendu-pottekkat** [comment]
Thank you @alphaX86 . I will review it and update ASAP.

**Review by navendu-pottekkat — COMMENTED** [review]
Formatting issue-

Screenshot from 2021-04-11 21-18-07

Not an issue particular to here since what you have added is what is in the tracker document but we need to add better descriptions for each set of commands that would explain their scope to the user-

Screenshot from 2021-04-11 21-19-14

I might have not been clear with the statement I left on my previous review-

> It would be better if each sub-command had a separate page dedicated to it.

What I mean by this is that say for the `system context` command, instead of having all its sub-commands (`create``delete``switch``view`) in the same page, we can have separate pages for each of these commands. And `system context` will have a link to a page which gives a broad description of the command and then links to its sub-commands.

Screenshot from 2021-04-11 21-21-25

This should make the docs more readable. It might get confusing in cases where there are flags which are local to only one sub-command. It would be best if we can get some suggestions on this // @layer5io/meshery-docs-contributors 

In total, the changes looks really good 💯  and this would prove to be really useful. 🚀 Thank you @alphaX86

**Comment by alphaX86** [comment]
Hmm, separate pages for subcommands huh? Might take time but will do it then

**Comment by alphaX86** [comment]
@navendu-pottekkat PR is ready :)

There may be slight variations for example `validate` coz command is just one and I don't think it needs a separate subcommand page.
Other than that, I've created pages. This should hold for long

**Comment by alphaX86** [comment]
If anything needs to be done, I think I or someone can do it in next PR (I mean after 2 weeks coz internals starting from Fri-Sat) so yep...

**Comment by navendu-pottekkat** [comment]
Did a quick check. The created individual pages looks good. There are some missing pages though, I think once we add that we are good to go.

Screenshot from 2021-04-14 22-08-42

**Comment by alphaX86** [comment]
> Did a quick check. The created individual pages looks good. There are some missing pages though, I think once we add that we are good to go.
> 
> Screenshot from 2021-04-14 22-08-42

I also guessed it. But won't it be a bit vague if we just included only command and example, and no flags for those commands? 🤔 We need to decide later on... @layer5io/meshery-docs-contributors what do you think of this guys?

**Comment by leecalcote** [comment]
@alphaX86 I'll do a quick review here...

**Comment by alphaX86** [comment]
Good to go

**Comment by leecalcote** [comment]
Awesome, @alphaX86. 💯 It was nice getting to chat with you on this, too.

**Pull request merged**
