### PR TITLE
Minimizing the number of files in the root directory of Meshery

### PR DESCRIPTION
**Pull request by EleisonC**
**Description**
Minimizing the number of files in the root directory of Meshery

Signed-off-by: Christopher Kalule <christopher.kalule21@gmail.com>
This PR fixes #
For https://github.com/meshery/meshery/issues/5667
**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 87a11d457e1fa57906f8d96999b5d2fbe46fbb6e at: https://62d59e6b14226e24c58e7d96--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 8ccaacda12e8c5a22ba6984de995f3c179146ed7 at: https://62d66e0be9ce89632e60839b--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit db22851daa3411210964e0430a4bb002dda1a5c4 at: https://62d674daa723ce6d24939a39--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit ce6a6c30d3f2363ed3efa1ece095cbfc83e78cf7 at: https://62d67ffd4a395b7567fa82fb--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 9956e1265b9b1f0a1901f5f4d43774a3affd2355 at: https://62d6947ecec48609bbd0dc63--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit bf9ba63598b08aeefaea8a762b6b79368f19e25d at: https://62d69914cb3c6d05c59672fa--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 327bf4629d9552bd8ad3352944a2dd97d2966dd7 at: https://62d6a4e247c2c21c84c15339--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 99ac45d2560bc47b413c3ab6f9f6e056f47b2cf7 at: https://62d6b8f71b180c2e37491779--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 81eadc133d1ed9c2a39ff2b63f284f96c9907561 at: https://62d70af663025a114b460c6a--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 1225fcd2b8ce44f0af691670f618cd7068eecba7 at: https://62d70da7fd285e13550f6ca4--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 2d3dc70c258be5526a020a1de87153bab9897970 at: https://62d71144d7886317e028603c--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 7ab5331023d3410285fbe025f17449d1086b88f7 at: https://62d7175ccd5e5e1d69444dd6--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 07437855f44112a4fc09b79f4f7e6b5c6ea1457a at: https://62d7a44db37fce01a26eeb93--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 5a105d90ecedf8b8c31ce135f1a294196c171e1a at: https://62d7aebf2d20e50a6d859420--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 1e2ed155704ee5419d2ad304c22d0cfb41479749 at: https://62d7cdd0b335a12503f85f41--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 07a5f9a3e31aca21b79a174516cde24c66575baa at: https://62d7d2386cacf929b8e92e7b--meshery-docs-preview.netlify.app

**Comment by alphaX86** [comment]
Great changes @EleisonC I must admit 👀 this is a great PR

**Comment by leecalcote** [comment]
> Great changes @EleisonC I must admit 👀 this is a great PR

👏 @EleisonC 


// @meshery/maintainers

**Comment by l5io** [comment]
🚀 Preview for commit bf2bdd4e76ca3c163a363f4dfdb6dd99747e3fb2 at: https://62d9cbd9850ae1009e2d59ce--meshery-docs-preview.netlify.app

**Comment by leecalcote** [comment]
Straight greens ✅

**Comment by leecalcote** [comment]
@Revolyssup @sudo-NithishKarthik please give this a once-over.

**Comment by l5io** [comment]
🚀 Preview for commit 85aeed2c3c9ecae6f29f6758088db2b890f79cc4 at: https://62dad60f21588315f6af973e--meshery-docs-preview.netlify.app

**Comment by Revolyssup** [comment]
@EleisonC  Can you please resolve the merge conflicts? Rest looks good to me so far.

**Comment by Revolyssup** [comment]
@EleisonC  Fix the path on line 1366 inside server/models/default_local_provider.go

**Comment by Revolyssup** [comment]
@EleisonC  Also change the path in Provider-UI handler.

**Review by Revolyssup — COMMENTED** [review]
Please make the asked changes.

**Comment by l5io** [comment]
🚀 Preview for commit e05674b83916e5e3fb095c8db595f6da86a93145 at: https://62de907ef9c9ed1695848ec8--meshery-docs-preview.netlify.app

**Comment by EleisonC** [comment]
> 

Hello @Revolyssup I am a bit stuck on where exactly to make the changes in the Provider-UI handler mind guiding me

**Comment by l5io** [comment]
🚀 Preview for commit 01f1da59184df0249eb66885b8a8f047d4e62a97 at: https://62de957f6771c81b4c05c8a8--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 2ad3706719887f17ba41b5f4b35efd2738f0646b at: https://62deaf75a972fa3c1ac2c6d2--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 41aad5b5ff8e2b372d74ea57d98b6d5e6ececfbf at: https://62ded82bb50ddd5c934cb0db--meshery-docs-preview.netlify.app

**Comment by leecalcote** [comment]
@meshery/maintainers please have a look here and offer comment on @EleisonC's hard work.

**Comment by leecalcote** [comment]
@EleisonC heads-up: there are a few merge conflicts to address.

**Comment by l5io** [comment]
🚀 Preview for commit 4567005f57a26ccbc7d66d667399998c0d9ac199 at: https://62e27c71163c450c330d0b5c--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 76aaff5641f223cb95b4c4fdeb36386ed1e42295 at: https://62e28a55569b03165a8e99f0--meshery-docs-preview.netlify.app

**Comment by leecalcote** [comment]
After I build the UI and Server, then authenticate, I get `404 page not found` at localhost:9081

**Comment by Revolyssup** [comment]
> Also change the path in Provider-UI handler.

Yes my above comment pointed exactly to this with how to resolve it. 
https://github.com/meshery/meshery/pull/5837#issuecomment-1193744754

**Comment by leecalcote** [comment]
> > Also change the path in Provider-UI handler.
> 
> Yes my above comment pointed exactly to this with how to resolve it. [#5837 (comment)](https://github.com/meshery/meshery/pull/5837#issuecomment-1193744754)

Oh, I see. That's great. 

@EleisonC ping when you've made these updates.

**Comment by EleisonC** [comment]
> 

Hey, @leecalcote @Revolyssup I already made the path changes. And @leecalcote I ran the `make build-ui` and I was able to authenticate successfully and got to the dashboard on `localhost:9081`

**Comment by Revolyssup** [comment]
> > 
> 
> Hey, @leecalcote @Revolyssup I already made the path changes. And @leecalcote I ran the `make build-ui` and I was able to authenticate successfully and got to the dashboard on `localhost:9081`

Thats good progress! Also did you make sure that all/if any hardcoded paths are changed/removed correctly?

**Comment by l5io** [comment]
🚀 Preview for commit a5d881192dbbcf796952406b0ee1169ad0c400e2 at: https://62e80f0017cd1600c52e90ae--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 30189b1d516d77564cb151259a92b116a11b03ec at: https://62e81859c9075909acd7b2b1--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 4420b9c81b1edb8a2b1189b3c10d3b13c4184595 at: https://62e81dfb2f372b10f7635a89--meshery-docs-preview.netlify.app

**Comment by leecalcote** [comment]
I get the following output while building from this branch:

```
cd server; cd cmd; go1.17.8 mod tidy; \
	BUILD="v0.6.0-rc.6f" \
	PROVIDER_BASE_URLS="https://meshery.layer5.io" \
	PORT=9081 \
	DEBUG=true \
	ADAPTER_URLS="localhost:10000 localhost:10001 localhost:10002 localhost:10004 localhost:10005 localhost:10006 localhost:10007 localhost:10009 localhost:10010 localhost:10012" \
	APP_PATH="./apps.json" \
	go1.17.8 run main.go;
go: finding module for package github.com/layer5io/meshery/models
go: finding module for package github.com/layer5io/meshery/handlers
go: finding module for package github.com/layer5io/meshery/internal/graphql/model
github.com/layer5io/meshery/internal/graphql/resolver imports
	github.com/layer5io/meshery/handlers: no matching versions for query "latest"
github.com/layer5io/meshery/internal/graphql/resolver imports
	github.com/layer5io/meshery/internal/graphql/model: no matching versions for query "latest"
github.com/layer5io/meshery/internal/graphql/resolver imports
	github.com/layer5io/meshery/models: no matching versions for query "latest"
# github.com/layer5io/meshery/server/internal/graphql/resolver
../internal/graphql/resolver/schema.resolvers.go:277:10: r.subscribeConfiguration undefined (type *subscriptionResolver has no field or method subscribeConfiguration, but does have SubscribeConfiguration)
make: *** [server] Error 1
```

**Comment by l5io** [comment]
🚀 Preview for commit 91889e7a3fd7a17c777adfb73366c57d98ccab86 at: https://62e8eadd38e8de2e97a7bd9a--meshery-docs-preview.netlify.app

**Comment by EleisonC** [comment]
> I get the following output while building from this branch:
> 
> ```
> cd server; cd cmd; go1.17.8 mod tidy; \
> 	BUILD="v0.6.0-rc.6f" \
> 	PROVIDER_BASE_URLS="https://meshery.layer5.io" \
> 	PORT=9081 \
> 	DEBUG=true \
> 	ADAPTER_URLS="localhost:10000 localhost:10001 localhost:10002 localhost:10004 localhost:10005 localhost:10006 localhost:10007 localhost:10009 localhost:10010 localhost:10012" \
> 	APP_PATH="./apps.json" \
> 	go1.17.8 run main.go;
> go: finding module for package github.com/layer5io/meshery/models
> go: finding module for package github.com/layer5io/meshery/handlers
> go: finding module for package github.com/layer5io/meshery/internal/graphql/model
> github.com/layer5io/meshery/internal/graphql/resolver imports
> 	github.com/layer5io/meshery/handlers: no matching versions for query "latest"
> github.com/layer5io/meshery/internal/graphql/resolver imports
> 	github.com/layer5io/meshery/internal/graphql/model: no matching versions for query "latest"
> github.com/layer5io/meshery/internal/graphql/resolver imports
> 	github.com/layer5io/meshery/models: no matching versions for query "latest"
> # github.com/layer5io/meshery/server/internal/graphql/resolver
> ../internal/graphql/resolver/schema.resolvers.go:277:10: r.subscribeConfiguration undefined (type *subscriptionResolver has no field or method subscribeConfiguration, but does have SubscribeConfiguration)
> make: *** [server] Error 1
> ```

Hey, @leecalcote so I also get the same error but I remember seeing a workaround which was commenting out # `GOVERSION = 1.17.8` in the makefile.core.mk file ln 22

**Comment by EleisonC** [comment]
> > > 
> > 
> > 
> > Hey, @leecalcote @Revolyssup I already made the path changes. And @leecalcote I ran the `make build-ui` and I was able to authenticate successfully and got to the dashboard on `localhost:9081`
> 
> Thats good progress! Also did you make sure that all/if any hardcoded paths are changed/removed correctly?

Hey @Revolyssup I made the hardcoded paths changes. You could help me re-review if i missed out on any

**Comment by leecalcote** [comment]
> Hey, @leecalcote so I also get the same error but I remember seeing a workaround which was commenting out # `GOVERSION = 1.17.8` in the makefile.core.mk file ln 22

Oh, no. We might have to dig in here further. The 1.17.8 version of golang is what is pervasively used across all the components of Meshery and is considered a mandatory setting as this is what released builds will use. Hmm. I wonder what is causing the issue with 1.17.8.

**Comment by EleisonC** [comment]
Hey, @leecalcote I might have mixed up errors. Mind running the branch again with the updates made

**Comment by l5io** [comment]
🚀 Preview for commit a4a4f39d024c5b3176244c506b5a6bd7b87a663c at: https://62ebd24a46eb4b191c3c4dd4--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit b96dc49522b26047bacd0d49538234698e9efaae at: https://62ec0b5745349f106a39b608--meshery-docs-preview.netlify.app

**Comment by leecalcote** [comment]
I'm able to build and use Meshery now. I did bump into this issue:

```
INFO[0038] performance profiles successfully retrieved from remote provider
13:46:47 http: panic serving [::1]:63776: proto: file "meshops.proto" is already registered
	previously from: "github.com/layer5io/meshery/server/meshes"
	currently from:  "github.com/layer5io/meshery/meshes"
See https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict

goroutine 247 [running]:
net/http.(*conn).serve.func1()
	/Users/lee/sdk/go1.17.8/src/net/http/server.go:1802 +0xb9
panic({0x64a7340, 0xc0075e7e70})
	/Users/lee/sdk/go1.17.8/src/runtime/panic.go:1047 +0x266
google.golang.org/protobuf/reflect/protoregistry.glob..func1({0x6e71c20, 0x6f49538}, {0x6e71c20, 0xc0075e7e60})
	/Users/lee/code/go/bin/pkg/mod/google.golang.org/protobuf@v1.28.0/reflect/protoregistry/registry.go:54 +0x1f4
google.golang.org/protobuf/reflect/protoregistry.(*Files).RegisterFile(0xc00012a180, {0x6f49538, 0xc001c82e00})
	/Users/lee/code/go/bin/pkg/mod/google.golang.org/protobuf@v1.28.0/reflect/protoregistry/registry.go:128 +0x399
google.golang.org/protobuf/internal/filedesc.Builder.Build({{0x6e9c9a0a, 0x22}, {0x702ca6e0, 0x849, 0x849}, 0x2, 0x10, 0x0, 0x1, {0x6e9e4f8, ...}, ...})
	/Users/lee/code/go/bin/pkg/mod/google.golang.org/protobuf@v1.28.0/internal/filedesc/build.go:113 +0x1d8
google.golang.org/protobuf/internal/filetype.Builder.Build({{{0x6e9c9a0a, 0x22}, {0x702ca6e0, 0x849, 0x849}, 0x2, 0x10, 0x0, 0x1, {0x0, ...}, ...}, ...})
	/Users/lee/code/go/bin/pkg/mod/google.golang.org/protobuf@v1.28.0/internal/filetype/build.go:139 +0x19f
github.com/layer5io/meshery/meshes.file_meshops_proto_init()
	/Users/lee/code/meshery/meshes/meshops.pb.go:1355 +0x1e8
github.com/layer5io/meshery/meshes.init.0()
	/Users/lee/code/meshery/meshes/meshops.pb.go:1154 +0x17
plugin.open({0xc003720120, 0x60})
	/Users/lee/sdk/go1.17.8/src/plugin/plugin_dlopen.go:102 +0x58a
plugin.Open(...)
	/Users/lee/sdk/go1.17.8/src/plugin/plugin.go:32
github.com/layer5io/meshery/server/handlers.(*Handler).LoadExtensionFromPackage(0xc000c5f270, {0x0, 0x400e814}, 0x100000000000020, {0x6f6a7c0, 0xc000913860})
	/Users/lee/code/meshery/server/handlers/extensions.go:45 +0x205
github.com/layer5io/meshery/server/handlers.(*Handler).ProviderComponentsHandler(0xc000c5f270, {0x6eb42d0, 0xc000d9c8c0}, 0xc003858100, 0x400eb67, 0x90, {0x6f6a7c0, 0xc000913860})
	/Users/lee/code/meshery/server/handlers/provider_handler.go:122 +0x17a
github.com/layer5io/meshery/server/handlers.(*Handler).MesheryControllersMiddleware.func1({0x6eb42d0, 0xc000d9c8c0}, 0xc003858000, 0x6e42f40, 0x6434bc0, {0x6f6a7c0, 0xc000913860})
	/Users/lee/code/meshery/server/handlers/middlewares.go:108 +0x399
github.com/layer5io/meshery/server/handlers.(*Handler).KubernetesMiddleware.func1({0x6eb42d0, 0xc000d9c8c0}, 0xc00490a000, 0x6e42c60, 0x63f6ae0, {0x6f6a7c0, 0xc000913860})
	/Users/lee/code/meshery/server/handlers/middlewares.go:174 +0xbec
github.com/layer5io/meshery/server/handlers.(*Handler).SessionInjectorMiddleware.func1({0x6eb42d0, 0xc000d9c8c0}, 0xc00211b500)
	/Users/lee/code/meshery/server/handlers/middlewares.go:208 +0x516
net/http.HandlerFunc.ServeHTTP(0xc0021588d0, {0x6eb42d0, 0xc000d9c8c0}, 0x31fbc318)
	/Users/lee/sdk/go1.17.8/src/net/http/server.go:2047 +0x2f
github.com/layer5io/meshery/server/handlers.(*Handler).AuthMiddleware.func1({0x6eb42d0, 0xc000d9c8c0}, 0xc00211b500)
	/Users/lee/code/meshery/server/handlers/middlewares.go:72 +0x173
net/http.HandlerFunc.ServeHTTP(0x6ed0708, {0x6eb42d0, 0xc000d9c8c0}, 0x6e42f30)
	/Users/lee/sdk/go1.17.8/src/net/http/server.go:2047 +0x2f
github.com/layer5io/meshery/server/handlers.(*Handler).ProviderMiddleware.func1({0x6eb42d0, 0xc000d9c8c0}, 0xc00211b400)
	/Users/lee/code/meshery/server/handlers/middlewares.go:40 +0x376
net/http.HandlerFunc.ServeHTTP(0xc00211b300, {0x6eb42d0, 0xc000d9c8c0}, 0xc0015859f8)
	/Users/lee/sdk/go1.17.8/src/net/http/server.go:2047 +0x2f
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0005c0000, {0x6eb42d0, 0xc000d9c8c0}, 0xc0056d8100)
	/Users/lee/code/go/bin/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0x1cf
net/http.serverHandler.ServeHTTP({0xc000d90bd0}, {0x6eb42d0, 0xc000d9c8c0}, 0xc0056d8100)
	/Users/lee/sdk/go1.17.8/src/net/http/server.go:2879 +0x43b
net/http.(*conn).serve(0xc0002bfb80, {0x6ed0708, 0xc0007baf90})
	/Users/lee/sdk/go1.17.8/src/net/http/server.go:1930 +0xb08
created by net/http.(*Server).Serve
	/Users/lee/sdk/go1.17.8/src/net/http/server.go:3034 +0x4e8
INFO[0038] attempting to fetch applications from cloud
DEBU[0038] constructed applications url: https://meshery.layer5.io/applications
INFO[0038] attempting to fetch kubernetes contexts from cloud for Meshery instance: 64a75819-0e58-4cfc-9bd4-25a6b6831f0a
```

I'm trying to reproduce to better qualify it...

**Comment by l5io** [comment]
🚀 Preview for commit 4f97607a49002bb7766c212c7e31636743b07936 at: https://62ec17418b5f9f1a6c324e38--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 0c71b4a679728312c046c23692860b6cbcadf419 at: https://62ecb392657d690e4057af7a--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit b40444221d3eade7657fb2c1e0c041efd4c706df at: https://62ee51ce8b5f9f39713251d6--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 18724d66dc075984cdecab795a7db785cd2b8fff at: https://62ee67808fac9d4715d7715c--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit c5c67c6318945615e64fddf553e9b3faaa2e7811 at: https://62f0e26a488b4a58d5a06b24--meshery-docs-preview.netlify.app

**Comment by EleisonC** [comment]
Hey @leecalcote @Revolyssup Just checking in for another review I noticed the UI integration tests are failing due to a duplicate key in the react code in providersComponent.js ln 122 and 124

**Comment by Revolyssup** [comment]
@EleisonC Merge conflicts!

**Comment by l5io** [comment]
🚀 Preview for commit 8a66bea86f2acf5b62225aaf3d4ad82198599e6e at: https://62fcaa8d59772b066d4a6b62--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 037d8d40034316558a09f51b32ec5caeaa9e5e7d at: https://62fe45bc2a4583379fff613e--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 97aadd8c8764057fb8de4808f00b64d69e4bbecb at: https://62fe46b8090da33416da4e09--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 6a85f3dd066a3446196af68208d25c51a256e585 at: https://62ffb1b85f38790562891f0a--meshery-docs-preview.netlify.app

**Comment by leecalcote** [comment]
@EleisonC we are almost there. I think the only item left is to reinstate this submodule. I'm sure that it was accidentally deleted. I've done it myself more than once.


Screen Shot 2022-08-19 at 11 05 54 AM

**Comment by l5io** [comment]
🚀 Preview for commit f6eafd7a902cf71bc7421b2f167d9840aa4c98f6 at: https://63036caef0b2c9643e040e96--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 205a8c95163c8aacc941a02afeac312f245ddaef at: https://6303f47654b84907cdbbbc2b--meshery-docs-preview.netlify.app

**Comment by leecalcote** [comment]
@EleisonC, I pinged @sudo-NithishKarthik to no avail, best to tag @gr455 or @nishantwrp as possible others to pick up the slack.

**Comment by l5io** [comment]
🚀 Preview for commit 0c8cad1f9b597ed500d59847a036b27077da80c4 at: https://6306b222b30a4b04b65fb40f--meshery-docs-preview.netlify.app

**Comment by leecalcote** [comment]
Yay, @EleisonC! 🎈 😄

**Pull request merged**
