### PR TITLE
[Docs] - make command update in docs

### LINKED ISSUE #6850: [Docs] Make file command update
#### Current State
Currently in `README.md` of `meshery/docs` the command to serve the code locally is `make site`, shown here:
image

#### Desired State
The current command is `make docs` as per the `Makefile`:
https://github.com/gurpreet-legend/meshery/blob/0deff4995db098f221ff092aa3bb2dc8d0069c25/docs/Makefile#L3

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by gurpreet-legend**
Signed-off-by: Gurpreet Singh <lostlegend2701@gmail.com>

The reference of command `make site` has been updated to the current command `make docs`

This PR fixes #6850 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 0708d08f39be9cbde5a741e74113d40b1adca310 at: https://63bc9b88d8e5650850be78a3--meshery-docs-preview.netlify.app

**Review by leecalcote — CHANGES_REQUESTED** [review]
@gurpreet-legend thanks much for this. Will you go ahead and exclude any changes to Meshery v0.4 and v0.5, considering that `make docs` works for those versions, but not for v0.6 and forward?

**Comment by gurpreet-legend** [comment]
@leecalcote, reverted changes for older versions.

**Comment by l5io** [comment]
🚀 Preview for commit 51cf6e48e3d750a34dbac56aa22b4d79b3ce4274 at: https://63bd07c2660c605cfd544d51--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 0f1338697b04f8d2b65b901e7f1624027ca8839e at: https://63bdb6768f4611307f0cd95f--meshery-docs-preview.netlify.app

**Review by leecalcote — APPROVED** [review]

**Comment by leecalcote** [comment]
@gurpreet-legend, @ayushthe1, @Anand-Theertha, in-context of this PR and  PR https://github.com/meshery/meshery/pull/6810, please ensure that `make site` persists.

**Comment by gurpreet-legend** [comment]
> @gurpreet-legend, @ayushthe1, @Anand-Theertha, in-context of this PR and  PR https://github.com/meshery/meshery/pull/6810, please ensure that `make site` persists.

So @leecalcote, I'm not sure what you mean by "`make site` persists", do we need `make site` for v6 or above? Do I need to make any more changes here?

**Comment by leecalcote** [comment]
Make targets are being deleted in the other PR. Please ensure that `make site` isn’t one of them.

**Comment by ayushthe1** [comment]
> Make targets are being deleted in the other PR. Please ensure that `make site` isn’t one of them. 

I've checked ,`make site` and `make docs` both of them are not being deprecated.

**Comment by leecalcote** [comment]
Perfect. Thank you, @ayushthe1

**Comment by leecalcote** [comment]
There it is. Yay, @gurpreet-legend! 🎈

**Pull request merged**
