### PR TITLE
[UI] Navigator align fix

### PR DESCRIPTION
**Pull request by Chadha93**
Signed-off-by: Gaurav Chadha <gauravchadha1676@gmail.com>

**Description**
Navigator align fix

This PR fixes # Navigator extra margin issue 

**Notes for Reviewers**
Screenshot from 2021-12-23 13-49-22

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — APPROVED** [review]

**Comment by warunicorn19** [comment]
I dont think we can move forward with this approach

**Comment by warunicorn19** [comment]
Problem that's happening with this is since everyone is on different screensizes the padding applied here would be different for other screensizes, thats why I had removed the padding. @Chadha93 do you still see the white scrollbar?? Could you rebuild and check, since it's not visible on my end anymore. Removing the padding here is the right call.

**Comment by Chadha93** [comment]
@warunicorn19 Thanks for the feedback, It's margin with defined size, and is responsive, tested on the different screen sizes it's working perfectly fine. 

https://user-images.githubusercontent.com/65453826/147248019-63a6f969-bb3e-464d-890a-178db9b80760.mp4

**Comment by warunicorn19** [comment]
I think it depends on the entire width of your display. see how the chevron is unaligned and the child menu items are popping out. 
Screenshot 2021-12-23 at 9 47 42 AM
Screenshot 2021-12-23 at 9 48 01 AM

**Comment by Chadha93** [comment]
@warunicorn19 I see, could you test this out on chrome, then it could be a browser-specific issue

**Comment by warunicorn19** [comment]
Screenshot 2021-12-23 at 9 58 51 AM
popping out of menu items seems to be browser specific, but the chevron alignment.

**Comment by Chadha93** [comment]
> 

this looks fine on my system, try increasing the `marginLeft `from inspect on your system, and test which size fits better 
 // @sudo-NithishKarthik what can we do to avoid the browser-specific issue here?

**Comment by leecalcote** [comment]
This update is working well in my Safari and Chrome.

**Comment by warunicorn19** [comment]
Sorry. I missed the comment here @Chadha93. Could you try using css to hide the scrollbar instead, similar approach to what we do in the designer on meshmap.

**Comment by Chadha93** [comment]
> 

@warunicorn19  the CSS for the scrollbar was also removed earlier in his pr by me: https://github.com/meshery/meshery/pull/4658/files

**Comment by leecalcote** [comment]
This is better than what we currently have. Let's move forward with a merge here for v0.6.0-rc3 and revisit with a new issue.

**Comment by warunicorn19** [comment]
Okay let's do that.

**Pull request merged**
