### PR TITLE
Minify and flatten Kubeconfig on Meshery UI

### LINKED ISSUE #11546: Certificate issue when using Minikube cluster.
### Current Behavior

When using minikube, users are faced with the issue of 
`x509: certificate signed by unknown authority https-192-168-49-2-8443-version-timeout-32s-x509-certificate-signed-by-unknown-authority`.
To resolve the issue users have to manually flatten the kubeconfig file using the
` kubectl config view --minify --flatten > config_minikube.yaml` which is not the ideal flow.

### Expected Behavior

1. Resolve the reference while importing the kubeconfig. (The logic to flatten the config should be present in either the Mesheryctl or the Meshery server.)
2. Try skipping the certificates when connecting to the cluster by using the `skip-tls-verify` flag.
### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by alero-awani**
**Notes for Reviewers**
**Fixes only out-of-cluster installation**
This implements minifying and flattening of the kubeconfig on Meshery UI, allowing users to upload their kubeconfig without running the command `kubectl config view --minify --flatten > config_minikube.yaml`.

This PR fixes #11546

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
I’m surprised that this isn’t being done already or that there isn’t a meshkit function to be reused considering that `system config minikube` is doing this already.

**Comment by Alero-Awani** [comment]
@leecalcote `mesheryctl system config minikube` uses this same function.

**Review by MUzairS15 — COMMENTED** [review]
Once the lint issues are fixed and the new meshkit is released, we are good to go.

**Comment by lekaf974** [comment]
@Alero-Awani any update ?

**Comment by lekaf974** [comment]
@Alero-Awani looks the branch needs to be updated

**Comment by Alero-Awani** [comment]
> @Alero-Awani looks the branch needs to be updated

@lekaf974 please could you review now, thank you.

**Comment by Alero-Awani** [comment]
@lekaf974 could you approve this change so that it can merged. It is linked to this [PR](https://github.com/meshery/meshkit/pull/588) for Minifying and flattening.

**Review by lekaf974 — APPROVED** [review]
LGTM

**Comment by lekaf974** [comment]
@Jougan-0, @Yashsharma1911  can you have a second review ?

**Pull request merged**
