### PR TITLE
Revert PR #6138

### PR DESCRIPTION
**Pull request by alphaX86**
Signed-off-by: Aadhitya A <aadhitya864@gmail.com>

**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by CyrineG — DISMISSED** [review]

**Comment by leecalcote** [comment]
@acald-creator you might like to review...

**Comment by acald-creator** [comment]
Based on this PR, there are only slight differences between mine and this PR. For some reason, the Chart definitions `meshery-perf.disabled` still pulled the images via Helm deployment.

**Comment by acald-creator** [comment]
Just to be clear, Helm docs stated that you can call the Chart definition by doing this `meshery-perf.enabled`, but in `values.yaml`, you declare if it is enabled by true or false. By leaving the things the way they are by `meshery-perf.enabled`, you can declare this to be false in `values.yaml` thus the deployment will go through without `meshery-perf` and `meshery-cpx`

**Comment by alphaX86** [comment]
Thanks for clarification @acald-creator it seems you have fixed this as well. 🤝

**Comment by alphaX86** [comment]
Closing this as this is resolved via pr #6182

**Pull request closed without merging**
