### PR TITLE
[CI] - Fixes code-ql analysis workflow

### LINKED ISSUE #2740: [CI] The GitHub Action of CodeQL not work
#### Description

https://github.com/layer5io/meshery/actions/runs/772847992/workflow
#### Expected Behavior

The CI can work well
#### Environment:
- Meshery Version: 
- Kubernetes Version: 
- Host OS:
- Browser:

### PR DESCRIPTION
**Pull request by adithyaakrishna**
Signed-off-by: Adithya Krishna <aadithya794@gmail.com>

**Description**

This PR fixes #2740 

**Notes for Reviewers**
I came across some info when I was working on release-notes, this led to the discussion at GitHub Community, https://github.community/t/running-adding-codeql-analysis-for-all-the-branches-of-a-repository/177070

**[Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by adithyaakrishna** [comment]
@Aisuko Could you please review this?

**Review by Aisuko — APPROVED** [review]
LGTM

**Comment by Aisuko** [comment]
Why there exists double CodeQL? @leecalcote 

Screen Shot 2021-04-28 at 6 02 16 PM

**Comment by Aisuko** [comment]
@adithyaakrishna Thanks

**Comment by adithyaakrishna** [comment]
> Why there exists double CodeQL? @leecalcote
> 
> Screen Shot 2021-04-28 at 6 02 16 PM

@Aisuko I guess, they both are different. The first one runs the workflow of CodeQL and the second one outputs the results of the first workflow

**Review by leecalcote — DISMISSED** [review]
LGTM

**Comment by adithyaakrishna** [comment]
**So if we want to run any action on all the branches of a repo, we can do so by** 

image

**Review by leecalcote — APPROVED** [review]
Thanks for looking into this, @adithyaakrishna. I believe @mgfeller is hopeful that this check might run on all branches just as you have updated it to do so.

**Comment by adithyaakrishna** [comment]
@leecalcote Ig we have to wait for the check for it to run next time to get the exact results 👀
But if it breaks, I'll make sure to fix the error 👨‍🔧

**Pull request merged**
