### PR TITLE
added cncf-white.png and cncf-black.png in [docs/assets/img/readme/] an…

### LINKED ISSUE #5538: [Docs] Support light vs dark mode display of CNCF logo in Meshery README
#### Current State

This repo's readme has a CNCF logo with dark text, which has low contrast when viewed in dark mode browsers.

Screen Shot 2022-05-25 at 10 28 50 AM

#### Desired State
Use [new feature of GitHub](https://github.blog/changelog/2022-05-19-specify-theme-context-for-images-in-markdown-beta/) to display theme appropriate CNCF logo. Find other CNCF logos here: github.com/cncf/artwork

---

#### [Contributor Guides](https://docs.meshery.io/project/contributing) and Resources
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by krisharyan**
…d changed README.md

Signed-off-by: KrishAryan <krisharyan.36@gmail.com>

**Description**
Added cncf-white.png and cncf-black.png in [docs/assets/img/readme/] and changed changed README.md
This PR fixes #5538 

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit d6c9e6567fe0140e2ce6ed31cd72f0529bd52d1d at: https://628f38d3b2a618396d12b2e5--meshery-docs-preview.netlify.app

**Comment by KrishAryan** [comment]
screenshot (40)
screenshot (41)

**Comment by KrishAryan** [comment]
@leecalcote I used a different method using #gh-dark-only and #gh-light-only for ex-
 
is it ok?

**Review by karnatisrinivas — COMMENTED** [review]
LGTM, Nice work krish

**Comment by KrishAryan** [comment]
@karnatisrinivas thanks

**Comment by leecalcote** [comment]
Good work, @KrishAryan. You got it. 👍

**Review by leecalcote — COMMENTED** [review]
Does this styling not support SVGs?

**Comment by KrishAryan** [comment]
sorry, I didn't know how to download SVGs so I went with PNGs .@leecalcote please review it again I have changed them into SVGs

**Comment by l5io** [comment]
🚀 Preview for commit 17ed84aa2e6806db77a544b9fea273a1203ab465 at: https://629192cb27be7e2896f7a120--meshery-docs-preview.netlify.app

**Review by leecalcote — APPROVED** [review]
Looks good. 👍 

Thank you, @KrishAryan and @karnatisrinivas

**Pull request merged**
