### PR TITLE
[CI] Upgrade setup-go version

### PR DESCRIPTION
**Pull request by alphaX86**
Signed-off-by: Aadhitya A <aadhitya864@gmail.com>

**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by MUzairS15 — APPROVED** [review]
Don't forget to sign-off your commit.

**Comment by alphaX86** [comment]
🤦‍♂️ Almost forgot

**Review by MarioArriaga92 — DISMISSED** [review]
LGTM 🔥! DCO still missing though.

**Review by Abhijay007 — APPROVED** [review]
LGTM

**Review by leecalcote — APPROVED** [review]

**Pull request merged**
