### PR TITLE
Create and integrate adapters collection into docs

### LINKED ISSUE #470: Docs: Create Jekyll Collection for Meshery Adapters
**Current State:**
Meshery Adapters are listed on a few different pages. Their multiple listings become fragile as new adapters are created and existing adapters move between alpha, beta, stable, and continue to version (e.g. v2.0.0) from there.

**Desired State:**
Ideally, this information is gathered into a _data [collection](https://jekyllrb.com/docs/collections/) as a single source of truth to be referenced across these various pages.

- [ ] Create a new collection for adapters.
- [ ] Supplant static adapter lists with a collection iterator.

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

### PR DESCRIPTION
**Pull request by schillingjerrid**
Main changes:
* Added an adapters collection to the docs
* Removed the previous individual adapter pages
* Updated the Adapters page to link to the new collection pages
* Updated the Architecture page with the new collection
* Added project_status to the front matter of each adapter in the collection
* Updated the main index page with the new collection
* Added table filters (if condition) to the Adapter, Architecture, and index pages to only show adapters that have the version, port, and project_status front matter, respectively.

Secondary changes:
* Added jekyll-cache to the gitignore for the new jekyll versions
* Ruby version was updated in the gemfile

Fixes #470

### CODE REVIEW

**Comment by schillingjerrid** [comment]
It looks like one of the checks is failing on the Run GOPROXY line of the Meshery / Check & Review code (pull_request) step. See screenshot.
Screen Shot 2019-12-07 at 9 58 37 AM

**Comment by schillingjerrid** [comment]
I tried to pull upstream master and merge it into my branch but it doesn't look like that fixed it. Not sure what the issue is.

**Comment by leecalcote** [comment]
@schillingjerrid nice work! The issue with accidentally pulling in others' changes is very common. Will you have a look at these steps, try them out and see if they cleanup your PR? --> https://github.com/layer5io/meshery/blob/master/git-workflow.md#submitting-your-changes-a-pull-request

**Comment by subhamkrai** [comment]
> Thanks, @schillingjerrid! This is a good step forward.
> 
> @schillingjerrid, in chatting with @subhamkrai recently, I noted that we'll want to take the next step and convert from Collections to Data Files. @subhamkrai, please collaborate with @schillingjerrid if you begin work on a data file.

@leecalcote I'll surely contact @schillingjerrid

**Pull request merged**
