### PR TITLE
REST API and GraphQL docs

### LINKED ISSUE #3066: [Docs] Improve UI for REST/GraphQL API Docs
[REST API Docs](https://docs.meshery.io/reference/rest-apis)
[GraphQL Docs](https://docs.meshery.io/reference/graphql-apis)

#### Desired State

Improve the UI/CSS for the Documentation pages.

---

#### Contributor Resources

- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
- [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by kaushambisharma**
**Description**

This PR fixes #3066

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by kaushambisharma** [comment]
@dhruv0000 please review

**Comment by piyushsingariya** [comment]
@kaushambisharma DCO is failing!

**Review by kaushambisharma — COMMENTED** [review]
👍

**Review by dhruv0000 — APPROVED** [review]

**Comment by kumarabd** [comment]
Ready to merge here? @dhruv0000 @kaushambisharma

**Comment by dhruv0000** [comment]
yes. @dhruv0000

**Pull request merged**
