### PR TITLE
Fix compatibility matrix order issues

### PR DESCRIPTION
**Pull request by rudrakshkarpe**
Signed-off-by: Rudraksh Karpe <rudraksh.karpe@gmail.com>

**Notes for Reviewers**

We can try it with the ```sort_by``` filter instead of ```group_by```. The ```sort_by``` filter will sort the items in a collection based on a specified key.

This PR fixes #
Issue #6873 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit a2cdf8ce76f74669e8816a3fc37b3f70c4d6ed9e at: https://63cc769c434a9507e6ca25f2--meshery-docs-preview.netlify.app

**Comment by asubedy** [comment]
@rudrakshkarpe this solution does not work, we use group by parameter to separated the compatibility collection on the basis of different k8s version and then show the test results according to each k8s version, if we just sort the compatibility collection this criteria is not fulfilled thus the matrix will not appear as  required.

You can check [here](https://63cc769c434a9507e6ca25f2--meshery-docs-preview.netlify.app/project/compatibility-matrix#integration-tests) that when you changed the parameters the compatibility matrix completely broken.

**Comment by Chadha93** [comment]
@rudrakshkarpe  Let's discuss this on the Meshery Dev call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#) if you would. :)

**Comment by rudrakshkarpe** [comment]
> @rudrakshkarpe Let's discuss this on the Meshery Dev call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#) if you would. :)

Sure! I would love to! 
image
I have sent an editing request, please give me editing rights. I'll add topic to agenda

**Comment by Chadha93** [comment]
Hi @rudrakshkarpe, you can add it as a suggestion.

**Comment by rudrakshkarpe** [comment]
> Hi @rudrakshkarpe, you can add it as a suggestion.

Sorry but there's only view access to my account

**Comment by Chadha93** [comment]
@rudrakshkarpe Submit the newcomer's form to get access to community resources: https://layer5.io/newcomer

**Comment by rudrakshkarpe** [comment]
> @rudrakshkarpe Submit the newcomer's form to get access to community resources: https://layer5.io/newcomer

Thanks!

**Comment by rudrakshkarpe** [comment]
I have raised another PR #6937 continuing my work on this issue. I am closing this one.

**Pull request closed without merging**
