### PR TITLE
removed extra spaces by replacing h5 with p and strong tags in [docs>_includes>installation_prerequisites]

### LINKED ISSUE #5496: [Docs] Remove Extra space in Prerequisites
#### Current State
Screen Shot 2022-05-09 at 2 28 18 PM

#### Desired State

---

#### [Contributor Guides](https://docs.meshery.io/project/contributing) and Resources
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by krisharyan**
Signed-off-by: KrishAryan <krisharyan.36@gmail.com>

**Description**

This PR fixes #5496 

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 1ac8d0185a474b8a0a3a49e9829344b0c06cd199 at: https://628a8584065a400bf2600f4e--meshery-docs-preview.netlify.app

**Comment by Akshit42-hue** [comment]
@KrishAryan please try to give an issue number and description

**Comment by KrishAryan** [comment]
[Docs] Remove Extra space in Prerequisites 
issue number:#5496 
description:removed extra spaces by replacing h5 with p and strong tags in [docs>_includes>installation_prerequisites]

**Review by Akshit42-hue — DISMISSED** [review]
LGTM!, Great work @KrishAryan

**Comment by KrishAryan** [comment]
is font-size of 20 px ok?

**Comment by asubedy** [comment]
> is font-size of 20 px ok? @asubedy

Yep that should do

**Comment by l5io** [comment]
🚀 Preview for commit 1464ae806f465b7f5217fd25defba9b8783e8630 at: https://628bd719b22f9b0470235e43--meshery-docs-preview.netlify.app

**Comment by KrishAryan** [comment]
Please review @asubedy

**Review by karnatisrinivas — APPROVED** [review]
LGTM! Nice work

**Comment by KrishAryan** [comment]
@karnatisrinivas thanks

**Review by warunicorn19 — APPROVED** [review]
Thank you @KrishAryan

**Pull request merged**
