### PR TITLE
[UI] Fixed pagination issue in database overview

### PR DESCRIPTION
**Pull request by Meyazhagan**
**Notes for Reviewers**

This PR fixes #
server-side pagination is changed to indexing 1,
for pages 1 & 2, the server returns the same result

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Review by MUzairS15 — COMMENTED** [review]
Here, https://github.com/meshery/meshery/pull/8064/files#diff-780ab59e9222a4ae3e25c67ab100a8e4707647f61d3fa74d1c6b6b99bb63f42dR44
the default value is changed to `0`
and then https://github.com/meshery/meshery/pull/8064/files#diff-780ab59e9222a4ae3e25c67ab100a8e4707647f61d3fa74d1c6b6b99bb63f42dR65
page is incremented by `1`.

@Meyazhagan What issue are you fixing??

**Comment by Meyazhagan** [comment]
@MUzairS15 I recorded the issue
https://github.com/meshery/meshery/assets/67836725/be952b07-d254-45bf-8562-e800238f10bd

DataTable doesn't have a reference to page state, its page starts from 0, but server indexing is based 1. so for pages 0 and 1 it returns the first-page result

**Comment by leecalcote** [comment]
@UsmanDev09 will you give this PR a review?

**Comment by UsmanDev09** [comment]
Thanks @Meyazhagan. This PR LGTM.

**Comment by leecalcote** [comment]
Yay! 🎈

**Pull request merged**
