### PR TITLE
deploy mesh unit test

### LINKED ISSUE #8087: [Unit Tests] Writing more Unit tests for mesheryctls  Packages
#### Current Behavior
Not much unit test for the [packages](https://github.com/meshery/meshery/blob/master/mesheryctl/internal/cli/root) in mesheryctl 
#### Desired Behavior
Adding more Unit tests to test the units and individual components of the codes in [mesheryctl's  packages](https://github.com/meshery/meshery/blob/master/mesheryctl/internal/cli/root) to improve ci coverage

#### Acceptance Tests

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
- Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)
- 🧪 [Meshery Test Plan Spreadsheet](https://docs.google.com/spreadsheets/d/13Ir4gfaKoAX9r8qYjAFFl_U9ntke4X5ndREY1T7bnVs/edit#gid=0)

### PR DESCRIPTION
**Pull request by Philip-21**
**Notes for Reviewers**

This PR fixes #8087 

Unit test for [deploy.go](https://github.com/meshery/meshery/blob/master/mesheryctl/internal/cli/root/mesh/deploy.go) in mesh package 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by Philip-21** [comment]
@theBeginner86 , @alphaX86 , please help look into the `deploy.istio.output.golden`  i dont think i am passing the right data for the fields. 
when i ran the tests i got this error message `time="2023-08-08T19:19:48+01:00" level=fatal msg="Failed to process JSON data. Please sign into Meshery"'`

**Comment by Philip-21** [comment]
Also as you look at the tests please mention other areas where I should make changes

**Comment by leecalcote** [comment]
Thanks, @Philip-21!

**Comment by Philip-21** [comment]
🙂

**Comment by Philip-21** [comment]
🙂

**Comment by Philip-21** [comment]
> Thanks, @Philip-21!

🙂

**Comment by Philip-21** [comment]
🙂

**Comment by vishalvivekm** [comment]
@Philip-21 Let's discuss this also on Meshery Dev call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#) if you would. :)

**Comment by l5io** [comment]
🚀 Preview for commit 08f39935355347be35b1ac1e239400275f51fd22 at: https://64e1bdce6eefb63e5b0cf968--meshery-docs-preview.netlify.app

**Pull request closed without merging**
