### PR TITLE
[Chore] Get rego policies passing regal lint and run lint during build.

### PR DESCRIPTION
**Pull request by ctcarrier**
**Notes for Reviewers**

This PR fixes #
- Minimal changes to rego policies to get them passing lint. 
- Moves regal config to standard location: ".regal/config.yaml"
- Added some lint rules to config as warning to get lint passing for now
- Adds Github Action to run regal lint when changes are made to rego files in PR

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — COMMENTED** [review]
It's nice to see the lint-rego rules in-action in this PR - https://github.com/meshery/meshery/actions/runs/10565049566/job/29268755314?pr=11799

**Review by MUzairS15 — COMMENTED** [review]
@ctcarrier for these lint failures 
> External reference in function.

By using `with` keyword, we are building the data/input for the rules and not actually/processing the external reference in the function. I wonder how to fix these.

**Comment by ctcarrier** [comment]
> @ctcarrier for these lint failures
> 
> > External reference in function.
> 
> By using `with` keyword, we are building the data/input for the rules and not actually/processing the external reference in the function. I wonder how to fix these.

@MUzairS15 Based on what I've read in the Rego documentation they would recommend passing all necessary data into the functions as parameters and avoiding the use of `with` outside of tests:

https://docs.styra.com/regal/rules/performance/with-outside-test-context
https://docs.styra.com/opa/rego-style-guide#prefer-using-arguments-over-input-data-or-rule-references

I started to refactor the code to remove the `with` and just pass the necessary fields in as parameters but it seemed to introduce some kind of regression so I backed those changes out and moved those errors to warning for now. I thought it might be worth getting some tests working before making those changes to make sure they don't accidentally break anything.

**Comment by MUzairS15** [comment]
This is good progress @ctcarrier , let’s discuss on upcoming Meshery Build and Release call.

**Comment by MUzairS15** [comment]
Makes sense, totally agree with you.

**Review by MUzairS15 — APPROVED** [review]
LGTM, no regression found.

**Pull request merged**
