### PR TITLE
Create tests for `mesheryctl exp relationship` command

### LINKED ISSUE #12136: Create Unit and Integration Tests for `mesheryctl exp relationships` Command
### Description
We need to develop comprehensive unit and integration tests for the `mesheryctl exp relationships` command. This command is responsible for listing, viewing, and searching MeshModel relationships, as well as generating relationship documents.

The goal is to ensure the correctness of the core functionalities, error handling, and interaction with the Meshery server.

### Current Behavior
Currently, there are no automated tests covering the `mesheryctl exp relationships` command, which includes:
[] Listing relationships (`mesheryctl exp relationships list`)
- Viewing details of a specific relationship (`mesheryctl exp relationships view`)
- Searching for relationships (`mesheryctl exp relationships search`)
- Handling interaction with the Meshery server and command prerequisites (e.g., server running, version validation).

### Desired Behavior
Tests should cover the following aspects:

1. **Unit Tests**:
   - **Model Prompt Selection**: Verify that the `selectRelationshipPrompt` function correctly displays and returns a relationship when multiple options are available.
   - **Argument Validation**: Ensure that missing or invalid arguments (e.g., invalid model names) trigger the appropriate error messages.
   - **Subcommand Handling**: Verify that invalid subcommands trigger the appropriate error messages.
   
2 **Integration Tests**:
   - **Server Interaction**: Mock the Meshery server and verify that the command correctly interacts with it, including:
     - Validating that the server is running.
     - Handling failed connections or invalid credentials.
     - Properly fetching and displaying relationships data.
   - **Data Retrieval and Display**: Ensure that relationships data is correctly retrieved, parsed, and displayed in both JSON and YAML formats.
   
4. **Error Handling**:
   - Handle cases where the Meshery server is unavailable.
   - Handle invalid or missing credentials.
   - Handle improper arguments or subcommands.

### Checklist:
- [ ] Listing relationships (`mesheryctl exp relationships list`)
- [ ] Viewing details of a specific relationship (`mesheryctl exp relationships view`)
- [ ] Searching for relationships (`mesheryctl exp relationships search`)
- [ ] Handling interaction with the Meshery server and command prerequisites (e.g., server running, version validation).

### Implementation
- Use mock APIs to simulate interaction with the Meshery server and return test data for relationships.
- Use existing testing frameworks and patterns for `mesheryctl`.
- Follow Meshery's contribution guidelines for writing tests.

### Resources
- The file to be tested: `mesheryctl/internal/cli/root/exp/relationships.go`
- [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)

### Contributor Resources

- ⌨️ [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by yaten2302**
**Notes for Reviewers**

- This PR fixes #12136 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

This PR creates  tests for - `mesheryctl exp relationships` command, responsible for viewing, listing and searching MeshModel relationships.

### CODE REVIEW

**Comment by yaten2302** [comment]
@lekaf974 @alphaX86 , I've re-created [this](https://github.com/meshery/meshery/pull/12624) PR. There was some issue with that one (DCO checks).
All the changes are same, also I've a doubt that, if I'm creating tests for all the other sub commands as well, like - `view`, `generate`, `list` etc... Then should I create different files for those? Like - `list_test.go`, `view_test.go` in the same dir i.e. `experimental`? Like this: <br>

image

**Comment by lekaf974** [comment]
@yaten2302 set this PR ready instead of draft. 

best is to create a test file per command but do one PR for each command to make the review easier please

**Comment by lekaf974** [comment]
also for sign off you could have only amend previous comment commit instead of recreate a new one

**Comment by yaten2302** [comment]
@lekaf974 , I've marked this PR as ready for review 👍 
Actually, earlier I thought that I've to make all the changes in 1 PR only, so that's why it was a draft previously.

**Review by alphaX86 — APPROVED** [review]
LGTM. Approved!

**Comment by alphaX86** [comment]
@lekaf974 could you review once on your side before finalizing?

**Comment by yaten2302** [comment]
@alphaX86 @lekaf974 , I've created tests for `mesheryctl exp relationship view model-name` command too! Could you please have a look at.

**Review by alphaX86 — DISMISSED** [review]

**Comment by leecalcote** [comment]
keep pushing, @yaten2302 👍

**Comment by yaten2302** [comment]
Sure, thanks @leecalcote 👍 
Ig only 2 tests are left, I'll push them by today and then we can discuss them in today's call 👍

**Comment by vishalvivekm** [comment]
@yaten2302 
Let's discuss this during the Meshery Development call today at 9:00 AM CT | 8:30 PM IST. Adding it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit?pli=1#) || [meeting link](https://meet.layer5.io/meshery).

**Comment by yaten2302** [comment]
Also, I wanted to ask that, the currently meshery doesn't contains docs for the `search` command. May I create an issue for the same? Like for [docs], for adding a small documentation for the search command.
Here's the link - https://docs.meshery.io/reference/mesheryctl

**Comment by alphaX86** [comment]
> Also, I wanted to ask that, the currently meshery doesn't contains docs for the `search` command. May I create an issue for the same? Like for [docs], for adding a small documentation for the search command. Here's the link - [docs.meshery.io/reference/mesheryctl](https://docs.meshery.io/reference/mesheryctl) image

@yaten2302 could you elaborate this more? Also, for "search" try checking if there's a subcommand page made by automated workflow (eg: click generate and replace it with search in URL) . If it is, then we should update the index to appear the changes there.

**Comment by yaten2302** [comment]
Ahh yes, I see that, it's there right over [here](https://docs.meshery.io/reference/mesheryctl/exp/relationship/search) 👍 
Got it, thanks @alphaX86

**Comment by alphaX86** [comment]
> Ahh yes, I see that, it's there right over [here](https://docs.meshery.io/reference/mesheryctl/exp/relationship/search) 👍 
> Got it, thanks @alphaX86 

Nice! Still.. we might need to update the index page to reflect the entry...

**Comment by yaten2302** [comment]
Yes, ig the link exists, but isn't being reflected on the index page, right 👀?
BTW @alphaX86 , does this PR looks good?

**Comment by lekaf974** [comment]
@yaten2302 thanks, busy in the last weeks, taking a look

**Review by alphaX86 — COMMENTED** [review]
@yaten2302 share the test results screenshot. It's just to check if all test cases are passing. Right now, I couldn't check in my system as something is blocking in `git pull` even after pruning

**Comment by alphaX86** [comment]
> Yes, ig the link exists, but isn't being reflected on the index page, right 👀? BTW @alphaX86 , does this PR looks good?

That actually is a manual task for now...

**Comment by yaten2302** [comment]
@alphaX86 , here are the screenshots of tests:<br>
image
<br>
image
<br>
image
<br>
image

**Comment by yaten2302** [comment]
Not really sure, if this is the issue, but if it is, then this might help - https://layer5io.slack.com/archives/C0130BQ4L3T/p1733291819564959?thread_ts=1733288794.775589&cid=C0130BQ4L3T

**Comment by alphaX86** [comment]
> Not really sure, if this is the issue, but if it is, then this might help - [layer5io.slack.com/archives/C0130BQ4L3T/p1733291819564959?thread_ts=1733288794.775589&cid=C0130BQ4L3T](https://layer5io.slack.com/archives/C0130BQ4L3T/p1733291819564959?thread_ts=1733288794.775589&cid=C0130BQ4L3T)

Yes, that's the issue I also suffered in Windows. Could you open an issue reg this?

**Review by alphaX86 — APPROVED** [review]
LGTM. Approved. 

@yaten2302 make sure your PR is in sync

**Comment by yaten2302** [comment]
@vishalvivekm , may we add this for today's call 👀

**Comment by alphaX86** [comment]
Thanks @yaten2302 for your work! This looks good, hence merging this.

**Pull request merged**
