### PR TITLE
[Docs] Jekyll Build Cache

### PR DESCRIPTION
**Pull request by leecalcote**
Signed-off-by: Lee Calcote <lee.calcote@layer5.io>

Use of Jekyll Build Cache plugin

### CODE REVIEW

**Comment by leecalcote** [comment]
See if your build times drop.

**Comment by vishalvivekm** [comment]
> See if your build times drop.

we can also do this
```
          {% if page.category != "integrations" %}
          {% include_cached suggested-reading.html language="en" %} 
          {% endif %}
 ```
 
 In my opinion showing a list of 200 hundred other integrations as suggested reading on each individual integration page is costing us a lot of build time . @iArchitSharma

**Comment by leecalcote** [comment]
Sounds good. And having that list on each of the integration pages isn't helpful.

More than an opinion, have you tested this change to confirm the integration pages are the major offender? Irrespective of the performance improvement, I agree regarding the nil value of having all other integrations as suggested reading.

**Comment by leecalcote** [comment]
P.S. Here's a _very_ helpful tool in to use while answering this question:

```
bundle exec jekyll build --profile
```

**Pull request merged**
