### PR TITLE
[bug] Resolve connections bug and UI

### PR DESCRIPTION
**Pull request by sudhanshutech**
**Notes for Reviewers**

This PR fixes #

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by sudhanshutech** [comment]
@senali-d 
image

**Review by senali-d — COMMENTED** [review]
@sudhanshutech Bug of the fixed here.. 🚀

**Comment by senali-d** [comment]
> @senali-d image

@sudhanshutech Regarding the status select component. Styles are not match with the which we already have.

**Comment by sudhanshutech** [comment]
ok i am updating it wait

**Comment by sudhanshutech** [comment]
@senali-d i have re added the styles because the standard chip and current one is whole messy styling its taking time, lets get this bug and we can use standard in next pr

**Pull request merged**
