### PR TITLE
New Registrant 

### LINKED ISSUE #8228: [Server] MeshModel API: New registrants Endpoint
#### Current Behavior

Currently, we have 3 tabs inside mesh models summary [page](https://playground.meshery.io/settings#meshmodel-summary) namely Components, Models and Relationships. 

meshmodel

#### Desired Behavior

We need a 4th tab named **Registrants** to display information of the registrant. 

We need to display the: 
1. Hostname
2. Port
3. ContextID
4. Endpoint
5. Summary of how many components, models and relationships are registered by the registrant

#### Implementation

Please create a new endpoint `api/meshmodels/registrant` that would return all this information. 

Refer to this [issue](https://github.com/meshery/meshery/issues/8224) for more contextual information.

#### Acceptance Tests

1. Refer to [API Endpoints Documentation](https://docs.meshery.io/reference/rest-apis) and add documentation for the new endpoint. 

2. Please add support for pagination, search, and filter for it to be accepted.  

#### Mockups

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by Jougan-0**
**Notes for Reviewers**

This PR fixes #8228 
The Endpoint is left i can't figure out where to access rest all is done apart from search can someone please review and tell whether the values are correct or not . 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Jougan-0** [comment]
@theBeginner86 can u have a look and confirm

**Review by MUzairS15 — CHANGES_REQUESTED** [review]
@Jougan-0 The PR description says the endpoint is left, but I can see the endpoint defined here. https://github.com/meshery/meshery/pull/8964/files#diff-c9f0fd2985523c81296d5a3b0b745ef02fa9d539a883a799977e0f4cb73f45e1R198

Also, since the use case is to list all registrants, why can we not just refer to the host table? (unless I am missing something) As extracting host information from the models seems inefficient.

**Comment by Jougan-0** [comment]
@MUzairS15 the endpoint is declared I made the variable but no value is passed in it. The host table if u mention from where I can access them i'll just replace those values in

**Comment by Jougan-0** [comment]
> @Jougan-0 The PR description says the endpoint is left, but I can see the endpoint defined here. https://github.com/meshery/meshery/pull/8964/files#diff-c9f0fd2985523c81296d5a3b0b745ef02fa9d539a883a799977e0f4cb73f45e1R198
> 
> Since the use case is to list all registrants, why not just refer to the host table? (unless I am missing something) Extracting host information from the models seems inefficient.

the endpoint here is the the api/meshmodels/registrants that is used by the front-end to display the info about the registrants 

but as mentioned in the image the istio shows an endpoint in my pr the api/meshmodels/registrants has the values as such the endpoint variable is declared but i don't know what values to pass in it 
image

**Comment by Jougan-0** [comment]
Continuing my point the values are shown as this at the ```api/meshmodels/registrants``` 
Screenshot from 2023-10-02 00-05-17
Are these the values that are correct regarding the registrants the contextID and the hostname??

**Comment by Jougan-0** [comment]
image
@MUzairS15 have a look the endpoint is sorted i guess

**Comment by MUzairS15** [comment]
@Jougan-0 The screenshot you posted ‘Hosts‘ table, I am saying to directly query this instead of what you have.

Are you saying you are not able to query hosts table?

Also, if fields are empty don’t bother to assign values on your own.
For eg: the ContextID this particular column is misleading and it only makes sense for kubernetes. The column should be more generic (but leave this concern for another time). The idea is that column captures the specific details for the regustrant. In case of kubernetes it stored context id against which the model and comps were registered. 

Suppose the models and comps were generated from some OCI/helm repo of a particular user in this case the value for the column would be different.

Above explanation has not much to do with your implementation currently.

**Comment by MUzairS15** [comment]
You are only trying to list all distinct registrants right?
So directly query the hosts table.

**Comment by Jougan-0** [comment]
@MUzairS15 how can i query host table was trying to find it but was not able to do so

**Comment by MUzairS15** [comment]
> @MUzairS15 how can i query host table was trying to find it but was not able to do so

Look at other funs the way they query different tables in a similar fashion you need to do. Additionally refer the gorm (golang ORM) docs

**Comment by Jougan-0** [comment]
> > @MUzairS15 how can i query host table was trying to find it but was not able to do so
> 
> Look at other funs the way they query different tables in a similar fashion you need to do. Additionally refer the gorm (golang ORM) docs

thank you will do it positively so

**Pull request closed without merging**
