### PR TITLE
Add `system dashboard` to the mesheryctl command reference index

### LINKED ISSUE #6640: [Docs] `mesheryctl system dashboard` is not in the Meshery Command Line Reference
#### Desired State

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by alphaX86**
Signed-off-by: Aadhitya A <aadhitya864@gmail.com>

**Notes for Reviewers**

This PR fixes #6640 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 8438e22603900e6f0eb0035d00a50d8b68c014f7 at: https://638f0ed878f55e004ec4c461--meshery-docs-preview.netlify.app

**Review by leecalcote — CHANGES_REQUESTED** [review]
Oh, no. I thought the docs updates were dynamically built. There no reason the we should have to put in the changes that you are manually making in the docs. It’s no wonder that the dashboard command is missing. This doc system is still manual. @asubedy will you work with @alphaX86 and show him how to get this changed?

**Comment by l5io** [comment]
🚀 Preview for commit 8e0f1566f03f55d644008dae6386ece034e8c988 at: https://638f1350194cb4028ee4cd2a--meshery-docs-preview.netlify.app

**Comment by alphaX86** [comment]
The index page alone is still manual, not the command doc pages, but still we do need it automated

**Comment by leecalcote** [comment]
The Monday Websites call will work, too, if this isn't already presented on Wednesday. Use iteration, includes, queries to eliminate the duplicative code.

**Comment by l5io** [comment]
🚀 Preview for commit f60f78e076f55eb3b33077cd07c5f2347dcb8912 at: https://638ff7fb538f411a7158df66--meshery-docs-preview.netlify.app

**Comment by leecalcote** [comment]
Write access reinstated.

**Comment by asubedy** [comment]
Ok, the duplication can be removed using includes file, I'm pushing the changes to this PR only

**Comment by asubedy** [comment]
But about the cmds.yml, I think we require another go script to  dynamically update the commands, I don't see another way to automate the cmds.yml

**Comment by l5io** [comment]
🚀 Preview for commit 5b89490c0a0e1bc1e501d2feffd63a9ed028a77e at: https://6397f848363255393939d53d--meshery-docs-preview.netlify.app

**Pull request merged**
