### PR TITLE
[WIP][Meshery] Fix Kube API authentication issue with GKE

### LINKED ISSUE #2440: [Platform] GKE: MeshKit-based adapters not authenticating to Kube API
#### Description
Meshery Adapter for Istio and other MeshKit-based adapters are not available on @rwong2888's system. He has the following environment:

- a gke cluster was instantiated with https://registry.terraform.io/modules/terraform-google-modules/kubernetes-engine/google/latest/submodules/private-cluster

#### Expected Behavior
Meshery Adapter for Istio should be available.

#### Screenshots/Logs
[mesheryctl.log](https://github.com/layer5io/meshery/files/6025580/mesheryctl.log)
image (3)

#### Environment:
- Host OS: macOS
- Meshery Version: v0.5.0-rc-3
- Kubernetes Version: GKE private cluster
- Browser: 

#### To Reproduce
@rwong2888 has run the following sequence of commands:

```
10687  mesheryctl system stop
10688  docker rm -f $(docker ps -aq)
10689  docker ps
10690  docker ps -aq
10691  rm -rf ~/.meshery
10692  rm ~/.kube/config
10693  gcloud container clusters get-credentials playground --region us-east4
10694  mesheryctl system start
10695  mesheryctl system config gke --token ~/Downloads/auth.json
10696  mv ~/.meshery/kubeconfig.yaml ~/.kube/config
```

#### Reference
Conversation - https://istio.slack.com/archives/C01NS1FMHSR/p1614025599030300

### PR DESCRIPTION
**Pull request by hexxdump**
**Description**
mesheryctl system config gke  -t <> fails with "no Auth Provider found for name gcp" error.
Because of this, bringup of Meshery with GKE config fails.
Fix: import the GCP auth packages in k8s handler code

This PR fixes #2440

**Notes for Reviewers**
This issue was seen in GKE setup of @utkarsh-pro  and fix has been suggested by him.

Signed-off-by: Hussaina Begum Nandyala <hexxdump@gmail.com>
**[Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
A golangci-lint issue to have more of a look at:

```
  level=error msg="Running error: assign: failed prerequisites: [inspect@github.com/layer5io/meshery/handlers: analysis skipped: errors in package: [/home/runner/work/meshery/meshery/handlers/k8sconfig_handler.go:12:2: could not import k8s.io/client-go/plugin/pkg/client/auth/gcp (/home/runner/go/pkg/mod/k8s.io/client-go@v0.18.12/plugin/pkg/client/auth/gcp/gcp.go:31:2: could not import golang.org/x/oauth2/google (/home/runner/go/pkg/mod/golang.org/x/oauth2@v0.0.0-20200107190931-bf48bf16ab8d/google/default.go:17:2: could not import cloud.google.com/go/compute/metadata (../../../go/pkg/mod/golang.org/x/oauth2@v0.0.0-20200107190931-bf48bf16ab8d/google/default.go:17:2: missing go.sum entry for module providing package cloud.google.com/go/compute/metadata (imported by golang.org/x/oauth2/google); to add:\n\tgo get golang.org/x/oauth2/google@v0.0.0-20200107190931-bf48bf16ab8d))) /home/runner/work/meshery/meshery/handlers/k8sconfig_handler.go:12:2: \"k8s.io/client-go/plugin/pkg/client/auth/gcp\" imported but not used]]"
```

**Comment by hexxdump** [comment]
> A golangci-lint issue to have more of a look at:
> 
> "
> level=error msg="Running error: assign: failed prerequisites: [[inspect@github.com](mailto:inspect@github.com)/layer5io/meshery/handlers: analysis skipped: errors in package: [/home/runner/work/meshery/meshery/handlers/k8sconfig_handler.go:12:2: could not import k8s.io/client-go/plugin/pkg/client/auth/gcp (/home/runner/go/pkg/mod/k8s.io/client-go@v0.18.12/plugin/pkg/client/auth/gcp/gcp.go:31:2: could not import golang.org/x/oauth2/google (/home/runner/go/pkg/mod/golang.org/x/oauth2@v0.0.0-20200107190931-bf48bf16ab8d/google/default.go:17:2: could not import cloud.google.com/go/compute/metadata (../../../go/pkg/mod/golang.org/x/oauth2@v0.0.0-20200107190931-bf48bf16ab8d/google/default.go:17:2: missing go.sum entry for module providing package cloud.google.com/go/compute/metadata (imported by golang.org/x/oauth2/google); to add:\n\tgo get golang.org/x/oauth2/google@v0.0.0-20200107190931-bf48bf16ab8d))) /home/runner/work/meshery/meshery/handlers/k8sconfig_handler.go:12:2: "k8s.io/client-go/plugin/pkg/client/auth/gcp" imported but not used]]"
> "

My bad, this needs rework. Moving the PR to WIP.

**Comment by leecalcote** [comment]
One final lint check getting in the way here...

**Comment by leecalcote** [comment]
@hexxdump, I'll make you a deal: teach me how to go fmt -s and I'll fix some of these on your behalf in the future.

**Comment by hexxdump** [comment]
> @hexxdump, I'll make you a deal: teach me how to go fmt -s and I'll fix some of these on your behalf in the future.

@leecalcote, its just about running "gofmt -s <problematic-file.go>" command.
I have fixed the issue and pushed the new change. Hopefully, now all checks should pass.

**Review by leecalcote — APPROVED** [review]

**Pull request merged**
