### PR TITLE
Add Related models category name

### PR DESCRIPTION
**Pull request by iArchitSharma**
image

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 5bb30eaa7a5a789fbba6327d11f2e71594e0e5b1 at: https://663b3ffca87aa311c957ac53--meshery-docs-preview.netlify.app

**Comment by ritiksaxena124** [comment]
@iArchitSharma looks like we have an issue here
image

**Comment by vishalvivekm** [comment]
Also: https://663b3ffca87aa311c957ac53--meshery-docs-preview.netlify.app/extensibility/integrations/antrea
image

**Comment by l5io** [comment]
🚀 Preview for commit 96d72ffa8117577d0fa79bfe9e1b577996d707be at: https://663b80072e23fd4d61bb4f5c--meshery-docs-preview.netlify.app

**Review by leecalcote — APPROVED** [review]

**Pull request merged**
