### PR TITLE
[UI] [Pattern] changed minor bugs on MesheryPattern.js

### PR DESCRIPTION
**Pull request by asubedy**
Signed-off-by: asubedy <frexpe@pm.me>

**Description**
This PR fixes:
1. Creation new design with the design configurator.
2. Updating the design in YAML dialog box on table view.

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
I canceled this flow "Golang Unit and Integration Tests / Integration tests (pull_request)", so its failure shouldn't be considered.

**Review by Chadha93 — APPROVED** [review]
Thanks, @asubedy will you also ensure the update behavior from YAML for applications too.

**Review by Abhishek-kumar09 — APPROVED** [review]
LGTM

**Comment by Abhishek-kumar09** [comment]
> Applications don't need any update, it is working fine. But after updating the YAML file the Application Name field on the table becomes empty

is it fixed or remaining?

**Comment by asubedy** [comment]
> > Applications don't need any update, it is working fine. But after updating the YAML file the Application Name field on the table becomes empty
> 
> is it fixed or remaining?
Fixed 👍

**Review by Chadha93 — APPROVED** [review]
LGTM @asubedy Thanks for apps fix

**Pull request merged**
