### PR TITLE
Go Upgrade

### LINKED ISSUE #12829: Upgrade Meshery Server and all Components to Golang 1.23.4
### Current Behavior
Meshery and its components all use golang 1.21.8 currently. Some packages that Meshery relies upon are no longer compatible with 1.21, but require 1.22 or higher. For example.

```
go: downloading github.com/99designs/gqlgen v0.17.57
go: github.com/99designs/gqlgen@v0.17.57 requires go >= 1.22.5 (running go 1.21.8; GOTOOLCHAIN=go1.21.8)
go: github.com/99designs/gqlgen@v0.17.57 requires go >= 1.22.5 (running go 1.21.8; GOTOOLCHAIN=go1.21.8)
make: *** [graphql] Error 1
```

### Desired Behavior
All components within the Meshery project to support the latest version of Golang (1.23.4).

### Implementation
1. github workflows: Uniformly, upgrade Meshery Server and all its components workflows to Golang 1.23.4.
1. makefile variables
1. github repo secret (if applicable)

- [x] https://github.com/meshery/meshery-kuma/issues/441 @devhindo
- [x] https://github.com/meshery/meshery-linkerd/issues/586
- [x] https://github.com/meshery/meshery-adapter-library/pull/164 @devhindo
- [ ] meshery/meshkit @weilirs 
- [ ] meshery-istio
- [ ] meshery-consul
- [ ] meshery-cilium
- [ ] meshery/meshery server
- [ ] meshery/meshery ctl

### Acceptance Tests
1. Meshery Extension providers notified of impending upgrade.
1. Compatibility of new version confirmed with each component and with Meshery Extension providers.

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by weilirs**
**Notes for Reviewers**

- This PR fixes #12829

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by weilirs** [comment]
I updated the version of go in these files, the next step is testing?

**Comment by weilirs** [comment]
After making these changes, I successfully ran `make build-server` and `make ui-build`.
For `make docker build`, I don't know if it is my computer lacks capacity, it got stuck at
```
➜  meshery git:(go-version-upgrade) ✗ make docker-build
# `make docker-build` builds Meshery inside of a multi-stage Do
# `make docker-build` builds Meshery inside of a multi-stage Docker container.
# This method does NOT require that you have Go, NPM, etc. inst
# This method does NOT require that you have Go, NPM, etc. installed locally.
DOCKER_BUILDKIT=1 docker build -f install/docker/Dockerfile -t 
DOCKER_BUILDKIT=1 docker build -f install/docker/Dockerfile -t layer5/meshery --build-arg TOKEN= --build-arg GIT_COMMITSHA=576
DOCKER_BUILDKIT=1 docker build -f install/docker/Dockerfile -t layer5/meshery --build-arg TOKEN= --build-arg GIT_COMMITSHA=5763fd32c72569aa24ecfd43168857ebaf256c80 --build-arg GIT_VERSION=v
DOCKER_BUILDKIT=1 docker build -f install/docker/Dockerfile -t layer5/meshery --build-arg TOKEN= --build-arg GIT_COMMITSHA=5763fd32c72569aa24ecfd43168857ebaf256c80 --build-arg GIT_VERSION=v0.7.167 --build-arg RELEASE_CHANNEL="edge" .
[+] Building 608.7s (31/59)               docker:desktop-linux
 => [internal] load build definition from Dockerfile     30.7s
 => => transferring dockerfile: 5.73kB                    0.0s
 => [internal] load .dockerignore                        30.3s
 => => transferring context: 2B                           0.1s
 => [internal] load metadata for docker.io/library/alpin  2.7s
 => [internal] load metadata for docker.io/layer5/getnig  2.5s
 => [internal] load metadata for docker.io/library/ubunt  2.7s
 => [internal] load metadata for docker.io/library/golan  3.1s
 => [internal] load metadata for docker.io/library/node:  2.7s
 => CACHED FROM docker.io/layer5/getnighthawk:v1.0.1@sha  0.1s
 => [seed_content 1/5] FROM docker.io/library/alpine:3.1  0.0s
 => [internal] load build context                       174.7s
 => => transferring context: 31.73MB                    170.3s
 => [wrk2 1/6] FROM docker.io/library/ubuntu@sha256:80dd  0.0s
 => [base-node 1/1] FROM docker.io/library/node:18.13.0-  0.0s
 => [meshery-server 1/5] FROM docker.io/library/golang:1  0.0s
 => CACHED [meshery-ui-provider-builder 1/4] WORKDIR /ap  0.0s
 => CACHED [seed_content 2/5] RUN apk add --no-cache cur  0.0s
 => CACHED [seed_content 3/5] RUN lines=$(curl -s https:  0.0s
 => CACHED [seed_content 4/5] RUN curl -L -s https://git  0.1s
 => CACHED [wrk2 2/6] RUN apt-get -y update && apt-get -  0.0s
 => CACHED [wrk2 3/6] RUN apt-get -y update && apt-get -  0.0s
 => CACHED [wrk2 4/6] RUN git config --global user.email  0.0s
 => CACHED [wrk2 5/6] RUN git config --global user.name   0.1s
 => CACHED [meshery-server 2/5] RUN adduser --disabled-l  0.0s
 => CACHED [meshery-server 3/5] WORKDIR /github.com/mesh  0.1s
 => [wrk2 6/6] RUN git clone --depth=1 https://github.  574.4s
 => CACHED [meshery-ui-provider-deps 1/4] RUN apk add --  0.0s
 => CACHED [meshery-ui-provider-deps 2/4] WORKDIR /app    0.0s
 => CACHED [meshery-ui-provider-deps 3/4] COPY provider-  0.0s
 => CACHED [meshery-ui-provider-deps 4/4] RUN npm ci --o  0.0s
 => CACHED [meshery-ui-deps 3/4] COPY ui/package.json ui  0.0s
 => [meshery-ui-provider-builder 2/4] COPY --from=mesh  399.6s
 => [meshery-ui-deps 4/4] RUN npm ci --omit=dev --lega  399.6s
 => [meshery-server 4/5] ADD . .                        399.0s
 => CACHED [stage-8  2/22] RUN set -ex &&     apk --upda  0.0s
 => CACHED [stage-8  3/22] RUN update-ca-certificates     0.0s
 => CACHED [stage-8  4/22] COPY ./server/cmd/server-conf  0.0s
 => [stage-8  5/22] COPY ./server/meshmodel /app/serve  399.0s
```

**Comment by devhindo** [comment]
Is this done yet?

**Comment by vishalvivekm** [comment]
@weilirs 
Let's discuss this during the Meshery Development call today at 9:00 AM CT | 8:30 PM IST. Adding it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit?pli=1#) || [meeting link](https://meet.layer5.io/meshery).

**Review by leecalcote — APPROVED** [review]
Looking good, @weilirs!

**Pull request merged**
