### PR TITLE
Fix Netlify builds

### LINKED ISSUE #849: Trigger PR specific CI jobs
**Current Behavior**

Currently, we are triggering all CI jobs irrespective of PR type. As discussed in the CI W/G, we need to trigger CI jobs that are related to PR which will reduce the CI Build Time as well as will be easy to manage.

**Desired Behavior**

Preferred Area->Jobs Relation -:

- Documentation -> Only run netlify
- Server -> Run Go-Vet/Sec/Tests/ErrCheck/Error-Test/Static-Check/Revive-Lint + Server Build Check
- Mesheryctl -> Run Go-Vet/Sec/Tests/ErrCheck/Error-Test/Static-Check/Revive-Lint + Mesheryctl build & releae 
- UI -> Run Tests+Lint+Build

**Way to move forward**

We are planning to incorporate conditional logic on the basis of PR Labels to let us know in what area does the PR include changes after then we will decide on the basis of the label to trigger the CI Jobs.

---
**Alternatives / Additional Context**

See https://github.com/layer5io/meshery/pull/832#pullrequestreview-392472434

### PR DESCRIPTION
**Pull request by ramrodo**
Signed-off-by: Rodolfo Martínez Vega <rodomar@outlook.com>

**Description**

This PR checks if there are changes in `docs` folder against **master**.

This PR fixes #849

**Notes for Reviewers**

We should configure in Github project settings to force to PRs to be rebased against master in order to have this working.

**[Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by ramrodo** [comment]
@leecalcote I finally understood this Netlify configuration. But, in order to have this working, we should configure the Github Project to force all the PRs to be up to date to master because if there is a change in **upstream master** and the PR has no that change, Netlify will be triggered (even if the PR has no changes in `docs`).

So, we need to go to `GitHub > Settings > Branches: Branch protection rule > Select "master" > Activate "Require branches to be up to date before merging"`.

**Comment by leecalcote** [comment]
Oh, interesting, @ramrodo. Looking at this now...

**Comment by leecalcote** [comment]
It seems that one of the build checks will need to be enforced in order for this setting to take affect. Is the "Pages changed - meshery docs" the most appropriate or is that the inverse of what we're looking to match?

**Comment by ramrodo** [comment]
@leecalcote Please check `golangci-lint` and some of the jobs related to docs: `Page build` and `Pages changed - meshery-docs`. Those checks should pass before merging any PR. I think those checks are enough for now.

**Comment by leecalcote** [comment]
Sounds real good, @ramrodo. I have checked `golangci-lint`, `Page build`, and `Pages changed - meshery-docs`.

**Comment by leecalcote** [comment]
You can now see an encircled **Required** label on those three checks.

**Comment by ramrodo** [comment]
@leecalcote According to the [last CI meeting](https://docs.google.com/document/d/1GrVdGHZAYeu6wHNLLoiaKNqBtk7enXE9XeDRCvdA4bY/edit?usp=sharing), we should **keep only** _"DCO bot"_ and **remove** _"Page Build and all the meshery-docs"_. And then, we can merge this PR

**Comment by leecalcote** [comment]
@ramrodo, ok, perfect. Settings updated. ✔️

**Review by leecalcote — APPROVED** [review]

**Pull request merged**
