### PR TITLE
added maximize and minimize to application

### PR DESCRIPTION
**Pull request by warunicorn19**
Signed-off-by: Aditya Chaterjee <speak2adi@gmail.com>

**Description**
Added maximize and minimize feature to application, might be nice to have. same approach as@Abhishek-kumar09

https://user-images.githubusercontent.com/53532328/135158817-5e23e4b5-2571-4d36-b0a0-2214ee99d70d.mov

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by warunicorn19** [comment]
@ramrodo tests are failing, https://github.com/meshery/meshery/pull/4268/checks?check_run_id=3737136488#step:13:170
and https://github.com/meshery/meshery/pull/4268/checks?check_run_id=3737136538#step:5:152

**Review by leecalcote — APPROVED** [review]
Wonderful. 👏

**Comment by leecalcote** [comment]
@warunicorn19 do you think you can do this same thing for Filters?

**Comment by warunicorn19** [comment]
@leecalcote yup, at least I think I can 😅.

**Comment by ramrodo** [comment]
> @ramrodo tests are failing, https://github.com/meshery/meshery/pull/4268/checks?check_run_id=3737136488#step:13:170 and https://github.com/meshery/meshery/pull/4268/checks?check_run_id=3737136538#step:5:152

Thanks for letting me know @warunicorn19. I'll fix them.

**Pull request merged**
