### PR TITLE
[Extension] load only Single page extension on desktop-desktop env

### PR DESCRIPTION
**Pull request by Abhishek-kumar09**
Signed-off-by: Abhishek-kumar09 <abhimait1909@gmail.com>

**Description**
This PR checks for user-agent in which the website is running and based on that loads the pages without drawer to restrict navigation

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Abhishek-kumar09** [comment]
Preview
image

**Comment by leecalcote** [comment]
@Abhishek-kumar09, what you have in the screenshot hits the nail on the head. It's good.

**Comment by leecalcote** [comment]
@Abhishek-kumar09 for your reference - https://youtu.be/y_LsCOG-PHE?t=15

**Comment by leecalcote** [comment]
> I assume you will be giving reference for all your idioms from now on 😸

ha!

**Review by leecalcote — APPROVED** [review]

**Pull request merged**
