### PR TITLE
Publish feature in UI for Catalog

### PR DESCRIPTION
**Pull request by harkiratsm**
Signed-off-by: harkiratsm <multaniharry714@gmail.com>

**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by harkiratsm** [comment]
@leecalcote @theBeginner86 @gr455 Can you test the publish feature, as that endpoint is limited to ```admin``` role.

**Comment by leecalcote** [comment]
User account permissions upgraded, @harkiratsm.

Merge conflict alert.

**Comment by leecalcote** [comment]
Another merge conflict.

@gr455 does this work?

**Comment by leecalcote** [comment]
> @leecalcote @theBeginner86 @gr455 Can you test the publish feature, as that endpoint is limited to `admin` role.

@harkiratsm, yes, @gr455 should be focused here, partnering closely.

**Comment by harkiratsm** [comment]
I tested and it is working fine :+1:

**Comment by leecalcote** [comment]
Thanks, @harkiratsm. Given that the GH workflow to publish the item in the meshery.io/catalog is failing, I question your assessment. I'll repeat: merge conflict(s) exist.

@gr455 should test with you.

**Comment by leecalcote** [comment]
@gr455, were you able to test and verify?

**Comment by leecalcote** [comment]
@harkiratsm a merge conflict has popped in the time waiting for functionality verification.

**Comment by leecalcote** [comment]
@gr455 are you driving this area?

**Comment by leecalcote** [comment]
@gr455 what would you like to do here?

**Comment by leecalcote** [comment]
@harkiratsm there's an outstanding merge conflict to address.

@gr455 have you tested this?

**Comment by harkiratsm** [comment]
merge conflicts resolved

**Pull request merged**
