### PR TITLE
fix : [UI] Failed to show Meshery UI on CLI Command Reference

### LINKED ISSUE #12606: [UI] Failed to show Meshery UI on CLI Command Reference
### Current Behavior

image

### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by Divyansh200102**
**Notes for Reviewers**

- This PR fixes #12606

-After
image

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 3ed6c687157be981cc9bb7097557d9d4f2be7366 at: https://6732615be72a7aa7e57800a4--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 4874bbd7f40a7fd991330c7322996754126a147a at: https://673264eca803a7a3af86978f--meshery-docs-preview.netlify.app

**Comment by vishalvivekm** [comment]
@JianMinTang ^^

**Comment by vishalvivekm** [comment]
requesting review from @JianMinTang

**Review by JianMinTang — APPROVED** [review]
LGTM

**Comment by l5io** [comment]
🚀 Preview for commit 66979bdb11619064d9cd39f73b6294d624b0b7b3 at: https://673b6ce15d808303f3fac361--meshery-docs-preview.netlify.app

**Comment by Divyansh200102** [comment]
> 🚀 Preview for commit 66979bdb11619064d9cd39f73b6294d624b0b7b3 at: https://673b6ce15d808303f3fac361--meshery-docs-preview.netlify.app

@vishalvivekm there were some conflicts in this pr so I have fixed them and the changes are approved by @JianMinTang .Can you merge the pr?

**Review by leecalcote — APPROVED** [review]
Thank you, @Divyansh200102 and @JianMinTang 👏

**Pull request merged**
