### PR TITLE
Update Doc link

### LINKED ISSUE #1212: [Docs] Update "Create doc issue" hyperlink to use new GitHub issue label
**Current State:**
The "Create doc issue" hyperlink on the Meshery Docs site is out of date. It refers to a GitHub issue label `docs` that this project no longer uses. This project now uses the `area/docs` label instead.

Screen Shot 2020-07-05 at 12 28 09 PM

**Desired State:**
Update [editable.html](https://github.com/layer5io/meshery/blob/master/docs/_includes/editable.html) to refer to the label `area/docs` not the old label `docs`.

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

### PR DESCRIPTION
**Pull request by Adeola-Adesoba**
Fixes #1212 
Signoff-by: Adeola Adesoba <adeoladee92@gmail.com>

**Description**

This PR fixes # 

**Notes to reviewers**

#### Checklist

- [] [Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin).
- [] PR title includes `[<name of area>]:<description>`

### CODE REVIEW

**Comment by leecalcote** [comment]
Hi @Adeola-Adesoba, thanks for this! Will you take a short moment to sign-off on your commit? You can do so in this PR by executing these commands - https://github.com/layer5io/meshery/pull/1215/checks?check_run_id=839548330

**Comment by morrme** [comment]
@leecalcote I had this issue too, when I committed from the browser. Since you helped me before,  I walked @Adeola-Adesoba through the command line DCO fix 😅

**Comment by leecalcote** [comment]
> @leecalcote I had this issue too, when I committed from the browser. Since you helped me before, I walked @Adeola-Adesoba through the command line DCO fix 😅

Rock on. You guys did team up. A feature request to support commit sign-offs through their web UI has been open with GitHub for a loooong time. These instructions have really saved people a long of time - https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin

**Comment by Adeola-Adesoba** [comment]
Thank you Lee. Glad the changes looked good.
@morrme thanks for the help with the DCO.

**Comment by leecalcote** [comment]
Yay, @Adeola-Adesoba! 🎈

**Pull request merged**
