### PR TITLE
Regrouped applications, filters, designs

### LINKED ISSUE #7170: [UI] Regroup Applications, Filters, and Patterns/Designs together
#### Current Behavior

Currently, in the `ui/components` folders, we have a couple of files such as `Filters.js` and `MesheryPatterns.js` that can be moved to its relevant folder such as `MesheryFilters` and `MesheryPatterns`.

#### Desired Behavior

This can help clean up and make certain files relevant and easier to find if you're having an issue with a certain page.

#### Implementation

Since we're using naming conventions such as `MesheryPatterns` or `MesheryApplications`, Filters can also get an update, and be moved to the designated folder.

#### Mockups

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by hs05june**
**Notes for Reviewers**

This PR fixes #7170 

https://user-images.githubusercontent.com/103871275/221399363-112a7637-6f84-4045-ada2-139bf981eb59.mp4

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by hs05june** [comment]
Hey @lee. Please review the PR.

**Comment by hs05june** [comment]
@leecalcote @acald-creator How would it be if we regroup other as well?? Like Settings has many components (MesherySettings, MesherySettingsEnvButtons etc). They all can be grouped.

**Comment by acald-creator** [comment]
@hs05june Hey thanks for your PR.

At this time, we're focusing on these three, as my next plan to update the code editor, and I wanted to group these so it is easier to debug code editor issues.

**Comment by Chadha93** [comment]
@hs05june Let's discuss this on the Meshery Dev call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#) if you would. :)

**Comment by Chadha93** [comment]
:eyes:

**Comment by leecalcote** [comment]
@hs05june it'd be great to see a redesign proposal in the Meshery UI figma design file. There are major improvements to be done in Meshery's UI. A mockup will help facilitate traction in this regard.

**Comment by harkiratsm** [comment]
Instead, you can refractor the entire code which would be great.
Since Applications, Patterns & Filter nearly share the same code reusability would be at peak. 
It would save the effort during the muiv5 migration as well.

// @Abhishek-kumar09 @acald-creator @leecalcote @hs05june @Chadha93

**Comment by harkiratsm** [comment]
You can look at the previous effort of muiV5 to get the context of what I am speaking of.

https://github.com/meshery/meshery/tree/meshery-ui-restructuring

**Comment by acald-creator** [comment]
@harkiratsm I agree, which is what I'm working on with my open issue regarding the code editor. By doing this, I'll be moving this around things close to what it is on the ui restructuring branch. I only brought this up as multiple steps to get there instead of one big pr.

**Pull request closed without merging**
