### PR TITLE
commented empty 'suggested reading' section

### LINKED ISSUE #7708: dead link for 'Suggested reading' in Meshery doc
### Description
There's a section for "Suggested Reading" but there's no content in it, also it has a dead link
It seems that the section is still under development, until it's get ready , this section can removed or hidden in production
problem_2

### Expected Behavior

- [ ] remove or hide the "Suggested Reading" section

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by sayyedarib**
**Notes for Reviewers**
The suggested reading section had no content inside it , so I have commented it for now.
Also there are changes in gemfile, I had to make just to setup the environment.(which I have reverted it now in further commit)

This PR fixes #7708

Earlier
solving_issue

Now
solve_issue

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit bfe0554797808fe700cd80498857cfec5564f36a at: https://646900108d6d8d4750015e4a--meshery-docs-preview.netlify.app

**Comment by sayyedarib** [comment]
@leecalcote please review this

**Comment by alphaX86** [comment]
@sayyedarib you didn't mean to close this PR, do you? 👀

**Comment by sayyedarib** [comment]
But i didn't closed any PR, how can this be possible?

**Comment by sayyedarib** [comment]
@alphaX86  sorry i didn't knew that it would close that PR
My laptop's storage was getting full , so I was trying to delete most of files
and I did the same the meshery clone, and thought it would be better to fork again and clone

It was simple issue, I can create PR again

BTW everyday I'm learning new thing at layer 5 :)

**Comment by alphaX86** [comment]
Oh... one tip though, once you forked this repo in your GitHub account, you need not re-fork it again as it'll be present in your account itself and not in your local storage. However, if you feel that you need to work on this repo while saving storage in your local system, then I suggest you to try the online IDEs like GitPod, GitHub Codespaces

**Pull request closed without merging**
