### PR TITLE
add error code monikers

### LINKED ISSUE #10761: [Server] Not returning error code moniker in events, only numeric error code.
### Current Behavior
Example error:
Screenshot 2024-04-23 at 10 32 32 AM

Hyperlinks to https://docs.meshery.io/reference/error-codes#meshery-server-1073, which only includes the sub-system ("meshery-server") and not the moniker ("ErrCompConfigPairsCode").

### Expected Behavior
Moniker should be included in addition to component.

### Environment

- **Meshery Server Version:** stable-v0.7.46

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by EleisonC**
**Notes for Reviewers**
Add Error code monikers for Meshery server

This PR fixes #10761 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — COMMENTED** [review]
Thanks! Are these updates done after having changed the error code utility in MeshKit?

If you haven't seen the [Messaging Framework and Notification Center](https://docs.google.com/document/d/1_zpEWBcC6ngOLen_E_nc-octiUdBbpmdwwIX6qzo70M/edit) design specification, it's a good one to peruse.

**Comment by EleisonC** [comment]
> Thanks! Are these updates done after having changed the error code utility in MeshKit?
> 
> If you haven't seen the [Messaging Framework and Notification Center](https://docs.google.com/document/d/1_zpEWBcC6ngOLen_E_nc-octiUdBbpmdwwIX6qzo70M/edit) design specification, it's a good one to peruse.

Alright I am taking a look

**Comment by leecalcote** [comment]
I updated the Meshery Docs Error Codes page with (hopefully) helpful details with regard to the combination of details - https://docs.meshery.io/reference/error-codes

**Comment by leecalcote** [comment]
@MUzairS15, as we go to enhance the format of the MeshKit Error Codes, will this format mess up anything other than the Meshery Docs error code page? Are Meshery Events v2 completely separate or do they use the same messaging framework, but with simply a different event format?

@aabidsofi19, the Notification Center will need to be updated, I assume.

**Comment by EleisonC** [comment]
> I updated the Meshery Docs Error Codes page with (hopefully) helpful details with regard to the combination of details - https://docs.meshery.io/reference/error-codes

Alright I will make the changes shortly and push them thank you for the help @leecalcote

**Comment by vishalvivekm** [comment]
Hey @EleisonC , let's discuss this on today's Meshery Dev meeting at 7:30 PM IST. I am adding this as an [agenda item](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit?pli=1#). Please Join https://meet.layer5.io/meshery if you are available during the meet.

**Comment by vishalvivekm** [comment]
> Hey @EleisonC , let's discuss this on today's Meshery Dev meeting at 7:30 PM IST / 15 minutes from now. I am adding this as an [agenda item](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit?pli=1#). Please Join https://meet.layer5.io/meshery if you are available during the meet.

**Comment by leecalcote** [comment]
Let me know if this is to be reopened...

**Pull request closed without merging**
