### PR TITLE
[mesheryctl] Implementing usage of Meshkit for logging instead of logrus/fmt

### LINKED ISSUE #6309: [mesheryctl] Implement usage of meshkit for logging instead of logrus/`fmt.Print`
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior

We've implemented our own function library called Meshkit in which it can be used to implement logging, show error messages and so on. But the logging function isn't used/changed and still the legacy code exists, we need to remove them in the `mesheryctl` code base

#### Desired Behavior

Implement the usage of Meshkit's own logger function `utils.Log` instead of using Logrus or `fmt` package

#### Implementation

Replacing the Logrus/fmt function with the intended function would do the trick

#### Acceptance Tests

None

#### Mockups

None

---

#### Contributor Resources

- ⌨️ [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by kamalbuilds**
Scenario Implemented.

Removing the logrus code in the mesheryctl code base and Implementing the usage of Meshkit's own logger function utils.Log instead of using Logrus or fmt package.

This PR fixes #6309

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by alphaX86** [comment]
Seems bit unstabilized, we need to fix lint and other errors too

**Comment by legendarykamal** [comment]
> Seems bit unstabilized, we need to fix lint and other errors too

yeah looking to .

**Comment by Chadha93** [comment]
@legendarykamal Let's discuss this on the Meshery Dev call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#) if you would. :)

**Comment by legendarykamal** [comment]
sure , @Chadha93 I have added it ✅

**Comment by acald-creator** [comment]
Reviewing...

**Comment by acald-creator** [comment]
@leecalcote , @legendarykamal

Was there any intention in the past to move away from `logrus`?

There's an import cyclic error happening with the `pkg/utils` calling for `mesheryctl/internal/cli/root/config`.

If we are to move away from `logrus`, why are we not using the logging implemented from `meshkit` itself, instead of an `internal` and or `pkg` within `mesheryctl`?

Attempting to use within the directory is causing this error. Either we move this someplace else, or using an existing logging function from `meshkit` repo itself.

Just a side question, maybe we should move away from `logrus` altogether and use a different logging tool?

Can you help me understand?

**Comment by leecalcote** [comment]
@acald-creator you hit the nail on the head with this suggestion: ```or using an existing logging function from meshkit repo itself.```

**Comment by acald-creator** [comment]
Still working on this.

**Comment by acald-creator** [comment]
Close PR, will create a new one

**Pull request closed without merging**
