### PR TITLE
Fix technology not showing in info modal

### PR DESCRIPTION
**Pull request by Yashsharma1911**
**Notes for Reviewers**

This PR fixes #

- [X] Added case validation on UI side
- [X] Made fields not required
- [X] Used RTK

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by Yashsharma1911** [comment]
I'll be making a couple of more enhancements here so that we don't get any rerender issues or other issues in future, to prevent rerender I'll be separating them from the parent component so that they don't depend on parent component states

**Comment by Yashsharma1911** [comment]
@sudhanshutech can you help with testing this PR, lemme know if you find any issue related to losing focus during typing or losing technology in technology field

**Comment by sudhanshutech** [comment]
sure @Yashsharma1911 , i will get back to you after testing

**Review by leecalcote — DISMISSED** [review]

**Comment by leecalcote** [comment]
> @sudhanshutech can you help with testing this PR, lemme know if you find any issue related to losing focus during typing or losing technology in technology field

Again, this is only applicable in MeshMap Designer.

**Comment by leecalcote** [comment]
@Yashsharma1911 make sure that you have tested the Info / Share modal in Visualizer, too.

**Comment by Yashsharma1911** [comment]
@sudhanshutech have checked?

**Review by sudhanshutech — APPROVED** [review]
Yes i checked, its working fine for me. There was no loosing focus

**Comment by Yashsharma1911** [comment]
> Yes i checked, its working fine for me. There was no loosing focus

Thankyou @sudhanshutech

**Pull request merged**
