### PR TITLE
fix: Create/Delete/Read on user test profiles

### PR DESCRIPTION
**Pull request by kushthedude**
This PR is an extension for PR #1158 where @kanishkarj did most of the work to introduce the CRD operations on test profiles.

To test the PR -:

**Create a Test Profile**
```sh
curl --location --request POST 'localhost:9081/api/user/test-prefs' \
--header 'Content-Type: application/json' \
--header 'Cookie: meshery-provider=None' \
--data-raw '{
  "smpsVersion": "v0.1",
  "name": "quick-test",
  "labels": {
    "h1": "v1"
  },
  "clients": [
    {
      "internal": false,
      "loadGenerator": "fortio",
      "protocol": "http",
      "connections": 10,
      "rps": 10,
      "headers": {
        "header1": "val1"
      },
      "cookies": {
        "cookie1": "val1"
      },
      "body": "ReqBody",
      "contentType": "application/txt",
      "endpointUrl": [
        "https://githudfgb.com"
      ]
    }
  ],
  "duration": "1s"
}'
```
**Get a Test Result**
```sh
curl --location --request GET 'localhost:9081/api/user/test-prefs?uuid=<TEST_ID>' \
--header 'Cookie: meshery-provider=None'
```
**Get all Test Results** (Pagination API is already implemented)
```sh
curl -v --location --request GET 'localhost:9081/api/user/test-prefs?page=0&pageSize=10' \ --header 'Cookie: meshery-provider=None'
```
**Delete a Test Result**
```sh
curl --location --request DELETE 'localhost:9081/api/user/test-prefs?uuid=<TEST_ID>' \
--header 'Cookie: meshery-provider=None'
```

### CODE REVIEW

**Comment by kushthedude** [comment]
@kanishkarj The error which was being faced in your old PR was due to the gorilla mux. After reading documentation, to migrate to mux we will have to re-write our UI handler which may serve the frontend files from the UI. I guess it will be better to have gorilla migration in an another PR where we can reform our handlers on the basis of request objects as you had done them earlier.
/cc @leecalcote

**Comment by kanishkarj** [comment]
Ahh! Makes sense. Thanks a lot @kushthedude

**Comment by leecalcote** [comment]
@kushthedude a few conflicts to resolve - https://github.com/layer5io/meshery/pull/1398/conflicts

**Comment by kushthedude** [comment]
@leecalcote fixed!

**Pull request merged**
