### PR TITLE
refactor(mesheryctl): Promote environment command

### LINKED ISSUE #12947: [mesheryctl] Promote environment command from experimental
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

We need to promote environment subcommand

### Current Behavior

Command is available under experimental status

```bash
mesheryctl exp environment
```
### Desired Behavior

Should move as regular subcommand

```bash
mesheryctl environment
```

### Implementation

1. move subcommand under root
2. Update related documentation 

### Acceptance Tests

- command is available at root subcomands level
- documentation is updated

### Mockups

---

### Contributor Resources

- ⌨️ [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by lekaf974**
**Notes for Reviewers**

- This PR fixes #12947 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit c4f3f042d25f5415d3cf6bde34e612681bb4f1d2 at: https://676ed6775d0d59612ea3e7e6--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit bbbadaee57603723345adda0be342c87ab2068ea at: https://676ed9ff97d6ea5c46fb0ab1--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 87e1da7ccae45b9402cf35b970547e86fa1b6efb at: https://676edbe10a5c636bf8a876d9--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 8c5320f82db9f8114260fc3a4450b7c79300f886 at: https://676edd7e9d3a5b66a7174b4e--meshery-docs-preview.netlify.app

**Comment by leecalcote** [comment]
@souvikinator

**Review by alphaX86 — APPROVED** [review]

**Comment by l5io** [comment]
🚀 Preview for commit abb4722fb7156197c6b5bda59117e55e83e6a4e5 at: https://676f6f0de4af280eb4a5b33d--meshery-docs-preview.netlify.app

**Review by souvikinator — APPROVED** [review]

**Comment by l5io** [comment]
🚀 Preview for commit 4faddceb9921687b13e9857123dbe524525b51a8 at: https://6771654f644e6110ed76d13a--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 03144e34a4906b90e88280d8900a4b3267eb0549 at: https://6771cb09c548a586175da854--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit bd7c6d282d242f4489c25b823aa124bb8f6fc129 at: https://6772227d4e3074dcd3e33180--meshery-docs-preview.netlify.app

**Review by leecalcote — APPROVED** [review]
Merge conflict resolved.

**Comment by leecalcote** [comment]
Yay! A new top-level command 🚀

**Pull request merged**
