### PR TITLE
Updated the meshkit error for schedule_handler.go 

### LINKED ISSUE #3275: [Chore] Update Handlers to use new Meshkit Errors
#### Current Behavior
Meshery Server (and its other components, like Adapters) use a centralized library, MeshKit, to provide uniform utilities (e.g. raising and logging errors). Currently, Meshery Server uses a now antiquated style of error logging with logrus.

#### Desired Behavior
Ideally, all use of logrus is replaced with use of MeshKit-style error logging.

#### Implementation
Meshery Handlers needs to be:
 - Updated to use meshkit errors. 
 - Switch to handler Log instead of `logrus`

Handlers to update:

  - [x] event streamer
  - [x] fetch results handler
  - [x] k8sconfig handlers
  - [x] load test handler
  - [x] load test mesh handler
  - [x] load test preferences handler (#3390)
  - [x] mesh ops handler
  - [x] meshery application handler
  - [ ] meshery filter handler
  - [ ] meshery pattern handler
  - [x] oam handler (#3387)
  - [x] performance profiles handler
  - [x] provider handler 
  - [x] schedule handler
  - [x] server spec handler
  - [x] session sync handler
  - [x] user handler
  - [x] Grafana handler
  - [x] Prometheus Handler
     
For reference, you can checkout  the `grafana handler` and `prometheus handler` or the [docs](https://docs.meshery.io/project/contributing-error).

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

### LINKED ISSUE #3304: [Chore] Update performance profile, provider, and schedule handlers to use new Meshkit Errors
Note: This is a child issue of #3275 
#### Current Behavior
Meshery Server (and its other components, like Adapters) use a centralized library, MeshKit, to provide uniform utilities (e.g. raising and logging errors). Currently, Meshery Server uses a now antiquated style of error logging with logrus.

#### Desired Behavior
Ideally, all use of logrus is replaced with use of MeshKit-style error logging.

#### Implementation
Meshery Handlers needs to be:
 - Updated to use meshkit errors. 
 - Switch to handler Log instead of `logrus`

Handlers to update:

- [ ] performance profiles handler
- [ ]  provider handler
- [x]  schedule handler

For reference, you can checkout  the [`grafana handler`](https://github.com/layer5io/meshery/blob/master/handlers/grafana_handlers.go) and [`prometheus handler`](https://github.com/layer5io/meshery/blob/master/handlers/prometheus_handlers.go) or the [docs](https://docs.meshery.io/project/contributing-error).
Define all Error functions for all the handlers to be written in the `handlers/error.go` file.

#### Mockups

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

### PR DESCRIPTION
**Pull request by Shreyas220**
Signed-off-by: Shreyas220 <shreyas.ny@gmail.com>

**Description**
Updated the meshkit error for schedule_handler.go file

This PR fixes #3304 

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Shreyas220** [comment]
@sayantan1413 Please review

**Comment by sayantan1413** [comment]
Hey @Shreyas220 I think it would be good if we log the error before the https.Error .

**Review by sayantan1413 — APPROVED** [review]
LGTM. @kumarabd please have a review on this.

**Review by kumarabd — APPROVED** [review]
LGTM

**Pull request merged**
