### PR TITLE
add network policy as a relationship

### PR DESCRIPTION
**Pull request by MUzairS15**
**Notes for Reviewers**

This PR adds a new relationship b/w Pods, that restricts how Pods can communicate with each other.

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by MUzairS15** [comment]
@leecalcote  After merging this relationship cannot be visualized in MeshMap, as there is small amount of hardcoding.

I am thinking of how to leverage Relationship schema to get rid of this hardcoding

**Comment by leecalcote** [comment]
> @leecalcote After merging this relationship cannot be visualized in MeshMap, as there is a small amount of hardcoding.
> 
> I am thinking of how to leverage Relationship schema to get rid of this hardcoding

@MUzairS15 does this break the existing relationship functionality? Or are you saying that only this Firewall relationship won't quite work just yet?

**Comment by MUzairS15** [comment]
The later,  will not break,

**Comment by leecalcote** [comment]
> The later, will not work.

Ok, understood: This PR doesn't break anything, however, it doesn't completely deliver a functional relationship either. 👌

**Review by leecalcote — CHANGES_REQUESTED** [review]

**Pull request merged**
