### PR TITLE
Fix Multi-Context

### PR DESCRIPTION
**Pull request by tangledbytes**
**Description**

This PR attempts to fix:
Environment: Kubernetes context present but API server unreachable
1. Auth flow failure when no client is present.
2. Meshery crash when operator operation is invoked.
3. Meshery crash when GraphQL API invoked.
4. Middleware interruption removed, handlers should be handling the `nil` kubeclients.

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
There he is! Mr. Pro.

**Review by Revolyssup — APPROVED** [review]

**Comment by warunicorn19** [comment]
https://user-images.githubusercontent.com/53532328/154156593-84034650-2cc0-48ad-b9a5-c43f7b38fc72.mov

Running a performance test is breaking the UI

**Comment by warunicorn19** [comment]
Fixed the UI crashing on running performance test
Fixed empty chip when Kubernetes not connected.

**Comment by leecalcote** [comment]
Issue 1: On click of the "x" on the Kubernetes chip in the Settings UI, the context is deleted with log output:

```
INFO[0129] kubernetes context successfully retrieved from remote provider
```

But chip remains in the UI.

**Comment by leecalcote** [comment]
Issue 2:

Scenario: User has no Kubernetes cluster available. User navigates to Settings page. Page returns "unexpected error" with the following console log:

Screen Shot 2022-02-15 at 4 56 36 PM

and Meshery Server log:
```
Failed to load resource: the server responded with a status of 500 (Internal Server Error)`
````

**Comment by leecalcote** [comment]
Merging as this PR provides some fixes. Additional issues identified in need of follow up fixes...

**Pull request merged**
