### PR TITLE
[Connections] Connection State Management

### PR DESCRIPTION
**Pull request by MUzairS15**
**Notes for Reviewers**

This PR fixes #

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
@MUzairS15 merge conflict.

Is this PR dependent upon the new k8s connection definition PR?

**Comment by leecalcote** [comment]
Some extra logs that we might want to cut down on:

```
INFO[2023-11-17T14:18:06-06:00] entering event loop                           app=meshery
INFO[2023-11-17T14:18:06-06:00] inside getNextState: discoverytrue            app=meshery
INFO[2023-11-17T14:18:06-06:00] next state: discovered                        app=meshery
INFO[2023-11-17T14:18:06-06:00] transitioning to next state: discovered       app=meshery
INFO[2023-11-17T14:18:06-06:00] entry action executed, event emitted noop     app=meshery
```

**Comment by leecalcote** [comment]
Each time that I refresh my browser, I get four of these:

Screenshot 2023-11-17 at 2 20 46 PM

**Comment by MUzairS15** [comment]
removed logs.

**Comment by MUzairS15** [comment]
It indicates you don't have any connected cluster. Server is trying to import local kubeconfig and trying to connect.
Previously, user's were not notified about this behaviour.

The concern with having repitive notifications, this is happening because when the browser is refreshed several initialisation requests are made from the UI, causing the same logic to get invoked.

**Comment by MUzairS15** [comment]
Merging by EOD.

**Comment by leecalcote** [comment]
> It indicates you don't have any connected cluster. Server is trying to import local kubeconfig and trying to connect. Previously, user's were not notified about this behaviour.
> 
> The concern with having repitive notifications, this is happening because when the browser is refreshed several initialisation requests are made from the UI, causing the same logic to get invoked.

This all makes sense (no news here). 

What I’m pointing out is that this needs to be taken care of. With this PR merged, is there a new issue tracking this bug regarding duplicative notifications?

**Pull request merged**
