### PR TITLE
Create smi-conformance-capability.md

### LINKED ISSUE #1373: [Docs]Add section in docs about Meshery's SMI Conformance capability
**Current State:**
Reference material for the short write-up: https://docs.google.com/document/d/1HL8Sk7NSLLj-9PRqoHYVIGyU6fZxUQFotrxbmfFtjwc/edit#

**Desired State:**
Perhaps, add this new capability at in a new page under https://meshery.layer5.io/docs/functionality

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

### PR DESCRIPTION
**Pull request by ghost**
Signed-Off-By: KarenEfereyan <thedevkaren@gmail.com>

**Description**
Added smi-conformance-capability file in a  new page under docs/

This PR fixes #1373

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by NupurThakur27** [comment]
@KarenEfereyan I am so glad you passed all the checks. So proud of you. 🎉

**Comment by KarenEfereyan** [comment]
Your kindness @NupurThakur27 made it possible

**Comment by leecalcote** [comment]
Whoa, impressive. Well done, @KarenEfereyan. A good layout with appropriate length summary. ✔️

**Comment by PluckyPrecious** [comment]
Yippe! 🥳 Welldone Karen.

**Pull request merged**
