### PR TITLE
new cards for design

### PR DESCRIPTION
**Pull request by captain-Akshay**
**Notes for Reviewers**

This PR fixes #

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by captain-Akshay** [comment]
Screenshot from 2024-05-13 19-34-40

**Comment by leecalcote** [comment]
@Rexford74 this design is missing a few consideration.

**Comment by sudhanshutech** [comment]
@captain-Akshay @Rexford74 did we finalized here ?

**Comment by leecalcote** [comment]
@dottharun, should we continue or discontinue with this PR?

**Comment by dottharun** [comment]
> @dottharun, should we continue or discontinue with this PR?

We can use this PR if Sistent migration can be done later and everything is functional.

**Pull request closed without merging**
