### PR TITLE
Fix sidebar top

### PR DESCRIPTION
**Pull request by abhishekmmgn**
**Notes for Reviewers**

This PR fixes #
image
Now:
image

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
@abhishekmmgn this bug was recently introduced. The margin for page content should not be 0%, so that the pull tab doesn't overlap.

Screenshot 2024-04-25 at 8 00 55 AM

**Comment by l5io** [comment]
🚀 Preview for commit f8f05f0f88737ed37e2d463b4a3f131d57f9ba87 at: https://66392f15783c73291ff72953--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 0790dd9245f999613687b6c732d1bc7d07a77584 at: https://663a2022ad9ae619abf2ee9d--meshery-docs-preview.netlify.app

**Review by iArchitSharma — APPROVED** [review]
Good to go now!

**Pull request merged**
