### PR TITLE
[Fixed] : Meshery UI errors related to permissions while importing a file

### LINKED ISSUE #10449: [Meshery UI] : Meshery UI encountering errors related to permissions while importing a file.
### Current Behavior
Users encounter permission errors when attempting to import files via Meshery UI. This issue disrupts the import process and prevents users from successfully uploading their files. Checkout the ongoing [discussion](https://discuss.layer5.io/t/unable-to-import-designs-docker-compose/4537) on the forum about the issue

### Desired Behavior
Users should be able to import files smoothly without encountering permission errors. Meshery UI should handle file imports seamlessly, ensuring a hassle-free experience for users.

### Environment

- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Meshery Build and Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 UI Design For Meshery Extensions [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 📚 [Meshery Extensibility Providers](https://docs.meshery.io/extensibility/providers)
- ⌨️ [Meshery API Docs](https://docs.meshery.io/extensibility/api)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by Adarsh-jaiss**
**Notes for Reviewers**

This PR fixes #10449 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by vishalvivekm** [comment]
@Adarsh-jaiss  Let's discuss this on the Meshery Dev call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#) if you would. :)

**Comment by Adarsh-jaiss** [comment]
> @Adarsh-jaiss Let's discuss this on the Meshery Dev call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#) if you would. :)

Sure :)

**Comment by leecalcote** [comment]
Refactoring in-progress?

**Comment by Adarsh-jaiss** [comment]
> Refactoring in-progress?

Yup!!!!
Will Create a PR soon :)

**Comment by Yashsharma1911** [comment]
@Adarsh-jaiss you still working on this?

**Comment by Adarsh-jaiss** [comment]
yup @Yashsharma1911 
Sorry for the delay, i'll just work on this, and make a PR by tommorow EOD!

**Comment by Yashsharma1911** [comment]
@Adarsh-jaiss you will be raising new PR or update this one?

**Comment by Adarsh-jaiss** [comment]
> @Adarsh-jaiss you will be raising new PR or update this one?

I'll raise a new PR

**Pull request closed without merging**
