### PR TITLE
Adds custom names to catalog clone API

### PR DESCRIPTION
**Pull request by gr455**
Signed-off-by: Ruturaj Mohite <mohite.ruturaj15@gmail.com>

Earlier the clone API did not support any extra parameters when cloning the catalog items. This commit adds support for custom name when cloning catalog item.

**Notes for Reviewers**

This PR fixes #

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by harkiratsm** [comment]
@gr455 Seems like the payload from UI is correct, but at the backend there may be a problem, Can you confirm me that ? I tried clone but I see no changes in name of the Cloned Design.

**Comment by gr455** [comment]
> @gr455 Seems like the payload from UI is correct, but at the backend there may be a problem, Can you confirm me that ? I tried clone but I see no changes in name of the Cloned Design.

Yes @harkiratsm you will also have to run meshery cloud's PR for this locally. The PR is on m cloud

**Comment by harkiratsm** [comment]
I got it, I wasn't aware about the cloud PR.

**Comment by leecalcote** [comment]
Harikat, what do you think? @harkiratsm

**Comment by harkiratsm** [comment]
It is good to have & I would test the PR .

**Comment by leecalcote** [comment]
Thank you, @harkiratsm.

**Comment by leecalcote** [comment]
@gr455

**Comment by gr455** [comment]
Waiting for @harkiratsm's review and UI changes. This is good to go from my side

**Comment by Chadha93** [comment]
@gr455  Let's discuss this on the Meshery Dev call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#) if you would. :)

**Comment by leecalcote** [comment]
@Revolyssup ...

**Comment by leecalcote** [comment]
@Revolyssup ?

**Comment by Revolyssup** [comment]
> @Revolyssup ?

Some equivalent changes would be required in meshery cloud. I dont see a PR up for that. I will take this up from here and create a subsequent PR in meshery cloud.

**Comment by Revolyssup** [comment]
@gr455 Checking in.. Just in case you have made the appropriate changes in meshery cloud and didn't create the PR.

**Comment by gr455** [comment]
> @gr455 Checking in.. Just in case you have made the appropriate changes in meshery cloud and didn't create the PR.

I had, I think GH auto removed my PR when I lost access. Is there a way I can get those changes in now?

**Comment by Revolyssup** [comment]
> > @gr455 Checking in.. Just in case you have made the appropriate changes in meshery cloud and didn't create the PR.
> 
> I had, I think GH auto removed my PR when I lost access. Is there a way I can get those changes in now?

No worries, I will takeover this PR from here and make the subsequent changes in cloud. Thank you for the change so far.

**Review by Revolyssup — APPROVED** [review]

**Pull request merged**
