### PR TITLE
fix(ci/lint): fix failing lint check

### LINKED ISSUE #6098: Failing lint checks - [Fix ] Add logic to modify component scheme regarding inconsistent naming
See [Fix ] Add logic to modify component scheme regarding inconsistent naming | CU-2jp390j #6095

#### Example:
Screen Shot 2022-08-27 at 3 19 10 PM

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by whois-pk**
Signed-off-by: pk-218 <53428217+pk-218@users.noreply.github.com>

**Description**
Fixed failing lint staticcheck - [validate.go](https://github.com/meshery/meshery/blob/master/server/handlers/validate.go#L121)

This PR fixes #6098 

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by pk-218** [comment]
@leecalcote there are some other lint checks that have been failing apart from this staticcheck for other PRs are well. Shall I look for a fix for these as well?

**Comment by leecalcote** [comment]
@pk-218, yes, that would be great. 👌

**Comment by pk-218** [comment]
All lint checks pass now 🎊

**Comment by pk-218** [comment]
@leecalcote can you approve these changes? Lint checks are passing now

**Comment by leecalcote** [comment]
@pk-218 you addressed this separately, right? https://github.com/meshery/meshery/runs/8053832984?check_suite_focus=true#step:5:250

**Comment by leecalcote** [comment]
Right, yes. Here it is: https://github.com/meshery/meshery/pull/6111

**Comment by pk-218** [comment]
Thanks @leecalcote! First PR merged at Meshery 🥳

**Comment by leecalcote** [comment]
Ka-pow! 💥 Boom, bam! 🚀 This is most excellent. 😀 

The start to a ❤️ story, I hope. 🥰

**Pull request merged**
