### PR TITLE
Removed duplicate code and merged them

### PR DESCRIPTION
**Pull request by Nikhil-Ladha**
#461 Fixed!
Signed-off-by: Nikhil-Ladha <nikhilladha1999@gmail.com>

### CODE REVIEW

**Comment by leecalcote** [comment]
@Nikhil-Ladha will you look into the Meshery UI build check error?

**Comment by Nikhil-Ladha** [comment]
@leecalcote in the build process the issue is that the build check is looking for `MeshConfigComponent.js` file, but now it has been removed in this pr and merged with `MeshOutClusterConfig.js` file. So, i guess the build check process has to be modified.

**Comment by Nikhil-Ladha** [comment]
Or another thing i may try is that instead of changing both the file to `MeshOutClusterConfig.js` i will merge them in `MeshConfigComponent.js` and then make the PR?

**Comment by Nikhil-Ladha** [comment]
@leecalcote as expected that was only the issue the missing file `MeshConfigComponent,js`. Now it's good!

**Pull request merged**
