### PR TITLE
[UI]fixed the overflowing RJSF form

### LINKED ISSUE #4024: [UI] Broken Pattern Accordion
#### Current Behavior

Some Recent code change may have broken the accordion behaviour for pattern and RJSF form editing wizard.

https://user-images.githubusercontent.com/48255244/131253767-68258766-d300-4e8f-bcff-dce7007236ff.mp4

**Ignore right cutout of video, it was to emphasise on accordion behaviour and problems**

#### Desired Behavior

The siblings of accordion should behave responsibly.

#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by warunicorn19**
Signed-off-by: Aditya Chaterjee <speak2adi@gmail.com>

**Description**
Fixed the accordion.

https://user-images.githubusercontent.com/53532328/131259429-7db6599a-07bb-4ea2-884e-abf4d126d19e.mov

This PR fixes #4024 

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by sudo-NithishKarthik** [comment]
Its weird 🤔 , UI integration test is still failing...

**Comment by warunicorn19** [comment]
@sudo-NithishKarthik did someone put in a fix?🤔

**Comment by leecalcote** [comment]
FWIW - sometimes GH workflows fail for reasons of the GitHub runner having an issue. I don't think that is the case with respect to the backend failure. I'm mentioning this as just an FYI.

**Comment by sudo-NithishKarthik** [comment]
> @sudo-NithishKarthik did someone put in a fix?🤔

yes, #4000

**Review by Abhishek-kumar09 — COMMENTED** [review]
Nice

**Pull request merged**
