### PR TITLE
changes the application icon w/signoff

### LINKED ISSUE #7023: [UI] Update the Application Icon
#### Current Behavior

image

#### Desired Behavior

Update the application icon to the one described in [figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=5871%3A25449&t=0kGGPBYbMNyOerq6-0)

#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by AakashRaj20**
**Notes for Reviewers**

This PR fixes #7023

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — COMMENTED** [review]
Thank you, @AakashRaj20. How are both dark and light mode considered here?

**Comment by AakashRaj20** [comment]
> Thank you, @AakashRaj20. How are both dark and light mode considered here?
I will share some ss to explain

**Comment by AakashRaj20** [comment]
> Thank you, @AakashRaj20. How are both dark and light mode considered here?

Screenshot from 2023-04-05 21-09-12
Screenshot from 2023-04-05 21-08-58

**Comment by AakashRaj20** [comment]
> Thank you, @AakashRaj20. How are both dark and light mode considered here?

So I only Changed the svg code of the old icon with new icon svg code and as the menu is always in the dark mode regardless of the whole application so the svg icon has to always remain white in color. I hope this answers the questions. please let me know if I need to do more work on this code here

**Review by Chadha93 — APPROVED** [review]
LGTM, Thank you @AakashRaj20

**Comment by Chadha93** [comment]
Please link the issue from next time.

**Pull request merged**
