### PR TITLE
Integration Test Details: Wrong color and missing pass/fail icons

### LINKED ISSUE #5535: [Docs] Integration Test Details: Wrong color and missing pass/fail icons
#### Description
This page, https://docs.meshery.io/project/compatibility-matrix/meshery-traefik-mesh-past-results, needs to be updated to use the same colors defined on https://docs.meshery.io/project/compatibility-matrix and to use the same icons from https://docs.meshery.io/project/compatibility-matrix

Screen Shot 2022-05-24 at 10 15 50 AM

---

#### [Contributor Guides](https://docs.meshery.io/project/contributing) and Resources
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by karnatisrinivas**
Signed-off-by: karnatisrinivas <karnatisrinivasulareddy@gmail.com>

**Description**

This PR fixes #5535 

**Notes for Reviewers**
- **Present State**
Screenshot 2022-05-26 at 10 22 22 AM

- **Desired State (PR)**

Screenshot 2022-05-26 at 10 23 45 AM

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 7c37cb0983045758c155b1ecb26466b267f13151 at: https://628f0908c93cfc15746aed02--meshery-docs-preview.netlify.app

**Comment by leecalcote** [comment]
Same green as the integration test results page?

while you’re in there, @karnatisrinivas, will you use the custom check mark icons that can now be found on the compatibility matrix page?

**Comment by karnatisrinivas** [comment]
> Same green as the integration test results page?

> while you’re in there, @karnatisrinivas, will you use the custom checkmark icons that can now be found on the compatibility matrix page?

Yes, the PR utilizes the same colors as the Compatibility matrix page.

Custom check mark icons? Are you referring to the below icons?

Screenshot 2022-05-26 at 10 43 48 AM

**Comment by leecalcote** [comment]
Yes, @karnatisrinivas. You found them. 👍 

@asubedy engage here at-will.

**Comment by asubedy** [comment]
@karnatisrinivas Do you need any help here? I guess only the custom check marks icons are left on this PR. If there is something blocking you please say.

**Comment by warunicorn19** [comment]
@karnatisrinivas let's discuss this PR on the Meshery dev call tomorrow.

**Comment by l5io** [comment]
🚀 Preview for commit d6e1eb1ca6daaf7d7003eed578ad03f0a463683c at: https://6298434620686c3cd01ae34a--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 0e9f30f660e30c97f52408d48b73ade518f85163 at: https://62984444d415263e17e9a275--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 0513b679b89ab5b5ca8f0e34d20f8940547b0f1c at: https://629850e3130dd147caa22fde--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 67cf947432b24075ce6ba3a64abdcfaa3762e9dd at: https://629852bfadaad84a2b32df70--meshery-docs-preview.netlify.app

**Review by asubedy — APPROVED** [review]
LGTM, thank you @karnatisrinivas

**Pull request merged**
