### PR TITLE
Added service mesh Icons in Navigator

### PR DESCRIPTION
**Pull request by Harshit-Dandriyal**
Signed-off-by: Harshit Dandriyal <56961488+Harshit-Dandriyal@users.noreply.github.com>

**Notes for Reviewers**

This PR fixes #

Screenshot from 2022-12-02 20-26-31

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
@Harshit-Dandriyal thanks for fixing this. What was the root cause of this issue? "Where did the logos go?"

**Comment by Harshit-Dandriyal** [comment]
> @Harshit-Dandriyal thanks for fixing this. What was the root cause of this issue? "Where did the logos go?"

The icons where we fetching from just were not there, I don't know from when they are missing, it seems like an issue from a long time that no one was observed.

**Comment by Harshit-Dandriyal** [comment]
@leecalcote PR is good to be merged now.

**Review by leecalcote — APPROVED** [review]
LGTM

**Pull request merged**
