### PR TITLE
Utkarsh pro/UI/addons extraction

### PR DESCRIPTION
**Pull request by tangledbytes**
Signed-off-by: Utkarsh Srivastava <srivastavautkarsh8097@gmail.com>

**Description**
This PR adds a separate slider menu for addons

Relevant screenshorts:

new2

new

**[Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
@utkarsh-pro one item I overlooked in our conversation is the state whether any of these add-ons are present in the cluster or not (whether or not the switch should be on or off when the user navigates away and returns to the page). MeshSync v1 is discovering Prom and Graf, and we can quickly add discovery for the others. We will need to define the logic by which state of the switch is controlled.

For simple training purposes, we can assume that is a Prom or Graf is registered in Settings then that instance of Prom and/or Graf is the same instance being used by the given service mesh (adapter), however, this won't always be the case.

// @kalradev

**Comment by leecalcote** [comment]
@utkarsh-pro can we split this PR into two PRs so that the rearrangement of the namespace field and adapter chip can land while the MeshSync considerations are made in the meantime?

**Comment by utkarsh-pro** [comment]
> @utkarsh-pro can we split this PR into two PRs so that the rearrangement of the namespace field and adapter chip can land while the MeshSync considerations are made in the meantime?

@leecalcote, the rearrangement of namespace field and adapter chip was in my [previous PR](https://github.com/layer5io/meshery/pull/2069). This one only adds the switches to the addons. So we can hold this one until we have clarification on the meshsync thing?

**Comment by leecalcote** [comment]
Oooh. 😆, yes.

**Comment by leecalcote** [comment]
@utkarsh-pro this functionality is positioned to be the first to take advantage of MeshSync v2. Considering use of SSE, @kumarabd, what's the recommended approach to an endpoint that will expose this information?

**Comment by kumarabd** [comment]
> @utkarsh-pro this functionality is positioned to be the first to take advantage of MeshSync v2. Considering use of SSE, @kumarabd, what's the recommended approach to an endpoint that will expose this information?

One needed to be created here with GraphQL. Issue created for that - 

> @utkarsh-pro this functionality is positioned to be the first to take advantage of MeshSync v2. Considering use of SSE, @kumarabd, what's the recommended approach to an endpoint that will expose this information?

A new endpoint needs to be added for this purpose. Issue to track - https://github.com/layer5io/meshery/issues/2401

**Pull request closed without merging**
