### PR TITLE
[CI] Fix image path in meshmodel docs

### PR DESCRIPTION
**Pull request by gr455**
Signed-off-by: Ruturaj Mohite <mohite.ruturaj15@gmail.com>

**Notes for Reviewers**

This PR fixes #

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — COMMENTED** [review]
The color version should have `-color` in the name, @Revolyssup

**Comment by gr455** [comment]
> The color version should have `-color` in the name, @Revolyssup

This can be done. I just stayed consistent with how it was earlier

**Comment by leecalcote** [comment]
Oh, I see. Yes, let's follow this format - https://github.com/layer5io/layer5/tree/master/src/collections/integrations

**Comment by leecalcote** [comment]
There might need to be an update made to the component generator script.

**Comment by gr455** [comment]
> There might need to be an update made to the component generator script.

Alright, `-color` it is then

**Review by leecalcote — APPROVED** [review]
LGTM

**Pull request merged**
